fluent/fluent-bit

plugins/in_cpu/in_cpu.c
plugins/in_kmsg/in_kmsg.c
plugins/in_xbee/in_xbee.c

I got following error when building source code.
```
...
[ 86%] Building C object plugins/in_xbee/CMakeFiles/flb-plugin-in_xbee.dir/in_xbee.c.o
/home/syohei/work/fluent-bit/plugins/in_xbee/in_xbee.c:29:32: fatal error: fluent-bit/in_xbee.h: No such file or directory #include <fluent-bit/in_xbee.h>
```
That header file was moved.

Fix include paths

---

plugins/out_fluentd/out_fluentd.c

out_fluentd plugin causes following fd/socket leakage.
cb_flush_buf handler should close sockets it opened.
```
$ lsof -p 2705                                                                                                                                                                                                                         [1056/1953]
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/112/gvfs
Output information may be incomplete.
COMMAND    PID    USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
fluent-bi 2705 enukane  cwd    DIR    8,1     4096 817620 /home/enukane/Dev/fluent-bit/build
fluent-bi 2705 enukane  rtd    DIR    8,1     4096      2 /
fluent-bi 2705 enukane  txt    REG    8,1    56056 818517 /home/enukane/Dev/fluent-bit/build/bin/fluent-bit …
```

fix fd leak in out_fluentd

---

include/fluent-bit/flb_network.h
src/flb_network.c
src/flb_output.c

Implement IPv6 support.
```
$ ./fluent-bit -V -i cpu -o fluentd://[::1]:12224
Fluent-Bit v0.1.0
[2015/05/27 00:24:43] [ info] Configuration
flush time     : 5 seconds
input plugins  : cpu 
collectors     : [cpu 1s,0ns] 
[2015/05/27 00:24:43] [ info] starting engine
[2015/05/27 00:24:44] [debug] [in_cpu] CPU 1.00% (buffer=0)
[2015/05/27 00:24:45] [debug] [in_cpu] CPU 0.00% (buffer=1)
[2015/05/27 00:24:46] [debug] [in_cpu] CPU 0.00% (buffer=2)
[2015/05/27 00:24:47] [debug] [in_cpu] CPU 0.00% (buffer=3)
[2015/05/27 00:24:48] [ info] Flush buf 97 bytes
[2015/05/27 00:24:48] [debug] [in_cpu] CPU 0.00% (buffer=0)
[2015/05/27 00:24:49] [debug] [in_cpu] CPU 2.00% (buffer=1)
[2015/05/27 00:24:50] [debug] [in_cpu] CPU 0.00% (buffer=2)
[2015/05/27 00:24:51] [debug] …
```

IPv6 support

---

CMakeLists.txt
lib/msgpack-0.5.9/CMakeLists.txt
plugins/CMakeLists.txt
plugins/out_stdout/CMakeLists.txt
plugins/out_stdout/stdout.c
plugins/out_stdout/stdout.h

I implemented a new STDOUT Output Plugin.
I hope that it will assist debugging.
```
$ ./fluent-bit -i cpu -o stdout
Fluent-Bit v0.1.0
[2015/06/02 18:32:54] [ info] starting engine
[0] {"time"=>1433237575, "cpu"=>0.000000}
[1] {"time"=>1433237576, "cpu"=>0.000000}
[2] {"time"=>1433237577, "cpu"=>0.000000}
[3] {"time"=>1433237578, "cpu"=>0.000000}
[2015/06/02 18:32:59] [ info] Flush buf 96 bytes
[0] {"time"=>1433237579, "cpu"=>0.000000}
[1] {"time"=>1433237580, "cpu"=>0.000000}
[2] {"time"=>1433237581, "cpu"=>0.000000}
[3] {"time"=>1433237582, "cpu"=>0.000000}
[4] {"time"=>1433237583, "cpu"=>0.000000}
[2015/06/02 18:33:04] [ info] Flush buf 120 bytes
...
```
Note: An error has occurred that "libmsgpack.a is not a PIC format" in the process of generating a shared …

out_stdout: new STDOUT Output Plugin.

---

plugins/in_mem/in_mem.c

Sorry, cause of issue #6, was missing a set of size of msgpack data at in_mem_flush().
After the fix:
```
$ ./fluent-bit -i mem -o stdout
Fluent-Bit v0.1.0
[2015/06/03 10:49:16] [ info] starting engine
[0] {"time"=>1433296157, "total"=>501760, "free"=>220720}
[1] {"time"=>1433296158, "total"=>501760, "free"=>220720}
[2] {"time"=>1433296159, "total"=>501760, "free"=>220720}
[3] {"time"=>1433296160, "total"=>501760, "free"=>220720}
[2015/06/03 10:49:21] [ info] Flush buf 128 bytes
[0] {"time"=>1433296161, "total"=>501760, "free"=>220720}
[1] {"time"=>1433296162, "total"=>501760, "free"=>220720}
[2] {"time"=>1433296163, "total"=>501760, "free"=>220720}
[3] {"time"=>1433296164, "total"=>501760, "free"=>220720}
[4] {"time"=>1433296165, "total"=>501760, …
```

in_mem: fix overflow when reading in_mem generated msgpack maps #6

---

README.md

I added a description of in_mem and out_stdout plugins.
Signed-off-by: Masaya YAMAMOTO <pandax381@gmail.com>

Doc: update Input Plugins and Output Plugins

---

src/CMakeLists.txt

Fixed: Issue #9 
linking pthread library:
```
$ make
...
Linking C executable ../bin/fluent-bit
[ 81%] Built target fluent-bit-bin
Scanning dependencies of target fluent-bit-shared
[ 84%] Building C object src/CMakeFiles/fluent-bit-shared.dir/flb_pack.c.o
[ 86%] Building C object src/CMakeFiles/fluent-bit-shared.dir/flb_input.c.o
[ 89%] Building C object src/CMakeFiles/fluent-bit-shared.dir/flb_output.c.o
[ 92%] Building C object src/CMakeFiles/fluent-bit-shared.dir/flb_config.c.o
[ 94%] Building C object src/CMakeFiles/fluent-bit-shared.dir/flb_network.c.o
[ 97%] Building C object src/CMakeFiles/fluent-bit-shared.dir/flb_utils.c.o
[100%] Building C object src/CMakeFiles/fluent-bit-shared.dir/flb_engine.c.o
Linking C shared library ../library/libfluent-bit.so
[100%] Built target …
```

Build: fix failed to generate the executable file #9

---

lib/mk_core/mk_event_kqueue.c

Fixed timeout parameter given to EV_SET(EVFILT_TIMER) in some BSD.
Only FreeBSD (or LINUX_SECOND?) has NOTE_SECONDS defined and specify seconds
in EV_SET(EVFILT_TIMER). Other BSD (NetBSD, OpenBSD, DragonFlyBSD) requires milliseconds.
This caused 1000 times faster timeout & flushing.
I've tested this patch in NetBSD environment (on my netbsd-work branch).

mk_core: fix timeout given to EVFILT_TIMER in some BSD

---

include/fluent-bit/flb_network.h
lib/mk_core/mk_event_kqueue.c
plugins/out_fluentd/fluentd.c
plugins/out_td/td.c
src/CMakeLists.txt
src/flb_engine.c
src/flb_network.c

I wrote a patch to build on Mac OS X.
```
$ cmake -DWITH_IN_MEM=0 ../
-- The C compiler identification is AppleClang 6.0.0.6000054
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is AppleClang 6.0.0.6000054
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: …
```

Build: porting Mac OS X (and othrer BSD systems).

---

plugins/in_cpu/in_cpu.c
plugins/in_kmsg/in_kmsg.c
plugins/in_mem/in_mem.c

plugins/in_cpu: no longer flushes empty buffer
plugins/in_mem: no longer flushes empty buffer
plugins/in_kmsg: no longer flushes empty buffer
This changes avoid allocating and flushing unnecessary empty
buffers (size == 0). These also suppress error messages when
no updates in flush interval(typically every 5 seconds).
Signed-off-by: Takeshi HASEGAWA <hasegaw@gmail.com>

Input plugins: no longer flushes empty buffer

---

README.md

Doc: corrected cmake parameter -DWITH_IN_XBEE <- -DWITH_XBEE
Doc: Miscellaneous layout fixes
Signed-off-by: Takeshi HASEGAWA <hasegaw@gmail.com>

Doc: README.md updates

---

conf/xbee_input.conf
plugins/in_xbee/CMakeLists.txt
plugins/in_xbee/in_xbee.c
plugins/in_xbee/in_xbee.h
plugins/in_xbee/in_xbee_config.c
plugins/in_xbee/in_xbee_config.h

Updated version of XBee input plugin. Major changes:
- Now the plugin receives any broadcasted payloads over XBee
- Read parameters from a configuration file
Supported Format:
- [ time, { key => val, ... } ]
- [ { key => val, ... } ]
Signed-off-by: Takeshi HASEGAWA <<hasegaw@gmail.com>>

XBee input plugin update

---

plugins/in_serial/in_serial.c
plugins/in_serial/in_serial.h
plugins/in_xbee/CMakeLists.txt
plugins/in_xbee/in_xbee.c
plugins/in_xbee/in_xbee_config.c
plugins/in_xbee/in_xbee_config.h
plugins/in_xbee/in_xbee_iosampling.c
plugins/in_xbee/in_xbee_iosampling.h
plugins/in_xbee/in_xbee_utils.c
plugins/in_xbee/in_xbee_utils.h

Here's updated version of in_serial and in_xbee plugin.
in_serial plugin updates:
- Now functionable on MacOS X (and maybe on BSD variants)
- Use FD-based event for Linux, timer-based for other OSes
- Use non-blocking I/O
- Eliminated unnecessary data validation
- More several bugfixes and improvements
in_xbee:
- Added periodic I/O sampling packet support
- Resolved dead lock bug
- More several improvements

in_serial, in_xbee updates (2015-07-22)

---

lib/monkey/mk_core/include/mk_thread.h

```
[ 14%] Building C object lib/monkey/mk_core/CMakeFiles/mk_core.dir/mk_thread_channel.c.o
In file included from /Users/yamamoto-ma/LOCAL/src/fluent-bit/lib/monkey/mk_core/mk_thread_channel.c:25:
/Users/yamamoto-ma/LOCAL/src/fluent-bit/lib/monkey/mk_core/include/mk_thread.h:31:1: error: unknown type name 'pthread_key_t'; did you mean 'pthread_attr_t'?
pthread_key_t mk_thread_scheduler;
^~~~~~~~~~~~~
pthread_attr_t
/usr/include/sys/_pthread/_pthread_attr_t.h:30:33: note: 'pthread_attr_t' declared here
typedef __darwin_pthread_attr_t pthread_attr_t;
^
1 error generated.
make[2]: *** [lib/monkey/mk_core/CMakeFiles/mk_core.dir/mk_thread_channel.c.o] Error 1
make[1]: *** [lib/monkey/mk_core/CMakeFiles/mk_core.dir/all] Error 2
make: *** [all] Error 2
```
Signed-off-by: Masaya YAMAMOTO …

Build: fix build error on OSX with clang

---

include/fluent-bit/flb_input.h
include/fluent-bit/flb_output.h
src/flb_engine.c
src/flb_input.c
src/flb_output.c

Proposal to fix issue #23
Signed-off-by: Masaya YAMAMOTO &lt;pandax381@gmail.com&gt;

Engine: implement cb_exit callback for plugins

---

documentation/input/stdin.md
plugins/in_stdin/in_stdin.c
plugins/in_stdin/in_stdin.h

This adds a time field to each record from stdin input, if it doesn't exist.
Now data source can feed these formats.
- { map => val, map => val, map => val }
- [ time, { map => val, map => val, map => val } ]
Signed-off-by: Takeshi HASEGAWA <hasegaw@gmail.com>

in_stdin: Add a time field to each record if it does not exist.

---

plugins/in_serial/in_serial.c

1)
I noticed cb_exit callbacks are not called if I hit Ctrl-C.
This change adds signal handler to catch exit events to resolve the issue.
2)
in_serial plugin uses cb_exit to restore original termios.

cb_exit updates

---

examples/hello_world/hello_world.c

hello_world (not cpp) causes segfault.
backtrace
```
Program received signal SIGSEGV, Segmentation fault.
0x0000003e434081c3 in pthread_join () from /lib64/libpthread.so.0
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.166.el6_7.3.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x0000003e434081c3 in pthread_join () from /lib64/libpthread.so.0
#1  0x00002aaaaaac62ff in flb_lib_stop () from /home/(snip)/fluent-bit/build/library/libfluent-bit.so
#2  0x0000000000400c99 in main ()
(gdb) 
```
I think the segfault is caused by uninitialized ctx->config->worker.
So, I added initializing code, flb_lib_start(). It's similar to hello_world.cc.
test result
```
$ bin/hello_world
[2016/01/20 19:35:43] [ info] starting engine
[0] {"key"=>"val 0"}
[1] {"key"=>"val 1"}
[2] {"key"=>"val 2"} …
```

hello_world: Fixed segfault caused by flb_lib_stop()

---

src/flb_utils.c

The color of ']' is set to 'white_color' in flb_message().
It may be obscured on a white background.
I replaced 'white_color' to 'reset_color'.
And I removed unused variable 'white_color'.
Signed-off-by: nokute78 <nokute78@gmail.com>

utils: change the color of ] and remove unused variable

---

plugins/in_cpu/in_cpu.c

In proc_cpu_load(), a buffer 'line' is not released when return value of sscanf is less than 5. 
This patch is to check the buffer has been allocated. If so, it release the buffer on exit.
Signed-off-by: nokute78 <nokute78@gmail.com>

in_cpu: release buffer when sscanf returns small number

---

plugins/in_head/in_head.c
src/flb_engine.c

I added new code using high resolution interval (#48)
* Collector
Collector support high resolution interval.
We can pass 'nanoseconds' to flb_input_set_collector_time(). (it was not used.)
My patch makes the value applied in flb_engine_start().
* in_head
We can set interval which is less than 1 second.

Collector and in_head support high resolution interval (#48)

---

plugins/in_mqtt/mqtt.h
plugins/in_mqtt/mqtt_prot.c

To fix #63 
Received data is dropped when the buffer of in_mqtt is full.
Signed-off-by: nokute78 <nokute78@gmail.com>

in_mqtt: drop data when buffer is full (#63)

---

documentation/README.md

I fixed wrong URL of documentation.

Doc:fix URL

---

examples/out_lib/out_lib.c

I fixed memory leak.
User should release a buffer which passed from engine after using the buffer.

examples: release the buffer at user callback.

---

include/fluent-bit/flb_config.h
include/fluent-bit/flb_input.h
include/fluent-bit/flb_output.h
include/fluent-bit/flb_stats.h
include/fluent-bit/flb_tls.h
src/flb_config.c
src/flb_engine.c
src/flb_io.c
src/flb_output.c

I added prefix to HAVE_STATS, HAVE_HTTP and HAVE_TLS.
I checked like this.
```
$ find . -name "*.[ch]"|xargs grep HAVE_ |grep -v FLB_HAVE_ |grep -v lib
```

add missing prefix 'FLB_'

---

src/flb_input.c

If user passes NULL to flb_input_new as an input plugin name,
fluent-bit will be hangup at strlen() called from check_protocol().
I added NULL guard like flb_output_new().

input: add NULL guard to flb_input_new()

---

CMakeLists.txt
src/flb_lib.c
src/fluent-bit.c

I added mtrace(3) support.
mtrace(3) helps to reveal a buffer which is not released.
Build with -DFLB_DEBUG=Yes and -DFLB_MTRACE=Yes
``` sh
$ cmake .. -DFLB_DEBUG=Yes -DFLB_MTRACE=Yes
$ make
```
Execution with MALLOC_TRACE.
MALLOC_TRACE represents a file path to output tracing data.
``` sh 
$ MALLOC_TRACE=./trace.txt bin/fluent-bit -i cpu -o stdout
```
Analysis with mtrace(1).
On CentOS, glibc-utils package has mtrace(1).
``` sh
$ mtrace bin/fluent-bit trace.txt 
Memory not freed:
-----------------
Address     Size     Caller
0x0000000000c027b0     0x10  at /home/../fluent-bit/src/flb_log.c:37
0x0000000000c027d0      0xf  at 0x3a32681022
0x0000000000c027f0     0x14  at 0x3a3269cf82
0x0000000000c02810     0x14  at 0x3a3269cf82
0x0000000000c02830     0x15  at 0x3a3269cf82
0x0000000000c02850 …
```

Debug: add mtrace(3) support

---

src/flb_input.c
src/flb_output.c
src/fluent-bit.c

mtrace reports some leaks.
Amount of reports are different using -c option or not.
```
$ MALLOC_TRACE=./with_c.txt bin/fluent-bit -c ../conf/fluent-bit.conf
$ MALLOC_TRACE=./no_c.txt bin/fluent-bit -i cpu -o stdout
$ mtrace bin/fluent-bit with_c.txt |wc
51     195    5918
$ mtrace bin/fluent-bit no_c.txt |wc
11      35     452
```
It seems mk_rconf causes that leak.
mtrace reports that leak is generated at src/flb_input.c:150.
```
$ MALLOC_TRACE=./head.txt bin/fluent-bit -c ../conf/in_head.conf
$ mtrace bin/fluent-bit head.txt
<snip>
0x0000000001734730     0x20  at /home/.../fluent-bit/src/flb_input.c:150
0x0000000001734760      0x5  at 0x3a32681022
0x0000000001734780      0xd  at 0x3a32681022
0x00000000017347a0     0x20  at /home/.../fluent-bit/src/flb_input.c:150
0x00000000017347d0 …
```

Fix some leaks

---

plugins/in_mqtt/mqtt.c
src/flb_pack.c

mtrace reports flb_pack.c and mqtt.c are leaking.
I fixed these two leaks.
```
0x00eddaf0        0  at /home/pi/git/fluent-bit/plugins/in_mqtt/mqtt.c:78
0x00eddb00        0  at /home/pi/git/fluent-bit/plugins/in_mqtt/mqtt.c:78
0x00eddb10        0  at /home/pi/git/fluent-bit/plugins/in_mqtt/mqtt.c:78
0x00eddb20        0  at /home/pi/git/fluent-bit/plugins/in_mqtt/mqtt.c:78
0x00ede3c0   0x1000  at /home/pi/git/fluent-bit/src/flb_pack.c:189
0x00edf3c8   0x1000  at /home/pi/git/fluent-bit/src/flb_pack.c:189
0x00ee0818   0x1000  at /home/pi/git/fluent-bit/src/flb_pack.c:189
0x00ee1938   0x1000  at /home/pi/git/fluent-bit/src/flb_pack.c:189
```

[MQTT] fix leaks

---

plugins/in_head/in_head.c

Referring mtrace, sbuffer is leaked.
So, I added release code to in_head_exit() like in_cpu_exit().

in_head: release sbuffer at cb_exit

---

plugins/in_mqtt/mqtt.c
plugins/in_mqtt/mqtt_config.c

I added exit callback to in_mqtt.
However it causes double-free in the case of using in_mqtt.conf.
The root cause of double-free is here. (mqtt_config.c)
```c
/* Listen interface (if not set, defaults to 0.0.0.0) */
if (!i_ins->host.listen) {
listen = flb_input_get_property("listen", i_ins);
if (listen) {
config->listen = listen;
}
else {
config->listen = strdup("0.0.0.0");
}
}
```
flb_input_get_property() returns the part of prop list which will be freed at flb_input_exit_all().
So, I duplicated it with strdup() to prevent double-free at in_mqtt_exit().

[mqtt] add exit callback

---

src/flb_config.c

I added a code to release http_port.
http_port was static pointer (=FLB_CONFIG_HTTP_PORT).
On the other hand ,it was allocated at fluent-bit.c.
So, I use strdup to make http_port freeable.

config: release http_port string

---

src/flb_config.c

#83 is wrong patch.
We should release http_port (not  http_server)

config: release http_port

---

plugins/in_forward/fw_config.c

Freeing config->listen causes segfault.
In some cases, input property 'listen' is used as config->listen.
config->listen is freed at fw_config_destroy().
However, property is also freed at flb_input_exit_all().
1. Execute fluent-bit using in_forward.conf
2. Ctrl+c
```
$ bin/fluent-bit -c ../conf/in_forward.conf 
Fluent-Bit v0.9.0
[2016/07/22 18:19:06] [ info] starting engine
[2016/07/22 18:19:06] [ info] [in_fw] binding 0.0.0.0:24224
^C[engine] caught signal
*** glibc detected *** bin/fluent-bit: corrupted double-linked list: 0x00000000018a79e0 ***
======= Backtrace: =========
/lib64/libc.so.6[0x3a32675f3e]
/lib64/libc.so.6[0x3a326763c3]
/lib64/libc.so.6[0x3a32678d68]
bin/fluent-bit[0x48f682]
bin/fluent-bit(mk_event_loop_destroy+0x2c)[0x48fcf3] …
```

in_forward: duplicate 'listen' to prevent double free

---

README.md

I updated readme.
* add in_forward and out_http
* rename out_forward
* add Quick Start section
'Quick Start' makes fluent-bit more attractive.
It will be easier for user and developer to try to use fluent-bit.
(Old 'Build' section helped me to try fluent-bit and contribute.)

Readme: Update plugin information and add Quick Start

---

include/fluent-bit/flb_error.h

refer #87 
I converted octal error code into decimal.
I checked this simple code and all codes were unique.
``` c
#include <fluent-bit/flb_error.h>
int main(void)
{
int error[] = {
FLB_ERR_CFG_FILE,
FLB_ERR_CFG_FILE_FORMAT,
FLB_ERR_CFG_FLUSH,
FLB_ERR_CFG_FLUSH_CREATE,
FLB_ERR_CFG_FLUSH_REGISTER,
FLB_ERR_INPUT_INVALID,
FLB_ERR_INPUT_UNDEF,
FLB_ERR_INPUT_UNSUP,
FLB_ERR_OUTPUT_UNDEF,
FLB_ERR_OUTPUT_INVALID,
FLB_ERR_OUTPUT_UNIQ,
-1,
};
int i=0;
while( error[i++] > 0 ){
printf("%d\n",error[i]);
}
return 0;
}
```
```
$ bin/test
11
20
21
22
50
51
52
100
101
102
-1
```

error: convert octal error code into decimal

---

tests/flb_test_fluentd.cpp

I updated test code of out_forward.
* fix plugin name
"fluentd" -> "forward"
* add sentinel value
To notify the end of va_list with NULL as a sentinel value.
* replace "tag" to "match".
According to Routing, We should pass "match" to flb_output_set().

test: replace fluentd to foward

---

include/fluent-bit/flb_output.h
src/flb_output.c
src/fluent-bit.c

I added a code to check output plugin name.(like checking input plugin name.)
If user sets undefined output plugin name (e.g. '-o aaa'), 
fluent-bit reports an error that output target is invalid.
```
$ bin/fluent-bit -i cpu -o aaa
Error: Invalid output target. Aborting
```

ouput: report error message if user sets undefined output plugin

---

tests/CMakeLists.txt
tests/flb_test_in_cpu.cpp

I add a new test program to test `in_cpu`.
test case is 
1. start `in_cpu`
2. wait 2 sec
3. check flushed data. We expect there is no data flushed.
4. wait 3 sec
5. check flushed data. We expect cpu data is flushed.
``` sh
$ bin/flb_test_in_cpu 
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Inputs
[ RUN      ] Inputs.flush_5s
[2016/08/05 22:36:06] [ info] starting engine
[2016/08/05 22:36:11] [ warn] [engine] service will stop in 5 seconds
[2016/08/05 22:36:16] [ info] [engine] service stopped
[       OK ] Inputs.flush_5s (9773 ms)
[----------] 1 test from Inputs (9773 ms total)
[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (9773 ms total)
[ …
```

tests: add new test to check in_cpu plugin

---

tests/flb_test_elasticsearch.cpp
tests/flb_test_stdout.cpp
tests/flb_test_td.cpp

I modified all of test codes.
* add sentinel value 'NULL' to prevent segfault
* rename output property 'tag' to 'match'

test: rename property and add sentinel value NULL

---

tests/CMakeLists.txt

I modified `tests/CMakeLists.txt` to build only enabled plugin.
e.g. if `-DFLB_OUT_STDOUT=No`, executable `flb_test_stdout` is not generated.

build: modify CMakeLists.txt to test only enabled plugin.

---

tests/CMakeLists.txt
tests/flb_test_in_mem.cpp

I added new test code.
test case is 
1. start in_cpu
2. wait 2 sec
3. check flushed data. We expect there is no data flushed.
4. wait 3 sec
5. check flushed data. We expect cpu data is flushed.
``` sh
$ ./flb_test_in_mem 
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Inputs
[ RUN      ] Inputs.flush_5s
[2016/08/10 21:13:17] [ info] starting engine
[2016/08/10 21:13:22] [ warn] [engine] service will stop in 5 seconds
[2016/08/10 21:13:27] [ info] [engine] service stopped
[       OK ] Inputs.flush_5s (9445 ms)
[----------] 1 test from Inputs (9445 ms total)
[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (9445 ms total)
[  PASSED  ] 1 test.
``` …

tests: add test code for in_mem

---

tests/CMakeLists.txt
tests/flb_test_engine.cpp

I added new test code.
This program is testing these routing configuration ( which comes from #67 )
``` c
test_wildcard_fmt checklist[] =
{
{"cpu.rpi","cpu.rpi", true  },
{"cpu.rpi","cpu.ard", false },
{"cpu.rpi","cpu.*",   true  },
{"cpu.rpi","*",       true  },
{"cpu.rpi","*.*",     true  },
{"cpu.rpi","*.rpi",   true  },
{"cpu.rpi","mem.*",   false },
{"cpu.rpi","*u.r*",   true  },
{NULL, NULL, 0}
};
```

tests: add new test for routing

---

include/fluent-bit/flb_task.h

`flb_task.h` includes `flb_thread.h`.
And `flb_thread_*.h` defines `struct  flb_thread` which contains `struct flb_task` which is defined at `flb_task.h`
So, pre-processing is 
1. `flb_task.h` includes `flb_thread.h`
2. `struct flb_thread` is defined. (`flb_task` is not defined at this time. ) at `flb_thread_*.h`
3. `struct flb_task` is defined at `flb_task.h`
Step2 causes build error.

build: fix Travis CI error

---

include/fluent-bit/flb_config.h
include/fluent-bit/flb_lib.h
src/flb_config.c
src/flb_lib.c
tests/flb_test_engine.cpp

I added a new API `flb_service_set` for library mode.
User can set  global properties of the service with new API. (e.g. Flush)
I updated a test code `flb_test_engine.cpp` with new API to shorten flush time.

lib: add new API flb_service_set(flb_ctx_t *ctx, ...)

---

include/fluent-bit/flb_task_map.h
src/flb_task.c

Refer to Valgrind, the size of `flb_config` is about 33KB.
```
$ valgrind --tool=massif bin/fluent-bit -i cpu -o stdout
.
$ ms_print massif.out.7631 
.
->55.89% (33,120B) 0x41334B: flb_config_init (in /home/taka/git/oss/pull_req/fluentbit_env/fluent-bit/build/bin/fluent-bit)
| ->55.89% (33,120B) 0x41092E: main (in /home/taka/git/oss/pull_req/fluentbit_env/fluent-bit/build/bin/fluent-bit)
.
```
It is caused by this member. 
``` c
struct flb_task_map tasks_map[2048];
```
`flb_task_map` is like this.
``` c
struct flb_task_map {
uint8_t id;
void    *task;
};
```
So, the size of array `tasks_map` is (8 + 8) *2048= 32.7KB.
By the way, the value `id` is used like `bool`.
So, I deleted `id` to reduce memory usage.

task: reduce memory usage

---

plugins/in_kmsg/in_kmsg.c

Refer to mtrace, sbuffer is leaked when fluent-bit catches Ctrl+C before flushing.

in_kmsg: release sbuffer at cb_exit

---

src/flb_config.c

I fixed `flb_config.c`
* Preventing illegal access(CID 152995)
I used wrong pointer type, so my code breaks memory when user sets `http_port` or `buffer_path`.
I fixed to use proper pointer.
* Releasing pointer before overwriting(also CID 152995)
If user sets `http_port` or `buffer_path` twice or more, previous pointer is not released.
* Preventing releasing non-pointer.
`http_server` is boolean, however it is released at `flb_config_exit`

Clean up flb_config.c

---

src/CMakeLists.txt
src/flb_output.c
src/flb_task.c

I fixed these issues which is happened when `FLB_BUFFERING` is No.
* Compilation error which is caused `flb_buffer_qchunk.c`
I fixed not to use source code and variable which need to define `FLB_BUFFERING`.
* Segfault 
`ins->tls.context` is initialized if `(p->flags & FLB_IO_TLS)` is true.
So, I fixed the value is released when the condition is same.

Fix compilation error and segfault which is happened when FLB_BUFFERING is No.

---

src/flb_lib.c

`flb_test_engine` is failed in two test cases.
```C
{"cpu.rpi","cpu.ard", false },
{"cpu.rpi","mem.*",   false },
```
I fixed looking for an output instance at `out_instance_get`.

lib: fix looking for output instance

---

tests/flb_test_td.cpp

I fixed `flb_test_td.cpp` to be able to compile when using new API.

tests: migrate test of td to new API

---

.travis.yml

Sorry, #119 is not a proper patch.
I added `cd build` command before executing cmake.

ci: add cd command before cmake

---

plugins/out_forward/forward.c

To fix #125.
In some cases, sbuffer is not released at `cb_forward_flush`
@edsiper could you review this patch?

out_forward: release sbuffer before FLB_OUTPUT_RETURN

---

src/flb_scheduler.c

Bitwise Operation is faster than pow().

sched: replace pow() with bitwise operation

---

plugins/in_cpu/in_cpu.c

I fixed to prevent 0 byte allocation.

in_cpu: do not allocate if data size is 0

---

CMakeLists.txt
README.md
conf/out_flowcounter.conf
plugins/CMakeLists.txt
plugins/out_flowcount/CMakeLists.txt
plugins/out_flowcounter/CMakeLists.txt
plugins/out_flowcounter/out_flowcounter.c
plugins/out_flowcounter/out_flowcounter.h

Counting plugin was renamed out_flowcount**er** ( I added "er" )
I misunderstood @kzk 's comment of #130
Sorry and Thanks @kzk !

flowcounter: rename flowcount to flowcounter (add er)

---

conf/in_head.conf
plugins/in_head/in_head.c
plugins/in_head/in_head.h

I added a new option "add_path" to display file path.
Using like this.
`$ bin/fluent-bit -i head -p file=/proc/uptime -p add_path=true -o stdout`
In this case, "path"=>"/proc/uptime" is appended with this option.
```
$ bin/fluent-bit -i head -p file=/proc/uptime -p add_path=true -o stdout
[2016/11/23 22:31:29] [ info] [engine] started
[0] head.0: [1479907890, {"head"=>"237197.57 226881.09
", "path"=>"/proc/uptime"}]
[1] head.0: [1479907891, {"head"=>"237198.57 226882.00
", "path"=>"/proc/uptime"}]
```

head: add new option to display file path to read

---

plugins/in_tcp/tcp.c
plugins/in_tcp/tcp_config.c

I fixed in_tcp.
* prevent allocating 0byte at cb_flush.
* add missing release code.
* add release code when initialize failed.

cleanup in_tcp

---

src/flb_input.c

I added releasing code.
If cb_init of input network plugin failed, some resources allocated at flb_input_new are not released.
I tested with in_tcp.
```
$ cmake .. -DFLB_MTRACE=yes -DFLB_DEBUG=yes
$ make
$ MALLOC_TRACE=./hoge.txt bin/fluent-bit -i tcp:/123.123.123.123 -o stdout # dummy address
[2016/12/09 21:57:26] [ info] [engine] started
[2016/12/09 21:57:26] [error] Error binding socket
[2016/12/09 21:57:26] [ warn] Cannot listen on 23.123.123.123 port 5170
[2016/12/09 21:57:26] [error] [in_tcp] could not bind address 23.123.123.123:5170. Aborting
[2016/12/09 21:57:26] [error] Failed initialize input tcp.0
^C[engine] caught signal
```
```
$ mtrace bin/fluent-bit hoge.txt 
Memory not freed:
-----------------
Address     Size     Caller …
```

input: release resources when cb_init failed

---

plugins/in_forward/fw.c

I added a code to release resources which allocated at fw_config_init.

in_forward: release resources when binding failed

---

include/fluent-bit/flb_log.h

I added NULL checking.
Log output causes segfault before `flb_log_init` is called.
Because `flb_worker_ctx` is indefinite in that case, it is defined at flb_log_init.

log: add flb_worker_ctx validation

---

plugins/out_flowcounter/out_flowcounter.c

I modified output format of out_flowcounter to append timestamp.
I referenced a format of `out_stdout`.
```
$ bin/fluent-bit -i cpu -o flowcounter -p unit=second
[2016/12/12 22:26:13] [ info] [engine] started
[out_flowcounter] cpu.0:[1481549174, {"counts":1, "bytes":126, "counts/second":1, "bytes/second":126 }]
[out_flowcounter] cpu.0:[1481549175, {"counts":1, "bytes":126, "counts/second":1, "bytes/second":126 }]
[out_flowcounter] cpu.0:[1481549176, {"counts":1, "bytes":126, "counts/second":1, "bytes/second":126 }]
```
```
$ bin/fluent-bit -i cpu -o flowcounter -p unit=second
[2016/12/12 22:28:52] [ info] [engine] started
[out_flowcounter] cpu.0:{"counts":1, "bytes":126, "counts/second":1, …
```

out_flowcounter: add timestamp to output record

---

src/flb_output.c

Engine allocates tls.context in spite of  property 'tls=false'.
My patch is to reduce memory usage not to allocate these structure (about 3KB).
```
->06.82% (2,744B) 0x422B4E: flb_malloc (in /home/taka/git/oss/pull_req/fluentbit_env/tmp/fluent-bit/build/bin/fluent-bit)
| ->06.82% (2,744B) 0x4230EA: flb_tls_context_new (in /home/taka/git/oss/pull_req/fluentbit_env/tmp/fluent-bit/build/bin/fluent-bit)
|   ->06.82% (2,744B) 0x419999: flb_output_init (in /home/taka/git/oss/pull_req/fluentbit_env/tmp/fluent-bit/build/bin/fluent-bit)
|     ->06.82% (2,744B) 0x41DB28: flb_engine_start (in /home/taka/git/oss/pull_req/fluentbit_env/tmp/fluent-bit/build/bin/fluent-bit)
|       ->06.82% (2,744B) 0x41632C: main (in /home/taka/git/oss/pull_req/fluentbit_env/tmp/fluent-bit/build/bin/fluent-bit) …
```

output: do not allocate tls.context if tls=false

---

include/fluent-bit/flb_config.h
src/flb_config.c
src/fluent-bit.c

I moved logfile settings to be configurable with file.
We can set `logfile` with configuration file like this.
```
[SERVICE]
logfile ./log.txt
Flush        5
HTTP_Monitor Off
[INPUT]
Name cpu
Tag  cpu.local
[OUTPUT]
Name  stdout
Match **
```

bin: make logfile configurable with configuration file

---

plugins/in_health/health.c

in_health causes segfault if hostname is not given.
I fixed it.
```
$ bin/fluent-bit -i health -o stdout
Segmentation fault
```

in_health: prevent segfault when hostname is not given

---

src/flb_input.c

Refer to documentation about in_health, we can set property 'Host' and 'Port'.
However, they can't be set with command line option and configuration file.
http://fluentbit.io/documentation/0.9/input/health.html
I fixed them.
We can set like this with this PR.
```
$ bin/fluent-bit -i health -p host=google.com -p port=80 -o stdout
[2016/12/22 21:34:35] [ info] [engine] started
[0] health.0: [1482410076, {"alive"=>true}]
```
And with configuration file.
```
[INPUT]
Name health
Tag  cpu.local
host google.com
port 80
[OUTPUT]
Name  stdout
Match **
```
```
$ bin/fluent-bit -c fluent-bit.conf 
[2016/12/22 21:35:33] [ info] [engine] started
[0] cpu.local: [1482410134, {"alive"=>true}]
```

input: 'Host' and 'Port' are configurable with flb_input_set_property

---

plugins/out_flowcounter/out_flowcounter.c
plugins/out_flowcounter/out_flowcounter.h

This PR is to fix #155.
This is a sample output with in_cpu (output every seconds) and in_random(output every 5 seconds).
Then "counts" is 2 in every 5 seconds. (others are 1).
```
$ bin/fluent-bit -i cpu -t hoge -i random -p interval_sec=5 -t hoge -o flowcounter -p unit=second -m '*'
[2017/01/07 23:07:40] [ info] [engine] started
[out_flowcounter] [1483798060, {"counts":0, "bytes":0, "counts/second":0, "bytes/second":0 }]
[out_flowcounter] [1483798061, {"counts":1, "bytes":126, "counts/second":1, "bytes/second":126 }]
[out_flowcounter] [1483798062, {"counts":1, "bytes":126, "counts/second":1, "bytes/second":126 }]
[out_flowcounter] [1483798063, {"counts":1, "bytes":126, "counts/second":1, "bytes/second":126 }]
[out_flowcounter] [1483798064, …
```

out_flowcounter: multiple input support(#155)

---

plugins/in_proc/in_proc.c
plugins/in_proc/in_proc.h

I add a new function to collect memory usage of "each process".
This is a sample. It reports memory usage of `bash`
```
ent-Bit v0.11.0
[2017/01/14 23:43:31] [ info] [engine] started
[0] proc.0: [1484405012, {"alive"=>true, "proc_name"=>"bash", "pid"=>13344, "mem.VmPeak"=>114796000, "mem.VmSize"=>114796000, "mem.VmLck"=>0, "mem.VmHWM"=>4092000, "mem.VmRSS"=>2868000, "mem.VmData"=>2568000, "mem.VmStk"=>88000, "mem.VmExe"=>852000, "mem.VmLib"=>1988000, "mem.VmPTE"=>84000, "mem.VmSwap"=>920000}]
```
These values are come from `/proc/[pid]/status`.
```
$ cat /proc/13344/status 
Name:	bash
.
.
VmPeak:	  114796 kB
VmSize:	  114796 kB
VmLck:	       0 kB
VmHWM:	    4092 kB
VmRSS:	    2868 kB
VmData:	    2568 kB
VmStk:	      88 kB
VmExe:	     852 kB
VmLib:	    1988 kB …
```

in_proc: add function to collect memory usage of process

---

examples/out_lib/out_lib.c
include/fluent-bit/flb_pack.h
plugins/out_lib/out_lib.c
plugins/out_lib/out_lib.h
src/flb_pack.c

I added a generic converting function flb_msgpack_to_json.
Now, we have 3 different functions to convert msgpack to JSON.
(at out_http, out_nats, out_es)
Duplicate code is hard to maintain.
The new function is similar to snprintf.
We can pass 3 args, str_ptr, length of pointer, and msgpack data.
`int flb_msgpack_to_json(char* json_str, size_t str_len, msgpack_unpacked* data)`
It returns a number of characters filled or negative value if error happened.
If return value is larger than str_len, it means buffer is small.
So, user should re-allocate bigger buffer and retry to convert.
I pushed a patch to make out_lib using new function.
@edsiper 
Could you review and check this new function?
If you say OK, I will replace legacy converting function.

Add a function to convert msgpack to JSON

---

plugins/in_proc/in_proc.c
plugins/in_proc/in_proc.h

I added a new function to count file descriptors.
It is useful to check fd leak.
```
$ bin/fluent-bit -i proc -p proc_name=fluent-bit -p fd=true -p mem=false -o stdout
[2017/01/22 21:21:02] [ info] [engine] started
[0] proc.0: [1485087663, {"alive"=>true, "proc_name"=>"fluent-bit", "pid"=>3188, "fd"=>18}]
[1] proc.0: [1485087664, {"alive"=>true, "proc_name"=>"fluent-bit", "pid"=>3188, "fd"=>18}]
[2] proc.0: [1485087665, {"alive"=>true, "proc_name"=>"fluent-bit", "pid"=>3188, "fd"=>18}]
[3] proc.0: [1485087666, {"alive"=>true, "proc_name"=>"fluent-bit", "pid"=>3188, "fd"=>18}]
```
fluent-bit read `/proc/[PID]/fd` and count up file descriptors.
```
$ ls -lt /proc/`pidof fluent-bit`/fd |wc
18     206    1127
```

in_proc: add new function to count file decriptors

---

include/fluent-bit/flb_lib.h
src/flb_lib.c

I added API for filter plugin.
It is similar to API for input/output plugin.
```C
filter_ffd = flb_filter(ctx, "stdout", NULL);
flb_filter_set(ctx, filter_ffd, "match", "*", NULL);
```
sample code is
https://gist.github.com/nokute78/67712ad25cbf829d12f4c1dece842ab7
```
$ bin/out_lib 
[2017/02/02 22:13:25] [ info] [engine] started
[0] test: [1486041206, {"cpu_p"=>0.000000, "user_p"=>0.000000, "system_p"=>0.000000, "cpu0.p_cpu"=>0.000000, "cpu0.p_user"=>0.000000, "cpu0.p_system"=>0.000000}]
[0] test: [1486041207, {"cpu_p"=>7.000000, "user_p"=>6.000000, "system_p"=>1.000000, "cpu0.p_cpu"=>7.000000, "cpu0.p_user"=>6.000000, "cpu0.p_system"=>1.000000}]
[0] test: [1486041208, {"cpu_p"=>4.000000, "user_p"=>2.000000, "system_p"=>2.000000, "cpu0.p_cpu"=>4.000000, "cpu0.p_user"=>2.000000, …
```

lib: add new library API for filter plugin

---

include/fluent-bit/flb_filter.h
src/flb_engine.c
src/flb_filter.c

I added a cleanup function `flb_filter_exit` for filter plugin like input/output plugin.
Could you review it?

filter: add cleanup function

---

plugins/in_lib/in_lib.c

One of #173 
I tested with this code.
https://gist.github.com/nokute78/40529577fffdaa93c0af4dabf75fe933
```
$ bin/hello_world
[0] test: [1486388712, {"key"=>"val 0"}]
[1] test: [1486388712, {"key"=>"val 1"}]
[2] test: [1486388712, {"key"=>"val 2"}]
[3] test: [1486388712, {"key"=>"val 3"}]
[4] test: [1486388712, {"key"=>"val 4"}]
.
.
.
[94] test: [1486388712, {"key"=>"val 94"}]
[95] test: [1486388712, {"key"=>"val 95"}]
[96] test: [1486388712, {"key"=>"val 96"}]
[97] test: [1486388712, {"key"=>"val 97"}]
[98] test: [1486388712, {"key"=>"val 98"}]
[99] test: [1486388712, {"key"=>"val 99"}]
[2017/02/06 22:45:12] [ info] [engine] started
[2017/02/06 22:45:22] [ warn] [engine] service will stop in 5 seconds
[2017/02/06 22:45:27] [ info] [engine] service stopped
```

in_lib: filter plugin support (#173)

---

plugins/in_random/random.c

One of #173 
I fixed like this
```
$ bin/fluent-bit -i random  -o null -F stdout -m '*'
[2017/02/06 22:31:20] [ info] [engine] started
[0] random.0: [1486387881, {"rand_value"=>12615723256373713967}]
[0] random.0: [1486387882, {"rand_value"=>10210476662233778806}]
```

in_random: filter plugin support (#173)

---

plugins/in_proc/in_proc.c

One of #173 
I fixed like this
```
$ bin/fluent-bit -i proc -p proc_name=fluent-bit  -o null -F stdout -m '*'
[2017/02/06 22:25:34] [ info] [engine] started
[0] proc.0: [1486387535, {"alive"=>true, "proc_name"=>"fluent-bit", "pid"=>20353, "mem.VmPeak"=>15396000, "mem.VmSize"=>15396000, "mem.VmLck"=>0, "mem.VmHWM"=>1164000, "mem.VmRSS"=>1164000, "mem.VmData"=>2276000, "mem.VmStk"=>88000, "mem.VmExe"=>2416000, "mem.VmLib"=>2328000, "mem.VmPTE"=>64000, "mem.VmSwap"=>0, "fd"=>18}]
[0] proc.0: [1486387536, {"alive"=>true, "proc_name"=>"fluent-bit", "pid"=>20353, "mem.VmPeak"=>15396000, "mem.VmSize"=>15396000, "mem.VmLck"=>0, "mem.VmHWM"=>1208000, "mem.VmRSS"=>1208000, "mem.VmData"=>2276000, "mem.VmStk"=>88000, "mem.VmExe"=>2416000, …
```

in_proc: filter plugin support (#173)

---

plugins/in_health/health.c

One of #173 
I fixed like this
```
$ bin/fluent-bit -i health://google.com:80  -o null -F stdout -m '*'
[2017/02/06 22:22:29] [ info] [engine] started
[0] health.0: [1486387350, {"alive"=>true}]
[0] health.0: [1486387351, {"alive"=>true}]
```

in_health: filter plugin support (#173)

---

plugins/in_head/in_head.c

One of #173 
I fixed like this
```
$ bin/fluent-bit -i head -p file=/proc/uptime -o null -F stdout -m '*'
[2017/02/06 22:18:16] [ info] [engine] started
[0] head.0: [1486387097, {"head"=>"647217.91 617385.81\x0a"}]
[0] head.0: [1486387098, {"head"=>"647218.91 617386.73\x0a"}]
```

in_head: filter plugin support (#173)

---

plugins/in_disk/in_disk.c

One of #173 
I fixed like this.
```
$ bin/fluent-bit -i disk -o null -F stdout -m '*'
[2017/02/06 22:14:35] [ info] [engine] started
[0] disk.0: [1486386876, {"read_size"=>0, "write_size"=>0}]
[0] disk.0: [1486386877, {"read_size"=>0, "write_size"=>110592}]
```

in_disk: filter plugin support (#173)

---

plugins/in_mem/mem.c

One of #173 
I fixed like this.
```
$ bin/fluent-bit -i mem -o null -F stdout -m '*'
[2017/02/06 22:09:21] [ info] [engine] started
[0] mem.0: [1486386562, {"total"=>1016044, "free"=>277188}]
[0] mem.0: [1486386563, {"total"=>1016044, "free"=>277188}]
```

in_mem: filter plugin support (#173)

---

include/fluent-bit/flb_regex.h

Travis CI reports that macOS can't compile fluent-bit.
https://travis-ci.org/fluent/fluent-bit/jobs/198991560
It is because there is no definition of `ssize_t` and it is defined with unistd.h or sys/types.h.

regex: include unistd.h for BSDs and macOS

---

plugins/out_flowcounter/out_flowcounter.c

I fixed out_flowcounter which counts between wrong duration.

out_flowcounter: fix checking duration(#184)

---

src/flb_config.c
src/flb_lib.c
src/flb_log.c

Hi, I found small issues about initializing and try to fix them.
I added changes below;
- NULL checking for flb_log_init()
- free pointer if flb_worker_create() is failed
Could you review it?

log: fix memory leaks in the error case

---

include/fluent-bit/flb_input.h
include/fluent-bit/flb_output.h
include/fluent-bit/flb_plugins.h.in
include/fluent-bit/flb_thread_libco.h
include/fluent-bit/flb_thread_pthreads.h
include/fluent-bit/flb_thread_ucontext.h

To fix #190 
I fixed NON-inline functions which are implemented header.
If the header is included, the function is implemented at a file and libfluent-bit.so and they are conflicted.

include: add FLB_INLINE to implemented functions

---

tests/flb_test_in_proc.cpp

Hi, I found an small issue about test failure for in_proc plugin.
The root cause was;
- No considered NULL checking for property "proc_name"
Could you review it?

tests: fix fails of test for in_proc plugin

---

plugins/in_tail/tail_config.c
plugins/in_tail/tail_config.h
plugins/in_tail/tail_file.c

I added a new option "add_path_field" to in_tail plugin. (see also #206)
If it is true, in_tail appends a file path to each record.
This is a case to read 3 files.
```
[taka@localhost build]$ cat sample/a.txt 
aaa
[taka@localhost build]$ cat sample/b.txt 
bbb
[taka@localhost build]$ cat sample/c.txt 
ccc
ddd
```
So, the command is 
```
$ fluent-bit -i tail -p 'path=sample/*.txt' -p add_path_field=true -o stdout
```
Result is 
```
$ bin/fluent-bit -i tail -p 'path=sample/*.txt' -p add_path_field=true -o stdout
[2017/03/04 21:34:28] [ info] [engine] started
[0] tail.0: [1488630868, {"path"=>"sample/a.txt", "log"=>"aaa"}]
[1] tail.0: [1488630868, {"path"=>"sample/b.txt", "log"=>"bbb"}]
[2] tail.0: [1488630868, {"path"=>"sample/c.txt", …
```

in_tail: add new option 'path_key" to append a filepath to each record

---

include/fluent-bit/flb_time.h
plugins/out_counter/counter.c
src/flb_time.c

This is a Step2 to support nanosecond.(#193)
I updated out_counter to support nanosecond.
I also added new timer API.
* to convert double from flb_time.
* to get current flb_time.

out_counter: nanosecond support

---

CMakeLists.txt
plugins/CMakeLists.txt
plugins/filter_record_modifier/CMakeLists.txt
plugins/filter_record_modifier/filter_modifier.c
plugins/filter_record_modifier/filter_modifier.h

I added new filter plugin "filter_record_modifier".
It is based on https://github.com/repeatedly/fluent-plugin-record-modifier.
This plugin is to filter and append key-value pair.
It supports
* remove_key (if matched, removed the key-val)
* whitelist_key (if NOT matched, removed the key-val)
* record (append the record)
This is a example to edit a record from in_mem.
The original format is
```
{"Mem.total"=>1016024, "Mem.used"=>758792, "Mem.free"=>257232, "Swap.total"=>2064380, "Swap.used"=>7780, "Swap.free"=>2056600}
```
To remove "Mem.total" with removed_key, we can set the property like this.
```
[INPUT]
Name mem
Tag  cpu.local
[OUTPUT]
Name  stdout
Match *
[FILTER]
Match *
remove_key Mem.total
```
And output is (Mem.total is removed!)
```
$ bin/fluent-bit -c …
```

filter_record_modifier: add new plugin

---

plugins/out_plot/plot.c

refer to #193 
This PR is to support nanosecond for out_plot.
```
$ bin/fluent-bit -i random -o plot -F stdout -m '*'
[2017/04/17 21:19:43] [ info] [engine] started
[0] random.0: [(ext: 0)"X\xf4\xb2\xe0\x00\x09\x9e\xd1", {"rand_value"=>12035555825123622030}]
[0] random.0: [(ext: 0)"X\xf4\xb2\xe1\x00\x0c\xbdR", {"rand_value"=>10163745917373870873}]
[0] random.0: [(ext: 0)"X\xf4\xb2\xe2\x00\x02\xc2\xc6", {"rand_value"=>9931370750710165450}]
[0] random.0: [(ext: 0)"X\xf4\xb2\xe3\x00\x07O\xd8", {"rand_value"=>11017442887508247469}]
[0] random.0: [(ext: 0)"X\xf4\xb2\xe4\x00\x1dIO", {"rand_value"=>17451077018934266832}]
```
This is an output of out_plot.
```
$ cat random.0 
1492431584.000630 12035555825123622030
1492431585.000835 …
```

out_plot:nanosecond support

---

plugins/filter_stdout/stdout.c

This PR is to support nanosecond for filter_stdout.
This is a sample output.
```
$ bin/fluent-bit -i random -o stdout -F stdout -m '*'
[2017/04/17 21:27:44] [ info] [engine] started
[0] random.0: [1492432065.000872449, {"rand_value"=>18018567782972291650}]
[0] random.0: [1492432066.000194421, {"rand_value"=>4834213566149347330}]
[0] random.0: [1492432067.000505875, {"rand_value"=>18194037506161953329}]
[0] random.0: [1492432068.000892927, {"rand_value"=>10508887116319800125}]
[0] random.0: [1492432065.000872449, {"rand_value"=>18018567782972291650}]
[1] random.0: [1492432066.000194421, {"rand_value"=>4834213566149347330}]
[2] random.0: [1492432067.000505875, {"rand_value"=>18194037506161953329}]
[3] random.0: [1492432068.000892927, …
```

filter_stdout: nanosecond support(#193)

---

src/flb_time.c

I fixed wrong calculation.
e.g. 
nsec1 = 10, nsec0 = 90.
result of nanosecond should be 999999920. (1000000000 + 10 - 90.)
(and  decrement second).

time: fix wrong calculation

---

CMakeLists.txt

This helps in doing cross compiles for modules which are using
GNU autoconf for build system
Signed-off-by: Khem Raj <raj.khem@gmail.com>

CMakeLists.txt: Add AUTOCONF_HOST_OPT to help cross compiling

---

plugins/in_tail/tail.c
plugins/in_tail/tail_config.c

I fixed in_tail cleanup functions.
* Modified to call flb_tail_config_destroy() at exit callback.
* Modified to call flb_tail_db_close.
* Fixed port number.

in_tail: fix cleanup functions

---

plugins/out_file/file.c
plugins/out_file/file.h

This PR is to support csv output file format.
I added new properties "format" and "delimiter".
configuration file is
```python
[INPUT]
Name mem
Tag  mem.usage
[OUTPUT]
Name file
Match *
Path  mem.csv
Format csv
#Delimiter \t
[FILTER]
Name stdout
Match *
```
```sh
$ bin/fluent-bit -c file.conf 
[2017/04/21 23:16:16] [ info] [engine] started
[0] mem.usage: [1492784177.002298028, {"Mem.total"=>3920464, "Mem.used"=>2001032, "Mem.free"=>1919432, "Swap.total"=>2064380, "Swap.used"=>0, "Swap.free"=>2064380}]
[0] mem.usage: [1492784178.000651208, {"Mem.total"=>3920464, "Mem.used"=>2001204, "Mem.free"=>1919260, "Swap.total"=>2064380, "Swap.used"=>0, "Swap.free"=>2064380}]
[0] mem.usage: [1492784179.001232752, {"Mem.total"=>3920464, …
```

out_file: support csv format

---

lib/flb_libco/ppc.c

This software currently does not built on Power due to duplicated
function.
lib/flb_libco/ppc.c:282:12: error: conflicting types for 'co_create'
cothread_t co_create(unsigned int size, void (*entry_)(void)) {
lib/flb_libco/libco.h:19:12: note: previous declaration of 'co_create' was here
cothread_t co_create(unsigned int, void (*)(void), size_t *);
This is happening because commit
b2bb2227cd2712df1946c438ec733b5956e9ecd8 forgot to change the function
name on ppc source code.
Signed-off-by: Breno Leitao <breno.leitao@gmail.com>

lib: flb_libco: Fix ppc64 function arguments

---

tests/flb_test_file.cpp

Hi, I found a small issue about test failure for out_file plugin.
The root cause was;
- sometimes the test ends before flushing
Could you review it?

tests: fix the test ends before flushing

---

tests/flb_test_file.cpp

Hi, I added new 3 tests of  out_file plugin to support csv and ltsv format.
Could you confirm this change?

tests: add tests of out_file plugin for supporting new formats

---

plugins/out_forward/forward.c

out_forward: replace msgpack_pack_bin with str

---

plugins/out_plot/plot.c
tests/CMakeLists.txt
tests/flb_test_counter.cpp
tests/flb_test_exit.cpp
tests/flb_test_flowcounter.cpp
tests/flb_test_null.cpp
tests/flb_test_plot.cpp
tests/flb_test_retry.cpp
tests/flb_test_stdout.cpp

Hi, I added new tests for out plugin the below.
- counter
- flowcounter
- exit
- null
- plot
- retry
Also, I fixed a bug of out_plot plugin found by these unit tests.
Could you confirm this change?

Add out plugin tests (counter, flowcounter, exit, null, plot, retry)

---

plugins/in_tail/tail_config.c

'path_key' option is broken with latest commit.
This PR is to fix it.

in_tail: fix missing option 'path_key'

---

examples/out_lib/out_lib.c
include/fluent-bit/flb_lib.h
plugins/out_lib/out_lib.c
src/flb_lib.c

Now, out_lib releases the buffer after invoking callback to avoid difference of malloc engine.
However, this approach may cause some bugs.
e.g. User stores the data at callback and reads it at other thread. On the thread, the buffer is already released.
So, I added a new library API to release the buffer of out_lib.
It helps to avoid difference of malloc engine and also user can handle the lifecycle of the buffer.

out_lib: releasing buffer at user side

---

src/flb_io_tls.c

Support adding SNI headers to the tls connection being created. This lets us use the headers for stuff like load balancing

Add SNI headers

---

plugins/filter_record_modifier/filter_modifier.c
plugins/filter_record_modifier/filter_modifier.h

With some OS, the cast from int to string of -1 is 377. 
In that case the loop ` for(i=0; bool_map[i] >= 0; i++)` is infinite.
This fix add a cast of -1 to be sure to compare the -1 stored as string in bool_map with a -1 cast in string too. ` for(i=0; bool_map[i] != (char)-1; i++)`
Signed-off-by: Loris Bererd <bererd.loris@gmail.com>

filter_record_modifier: cast -1 from int to string for loop condition test

---

plugins/out_es/es.c

timespec.tv_nsec is 'long' (signed 32/64 bit integer).
out_es converts timestamp like this.
```c
len = snprintf(time_formatted + s, sizeof(time_formatted) - 1 - s,
".%" PRIu64 "Z", tms.tm.tv_nsec);
```
On 32bit system (e.g. raspberry pi 2), it may cause wrong conversion. 
It is a sample code.
```c
#include <stdint.h>
#include <inttypes.h>
int main(void)
{
long val = 10;
printf("val=%" PRIu64 "\n", val);
printf("val=%" PRIu64 "\n", (uint64_t)val);
return 0;
}
```
And output on raspberry pi 2 is
```
pi@raspberrypi /tmp $ ./a.out
val=145721776104988
val=10
```

out_es: modify converting timestamp

---

plugins/filter_record_modifier/filter_modifier.c

Now, if user removes all key-value pairs with filter_record_modifier, all key-value pairs remain.
This PR is to fix it.
Using this configuration file, the output should be blank.
```
[INPUT]
Name disk
Tag  disk
[OUTPUT]
Name stdout
Match *
[FILTER]
Match *
Remove_key read_size
Remove_key write_size
```
However, no pairs are removed.
```
$ bin/fluent-bit -c test.conf 
[2017/06/07 22:52:12] [ info] [engine] started
[0] disk: [1496843533.001570594, {"read_size"=>0, "write_size"=>0}]
[1] disk: [1496843534.002714136, {"read_size"=>0, "write_size"=>0}]
[2] disk: [1496843535.002754669, {"read_size"=>0, "write_size"=>0}]
[3] disk: [1496843536.002622451, {"read_size"=>0, "write_size"=>221184}]
```

filter_record_modifier: fix handling empty msgpack

---

conf/in_head.conf
plugins/in_head/in_head.c
plugins/in_head/in_head.h

feature request #299.
I added "key" option to in_head.
It makes to be able to change the key name of in_head.
```python
[INPUT]
Name head
File /proc/meminfo
Key  meminfo
Tag  head.meminfo
[OUTPUT]
Name stdout
Match *
```
result is this. key is renamed as "meminfo". 
"meminfo"->"..."
```shell
[2017/06/17 12:54:25] [ info] [engine] started
[0] head.meminfo: [1497671666.001193509, {"meminfo"=>"MemTotal:        3920464 kB
MemFree:          392792 kB
Buffers:          180328 kB
Cached:          2658532 kB
SwapCached:            8 kB
Active:          1601776 kB
Inactive:        1487980 kB
Active(anon):      98456 kB
Inactive(anon):   156756 kB
Acti"}]
```

in_head: add key property

---

conf/in_head.conf
plugins/in_head/in_head.c
plugins/in_head/in_head.h

I added a new mode "lines" of in_head to fix #294.
It works like "$ head -n"
The new property "lines" is needed.
```python
[INPUT]
Name head
File /proc/meminfo
Lines 5
Tag  head.meminfo
[OUTPUT]
Name stdout
Match *
```
in_head reads 5 (=property "Lines 5") lines each iteration.
```shell
$ bin/fluent-bit -c head.conf 
[2017/06/15 22:54:57] [ info] [engine] started
[0] head.meminfo: [1497534898.001409355, {"head"=>"MemTotal:        3920464 kB"}]
[1] head.meminfo: [1497534898.001422557, {"head"=>"MemFree:          373088 kB"}]
[2] head.meminfo: [1497534898.001423877, {"head"=>"Buffers:          184648 kB"}]
[3] head.meminfo: [1497534898.001425171, {"head"=>"Cached:          2675856 kB"}]
[4] head.meminfo: [1497534898.001426330, …
```

in_head: add lines mode like $ head -n

---

CMakeLists.txt
README.md
plugins/CMakeLists.txt
plugins/filter_parser/CMakeLists.txt
plugins/filter_parser/filter_parser.c
plugins/filter_parser/filter_parser.h

I added a new plugin filter_parser.
It parses records at filter plugin.
I got a nginx log from 
https://raw.githubusercontent.com/elastic/examples/master/ElasticStack_NGINX/nginx_logs
This example is to parse record which is generated  by in_head.
```
[SERVICE]
Parsers_File /home/taka/git/oss/pull_req/fluentbit_env/fluent-bit/conf/parsers.conf
[INPUT]
Name head
file /home/taka/git/oss/pull_req/fluentbit_env/fluent-bit/build/nginx.log
line 1
[FILTER]
Name parser
Match *
Key_Name head
Parser nginx
[OUTPUT]
Name stdout
Match *
```
```
$ bin/fluent-bit -c dummy.conf  
[2017/06/24 00:23:23] [ info] [engine] started
[0] head.0: [1498231404.001205864, {"remote"=>"93.180.71.3", "host"=>"-", "user"=>"-", "method"=>"GET", …
```

filter_parser: add new plugin filter_parser

---

plugins/out_flowcounter/out_flowcounter.c
plugins/out_flowcounter/out_flowcounter.h

Now , out_flowcounter is based on timestamp of each event.
However, first timestamp comes from timestamp of host which executes fluent-bit.
So, the difference (event time and host timestamp) causes range error.
I added new mode 'event_based'.
If it is true, the plugin uses timestamp of each event(as usual)
If it is false, the plugin uses host timestamp only (Default, to fix #311)

out_flowcounter: add new mode 'event_based' (#311)

---

README.md

I modified README.md
* add in_dummy
* remove in_xbee (deprecated)

README: add in_dummy and remove in_xbee

---

include/fluent-bit/flb_parser.h
src/flb_parser.c
src/flb_parser_regex.c

to support #308 
I added 'types' feature of parser like fluentd.
note: http://docs.fluentd.org/v0.12/articles/parser_regexp#types
We can define data types at parsers.conf.
The syntax is 
```
types <field_name_1>:<type_name_1> <field_name_2>:<type_name_2> ...
```
Now these type_names are supported.
* integer
* float
* bool
```
[PARSER]
Name dummy_test
Format regex
Regex ^(?<INT>[^ ]+) (?<FLOAT>[^ ]+) (?<BOOL>[^ ]+) (?<STRING>[^ ]+)$
Types INT:integer FLOAT:float BOOL:bool
```
Try to parse `"100 12.1 true strings"`
```
[SERVICE]
Parsers_File /home/taka/git/oss/pull_req/fluentbit_env/fluent-bit/build/parsers.conf
[INPUT]
Name dummy
dummy {"test":"100 12.1 true strings"}
[FILTER]
Name parser
Match *
Key_Name test
Parser dummy_test
[OUTPUT]
Name stdout
Match *
```
```
$ bin/fluent-bit -c …
```

parser: support 'types' feature

---

src/flb_env.c

When there is a variable used in the configuration with some text
following it, like `${VAR}-additional-text`, the additional text is not
carried over in the result. This is caused by accidentally overwriting
the variable holding the length of the original string and not copying
the remaining parts of the value into the buffer.

env: fix insertion of non variable parts in result

---

include/fluent-bit/flb_pack.h
plugins/filter_parser/filter_parser.c
plugins/filter_parser/filter_parser.h
src/flb_pack.c

To implement feature request ("reserve_data" #307) 
This option is to save key-value pairs which are not parsed.
This is an example to treat record ` {"data":"100 0.5 true This is example", "hoge":"moge"}`
`"data":"100 0.5 true This is example"` will be parsed and fluent-bit will generate parsed key-value pairs.
If "Reserve_data true", fluent-bit will save other key-value pair (in this case, `"hoge":"moge"`).
```
[SERVICE]
Parsers_File /home/taka/git/oss/pull_req/fluentbit_env/fluent-bit/build/reserve_data_parser.conf
[INPUT]
Name dummy
Tag  dummy.data
Dummy {"data":"100 0.5 true This is example", "hoge":"moge"}
[FILTER]
Name parser
Match dummy.*
Key_Name data
Parser dummy_test
Reserve_data true
[OUTPUT]
Name stdout
Match *
```
parser file is 
```
[PARSER]
Name dummy_test
Format regex …
```

filter_parser: support "reserve_data" 

---

src/flb_parser.c

Parser supports `types` and default type is `string`.
But explicit definition `string` causes warning.
This PR is to suppress the warning message.
parsers.conf is 
```python
[PARSER]
Name dummy_test
Format regex
Regex ^(?<INT>[^ ]+) (?<FLOAT>[^ ]+) (?<BOOL>[^ ]+) (?<message>.+)$
Types INT:integer FLOAT:float BOOL:bool message:string
```
The `message:string` causes the warning.
The configuration file is
```python
[SERVICE]
Parsers_File /home/taka/git/oss/pull_req/fluentbit_env/fluent-bit/build/parsers.conf
[INPUT]
Name dummy
Tag  dummy.data
Dummy {"data":"100 0.5 true This is example"}
[FILTER]
Name parser
Match dummy.*
Key_Name data
Parser dummy_test
[OUTPUT]
Name stdout
Match *
```
The warning message is
```
$ bin/fluent-bit -c dummy.conf  …
```

parser: fix to handle types 'string'

---

plugins/filter_parser/filter_parser.c

I fixed a memory leak of filter_parser when "reserve_data" is true

filter_parser:fix leak CID 166134

---

plugins/filter_kubernetes/kube_meta.c

* Extract `nodeName` from spec and stick it in as
` host` in the result.
`fluent-plugin-kubernetes_metadata_filter` has this and fluent-bit's kubernetes filter does not. Hence, the request.

filter_kubernetes: Add kubernetes host of the pod in the record

---

plugins/filter_kubernetes/kube_conf.c
plugins/filter_kubernetes/kube_conf.h
plugins/filter_kubernetes/kube_meta.c

Signed-off-by: Kushal Bhandari <kushwiz@gmail.com>
This option is required to specify is TLS verify is required or not because in cases where the CA certificates of the cluster are not verified or the chain is incomplete the filter_kubernetes would not work.

filter_kubernetes: new tls_verify option

---

plugins/in_systemd/systemd.c
plugins/in_systemd/systemd_config.c

When ``DB`` parameter is used to store the last cursor, each new start
process as the first entry the one pointed by the stored cursor.
This change checks for each entry if cursor is the same as the one
stored and skip if it is true.

in_systemd: skip last journald entry already processed

---

plugins/in_systemd/systemd_config.c

New configuration option to allow to start processing Journald only new
entries.

in_systemd: configuration option to start reading from tail

---

conf/parsers.conf

- Fix field naming connection-> context
- Fix field naming context -> component
- Add an optional "ms" field that will be the Microseconds the query took to execute (won't be there if it's not a COMMAND)
- ref: https://docs.mongodb.com/manual/reference/log-messages/

Update [PARSER] for mongodb (parser.conf)

---

conf/parsers.conf

The pattern will match docker daemon logs usually saved in `/var/log/docker.log`:
```
time="2017-10-22T12:33:52Z" level=warning msg="Running experimental build"
time="2017-10-22T12:33:52.467735758Z" level=info msg="libcontainerd: new containerd process, pid: 30587"
time="2017-10-22T12:33:53.469642684Z" level=warning msg="failed to rename /mnt/data/docker/tmp for background deletion: %!s(<nil>). Deleting synchronously"
time="2017-10-22T12:33:53.479675410Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2017-10-22T12:33:53.480678652Z" level=info msg="Loading containers: start."
time="2017-10-22T12:33:53.867581187Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP …
```

conf: parser: add docker-daemon pattern

---

include/fluent-bit/flb_parser.h
src/flb_parser.c

This patch is to convert hexadecimal string to unsigned integer.
e.g. `"hex":"0xff"` -> `"hex":255`
Some logs contain hexadecimal value.
e.g. 
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security_Guide/sec-Understanding_Audit_Log_Files.html
This patch is to convert these strings.
parsers.conf
```
[PARSER]
Name dummy_test
Format regex
Regex ^(?<INT>[^ ]+) (?<FLOAT>[^ ]+) (?<BOOL>[^ ]+) (?<HEX_VAL>[^ ]+) (?<message>.+)$
Types INT:integer FLOAT:float BOOL:bool HEX_VAL:hex
```
conf 
```
[SERVICE]
Parsers_File /home/taka/git/oss/pull_req/fluentbit_env/fluent-bit/build/parsers.conf
[INPUT]
Name dummy
dummy {"test":"100 12.1 true 0xff strings"}
[FILTER]
Name parser
Match *
Key_Name test
Parser dummy_test
[OUTPUT]
Name stdout
Match *
```
output . "HEX_VAL" is …

parser: support hexadecimal format

---

plugins/in_disk/in_disk.c
plugins/in_dummy/in_dummy.c
plugins/in_forward/fw.c
plugins/in_head/in_head.c
plugins/in_health/health.c
plugins/in_kmsg/in_kmsg.c
plugins/in_lib/in_lib.c
plugins/in_lib/in_lib.h
plugins/in_netif/in_netif.c
plugins/in_proc/in_proc.c
plugins/in_random/random.c
plugins/in_stdin/in_stdin.c
plugins/in_stdin/in_stdin.h
plugins/in_tcp/tcp.c
plugins/out_td/td.c
plugins/out_td/td_config.c
tests/runtime/flb_test_file.c
tests/runtime/flb_test_plot.c

Hi,
I found an issue in the case of runtime tests in multi-thread execution.
Plot and file tests are sometimes failed because conflicted by accessing the same file name.
For example;
```
ctest -j 8
```

tests: runtime: out_plot, out_file: fix conflicts by accessing the same file name

---

plugins/filter_kubernetes/kube_conf.c
plugins/filter_parser/filter_parser.c
plugins/filter_record_modifier/filter_modifier.c

Check context is not NULL when tearing down a filter. This prevents a
segmentation fault if the filter has not been initialized yet.
This is possible when an output plugin fails to initialize - the engine
will shutdown the server before the filters have chance to be
initialized.
Signed-off-by: James Ravn <james@r-vn.org>

filter: check context is not NULL

---

CMakeLists.txt
plugins/CMakeLists.txt
plugins/in_exec/CMakeLists.txt
plugins/in_exec/in_exec.c
plugins/in_exec/in_exec.h

in_exec is to gather event from other programs.
This is an example to collect an output of `ps`
```
$ fluent-bit  -i exec -p command=ps  -o stdout
```
output is 
```
Fluent-Bit v0.13.0
[2017/11/01 23:44:28] [ info] [engine] started
[0] exec.0: [1509547469.121841165, {"exec"=>"  PID TTY          TIME CMD"}]
[1] exec.0: [1509547469.121849714, {"exec"=>" 4256 pts/1    00:00:00 fluent-bit"}]
[2] exec.0: [1509547469.121850349, {"exec"=>" 4258 pts/1    00:00:00 ps"}]
[3] exec.0: [1509547469.121850836, {"exec"=>" 6484 pts/1    00:00:05 bash"}]
[4] exec.0: [1509547469.121851308, {"exec"=>"31606 pts/1    00:00:31 emacs"}]
```
in_exec supports parser.
This is an example to parse the output of `ps`
Parser file is
```
[PARSER]
Name ps
Format regex
Regex …
```

[WIP] add new plugin in_exec

---

src/flb_http_client.c

The prior calculation was incorrectly shrinking the buffer when it
reached its limit, leading to data corruption.
Here's an example of what the buffer was resizing to (with added debug
statement):
[2017/11/02 10:56:00] [ info] [filter_kube] testing connectivity with
API server...
resizing http buffer to 28672
resizing http buffer to 4096
resizing http buffer to 28672
resizing http buffer to 4096
Segmentation fault (core dumped)
This is for a max_size of 32768.
I've changed the calculation to cap to the max_size, and return -1 if the buffer has already been realloc'd to the cap.
Signed-off-by: James Ravn <james@r-vn.org>

http_client: fix buffer new_size calculation

---

tests/runtime/CMakeLists.txt
tests/runtime/filter_kubernetes.c

Add a couple tests checking JSON merging of the Kubernetes filter plugin. I wrote these trying to debug an issue with missing logs, but couldn't reproduce (the tests pass). Anyways, I think it will be useful to have some k8s filter tests.

filter_kubernetes: add tests for merged json

---

include/fluent-bit/flb_hash.h
plugins/filter_kubernetes/kube_conf.c
src/flb_env.c
src/flb_hash.c
tests/internal/hashtable.c

The hashtable is being used as a cache for kubernetes metadata and
environment variables. The drawback is the hashtable is unbounded and
doesn't resize itself. Thus over time it uses more memory and
performance becomes worse as the chains get longer.
For Kubernetes this can be particularly bad in busy environments as the
cache key uses podname, which will change every time a deployment
occurs.
By bounding the hashtable we ensure memory doesn't become unbounded and
performance remains constant. For a cache it should be okay to evict
old entries.
This implementation tries to keep things simple by performing eviction
on adding a key to the table. As long as the hashtable size isn't
exceeded, the behaviour remains the same as before - the table is looked
up via hash function, and the table …

hash: bound the hashtable size

---

plugins/filter_kubernetes/kube_conf.c
plugins/filter_kubernetes/kube_conf.h
plugins/filter_kubernetes/kube_meta.c

This addresses my actual concern here in issue #422. I think this is a good starting point in allowing users to decide what metadata to include. What do you guys think?

Allow user to decide whether they want to include annotations in Kubernetes filter

---

plugins/out_es/CMakeLists.txt
plugins/out_es/es.c
plugins/out_es/es.h
plugins/out_es/es_bulk.h
plugins/out_es/es_conf.c
plugins/out_es/murmur3.c
plugins/out_es/murmur3.h

So that retries won't cause duplicate records in ES.
Adds option 'Generate_ID' that when set to yes generates a unique ID per record.
For https://github.com/fluent/fluent-bit/issues/423

out_es: add option to generate uuid

---

plugins/in_tail/tail.c
plugins/in_tail/tail_config.c
plugins/in_tail/tail_signal.h

When paused under heavy load, it is possible for the pending pipe to
fill up and then block - causing the entire fluent-bit process to
block/hang. This is due to adding a pending signal for every file, instead
of just one single signal. Similarly, every inotify event can also fill the pending pipe.
Fix is to use nonblocking mode for the pending pipe, and clear it out after all pending files are processed.

in_tail: Avoid blocking on pending pipe

---

plugins/in_disk/in_disk.c
plugins/in_disk/in_disk.h
plugins/in_netif/in_netif.c
plugins/in_netif/in_netif.h

I hava find that the in_netif plugin use prev and now to indicate the previous and current correct value.
At the first collect, the prev is not exist. I think the first correct should not output, and should just assign now to prev. It should begin to output from the second collect.
So I add a feild first_snapshot to indicate current collect is the first fo not to control.
The same of in_disk.
This is reference to
How to solve Large log file leading to some input plugin abnormal #464

in_disk and in_netif: Fix the first output uncorrect of input plugin

---

plugins/filter_parser/filter_parser.c
plugins/filter_parser/filter_parser.h
tests/runtime/CMakeLists.txt
tests/runtime/filter_parser.c

Fix reserve_data which was segfaulting due to multiple parser patch.
This was due to not handling the exit of the parse loop to preserve
existing records.
Add `preserve_key` option so we can also choose to preserve the original
key field, along with `reserve_data`.
Add tests to cover the various scenarios, including time key parsing.

filter_parser: fix reserve_data, add preserve_key

---

plugins/in_tail/tail_file.c

`file->buf_data` should have been `data`, which was missed in 98e86523.

in_tail: fix process_content when FLB_REGEX is false

---

plugins/out_http/http.c
plugins/out_http/http.h

In the existing implementation the "date" key is hardcoded.
This defaults to the existing key of "date" to ensure backwards compatibility.

out_http: Add configuration for the date key when output is JSON

---

plugins/in_tail/tail.c
plugins/in_tail/tail_file.c

Otherwise new files may never get ingested if heavy log volume is
causing frequent pauses.
This should be safe since no ingestion happens during scan and rotate.
Fix https://github.com/fluent/fluent-bit/issues/465

in_tail: don't pause scan/rotate

---

plugins/filter_record_modifier/filter_modifier.c
plugins/filter_record_modifier/filter_modifier.h

Allow matching of Remove_key by wildcard after some prefix.
Example: -F record_modifier -p 'Remove_key=example*'
Allow matching of Whitelist_key by wildcard after some prefix.
Example: -F record_modifier -p 'Wildcard_key=example*'
This change may break some existing config if a key's final character is '*'.

filter_record_modifier: Support wildcard for Remove_key and Whitelist_key

---

CMakeLists.txt
plugins/CMakeLists.txt
plugins/filter_throttle/CMakeLists.txt
plugins/filter_throttle/throttle.c
plugins/filter_throttle/throttle.h
plugins/filter_throttle/window.c
plugins/filter_throttle/window.h
tests/runtime/CMakeLists.txt
tests/runtime/filter_throttle.c

This is more advanced throttling mechanism based on https://github.com/fluent/fluent-bit/pull/410
There is a window of some size, if interval is not set it defaults to 1 second, otherwise it got parsed by similar to GNU/sleep parser. 
This interval is window pane, we slide one pane at interval, and calculate average over entire window. We also have a slow start, to prevent overflowing at the beginning of the window.
Basically rate of 100 with window of `5` with interval set to `1m` is different than rate of 3 with window 300 and interval of 1s, because in first example it is possible to get all 100 messages in first second, while second one, will accept only 3 and wait for the next second to accept the rest. 
We have this working in production for more than 3 months, and everything is …

Sliding window throttling implementation

---

conf/parsers_cinder.conf
conf/parsers_extra.conf
conf/parsers_openstack.conf

I was not sure whether to contribute to parsers.conf directly but finally I follow the current practice add additional files that are not enabled by default.
Default parsers enabled has a reasoning if they are really general, thus format/time match most of the platforms.
Log_time regex, as well as some other parts, could be written better, but instead of expensive re-do I am keeping this for others to update as needed.

Additional parsers spec.

---

tests/runtime/core_engine.c
tests/runtime/filter_parser.c
tests/runtime/in_cpu.c
tests/runtime/in_disk.c
tests/runtime/in_dummy.c
tests/runtime/in_head.c
tests/runtime/in_mem.c
tests/runtime/in_proc.c
tests/runtime/in_random.c

out_lib api was updated and it broke some runtime tests.
(Now, we should pass `struct flb_lib_out_cb` to out_lib_init)
I fixed some tests to use new api.

fix SIGSEGV of runtime tests

---

src/flb_parser.c
tests/runtime/filter_parser.c

This change allows to use `%L` format option after `%s` in addition to already existing `%S`.
Essentially this allows to parse unix timestamp followed by microseconds (`1509575121.648`).
This is useful because not all systems are capable of logging with sub-second precision in human readable form. Nginx is a good example of such case, neither of [`$time_iso8601`](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_time_iso8601) or [`$time_local`](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_time_local) will include milliseconds. However, [`$msec`](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_msec) does write a unix timestamp with milliseconds resolution (`1509575121.648`), hence by adding support for `%s.%L` it would be possible to parse nginx logs …

Support fractional seconds with UNIX timestamp

---

plugins/in_kmsg/in_kmsg.c
plugins/in_tcp/tcp_conn.c

I noticed funny timestamps when collecting kernel messages using fluent-bit. The fix turned out to be straight-forward.

Fix timestamp in in_kmsg

---

include/fluent-bit/flb_parser_decoder.h
src/flb_parser_decoder.c

This adds a parser decoder that unescapes JSON-safe UTF8 escaped strings.
Example input,
{"log":"\u0009\u0009Starting app ..\n","stream":"stdout","time":"2018-02-19T23:25:31.0679529Z"}
File `main.conf`,
[SERVICE]
Parsers_File fluent-bit-parsers.conf
[INPUT]
Name        tail
Parser      docker
Path        /path/to/log.log
[OUTPUT]
Name   stdout
Match  *
File `fluent-bit-parsers.conf`
[PARSER]
Name        docker
Format      json
Time_Key    time
Time_Format %Y-%m-%dT%H:%M:%S %z
Decode_Field_as escaped_utf8 log

Add parser decoder for escaped utf8 strings

---

plugins/filter_kubernetes/kubernetes.c

In case the message didn't come from a pod, we would leak the message.

Kubernetes filter: Fix memory leak

---

plugins/out_http/http.c
plugins/out_http/http.h

This PR adds support for the ISO8601 timestamp format to the `http` output plugin.
The immediate purpose for this is to be able to have Loggly recognize log timestamps: Loggly requires messages to have a field named `timestamp` in this format. Otherwise it uses the ingestion timestamp instead of the timestamp in the original log message.
This new format is optional -- the original `double` format is kept as the default.
To use the new format, specify it like this:
```
Json_Date_Key    timestamp
Json_Date_Format iso8601
```
@brandoncole This might be of interest to you.

out_http: Support ISO8601 format for json date

---

Dockerfile

In commit 7584ee58 (@edsiper), the path conf/parsers_mult.conf was added to the Dockerfile. However, that path doesn't exist in the repo (but conf/parsers_extra.conf does).

Fix reference to nonexistent path (introduced in commit 7584ee5)

---

conf/parsers.conf

The user-agent comes from the client and we cannot prevent \" within it, so certain entries wont be parsed.
User-Agent is the last column in access.log so we cannot miss anything afterwards anyways.
eg. x.x.x.x - - [16/Apr/2018:16:19:20 +0000] "POST /myURL HTTP/1.1" 200 8073 "-" "Dalvik/2.1.0 (Linux; U; Android 5.1; Alba 10\" Build/LMY47I)"

Apache2 Parser config: Allow \" in the user-agent

---

plugins/out_http/http.c
plugins/out_http/http.h

This is an attempt to provide a simple option that allows JSON logs to be sent to services that require each log entry be on a separate line.  An example is Loggly.  Currently testing this do no not merge yet but would love some feedback from anyone interested.
This is to address the items mentioned in #579 
```
outputs.conf: |
[OUTPUT]
Name            http
Match           *
Host            logs-01.loggly.com
Port            443
URI             /bulk/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/tag/testing/
Format          json_lines
tls             On
tls.verify      On
```
This closes #579

Additional json_lines Format for HTTP Output

---

plugins/out_http/http.c
plugins/out_http/http.h

The http plugin currently not sending the message's tag. The in_http
plugin of Fluentd use the URI as tag. If we want to keep the original
tag then we have to define multipe output section per tag to map it to
URI. This change send the tag in a header(the headername can define in
config file), and it's up to the receiver to parse the header and
replace the tag.
The use case is to use this plugin in place of SecureForward plugin
because it's easier to maintain and config terminating TLS at load balancer
level, which probably a part of infrastructure already, comparing
with maintain TLS per fluentd instance.

out_http: Pass tag dynamically in header

---

plugins/in_systemd/systemd.c

`ns = us * 1000` - nanoseconds are smaller than microseconds.
Signed-off-by: Mike Kaplinskiy <mike@ladderlife.com>

in_systemd: fix nanosecond timestamp calculation

---

plugins/in_systemd/systemd_config.c

The docs seems to point to these being ANDs. You can always use multiple inputs to create ORs.

in_systemd: treat multiple filters as ANDs, not ORs

---

plugins/out_splunk/splunk.c
plugins/out_splunk/splunk.h
plugins/out_splunk/splunk_conf.c

This patch adds a new toggle for the Splunk HTTP Event Collector output
plugin to allow users to specify index, sourcetype and other top level
fields when sending data to splunk.  The current behaviour sends data to
the main index by default.
When enabling the feature, the user must take care to put all log
details in the event field, and only specify fields known to splunk in
the top level event.
Example:
Splunk_Send_Raw Off
{"time": .., "event": {"k1": "foo", "k2": "bar", "index": "applogs"}}
Splunk_Send_Raw On
{"time": .., "k1": "foo", "k2": "bar", "index": "applogs"}
For up to date information about the valid keys in the top level object,
refer to the splunk documentation:
http://docs.splunk.com/Documentation/Splunk/latest/Data/AboutHEC
The patch has been tested using Splunk 6.6.1 …

out_splunk: Allow user to send raw message by setting Splunk_Send_Raw On

---

scripts/test.lua

Recently, we changed the format of filter_lua, JSON -> Lua table.
So, we also need to modify cb_print to handle Lua table.
Now, cb_print doesn't output contents of table.
```shell
$ bin/fluent-bit -i mem -F lua -p script=../scripts/test.lua -p call=cb_print -m '*' -o stdout
Fluent-Bit v0.14.0
[2018/06/11 22:53:12] [ info] [engine] started (pid=20490)
mem.0	1528725193.000884	table: 0x41f16340
mem.0	1528725194.000263	table: 0x41f16398
mem.0	1528725195.000821	table: 0x41f1ccf0
```
My patch is to output such JSON like format.
```shell
$ bin/fluent-bit -i mem -F lua -p script=../scripts/test.lua -p call=cb_print -m '*' -o stdout
Fluent-Bit v0.14.0
[2018/06/11 22:48:53] [ info] [engine] started (pid=20207)
mem.0:  [1528724934.002288, { …
```

test.lua: output table contents

---

plugins/filter_modify/modify.c
plugins/filter_modify/modify.h

This extends the number of operations the modify filter can perform to,
-   RENAME
-   HARD_RENAME
-   ADD
-   SET
-   REMOVE
-   REMOVE_WILDCARD
-   COPY
-   HARD_COPY
In addition, this also adds the option to add conditions that have to be met for a filter instance's rules to be applied.
The possible conditions are,
-   KEY_EXISTS
-   KEY_DOES_NOT_EXIST
-   KEY_VALUE_EQUALS
-   KEY_VALUE_DOES_NOT_EQUAL
Example configuration,
```
[FILTER]
Name    modify
Match   *
Set sourcetype memstats
[FILTER]
Name    modify
Match   *
Condition Key_Value_Does_Not_Equal sourcetype memstats
Condition Key_Value_Equals sourcetype memstats
Add sourcetypeX memstatsX
Copy sourcetypeX sourcetype_copy
Rename sourcetypeX new_sourcetype
Set all_done true
```

filter_modify: Add new operations, conditionals

---

plugins/filter_modify/modify.c
plugins/filter_modify/modify.h

This adds rules and conditions with regex support to `filter_modify`.
Conditions,
- `A_key_matches`
- `No_key_matches`
- `Key_value_matches`
- `Key_value_does_not_match`
- `Matching_keys_have_matching_values`
- `Matching_keys_do_not_have_matching_values`
Rules,
- `Remove_regex`
Signed-off-by: Michiel Kalkman <michiel@nosuchtype.com>

filter_modify: Add regex rules and conditions

---

plugins/out_http/http.c
plugins/out_http/http.h

This adds a new configuration option '`Header`', which will add an
arbitrary key/value pair as HTTP header to outgoing HTTP requests.
Signed-off-by: Michiel Kalkman <michiel@nosuchtype.com>

out_http: Add arbitrary HTTP headers

---

plugins/filter_nest/nest.c
plugins/filter_nest/nest.h

This adds support to `filter_nest` for,
- Multiple wildcards in a single filter instance
- `Add_prefix` for both nest and lift operations
- `Remove_prefix` for both nest and lift operations
Signed-off-by: Michiel Kalkman <michiel@nosuchtype.com>

filter_nest: Multiple wildcards and add/remove prefix options

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

This Pull Request [adds initial Issue Templates for this repository](https://help.github.com/articles/about-issue-and-pull-request-templates/). Using the template builder, you can specify a title and description for each template, add the template content, and either commit the template to the default branch or open a pull request in the repository. The template builder automatically adds the YAML front matter markup that is required for the template to show on the new issue page. For more information, see "Creating issue templates for your repository."

Add initial Issue Template for Feature Requests and Bug Reports

---

plugins/filter_parser/filter_parser.c

To fix #700 
In some cases, `cb_parser_filter` returns -1.
cb_filter should return 1 or 2
```
#define FLB_FILTER_MODIFIED 1
#define FLB_FILTER_NOTOUCH  2
```
The variable `ret` is diverted as return value of `flb_parser_do`.
If flb_parser_do returns -1, it will be returned from cb_parser_filter.
The buffer will not be released at `flb_filter_do`, if return value is not 1 
```
$ ../bin/fluent-bit -c out_forward.conf  -f 1
$ valgrind --tool=massif ../bin/fluent-bit -c in_forward.conf
```
in_forward.conf:
```python
[SERVICE]                                      
Flush        1                             
Daemon       Off                           
Parsers_File ./parsers.conf  
HTTP_Server  On                             …
```

filter_parser: fix return value(#700)

---

src/flb_parser_decoder.c

In the UTF-8 decoder, it tries to read escaped char for general
purpose. Escaping a new-line is valid in JSON encoding, if it
lines a UTF-8 decoder and then a JSON decoder, the JSON decoder
will fail, as the escaped new-line is treated as a real newline
in the first UTF-8 decoder.
This fixes the issue in #615
Signed-off-by: Richard Meng <mengangr@foxmail.com>

decoder_utf8: do not read escaped newline (#615)

---

plugins/in_mem/mem.c

I'm trying to make `in_mem` fully compatible with the modern sysinfo() API to
ensure that it produces correct memory/swap data among various systems.
This patch is my attempt to implement it.
In particular, the current code naively assumes that a sysinfo() call
returns memory/swap sizes in bytes. The problem is, however, it's not
always the case. According to sysinfo(2):
In the above structure, sizes of the memory and swap fields are
given as multiples of mem_unit bytes.
This patch fixes the issue by introducing a function calc_kb() that
computes sizes based on mem_unit.

in_mem: Consider mem_unit when computing memory/swap sizes.

---

plugins/out_influxdb/influxdb_bulk.c

Timestamps `tm.tv_sec` and `tm.tv_nsec` set in `src/flb_time.c` [here](https://github.com/010akv/fluent-bit/blob/master/src/flb_time.c#L36-L51) will be uint64_t or uint32_t. However, `influxdb_bulk_append_timestamp()` in influxdb plugin assumes uint64_t.  This is not always true. This causes incorrect timestamp values being computed and sent to influxdb.
Adding a global uint64_t constant to fix this issue.
Signed-off-by: Anusha Kasi Vishwanathan 010akv@gmail.com

 influxdb: fix timestamp types

---

src/flb_io_tls.c

Changing the hard-coded value `/etc/ssl/certs` to the variable `ca_path`. The user could enter a different value for `ca_path` in the `.conf` file. When this happens, this error displays incorrect path.
Signed-off-by: Anusha Kasi Vishwanathan 010akv@gmail.com

Fix hard-coded value in TLS error message.

---

plugins/out_stdout/stdout.c
plugins/out_stdout/stdout.h

This adds new options for the stdout output plugin.  The Format option
can now accept json_lines, which will result in printing newline
delimited json.  The implementation was based on the out_http plugin
and also includes the json_date_format and json_date_key options.
Signed-off-by: Dylan Cooper dylanzycooper@gmail.com

Output: Added json_lines format for out_stdout

---

plugins/in_tail/tail_config.c
plugins/in_tail/tail_config.h
plugins/in_tail/tail_file.c
plugins/in_tail/tail_file.h
src/flb_hash.c

Add a new Tag_Regex option to capture named groups in the filename. Format the
tag according to the pattern set in the tag option which makes use of these
named groups.
Signed-off-by: Yann Soubeyrand <ysoubeyrand@leadformance.com>

in_tail: optionally format tag based on a regex against filename

---

plugins/filter_lua/lua.c
plugins/filter_lua/lua_config.c
plugins/filter_lua/lua_config.h

This is an another patch to fix #641 
With this patch
* default : lua_TNUMBER is converted to `double`
* option (c_int_key) : lua_TNUMBER is converted to `int64`
lua.conf:
```python
[INPUT]
Name cpu
[FILTER]
Name lua
Match *
call  cb_append
script append.lua
c_int_key cpu_p cpu0.p_system lua_int
[OUTPUT]
Name stdout
```
append.lua:
```lua
function cb_append(tag, timestamp, record)
new_record = record
new_record["lua_double"] = 12345
new_record["lua_int"]    = 12345
return 1, timestamp, new_record
end
```
`cpu_p` and `cpu0.p_system` and `lua_int` (generated in lua) are converted to integer.
Others are double.
```sh
$ bin/fluent-bit -c lua.conf 
Fluent-Bit v0.14.0
[2018/08/26 20:30:27] [ info] [engine] started (pid=22075)
[0] cpu.0: [1535283028.002336740, …
```

filter_lua: add new option to convert integer

---

src/flb_unescape.c

Maintain double escapes in order to allow quote characters in stringed json values.
For example:
```
{\"log\": "test \\\"message\\\"\"}
```
to
```
{"log": "test \"message\""}
```
fix: #615

Maintain double escapes in json strings

---

.gitignore

Add various generated files for in-tree builds to .gitignore
Signed-off-by: Don Bowman <db@donbowman.ca>

Add build directory and generated headers to .gitignore

---

plugins/out_flowcounter/out_flowcounter.c

Hi,
I encountered SEGV faults using fluent-bit (0.13.7 deb) on a 32 bit armv7 platform with the following config:
~~~
[INPUT]
Name          stdin
Tag           auditflow
[OUTPUT]
Name          flowcounter
Match         *
Unit          second
~~~
Gave the following output
~~~
Fluent-Bit v0.14.2
[2018/09/18 15:16:45] [ info] [engine] started (pid=6629)
[2018/09/18 15:16:45] [ info] [http_server] listen iface=127.0.0.1 tcp_port=2020
[out_flowcounter] [1537283805, {"counts":0, "bytes":0, "counts/(null)":0, "bytes/second":2759094127 }]
[out_flowcounter] [1537283806, {"counts":0, "bytes":0, "counts/(null)":0, "bytes/second":2759094127 }]
[out_flowcounter] [1537283807, {"counts":0, "bytes":0, "counts/(null)":0, "bytes/second":2759094127 }]
[out_flowcounter] …

fixup format warning - actually causing segv on arm32

---

Dockerfile

Fixed "Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)" error during the Dockerfile build

Fixed Dockerfile, zlib1g-dev missing

---

include/fluent-bit/flb_time.h
plugins/out_influxdb/influxdb.c
plugins/out_influxdb/influxdb.h
plugins/out_influxdb/influxdb_bulk.c

When I used the Influxdb output to test the fluency, I found it unusable.
* Crash when an error occurs when writing to Influxdb.
* There is no escaping in the kv field, so the write fails when the field contains a space.
* The written data will be overwritten by other data with the same timestamp.
* The `sequence_tag` produces too many series.
So I committed some changes and fixed the above problem. Now when I use influxdb as the output, everything works fine.

Some changes make the influxdb output work properly

---

src/flb_parser.c

its kind of a paint to get
```
[2018/09/25 14:29:35] [error] [parser] no parser 'format' found
```
without knowing what file or section. Simplify.

Add file & section-name diagnostics to error output of parser config

---

plugins/in_mem/proc.c

This adds flb_free(t) to the failure path, to reclaim memory we
allocated a few lines above but end up not using.

in_mem: fix a minor memory leak due to forgetting to free.

---

plugins/in_mem/proc.c

fread() never returns a negative value, and does not have any special
error returns. Instead, we need to call ferror() to check the status of
the file stream.
Also fread() does not set errno, so we shouldn't use flb_errono() here.

in_mem: Fix error handling of fread(3)

---

plugins/in_mem/proc.h

The file format has been changed in Linux 2.6. Specifically, the data
types of the following fields have been modified. According to proc(5):
(9) flags  %u
The kernel flags word of the process.
(22) starttime  %llu
The time the process started after system boot.
This fixes up the type declarlations in proc.h to keep them sync with
the latest specification.

in_mem: Use correct type specifiers when parsing `/proc/[pid]/stat`

---

plugins/out_influxdb/influxdb_bulk.c

I made a mistake in Influxdb escaping in #785 , we just need to escape the double quotes in string field.

out_influxdb: fix escaping in string fields

---

plugins/out_http/http.c

We mistakenly allowed `msgpack_to_json()` to work on an uninitialized
buffer, by deferring the check of the return code from the json
converter function.
This patch fixes the segfault bug by moving the error return to right after
the initialization call.

out_http: fix SIGSEGV on uninitialized json buffer

---

tests/runtime/filter_kubernetes.c
tests/runtime/out_counter.c
tests/runtime/out_exit.c
tests/runtime/out_file.c
tests/runtime/out_flowcounter.c
tests/runtime/out_null.c
tests/runtime/out_stdout.c

Many of the tests had thousands of lines of
```
[2018/10/05 08:10:46] [ warn] lib data incomplete, waiting for more data...
```
output since they had Log_Level set to 'debug'. Change
to 'error'.

Reduce non-interesting verbosity of tests

---

src/flb_http_client.c

header_lookup() has a bug that it goes over the boundary line and
finds matches in the body part.
This patch fixes the bug by limiting its search scope to the HTTP
header section.

http_client: fix header_lookup() to honor the header/body boundery

---

src/flb_pack.c

The string "full_message" is 12 char length, not 13.
This subtle error creates a classical "off-by-one" situation and
results in SIGSEGV when someone tries to output long messages.

flb_pack: fix sigsegv error while packing in GELF format

---

plugins/out_es/es.h

Elasticsearch reserves keys starting with underscore (_) for internal
use. This is enforced in Kibana. Change the default to avoid errors.

Change FLB_ES_DEFAULT_TAG_KEY to flb-key from _flb-key

---

src/flb_pack.c

This adds free() to the failure path, to prevent memory we allocated
for the prefix string from leaking.

flb_pack: fix a minor memory leak in flb_msgpack_to_gelf()

---

src/flb_unescape.c

This fixed the null bytes reported in #841

flb_unescape_string_utf8: Fix wrong null bytes string ending (Fixes parts of #841)

---

plugins/filter_throttle/throttle.c

The hash table and window were leaked in the destructor.

Fix leak on cleanup of throttle

---

plugins/out_es/es.c
plugins/out_es/es.h
plugins/out_es/es_conf.c

I find it very difficult to diagnose errors logging to Elastic,
and don't want to see all messages logged at e.g. debug level,
this allows gating it on/off to print the JSON of the exchange.

Add Trace_Output to Elasticsearch output plugin

---

tests/runtime/filter_kubernetes.c

Its possible that the build system has systemd available,
but the test system does not, leading to a false-failure.

Skip systemd journal test if not running

---

plugins/filter_modify/modify.c

filter_modify/modify.c doesn't handle return status FLB_FILTER_NOTOUCH.
It should free memory allocated for msgpack_sbuffer fore returning  FLB_FILTER_NOTOUCH status.
This  can make memory leak, I think.
Or I have understood memory handling correctly? 

filter_modify: fix return data leak when input unmodified

---

plugins/filter_kubernetes/kube_conf.c

filter_kubernetes: Fix leak of 'meta dir' on destroy

---

src/flb_utils.c

In flb_utils_write_str, written and *off could be set
to an incorrect large value on invalid UTF-8 input.
Later, this would lead to an out of bounds write when
nul-terminating the string:
Invalid write of size 1
at 0x44378B: flb_msgpack_to_json (in /build/bin/fluent-bit)
by 0x443B78: flb_msgpack_raw_to_json_str (in /build/bin/fluent-bit)
by 0x47576D: kafka_rest_format (in /build/bin/fluent-bit)
by 0x4758E9: cb_kafka_flush (in /build/bin/fluent-bit)
by 0x434A71: output_pre_cb_flush (in /build/bin/fluent-bit)
by 0x50DF26: co_init (in /build/bin/fluent-bit)
Address 0x4d9985e is on thread 1's stack
Input file (base64 encoded):
MAowCjAwCjAwADAKMDAwMDAK/wowCjAwCoAK

flb_utils: fix out of bounds write on invalid utf-8

---

plugins/in_tail/tail.c
plugins/in_tail/tail_config.c
plugins/in_tail/tail_config.h

The rationale is to allow writing a simple test which
takes an input file, runs to completion (perhaps writing
to stdout or output file) and then exits.

in_tail: Add Exit_On_EOF option to tail input

---

plugins/in_systemd/systemd.c
plugins/in_systemd/systemd_config.c
plugins/in_systemd/systemd_config.h

Add an option to strip leading underscores when reading systemd keys.
Elasticsearch has reserved fields beginning with underscore for internal
use. Kibana enforces this by not allowing these fields in filter.
See https://github.com/elastic/kibana/issues/2551.
This configuration option will make it easier to work with in_systemd
together with out_es.
Fix #638
Signed-off-by: Patrik Karlström <jp.karlstrom@gmail.com>

in_systemd: add strip_underscores configuration

---

.travis.yml
ci/do-ut

Switch to 'xenial' from 'trusty' for unit testing since the older
binutils did not work well with the sanitizer tests for gcc.
There was also a bug in libc gmtime() which was causing faulse failures.
Add a matrix so that we run, for both gcc and clang:
- JEMALLOC on/off
- ASAN on/off
- USAN on/off
- MSAN on/off
TSAN is disabled as there are significant errors/false positives
in the code where sleep() is used to synchronise.
Infrastructure is put in place to build a test docker image
with a bash test suite prepatory to committing a 'corpus' of
input test files to compare output for system test of the
docker image.

Switch travis UT to 'xenial', add matrix of clang/gcc for sanitizers

---

tests/runtime/filter_kubernetes.c

In a container environment systemd does not run. Skip
the test if there is no systemd journal sock.
Signe-off-by: Don Bowman <don@agilicus.com>

[test filter_kubernetes] skip systemd test if journal not running

---

.dockerignore
Dockerfile

The copy-in of the code is moved to after the setup of the build
container to maximise cache (so no rebuild of the build packages
if the source changes).
Add a .dockerignore of .git / build / Dockerfile to maximise
cache.
Switch to gcr.io/distroless/cc as a base container for the run-time,
reducing the possibility of an 'escape' in the code.

Switch to distroless as base image for container, add .dockerignore

---

plugins/out_es/es_conf.c

Elasticsearch reserves keys starting with '\_' for internal use, although it does not enforce this. Kibana does enforce it, making such keys useless to it. 'flb-key' is not internal to Elasticsearch, so it should not start with '\_', remove warning.

out_es: remove warning on not using '_' as first character of tag-key

---

include/fluent-bit/flb_pack.h
plugins/in_tail/CMakeLists.txt
plugins/in_tail/tail.c
plugins/in_tail/tail_config.c
plugins/in_tail/tail_config.h
plugins/in_tail/tail_dockermode.c
plugins/in_tail/tail_dockermode.h
plugins/in_tail/tail_file.c
plugins/in_tail/tail_file.h
plugins/in_tail/tail_file_internal.h
plugins/in_tail/tail_multiline.h
src/flb_pack.c

An extension to in_tail that recombines JSON-encoded log lines split by
Docker's 16k log line limit. Just add "Docker_Mode on" to in_tail's
configuration.

in_tail: add Docker mode for recombining log lines split by Docker

---

conf/parsers.conf

See #876 and #873 
If a single character is detected, consider this the log tag for the line.
This is a part of the multiline handling for cri-o logs.
Example Fluent-bit log line on disk:
```
root@fluent-bit-29xjh:/# more /var/log/containers/fluent-bit-29xjh_dev-eeva-logging_fluent-bit-0db128860717a93c7d219425c9d49f4445c2d6c6e5fed3f4dc4298f03c582378.log 
2018-10-31T21:54:45.45487617Z stderr F Fluent-Bit v0.14.4
2018-10-31T21:54:45.454938595Z stderr F Copyright (C) Treasure Data
2018-10-31T21:54:45.454946545Z stderr F 
2018-10-31T21:54:45.455512949Z stderr F [2018/10/31 21:54:45] [ info] [engine] started (pid=1)
2018-10-31T21:54:48.837184585Z stderr F [2018/10/31 21:54:48] [ info] [filter_kube] https=1 host=kubernetes.default.svc.cluster.local port=443
2018-10-31T21:54:48.837218858Z stderr …
```

parsers: Support CRI-O and containerd

---

plugins/filter_kubernetes/kube_meta.c

If there was more than 1 container in a pod with different parser
types, it was matching the first one each time. Separate the hash-key
by container-name.

[filter_kubernetes] Fix issue with >1 container in pod diff parser type

---

init/systemd.in
init/upstart.in
src/CMakeLists.txt

This patch provides an upstart job file to be passed to the build process;
The job's config mimics the behaviour of the systemd service.
CMake config modified to handle the above.
Also, there was some duplication of '/' in the resulting package's
paths, that is fixed as well.
Build tested with modified 'fluent-bit-packaging' project;
Resulting package tested on Ubuntu 14.04.
Signed-off-by: Zsolt Kulcsar <zskulcsar@gmail.com>

Build: Adding upstart init system support

---

Dockerfile

Google has deprecated `launcher.gcr.io`
(see https://cloud.google.com/marketplace/docs/container-images)
Their recommended replacement is marketplace.gcr.io, which requires
Google Cloud Platform credentials (which we don't have).
Switch to the upstream debian-maintained Dockerhub image
which derives from the same source.

Switch to dockerhub debian:9 from launcher.gcr.io/debian9

---

plugins/in_systemd/systemd.c

tag and last_tag are pointers and can't both point at the same buffer if they're to hold different values.

in_systemd: tags dont match _SYSTEMD_UNIT

---

plugins/in_mem/proc.c

Right now, `proc_stat()` tries to find out the buffer size by asking
`file_to_buffer()` about it. This is totally unnecessary, because the
size is actually a globally-accessible constant.
This patch removes the meaningless hustle surrounding `read_size` and
simplifies the logic of `proc_stat()`.
Also `file_to_buffer()` now just uses `flb_calloc()`, instead of allocating
memory and initialize it with `memset()` by hand.

in_mem: clean up the buffer handling in proc.c

---

Dockerfile

plugins.conf was missing from the Dockerfile

docker: add missing plugins.conf

---

tests/runtime/filter_kubernetes.c

Although bc0a21372274aadb6e81aed19b2ea1b4c824992c put in
a fix for the problem of multiple systemd records causing
a crash, I believe this solution is more robust since it will
work for any future inputs that have multiple result records.

tests: runtime: filter_kubernetes: make kube_test_create do destroy

---

src/flb_pack.c

When serialization fails, we try to add a 128-byte block to the
buffer and retry again. This strategy seemingly works fine.
Except when we have an input with high flow volume, and suddenly
the consent growth factor (128 bytes) becomes too small. And we
end up wasting time doing a ridiculous amount of recalculations:
```
| EVENTS | INITIAL [bytes] | ACTUAL [bytes] | RECALC [calls] |
| ------ | --------------- | -------------- | -------------- |
|      1 |             36  |            47  |             1  |
|     10 |            349  |           470  |             1  |
|    100 |           3483  |          4700  |            10  |
|   1000 |          34803  |         47000  |            96  |
|  10000 |         348003  |        470000  |           954  |
```
This patch fixes the issue by …

flb_pack: improve the buffer allocation strategy

---

plugins/out_nats/nats.c

This patch resolves the issue #909.
A typical NATS publish request looks like below:
PUB <tag> <bytes>\r\n<json>
... which means that we need to allocate (tag_len + 32) bytes for
the request header, and (json_len) bytes for the payload body.
We right now allocates no more than (json_len + 32) bytes, so the
following memcpy can overrun the buffer.

out_nats: fix SIGSEGV on long topic names

---

CMakeLists.txt
include/fluent-bit/flb_time.h
src/flb_time.c

macOS does not have `clock_gettime()`.
Instead, we can use `clock_get_time()` which is originated from Mach.

Implement precise time obtaining mechanism on macOS

---

CMakeLists.txt
plugins/in_forward/fw.c

Windows cannot handle unix socket.
We should disable it on Windows.

in_forward: Check unix socket availability 

---

CMakeLists.txt

Right now, we receive lots of vogus warnings on Windows from system
headers (e.g. "padding added after construct X in windows.h").
This patch tweaks the compiler flag to use -W4 (instead of -Wall) on
MSVC. This should reduce quite a lot of unhelpful warnings.
**Note** See [mbedtls/CmakeLists.txt](https://github.com/fluent/fluent-bit/blob/master/lib/mbedtls-2.14.1/CMakeLists.txt#L153) for similar tweaking.

build: suppress excessive warnings on Windows/MSVC

---

plugins/CMakeLists.txt

This fixes the compilation error on FLB_REGEX=Off; Both plugins
depend on onigmo.h, so we really should not try to build them in
such situations.
This patch is part of #960.

build: don't build nest/modify filter plugins if FLB_REGEX=Off

---

include/fluent-bit/flb_compat.h
src/fluent-bit.c

Windows defines the maximum path length as `MAX_PATH`, while
Linux calls the same constant `PATH_MAX`.
This patch adds a compatibility macro for them (and is part of #960).

compat: define PATH_MAX for Windows

---

src/CMakeLists.txt

This is a trivial fix for the following compilation error.
LINK : fatal error LNK1104: cannot open "rt.lib"
Since librt normally does not exist except on Linux (and some other
Unix systems), we really should not try to link it on Windows.

build: fix "cannot open rt.lib" error on Windows

---

src/CMakeLists.txt

This fixes the "cannot open mbedtls/base64.h" error at compile
time when FLB_TLS is disabled.
Essentially, both source files depend on mbedtls and cannot be
compiled without TLS support.

cmake: don't build flb_http_client/flb_oauth2 when FLB_TLS=Off

---

plugins/out_lib/out_lib.c

Right now, VC++ fails to compile out_lib due to the following error.
C2036: 'void *' unknown size
This patch fixes it by adding a explicit type cast to a char pointer.

out_lib: fix "data size is unknown" error on MSVC

---

include/fluent-bit/flb_sds.h

We need this to build flb_sds.c on MSVS without errors.
Note that GCC and clang also support the Microsoft `#pragma pack` feature,
so we can use Microsoft's syntax here without breaking portability.
* https://gcc.gnu.org/onlinedocs/gcc-6.3.0/gcc/Structure-Layout-Pragmas.html
* http://releases.llvm.org/3.8.0/tools/clang/docs/UsersManual.html

sds: use "pack" pragma instead of __attribute__(__packed__)

---

plugins/out_forward/forward.c

Namely C99 requires programmers to use `{0}` to initialize an array.
The syntax `{}` is only for C++ and causes an compilation error on
VC++ (GCC accepts it, though).

out_forward: initialize the array with `{0}` not `{}`.

---

src/flb_pipe.c

This allows us to compile `flb_pipe.c` without errors on both Linux
and Windows.
Basically, we need to pass a char pointer to recv/send on Windows;
Otherwise VC++ will complain "void * unknown size" and the compilation
process fails.

flb_pipe: add cast to character pointer type for VC++

---

include/fluent-bit/flb_compat.h
include/fluent-bit/flb_network.h
src/flb_network.c
src/flb_time.c

Both Windows and Linux have their own way to name network libraries.
This patch allows you to import these libraries just with:
#include <fluent_bit/flb_compat.h>
so you do not need to care the underlying difference.

compat: move the network-related compatibility stuff

---

src/flb_engine.c

Without this, MSVC failes to compile `flb_engine.c` spitting
"unknown types" errors on Windows.

engine: include <fluent-bit/flb_time.h> explicitly

---

src/flb_pipe.c
src/flb_time.c

This is a portable implementation to suspend execution in sub-second
precision, which should work on both Linux and Windows.
Since Windows provides neither nanosleep() nor usleep(), we need to
implement the functionality using Win32 Sleep() function here.

time: add flb_time_msleep() to sleep N milliseconds

---

src/flb_output.c

The attribute `match_regex` does not exist if FLB_REGEX is turned
off at compile time, so we need special care not to touch it in
such case.

output: initialize match_regex conditionally

---

tests/internal/parser.c

Parser tests failed with macOS (OSX 13.X in my case).
Changed them to work.
* config init done with flb_config_init.
* timezone: +XX:YY cases ignore
macos strptime(3) doesn't like those.
* some error printing in case of failed for clarity
using TEST_MSG()

tests: parser.c tests made working with macOS.

---

include/fluent-bit/flb_compat.h

This is a series of patches to provide a set of functions that we do not have on Windows.
23797a00 compat: add a function to get memory page size on Windows
ffd5b111 compat: implement gmtime_r() function for MSVS
Part of #960

compat: add Windows compatibility functions

---

src/fluent-bit.c

Windows does not support realpath(3); so added ifdefs to switch to
_fullpath on VC++.

core: use _fullpath in place of realpath on Windows

---

fluent-bit_git.bb

The original Bitbake recipe did not cross-compile to ARM architecture.
That should be fixed now, though without an additional patch to FindMonkey,
the build (which happens out of the project tree in Yocto) will still fail
at do_configure. Lua support is disabled by default here because it does
not appear to cross-compile successfully.
Partial solution to issue #839

OpenEmbedded/Yocto: update Bitbake recipe for cross-compiling.

---

Dockerfile.debug

Some people prefer debugging by shell'ing into a container
and having local filesystem access. This image inherits the
parent and then adds busybox (giving sh/cat/ls etc).

build: Add Dockerfile.debug to allow 'shell into image'

---

tools/xxd-c/xxd-c.c

I can confirm this patch fixes compile errors within tools/xxd-c.c,
and allows us to use xxd-c.exe on Windows.
% .\bin\debug\xxd-c.exe -i test.conf
...
static unsigned char __test_conf[] = {
0x61, 0x69, 0x75, 0x65, 0x6f,
};
Part of #960

tools: xxd-c: include getopt.h through <mk_getopt.h> for portability

---

include/fluent-bit/flb_compat.h

Without this, MSVC wrongly assumes that the return value of localtime_r()
is an integer while it's actually a pointer (struct tm*).
> warning C4013: 'localtime_r' undefined; assuming extern returning int
This has been causing SIGSEGV in flb_log_print() on Win64, since Windows
improperly truncates the returned pointer in order to fit the pointer
address into 4 bytes.
Part of #960

compat: add an explicit declaration for localtime_r()

---

include/fluent-bit/flb_worker.h

On Windows, evutil_socket_t is an alias of intptr_t, not integer.
> libevent-2.0 > util.h > evutil_socket_t
>
> A type wide enough to hold the output of "socket()" or "accept()".
> On Windows, this is an intptr_t; elsewhere, it is an int.
Since sizeof(intptr_t) is greater than sizeof(int) on x64 MSVC,
flb_pipe_create() silently corrupts memory inside the worker struct
resulting in SIGSEGV.
This patch fixes the issue by using the correct data type on Windows.
Part of #960

worker: fix SIGSEGV on calling loging functions on Win64

---

plugins/out_http/http.c

This allows receivers to identify Fluentbit traffic.
This matches the `User-Agent` used in other output plugins that use HTTP as a transport, e.g. Splunk, ES, Kafka, etc.

Add User-Agent header to out_http

---

src/flb_log.c

Without this fluent-bit tries to manipulates the thread-local storage
using an uninitialized key, which was causing a series of memory
corruptions.
**NOTE:** the reason this bug hasn't been evident was that GCC and clang
have native `__thread` support so we do not need to prepare the data
key manually; Unfortunately, it's not the case with MSVC.
Part of #960

log: add a missing FLB_TLS_INIT call for flb_log_ctx

---

src/flb_config.c

The point is that we do not need to call both `mk_event_del()` and
`mk_event_timeout_destroy()` on the same event object. In fact,
calling both  can lead to SIGSEGV in some backend (e.g. libevent).
This patch fixies the issue by moving the call of mk_event_del() to
the "else" block.
Part of #960

config: fix SIGSEGV errors on shutdown of input plugins

---

cmake/luajit.cmake
cmake/onigmo.cmake

The problem was that older cmake versions (2.x) didn't recognize
EXCLUDE_FROM_ALL setting. Since cmake would add external projects
into "make all" target by default, it has been causing compilation
errors on non-Windows systems.
This patch fixes the issue by not including the build definitions
on platforms other than Windows.
Part of #960
Related to #1071

build: avoid including Windows-specific build definitions

---

plugins/out_kafka/kafka.c
plugins/out_kafka/kafka_config.c
plugins/out_kafka/kafka_config.h

This allows using iso8601 in the JSON output format if desired
rather than double.

Add timestamp_format to kafka output

---

tests/runtime/filter_kubernetes.c

I'm not 100% sure what was 'fixed' elsewhere, but the exclude
annotation started working on the apache exclude case, and the
test was written to expect 1 row out, was getting 0. Resolve
test case.

test: fix filter kubernetes test for excluded logs

---

src/flb_parser.c

If a parser configuration does not have Types fields, the "types"
variable can be passed around without initialized. This has been
causing errors on Windows build.
Part of #960

parser: initialize "types" to NULL explicitly

---

include/fluent-bit/flb_pipe.h
src/flb_pipe.c

The reason why need this function is that Windows does not support
O_NONBLOCK and we need to call another function (ioctlsocket) to
create a nonblocking socket.
This patch adds a portable wrapper function for that purpose.

pipe: add flb_pipe_set_nonblocking() for portability

---

tests/internal/http_client.c

test http_client.c did not allocate config using flb_config_init(),
but just allocating structure.  This doesn't work with macOS and
makes segfault.
All flb_config's should be created  with flb_config_init() and
deleted with flb_config_exit() (?)

test:  http client test segfaults in macOS.

---

src/flb_config.c
src/flb_input.c

This is a series of patches to fix SIGSEGV on closing sockets on Windows.
21bcd10b lib: monkey: sync Windows support changes
50325994 core: use mk_event_closesocket() instead of plain close(2)
Since this patch depends on the function added in monkey/monkey/pull/294,
it syncs lib/monkey with the latest master HEAD.
Part of #960.

core: use mk_event_closesocket() instead of plain close(2)

---

plugins/filter_lua/lua.c

Allow larger integers back in from lua (without using floating/double).

changed casting

---

include/fluent-bit/flb_compat.h

This is a series of patches to add functions and macros that are missing on Windows.
We need them in order to port in_tail to Windows.
569c5521 compat: implement timegm(3) for Windows
96abb9c6 compat: implement basename(3) for Windows
2f276993 compat: define S_ISREG macro for Windows

compat: Implement a couple of functions/macros for Windows

---

plugins/out_forward/forward.c

If we are using fluent-bit -> fluent-bit (e.g. fwd from one
to another) we might have a TLS tunnel in the middle courtesy
of e.g. stunnel. We are secured by client-certificate, but not
by 'forward protocol secure mode'.

[out_forward] Don't assumed 'secure' mode just because TLS is on

---

include/fluent-bit/flb_langinfo.h

This allows us to call nl_langinfo() on Windows to query locale-
specific format strings.
Right now it only supports LC_TIME and "C" locale, but should be
sufficient to get flb_strptime.c (submitted in the later patches)
compilable on Windows.
Part of #960

langinfo: implement langinfo.h for Windows

---

include/fluent-bit/flb_compat.h

It's preparation for introducing a portable strptime function.
Since Windows calls some functions and constants differently, we
need these macros to compile the source code properly.
Part of #960

compat: add a set of macros for implementing strptime

---

src/flb_strptime.c

This is a series of patches to introduce a new Windows-compatible
implementation of strptime(3).
I needed to apply several patches to the base implementation (OpenBSD)
in order to make it usable. For making changes easier to track, I put
these custom patches into separate commits.
c132d340 strptime: copy strptime.c from OpenBSD project
50680411 strptime: make flb_strptime.c actually usable
0edf6f27 strptime: fix "differ in signedness" warnings on GCC
103c6a11 strptime: store the timezone offset in seconds (tm_gmtoff)
**Note** This PR only introduces flb_strptime.c into `fluent-bit/src/`.
I'll post a separate PR for build settings etc.
Depends on #1105, #1106
Part of #960

strptime: add a new portable strptime(3) (version 2)

---

CMakeLists.txt
cmake/windows-setup.cmake
include/fluent-bit/flb_strptime.h
src/CMakeLists.txt
src/flb_parser.c

This is a series of patches to introduce flb_strptime into the code base.
d9586753 build: set up cmake build procedures for flb_strptime.c
8670b19b parser: introduce flb_strptime.h to the codebase
The important part is that this adds a new option FLB_SYSTEM_STRPTIME
that allows us to switch between implementations of strptime(3).
$ cmake -DFLB_SYSTEM_STRPTIME=Off ..
Right now this option is set to false only on Windows, but might be
useful on other platforms as well.
Depends on #1109
Part of #960

strptime: set up the build settings for flb_strptime

---

include/fluent-bit/flb_pipe.h
src/flb_pipe.c

Since Windows has a different way to check what happend in the last
nonblocking read, it's convenient have a wrapper function for it.
We will use this function to port plugin/in_tail to Windows.
Part of #960

pipe: add a portable function to check EAGAIN

---

plugins/in_tail/tail_file.c

Unless we open the file with O_BINARY, Windows will treat "\r\n" as
1 byte. This has been causing in_tail malfunctioning on Windows, due
to the read count never reaching the actual file size.
Part of #960

tail_file: open the target file in binary mode

---

conf/kube_elasticsearch.conf
plugins/out_es/es.c
plugins/out_es/es.h
plugins/out_es/es_conf.c

Signed-off-by: Leo Jiang <jiangfengbing@conew.com>
ConfigMap example for k8s:
```
output-elasticsearch.conf: |
[OUTPUT]
Name                es
Match               *
Host                ${FLUENT_ELASTICSEARCH_HOST}
Port                ${FLUENT_ELASTICSEARCH_PORT}
Logstash_Format     On
Logstash_Prefix     k8s   
Logstash_Prefix_Key es_index
```
log example
```
{"es_index":"service-liveness-probe","func":"ProbeService","level":"info","method":"TcpPort","msg":"okay","port":0,"prob_name":"http","svc":"service_name.ns","time":"2018-07-31T11:11:18+08:00"}
```
ElasticSearch result:

out_es: add Logstash_Prefix_Key support

---

src/flb_pack.c

According to GELF-protocol "the *level* equal to the standard syslog levels; optional, default is 1 (ALERT)", otherwise messages will be silently dropped by graylog.
Here we checking the *level* field to have a correct value, informing otherwise.
http://docs.graylog.org/en/2.4/pages/gelf.html

warn on wrong gelf-level

---

plugins/in_exec/in_exec.c
plugins/in_exec/in_exec.h

This is in relation to [this](https://github.com/fluent/fluent-bit/issues/1009) issue.
I used the **head** plugin as inspiration.
The idea is to be able to specify a `buf_size` property for the exec plugin to be able to handle outputs larger than 4kb.
A few things about this PR:
- the buffer is allocated once, at plugin init, exactly like the **head** plugin
- the buffer is deallocated at the exit of the plugin
- the size can be specified exactly like `mem_buf_limit` property, using human readable sizes like `1kb` or `3mb`. Fails if it doesn't understand the size.
- Added an error message and some trace messages in case the parser is specified and it fails.
- Uses `DEFAULT_BUF_SIZE` (4096) in case the `buf_size` property is not present.
Tested using this:
```bash
$ echo "{\"$(printf …
```

Add buf_size property to exec plugin

---

plugins/out_http/http.c
plugins/out_http/http.h
plugins/out_http/http_conf.c

I am working with an API that expects the timestamp format to be an integer. Previously I've been able to work around this by using a Lua script, but it would be nicer if this could be accomplished inside the plugin since it's already handling timestamp fields.
I do not have a ton of experience working with C, so any feedback or direction would be much appreciated!

out_http: add epoch option for json_date_format

---

plugins/in_tail/tail.c
plugins/in_tail/tail_file.c
plugins/in_tail/tail_file.h
plugins/in_tail/tail_fs_stat.c
plugins/in_tail/tail_scan.c
plugins/in_tail/tail_signal.h

We need this in order to make the source tree compilable on Windows.
Since Windows lacks unistd.h, we need to include it indirectly though
flb_compat.h.
Part of #960

in_tail: use flb_compat.h instead of unistd.h

---

include/fluent-bit/flb_oauth2.h
plugins/out_stackdriver/CMakeLists.txt
plugins/out_stackdriver/gce_metadata.c
plugins/out_stackdriver/gce_metadata.h
plugins/out_stackdriver/stackdriver.c
plugins/out_stackdriver/stackdriver.h
plugins/out_stackdriver/stackdriver_conf.c
src/flb_oauth2.c

This PR adds basic support of GCE metadata server to fluentbit. Now plugin can read next fields: project_id, zone and instance_id from the metadata server (happens once during plugin init phase).
In case if private key wasn't provided, plugin assumes that it runs in GCE environment and token can be fetched from the metadata server. If client_email wasn't provided too "default" is used.
Combining project_id, zone and instance_id allows us to add support of gce_instance resource.

out_stackdrvier: added support of metadata server and gce_instance resource.

---

plugins/in_tail/tail_dockermode.c
plugins/in_tail/tail_file.c

Zero-initialization with 'struct foo bar = {}' is a GCC extension and
MSVC does not support it.
Instead, we need to do 'struct foo bar = {0}' to be portable.
(To my knowledge, this is valid at least since C89)
Part of #960

in_tail: use {0} instead of {} to initialize structs

---

conf/parsers.conf

Seeing that `fluent-bit` and NGINX ingress controller are widely used in k8s, it seems like a good idea to include a parser out of the box.
Thanks to @donbowman https://blog.donbowman.ca/2018/09/13/increasing-the-usefulness-of-your-kubernetes-ingress-logging/ for creating the parser.

include k8s nginx ingress parser

---

src/flb_pack.c

This fixes: https://github.com/fluent/fluent-bit/issues/1070

[gelf] Fix printf %.*s arguments order.

---

plugins/in_tail/tail_config.h

This is essentially the same fix as 13166dfb.
Since these pipe fds are actually sockets on Windows, we need to
use a 64-bit type (intptr_t) instead of 32-bit one (int) to hold
the descriptor properly.
Otherwise memory can silently get corrupt due to the type-length
mismatch, resulting in SIGSEGV.
Part of #960

tail: fix SIGSEGV due to the incompatible type length (int/intptr_t)

---

plugins/in_systemd/systemd.c

After stripping the leading underscore, the code adjusts string length for copying the key but doesn't adjust length for copying the value, adding a trailing character to value.  Better to strip the leading underscore before searching and extracting the key/value pair.

in_systemd: strip_underscores adds extra character to value

---

include/fluent-bit/flb_compat.h
plugins/in_tail/tail_file.c

This moves the include statement for libgen.h (the header for basename
and dirname) to flb_compat.h.
This is just for portability; Since Windows does not provide libgen.h,
we need to include it only on UNIX systems.
Part of #960

in_tail: include libgen.h though flb_compat.h for portability

---

cmake/windows-setup.cmake

We have migrated flb_parser to Windows on 1ace90224, so this patch
enables the build option by default on Windows.

build: enable FLB_PARSER on Windows

---

plugins/in_stdin/in_stdin.c

Currently the msgpack sbuffer is destroyed instead of cleared after constructing the msgpack objects. This is changed to clear the buffer instead, so re-using it does not refer to deallocated memory.
Alternatively the buffer could be re-initialized after destroying it, but since the memory which would be used is effectively bound to the stdin buffer size, clearing it should be the better approach here.

in_stdin: prevent double free / use after free of msgpack buffer

---

plugins/in_tail/tail.c
plugins/in_tail/tail_config.c
plugins/in_tail/tail_signal.h

The reason we need this patch is that Windows does not support pipe(2),
which in_tail uses for internal communication (e.g. for notifying file
rotations).
This patch migrates all these non-portable calls to flb_pipe_*() and
make the internal communication working properly on Windows.
Part of #960

in_tail: migrate pipe operations to flb_pipe_* functions

---

src/flb_config.c

If the input plugin supports cb_pause() interface, we ended up freeing
the same timeout object twice while shutdown, because of the function
flb_input_pause_all() destroying the timeout object in order to halt it.
This issue has been causing SIGSEGV on libevent backend (and probably
on select backend).
Part of #960

in_tail: avoid double freeing the same timeout event object

---

plugins/out_es/es.c
plugins/out_es/es.h
plugins/out_es/es_conf.c

This change does two things. In elasticsearch_error_check()
it was incorrectly returning 'was an error' all the time
(e.g. whenever the response msgpack *could* be unpacked).
Add a 'trace_error' flag to elasticsearch output to get
a raw dump of the json messages that cause a failure, in order
to debug why the failure occurred.

out_es: Fix elasticsearch_error_check, add trace_error output

---

plugins/filter_kubernetes/kube_conf.c
plugins/filter_kubernetes/kube_conf.h
plugins/filter_kubernetes/kube_meta.c

[#440](https://github.com/fluent/fluent-bit/pull/440) makes possible to exclude the `Annotations` from the extra metadata. This PR does the same for kubernetes `Labels`.

filter_kubernetes: allow user to decide whether they want to include labels

---

src/flb_utils.c

flb_utils_split() can be called with a null line
in the case where e.g. an environment variable is used
that is not set. For example:
```
[OUTPUT]
Match *
Name  http
Host   127.0.0.1
Port   8000
URI    ${URI}
```
if URI is not set in the environment.

utils: Protect flb_utils_split() from null input

---

plugins/in_cpu/in_cpu.c
plugins/in_cpu/in_cpu.h

Seems like extending the CPU Usage input plugin to sub-second sampling interval is a straight-forward sort of change.
For example:
```
$ fluent-bit -i cpu -p interval_sec=0.500000000 -F record_modifier -m '*' -p 'Whitelist_key=cpu_p' -o stdout -p format=json_lines -p json_date_format=iso8601  -m '*'
...
{"date":"2019-02-20T11:40:22.500103Z", "cpu_p":12.500000}
{"date":"2019-02-20T11:40:23.000148Z", "cpu_p":10.000000}
{"date":"2019-02-20T11:40:23.500153Z", "cpu_p":5.000000}
{"date":"2019-02-20T11:40:24.000157Z", "cpu_p":5.000000}
...
```
It would be nicer to have another utility function for accepting an optional unit such as 'ms', 'milis', 'micros' or 'nanos' as a suffix to a floating-point interval?

in_cpu: extend to support sec.nanosecond for sub-second sample rate

---

appveyor.yml
ci/do-ut.ps1

Currently, Windows support is targeted to build with Visual Studio 2017 and w/o chunkio filesystem backend.
This PR contains just building and minimal testing fluent-bit on Windows with Visual Studio 2017.
~~Compiling and running unit tests is on AppVeyor not yet.~~ Done. :muscle:
---
Part of #960

appveyor: Re-setup AppVeyor to build with Visual C++ 2017

---

src/flb_hash.c

In case that we are searching for an entity using non-null terminated string
`if (strcmp(entry->key, key) == 0) {}` will fail every time.
We need to compare the keys with `if (strncmp(entry->key, key, key_len) == 0)`
In case that we have an entity with a key `abcde` and it is the only one in the hash bucket,
`if (strncmp(entry->key, key, key_len) != 0)` will give false find for `a`, `ab`, `abc` and `abcd`.
We need to add `entry->key_len != key_len` as a first condition to check in the if statement.

flb_hash: Make flb_hash_get to work with non-null terminated string

---

plugins/in_tail/CMakeLists.txt
plugins/in_tail/tail_scan_win32.c

This is a first cut at supporting wildcard pathspecs on Windows.
Since Windows has no support for glob(3), we need to emulate the
feature using Win32 API. Here I implemented it using the Win32's
FindFirstFile/FindNextFile functions, and this enables you to do:
PS > fluent-bit -i tail -p 'path=log\*.json' -o stdout
The biggest limitation right now is that we can't use a wildcard
in the directory path (like 'C:\*\test.log'). This is because
a) FindFirstFile() does not support it and b) there seems to be no
other API that is usable for this purpose.
We'll revisit this issue in future, but the current implementation
should be sufficient for now.
*This patch is intended to be merged after v1.1 release.*
Part of #960

in_tail: add tail_scan_win32.c for scanning paths on Windows

---

plugins/in_tail/tail_sql.h

Windows is LLP64 system, and long integers have only 32-bit width there.
However, we use '%lu' for serializing read offset numbers (and others)
in tail_sql.h assuming long has always 64-bit width.
This was causing data corruption on Windows. This patch fixes the bug by
replacing them with C99's PRIu64 macro.
*This patch is intended to be merged after v1.1 release*
Part of #960

in_tail: use C99 macro instead of '%lu' to format 64-bit integers

---

plugins/in_tail/tail_db.c

The printf-family functions can corrupt data if the arguments have
different type length than specified in the format string (for example,
passing a 32-bit integer to PRIu64).
This patch casts each argument with platform-variable width into uint64_t
for safety.
*This patch is intended to be merged after v1.1 release*
Part of #960

in_tail: cast arguments explicitly for snprintf(2)

---

plugins/in_tail/tail_file.c

Previously, flb_tail_file_append() used POSIX open(2) to open log files.
The problem with this approach was that it silently acquires a delete
lock on the file, and thus can interfere with file maintenance operations
performed by the logging process (like log file rotation).
PS > rm access.log
rm : cannot remove item access.log: The access cannot access the
file 'access.log' because it is being used by another process.
This patch resolves the issue by using CreateFile() instead of POSIX open()
and enabling resource sharing (FILE_SHARE_*) explicitly.
*This patch is intended to be merged after v1.1 release*
Part of #960

in_tail: avoid locking files on Windows

---

plugins/in_tail/tail_file.c
plugins/in_tail/tail_file_internal.h

in_tail uses inodes to identify files in a SQLite DB. The problem
was that Windows did not support inode and always set st_ino to 0
on stat(3) calls. Because of such, the offset storing feature was
not working properly on Windows.
This patch adds a simple emulation of inodes for Windows, and
enables Windows users to retain the read offset between restarts.
*This patch is intended to be merged after v1.1 relelase*
Part of #960

in_tail: emulate inodes on Windows

---

src/flb_scheduler.c

On Windows, this line fails with a segmentation fault. This is because
Windows distinguishes sockets and file descriptors strictly and we can't
use POSIX close() to close a socket.
Fix this by using monkey's wrapper function.
Part of #960

scheduler: use mk_event_closesocket() to close timer->timer_fd

---

plugins/in_tail/tail_file.c

On Windows, text files are normally stored with CRLF. This means we
need to detect '\r' at end of lines and handle hem too, or we will
get an ugly artifact in each data record.
tail.0: [1551370107, {"log"=>"aiueo\r"}]
This patch implements a simple support for it.
*This patch is intended to be merged  after v1.1 release*
Part of #960

in_tail: Add CRLF support to in_tail

---

ci/do-ut
tests/runtime/CMakeLists.txt

* in_cpu/in_disk/in_mem/in_proc is written for Linux not macOS.
ref: https://github.com/fluent/fluent-bit/blob/master/plugins/CMakeLists.txt#L91-L100

runtime tests: Tighten executing runtime tests targets on macOS

---

src/flb_io.c

Applying read(2) to TCP sockets results in a segmentation fault on
Windows, since sockets and file handles are two very different things
on that platform.
This fixes the issue by replacing read(2) with recv(2), which should
work fine both on Windows and Linux.
Part of #960

io: use recv(2) instead of read(2) for portability

---

src/flb_scheduler.c

This is a series of patches that sorts out `flb_sched_request_destroy()`
so that it does not fail with segmentation faults on Windows.
a2b49aa6 scheduler: close communication pipe after invalidating timer
90903a16 scheduler: fix double free of timer->event
Part of #960

scheduler: fix multiple SIGSEGV issues on Windows

---

CMakeLists.txt

To simplify installation process on Windows, this patch configures
cpack to generate an EXE installer on Windows.
You can build one by trying (requires MSVC 2017 and NSIS 3.x):
```
PS> cd build
PS> cmake .. -D CIO_BACKEND_FILESYSTEM=Off
PS> cmake --build .
PS> cpack
```
Part of #960

build: use CPackNSIS to create an EXE installer

---

CMakeLists.txt
src/CMakeLists.txt

In order to set up a program directory structure properly for each
platform, this introduces a set of new variables "FLB_INSTALL_*".
WIth this patch, the directry structure for Windows looks like below:
C:\Program Files\td-agent-bit
├── bin
│   ├── fluent-bit.dll
│   └── fluent-bit.exe
├── conf
│   ├── fluent-bit.conf
│   ├── parsers.conf
│   └── plugins.conf
└── include
   ├── fluent-bit.h
   └── fluent-bit\*.h
... and one for Linux is kept intact.
Part of #960

build: update an installation layout for Windows

---

include/fluent-bit/flb_socket.h
src/flb_io.c

This is a series of patches that introduces `FLB_WOULDBLOCK` to detect
`EWOULDBLOCK` portably.
bc6c97be io: perform EAGAIN checks using FLB_WOULDBLOCK()
3b3b4caf socket: introduce FLB_WOULDBLOCK to handle nonblocking IO portably
With this patch applied, we can handle temporal socket errors reliably both
on UNIX and Windows.
Part of #960

socket: introduce FLB_WOULDBLOCK to handle nonblocking IO portably

---

CMakeLists.txt
include/fluent-bit/flb_dlfcn_win32.h
src/CMakeLists.txt
src/flb_dlfcn_win32.c
src/flb_plugin_proxy.c

This PR adds output plugin proxy Golang support for Windows.
I've confirmed with fluent-bit-go (out_gstdout).
```log
~\GitHub\fluent-bit-go\examples\out_gstdout [master ≡ +3 ~1 -0 !]> make
go build -buildmode=c-shared -o out_gstdout.so .
```
And then I copied `out_gstdout.so` into fluent-bit.exe located folder.
```log
PS> .\bin\Debug\fluent-bit.exe -e .\\bin\\Debug\\out_gstdout.so -i dummy -p tag=debug -o gstdout
```
Fluent-Bit can handle windows dynamic link library (This example uses `.so` but it should use `.dll`):
```log
Fluent Bit v1.1.0
[2019/03/14 18:05:43] [ info] [storage] initializing...
[2019/03/14 18:05:43] [ info] [storage] in-memory
[2019/03/14 18:05:43] [ info] [storage] normal synchronization mode, checksum disabled
[2019/03/14 18:05:43] [ info] …
```

Output proxy go windows

---

plugins/out_es/es.c

While testing out_es on Windows, I noticed that Fluent Bit sometimes
outputs a garbled noise that apparently is a memory dump.
It turned out that it was just because elasticsearch_format() tried
to do printf("%s", buf) where buf is actually not null-terminated.
This patch is a simple fix for it.

out_es: fix buffer overrun on Trace_Output=On

---

src/flb_hash.c

Improve `flb_hash_del` to check also the key when there is only one element in a table.

flb_hash: fix del to compare key

---

tests/runtime/in_simple_systems.c

Previously we used a few clever tricks in order to make our test
cases run robustly on slow servers (e.g. use while loop to absorb
random delays). Still we saw occasional failures on CI servers.
My opinion is that the old implementation was thinking too complex,
ended up introducing another fragility itself. I do not think adding
another pile of tricks would improve the overall situation.
Instead, this patch simplifies the test code significantly (e.g.
use a fixed sleep interval instead of a wait loop), and improve
the stability by making sure each test has enough cushion for
absorbing random delays.
In a nutshell, the new version tests the event generation using the
following schedule:
0  1  2  3  4  5  6  7  8 (sec)
|--C--*--F--C--*--F--C--|
F ... Flush (3 sec interval)
C ... Check if …

tests: make input plugin testing run more stable on Travis CI

---

CMakeLists.txt

Right now, we get 3000+ warnings while building fluent-bit on MSVC.
Roughly 80% of them comes from dependent libraries. For example,
msgpack alone contributes more than 2000 warnings.
Built with /W4 : 3804 warnings
Built with /W3 :  828 warnings
I believe /W4 is too overwhelming to provide any insight on the specific
code lines of Fluent Bit. Let's reduce the verbosity level by one.
After this patch, I'm planning to work on the remaining 828 warnings to
make our Windows build process less clunky.

build: use /W3 for MSVC to get less warnings

---

CMakeLists.txt
include/fluent-bit/stream_processor/flb_sp.h
lib/rbtree/CMakeLists.txt
lib/rbtree/README.md
lib/rbtree/rbtree.c
lib/rbtree/rbtree.h
src/CMakeLists.txt
src/stream_processor/CMakeLists.txt

Steps to reproduce:
$ git clone https://github.com/fluent/fluent-bit/
$ cd fluent-bit/build
$ cmake ..
$ make
will fail with "undefined reference" errors to rbtree functions.
This is because we do not build monkey in the default configuration,
so functions in monkey/deps/rbtree are not available.
This fixes the error by having a copy of rbtree in fluent-bit/lib and switches
to it when we do not have one though lib/monkey.

Fix an compilation error in master HEAD due to stream-processor

---

src/flb_parser.c

Right now, the follwing command results in an error on startup on Windows:
PS> .\bin\fluent-bit -R ..\conf\parsers.conf ...
This is just because flb_parser is too strict on tm_gmtoff support,
and would abort if SOME of the parser definitions include '%Z'/'%z'
in their Time_Format.
In truth, it's perfectly fine to use these parsers on Windows, since
our strptime implementation can handle %Z/%z without any problems. So
let's just relax the restriction here.
Part of #960

parser: do not abort instantly on '%z'/'%Z' on Windows

---

src/CMakeLists.txt

Fluent Bit uses "pthread" to manage logging workers, both on Unix and
Windows. However, since Windows does not have a native pthread support,
we instead use the emulation layer in mk_core/external/winpthreads.c.
This means we should not try to link pthread by -lpthread on MSVC, or
the linker will emit the following warnings.
warning LNK4044: unrecognized option '/lpthread'; ignored
*This patch is intended to be merged after v1.1 release.*
Part of #960

build: don't try to link pthread on Windows

---

include/fluent-bit/flb_input.h
include/fluent-bit/flb_output.h

This fixes a couple of type mismatch warnings on MSVC
* Cast the argument explicitly to avoid "incompatibe type" warnings
* Add `void` argument to functions which we pass to co_create().
The reason why I call these warnings as "salient" is that they are cloned
to other files by `#include`, resulting tons of warnings in count.

Fix several salient warnings on MSVC

---

src/flb_input.c

Currently, using the flb_input.c function flb_input() returns an input ffd that can be
used to configure the plugin instance with subsequent calls to flb_input_set(). However,
the function instance_id() in flb_input.c will only return a unique ffd for input plugin
instances that are the same type; if instance_id() is called twice with two different
plugin types, it will return the same ffd both times. This patch fixes the issue by examining
all currently assigned ffds rather than checking plugin type.
Signed-off-by: Robert LaMarre <robert.lamarre@viasat.com>

input: return a unique ffd for each input plugin instance

---

appveyor.yml
ci/do-ut.ps1
lib/rbtree/rbtree.h
tests/internal/stream_processor.c

Enable stream_processor feature on MSYS2ed Windows.
Also enable stream_processor test case on AppVeyor.

Stream processor on MSYS2ed Windows

---

include/fluent-bit/flb_sds.h
include/fluent-bit/flb_thread_libco.h
include/fluent-bit/flb_thread_pthreads.h
include/fluent-bit/flb_time.h

This is a series of patches that fix compiler warnings on MSVC.
Before: 873 Warnings
After : 627 Warnings
The gist is that MSVC is rather strict on types than GCC and clang,
and we needed some explicit type casts to prevent it complaining.

More on compiler warnings on MSVC

---

include/fluent-bit/flb_pipe.h
plugins/in_tail/tail_signal.h
src/flb_pipe.c

This migrates a few remaining raw EAGAIN checks. With this merged,
all EAGAIN handlings in Fluent Bit are Windows-compatible.
I added a new macro FLB_PIPE_WOULDBOCK instead of using the existing
flb_pipe_check_eagain() here. The reason for doing this is coding coherency.
That is, previously we did:
* for sockets, define a "macro" FLB_WOULDBLOCK to check EAGAIN.
* for pipes, define a "function" flb_pipe_check_eagain() to check EAGAIN.
So similar problem, different solutions. I liked the design we used
for socket, so removed the function and introduced a new macro.

Clean up EAGAIN checks on pipes

---

Dockerfile

Signed-off-by: Warren Fernandes <wfernandes@pivotal.io>

Add required dependencies for docker build

---

cmake/windows-setup.cmake
plugins/out_kafka/CMakeLists.txt

librdkafka is already compatible for MinGW and MSVC.
For MSVC, we should avoid to link libpthread.
---
I've confirmed with the folllowing fluent-bit settings:
```ini
[INPUT]
Name  dummy
[OUTPUT]
Name        kafka
Match       *
Brokers     local-kafka-server-address:9092
Topics      test
Timestamp_Format iso8601 # or double
Timestamp_Key @timestamp
Format msgpack # or json
rdkafka.log.connection.close false
rdkafka.request.required.acks 1
```
Part of #960.

out_kafka: Make MSVC compatible

---

src/flb_hash.c

Make `flb_hash_add` to copy the key up to the passed key_len.

hash: Improve flb_hash_add to copy the key up to the passed key_len

---

plugins/out_forward/forward.c

Right now, Fluent Bit forces us to set up a common secret (Shared_Key)
if TLS/SSL encryption is in use. The opposite is also true and we can't
use a common secret on a plain-text connection.
Since these two features are not actually depending each other, Fluent
Bit should allow users to set up them independently. This fixes it.
For example, this allows users to set up the configuration as follows:
[Output]
Name forward
Host 127.0.0.1
Self_Hostname example.com
Shared_Key some-secret-key
I have tested this patch with Fluentd v1.4.2, and confirmed it works
fine on the following patterns.
No  | Test Pattern           |  Working?  |
--- | ---------------------- | ---------- |
1  | TLS + Shared_Key       |  OK        |
2  | TCP + Shared_Key       |  OK        |
3  | TLS without Shared Key |  OK …

out_forward: make Shared_Key usable without TLS (and vice versa)

---

.travis.yml

This needs https://github.com/fluent/fluent-bit/pull/1271 merged first.
E.g. this will show a failure in CI that was being masked, the above MR will resolve the underlying failure.
Remove `bats` which was vestigal, not in use
Add explicit docker service need

CI: remove `bats` and nodejs from Docker canary build

---

tests/internal/CMakeLists.txt

Right now, the following command fails with a compile error.
$ cmake -DFLB_DEV=On -DFLB_STREAM_PROCESSOR=Off ..
$ make
...
error: struct flb_config’ has no member named ‘stream_processor_tasks
This is just due to cmake trying to compile the test suite for stream
processor even when the feature is not available (FLB_STREAM_PROCESSOR=Off).
This fixes it.

tests: internal: fix a compilation error on FLB_STREAM_PROCESSOR=Off

---

include/fluent-bit/flb_plugin_proxy.h
src/flb_output.c
src/flb_plugin_proxy.c
src/proxy/go/go.c
src/proxy/go/go.h

plugin_proxy: pass ctx to remote plugins (#1000)
This change is intended to allow for the flush functions of Go plugins to be able to determine what output plugin instance they are flushing messages for. Currently, this is not possible as the existing flush function does not receive a context.
This change introduces a new struct called flb_plugin_proxy_context. This context is used as the instance context. The flb_plugin_proxy_context contains a pointer to a context set by the init function of the Go plugin. The remote Go plugin can set whatever value they want for their context and fluent-bit will pass it into the remote FLBPluginFlushCtx. FLBPluginFlush behaviour remains the
same.
This change is backwards compatible with plugins that are already compiled. It was manually tested with Go …

plugin_proxy: pass ctx to remote plugins

---

plugins/out_stackdriver/gce_metadata.h

Without this, the plugin generates an invalid request with a relative
path.

out_stackdriver: add missing / to URI

---

plugins/in_systemd/systemd.c
plugins/in_systemd/systemd_config.c
plugins/in_systemd/systemd_config.h

Journald may write logs faster than fluent-bit is able to forward.
For example, the receiving part or network may be too slow.
In such situation, journald will rotate (delete) a journal file that is being read by fluent-bit.
Then, sd_journal_next() will return error (ret_j<0). The current master branch code does not address
such case. Therefore, in_systemd_collect() will be restarted in order to retry reading the very same 
deleted log file. It will never succeed, thus leaving fluent-bit in an endless loop.
The proposed PR fixes this endless loop by detecting such a case and returning an error instead of FLB_SYSTEMD_MORE.
* setup docker logging into systemd;
* disable systemd-journald throttling
```bash
cat <<EOF > /etc/systemd/journald.conf.d/0-ratelimit.conf
[Journal] …
```

in_systemd: fix endless loop on reading a rotated journal

---

GOLANG_OUTPUT_PLUGIN.md

Minor updates to the `GOLANG_OUTPUT_README` to be a little more consistent with `fluent-bit-docs/development/golang_plugins.md`
Signed-off-by: Warren Fernandes <wfernandes@pivotal.io>

doc: update golang plugin example

---

include/fluent-bit/flb_compat.h
src/fluent-bit.c

Fluent Bit has a feature that allows users to use a relative path
in the main configuration file. For example, if you have the
following files in the same directory:
PS > ls C:\Program Files\td-agent\conf\
parsers.conf fluent-bit.conf
Then you can just set "parsers.conf" to Parser_File as below:
[SERVICE]
Flush       5
Daemon      Off
Parser_File parsers.conf
Previously this feature did not work properly on Windows, due to
its path schema being incompatible with Unix. This fixes it.

core: allow use of relative paths in configuration files on Windows

---

plugins/out_stdout/stdout.c

Some terminal programs buffer stdout in memory before printing, so
emitted records may not appear on the screen promptly.
This is very confusing especially when debugging ("Is there something
wrong with my fix? Or is it just due to buffering of I/O?).
Let's flush stdout in each cb_flush call to avoid confusion.

out_stdout: call fflush(stdout) at the end of cb_stdout_flush()

---

plugins/out_es/es_bulk.h

Setting Generate_Id with ES output creates corrupted JSON output #1308
When the UUID was expanded to 37 to include dashes the header size was not incremented accordingly ...
Can this get merged quickly so we can use yum to update our severs.  I opened #1308 weeks ago and ended up debugging and fixing this for you.

Setting Generate_Id with ES output creates corrupted JSON output #1308

---

.gitlab-ci.yml
.gitlab/ci-templates.yml

This merge request modified the GitLab CICD Process to take advantage of templates. Thus cleaning code up. In addition it adds in the additional build targets.
It does not add in a Clang build target. The reason for this is no supported clang docker image has been selected. Once it has been, A new merge request should be done to add support for clang.

Improve GitLab CICD Pipeline

---

plugins/out_forward/forward.c
plugins/out_forward/forward.h

This patch enables fluentd forward-protocol "chunk" option
where client waits ack from server.
This feature is very useful for flow control of fluentd servers.
New Configuration parameters:
* **require_ack_response** (Boolean)
Send chunk option to server and wait for ACK response
before continue.
default: off
* **send_options** (Boolean)
Send options in data messages. By default have "size" field.
default: off, but require_ack_response implies on.

forward: implement 'require_ack_response'

---

include/fluent-bit/flb_compat.h
src/flb_plugin.c
src/flb_plugin_proxy.c

Since MSVC does not provide dlfcn.h, we need to use a stub
implementation in flb_dlfcn_win32.c on Windows.
This patch allows flb_compat.h to abstract away the difference,
and should make flb_plugin.c compilable on Windows.

plugin: include flb_compat.h for Windows compatibility

---

CMakeLists.txt

Right now, running cmake in a clean fluent-bit repository fails with
the following error.
$ git clone https://github.com/fluent/fluent-bit
$ cd build
$ cmake ..
CMake Error at CMakeLists.txt:334 (add_subdirectory):
... which is just because of cmake trying include sqlite3 instead
of libco wrongly. This is a trivial fix for the bug.

build: fix cmake to include FLB_PATH_LIB_CO properly

---

CMakeLists.txt
appveyor.yml

This teaches cmake to create a ZIP archive that contains a full set
of binaries of fluent-bit. Here is how a ZIP archive looks like:
td-agent-bit-1.2.0-win32.zip
├── bin
│   ├── fluent-bit.dll
│   └── fluent-bit.exe
├── conf
│   ├── fluent-bit.conf
│   ├── parsers.conf
│   └── plugins.conf
└── include
└── fluent-bit.h
This makes running fluent-bit trivial for Windows users, since all
one needs is just to download the archive and unzip it.

build: create a simple ZIP archive for Windows

---

plugins/in_mqtt/mqtt_prot.c

While parsing the length of a MQTT packet, the buf_pos is already
incremented, making it no longer necessary to do it once more once the
length is determined.
Fixes #672.
Signed-off-by: Jan Willem Janssen <j.w.janssen@lxtreme.nl>

in_mqtt: fix incorrect MQTT length handling

---

plugins/out_stackdriver/stackdriver.c
src/flb_oauth2.c

Fixes #1348 
- oauth2
When oauth2 module creates upstream to retrieve an token, if the access using ipv4 is failed, it will attempt to connect to with ipv6.
- stackdriver
Support `ipv6` param in out_stackdriver config.
If set `ipv6 on`, create upstream connection for stackdriver logging with FLB_IO_IPV6 mode.

Oauth2 and stackdriver support ipv6

---

.gitlab-ci.yml

This points to the correct Dockerfile to fix failing builds.

Resolve GitLab-CI Missing Dockerfile

---

plugins/filter_modify/modify.c

To fix #1077 
filter_modify doesn't copy event if it is not matched at `apply_modifying_rules`. ( only logging)
```c
static inline int apply_modifying_rules(msgpack_packer * packer,
msgpack_object * root,
struct filter_modify_ctx *ctx)
{
msgpack_object ts = root->via.array.ptr[0];
msgpack_object map = root->via.array.ptr[1];
if (!evaluate_conditions(&map, ctx)) {
flb_debug
("[filter_modify] : Conditions not met, not touching record");
return 0;
}
```
So some events will removed by filter_modify when multiple events come and some of events are not matched.
@jesk78 's config is https://github.com/fluent/fluent-bit/issues/1077#issuecomment-463445403
In that case,  4 events are expected.
```
[0] test: [1562233919.205549498, {"mickey"=>"mouse", "do"=>"like"}]
[1] test: [1562233919.205562366, …
```

filter_modify:copy original event if condition is not matched(#1077)

---

tests/runtime/filter_modify.c

I added test case to detect #1077 issue.
In this case, 3 events are pushed and fluent-bit appends key value if "cond" is "true".
```
{"cond":"false", "data": "something"}
{"cond":"true", "data": "something"}
{"data": "something"}
```
If filtered events are 3 (no events are dropped), it means #1077 is addressed.

tests: modify add test case to detect issue #1077

---

plugins/filter_nest/nest.c
tests/runtime/filter_nest.c

To fix #1434 
The issue #1434 is similar to #1077 .
filter plugin drops some events if they are not matched condition.
test data:
```
$ for i in `seq 6 1 10`;do echo '{"key'$i'": "somevalue"}';done | tee bad_batch.log
{"key6": "somevalue"}
{"key7": "somevalue"}
{"key8": "somevalue"}
{"key9": "somevalue"}
{"key10": "somevalue"}
```
Execute from cmdline. filter_nest checks `key6`.
```
fluent-bit -v -R ../../conf/parsers.conf   -i tail -p path=./bad_batch.log -p "Parser=json" -F nest  -p 'Operation=nest' -p 'Wildcard=key6' -p "Nest_under=nested" -m '*' -o stdout
```
Result: (only 1 event. Other events which doesn't have `key6` are dropped.)
```
[0] tail.0: [1562767117.577847002, {"nested"=>{"key6"=>"somevalue"}}]
```
Expected: 
```
[0] tail.0: [1562978400.221393545, …
```

filter_nest: copy original event if condition is not mached

---

src/flb_pack.c

Allows logs form Kubernetes pods having labels or annotations containing '/' in the name, which is not a valid GELF field name.
Also changes the log level to `error` and adds the invalid char position to "invalid key char" errors.
Fixes #1070 , #1291 .

[gelf] Replace '/' with '_' in keys when converting from msgpack.

---

plugins/in_winlog/in_winlog.c

This is the default behaviour of Windows and very likely what users
expect. Let's just follow the convention here.
For details, read the official manual page of OpenEventLog().
lpSourceName
The name of the log. If you specify a custom log and it cannot
be found, the event logging service opens the Application log;

in_winlog: listen to 'Application' channel by deafult

---

plugins/out_influxdb/influxdb_bulk.c

According to the new docs of the line protocol, multiple backslashes
must be escaped.
https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_reference/#note-on-backslashes
Signed-off-by: disigma <yang.yu@disigma.org>

out_influxdb: add backslashes escaping.

---

include/fluent-bit/flb_compat.h

This is an attempt to make `flb_compat.h` less tangled.
* Add comments to explain what these macros do and why we need them.
* Replace a compat function for `timegm` with a trivial macro.
* Make `localtime_r` own function instead of relying on an undocumented API.
I can confirm it works fine on my development machine.

compat: clean up compat macros in flb_compat.h

---

src/flb_lib.c
src/flb_log.c

From the `STDARG(3)` man page:
> Note that each call to va_start() must be matched by a call to va_end(), from within the same function.

core: add missing va_end() on exception

---

plugins/in_mqtt/mqtt_prot.c

This fixes how packet identifiers are encoded in acknowledgements to publish events with a QoS > 0.
Fixes #1464
Signed-off-by: Jan Willem Janssen <j.w.janssen@lxtreme.nl>

in_mqtt: properly encode packet identifier

---

src/flb_gzip.c

Incrementing a void pointer is GCC extension and not allowed in the
standard C. To be portable, we need to cast the pointer to `(char *)`.
This should fix the testing failure occurring on AppVeyor.

gzip: fix compilation errors on Microsoft Viasual C++

---

plugins/in_mqtt/mqtt_prot.c

A ping response has no payload, but it was encoded with a payload length of 2, confusing many MQTT clients and causing connection timeouts/drops.
Fixes #1469.
Signed-off-by: Jan Willem Janssen <j.w.janssen@lxtreme.nl>

in_mqtt: fix ping response

---

src/flb_gzip.c

This resolves the following warning occurring on GCC.
> warning: pointer targets in assignment from ‘char *’ to
> ‘uint8_t *’ {aka ‘unsigned char *’} differ in signedness
Since the buffer pointer was declared as (uint8_t *), I should have
casted the value to unsigned char, not signed one. Fix it.

gzip: fix GCC warnings about signedness

---

src/flb_router.c

Needed this little build fixup for `-DFLB_REGEX=No -DFLB_PARSER=No` to work.
Otherwise:
```
$ cmake -DFLB_REGEX=No -DFLB_PARSER=No ..
..
$ make -j4
...
[ 49%] Building C object src/CMakeFiles/fluent-bit-static.dir/flb_upstream.c.o
[ 49%] Building C object src/CMakeFiles/fluent-bit-static.dir/flb_upstream_ha.c.o
[ 49%] Building C object src/CMakeFiles/fluent-bit-static.dir/flb_upstream_node.c.o
[ 50%] Building C object src/CMakeFiles/fluent-bit-static.dir/flb_router.c.o
[ 50%] Building C object src/CMakeFiles/fluent-bit-static.dir/flb_worker.c.o
/home/nigels/dev/fluent-bit/src/flb_router.c:28:10: fatal error: onigmo.h: No such file or directory
#include <onigmo.h>
^~~~~~~~~~
compilation terminated.
src/CMakeFiles/fluent-bit-static.dir/build.make:782: recipe for target …
```

router: Conditional inclusion of onigmo.h for regex support

---

include/fluent-bit/stream_processor/flb_sp_timeseries.h

According to IEEE standard, the expression "0.0 / 0.0" should return NaN,
but not all C compilers (e.g. MSVC 2017) adhere it.
Let's use nan() in math.h (which is added in C99) for better portability.

sp: use nan() to produce a NAN

---

src/flb_log.c

Return value of a function 'localtime_r' is dereferenced from 356 line
without checking whether the return value of localtime_r(2) is NULL or not
Signed-off-by: aniketoss <aniketoss@naver.com>

log: check localtime_r(2) is not NULL

---

plugins/filter_nest/nest.c

To fix #1540 
filter_nest doesn't free a temporary buffer when the condition is not matched.
a.conf:
```
[INPUT]
Name cpu
[FILTER]
Name nest
Match *
[OUTPUT]
Name null
Match *
```
valgrind reports leakage information using a.conf.
My patch is to fix it.
```
$ valgrind ../bin//fluent-bit -c a.conf 
==26867== Memcheck, a memory error detector
==26867== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==26867== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==26867== Command: ../bin//fluent-bit -c a.conf
==26867== 
Fluent Bit v1.3.0
.
.
.
^C[engine] caught signal (SIGINT)
[2019/08/30 19:47:35] [ info] [input] pausing cpu.0
==26867== 
==26867== HEAP SUMMARY:
==26867==     in use at exit: 32,768 bytes in 4 blocks
==26867==   total heap usage: 170 allocs, 166 …
```

filter_nest: free unused temporary buffer(#1540)

---

src/flb_output.c

Came across this segfault:
```
==21111== Invalid free() / delete / delete[] / realloc()
==21111==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==21111==    by 0x15476A: flb_free (flb_mem.h:107)
==21111==    by 0x154BA2: flb_output_free_properties (flb_output.c:87)
==21111==    by 0x154D07: flb_output_instance_destroy (flb_output.c:141)
==21111==    by 0x154DD2: flb_output_exit (flb_output.c:170)
==21111==    by 0x15C546: flb_engine_shutdown (flb_engine.c:564)
==21111==    by 0x14499C: flb_signal_handler (fluent-bit.c:235)
==21111==    by 0x5853F1F: ??? (in /lib/x86_64-linux-gnu/libc-2.27.so)
==21111==    by 0x5936BB6: epoll_wait (epoll_wait.c:30)
==21111==    by 0x3D00EB: _mk_event_wait (mk_event_epoll.c:345)
==21111==    by 0x3D03DB: mk_event_wait …
```

output: fixup for SDS alloc/free matching for TLS parameters

---

include/fluent-bit/stream_processor/flb_sp_parser.h
include/fluent-bit/stream_processor/flb_sp_timeseries.h
src/stream_processor/parser/flb_sp_parser.c
src/stream_processor/parser/sql.l
src/stream_processor/parser/sql.y
tests/internal/stream_processor.c

This pull request adds `TIMESERIES_FORECAST_R(x, y, v, maximum_x)` function, which is the same as `TIMESERIES_FORECAST_R`, but returns the forecast of number of future points for `x`, when the value of `y` becomes `v`.
To prevent returning infinity when such value is estimated to be unreachable in future (the slope of the line in Linear Regression calculation is zero or negative), the function returns `maximum_x` passed as 4th parameter.

sp: add timeseries function TIMESERIES_FORECAST_R

---

ci/appveyor-download

When we release a new version, we need to download build artifacts
from AppVeyor and in turn transfer them to our website.
This adds a script to automate the process. Now we can release Windows
installers just by the following steps.
$ ./appveyor-download v1.2.2
$ scp td-agent-bit-1.2.2-* fluentbit.io

ci: add a script to download Windows installers from AppVeyor

---

plugins/out_datadog/datadog.c
plugins/out_datadog/datadog.h
plugins/out_datadog/datadog_conf.c

Datadog Http(s) logs API required to send application logs into the
JSON key `message`. By default, the plugin searches for the key `log` and
remap the value to the key `message`.
If never the application logs are associated with another key than `log`
you can specify it with the parameter: `dd_message_key`

[out_datadog] allow remapping entry to `message` key

---

plugins/in_syslog/syslog.h
plugins/in_syslog/syslog_conf.c
plugins/in_syslog/syslog_server.c

It solves a common pain point when using the `in_syslog` plugin. Here
is an example usage:
[INPUT]
Name      syslog
Tag       syslog_data
Parser    syslog-rfc3164
Path      /tmp/fluent-bit.sock
Mode      unix_udp
Unix_Perm 0777
Without this, users are required to keep track of restarts of fluent-bit
and manually set file permission on the UNIX socket it creates. Let's
just make it work seamlessly without such manual interventions.
This resolves the user reports #1479 and #1493.

in_syslog: add 'Unix_Perm' option

---

plugins/in_thermal/in_thermal.c
plugins/in_thermal/in_thermal.h

Some systems have no thermal device. (e.g. virtual machine / docker env)
This is a `ls` output of Ubuntu 18.04 on VMWare
```
$ ls /sys/class/thermal/
cooling_device0
$
```
In such cases, fluent-bit registers in_thermal as input plugin ,
but no records will be emitted.
My patch is to detect thermal device on `cb_init`.
If no device is found, fluent-bit doesn't register in_thermal plugin and reports error.

in_thermal: Add thermal device detection on init.

---

include/fluent-bit/flb_endian.h
plugins/in_collectd/netprot.c

It turned out that endian.h is non-standard and UNIX platforms
disagree with each other on how to provide the functionality.
- glibc provides <endian.h>.
- BSD platforms privies <sys/endian.h>.
- macOS does not provide endian.h but does provide similar macros
in libkern.
This adds a convenient portability layer for endian.h. With this,
I can confirm that in_collectd compiles and runs fine on macOS.
Resolves: #1561

in_collectd: fix compilation errors due to endian.h

---

src/flb_io_tls.c
src/flb_upstream.c

This fix notifies the peer that the (SSL) connection is being closed
before closing the socket.
Tested against rsyslog 8.1901.0 using GnuTLS,
"The TLS connection was non-properly terminated" errors are gone.
Signed-off-by: Joost Coelingh <joost.coelingh@eu.equinix.com>

upstream: Do ssl_close_notify before closing the socket

---

src/flb_unescape.c

In `flb_unescape_string_utf8`, if the in_buf string starts with an esacped
single quote (\\'), the ch variable would be uninitialized when used in
`esc_out = u8_wc_toutf8(temp, ch);`.

unescape: fix use of uninitialized variable if string starts with \'

---

src/flb_dlfcn_win32.c

* Plug memory leak from `FORMAT_MESSAGE_ALLOCATE_BUFFER`
* Use more appropriate buffer size and use `FormatMessageA` instead of `FormatMessage`

proxy: windows: Plug memory leak and tweak code

---

src/flb_sha512.c
tests/internal/sha512.c

If the length of an input string is exactly 127 bytes, this line
produces:
memset(s->buf + 128, 0, 0);
... where s->buf is an array of 128 integers.
The probability is that it does no harm since almost all memset()
implementations don't touch the buffer when n = 0, but it's not
guaranteed by the spec. Let's just play it safe here.

sha512: fix a potential buffer overrun

---

plugins/in_serial/in_serial.c

This fixes a build issue on macOS.
```
[ 78%] Building C object plugins/in_serial/CMakeFiles/flb-plugin-in_serial.dir/in_serial.c.o
/Users/<>/src/fluent/fluent-bit/plugins/in_serial/in_serial.c:330:40: error: use of undeclared identifier 'in_serial_collect'; did you
mean 'cb_serial_collect'?
in_serial_collect,
^~~~~~~~~~~~~~~~~
cb_serial_collect
/Users/<>/src/fluent/fluent-bit/plugins/in_serial/in_serial.c:99:12: note: 'cb_serial_collect' declared here
static int cb_serial_collect(struct flb_input_instance *in,
^
1 error generated.
```

in_series: Fix typo in_ => cb_

---

plugins/out_forward/forward.c
plugins/out_forward/forward.h

Fluentd has support for username/password authentication in addition
to the shared secret (shared_key). This teaches Fluent Bit about it.
To enable the support, put the following to your configuration.
[OUTPUT]
Name       forward
Shared_Key some-shared-key
Username   fluent-bit
Password   password
This patch should resolve the issue #596.

out_forward: add support for user-based authentication

---

.gitignore
conf/parsers.conf

The default nginx parser provided does not properly match logs from nginx. After hunting around I found [this comment](https://github.com/fluent/fluent-bit/issues/1041#issuecomment-457795464) from the fluentbit issues which after testing a bit seems to work as expected.
I think it makes sense to update the parsers list here and on the `fluent-bit-kubernetes-logging` repo.

Fix Nginx parser regex

---

src/flb_hash.c

`ht->total_count` is assigned 0 twice consecutively.
https://github.com/fluent/fluent-bit/blob/262267287641d6d54bb62f0a0ada1c76a5bd40b4/src/flb_hash.c#L123-L125

hash: remove duplicate assignment

---

plugins/in_cpu/cpu.c

Value of expression `*p++` is not used.

in_cpu: remove unnecessary pointer dereference

---

plugins/out_datadog/CMakeLists.txt
plugins/out_datadog/datadog.c
plugins/out_datadog/datadog.h
plugins/out_datadog/datadog_conf.c
plugins/out_datadog/datadog_remap.c
plugins/out_datadog/datadog_remap.h

Implement attributes to tags remapping to tag ecs metadata
To activate the remapping, specify configuration flag `provider` with value `ecs` as following:
```
[OUTPUT]
Name        datadog
Match       *
Host        http-intake.logs.datadoghq.com
TLS         on
apikey      <my-datadog-api-key>
dd_service  my-app-service
dd_source   my-app
dd_tags     team:logs,foo:bar
provider    ecs
```

out_datadog: implement attributes to tags remapping

---

plugins/out_stackdriver/stackdriver.c
plugins/out_stackdriver/stackdriver.h
plugins/out_stackdriver/stackdriver_conf.c

As per google cloud documentation there is ability to set severity log
level information for each log entry.
https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#LogSeverity
This patch modifies pack entries and inserts "severity" field with one
of log levels:
- EMERGENCY
- ALERT
- CRITICAL
- ERROR
- WARNING
- NOTICE
- INFO
- DEBUG
This enables better ability to filter logs in stackdriver.
Log level information / severity level is retrived from payload object
(parsed log entry). Key for which fluent-bit looks inside payload is
configurable by "severity_key" stackdriver output option.
Example:
[OUTPUT]
Name            stackdriver
Match           *
severity_key    level
With this configuration stackdriver output would look inside payload
for "level" key and compare its value …

out_stackdriver: add functionality to send log level info to stackdriver

---

plugins/out_datadog/datadog_remap.c

`uint` is not a standard type and many compilers do not recognize it.
This should fix the testing failure occurring on AppVeyor.

out_datadog: use 'unsigned int' instead of 'uint'

---

include/fluent-bit/flb_io_tls.h
include/fluent-bit/flb_output.h
src/flb_io_tls.c
src/flb_output.c

Addresses #1312. Please let me know what you guys think! :-)

io: tls: support SNI routing for outputs

---

plugins/out_influxdb/influxdb_bulk.c

Refer to influxdata git issue
https://github.com/influxdata/docs.influxdata.com/issues/1295
Although the line protocol doesn't mention about escaping backslash, however, consider using fluent-bit to process docker container logs, sample data is below
log="msg=\\\"faulty\\\"",stream="stderr",time="2019-02-15T01:56:37.53737463Z"
out-influxdb plugin will escape it to
log="msg=\\\\\"faulty\\\\\"",stream="stderr",time="2019-02-15T01:56:37.53737463Z"
If we post this data to influxdb, it will report 400 error
curl -i -XPOST 'http://127.0.0.1:8086/write?db=fluentbit' --data-binary 'faultylog log="msg=\\\\\"faulty\\\\\"",stream="stderr",time="2019-02-15T01:56:37.53737463Z"'
This fix is added to escape backslash so the correct post request will be and it can be accepted by influxdb
curl -i -XPOST …

Add backslash escape for output_influxdb plugin

---

plugins/in_tail/tail_file.c
plugins/in_tail/tail_scan_glob.c

Call `flb_tail_file_name()` for a normalized path and then perform a
duplication chack using the returned path. We normally don't need to
do this, but we _do_ need in order to handle symlinks properly on OSX.
$ ls -l /tmp/nginx.log
20 Sep 26 18:15 /tmp/nginx.log -> /private/tmp/nginx.log
This patch should resolve the bug that in_tail registers the same file
again and again on macOS (#1591)

in_tail: prevent file duplication on macOS

---

src/flb_dlfcn_win32.c

Previous PR #1577 still has a pitfall.
@ashie advised me to plug this pitfall.

Remove needless typecast and 

---

Dockerfile.debug

ls failed on the debug docker images with the following message:
```
$ ls
ls: can't open '.': Value too large for defined data type
```
This patch changes the Busybox version to Glibc and bumps it
from 1.30.0 to 1.31.0.
Upstream issues:
- https://github.com/GoogleContainerTools/distroless/issues/225
- https://bugs.busybox.net/show_bug.cgi?id=11651
Signed-off-by: Mario Marín <mmfmarin@gmail.com>

dockerfile: fix ls in debug Docker image

---

plugins/out_forward/forward.c

According to [the Forward Protocol Specification](https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1):
> *auth* a binary string of salt to generate digest for user authentication
> (authentication not required if it's empty)
But in practice, Fluentd always include an `auth` token in HELO requests
regardless of whether it actually requires password auth or not.
This patch fixes the implementation to use an empty username and password
by default, and generate a PONG response accordingly.
This patch should fix #1612.

out_forward: try authenticate with empty username/password by default

---

src/flb_utils.c

When we encode a multi-byte character in UTF-8 strings, we encode
each character in the format of '\\uXXXX' (e.g. 'à' => "\\u00e0").
Hence we use 6 bytes per character.
However, we previously did:
hex_bytes = flb_utf8_len(str + i);
if ((available - written) < (2 + hex_bytes)) {
return FLB_FALSE;
}
to see if the buffer has an enough space, and it almost always
miscalculated the byte size required; For instance, (2 + hex_bytes)
would evaluate to 4 (instead of 6) for 'à'.
This fixes the bug and should make flb-it-pack run fine on arm64.

utils: avoid overflowing string buffer in flb_utils_write_str()

---

plugins/out_es/es.c

This patch introduces logging of response payloads from the server when the status code is not 200 or 201.

es_out: trace log payload for HTTP statuses > 201

---

plugins/in_mem/proc.c

To fix #1625  .
The return value of  human_readable_size() is also thrown away.
My patch is to use it.

in_mem: don't discard return value of human_readable_size(#1625)

---

src/flb_utils.c
tests/internal/utils.c

This fixes the memory issue pointed out by https://github.com/fluent/fluent-bit/pull/1633#issuecomment-539936507.
The current flb_utils_write_str() tries to read "ahead" to decode
a multibyte UTF-8 sequence. While doing so, it never checks the
boundary of the input buffer.
This means that if we pass a truncated UTF-8 string like "\xe3",
it will read _beyond_ the boundary of the buffer and potentially
cause a crash.
This fixes the bug, and also add corresponding test cases for it.

utils: fix buffer overrun on invalid UTF-8 characters

---

.travis.yml

We're right now seeing persistent test failures on Travis (arm64/clang).
* https://travis-ci.org/fluent/fluent-bit/builds/601256615
* https://travis-ci.org/fluent/fluent-bit/builds/602281393
* https://travis-ci.org/fluent/fluent-bit/builds/601502335
I noticed that Travis downgraded the clang version to 3.8 since last week's
build and coincidentally the failure started to occur (Before that build,
Travis used clang 6.0.0 -- I'm not sure what made it switch).
This patch tweaks travis.yml so that Travis uses clang-6 consistently.

build: fix unit test failures occurring on Travis (arm64/clang)

---

CMakeLists.txt

This change removes the message: `configure: WARNING: unrecognized options: --enable-cc-silence` when build fluent-bit.
The flag was replace by --disable-cc-silence in jemalloc v4.0.0  https://github.com/jemalloc/jemalloc/commit/644d414bc9ab52efbbf7ebeb350170106ec1f937

build: remove jemalloc flag --enable-cc-silence

---

plugins/in_tcp/tcp_conn.c

Currently, the event callback discards the received data when
parse_payload_none() returns a non-positive code, whereas it actually
means "Please retry later when you received the remaining data".
This was causing data loss when in_tcp received a long line (a few
hundred kilobytes in length.). 
This patch should resolves #1702.

in_tcp: prevent tcp_conn_event() from truncating data

---

cmake/windows-setup.cmake

We received a bug report that pointed out "filter_nest" being absent
from Windows build.
A basic testing reveals the plugin was already Windows-compatible
and all we needed was to turn on the compile flag on Windows. This
patch contains that changeset.

build: enable "filter_nest" on Windows

---

src/fluent-bit.c

Signed-off-by: Nigel Stewart <nigels@nigels.com>
As a follow-up to https://github.com/fluent/fluent-bit/pull/1198
Clarify how to get trace logging, if available.
```
$ bin/fluent-bit -h
Usage: fluent-bit [OPTION]
Available Options
-b  --storage_path=PATH	specify a storage buffering path
-c  --config=FILE	specify an optional configuration file
-d, --daemon		run Fluent Bit in background mode
-f, --flush=SECONDS	flush timeout in seconds (default: 5)
-F  --filter=FILTER	 set a filter
-i, --input=INPUT	set an input
-m, --match=MATCH	set plugin match, same as '-p match=abc'
-o, --output=OUTPUT	set an output
-p, --prop="A=B"	set plugin configuration property
-R, --parser=FILE	specify a parser configuration file
-e, --plugin=FILE	load an external plugin (shared lib)
-l, --log_file=FILE	write log …
```

Clarify info, debug and trace logging modes for fluent-bit CLI

---

lib/tutf8e/CMakeLists.txt
lib/tutf8e/codegen.py
lib/tutf8e/src/tutf8e.c

In relation to Issue #1753 and PR #1752 
`-std=c90` is not quite sufficent, due to `inline`

lib: tutf8e: C99 baseline compiler support

---

plugins/in_stdin/in_stdin.c

As reported in Issue #1733 - stdin input plugin adds timestamp unconditionally
According to the documentation the following format is supported:
https://docs.fluentbit.io/manual/input/stdin
```
2. [ time, { map => val, map => val, map => val } ]
```
This change ensures that JSON array data is passed through without modification.
Last observed to work in `1.13.8`, still seems like a reasonable and useful behaviour.

in_stdin: Restore documented JSON array handling

---

plugins/out_datadog/datadog.c
plugins/out_datadog/datadog.h
plugins/out_datadog/datadog_conf.c

Introduce a new plugin parameter: `compression`.
`If compression=="gzip"`, the http payload is send compressed in gzip
format.
By default the compression is not activated.

[out_datadog] Add gzip http payload compression

---

plugins/in_tail/tail_scan_glob.c

Only free memory when it is actually allocated by expand_tilde, otherwise we're freeing memory that shouldn't be freed (at least not here).
Verified that fix is working on a musl-based ARMv7 system.
Signed-off-by: Jan Willem Janssen <j.w.janssen@lxtreme.nl>

in_tail: free memory if allocated by expand_tilde

---

src/flb_upstream.c

flb_upstream_conn.ka_count is not initialized and can get
random values.
This can break out_forward when it get wrong information
that tells that connection is reused, but it's not and
out_forward thinks that handshake is already done.
flb_calloc could also be used to zero init whole flb_upstream_conn 
in allocation.

core/upstream: flb_upstream_conn.ka_count should be initialized

---

plugins/in_netif/in_netif.c

To fix #1680 
in_netif uses uninitialized variable `ctx->entry_len` to allocate memory.

in_netif: fix uninitialized variable to malloc (#1680)

---

cmake/macros.cmake

`FLB_OPTION` in `macros.cmake` sets variable with invalid order of arguments and it generates some warning errors like below.
```plain
CMake Warning (dev) at cmake/macros.cmake:9 (set):
implicitly converting '' to 'STRING' type.
Call Stack (most recent call first):
CMakeLists.txt:313 (FLB_OPTION)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
According to cmake document, we should put `type` first and then docstring but `FLB_OPTION` does opposite.
cmake2: https://cmake.org/cmake/help/v2.8.12/cmake.html
cmake3: https://cmake.org/cmake/help/latest/command/set.html

cmake: fix FLB_OPTION cmake macro

---

include/fluent-bit/flb_output.h

```
[ 98%] Built target hello_world
[ 98%] Building CXX object examples/hello_world_cpp/CMakeFiles/hello_world_cpp.dir/hello_world.cc.o
In file included from /Users/hli/src/fluent-bit/examples/hello_world_cpp/hello_world.cc:20:
In file included from /Users/hli/src/fluent-bit/include/fluent-bit.h:39:
/Users/hli/src/fluent-bit/include/fluent-bit/flb_output.h:308:14: error: assigning to 'struct flb_libco_out_params *' from incompatible type 'void * _Nullable'
params = FLB_TLS_GET(flb_libco_params);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/hli/src/fluent-bit/include/fluent-bit/flb_thread_storage.h:37:36: note: expanded from macro 'FLB_TLS_GET'
#define FLB_TLS_GET(key)           pthread_getspecific(key)
^~~~~~~~~~~~~~~~~~~~~~~~
In file included from …
```

output: Explicit cast to fix a build error on macOS

---

include/fluent-bit/flb_compat.h
src/flb_sds.c

The commit 2eef4071 introduced a change that breaks the AppVeyor build.
Test project C:/projects/fluent-bit-2e87g/build
Start  1: flb-it-pipe
1/11 Test  #1: flb-it-pipe ......................   Passed    0.02 sec
Start  2: flb-it-sds
2/11 Test  #2: flb-it-sds .......................***Failed    0.02 sec
Test sds_usage...                               [   OK   ]
Test sds_printf...                              [ FAILED ]
sds.c:35: Check tmp == s... failed
sds.c:36: Check flb_sds_len(s) == len... failed
Due to this, AppVayor has been failing to generate Windows installers.
This is why we are unable to download v1.3.4 installers.
This patch fixes it.

Fix AppVeyor build failure on v1.3.4

---

cmake/windows-setup.cmake
plugins/out_kafka/CMakeLists.txt

This reverts commit 69fffab96630869015437a6d1d13aa1efeb0a9c7.
Bakashar Kemerbay (and many other Windows users) reports that it
causes an immediate abort on Windows environments. In particular,
it causes abort even when they does not use out_kafka.
For example, I can confirm that even the following command does
not work on a vanilla Windows server.
$ fluent-bit.exe -i dummy -o stdout
This is because librdkafka is dependent on OpenSSL (ssleay32.dll
and libeay32.dll), which most Windows servers do not have. Hence
fluent-bit.exe always fails due to missing DLL dependencies.
So we have to revert this, and revisit it after resolving the
dependency issue.

Revert "out_kafka: make MSVC compatible (#1179)"

---

src/flb_lib.c

I noticed that unit tests for macOS were failing on Travis CI with
the following error message.
No output has been received in the last 10m0s, this potentially
indicates a stalled build or something wrong with the build itself.
It turned out that we introduced a new TLS variable in 30d271ea,
but never added a code path to initialized it. This was causing
runtime test programs to deadlock on flb_start().
This should fix it.

lib: do not forget to initialize TLS keys for output plugins

---

src/flb_output.c

There are multiple cases
1. Plugin doesn't support TLS.
2. Plugin supports TLS but TLS isn't configurable.
3. Plugin support TLS but is configurable.
flb_output.c:
In all cases, the use_tls gets set to appropriate value. But not the instance flags.
318     else if (flags & FLB_IO_OPT_TLS) {
319         /* TLS must be enabled manually in the config */
320         instance->use_tls = FLB_FALSE;
321         instance->flags |= FLB_IO_TLS;
322     }
In the above snippet we can see that flags is set to FLB_IO_TLS irrespective of the configuration. So this flag alone doesn't tell us if the configuration has tls enabled or not.
But the use_tls gets updated based on the configuration:
447     else if (prop_key_check("tls", k, len) == 0 && tmp) {
448         if (strcasecmp(tmp, "true") == 0 || …

Fix for issue #1840

---

src/flb_io.c

maine -> main, their selfs -> themselves, etc.

io: fix typos in comments

---

plugins/out_forward/forward.c
plugins/out_forward/forward.h

Fluentd allows to use an empty string "" as a shared key. This means
that the following configuration is perfectly valid in Fluentd.
<source>
@type forward
<security>
shared_key ""
self_hostname foo
</security>
</source>
The trouble is that Fluent Bit was being unable to connect to such
a Fluentd node, because Fluent Bit's configuration syntax did not
allow to specify an empty string.
This adds a new boolean option 'Empty_Shared_Key' that enables us to
circumvent the limitation, and should make Fluent Bit on par with
Fluentd.

out_forward: Add a new option 'Empty_Shared_Key'

---

CONTRIBUTING.md
DEVELOPER_GUIDE.md

I wrote originally wrote this guide because I need to train one of my coworkers to work on Fluent Bit. I think its generally useful for the project to have a guide like this- diving into the code when you are new is a daunting task.
I think that any engineer with knowledge of C could read the existing code base and figure out how to make changes. However, many would be put off by the initial steep learning curve. I've found with these sorts of things that if you give people a little help in the beginning, it speeds things up a lot. I think it's partly a psychological factor- having a clear starting point and example helps one figure out what they need to learn. Once the path is clear, motivation follows.

readme: add 'beginners guide'/library reference with code examples

---

src/flb_parser.c

When Fluent Bit encounters with a partial parser definition, it
crashes badly with a segmentation fault.
$ ./bin/fluent-bit -R parser.conf -c tail.conf
...
[2020/01/15 16:11:21] [error] [parser] no parser 'format' found for 'simple' in file 'conf/timestamp.parser'
[engine] caught signal (SIGSEGV)
#0  0x558bc4a0a226      in  flb_parser_decoder_list_destroy() at src/flb_parser_decoder.c:700
#1  0x558bc4a05d75      in  flb_parser_conf_file() at src/flb_parser.c:566
#2  0x558bc49f4bdd      in  flb_config_set_property() at src/flb_config.c:406
#3  0x558bc49e24ae      in  flb_service_conf() at src/fluent-bit.c:446
#4  0x558bc49e2f90      in  main() at src/fluent-bit.c:807
#5  0x7fa1cb7f109a      in  ???() at ???:0
#6  0x558bc49e13a9      in  ???() at ???:0
#7  0xffffffffffffffff  in  ???() at …

parser: initialize decoders with NULL to avoid SIGSEGV

---

src/flb_input.c

I noticed that Fluent Bit sometimes fails to start up with SIGSEGV,
seemingly at random.
The reason turned out that some fields in flb_input_instance were
not initialized to NULL properly, so conditionals such as
if (in->host.listen) {
listen = in->host.listen;
}
... were not really reliable, and could pass a random memory
location to variables. Fix it.

input: make flb_input_new() zero-initialize input instances

---

cmake/windows-setup.cmake

I can confirm that in_statsd is already working fine on Windows.
Let's just make it available to Windows users.
**Screenshot**

build: Enable in_statsd on Windows

---

src/flb_http_client.c
src/flb_signv4.c
tests/internal/signv4.c

Re-implements the functionality in [9cccabe](https://github.com/fluent/fluent-bit/commit/9cccabe319286d5cb3c3e072de65de60b5c11432).
In order for sigv4 to work properly, host must be added as a header in the mk_list of headers. The problem with 9cccabe is that it adds the host header in `flb_http_do`, which is called after `flb_signv4_do` when making a request to AWS. 
There are also two small additional fixes which are explained in my commit message.
This PR also adds a slightly hacky fix to the signv4 tests so that the only headers in the client are from the test files.
In a separate branch, I have tested making a real API request to AWS using this code- it worked.

signv4: fixes to sigv4 algorithm

---

src/flb_http_client.c

Fixes a bug I committed in fcf15a9
(content length header was added before body was set, so it was always 0).
Fixes #1896

http: add content-length header after body is set

---

plugins/in_tail/tail_db.c

in_tail: fix inode overflow in 32-bit OS for statement SQL_GET_FILE

in_tail: fix inode overflow in 32-bit OS for statement SQL_GET_FILE

---

ci/do-ut.ps1

This should fix the build failure on AppVeyor.
The test program for Signv4 depends on `dirent.h` for test suite
discovery. However, since Windows provides neither `dirent.h` nor
its equivalent functions, we cannot easily port the testing script
to Windows.
So this disables the signv4 testing for now. We need to revisit
this issue after we prepare a compatiblity layer for dirent.h.

tests: internal: signv4: skip Signv4 unit testing on Windows

---

plugins/in_tail/tail_scan_win32.c

This patch adds a full wildcard support to in_tail on Windows, which has
been in our "TODO" list for a while (since 55e27e0).
With this patch applied, I can confirm that nested wildcard pathspecs
(like below) just work fine.
```ini
[INPUT]
Nat lme tail
Tag  app.log
Path C:\myapp\*\*.log
```

in_tail: Implement a full wildcard support for Windows

---

ci/do-ut

We are seeing unit test failures on Travis CI.
> /usr/bin/ld.gold: fatal error: ../../library/libflb-plugin-out_plot.a: ELF section name out of range
> collect2: error: ld returned 1 exit status
It looks to me that these failures are occurring only on ARM systems
with sanitizers enabled. The possible cause is we're using a different
linker when sanitizers enabled.
This commit removes the relevant part in the unit test script.

ci: avoid using ld.gold to fix "ELF section name out of range" error

---

src/flb_utils.c
src/fluent-bit.c

Previously, if log level was set to error you'd get some weird print statements:
```
[2020/01/29 08:28:04] [ info] Configuration
[2020/01/29 08:28:04] [ info]  flush time     : 9190080 seconds
[2020/01/29 08:28:04] [ info]  input plugins  :
[2020/01/29 08:28:04] [ info] dummy
[2020/01/29 08:28:04] [ info] cpu
[2020/01/29 08:28:04] [ info]  collectors     :
```
It seems the goal of these statements was to print the current config. I've changed it to print more useful information, and also made it so it only prints these messages if log level is debug or trace:
```
[2020/01/29 08:24:32] [ info] Configuration:
[2020/01/29 08:24:32] [ info]  flush time     | 5.000000 seconds
[2020/01/29 08:24:32] [ info]  grace          | 5 seconds
[2020/01/29 08:24:32] [ info]  daemon         | 0
[2020/01/29 …
```

utils: fix flb_utils_print_setup

---

tests/internal/config_map.c

Since `FLB_CONFIG_MAP_SLIST_4` requires 4 strings at least, we
need to pass something like "a b c d", not "a b c".
This should fix the CI failure occurring on 013a2553.

tests: internal: config_map: fix test for mult_slist

---

conf/parsers.conf

The timestamp in RFC 5424 conforms to RFC 3339 and it should accept
timezone, such as "2019-10-18T11:50:47.788+03:00". Without it all
timestamps from syslog input are treated as UTC.
Signed-off-by: Ji-Ping Shen <ji-ping.shen@relexsolutions.com>

conf: parsers: fix syslog-rfc5424 timestamp format

---

include/fluent-bit/flb_config.h
src/flb_config.c
src/flb_env.c
src/fluent-bit.c

#1769 
Previously, log level could be set with the following precedence:
1. Via `Log_Level` in the [SERVICE] section of a config file
2. Command Line args `-q` and `-v` 
Now the options and precedence are:
1. Value of the Env Var `FLB_LOG_LEVEL`
2. Via `Log_Level` in the [SERVICE] section of a config file
3. Command Line args `-q` and `-v`

Set log level from env var FLB_LOG_LEVEL

---

src/flb_input_chunk.c

See #1903, I think this message should probably be a warning instead of debug.

input_chunk: change mem buf overlimit message to warning

---

include/fluent-bit/flb_http_client.h
plugins/out_es/es.c
plugins/out_es/es.h
plugins/out_es/es_conf.c
src/flb_http_client.c

out_es: Add experimental support for Amazon ElasticSearch for 1.4

---

src/CMakeLists.txt

The build is currently failing due to option `FLB_SIGNV4` being set to `Yes`, but the `flb_signv4.c` file is gated behind the `FLB_METRICS` option.

build: register signv4 if FLB_SIGNV4 and FLB_TLS enabled

---

plugins/out_es/es.c
plugins/out_es/es.h
plugins/out_es/es_conf.c

When `AWS_auth` is `On`, the user-agent will match that of the other AWS fluent bit plugins: https://github.com/aws/amazon-kinesis-firehose-for-fluent-bit/blob/master/plugins/user_agent.go#L32

out_es: update user-agent for Amazon ES to conform with AWS standards

---

conf/parsers.conf

Updated parser to support latest helm release 
Helm Version: `nginx-ingress-1.28.0`
App Version: `0.26.2 `

Updated k8s-nginx-ingress parser for NGINX Controller

---

src/flb_input.c

Pausing the same timer twice can result in a nasty memory error,
since mk_event_timeout_destroy() is not guaranteed to be idempotent
(notably it's unsafe on the "select" backend).
I can confirm that this issues was causing occasional segmentation
faults on Windows platform. Fix it.

input: avoid destroying the same collector timer twice

---

src/flb_engine.c

This actually fixes two bugs:
- The argument to "flb_utils_bytes_to_human_readable_size()" is
wrong. It's `*char[]`, where it should be `char[]`.
- The format string for coro_stack_size should be "%u" (not "%lu"),
since it is declared as unsigned integer.

engine: avoid segmentation faults while formatting stack size

---

plugins/in_tail/tail_file.c
plugins/in_tail/tail_scan_win32.c

This is a supplemental patch for a8976f2e90, applying interface
changes introduced by the commit to Windows code paths.
With this, in_tail can be compiled and linked again.

in_tail: fix compilation error due to recent updates

---

cmake/windows-setup.cmake
plugins/filter_rewrite_tag/rewrite_tag.c
plugins/in_emitter/emitter.c

This contains a series of small fixes that bring `filter_rewrite_tag`
(and `in_emitter`) to Windows platforms.
With this applied, I can confirm that I can rewrite tags with Fluent Bit
running on cmd.exe.
**Test Configuration**
```ini
[INPUT]
NAME   dummy
Dummy  {"tool": "fluent", "sub": {"s1": {"s2": "bit"}}}
Tag    test_tag
[FILTER]
Name          rewrite_tag
Match         test_tag
Rule          $tool ^(fluent)$  from.$TAG.new.$tool.$sub['s1']['s2'].out false
[OUTPUT]
Name  stdout
Match from.*
```
**Execution Result**
```
C:> fluent-bit.exe -c rewrite.conf
...
[0] from.test_tag.new.fluent.bit.out: [1581663803.613948700, {"tool"=>"fluent", "sub"=>{"s1"=>{"s2"=>"bit"}}}]
[1] from.test_tag.new.fluent.bit.out: [1581663804.613835400, {"tool"=>"fluent", "sub"=>{"s1"=>{"s2"=>"bit"}}}]
[2] …
```

filter_rewrite_tag: port the plugin to Windows

---

src/flb_output.c
src/flb_plugin_proxy.c
src/proxy/go/go.h

Fixes: #1421 
Currently in `flb_plugin_proxy.c`, only the `cb_flush` handler is set on the proxy plugin instance that is managed by fluent-bit, with the init and register callbacks begin invoked in `go.c`  itself.
For certain cases such as writing a GZip stream - the invocation of the exit handler is *essential* so that the plugin can close the current GZip stream - else the currently written file would not be a valid GZip file, and extraction of already written data would require additional work.
Signed-off-by: Sriduth Jayhari <sriduth.jayhari@juspay.in>

go plugin: Added minimal changes to set and call `FLBPluginExit`

---

src/flb_parser.c

Mehdi Hamidi reported that Fluent Bit always defaults to "31 December"
if the incoming records do not contain any date information. For example,
suppose that we have set up something like below:
[PARSER]
Name nginx
Format regex
Time_Format %H:%M:%S
... then Fluent Bit would parse '12:00:00' into '2020/12/31 12:00:00'
regardless of what the day is today.
This is a fix for the issue and make Fluent Bit to use "today" as a
reasonable default value.

parser: interpolate the date field with a reasonable value

---

src/flb_plugin_proxy.c

Current warning when building master:
```
/home/ec2-user/fluent-bit/src/flb_plugin_proxy.c: In function ‘flb_proxy_register_output’:
/home/ec2-user/fluent-bit/src/flb_plugin_proxy.c:111:18: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
out->cb_exit = flb_proxy_cb_exit;
```
This was caused by #1426

Fix build warning from go plugin proxy exit

---

plugins/in_tail/tail_file.c
plugins/in_tail/tail_file.h
plugins/in_tail/tail_fs_stat.c

Fixes #1806
When deciding whether a path should be added to the scan queue or not, a superficial comparison on path/name is the correct behavior for all OSes. Only operations that actually touch the files in question may need to do a deeper comparison that accounts for `real_name` on applicable OSes. 
cc @fujimotos

tail plugin on win: don't repeatedly add symlinks to scan queue

---

conf/parsers.conf

This pull request refers to issue #1973 
This addition adds the ability to parse the access logs generated by Envoy.
Envoy Version: `1.14.0-dev-3d1620`
Signed-off-by: Carmen Puccio <CarmenAPuccio@gmail.com>

parser: add Envoy access log parser

---

CMakeLists.txt
cmake/onigmo.cmake

When we perform a snap build, it results in the following error.
Failed to run 'cmake --build . -- -j2' for 'fluent-bit': Exited with code 2.
Verify that the part is using the correct parameters and try again.
It turns out that snapcraft's cmake plugin sets DESTDIR automatically,
and it confuses Makefile to install libonigmo.a into a wrong path.
So here is a trivial patch that add `DESTDIR=` to installation commands.

build: make Fluent Bit compilable as Snap application

---

.gitignore

Signed-off-by: Nick Fischer <nicfisch@amazon.com>
Add `.gitignore` entry for `lib/chunkio/include/chunkio/cio_version.h`. It seems this file is generated from `lib/chunkio/include/chunkio/cio_version.h.in` and it looks like we ignore other files generated in this same fashion.
----
**Testing**
---- …

gitignore: add chunkio/cio_version.h

---

src/flb_utils.c

Minor typo fix in error message.
----
**Testing**
----

utils: fix typo in error message

---

src/flb_task.c

Reassigning `seconds` would make it always go into the worst case.
----

task: use return value of flb_sched_request_create

---

src/flb_sds.c

After int2hex lookup, c is greater than or equal to '0' = 48, so in the
second lookup, it overruns the int2hex array.
----
**Testing**
----

sds: fix double lookup of int2hex

---

tests/internal/sds.c

This adds unit tests for `flb_sds_cat_utf8()` so that we can prevent future
similar bugs similar to #1995 from happening.
----
**Testing**
----

tests: internal: sds: add test for flb_sds_cat_utf8()

---

Dockerfile.windows
Dockerfile.windows.devel

This consolidates the common operations for building Windows images,
before we include Windows Dockerfiles into v1.4.0 release.
Here are several user-visible improvements:
- Add OCI labels to Docker images so that we can inspect them easily.
- Supply default values to command-line arguments so that we can
build an image just by:
$ docker -f Dockerfile.windows .
- Avoid appending unnecessary stuffs into the final image to minimize
the footprint.

dockerfile: Simplify Windows Dockerfiles

---

DEVELOPER_GUIDE.md

Added two new sections:
- Valgrind (under testing)
- High level explanation of concurrency in Fluent Bit
----

Dev Guide updates: concurrency and valgrind

---

src/flb_plugin_proxy.c
src/proxy/go/go.c
src/proxy/go/go.h

go plugin - Implement `FLBPluginExitCtx` - allowing multiinstance plugins to cleanup their respective contexts.
Related  #1421
Signed-off-by: Sriduth Jayhari <sriduth.j@compile.com>

Implement `FLBPluginExitCtx(ctx)`

---

src/flb_http_client.c

Hi, this pr should fix the problem that HTTP request sent by flb_http_client contains an illegal `Content-Type` header with `\0` character.
I found this when trying to send my logs to ES by fluent-bit. Error logs like this:
```
[2020/03/09 07:39:10] [error] [output:es:es.0] HTTP status=400 URI=/_bulk, response:
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"a header value contains a prohibited character '\u0000': 166062\u0000"}],"type":"illegal_argument_exception","reason":"a header value contains a prohibited character '\u0000': 166062\u0000"},"status":4
00}
[2020/03/09 07:39:14] [error] [output:es:es.0] HTTP status=400 URI=/_bulk, response:
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"a header value contains a prohibited character …
```

http_client: Content-Type header buffer should have enough space for integer

---

plugins/out_datadog/datadog.c
plugins/out_datadog/datadog.h
plugins/out_datadog/datadog_conf.c
plugins/out_http/http_conf.c
src/flb_http_client.c
src/flb_utils.c

Add a new plugin parameter, `proxy` that can be used to to specify an http proxy
to use to send datadog queries.
Signed-off-by: Lénaïc Huard <lenaic.huard@datadoghq.com>

out_datadog: add http proxy support

---

plugins/out_es/es.c

Previously, when trace_error was enabled, a single error log would
be produced with the raw elasticsearch output and the raw input
that caused the error. This was imperfect because the fluent bit
logging functions truncate output. Long inputs could prevent the
output from being printed.
With this change, the input and output is printed in separate
calls. The input is printed as debug, so that users can control
whether or not it is printed. The actual error output is still
printed at the error level.
----

out_es: fix/improve trace_error output

---

src/flb_gzip.c

`flb_gzip_compress()` calculate `strm.avail_out` while compressing the buffer. However, it wrongly uses `out_data` which is argument to this function and likely to be an address of local variable in stack (large value). This should be `out_buf` which is the start address and `pb` belongs to.
Here's the difference in `tests/internal/gzip.c`:
```plain
$ gdb ./flb-it-gzip
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-115.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting …
```

gzip: fix wrong usage of address when calculating available size

---

plugins/out_pgsql/CMakeLists.txt
plugins/out_pgsql/pgsql.h

The plugin was compiling without issues on Debian based distributions but not on RedHat based distributions, this PR fix that issue using CMake capabilities

out_pgsql: Added target_include_directories() to CMakeLists.txt to

---

src/fluent-bit.c

Windows has only a limited support for POSIX signals, and SIGCONT
is not one of them (not defined in signal.h).
Add ifdefs to code blocks that use SIGCONT to avoid compile errors.
----
**Testing**

bin: do not use SIGCONT on Windows

---

plugins/in_tail/tail_multiline.c

`tmp` is discarded in next `flb_input_get_property`.
----

in_tail: remove unused get_property

---

include/fluent-bit/flb_compat.h

A recently introduced code uses SHUT_RDWR to shutdown both send
and receive ends of a socket. This implementation does not work
as expected on Windows where SHUT_* constants do not exist.
Work around this issue by aliasing SD_BOTH to SHUT_RDWR.

compat: A quick fix for build failure on Windows due to SHUT_RDWR

---

plugins/in_winlog/in_winlog.c

Visual C++ assumes that a function returns "int" if there is no
preceeding prototype declaration. Due to this behaviour, the
pointer to the SQLite context was being silently truncated.
The fix is just to include fluent-bit/flb_sqldb.h.

in_winlog: add missing header "flb_sqldb.h"

---

DEVELOPER_GUIDE.md

The link to the  monkey project in concurrency section was showing page not found. Redirected it to correct link . 
----
**Testing**
----

DEVELOPER_GUIDE : fix 404 not found error due to typo

---

plugins/out_file/file.c

The recent change introduced a bug that assigns the default value
after the configuration file is loaded. This resulted in out_file
ignoring the user settings.
Fix it by letting flb_output_config_map_set() handle default values,
not manually assigning them.
Resolves #2069 
----
**Testing** …

out_file: fix wrong assignment to ctx->template

---

cmake/luajit.cmake
cmake/onigmo.cmake

Some Windows systems do not set PATH to cmake.exe. For this reason,
invoking cmake can sometimes fail with an error "unrecognized
command: cmake".
Work around that by using CMAKE_COMMAND that contains an absolute
path to cmake.exe.

build: use cmake variable magic instead of `cmake`

---

tests/internal/utils.c

This patch is to fix internal test `flb-it-utils ` error.
`flb_utils_url_split` sets "443" or "80" when port number is missing.
https://github.com/fluent/fluent-bit/blob/master/src/flb_utils.c#L816
So, I modified expected port number on such testcases and add "http" testcase.
https://travis-ci.org/github/fluent/fluent-bit/jobs/672310084#L2021
```
33/41 Test #34: flb-it-utils .....................***Failed    0.00 sec
Test url_split...                               [ FAILED ]
utils.c:85: Check port == NULL... failed
utils.c:85: Check port == NULL... failed
Test write_str...                               [   OK   ]
FAILED: 1 of 2 unit tests have failed.
```
----
**Testing**
Before we can approve your change; please …

utils: set default http/https port

---

plugins/filter_rewrite_tag/rewrite_tag.c
plugins/filter_rewrite_tag/rewrite_tag.h

This fixes an issue found during load testing the rewrite_tag filter
At very heavy loads (3K/sec records) the emitter buffer was seen to grow unbounded
until an OOM event.  During this test a complex lua filter was utilized and the
output was kinesis.  This is of note because more processing load seems to make
the issue occur at lower rates.
This patch has been load tested by in a kubernetes environment:
pod -> docker-json-driver -> fluenbit-daemonset -> kinesis
The config was something similar to this:
tail -> modify_filter -> kubernetes -> lua_filter -> rewrite_tag -> kinesis
Signed-off-by: Zack Wine <zwine@synamedia.com>
Add `emitter_mem_buf_limit` option to rewrite tag filter emitter to prevent unbounded memory growth.  A new setting on the rewrite_tag filter `emitter_mem_buf_limit` …

filter_rewrite_tag: Add mem_buf_limit to rewrite tag filter emitter.

---

plugins/filter_lua/lua.c
scripts/test.lua

filter_lua: support new return value to keep timestamp

---

plugins/in_tail/tail_file.c

Build of in_tail plugin is broken when FLB_HAVE_REGEX isn't set because of redundant parenthesis, which came from this commit: https://github.com/fluent/fluent-bit/commit/5e70c21dc6bb4d2548a8f66d2e05f8d7be234cd8#diff-77b5412db7cc81c07e52ff8f074fd00aR419
Without it build completes successfully
----
**Testing**
---- …

Fix typo in in_tail to fix build with FLB_HAVE_REGEX=Off

---

scripts/test.lua

via review comment https://github.com/fluent/fluent-bit/pull/2100#discussion_r411054204.
I fixed the number of return value.
The patch fixes only comment in lua script.
----
**Testing**
----

scripts: fix description about return value

---

plugins/out_stdout/stdout.c

Addresses https://github.com/fluent/fluent-bit/pull/2060#discussion_r401884323
----
**Testing**
```sh
==18355== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==18355== Command: bin/fluent-bit -c ../conf/in_dummy.conf
==18355== 
Fluent Bit v1.5.0
[2020/04/02 09:35:37] [ info] [storage] version=1.0.3, initializing...
[2020/04/02 09:35:37] [ info] [storage] in-memory
[2020/04/02 09:35:37] [ info] …
```

out_stdout: add description for properties in config map

---

DEVELOPER_GUIDE.md

developer_guide.md : added documentation for config maps

---

tests/internal/fuzzers/parse_json_fuzzer.c
tests/internal/fuzzers/parse_logfmt_fuzzer.c
tests/internal/fuzzers/parse_ltsv_fuzzer.c

Added three new fuzzers for parsers.
----
**Testing**
----

Added three fuzzers for parser.

---

plugins/in_tail/tail_file.c
plugins/in_tail/tail_file.h
plugins/in_tail/tail_file_internal.h

When compiled with FLB_HAVE_INOTIFY=no for linux, records were continuously
resent if the files in PATH are symlinks.  This patch ensures the fs_stat file
monitoring correctly handles symlinks when checking for file rotations.
The issue was found when running fluentbit as a daemonset in kubernetes where all
files in /var/log/containers/* are symlinks.
This patch was tested by forwarding 1M records of 1K size when compiled with
both FLB_HAVE_INOTIFY=no/yes and verifying the output metrics reported exactly
1M records.  The test was executed by running a container logging to stdout
in a kubernetes cluster where symlinks are the target input.  Further docker
was configured to rotate logs at 10M to ensure multiple file rotations
occurred.
Signed-off-by: Zack Wine <zwine@synamedia.com>
---- …

in_tail: fix symlink log rotation for fs_stat on linux

---

plugins/in_tail/tail_fs_stat.c

Windows will not actually delete a file as long as there is any
open handler for it. Until we close the last open handler, the
file is kept alive as "pending delete".
Obviously this has been breaking the log rotation mechanism for
some users. Work arount that by checking the "DeletePending" flag
manually in tail_fs_check().

in_tail: Work around "undeletable file" issue on Windows

---

plugins/in_mqtt/mqtt.c

Fixes #1672 
Registers config_map for in_mqtt.
----
**Testing**
----

in_mqtt: register config_map

---

plugins/filter_lua/lua.c
plugins/filter_lua/lua_config.c
plugins/filter_lua/lua_config.h

Fixes #2148. 
I added `protected_mode` property to prevent crash when fluent-bit executes invalid lua script.
refs https://www.lua.org/pil/24.3.1.html
If the property is enabled, fluent-bit reports error and continues filtering. 
protected mode is less performance,
so I added property to be able to select unprotected mode and not to change default behavior.
(Default is False)
a.conf:
```
[INPUT]
Name dummy
dummy {"test":"data"}
[FILTER]
Name lua
Match *
script break.lua
call breaking
protected_mode true
[OUTPUT]
Name stdout
Match *
```
break.lua:
```lua
function breaking(tag, timestamp, record)
print(errordata["panic"])
return 0, timestamp, record
end
```
valgrind output:
```
buntu:~/git/fluent-bit/build/2148$ valgrind ../bin/fluent-bit -c a.conf 
==27166== Memcheck, a memory error …
```

filter_lua: support protected mode (#2148)

---

include/fluent-bit/flb_parser_decoder.h
include/fluent-bit/flb_unescape.h
src/flb_parser_decoder.c
src/flb_unescape.c
tests/internal/data/parser/regex.conf
tests/internal/parser.c

New decoder "mysql_quoted" to decode mysql/mariadb quoted 'xxx' strings.
```
[PARSER]
Format regex
...
Decode_Field_As   mysql_quoted    field
```

parser: mysql quoted decoder

---

plugins/in_tail/tail_file_internal.h
plugins/in_tail/tail_multiline.c

The fix for #1368, applied in 826c84f forbids the firstline to end with an integer. This is required if the continuation line does not match any parser.
In cases where the line is not appended to the parent, we are save to process the line, even if the first line does not end with an string.
Signed-off-by: Thomas Berger <loki@lokis-chaos.de>

in_tail: allow firstline to end with an int

---

src/flb_pack.c

Floating point numbers when unpacked are stored as double type,
though when packing to json is stored with %f which stores only
6 digits after point. Double has precision of 15 digits, hence
changed to %.16g which is most compact representation of number
without losing precision.
The patch has been tested in kubernetes locally, it proven to
push numbers like 15,000.08883478 to elastic, whilst previously
it pushed 15,000.088835 instead.
Signed-off-by: Maxim Vorobjov <maxim.vorobjov@gmail.com>

pack: fixed double's json packing precision

---

scripts/override_time.lua

I added a lua script to override timestamp.
We can override with `Time_key` option.
However it doesn't work when the value is integer/float.
https://github.com/fluent/fluent-bit/issues/662
This script is to solve the issue.
This is an example to override with a value of `KEY_OF_TIMESTAMP` which is an integer.
a.conf
```python
[INPUT]
Name dummy
Tag  dummy.data
Dummy {"KEY_OF_TIMESTAMP":1530239065, "data":"sample"}
[FILTER]
Name lua
Match *.*
script override_time.lua
call   override_time
[OUTPUT]
Name stdout
Match *
```
result is
```
Fluent Bit v1.4.0
[2019/10/13 07:19:28] [ info] [storage] initializing...
[2019/10/13 07:19:28] [ info] [storage] in-memory
[2019/10/13 07:19:28] [ info] [storage] normal synchronization mode, checksum …
```

scripts: add scripts to override timestamp with float/integer timestamp

---

src/flb_hash.c
tests/internal/hashtable.c

This patch will implement the FLB_HASH_EVICT_OLDER and FLB_HASH_EVICT_LESS_USED
eviction modes where they were previously marked as Todos. FLB_HASH_EVICT_OLDER
mode will evict the oldest entry found in the hash table if the size exceed the
max_entries and FLB_HASH_EVICT_LESS_USED mode will evict the entry that has the
least number of hits if the size exceeds the max_entries.
Also adds two more unit tests to test the new eviction modes
flb_hash unit tests results:
./bin/flb-it-hashtable
Test zero_size...                               [   OK   ]
Test single...                                  [   OK   ]
Test small_table...                             [   OK   ]
Test medium_table...                            [   OK   ]
Test chaining_count...                          [   OK   ]
Test …

hash: Implement EVICT_OLDER and  EVICT_LESS_USED modes in flb_hash

---

plugins/out_es/es.h

In order to be compatible with the new versions of ElasticSearch which effectively are getting rid of
_type, we should change the default type to be "_doc"
As per the ElasticSearch forum discussion at:
https://discuss.elastic.co/t/7-0-1-template-with-geo-point-geoip-processor-in-pipeline-bulk-crash/182039/3
this seems to be due to not specifying a _type when creating the mapping, at which point it defaults
to "_doc".
Later when performing a bulk operation (indexing) we specifying that _type is "flb_type" which then
causes the error to be thrown about multiple types not being allowed:
"Rejecting mapping update to [logs-2019.11.16] as the final mapping would have more than 1 type: [_doc, flb_type]"
Another possible solution to this issue might be to use the "flb_type" when creating the …

Change the default _type to be _doc

---

plugins/out_flowcounter/out_flowcounter.c

Sorry, #1649 is a broken patch. It causes compilation error.
----
**Testing**
----

out_flowcounter: add missing semi-colon

---

plugins/out_kafka/kafka.c
plugins/out_kafka/kafka_config.c
plugins/out_kafka/kafka_config.h

this PR enhances plugin out_kafka with 'dynamic_topic' option. See
fluent/fluent-bit-docs#259
If dynamic_topic is set, unknown 'new' topics found in Topic_Key are
added on the fly to Topics.
This feature is helpful in kubernetes/openshift environment, forwarding the
logs of all pods to distinct kafka topics, when e.g. the topics are
extracted from a pod's annotation field. The static listing of all topics in the
configuration is not practicable for dynamic scaling up kubernetes
environments
configuration example:
```
Topics               logging_ichp_dev
Topic_Key            topickey
Dynamic_Topic        on
``
the commit was tested in an openshift-environment and logoutput is:
```
[2020/01/21 12:49:57] [ info] [out_kafka] brokers='kafka-t-0.europe.intranet: 9093' topics='logging_ichp_dev' …

out_kafka: add dynamic_topic option

---

plugins/in_tail/tail_scan_glob.c

Comparing tmp and pattern pointers before freeing memory potentially allocated by extend_tilde function is not correct: in case extend_tilde allocates memory and returns a pointer different than pattern, we make pattern equal to tmp, therefore the check for whether these pointers are not equal is never  satisfied. To avoid memory leak on platforms without GLOBE_TILDE I added additional "boolean" variable tmp_needs_free.
Fixes #2096 
----
**Testing**
- [N/A] Debug log output from testing the change (this piece of code doesn't have debug logging) …

Fixing memleak in do_glob.

---

src/http_server/api/v1/metrics.c
src/http_server/api/v1/metrics.h

adds missing "HELP... " strings to prometheus metrics for compatibilty
with prometheus pushgateway.
output of /api/v1/metrics/prometheus:
```
fluentbit_input_bytes_total{name="cpu.0"} 7608 1580245280923
fluentbit_input_records_total{name="cpu.0"} 24 1580245280923
fluentbit_output_errors_total{name="stdout.0"} 0 1580245280923
fluentbit_output_proc_bytes_total{name="stdout.0"} 6023 1580245280923
fluentbit_output_proc_records_total{name="stdout.0"} 19 1580245280923
fluentbit_output_retries_failed_total{name="stdout.0"} 0 1580245280923
fluentbit_output_retries_total{name="stdout.0"} 0 1580245280923
process_start_time_seconds 1580245256
```
Signed-off-by: Michael Voelker <novecento@gmx.de>

http_server: metrics: prometheus: add help string #1849

---

include/fluent-bit/flb_time.h
plugins/in_dummy/in_dummy.c
plugins/in_dummy/in_dummy.h
src/flb_time.c

timestamp issue (especially filter plugin issue like #2015) is hard to reproduce.
(e.g. write dummy logfile and use in_tail to parse it or use in_forward and send dummy message pack event ...)
I added new property `dummy_sec` and `dummy_nsec` for debugging.
It makes timestamp of event configurable.
If `dummy_sec` and `dummy_nsec` are not set, in_dummy works as usual.
in_dummy uses current time as timestamp.
----
**Testing**
a.conf:
```python
[INPUT]
Name dummy
dummy_sec  1582135200
dummy_nsec 1000000
[OUTPUT]
Name stdout
Match *.*
```
output is like this.
Timestamp is overwritten.
```
taka@ubuntu:~/git/fluent-bit/build/dummy_timestamp$ …
```

in_dummy: support new property dummy_sec/dummy_nsec

---

CMakeLists.txt

Farcop reported that Fluent Bit fails to run on a freshly installed
Windows. In particular, it hangs with the following message:
> The program can't start because VCRuntime140.dll is missing from
> your computer. Try reinstalling the program to fix this problem.
This patch fixes it by tweaking the compiler flags.

build: fix "vcruntime140.dll is missing" error on Windows

---

src/flb_dump.c

Addresses issue raised in #2175 where it is not possible to view the Internal dump if stdout is redirected to `tee` or a file.
----
**Testing**
----

Added missing fflush(stdout) to flb_dump 

---

plugins/in_tail/tail_file.c

Unix and Windows use different characters as delimiters. Unix
uses `/`, and Windows uses `\`. Windows also uses `:` for drive
names.
This patch teaches Fluent Bit about both flavors of delimiters,
so that it can produce a pretty tag like:
prefix.c.users.public.test.log
... not something like:
prefix.c:\users\public\test\log

in_tail: add more path delimiters to the sanitization list

---

plugins/filter_kubernetes/kube_conf.h
plugins/filter_kubernetes/kube_meta.c
plugins/filter_kubernetes/kubernetes.c

Windows pods are known to have unstable network immediately after
boot. This has been causing deployment failures for many users.
Work around that by adding small code to poll the network status.

filter_kubernetes: Poll DNS status on Windows pods

---

src/flb_upstream.c

Under heavy load, Fluent Bit sometimes crashes with the following
message.
[upstream] KA connection #-1 to 127.0.0.1:24224 has been assigned (recycled)
This is obviously broken. This log suggests that file descriptor is
already closed (-1), so the keepalive mode should never recycle it.
This patch fixes the bug by adding check for closed connections.

upstream: fix segmentation fault on net.keepalive=yes

---

plugins/in_tail/tail_fs_stat.c

Added an if clause around a db usage in an input plugin.
----
**Testing**
- [ N/A ] Example configuration file for the change
----

Added if around db usage

---

conf/parsers.conf

Fix the regex for *extradata* because it consumes everything between `[` from extradata and the last `]` in *message*, if the latter is present.
This is not meant to be a perfect solution because structural data may contain complex text with escaping chars, such as `[name="\\\] "]`, which is difficult if not impossible to be parsed properly by regex. However, it'd still be better to have wrongly parsed part ended up in *message* rather than *extradata*, which is more often ignored.
Signed-off-by: Ji-Ping Shen <ji-ping.shen@relexsolutions.com>
----

conf: parsers: fix syslog-rfc5424 extradata

---

src/flb_record_accessor.c
tests/internal/record_accessor.c

This fixes record accessor `ra_parse_buffer` to allow dots inside subkeys.
Fixes https://github.com/fluent/fluent-bit/issues/2151
Test results:
```
./build/bin/flb-it-record_accessor
Test keys...                                    
=== test ===
type       : KEYMAP
key name   : aaa
- subkey  : a
type       : STRING
string     : ' extra '
type       : KEYMAP
key name   : bbb
- subkey  : b
type       : STRING
string     : ' final access'
=== test ===
type       : KEYMAP
key name   : b
- subkey  : x
- subkey  : y
=== test ===
type       : KEYMAP
key name   : z
=== test ===
type       : STRING
string     : 'abc'
[2020/05/22 02:43:54] [error] [record accessor] syntax error, unexpected $end, expecting ']' at '$abc['a''
[   OK   ]
Test translate...                               == input ==
START …
```

record_accessor: fix parser to ignore dots in subkeys

---

src/flb_scheduler.c

The request object and its event object hold a reference to the
same file descriptor. As such, if we call close(2) on one reference,
it implicitly invalidates another reference.
This design is potentially dangerous. Since Windows can reuse the
descriptor number immediately after the first close call.
For example, consider the following case:
close(req->fd)           // close fd:601
fd = open("other_file")  // return fd:601 (reused)
close(event->fd)         // ???
The second close(2) can close an unrelated file, which may well be
an important fd for the core engine.
I believe this is the root cause of "Windows enters busy loop under
heavy load" issue reported by Thomas Heggelund.

scheduler: fix infinite loop bug on Windows

---

src/flb_parser.c

Thomas Heggelund reported a segmentation fault issue on the "Types"
option. His configuration was:
[PARSER]
Name    dips-log4net-multiline
Format  regex
Regex   ^(?<test>.*)$
Types test:integer
It turned out that c197f1c1 introduced a new method get_parser_key()
but forgot to apply that change to some option.
Due to this inconsistency, it ended up calling flb_sds_destroy() on a
plain char*. Resolve that issue by fixing the inconsistent key
retrieval.

parser: fix segmentation fault on "Types" option

---

src/flb_upstream.c

Make sure to clear dirty state from the previous connection
before reusing an event object.
It was confusing mk_core to double-delete an already deleted event,
resulting in random crash on Windows.

upstream: fix a segfault bug in flb_upstream_conn_release()

---

plugins/filter_kubernetes/kube_conf.h

A typical setup on Windows pods includes something like this:
```
[INPUT]
Name Tail
Path c:\var\log\containers\*
Tag  kube.*
```
In this case, in_tail emits events with a tag prefixed with
"kube.c.var.log.containers". Let's make it the default value
on Windows build.

filter_kubernetes: Tweak FLB_KUBE_TAG_PREFIX for Windows

---

src/stream_processor/flb_sp_groupby.c

Fixes the bug in GROUP BY string comparison.
fixes https://github.com/fluent/fluent-bit/issues/1794
output for the sample provided in the issue:
```
[0] bind_sp_1: [1591243567.965556140, {"query_domain_name"=>"google.com", "query_type"=>"A", "hits"=>2}]
[1] bind_sp_1: [1591243567.965565394, {"query_domain_name"=>"facebook.com", "query_type"=>"A", "hits"=>2}]
[2] bind_sp_1: [1591243567.965567060, {"query_domain_name"=>"google.com", "query_type"=>"AAAA", "hits"=>2}]
[3] bind_sp_1: [1591243567.965568394, {"query_domain_name"=>"facebook.com", "query_type"=>"CNAME", "hits"=>2}]
```
Valgrind output:
```
==23092== Memcheck, a memory error detector
==23092== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==23092== Using …
```

sp: fix group-by matching rule for string values

---

CMakeLists.txt
ci/do-ut.ps1
include/fluent-bit/flb_aws_credentials.h
include/fluent-bit/flb_aws_util.h
include/fluent-bit/flb_signv4.h
plugins/out_es/es.c
plugins/out_es/es.h
plugins/out_es/es_conf.c
src/CMakeLists.txt
src/aws/flb_aws_credentials.c
src/aws/flb_aws_credentials_ec2.c
src/aws/flb_aws_credentials_http.c
src/aws/flb_aws_credentials_profile.c
src/aws/flb_aws_credentials_sts.c
src/aws/flb_aws_util.c
src/flb_signv4.c
tests/internal/CMakeLists.txt
tests/internal/aws_credentials.c
tests/internal/aws_credentials_ec2.c
tests/internal/aws_credentials_http.c
tests/internal/aws_credentials_profile.c
tests/internal/aws_credentials_sts.c
tests/internal/aws_util.c
tests/internal/data/aws_credentials/shared_credentials_file.ini
tests/internal/data/aws_credentials/shared_credentials_file_nodefault.ini
tests/internal/data/aws_credentials/web_identity_token_file.txt
tests/internal/signv4.c

This is the *fifth and final* in a series of pull requests to add comprehensive support for AWS credentials in Fluent Bit. 
This PR should be reviewed after #1852 
This pull request adds support for 1 provider:
- Standard Chain: the standard order of resolution for credential providers
AWS Credential Provider Check List:
----

AWS Credentials Providers PR 5: Standard Chain

---

README.md

Noticed this existing output plugin was not listed in `README.md`, so I added it.
----
**Testing**
----

Add missing gelf plugin to README

---

include/fluent-bit/flb_compat.h
src/aws/flb_aws_credentials_profile.c

@PettitWesley The changes required are actually small.
- Add a compat implementation for ctime_r(3)
- Don't include <unistd.h>
I tested on Visual Studio 2019 that aws/flb_*.c compiles fine with
this patch.

aws: Make "aws" module compilable on Windows

---

plugins/out_forward/forward.c
plugins/out_forward/forward.h

Add a tag overwrite configuration to the forward output.
This allows unconditionally overwriting a specific tag.
It is useful in a scenario such as:
[OUTPUT]
Name            forward
Match           kube.*
Host            logs.DOMAIN
Port            24224
Self_hostname   ${HOSTNAME}
Tag      cluster.kube.__CLUSTER__
tls             on
tls.verify      on
tls.debug 2
tls.crt_file    /etc/certs/ca.crt
tls.key_file    /etc/certs/ca.key
where fluent-bit is used to forward logs to a central aggregator,
but we wish to overwrite a specific tag to indicate the source cluster.
----
**Testing** …

out_forward: add tag overwrite mode

---

src/flb_log.c
src/flb_pipe.c

The current logic assumes that read(2) never does a partial read
on a certain condition. This is really not guaranteed by POSIX,
and indeed not the case on Windows.
Use flb_pipe_write_all() and flb_pipe_write_all() to avoid partial
I/O in a portable manner.
Note: This patch is a joint efffort with @gitfool. It is verified to fix
random memory crash issue #2251 on WIndows.

fix a segmentation fault issue in logging worker 

---

src/CMakeLists.txt
src/fluent-bit.c
src/win32/winsvc.c

Windows services are equivalent to "daemon" in UNIX (i.e. long-running
background processes). This support is long-awaited by users who want
to run Fluent Bit on their servers.
In particular, this patch allows users to do:
% sc.exe create fluent-bit \
binpath= "\flb\fluent-bit.exe -c \flb\fluent-bit.conf"
and now "fluent-bit" can be started and managed as a normal Windows
service.
% sc.exe start fluent-bit
% sc.exe query fluent-bit
SERVICE_NAME: fluent-bit
TYPE               : 10  WIN32_OWN_PROCESS
STATE              : 4 Running
Fixes #1693. 

win32: add 'Windows Service' support

---

CMakeLists.txt
appveyor.yml
ci/do-ut.ps1
src/CMakeLists.txt

Sean Fausett pointed out that the current Windows release does
not include a debug symbol file. This makes it hard for our
users to analyze a crash dump.
This commit enables the PDB generation, and teaches CMake to
include the symbol file into the release distribution.

Enable PDB generation on Windows build

---

src/aws/flb_aws_credentials_sts.c

aws: sts: remove dead code (CID 304549)

---

plugins/filter_parser/filter_parser.c
tests/runtime/filter_parser.c

To fix #2250 
filter_parser supports multiple parsers.
However the behavior is different depending on `Reserve_Data` property when some parsers matched.
If `Reserve_Data` is enabled, filter_parser tries to parse "all" parser configuration even if one of them is matched.
Configuration and the expected behavior is here.
https://github.com/fluent/fluent-bit/issues/2250#issuecomment-643550026
----
**Testing**
- [*] Example configuration file for the change
- [*] Debug log output from testing the change
- [*] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found
Debug log …

filter_parser: cancel parsing if one parser is matched when Reserve_Data is enabled

---

src/aws/flb_aws_credentials.c

aws: fix flb_aws_credentials_destroy (CID 304556)

---

plugins/out_pgsql/CMakeLists.txt
plugins/out_pgsql/pgsql.c
plugins/out_pgsql/pgsql.h
plugins/out_pgsql/pgsql_connections.c
plugins/out_pgsql/pgsql_connections.h

Since just one connection in async mode turns into a possible data lose
we added pool of connections.
The tests worked with 10M of line and 5 connections without loosing any
data.
If the idea it's too keep just one connection, that's also possible using
option Async=FALSE which will turn everything into one synchronous connection.
The option Async will be FALSE by default to keep compatibility.
Signed-off-by: Jonathan Gonzalez V <jonathan.gonzalez@2ndquadrant.com>
Signed-off-by: Davidlohr Bueso <dave@stgolabs.net>
Signed-off-by: Alvaro Herrera <alvherre@alvh.no-ip.org>
----
**Testing**
----
Fluent Bit is licensed under Apache …

out_pgsql: Fix pressure issue (#2112)

---

plugins/out_stackdriver/CMakeLists.txt
plugins/out_stackdriver/stackdriver.c
plugins/out_stackdriver/stackdriver.h
plugins/out_stackdriver/stackdriver_operation.c
plugins/out_stackdriver/stackdriver_operation.h
tests/runtime/CMakeLists.txt
tests/runtime/data/stackdriver/stackdriver_test_operation.h
tests/runtime/out_stackdriver.c

According to https://cloud.google.com/logging/docs/agent/configuration#special-fields, there are some special fields in structured payloads, such as operation and sourceLocation.
This patch enables the stackdriver to extract 'operation' field from the jsonPayload and add it to the entries sent to the Google Logging Agent APIs.
Besides, the unit tests for `operation` are added.
----
**Testing**
- [check] Example configuration file for the change
- [check] Debug log output from testing the change
- [check] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found …

out_stackdriver: add 'operation' field to the entries

---

include/fluent-bit/stream_processor/flb_sp.h
src/stream_processor/flb_sp.c

Fixed memory leak related to string storage of group by keys 
Valgrind output:
```
==22625== Memcheck, a memory error detector
==22625== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==22625== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==22625== Command: build/bin/flb-it-stream_processor
==22625== 
Test invalid_queries...                         [2020/06/25 23:53:14] [ info] [sp] stream processor started
[2020/06/25 23:53:14] [error] [sp] aggregated query cannot mix not aggregated keys: SELECT id, MIN(id) FROM STREAM:FLB;
[2020/06/25 23:53:14] [error] [sp] aggregated query cannot mix not aggregated keys: SELECT *, COUNT(id) FROM STREAM:FLB;
[2020/06/25 23:53:14] [error] [sp] syntax error, …
```

sp: fix memory leak related to groupby string values

---

src/stream_processor/flb_sp.c

remove redundant memory free for groupby items
----
**Testing**
----

sp: remove redundant memory free for groupby items

---

plugins/out_stackdriver/stackdriver.c
plugins/out_stackdriver/stackdriver.h
plugins/out_stackdriver/stackdriver_conf.c
tests/runtime/CMakeLists.txt
tests/runtime/data/stackdriver/stackdriver_test_k8s_resource.h
tests/runtime/out_stackdriver.c

For now stackdriver output plugin only supports 'global' and 'gce_instance' resource types. More resource types need to be supported like 'k8s_container", "k8s_node" and "k8s_pod"
This patch will enable fluent-bit stackdriver to support `k8s_container`, `k8s_node` and `k8s_pod` resource types.
Issue number #1003 
----
**Testing**
----

out_stackdriver: add 'k8s_container' , 'k8s_node' and 'k8s_pod' to supported resource types

---

src/flb_input_chunk.c

input_chunk: change mem buf resume message to info

---

src/flb_upstream.c

When keepalive mode is enabled, flb_upstream_release() attempts to
overwrite event.data with a custom data. This assignment is unsafe,
since that field is used to hold internal metadata within mk_core.
Nor this assignment is required. In fact, anyone including
`cb_upstream_conn_ka_dropped()` does not rely on that bit of data.
This patch removes it, and fixes the memory crash issue on Windows.

upstream: remove an unnecessary `event.data` assignment

---

src/aws/flb_aws_credentials.c

aws: fix time of check, time of use in flb_read_file (CID 304550)

---

src/flb_http_client.c

Host header for HTTPS should not contain 443 port as certificates might not be valid when the port is used in the hostname.
----
**Testing**
- I can't run Valgrind on Ubuntu 20.04. I installed libc6-dbg and libc6-dbg:i386, but did not work. I tried installing from sources - did not work either.
----

http_client: fixing SSL error when specifying 443 port in the host header

---

conf/parsers.conf

Signed-off-by: Spike Wu <xwu@splunk.com>
The Time_Format should not appear twice in syslog-rfc3164 parser config(cause issue in my local run), and based on the RFC 3164 standard [here](https://tools.ietf.org/html/rfc3164#section-4.1.2), the first one should be correct (The second one should be the timestamp format of RFC-5424)
```
The TIMESTAMP field is the local time and is in the format of "Mmm dd
hh:mm:ss" (without the quote marks) where:
Mmm is the English language abbreviation for the month of the
year with the first character in uppercase and the other two
characters in lowercase.  The following are the only acceptable
values:
Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
dd is the day of the month.  If the day of the month is less
than 10, then it MUST be represented …
```

in_syslog: remove typo of Time_Format in syslog-rfc3164 parser config

---

plugins/out_stackdriver/stackdriver.c
plugins/out_stackdriver/stackdriver.h

One feature of stackdriver output plugin in fluentd is that we will provide more information on log name based on the value of stream field. This feature is missing in fluent bit and this patch will add this feature back.
----
**Testing**
----

out_stackdriver: Modify logName based on stream value

---

include/fluent-bit/flb_aws_credentials.h
src/aws/flb_aws_credentials_sts.c
tests/internal/aws_credentials_sts.c

- Fix compiler warnings on strncat() usage, replace it with flb_sds
- Valgrind test raised warnings about unitialized variables when handling certain test exceptions
__Valgrind Output__
```
$ valgrind --leak-check=full bin/flb-it-aws_credentials_sts 
==297656== Memcheck, a memory error detector
==297656== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==297656== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==297656== Command: bin/flb-it-aws_credentials_sts
==297656== 
Test test_flb_sts_session_name...               [   OK   ]
==297657== 
==297657== HEAP SUMMARY:
==297657==     in use at exit: 90 bytes in 2 blocks
==297657==   total heap usage: 15 allocs, 13 frees, 6,051 bytes allocated
==297657== 
==297657== LEAK SUMMARY:
==297657==    definitely …
```

aws: sts: fix compiler warnings and missing initialization in structures

---

CMakeLists.txt
cmake/luajit.cmake

Fix build error on macOS 10.15
Fixes #2220
----
**Testing**
----

Fix build on macOS 10.15

---

src/flb_engine.c

The following configuration causes memory crash:
[Output]
Name File
Patt /var/log/test.log
The reason is that Fluent Bit ignores the error return from
`flb_output_init_all()`, and boldly proceeds into the main loop
without output plugins being initialized.
Fix the return code check so that it can exit on error properly.

engine: fix segfault on invalid output configuration

---

cmake/windows-setup.cmake
plugins/out_cloudwatch_logs/cloudwatch_api.c
plugins/out_cloudwatch_logs/cloudwatch_logs.c
plugins/out_cloudwatch_logs/cloudwatch_logs.h

libevent exports a struct with the same name (`struct event` in
event2/event_struct.h). For this reason, this plugin fails to
compile if libevent backend is enabled.
Also unistd.h is not POSIX standard and not all platforms (in
particular Windows) do not provide it. Include flb_compat.h to
abstract away the header inclusion.
With this patch, I can confirm out_cloudwatch_logs can be compiled
and run on Windows.

out_cloudwatch_logs: Rename 'event' to 'cw_event'

---

cmake/windows-setup.cmake

out_azure is already ported to Windows and usable (I confirmed
it on Windows Server 2019, connecting to Azure log Analytics).
This patch includes the plugin into the release builds.

build: enable out_azure on Windows

---

src/flb_http_client.c

flb_http_client supports internal buffer size limit. If server
tries to send more data than the maximum size limit, the client
will refuse to receive it.
This behaviour is problematic when combined with keep-alive mode;
Since flb_http_do() can leave some data in the socket, the next
HTTP request can be confused by the leftover.
For example, if the socket has the following data (unread):
"data":["from", "previous", "conn"]}
The next HTTP request will see the following response:
"data":["from", "previous", "conn"]}HTTP/1.1 200 OK
Content-Type: text/html
Accept-Ranges: bytes
Last-Modified: Sat, 30 May 2020 23:47:16 GMT
...
This bug is originally reported by @gitfool on https://github.com/fluent/fluent-bit/issues/960#issuecomment-651457397.

http_client: mark connection as non-reuseable on failure

---

plugins/in_winlog/CMakeLists.txt
plugins/in_winlog/in_winlog.c
plugins/in_winlog/pack.c
plugins/in_winlog/winlog.c
plugins/in_winlog/winlog.h

This adds the first cut at a more complete record serializer
for Windows Event logs.
In particular, this patch implements the message formatting
using registry keys. The format of a new data record looks
something like this:
```json
{"RecordNumber": 408,
"TimeGenerated": "2020-06-22 06:26:31 +0900",
"TimeWritten": "2020-06-22 06:26:31 +0900",
"EventType": "Information",
"EventCategory": 0,
"Channel": "Application",
"SourceName": "Microsoft-Windows-RestartManager",
"ComputerName": "winsvr2019",
"Data": "",
"Sid": "",
"Message": "Starting session 0 - 2020-06-22T06: 26:31.710405700Z."}
```
Note that every field is explicitly encoded into UTF-8 - this
guarantees that we can always safely convert records into JSON.

in_winlog: fix "invalid UTF-8 bytes, skipping"

---

plugins/out_cloudwatch_logs/cloudwatch_api.c

out_cloudwatch_logs: fix unsigned conversion issue (CID 304901)

---

plugins/out_cloudwatch_logs/cloudwatch_api.c

out_cloudwatch_logs: fix mem leak (CID 304900)

---

src/aws/flb_aws_credentials_sts.c

aws_credentials_sts: fix typo in vtable (bug fix)

---

src/aws/flb_aws_credentials.c

aws_credentials: fix typo in flb_standard_chain_provider_create

---

plugins/out_cloudwatch_logs/cloudwatch_api.c
plugins/out_cloudwatch_logs/cloudwatch_logs.c

out_cloudwatch_logs: alloc event buffer to max size in init

---

src/flb_http_client.c

http: fix storage leak and assignment issue (CID 304893)

---

src/aws/flb_aws_credentials.c

aws: always close file before returning (CID 304895)

---

plugins/out_cloudwatch_logs/cloudwatch_logs.c

out_cloudwatch_logs: fix mem leak in init (CID 304902)

---

plugins/out_es/es.c

By creating `es_pack_array_content` function and using it to deal with map values that are arrays, replace dots now runs on the elements of arrays.
`es_pack_array_content` function created and used on map values if they are arrays. It is mutually recursive with `es_pack_map_content`, i.e. if an element of the array is a map, run `es_pack_map_content` on it, if an value of a map is an array, run `es_pack_array_content` on it.
Fixes #2093 
----
**Testing**
- [n/a] Example configuration file for the change
`Dummy {".le.vel":"error", ".fo.o":[{".o.k": [{".b.ar": "baz"}]}]}`
yields:
```
{
"_index" : "fluent-bit",
"_type" : "flb_type",
"_id" : …
```

out_es: fix replace_dots in array values

---

plugins/in_tail/tail_db.c

We have a few bug reports regarding to this function. Evidently
the SQL query generation can be broken on certain cases, but
we don't uncover the exact condition yet.
This patch adds additional logging to failure paths, to help
future debugging.
----
**Testing**
----

in_tail: add error handling to flb_tail_db_file_set()

---

plugins/out_cloudwatch_logs/cloudwatch_logs.c

One of my fixes to one of the Coverity issues found last week caused a new issue because I am not yet a good C programmer..
----
**Testing**
----

out_cloudwatch_logs: fix double free on session_name (CID 304942)

---

plugins/out_stackdriver/stackdriver.c
plugins/out_stackdriver/stackdriver.h
plugins/out_stackdriver/stackdriver_conf.c
tests/runtime/data/stackdriver/stackdriver_test_labels.h
tests/runtime/out_stackdriver.c

In the FluentD output plugin, it supports the extractions to convert the custom labels to the logEntry (see here). Currently there is no parsing function in out_stackdriver plugin to convert the cunstom labels to the logEntry (root-level) labels. Therefore this feature request will request the feature to perform this mapping. For example, we can provide a naming convention in out_stackdriver that all labels under prefix ‘logging.googleapis.com/labels’ in one log message are extracted and set as labels under the log entry.
This patch will support fluent bit out_stackdriver to perform ingesting customize labels.
The issue number that it is related to:  #2282 
----
**Testing** …

out_stackdriver: provide interface for ingesting customize labels

---

plugins/out_forward/forward.c

Without this patch, the following command-line invocation
causes memory corruption.
$ fluent-bit -i dummy -o forward -p Time_as_Integer=invalid
This is because `ctx->u` can be null, depending on when
`cb_forward_init()` aborted the initialization process.

out_forward: add null check for crx->u before deallocation

---

plugins/in_tail/tail.c
plugins/in_tail/tail_config.h
plugins/in_tail/tail_dockermode.c
plugins/in_tail/tail_dockermode.h
plugins/in_tail/tail_file.c
plugins/in_tail/tail_file_internal.h
tests/runtime/CMakeLists.txt
tests/runtime/data/tail/log/dockermode.log
tests/runtime/data/tail/log/dockermode_multiple_lines.log
tests/runtime/data/tail/log/dockermode_splitted_line.log
tests/runtime/data/tail/log/dockermode_splitted_multiple_lines.log
tests/runtime/data/tail/out/dockermode.out
tests/runtime/data/tail/out/dockermode_multiple_lines.out
tests/runtime/data/tail/out/dockermode_splitted_line.out
tests/runtime/data/tail/out/dockermode_splitted_multiple_lines.out
tests/runtime/data/tail/parsers.conf
tests/runtime/in_tail.c

Use Parser to verify if line is valid first line while using dockermode.
For example input:
```
{"log":"2020-03-24 Test line of first log\n"}
{"log":"           Another line of first log\n"}
{"log":"2020-03-24 Test line of second log\n"}
```
And regex: `Regex (?<log>^{"log":"\d{4}-\d{2}-\d{2}.*)`
Will output:
```
[0] containers.var.log.containers.test.log: [1585071971.732015500,
{"log"=>"{"log":"2020-03-24 Test line of first log
\n           Another line of first log\n"}"}]
[1] containers.var.log.containers.test.log: [1585071975.000917200,
{"log"=>"{"log":"2020-03-24 Test line of second log\n"}"}]
```
Fixes #1115 
**Testing**
Documentation should be updated with information how parser is use to …

in_tail: Support multiline functionality (not filter) in dockermode

---

src/aws/flb_aws_util.c

aws: bug fix: flb_aws_is_auth_error payload can be NULL

---

plugins/in_tail/tail_dockermode.c

in_tail: dockermode: fix mem leak (CID 304957)

---

plugins/in_tail/tail_scan_win32.c

Currently tail_scan_pattern() returns -1 if no file is found to
match the given pattern. For this reason, the caller was unable
to distinguish "no file found" and "an unexpected error occured".
Make it sure to return 0 if no file is found. This should allow
flb_tail_scan() to emit this message:
[debug] 0 new files found on path 'C:\*\test.log'
instead of:
[warn] error scanning path: C:\*\test.log

in_tail: tweak the return code of tail_scan_pattern()

---

plugins/out_nrlogs/newrelic.c

This patch fixes the format of the New Relic output payload - the payload needs to be an array.
While the current format will send the data successfully, New Relic interprets the whole payload as a stringified array. By sending as an array, we meet the New Relic MELT API spec, and are able to distinguish individual key/values from the payload.
Sample spec can be seen here: https://docs.newrelic.com/docs/logs/new-relic-logs/log-api/introduction-log-api#log-attribute-examples
Signed-off-by: Julian Giuca <julian@newrelic.com>
----
**Testing**
---- …

out_nrlogs: wrap output in an array to match the API

---

plugins/out_stackdriver/stackdriver.c
tests/runtime/data/stackdriver/stackdriver_multi_entries_severity.log
tests/runtime/out_stackdriver.c

This is the unit test for multi-entries log.
It is the following part of PR#[2380](https://github.com/fluent/fluent-bit/pull/2380#issue-454905278).
This PR will be pending due to the [issue](https://github.com/fluent/fluent-bit/pull/2380#issuecomment-662548318) of `in_tail`.
----
**Testing**
----

out_stackdriver: test: multi entries log

---

tests/runtime/data/stackdriver/stackdriver_multi_entries_severity.log
tests/runtime/out_stackdriver.c

Update the [unit test for multi-entries logs](https://github.com/fluent/fluent-bit/pull/2384).
----
**Testing**
----

tests: runtime: out_stackdriver: update test for multi entries log

---

plugins/out_stackdriver/CMakeLists.txt
plugins/out_stackdriver/stackdriver.c
plugins/out_stackdriver/stackdriver.h
plugins/out_stackdriver/stackdriver_helper.c
plugins/out_stackdriver/stackdriver_helper.h
plugins/out_stackdriver/stackdriver_operation.c
plugins/out_stackdriver/stackdriver_operation.h
tests/runtime/out_stackdriver.c

Since the PR #2302 is too large, we separate it into several parts.
In this part, we update the `operation` field.
----
**Testing**
----

out_stackdriver: update special field - operation

---

plugins/out_stackdriver/stackdriver.c
plugins/out_stackdriver/stackdriver.h
tests/runtime/data/stackdriver/stackdriver_test_insert_id.h
tests/runtime/out_stackdriver.c

Since the PR #2302 is too large, we separate it into several parts.
In this part, we support the `insertId` field.
----
**Testing**
----

out_stackdriver: support special field - insertId

---

plugins/out_stackdriver/CMakeLists.txt
plugins/out_stackdriver/stackdriver.c
plugins/out_stackdriver/stackdriver.h
plugins/out_stackdriver/stackdriver_source_location.c
plugins/out_stackdriver/stackdriver_source_location.h
tests/runtime/data/stackdriver/stackdriver_test_source_location.h
tests/runtime/out_stackdriver.c

Since the PR #2302 is too large, we separate it into several parts.
In this part, we update the `sourceLocation` field.
----
**Testing**
----

out_stackdriver: support special field - sourceLocation

---

plugins/out_stackdriver/CMakeLists.txt
plugins/out_stackdriver/stackdriver.c
plugins/out_stackdriver/stackdriver.h
plugins/out_stackdriver/stackdriver_http_request.c
plugins/out_stackdriver/stackdriver_http_request.h
tests/runtime/data/stackdriver/stackdriver_test_http_request.h
tests/runtime/out_stackdriver.c

Since the PR #2302 is too large, we separate it into several parts.
In this part, we update the `httpRequest` field.
----
**Testing**
----

out_stackdriver: support special field - httpRequest

---

plugins/out_stackdriver/CMakeLists.txt
plugins/out_stackdriver/stackdriver.c
plugins/out_stackdriver/stackdriver_timestamp.c
plugins/out_stackdriver/stackdriver_timestamp.h
tests/runtime/data/stackdriver/stackdriver_test_timestamp.h
tests/runtime/out_stackdriver.c

In this PR, we support two formats of `timestamp`:
1. "timestamp":{"seconds": "", "nanos":""}
2. "timestampSeconds":"" & "timestampNanos":""
----
**Testing**
----

out_stackdriver: support special field - timestamp

---

include/fluent-bit/flb_stacktrace.h

When fluent-bit runs in the container, if it captures a SIGSEGV signal, it can not print the stack trace to stdout.
It seemly likes the stdout had to be closed after the fluent bit receives a SIGSEGV signal. This pr fix this bug
by making the stack trace to output to stderr.
Signed-off-by: wanjunlei <wanjunlei@yunify.com>
----
**Testing**
----

engine: fix can not print stack trace when fluent bit run in container

---

plugins/out_stackdriver/stackdriver.c
plugins/out_stackdriver/stackdriver.h
plugins/out_stackdriver/stackdriver_conf.c
tests/runtime/data/stackdriver/stackdriver_test_k8s_resource.h
tests/runtime/out_stackdriver.c

out_stackdriver relies on the **local_resource_id** to extract kubernetes meta information and then put them into the resource labels. However there is case that local_resource_id is missing from the payLoad. Therefore we need to construct the local_resource_id from the current tag value of the log event. As the tag value is assigned in the begging of the logging pipeline by tail plugin. 
----
**Testing**
----

out_stackdriver: Construct local_resource_id from tag when field is missing

---

plugins/out_stackdriver/stackdriver.c
tests/runtime/data/stackdriver/stackdriver_test_k8s_resource.h
tests/runtime/out_stackdriver.c

The issue #2423 is caused by that the k8s metadata in the stackdriver context are shared for the same stackdriver instance. However different logs might contain different value of metadata. This patch will fix the issue.
#2423 
----
**Testing**
----

out_stackdriver: fix metadata not assigned correctly (issue-2423)

---

plugins/out_stackdriver/stackdriver.c
plugins/out_stackdriver/stackdriver.h
plugins/out_stackdriver/stackdriver_conf.c
tests/runtime/out_stackdriver.c

This patch will enable users to make change on the tag_prefix required for the k8s resource type. Users needed to use tag prefix `k8s_container.*` for k8s_resource type before because the tag prefix is used to validate the tag value of the log record. This patch will provide an interface to customize the tag_prefix when using k8s resource types in stackdriver plugin.
----
**Testing**
----

out_stackdriver: add new configurable option `tag_prefix`

---

src/flb_parser.c

This hack is meant to be for the old syslog format, which does
not contain a year part in timestamp (e.g. "Aug 10 13:20:55").
Obviously this hack is not applicable to Unix timestamps. Let's
fix it.
This bug was originally pointed out by @LionelCons in #2388

parser: avoid applying "time without year" hack to "%s"

---

CMakeLists.txt
cmake/windows-setup.cmake

Lionel Cons reports that Fluent Bit sometimes adds odd "drift"
to timestamps e.g. parsing "10000" with "%s" results in 13600.0
rather than 10000.0.
This occurs because "%s" is parsed differently depending on the
implementation of strptime(). Some use localtime() internally,
and others use gmtime(). This causes the parsed result to vary
by the amount of each system's time offset.
This patch attempts to fix that issue by defaulting to our own
version of strptime(), and hence makes the behaviour much more
consistent across platforms.

build: Use flb_strptime() by default

---

plugins/in_tail/tail.c

Currently using the option `exit_on_eof` in `true` with the `tail` plugin works well with one file, but when reading a bunch of files it fails since the plugin will exit as soon as it reach the first EOF in one of the files, this will prevent that until it reach the last file

in_tail: When option exit_on_eof=true wait for all the files to be read

---

src/flb_dump.c

Using SIGCONT it's very useful to debug and trace stuff within fluent-bit but in some cases, specially when using output plugin `stdout` when you want to redirect the plugin output to a file and still debugging, this PR fix that issue by printing everything to stderr so you can still redirecting the output to a file while debug the errors

core: flb_dump() use stderr instead of stdout when getting SIGCONT

---

src/flb_signv4.c

https://github.com/fluent/fluent-bit/blob/4b9ac8c78fbb25d62c74e7d955bdb0a5f20158a0/src/flb_signv4.c#L970-L984
----
**Testing**
----

signv4: remove duplicate assignment

---

plugins/out_nats/nats.c

https://github.com/fluent/fluent-bit/blob/4b9ac8c78fbb25d62c74e7d955bdb0a5f20158a0/plugins/out_nats/nats.c#L47
https://github.com/fluent/fluent-bit/blob/4b9ac8c78fbb25d62c74e7d955bdb0a5f20158a0/plugins/out_nats/nats.c#L65
----
**Testing**
----

out_nats: remove duplicate assignment

---

src/flb_http_client.c

`fmt_plain` expects 3 arguments, but `body_len` is the 4th.
----
**Testing**
----

http_client: fix format string mismatch

---

src/flb_ra_key.c

In our production k8s environment Fluent Bit will constantly crash with the following:
```
[engine] caught signal (SIGSEGV)
#0  0x559f5469c459      in  ra_key_val_id() at src/flb_ra_key.c:83
#1  0x559f5469ca2c      in  flb_ra_key_regex_match() at src/flb_ra_key.c:294
#2  0x559f5469c11c      in  flb_ra_regex_match() at src/flb_record_accessor.c:577
#3  0x559f546834cd      in  process_record() at plugins/filter_rewrite_tag/rewrite_tag.c:305
#4  0x559f546836d5      in  cb_rewrite_tag_filter() at plugins/filter_rewrite_tag/rewrite_tag.c:377
#5  0x559f545d4b79      in  flb_filter_do() at src/flb_filter.c:118
#6  0x559f545fb537      in  flb_input_chunk_append_raw() at src/flb_input_chunk.c:473
#7  0x559f54610b76      in  cb_queue_chunks() at plugins/in_emitter/emitter.c:142
#8  0x559f545d462f …
```

ra: Fix crashes when ra_key_val_id() is passed a non-map

---

plugins/out_cloudwatch_logs/cloudwatch_api.c

Avoid buffer overflows, just in case.
----
**Testing**
----

out_cloudwatch_logs: replace insecure sprintf

---

src/record_accessor/flb_ra_parser.c

flb_ra_parser_destroy(rp) may attempt to free uninitialized key->subkeys
when key->name failed to allocate.
----
**Testing**
----

ra: fix undefined behavior on error

---

plugins/out_stackdriver/stackdriver_http_request.c

MSVC does not support variable length arrays. For this reason,
this line raises a syntax error while compilation.
error C2133: 'extract_latency': unknown size
Avoid that error by using a fixed buffer size.
Note: According to the spec, the max value of latency/Duration is
"315576000000.999999999s". So a 64 bytes buffer should be enough,
even if there are some white spaces prefixed.
References 
* https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#HttpRequest
* https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Duration

out_stackdriver: Make out_stackdriver compilable with MSVC

---

plugins/in_winlog/pack.c

The "EventId" field was removed in cd54540a in part of an effort
to canonicalize the output format.
The assumption behind the removal was that "EventId" was too low
level to be meaningful for uesrs, and just having the human readable
"Message" field is just enough.
Our assumption was wrong. This reverts the removal to resolve
#2426 ("WinLog input plugin stopped reporting the EventId").

in_winlog: Bring back the 'EventId' field

---

src/flb_scheduler.c

https://github.com/fluent/fluent-bit/blob/d1bcfa8d1767020ff1a3bf68f004193eb49ceacd/src/flb_scheduler.c#L46-L50
src/flb_scheduler.c: cosumer_bytes() gives errors in macOS (10.13,... ?).
function flb_pipe_r can return value 0 which is consider as error. 
This patch allows return value zero.
Probably we should test if ret == 0 is ok in other operating systems. 
Fixes #2460 
----
**Testing**
---- …

core:  flb_scheduler fix for macOS

---

plugins/out_splunk/splunk.c

Similar to #2456, in our production k8s environment Fluent Bit will crash with the following:
```
[engine] caught signal (SIGSEGV)
#0  0x561a400562eb      in  splunk_format() at plugins/out_splunk/splunk.c:114
#1  0x561a4005657a      in  cb_splunk_flush() at plugins/out_splunk/splunk.c:175
#2  0x561a3ffe24df      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:449
#3  0x561a4040a8a6      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
```
Once again, I tracked this down to `splunk_format()` being passed non-array data. This will then cause a segfault when trying to read key-value pairs out of an assumed-to-be-there map.
Specifically, it seems to get passed an object with type `MSGPACK_OBJECT_POSITIVE_INTEGER`. Occasionally it'll get passed an array *containing* a …

out_splunk: Fix crashes when passed non-array input data

---

plugins/out_stackdriver/stackdriver.c
tests/runtime/out_stackdriver.c

Reported by the Fluent Bit community that if the tag_prefix include dot '.' then the stackdriver plugin will fail to parse the correct labels value for the k8s resource type. This patch will fix the issue and support including dot '.' in tag prefix.
----
**Testing**
----

out_stackdriver: support dot '.' in tag_prefix option 

---

plugins/in_exec/in_exec.c

Fixes crash caused by missing reference to logging context.
Signed-off-by: yang-padawan <25978390+yang-padawan@users.noreply.github.com>
Adding missing reference to logging context.
Logging was updated by 2c7c16db to use newly added `ins` attribute of `flb_exec` struct. That attribute was never populated, causing crashes whenever a log should have been produced by the plugin.
Fixes #2523
----
**Testing**
See #2523 for configuration.
```
$ ./bin/fluent-bit -c fluent_bit.conf
Fluent Bit v1.6.0 …
```

in_exec: fix logging crash

---

src/flb_ra_key.c

Just fix a typo of comment.
----
**Testing**
----

ra: fix typo of comment

---

src/aws/flb_aws_util.c

aws: utils: fix mem leak in flb_imds_request

---

include/fluent-bit/flb_upstream.h
src/flb_engine.c
src/flb_io.c
src/flb_upstream.c

The following patch introduces a new mechanism to cleanup upstream connections, avoiding corruption while there are still events to be processed.
In my local tests, I could no longer reproduce the issue, anyways we need extra testing.

address upstream connection corruption (Issue 2497)

---

plugins/out_stackdriver/stackdriver.c
plugins/out_stackdriver/stackdriver.h
tests/runtime/out_stackdriver.c

There is case that tag is generated by tag expansion as mentioned by [here](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#workflow-of-tail-kubernetes-filter). Currently the parsing logic to get resource labels for k8s resource types assume that the tag is in format like k8s_container.xxx.xxx.xxx. However it is not the default format of the tag when kubernetes filter plugin is used.
Note that this patch only supports default regex for now, tag_regex options could be added as future improvement.
----
**Testing**
---- …

out_stackdriver: parse tag that generated by tag expansion to extract k8s resource labels

---

cmake/windows-setup.cmake
include/fluent-bit/flb_utils.h
plugins/out_azure_blob/azure_blob_uri.c
src/flb_utils.c
tests/internal/mp.c

With this PR merged, `out_azure_blob` can be compiled and linked
on Windows.
I confirmed it works on Windows Server 2019 by sending test data
to  Azure Storage Account.
This patch also should fix CI builds on AppVeyor.

Port Azure BLOB plugin to Windows

---

src/flb_pack.c

Do not use `%lu` to format 64-bit int; A long can be 32-bit depending
on the system, so this line can implicitly truncate the target value.
This should fix the "timestamps are truncated inproperly" bug on
out_datadog reported by #2527. 

pack: Use PRIu64/PRId64 to format 64 bit integers.

---

tests/internal/fuzzers/CMakeLists.txt
tests/internal/fuzzers/msgpack_parse_fuzzer.c
tests/internal/fuzzers/msgpack_to_gelf_fuzzer.c
tests/internal/fuzzers/pack_json_state_fuzzer.c

Adds three new fuzzers. These target msgpack conversions as well as json packing.
----
**Testing**
----

Adds three new fuzzers.

---

tests/runtime/out_cloudwatch.c

out_cloudwatch_logs: Disable net.keepalive in test

---

plugins/in_forward/fw_config.h

Use FLB_IN_FW_CONFIG_H instead the MQTT one
Looks like there is a file copy leftover.
----

Fix copy paste

---

.travis.yml

See: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
----
**Testing**
----

ci: travis: remove deprecated key

---

plugins/out_es/es.c
plugins/out_es/es.h
tests/runtime/out_elasticsearch.c

Starting in Elasticsearch 7, a "date_nanos" data type was added, increasing timestamp precision from milliseconds to nanoseconds.
This patch adds a "Time_Key_Nanos" option which tells the ElasticSearch output plugin to send 9 decimal places instead of 3 to ElasticSearch.
Tests are included, and a patch to document the new option will be submitted shortly.
Addresses #2014.
----
**Testing**
----

out_es: support nanosecond timestamp precision

---

README.md

Add missing plugins to `README.md`.
- AWS Metadata
- Expect
- Rewrite Tag
----
**Testing**
----

doc: Add missing plugins to README

---

include/fluent-bit/flb_random.h
src/CMakeLists.txt
src/flb_random.c
tests/internal/CMakeLists.txt
tests/internal/random.c

This adds flb_randombytes(), which fills the given buffer with random
numbers using each OS's built-in Crypt API.
The most common use scenario is:
unsigned char buf[64]
if (get_randombytes(buf, 64)) {
flb_error("cannot get random bytes");
}
This function supports both UNIX and Windows. You can use this
function without caring the underlying OS.

random: Introduce a random generator

---

plugins/in_cpu/cpu.c
plugins/in_cpu/cpu.h

Handle per-process CPU stats the same way as system CPU stats by normalizing the value by the number of CPU cores.
Signed-off-by: yang-padawan <25978390+yang-padawan@users.noreply.github.com>
Changes the function called to compute per-process CPU stats (`/proc/[pid]/stat`) from per-core stats function to system-wide stats function. Removes the unused `CPU_METRIC_PID_USAGE` function.
Fixes #2542 
----
**Testing**
```
$ bin/fluent-bit -i cpu -p 'pid=18721' -t proc_cpu -i cpu -t sys_cpu -o stdout -m '*' -vv
Fluent Bit v1.6.0
* Fluent Bit is a CNCF sub-project …
```

in_cpu: Normalize per-process CPU stats by number of cores.

---

src/flb_strptime.c

According to the UNIX standard:
The external variable timezone shall be set to the difference,
in seconds, between Coordinated Universal Time (UTC) and local
standard time
FreeBSD is incompatible with this standard. In particular, since it
exposes a function symbol `char* timezone(int, int)`, expressions
like `-(timezone)` causes a compile error.
Fix #2491 by adding a compat macro for FreeBSD.

strptime: Add a fallback macro for `timezone`

---

plugins/out_forward/forward.c

There is an initialization bug in `out_forward` that leaves the shared key
salt being uninitialized if SSL is not enabled.
This might allow attackers to guess the shared key by looking at the hash.
Let's always initialize the salt buffer securely.

out_forward: Always initialize salt with random numbers

---

plugins/out_pgsql/pgsql.c
plugins/out_pgsql/pgsql.h

The SQL query will change when new option `cockroachdb` it's set to true
There's another PR associated fluent/fluent-bit-docs#373  in `fluent-bit-docs` repository to add the proper documentation

out_pgsql: Add support for CockroachDB

---

plugins/in_stdin/in_stdin.c
plugins/in_stdin/in_stdin.h

Add ability to configure buffer size for stdin input plugin with respect of default value (2 * 8192)
Addresses #2199 #89
----
**Testing**
----

in stdin: add buffer_size parameter

---

plugins/in_tail/tail.c
plugins/in_tail/tail_config.h
plugins/in_tail/tail_db.c
plugins/in_tail/tail_file.c
plugins/in_tail/tail_file_internal.h
plugins/in_tail/tail_fs_inotify.c
plugins/in_tail/tail_fs_stat.c
plugins/in_tail/tail_multiline.c
plugins/in_tail/tail_multiline.h
plugins/in_tail/tail_signal.h
plugins/in_tail/win32/stat.h

Previously it was not possible to handle files larger than 2GB on
Windows as discussed in #2208.
The fix is archived by migrating each vairable and function to be
explicitly 64-bit ready.

in_tail: Add large file support for Windows

---

include/fluent-bit/flb_aws_credentials.h
include/fluent-bit/flb_aws_util.h
plugins/out_cloudwatch_logs/cloudwatch_logs.c
plugins/out_cloudwatch_logs/cloudwatch_logs.h
plugins/out_es/es.c
plugins/out_es/es.h
plugins/out_es/es_conf.c
plugins/out_kinesis_firehose/firehose.c
plugins/out_kinesis_firehose/firehose.h
plugins/out_s3/s3.c
plugins/out_s3/s3.h
src/aws/flb_aws_credentials.c
src/aws/flb_aws_credentials_sts.c
src/aws/flb_aws_util.c
tests/internal/aws_credentials.c
tests/internal/aws_credentials_sts.c

- Added STS endpoint support for CW and ES plugin.
- Add sts_endpoint option in eks_provider and aws_sts_provider
- Added support to specify endpoint and sts_endpoint with or without the protocol. 
_E.g. endpoint logs.us-west-2.amazonaws.com and endpoint https://logs.us-west-2.amazonaws.com will work._ 
```
[OUTPUT]
Name cloudwatch_logs
Match *
log_stream_prefix fluent-bit-
log_group_name fluent
region us-west-2
auto_create_group On
role_arn arn:aws:iam::xxxxxxxxxxxx:role/test
sts_endpoint https://sts.us-west-2.amazonaws.com
endpoint logs.us-west-2.amazonaws.com
```
```
[OUTPUT]
Name  es
Match *
Host vpc-test-domain-ke7thhzoo7jawrhmz6mb7ite7y.us-west-2.es.amazonaws.com
Port  443
Index my_index
Type  my_type
Aws_Auth On
Aws_Region us-west-2
aws_role_arn arn:aws:iam::xxxxxxxxxxxx:role/test …
```

aws: Adding sts endpoint for CW and ES plugins

---

plugins/out_cloudwatch_logs/cloudwatch_api.c
plugins/out_cloudwatch_logs/cloudwatch_api.h

out_cloudwatch_logs: fix payload creation bugs

---

plugins/out_kinesis_firehose/firehose_api.c

out_kinesis_firehose: fix type of event_bytes (CID 309457)

---

plugins/out_kinesis_firehose/firehose_api.c

out_kinesis_firehose: Use correct printf format for time_t (CID 309456)

---

src/flb_fstore.c

fstore: fix null dereference (CID 309455)

---

src/aws/flb_aws_util.c

aws_util: fix double free issues in get_s3_key (CID 309453 & 309443)

---

plugins/out_s3/s3_multipart.c

out_s3: fix possible null dereference (CID 309448)

---

plugins/out_s3/s3.c

out_s3: always cast fstore meta_buf to char * (CID 309442)

---

plugins/out_s3/s3_multipart.c

out_s3: fix mem leak (CID 309438)

---

plugins/out_stackdriver/gce_metadata.c
plugins/out_stackdriver/gce_metadata.h
tests/runtime/out_stackdriver.c

The value for project ID of monitored resources of a LogEntry should be
project ID, not the project number, which is in numeric format.
The value of the project ID of Cloud Logging's Monitored Resources are
documented in
https://cloud.google.com/logging/docs/api/v2/resource-list.
The project ID to be retrived from instance metadata is documented in
https://cloud.google.com/compute/docs/storing-retrieving-metadata#default.
----
**Testing**
----

out_stackdriver: use the correct project ID

---

src/flb_pack.c

The recent change to the JSON floating point formatting to use `%.16g` caused a
regression where values that have no fractional part are formatted as integers.
For example, `10.0` gets formatted as `10`. This patch uses the same approach
as https://github.com/ohler55/oj/blob/v3.10.13/ext/oj/dump_strict.c#L100-L101,
which is used in Fluentd. It checks if the double value is equal to the integer
part, and if so, will use `%.1f` as the format to ensure the decimal part is
still rendered (with a single decimal place of `.0`). This prevents downstream
datastores from having data type conflicts.
This was tested by building locally and running through different value using
the dummy input plugin and stdout output plugin with json_lines formatting.
Will include example outputs of tests in Pull …

pack: fix json floating point format regression

---

plugins/out_s3/s3.c

out_s3: use correct printf format for MAX_UPLOAD_ERRORS (CID 309440)

---

plugins/out_stackdriver/gce_metadata.c

Signed-off-by: Yen-Cheng Chou <ycchou@google.com>
----
**Testing**
----

out_stackdriver: fix project_id length for testing

---

plugins/out_gelf/gelf.c

Windows does not have /dev/urandom. For this reason, it was always
using a less secure value (= UNIX time) as an entropy source.
Use flb_randombytes() to use a good entropy source, and thus,
reduce the possibility of message collision.

out_gelf: Port the random seed generation to Windows

---

plugins/in_tail/tail_dockermode.c
plugins/in_tail/tail_file.c
plugins/in_tail/tail_file_internal.h
tests/runtime/data/tail/log/dockermode_firstline_detection.log
tests/runtime/data/tail/out/dockermode_firstline_detection.out
tests/runtime/in_tail.c

Do not concatenate multiline logs in docker mode until first line is detected
Update runtime tests with additional test for this change
Fixes #2585
----
**Testing**
----

in_tail: Do not concatenate multiline logs in docker mode until first line is detected

---

src/fluent-bit.c

f303cdb5c has removed the global symbol "config" on which winsvc.c
depends. This ended up producing the following error:
error LNK2001: unresolved external symbol config
Bring back the symbol to make Windows Service working again.

win32: fix 'error LNK2001: unresolved external symbol config'

---

plugins/out_cloudwatch_logs/cloudwatch_api.c
plugins/out_cloudwatch_logs/cloudwatch_logs.c
plugins/out_cloudwatch_logs/cloudwatch_logs.h

Found this while trying to repro #2612. There are cases where a single flush can be split up into 5+ API calls, which can end up always resulting in a throttling exception, even on retries, since the entire batch is retried. This case should be extremely rare, so I didn't make the self-throttling logic very complex.
----
**Testing**
----

out_cloudwatch_logs: bug fix: self throttle if too many calls per flush

---

plugins/filter_aws/aws.c
plugins/filter_aws/aws.h
src/aws/flb_aws_util.c

This commit is for expand the AWS filter for supporting more EC2 metadata.
The default two fields:
* az            ${availability_zone}
* ec2_instance_id    ${instance_id}
The new fields are:
* hostname      ${hostname}
* ec2_instance_type ${instance_type}
* private_ip    ${private_ip}
* vpc_id        ${vpc_id}
* ami_id        ${image_id}
* account_id    ${account_id}
AWS Metadata Filter Plugin for EC2/ECS Metadata #1780
----
**Testing**
Example configuration
```
[FILTER]
Name aws
Match *
imds_version v2
az true
ec2_instance_id true
ec2_instance_type true
private_ip true
ami_id true
account_id true
hostname true
vpc_id true
```
Debug log output
```
[ec2-user@ip-172-31-6-59 build]$ bin/fluent-bit -c ../../config/fluent-bit.conf
Fluent Bit v1.6.0
* Copyright (C) 2019-2020 The Fluent Bit …
```

expand the EC2 metedata fields

---

ci/do-ut.ps1

This unittest relies on chunkio's file storage, which Windows port
does not support yet. Let's skip it for now.
This patch is required to build the Windows package for
Fluent Bit v1.6.0  on Appveyor.

ci: Skip 'tests/internal/input_chunk.c' on Windows

---

plugins/filter_aws/aws.c

filter_aws: fix return in get_vpc_metadata

---

plugins/out_cloudwatch_logs/cloudwatch_api.c

MSVC++ does not provide <unistd.h>. For this reason, including
this header breaks the compilation on Windows.
Fix it by adding an ifdef block to the header.

out_cloudwatch_logs: Don't include <unistd.h> on Windows

---

cmake/windows-setup.cmake

This patch ports the AWS core module (src/aws/flb_s3_local_buffer.c)
to Windows, and thereby allows Microsoft Visual Studio to compile
and link S3 plugin.
With this patch, #2631 and edsiper/chunkio/pull/53 combined, the master
HEAD can be compiled and run on Windows again.

aws: port Amazon S3 plugin to Windows

---

plugins/out_stackdriver/stackdriver.c

Signed-off-by: Yen-Cheng Chou <ycchou@google.com>
This is spun off from #2616 . See https://github.com/fluent/fluent-bit/pull/2616#discussion_r498461447 for details.
----
**Testing**
----

out_stackdriver: clean up buffer before return

---

include/fluent-bit/flb_task.h
src/flb_engine.c
src/flb_task.c

Signed-off-by: Tanapol Rattanapichetkul <tanapol.raa@gmail.com>
This typo message make it a bit harder to investigating log message.
----
**Testing**
----

task: fix typo messages and variables name 'attemps' to 'attempts'

---

plugins/out_stackdriver/stackdriver.c

Signed-off-by: Peijia Luo <luopeijia@JefffffffdeMacBook-Pro.local>
----
**Testing**
----

out_stackdriver: update error message

---

plugins/out_s3/s3.c
src/flb_fstore.c

out_s3: fix build failures

---

plugins/out_s3/s3.c
plugins/out_s3/s3_multipart.c
plugins/out_s3/s3_store.c

out_s3: fix multipart upload buffering

---

plugins/out_s3/s3.c
src/flb_signv4.c

More S3 Fixes

---

plugins/out_es/es_conf.c

out_es: make aws_sts_endpoint optional

---

include/fluent-bit/flb_intermediate_metric.h
plugins/out_cloudwatch_logs/cloudwatch_api.c
plugins/out_cloudwatch_logs/cloudwatch_api.h
plugins/out_cloudwatch_logs/cloudwatch_logs.c
plugins/out_cloudwatch_logs/cloudwatch_logs.h
src/CMakeLists.txt

This changes will enable customers to send cpu and mem metrics to CloudWatch in EMF format.
----
**Testing**
----

CloudWatch EMF Metric: Add support for cpu and mem input metrics

---

CMakeLists.txt
plugins/CMakeLists.txt
plugins/filter_tensorflow/CMakeLists.txt
plugins/filter_tensorflow/tensorflow.c
plugins/filter_tensorflow/tensorflow.h

Tensorflow Lite plugin for Fluent Bit. The filter imports a `.tflite` model file and runs inference on the input field defined in configuration. It returns/adds two fields `tf_out` and `inference_time` to the output record, containing the result of the inference, and the time spent on calculating the inference.
example configuration file:
```
[SERVICE]
Flush        1
[INPUT]
Name mqtt
Tag mqtt.data
[FILTER]
Name tensorflow
input_field image
model_file /home/user/model.tflite
include_input_fields false
normalization_value 255
Match mqtt.data
[OUTPUT]
Name stdout
Match *
```
valgrind output:
```
valgrind --leak-check=full ./build/bin/fluent-bit -c conf/filter_tensorflow.conf 
==3679== Memcheck, a …
```

Add Tensorflow Lite filter plugin

---

lib/mbedtls-2.24.0/CMakeLists.txt

CMAKE_C_CFLAGS -> CMAKE_C_FLAGS, this avoids C_FLAGS from environment
being overridden.
Signed-off-by: Ming Liu <liu.ming50@gmail.com>
----
**Testing**
----

mbedtls:CMakeLists.txt: fix a typo

---

tests/internal/fuzzers/CMakeLists.txt
tests/internal/fuzzers/parser_fuzzer.c

Provides a more general parser fuzzer than existing ones. This fuzzer aims to target both parser creation and parser routines.
This is the first of several fuzzers to be pushed in the near future. However, I will do it incrementally, mainly for the reason that it is convenient to see progress of coverage in OSS-Fuzz UI and also to limit the amount of bugs we receive from the fuzzers at once. 
----
**Testing**
- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that …

Adds a general parser fuzzer 

---

tests/internal/fuzzers/CMakeLists.txt

Fixes typo in CMakeLists.txt
----
**Testing**
----

Fix typo in cmakelists for fuzzers.

---

src/flb_scheduler.c

Windows does not support /dev/urandom. For this reason, it ended
up using a weak entropy source for task scheduling.
Avoid this issue by using flb_random_bytes() instead.

scheduler: use flb_random_bytes() instead of /dev/urandom

---

plugins/out_s3/s3.c

out_s3: Run upload callback without async mode

---

tests/internal/fuzzers/CMakeLists.txt
tests/internal/fuzzers/flb_fuzz_header.h
tests/internal/fuzzers/http_fuzzer.c
tests/internal/fuzzers/parser_fuzzer.c
tests/internal/fuzzers/strp_fuzzer.c

Two new fuzzers and a minor bit of refactoring to use a central fuzzer header for common code. 
----
**Testing**
----

Http-client fuzzer, strp fuzzer and minor refactoring. 

---

plugins/in_winlog/in_winlog.c
plugins/in_winlog/pack.c
plugins/in_winlog/winlog.h

A user (jsubirat) requested that in_winlog should be able to output
StringInserts in log records.
This patch implements that feature, which enables you to write the
plugin configuration like:
[INPUT]
Name winlog
StringInserts true
... and here is an example record after this patch:
{
"RecordNumber"=>333,
"TimeGenerated"=>"2020-08-11 10:56:41 -0000",
"TimeWritten"=>"2020-08-11 10:56:41 -0000",
"EventType"=>"Information",
"Message"=>"Starting session 0 - 2020-08-11T10:56:41.595894000Z.",
"StringInserts"=>["0", "2020-08-11T10:56:41.595894000Z"]
}
Fixes #2427 

in_winlog: Add a new configuration option "StringInserts"

---

src/flb_engine_dispatch.c

Fix the problem that the task cannot be executed due to the wrong status in non-multiplex mode. When it traverses the task queue, it resets the flag used to determine the task status
Signed-off-by: zhanghjster <zhanghjster@gmail.com>
----
**Testing**
----

engine: fix handling of task status of non-multiplex mode

---

tests/internal/fuzzers/CMakeLists.txt
tests/internal/fuzzers/utils_fuzzer.c

Adds a new fuzzer and include it in the OSS-Fuzz build. This fuzzer targets various utility functions, including gzip and hash logic. 
----
**Testing**
----

Added a utils fuzzer

---

plugins/out_es/es.c

out_es: default AWS options to NULL in config map #2714

---

plugins/out_es/es.c

out_es: default AWS options to NULL in config map 

---

include/fluent-bit/flb_network.h
src/flb_network.c
src/flb_upstream.c

Allow users to configure the max number of uses of a connection before it gets
thrown away. In cases where fluentbit is used with an upstream behind a
load-balancer, we can get better distribution amongst upstreams by tuning this
value.
----
**Testing**
I'm happy to write documentation for this once the config file change is agreed upon.
----
----
Sample config snippet of an output with this new option:
```ini …
```

network: optionally destroy keepalive connections after configured uses

---

include/fluent-bit/flb_parser.h
src/flb_parser.c
tests/internal/data/parser/json.conf
tests/internal/data/parser/regex.conf
tests/internal/parser.c

Previously our time parser only supports '%S.%L' (or '%S,%L') as
the sub-second time format.
This generalizes the support so that it can handle an arbitrary
occurance of %L (so for example '%S:%L' is now a valid format).
Closes #2210 and #2367.

parser: Implement generic support for %L (subseconds)

---

appveyor.yml

MSYS seems to be unstable. Indeed, our CI is currently failing with
the following error:
> warning: failed to retrieve some files
> downloading flex-2.6.4-1-x86_64.pkg.tar.xz...
> error: failed to commit transaction (unexpected error)
> Errors occurred, no packages were upgraded.
>
> https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/36072635
Mitigate the failure by switching to downloading WinFlexBison from GitHub.
**NOTE** I can confirm that [this patch makes Appveyor happy.](https://ci.appveyor.com/project/fujimotos/fluent-bit-github/builds/36075084)

ci: Download WinFlexBison from GitHub instead of MSYS

---

src/flb_io.c

Sockets were always initialized to synchronous mode in flb_io_net_connect.
This caused a large performance cost when using http_do in async mode.
----
**Testing**
- [ N/A ] Documentation required for this feature
----

io: Fix flb_io_net_connect only opening sync connections

---

include/fluent-bit/flb_config.h
include/fluent-bit/flb_http_client.h
include/fluent-bit/flb_upstream.h
include/fluent-bit/flb_utils.h
plugins/out_http/http.c
plugins/out_stackdriver/stackdriver.c
src/flb_config.c
src/flb_http_client.c
src/flb_io.c
src/flb_io_tls.c
src/flb_upstream.c
src/flb_utils.c
tests/internal/utils.c

- Add http_proxy in global config and set during upstream creation
- HTTP_PROXY url with username and password is also supported with this PR: `http://username:password@host:port`
- Implement `CONNECT` based HTTP support so that HTTPS can work over
a HTTP proxy. This is important for stackdriver.
- The key is to do proxy negotiation before tls handshake. that's why
proxy negotiation has to be in upstream.c.
Signed-off-by: Yu Yi <yiyu@google.com>
Fixes #2565 
----
**Testing**
https://github.com/fluent/fluent-bit-docs/pull/414
---- …

http_client: use HTTP_PROXY environment variable for proxy globally

---

src/flb_strptime.c

This commit https://github.com/fluent/fluent-bit/commit/163af0b9c0513f31cc4cbfe8aeee26d22513163c introduced a regression that causes parser tests to fail.
We only need bounds checking in the first place added by this commit, not the second.
Tests passing now. 
----
**Testing**
----
Fluent Bit is licensed under Apache 2.0, by submitting this pull …

strptime: fix regression

---

src/flb_config_map.c

A fix to ensure proper memory allocation to avoid double-free (oss-fuzz 27025).
----
**Testing**
----

Double-free fix

---

src/flb_parser.c

parser: fix inconsistent memory allocation in parser creation (oss-fuzz 26345)
This solves issue https://github.com/fluent/fluent-bit/issues/2686
The approach taken is to avoid any freeing of memory provided by the caller inside of `flb_parser_create`. The issues is well-explained in the link so I won't go into detail with it here, but please ask if clarification is needed.
The current approach in the `flb_parser_create` routine will inevitably lead to either use-after-frees, double-frees or memory leakage. 
This commit fixes https://github.com/fluent/fluent-bit/issues/2686 by
avoiding any free of memory provided by the caller in flb_parser_create.
----
**Testing**
Before we …

parser: fix inconsistent memory allocation in parser creation

---

src/flb_input_chunk.c

Signed-off-by: Jeff Luo <jefflpj@outlook.com>
This change is to keep the bytes counter updated when there are backoff logs on the container before running Fluent-bit.
----
**Testing**
----

in_storage_backlog: update bytes counter for backoff logs

---

include/fluent-bit/flb_aws_util.h
plugins/out_cloudwatch_logs/cloudwatch_logs.c
plugins/out_cloudwatch_logs/cloudwatch_logs.h
src/aws/flb_aws_util.c

Add extra_user_agent option to append strings to the user agent.
----
**Testing**
----

out_cloudwatch_logs: add extra_user_agent option

---

src/flb_scheduler.c

This is partly related to https://github.com/fluent/fluent-bit/pull/2463 for MacOS.
The first one is in  flb_pipe_r() function returning 0 on FreeBSD 12+ and that
brings up errors similar to "[error] [src/flb_scheduler.c:52 errno=0] No error:
0". This patch will fix it the same way as it was fixed by upstream code for
MacOS.
The second issue is a SIGSEGV that is caused by incorrect section
structure of the resulting binary file generated by clang due to some gcc
specific code in libco.  Since there are two copies of libco (flb_libco) code
in the fluent-bit sources - one in the lib/flb_libco folder and another one in
lib/monkey/deps/flb_libco - they are both patched the same way.
This patches were tested on FreeBSD 11.4 and 12.2 amd64.
The resulting binaries was tested with "elfdump -a" to …

Fix problem with SIGSEGV on FreeBSD 12+

---

plugins/out_forward/forward.c
plugins/out_forward/forward.h
plugins/out_forward/forward_format.c

Enables optional gzip compression in out_forward plugin, compliant with https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1.
Fixes #1497
----
**Testing**
https://github.com/fluent/fluent-bit-docs/pull/417
----

out_forward: add compress option for gzip compression

---

plugins/out_cloudwatch_logs/cloudwatch_logs.c
plugins/out_kinesis_firehose/firehose.c
plugins/out_s3/s3.c

Call flb_output_upstream_set() in all AWS Outputs

---

plugins/out_cloudwatch_logs/cloudwatch_api.c
plugins/out_cloudwatch_logs/cloudwatch_logs.c
plugins/out_cloudwatch_logs/cloudwatch_logs.h
tests/runtime/out_cloudwatch.c

support retention for `cloudwatch_logs` output plugin.
introduce a new property `log_retention_days`.
Addresses #2691
----
**Testing**
----

support retention for cloudwatch_logs output

---

src/win32/winsvc.c

This fixes the bug "Fluent Bit is stuck pending on WinServer 2012".
Apparently, Windows Server 2012 imposes a strict parameter control
on SetServiceStatus() and it returns errors if the service type is
set differently than the creation-time flag.
Avoid that issue by using "SERVICE_WIN32_OWN_PROCESS".

win32: Use SERVICE_WIN32_OWN_PROCESS for dwServiceType

---

plugins/out_s3/s3.c
plugins/out_s3/s3.h
plugins/out_s3/s3_multipart.c

Add support for canned ACL
Addresses part of #2700 
----
**Testing**
----

out_s3: add support for canned ACL

---

src/flb_pack_gelf.c
src/flb_parser_json.c
src/flb_record_accessor.c
src/flb_signv4.c
tests/internal/fuzzers/utils_fuzzer.c

Contains several fixes found by fuzzers.
----
**Testing**
----

Fixes of bugs found by fuzzers

---

src/flb_network.c

Windows build is failing with the following error:
flb_network.c(243): error C2065: 'u_conn': undeclared identifier
This is because `u_conn` is not defined within the scope of this
function (net_connect_sync).
With this patch, master HEAD becomes compilable on Windows again.

network: Fix an invalid reference to `u_conn`

---

cmake/windows-setup.cmake
plugins/in_storage_backlog/sb.c

This patch is what is needed in Fluent Bit's side to allow
Windows users to start using filesystem storage.
With this and edsiper/chunkio/pull/59 merged, I can confirm that
Fluent Bit can persist input data on disks.

in_storage_backlog: Add Windows file storage support

---

src/flb_pack_gelf.c

As discussed with myself in https://github.com/fluent/fluent-bit/issues/2256, the restrictions on log level in GELF is a **should**, and also it is an optional field; so it doesn't seem to have a hard restriction on level value, as Graylog accepts the non-standard levels.
So I changed the attempt to be some kind of best-effort to match with standards, but if it's not, send it anyway and just throw a warning.
This PR also adds invocation of an error when level is not a string or a non-negative integer (As I haven't seen any negative log level and I think other data types mustn't be valid, yes?)
----
**Testing**
- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was …

out_gelf: accept possible level values

---

plugins/out_bigquery/bigquery_conf.c

BigQuery output plugin discards the last character of URL for if dataset_id and table_id are long enough.  
`flb_sds_create_size(sizeof(FLB_BIGQUERY_RESOURCE_TEMPLATE)-7` is wrong as afterward flb_sds_printf is called that relies on `vsnprintf` that discards the remaining characters if the resulting string would be longer than n-1 characters.
`flb_sds_create_size(sizeof(FLB_BIGQUERY_RESOURCE_TEMPLATE)-7` should be replaced with `flb_sds_create_size(sizeof(FLB_BIGQUERY_RESOURCE_TEMPLATE)-6 `if really would like to preserve every byte
Fixes https://github.com/fluent/fluent-bit/issues/2728
**Testing**
Tested with the same conditions as in https://github.com/fluent/fluent-bit/issues/2728 
```echo '{"lol":42}' | docker run -v $PWD/bq:/cred -i fluent/fluent-bit:latest /fluent-bit/bin/fluent-bit …
```

biquery plugin should not discard the last character of URL

---

include/fluent-bit/flb_parser.h
src/flb_parser.c
tests/internal/fuzzers/parse_json_fuzzer.c
tests/internal/fuzzers/parse_logfmt_fuzzer.c
tests/internal/fuzzers/parse_ltsv_fuzzer.c
tests/runtime/filter_parser.c

The old behaviour was that it accepts time data only if the
format is specified exactly. If the format does not match, it
simply returns an error.
However, with the new `Time_Strict` option, a time parser can
behave in "best effort" mode, and be permissive on heterogeneous
time data.
For example, suppose you set up the following time format:
Time_Format %Y-%m-%dT%H:%M:%S.%L
... and received the record like this:
{"time":"2020-11-10T11:11:26+00:00"}
With `Time_Strict` turned off, you'll get the following result:
"2020-11-10T11:11:26+00:00" => 2020-11-10T11:11:26.000000Z

parser: Add a new option 'Time_Strict'

---

src/flb_input_chunk.c

Signed-off-by: Jeff Luo <jefflpj@outlook.com>
Backoff logs are pulled by a input plugin that users are not able to config. And also the plugin doesn't have the tag value that can be used to route the input chunks to their destination. I found that there is a function `flb_input_chunk_get_tag` that can be used to extract the tag value of the input chunk from metadata.
#2765 
----
**Testing**
----

input_chunk: Update tag value extraction for backoff logs

---

CMakeLists.txt
src/flb_http_client.c
tests/internal/fuzzers/CMakeLists.txt
tests/internal/fuzzers/config_fuzzer.c
tests/internal/fuzzers/engine_fuzzer.c
tests/internal/fuzzers/flb_json_fuzzer.c
tests/internal/fuzzers/http_fuzzer.c
tests/internal/fuzzers/parser_fuzzer.c
tests/internal/fuzzers/utils_fuzzer.c

Fuzzer updates to cover more entry points in the lib.

---

src/aws/flb_aws_credentials.c

aws: ECS comes before EC2 in standard chain

---

src/flb_network.c

Commit 90b2354 changed `flb_net_tcp_connect()` to check for errno
to detect EINPROGRESS, which does not work on Windows simply
because Win32's `connect()` does not set errno.
This causes general network issues on Windows. The common issue
is that Fluent Bit returns fatal errors erratically while the connection is
actually in progress.
Fix this bug by checking the connection status correctly on Windows

network: net_connect_*() is broken on Windows

---

include/fluent-bit/flb_str.h
plugins/out_kafka/kafka.c

`val.via.str.ptr` here is not a regular C string - it is not `\0`
terminated as it comes from `msgpack`. Thus, using the regular `strstr`
here is bad as we might "jump over" to other content in memory.
Introduce a new `flb_strnchr` which operates on possibly NULL-terminated
strings.  Use it in the `kafka` output plugin.
Using `strncmp` is fine because the char arrays need not be
NULL-terminated.
Fixes #2836. Cannot reproduce it locally after this fix.
Huge, huge kudos to @deimantastumas for a lot of investigation and a
very good test case. <3
Signed-off-by: Giedrius Statkevičius <giedriuswork@gmail.com>
Co-authored-by: Deimantas Tumas <d.tumas@adform.com>
Before:
```
./fluent-bit --config=fluent-bit.conf
Fluent Bit v1.7.0 …
```

kafka: check only for first val.via.str.size chars
