documentation/getting_started/installation.md

add a line about osx installation

---

plugins/in_serial/in_serial.c

Signed-off-by: Takeshi HASEGAWA <hasegaw@gmail.com>

in_serial: Restore termios before exiting.

---

plugins/out_fluentd/fluentd.c

Looks like the fluentd output plugin connects to fluentd every time it want to flush data. Since we already get the socket fd in pre run, may we reuse it and get connected if disconnected from fluentd?
If this direction is not correct, please let me know and I will close this pr. Thanks.

Reuse the socket fd created in pre run and reconnect to fluentd if disconnected

---

examples/hello_world/hello_world.c
examples/hello_world_cpp/hello_world.cc

For developer using flb_lib* functions, I add some lines.
* flb_lib_exit() to release resources.
* flb_config_verbose(). (This function is commented out.)

hello_world/cpp: add sample codes. How to use  flb_lib_exit() and flb_config_verbose()

---

README.md
documentation/SUMMARY.md
documentation/input/head.md

I wrote a document about head plugin.
Please review it.
Signed-off-by: nokute78 <nokute78@gmail.com>

Doc: add Head documentation

---

documentation/development/README.md
documentation/output/README.md

I updated the list of output plugins and fix typo.

Doc: Update the list of ouput plugins

---

examples/hello_world/hello_world.c
examples/hello_world_cpp/hello_world.cc

I fixed hello_world/cpp.
* add sentinel value
To notify the end of va_list with NULL as a sentinel value.
* replace "tag" to "match".
According to Routing, I think we should pass "match" to flb_output_set().

Fix hello_worlds.

---

src/flb_router.c

I wrote a patch to support routing with wildcard.
I tested new function with this test code.
``` c
#include <string.h>
#ifndef DEBUG
#define flb_debug
#else
#define flb_debug printf
#endif
/* wildcard support */
/* tag and match should be null terminated. */
static int is_matched(const char* tag, const char* match)
{
int    ret = 0;
char*  pos = NULL;
while(1){
flb_debug("tag[%x]:%c match[%x]:%c\n",tag,*tag,match,*match);
if (*match == '*') {
while(*++match == '*'){
/* skip successive '*' */
}
if(*match == '\0'){
/*  '*' is last of string */
ret = 1;
break;
}
while ( pos = strchr(tag, (int)*match) ) {
if ( is_matched(pos, match) ){
ret = 1;
break;
}
tag = pos+1;
}
break;
}else if ( *tag != *match ) {
/* mismatch! */
break;
}else if( *tag == '\0'){
/* end of tag. so …
```

router:wildcard support (#55)

---

src/flb_input.c

input: fix typo

---

documentation/README.md

Doc: fix URL

---

conf/in_head.conf

I updated in_head.conf to support new configuration schema.

config: update in_head.conf

---

plugins/in_kmsg/in_kmsg.c

I added exit callback to in_kmsg plugin to cleanup .

in_kmsg: add exit callback

---

README.md
tests/CMakeLists.txt
tests/flb_test_in_random.cpp

I add new test code and update README.md.
Result of test is  like this.
```  sh
$ bin/flb_test_in_random 
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Inputs
[ RUN      ] Inputs.flush_5s
[2016/08/22 21:03:13] [ info] [engine] started
[2016/08/22 21:03:18] [ warn] [engine] service will stop in 5 seconds
[2016/08/22 21:03:23] [ info] [engine] service stopped
[       OK ] Inputs.flush_5s (9981 ms)
[----------] 1 test from Inputs (9981 ms total)
[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (9981 ms total)
[  PASSED  ] 1 test.
```

in_random : add test code and add explanation

---

tests/CMakeLists.txt
tests/flb_test_in_head.cpp

I added a new program to test `in_head` plugin.

tests: add a new test for in_head plugin

---

.travis.yml

I fixed travis file to enable CI.
It was failed because of no makefile.

ci: fix CI configuration

---

README.md

I modified README.md. 
* add in_tcp, in_health, out_plot, out_flowcount.

README: update plugin information

---

conf/out_flowcount.conf

I added a configuration file to use out_flowcount.

conf: add configuration file for out_flowcount

---

plugins/in_health/health.c

I added new option "add_host" of in_health to display hostname to check health.
Using like that.
`$ bin/fluent-bit -i health://google.com:80 -p add_host=true -o stdout`
In this case, "hostname"->"google.com" is appended with this new option.
```
$ bin/fluent-bit -i health://google.com:80 -p add_host=true -o stdout     
[2016/11/18 23:04:44] [ info] [engine] started
[0] health.0: [1479477885, {"alive"=>true, "hostname"=>"google.com"}]
[1] health.0: [1479477886, {"alive"=>true, "hostname"=>"google.com"}]
[2] health.0: [1479477887, {"alive"=>true, "hostname"=>"google.com"}]
[3] health.0: [1479477888, {"alive"=>true, "hostname"=>"google.com"}]
```

health:add new option to display hostname

---

plugins/in_health/health.c

Refer to #136 
I added new option "add_port" of in_health to display port number to check health.
Using like that.
`$ bin/fluent-bit -i health://google.com:80 -p add_host=true -p add_port=true -o stdout`
```
$ bin/fluent-bit -i health://google.com:80 -p add_host=true -p add_port=true -o stdout
[2016/11/19 12:24:20] [ info] [engine] started
[0] health.0: [1479525861, {"alive"=>true, "hostname"=>"google.com", "port"=>80}]
[1] health.0: [1479525864, {"alive"=>true, "hostname"=>"google.com", "port"=>80}]
[2] health.0: [1479525864, {"alive"=>true, "hostname"=>"google.com", "port"=>80}]
```

health:add new option to display port

---

plugins/in_health/health.c

I added a code to prevent 0byte allocation.

in_health:prevent 0byte allocation

---

tests/CMakeLists.txt
tests/flb_test_in_proc.cpp

I added a test code for in_proc.

tests: add test for in_proc plugin

---

plugins/in_head/in_head.c
plugins/in_head/in_head.h
plugins/in_stdin/in_stdin.c
plugins/in_stdin/in_stdin.h

I removed unused variable of in_head, in_stdin.
Note: see also #62 .

Remove unused variable

---

conf/in_disk.conf
conf/in_proc.conf

I updated configuration files.
* add a file about in_disk
* modify in_proc file. (add description about "mem" option, and modify some lines)

Conf update

---

src/fluent-bit.c

I made filter plugin configurable with file.
We can configure like this.
```python
[INPUT]
Name cpu
Tag  cpu.local
[OUTPUT]
Name  stdout
Match **
[FILTER]
Name  stdout
Match *
```
```
$ bin/fluent-bit -c fluent-bit.conf 
[2017/02/02 21:40:28] [ info] [engine] started
[0] cpu.local: [1486039229, {"cpu_p"=>4.000000, "user_p"=>3.000000, "system_p"=>1.000000, "cpu0.p_cpu"=>4.000000, "cpu0.p_user"=>3.000000, "cpu0.p_system"=>1.000000}]
[0] cpu.local: [1486039230, {"cpu_p"=>7.000000, "user_p"=>6.000000, "system_p"=>1.000000, "cpu0.p_cpu"=>7.000000, "cpu0.p_user"=>6.000000, "cpu0.p_system"=>1.000000}]
[0] cpu.local: [1486039231, {"cpu_p"=>3.000000, "user_p"=>2.000000, "system_p"=>1.000000, "cpu0.p_cpu"=>3.000000, "cpu0.p_user"=>2.000000, …
```

bin: add configuration file support for filter plugin

---

plugins/in_mem/mem.c

I modified in_mem to be consistent with free(1).
It also traces swap usage.
I tested raspbian( which supports "MemAvailable") and CentOS6 (which doesn't support MemAvailable)
```
$ bin/fluent-bit -i mem -o stdout &
[1] 5814
[2017/01/24 14:36:48] [ info] [engine] started
[0] mem.0: [1485268609, {"Mem.total"=>948016, "Mem.used"=>193960, "Mem.free"=>754056, "Swap.total"=>102396, "Swap.used"=>0, "Swap.free"=>102396}]
[1] mem.0: [1485268610, {"Mem.total"=>948016, "Mem.used"=>193904, "Mem.free"=>754112, "Swap.total"=>102396, "Swap.used"=>0, "Swap.free"=>102396}]
[2] mem.0: [1485268611, {"Mem.total"=>948016, "Mem.used"=>193936, "Mem.free"=>754080, "Swap.total"=>102396, "Swap.used"=>0, "Swap.free"=>102396}]
[3] mem.0: [1485268612, …
```

in_mem: modify to be consistent with free(1)

---

src/flb_lib.c

lib: replace raw write with flb_pipe_w

---

plugins/out_flowcounter/out_flowcounter.c

This PR is to fix bug of out_flowcounter.
Old record causes infinite loop and fluent-bit will hang up.
In this code, in_lib throws old data and out_flowcounter will output log eternally.
https://gist.github.com/nokute78/ac22e0244f03867c5d90b7a0a118655d

out_flowcounter: discard old record

---

src/flb_config.c

I added missing releasing code.

config: release env struct

---

plugins/filter_grep/grep.c

Some input plugins generate a value as a MSGPACK_OBJECT_BIN.
By the way, filter_grep can handle only MSGPACK_OBJECT_STR format now.
e.g. in_proc is an one of input plugin which generates a value as a MSGPACK_OBJECT_BIN.
So, this command doesn't work.
```
$ bin/fluent-bit -i proc -p 'proc_name=fluent-bit' -o stdout -F grep -p 'regex=proc_name fluent-bit' -m '*'
```
This PR makes filter_grep also handle MSGPACK_OBJECT_BIN.
```
$ bin/fluent-bit -i proc -p 'proc_name=fluent-bit' -o stdout -F grep -p 'regex=proc_name fluent-bit' -m '*'
[2017/03/02 22:38:04] [ info] [engine] started
[0] proc.0: [1488461885, {"alive"=>true, "proc_name"=>"fluent-bit", "pid"=>31219, "mem.VmPeak"=>15344000, "mem.VmSize"=>15344000, "mem.VmLck"=>0, "mem.VmHWM"=>1284000, …
```

filter_grep: allow MSGPACK_OBJECT_BIN format

---

src/flb_pack.c

To fix #209.
I added a code to handle MSGPACK_OBJECT_FLOAT32 and MSGPACK_OBJECT_EXT.

pack:add float and ext cases

---

README.md

I added description about filter plugins.

README: add filter plugins

---

CMakeLists.txt
include/fluent-bit/flb_time.h
plugins/in_random/random.c
plugins/out_stdout/stdout.c
src/CMakeLists.txt
src/flb_time.c

refer to #193
I added a code to support nanosecond. 
Note : this is a step1 of the roadmap.
1. define flb_time struct and utilities. (append to msgpack, pop from msgpack, generate flb_time ...)
2. modify output plugins.
3. modify filter plugins.
4. modify input plugins.

Nanosecond support Step1

---

plugins/filter_record_modifier/filter_modifier.c

I fixed leak of flb_split_entry and replaced free() with flb_free().

Fix leak of filter_record_modifier

---

src/flb_pack.c

pack: fix handling null string

---

plugins/in_cpu/in_cpu.c
plugins/in_cpu/in_cpu.h

in_cpu: replace msgpack_pack_bin with str

---

plugins/in_head/in_head.c

in_head: replace msgpack_pack_bin with str

---

plugins/in_serial/in_serial.c

in_serial: replace msgpack_pack_bin with str

---

plugins/in_random/random.c

in_random: replace msgpack_pack_bin with str

---

plugins/in_disk/in_disk.c

in_disk: replace msgpack_pack_bin with str

---

plugins/in_health/health.c

in_health: replace msgpack_pack_bin with str

---

plugins/out_td/td.c

out_td: replace msgpack_pack_bin with str

---

plugins/in_proc/in_proc.c

in_proc: replace msgpack_pack_bin with str

---

plugins/in_mem/mem.c

in_mem: replace msgpack_pack_bin with str

---

README.md

I added a description about record_modifier.

README: add a description about record_modifier

---

tests/CMakeLists.txt
tests/flb_test_filter_grep.cpp
tests/flb_test_filter_stdout.cpp

Hi, I added new tests for filter plugin the below.
- stdout
- grep
Could you review my commits?

Add filter plugin tests (stdout, grep)

---

src/flb_filter.c

Hi, I fixed memory leak for filter found by unit test.
If inputs illegal parameter to filter plugin, the filter plugin instance will be removed when starts engine.
However, properties of the filter are not freed.
Could you check this modification?

filter: fix memory leak of property on failure case

---

src/proxy/go/CMakeLists.txt

Signed-off-by: Khem Raj <raj.khem@gmail.com>

flb-plugin-proxy-go: Add missing dependency on jemalloc

---

conf/parsers.conf

Update to parser.conf

---

plugins/in_dummy/in_dummy.c

in_dummy:fix leak

---

src/flb_hash.c

* Compare entry->key with key even when there is just one
entry present in the list.

Fix hash collision logic

---

plugins/filter_parser/filter_parser.c

When there are 2 lines at least ready to process on input and Reserve_data is On, fluent-bit gets SIGSEGV

filter_parser: reset append_arr_i to handle the next result

---

tests/runtime/CMakeLists.txt
tests/runtime/flb_test_in_disk.c

I added a test for in_disk plugin.

tests:runtime add test for in_disk

---

plugins/in_kmsg/in_kmsg.c
plugins/in_systemd/systemd.c

Found two places where the input is usec but the conversions to nsec were either done with the wrong operator or omitted. Fixes: #443

Make sure conversions from usec to nsec are correct

---

README.md
plugins/in_exec/in_exec.c

I fixed in_exec.
* add explanation to README.md
*  fix return values (it was always failed value)
*  fix wrong option message ( cmd -> command )

Fix in_exec

---

plugins/filter_lua/lua.c
scripts/test.lua

Signed-off-by: Manuel Luis Sanmartín Rozada <manuel.luis@gmail.com>

filter_lua: for the record use a lua table instead of a json string

---

plugins/filter_lua/lua.c

filter_lua: Initialize ffi to use CDATA

---

include/fluent-bit/flb_network.h
plugins/in_syslog/syslog.h
plugins/in_syslog/syslog_conf.c
plugins/in_syslog/syslog_server.c
src/flb_network.c

Patch a bit to add syslog udp network. Tested locally
Should fix #760

in_syslog: Add syslog udp network

---

plugins/in_mem/proc.c

To fix #766 
I modified the way to scrape process name from /proc/PID/stat.
Linux allows process name which contains '(', ')'.
In /proc/PID/stat, the process name is enclosed by '()'. (e.g. process `(a)` will be `((a))` in /proc/PID/stat)
So, the tail of process name is previous byte of final ')'.
I modified to seek ')' from tail of /proc/PID/stat.

in_mem: modify parsing proc name

---

plugins/in_cpu/in_cpu.c

Signed-off-by: Yann Soubeyrand <ysoubeyrand@leadformance.com>

in_cpu: fix compilation warning

---

plugins/filter_kubernetes/kube_property.c

Fix const warning on strnchr

---

src/flb_input.c

If an input was created which had a syntax error, it would
not be properly free'd.
Refactor to create an flb_input_free() function and call from
both the 'error' case and the normal 'delete all' case.

Fix leak in input teardown when there was an error on 'up'

---

plugins/CMakeLists.txt

I found comment message typo.
so I fix it!

plugin cmake config: fix typo

---

README.md

Add travis build badge to README.md

---

tests/runtime/filter_kubernetes.c

test: filter_kubernetes: fix compile warning on systemd test

---

src/flb_sosreport.c

Since we have neither uname() nor sysconf() on Windows, we need to
use Win32 API to retrieve the equivalent information.
With this patch, I can confirm that the following command runs fine
on Windows.
PS> fluent-bit -S
Part of #960

sosreport: make flb_sosreport() work for Windows

---

CMakeLists.txt

+ ignore for some Centos system dirs
+ CPACK_RPM_PACKAGE_RELEASE = CPACK_PACKAGE_RELEASE

Update CMakeLists.txt for rpm be usable

---

CONTRIBUTING.md

Fix typo and break run-on sentence.
Signed-off-by: heartrobotninja <github@heartrobotninja.com>

doc: contributing: fix typo s/pacth or patches/patches

---

plugins/out_es/es.c
plugins/out_es/es_conf.c

out_es: add path option.

---

plugins/in_tail/tail_file.c

This is part of the ongoing effort to port in_tail to Windows.
This patch teaches in_tail how to get the file name from an open file
descriptor on Windows. Essentially, we needed to convert the file
descriptor to HANDLE and ask the metadata about it though Win32 API.
Part of #960

in_tail: implement flb_tail_file_name() for Windows

---

src/flb_pack.c

Fixes #1164 , see that for details.
Also fixes the error message.

[gelf] Allow valid level 7.

---

src/stream_processor/flb_sp.c

sp: fix memory leak in exp_string_to_number function

---

ci/do-ut.ps1
cmake/windows-setup.cmake
include/fluent-bit/flb_compat.h
src/stream_processor/flb_sp.c
src/stream_processor/parser/CMakeLists.txt
src/stream_processor/parser/sql.l
src/stream_processor/parser/sql.y
tests/internal/stream_processor.c

Revised of https://github.com/fluent/fluent-bit/pull/1218.

 sp: Make buildable with msys2ed windows for first step. Revised of #1218 

---

src/stream_processor/flb_sp.c

sp: fix aggregation computation with default window type

---

src/stream_processor/flb_sp.c
tests/internal/stream_processor.c

sp: add tests for invalid aggregation queries

---

src/flb_output.c

Signed-off-by: Warren Fernandes <wfernandes@pivotal.io>

[output]: remove unnecessary loop to initialize proxies

---

src/stream_processor/README.md

sp: add @record.contains to stream processor's README

---

src/stream_processor/flb_sp.c
src/stream_processor/flb_sp_groupby.c
tests/internal/stream_processor.c

sp: fix group-by key comparison on Boolean keys

---

plugins/filter_modify/modify.c
plugins/in_tail/tail_dockermode.c
src/flb_kernel.c
src/flb_output.c
src/flb_pack.c

Also convert tab to 4 spaces in `src/flb_pack.c`.

Fix memory leaks

---

examples/hello_world_cpp/hello_world.cc

`ret` is not used anywhere in this file.

examples: hello world C++: remove unused variable

---

debian/control

build: Add cmake to source package Build-Depends.
build: Add flex and bison as suggested dependencies for binary packages.

build: Add missing dependencies to debian/control

---

src/http_server/api/v1/metrics.c

Two major updates:
1. Metrics are grouped, and each group has TYPE annotation.
2. Added process_start_time_seconds metric.

Fix prometheus format of metrics.

---

src/flb_sds.c

fixes: https://github.com/fluent/fluent-bit/issues/1527

sds: flb_sds_cat_utf8: fix utf-8 conversion

---

include/fluent-bit/stream_processor/flb_sp_parser.h
src/flb_config.c
src/stream_processor/flb_sp.c
src/stream_processor/parser/flb_sp_parser.c
src/stream_processor/parser/sql.y

sp: allow RECORD_TIME() as parameter in timeseries functions

---

src/flb_uri.c

Signed-off-by: Lang Chi <21860405@zju.edu.cn>

fix a spelling error

---

src/stream_processor/flb_sp.c

sp: fix dereferencing possible NULL pointers

---

plugins/in_systemd/systemd_config.c

Current `systemd` has the [unresolved bug](https://github.com/systemd/systemd/issues/9934), which prevents sd_journal_seek_tail() from seeking to the end of the last available `journald` log file.
Instead, two log messages were read from each log file until the end of last file is reached.
Then, the reading sequence continues monotonously for all new log messages, which is the expected behavior. But those two lines of old logs per journal file come as the very first logs after startup of `fluent-bit`, which is very confusing: it appeas as if the `Read_From_Tail` option of `in_systemd` does not work.
Luckily, the workaround is trivial: the sd_journal_next_skip() systemd function may be called immediately after sd_journal_seek_tail() to throw away some records that are still readable.
I …

in_systemd: Read_From_Tail also reads two entries from each journald file

---

README.md

Signed-off-by: Valerian Pereira <valerianpereira25@gmail.com>

Fixed Invalid hyperlink links

---

plugins/in_disk/in_disk.c

To fix #1626 
I  added missing memory checking code.

in_disk: validate memory allocation on init(#1626)

---

plugins/out_kafka/kafka_config.c

Signed-off-by: Nicholas Brown <nick.brown@att.com>

Initialising wrong variables for message_key

---

src/flb_output.c

Output instance_id is calculated base on filters instance_id.

output: fix duplicated instance_id

---

src/flb_config_static.c

core: const-correctness fixups for static configuration mode (#1682)

---

plugins/out_slack/slack.c

out_slack: fix calculation of print buffer in flush function

---

plugins/out_influxdb/influxdb.c

out_influxdb: add missing MSGPACK_OBJECT_FLOAT32 to influxdb_format

---

src/http_server/api/v1/metrics.c

We had a report #1755  that says the subsequent `qsort(metrics_arr)`
fails randomly with a segmentation fault. A possible cause is that
flb_sds_cat() failed to allocate memory and returned NULL here:
sds_metric = flb_sds_cat(sds_metric, "\n", 1);
metrics_arr[index] = sds_metric;
This attempts to fix the bug based on this hypothesis, by adding
proper return code checking to the relevant code.

http_server: fix potential SIGSEGV due to memory allocation errors

---

plugins/filter_kubernetes/kube_meta.c

Make help info more clear, once this error happend, kubernetes filter would skip,
Signed-off-by: Xiang Dai <764524258@qq.com>

Minor clarification of runtime error message in Kubernetes filtering

---

src/stream_processor/README.md
src/stream_processor/parser/sql.l
src/stream_processor/parser/sql.y
tests/internal/stream_processor.c

sp: add support for != and <> operators in WHERE condition

---

lib/flb_libco/ppc.c

Signed-off-by: Khem Raj <raj.khem@gmail.com>

ppc: Fix signature for co_create API

---

Dockerfile.windows.devel

@fujimotos can you take a look?
I built this on top of #1656 so that I didn't have to bother with installing OpenSSL. It shouldn't be too hard to do it with `scoop` though in the same place we're installing `winflexbison`.
#960

Add a Dockerfile for Windows

---

snap/snapcraft.yaml

Added support of pgsql plugin to snap package

snap: out_pgsql: Added support of pgsql plugin to snap package

---

README.md

README : added link to DEVELOPER_GUIDE.md

---

plugins/out_pgsql/pgsql.c

@edsiper  This it's a backport for PostgreSQL output plugin on version 1.4. Fix issue #2059

out_pgsql: Fix escaping issue (#2059)

---

README.md
documentation/README.md

As per https://github.com/DavidAnson/markdownlint/blob/v0.19.0/doc/Rules.md

Lint README

---

plugins/out_tcp/tcp.c
plugins/out_tcp/tcp_conf.c

In place of PR #1870 
Refer https://github.com/fluent/fluent-bit/pull/1870#issuecomment-584216614

out_tcp: register config_map

---

tests/internal/data/parser/json.conf
tests/internal/data/parser/regex.conf

Signed-off-by: Asher Foa <asher@asherfoa.com>

Fix typos in test config files.

---

plugins/out_pgsql/pgsql.c

Added column tag and time to PostgreSQL table, this will allow users
to better partition the table and distribute a big amount of data.
Added some check on PQgetResult() until sync and async version it's don

Added column tag and time to PostgreSQL table, this will allow users

---

plugins/out_pgsql/pgsql.c

out_pgsql: Fix excessive log message.

out_pgsql: Fix excessive log message.

---

src/aws/flb_aws_util.c

aws: util: use memcpy instead of strncat and set null byte

---

plugins/out_es/es.c
plugins/out_es/es.h
plugins/out_es/es_conf.c

#1804
#1807
----
**Testing**
----

Full Amazon ElasticSearch Service Support 

---

include/fluent-bit/flb_pack.h
include/fluent-bit/flb_parser_decoder.h
include/fluent-bit/record_accessor/flb_ra_parser.h
plugins/filter_grep/grep.c
plugins/filter_kubernetes/kube_conf.h
plugins/filter_kubernetes/kubernetes.c
plugins/filter_lua/lua.c
plugins/filter_parser/filter_parser.c
plugins/filter_record_modifier/filter_modifier.c
plugins/filter_throttle/throttle.c
plugins/in_tail/tail_file.c
plugins/in_tail/tail_file_internal.h
plugins/out_azure/azure.c
plugins/out_bigquery/bigquery.c
plugins/out_datadog/datadog.c
plugins/out_es/es.c
plugins/out_kafka/kafka.c
plugins/out_kafka_rest/kafka.c
plugins/out_splunk/splunk.c
plugins/out_stackdriver/stackdriver.c
src/flb_config_static.c
src/flb_input_chunk.c
src/flb_oauth2.c
src/flb_pack.c
src/flb_parser_decoder.c
src/flb_plugin_proxy.c
src/flb_storage.c
src/proxy/go/go.c
src/stream_processor/flb_sp.c
src/stream_processor/parser/flb_sp_parser.c

Looking at the instances and locations used, it seems very likely that
the meaning of 'temporary' is intended. For native English speakers,
temporary is clear, temporal is somewhat confusing.
This article helps make the distinction clear:
https://english.stackexchange.com/questions/7539/temporal-vs-temporary

Replace uses of 'temporal' with 'temporary'.

---

src/flb_strptime.c

This incorporates recent changes from OpenBSD project. The current
latest HEAD of strptime(3) in upstream is rev 1.30.
https://cvsweb.openbsd.org/src/lib/libc/time/strptime.c?rev=1.30

strptime: Apply upstream changes to flb_strptime().

---

plugins/out_splunk/splunk.c

The Splunk HTTP Event Collector [will return HTTP 4xx errors for authorization, authentication, or bad payloads](https://docs.splunk.com/Documentation/Splunk/8.0.5/Data/TroubleshootHTTPEventCollector#Possible_error_codes).
(In my estimation, bad requests are most likely to occur when using the `Splunk_Send_Raw` configuration option.)
In the logs this will look as follows under load:
```
[2020/08/11 19:45:55] [ warn] [output:splunk:splunk.0] http_status=400:
{"text":"No data","code":5}
[2020/08/11 19:45:55] [ warn] [engine] chunk '1-1597175144.127888580.flb' cannot be retried: task_id=0, input=splunk-raw > output=splunk.0
[2020/08/11 19:45:56] [ warn] [engine] failed to flush chunk '1-1597175155.177903791.flb', retry in 8 seconds: task_id=0, input=splunk-raw > output=splunk.0
```
At …

out_splunk: Avoid retries for requests we know will fail

---

src/aws/flb_aws_util.c

aws_util: fix failing sanitizer builds

---

plugins/in_random/random.c

Simplify the random seed generation by using flb_randombytes()
instead of trying to read entropy sources manually.
This is a part of the cleanups originating from #2555.

in_random: Use the new API to generate a random seed

---

include/fluent-bit/flb_aws_util.h
plugins/out_s3/s3.c
plugins/out_s3/s3_multipart.c
src/aws/flb_aws_util.c

Use path style S3 regional endpoints

---

src/flb_hash.c
src/flb_parser.c
src/flb_utils.c
tests/internal/fuzzers/CMakeLists.txt
tests/internal/fuzzers/config_map_fuzzer.c
tests/internal/fuzzers/record_ac_fuzzer.c

New fuzzer for flb_config_map.c
Fixes of several bugs. 
New fuzzer
----
**Testing**
----

New fuzzers and bug fixing.

---

src/aws/flb_aws_credentials.c

aws: credentials: Add support for EKS_POD_EXECUTION_ROLE

---

README.md

recently got added - see https://github.com/fluent/fluent-bit/issues/1004
I also capitalized the start of some lines for consistency.
----
**Testing**
----

add s3 output plugin to list

---

src/flb_engine_dispatch.c

This fix ensures that in non-multiplexing mode, if a task is in the retry state, the tasks behind it in the queue will not be started.
Signed-off-by: zhanghjster <zhanghjster@gmail.com>
Fixes #2748
----
**Testing**
----

engine: fix the out-of-order issue when there is task retry in non-multiplex mode

---

src/flb_input.c

Fluent Bit sometimes emits the following error on shutdown:
[error] [src\flb_utils.c:339 errno=0] No error
This is due to closing a socket is detected on Windows as a new
socket event.
Since the socket is already closed by the time the callback handler
dispatches, it results in the above error. Fix it.

input: Fix socket error during shutdown on Windows

---

src/tls/openssl.c

Red Hat provides system CA certificates in a bundled form (a.k.a.
ca-bundle.crt). Unfortunately, OpenSSL's CAPath feature cannot
handle such a packed cert well.
This is the root problem of bug #2973: "TLS connections are always
broken on Amazon Linux".
This mitigates the issue by teaching Fluent Bit to load `ca-bundle.crt`
(which RHEL provides in /etc/ssl/certs) if available.

tls: openssl: Load /etc/ssl/certs/ca-bundle.crt on RHEL.

---

plugins/out_s3/s3_store.c

s3_store: delete fstore files that are partially initialized

---

include/fluent-bit/flb_aws_credentials.h
plugins/out_cloudwatch_logs/cloudwatch_logs.c
plugins/out_es/es_conf.c
plugins/out_kinesis_firehose/firehose.c
plugins/out_s3/s3.c
src/aws/flb_aws_credentials.c
src/aws/flb_aws_credentials_ec2.c
src/aws/flb_aws_credentials_http.c
src/aws/flb_aws_credentials_sts.c

Support Multi Workers in AWS Credential Libraries

---

.travis.yml

Make Homebrew use bottles.
----
**Testing**
----

ci: travis: switch to macOS 10.15

---

include/fluent-bit/flb_aws_credentials.h
plugins/out_cloudwatch_logs/cloudwatch_logs.c
plugins/out_es/es_conf.c
plugins/out_kinesis_firehose/firehose.c
plugins/out_kinesis_streams/kinesis.c
plugins/out_s3/s3.c
src/aws/flb_aws_credentials.c
src/aws/flb_aws_credentials_ec2.c
src/aws/flb_aws_credentials_http.c
src/aws/flb_aws_credentials_profile.c
src/aws/flb_aws_credentials_sts.c

Support multiworkers in AWS credential libraries- attempt #2

---

include/fluent-bit/flb_aws_credentials.h
src/aws/flb_aws_credentials.c
src/aws/flb_aws_util.c
tests/internal/aws_credentials_ec2.c
tests/internal/aws_credentials_http.c
tests/internal/aws_credentials_sts.c

https://github.com/aws/aws-for-fluent-bit/issues/138
----
**Testing**
----

Fix AWS credential refresh and expiration handling

---

plugins/out_influxdb/influxdb.c
plugins/out_influxdb/influxdb.h

Fixes #3032 
----
**Testing**
https://github.com/fluent/fluent-bit-docs/pull/457
----

out_influxdb: add support v2

---

.github/workflows/README.workflows.md
.github/workflows/pr-closed-docker.yaml
.github/workflows/pr-stale.yaml
.github/workflows/test-integration-master-microk8s.yaml
.github/workflows/test-integration-pr-microk8s.yaml
MAINTAINERS.md

* Added workflow to close stale PR(s)
* Added workflow to remove stale docker image(s)
* Added workflow to run integration tests on master
* Added workflow to run integration tests on PR(s)
* Added myself to the maintainers list.
* Added README for workflows
**Testing**
This has been tested as part of my forked repository (https://github.com/niedbalski/fluent-bit/)
----

[ci/workflows] Added multiple workflows for running integration tests.

---

.github/workflows/build-master-packages.yaml

* Build packages (lib/runtime/headers) on every master merge and store the artifacts as a build artifact.
----

workflows: build packages on master merge.

---

.github/workflows/build-master-packages.yaml

* don't use actor, use master branch
----

workflows: fix build packages for master branch

---

CODEOWNERS

Added myself as a reviewer for:
- /.github
- /appveyor.yml
- /dockerfiles/
- /src/flb_lib.c

build: update codeowners

---

.github/workflows/merge-bot.yaml

* Revert to 0.4.3 as 0.4.4 exposes a bug

workflows: update merge-bot.yaml

---

.github/workflows/merge-bot.yaml
.github/workflows/pr-labels.yaml

* use pa token for pa/label actions.

workflows: change label/merge-bot to pa token

---

.github/workflows/unit-tests.yaml
appveyor.yml

workflows: ignore gh/md files from unit tests

workflows: ignore gh/md files from unit tests

---

.github/workflows/pr-labels.yaml

* run in in target, use GITHUB_TOKEN

workflows: update pr-labels.yaml

---

.github/workflows/unit-tests.yaml

* Add branch 1.7 to unit-tests.yaml

workflows: add 1.7 to unit-tests.yaml

---

plugins/out_http/http.c
plugins/out_http/http.h

This fixes https://github.com/fluent/fluent-bit/issues/2921.

out_http: add a log_response_payload parameter

---

.github/workflows/build-master-packages.yaml

workflows: update build-master-packages.yaml

---

plugins/out_cloudwatch_logs/cloudwatch_api.c

Signed-off-by: Ade Fisher adrian.fisher@montvieux.com
Fixes memory leak in out_cloudwatch_logs when using cpu or mem input
Fixes #3145 
----
**Testing**
----
Valgrind output after change
```
[2021/03/31 08:52:04] [ info] [engine] service stopped
==85211== 
==85211== HEAP SUMMARY:
==85211==     in use at exit: 0 bytes in 0 blocks
==85211==   total heap usage: 193,370 allocs, 193,370 frees, 33,548,850 bytes allocated
==85211== 
==85211== All heap blocks were freed -- no leaks are possible
==85211== 
==85211== For lists of detected and suppressed errors, rerun with: -s
==85211== ERROR SUMMARY: 23679 errors from 132 contexts …
```

out_cloudwatch_logs: fix memory leak when using cpu or mem input

---

tests/runtime/out_splunk.c

update: remove Fail initialization case.
I updated out_splunk test.
- `Splunk_Send_Raw` is enabled and check its output
- ~~Fail initialize when `http_user` is not set~~ 
----
**Testing**
```
$ bin/flb-rt-out_splunk 
Test basic...                                   [2021/04/10 08:22:52] [ info] [engine] started (pid=5798)
[2021/04/10 08:22:52] [ info] [storage] version=1.1.1, initializing... …
```

tests: runtime: out_splunk: update testcase

---

src/fluent-bit.c

Removed tabs and made sure the help text is properly aligned.
This fixes https://github.com/fluent/fluent-bit/issues/3424.
Signed-off-by: Lionel Cons <lionel.cons@cern.ch>

main: fixed help text alignment

---

.github/workflows/3398.yaml

* Builds a new docker image for branch 3398
* Triggers ci tests for running ci/long-run.

workflows: add workflow for testing issue 3398.

---

.github/workflows/3398.yaml

* Adds a dependency for docker_build

workflows: long running depends on docker_build

---

dockerfiles/Dockerfile.x86_64-3398

workflows: add 3398 dockerfile.

---

src/flb_input_chunk.c

Only drop the route of chunks to plugins that will be overlimit after ingesting new data. Current implementation will iterate over all output plugins which isn't necessary.
----
**Testing**
----

input_chunk: only iterate over overlimit output plugins

---

.github/workflows/3398.yaml

* Add gcp disk id to output commands.

workflows: enable gcp disk id.

---

plugins/in_http/http_conn.c

in_http: add pipelining support

---

plugins/out_stackdriver/stackdriver.c
src/flb_oauth2.c

out_stackdriver: implement cache for oauth2 token at thread level

---

.github/workflows/pr-stale.yaml

This PR is from comment https://github.com/fluent/fluent-bit/issues/2181#issuecomment-843689076
to explude enhancement label from stable bot.
----
**Testing**
----

workflows: Update stale bot to exclude enhancement label

---

.github/workflows/integration-run-master.yaml
.github/workflows/integration-run-pr.yaml

* Integrate bigquery tests from fluent-bit-ci

workflows: enable bigquery integration tests.

---

dockerfiles/Dockerfile.x86_64-1_7

workflows: add 1.7 dockerfile

---

.github/workflows/integration-build-master.yaml
dockerfiles/Dockerfile.x86_64-1_7
dockerfiles/Dockerfile.x86_64-master_debug

* Add debug images for master branch

workflows: add dbg images for master

---

.github/workflows/integration-build-master.yaml

workflows: update integration build master

---

.github/workflows/benchmark-run-master.yaml
.github/workflows/integration-run-master.yaml
.github/workflows/integration-run-pr.yaml

workflows: disable k8s 1.20

---

.github/workflows/integration-build-master.yaml

* enable buildkit = 1 when building master images.

workflows: enable buildkit docker for master

---

.github/workflows/integration-run-master.yaml

workflows: publish master-debug images

---

.github/workflows/integration-build-master.yaml
.github/workflows/integration-run-master.yaml

workflows: publish master debug images

workflows: publish master debug images

---

README.md

readme: update ci badges url

---

src/flb_parser.c

parser: fix double-free

---

src/flb_output_thread.c

output_thread patch #1 : pipe creation is platform dependent, in unixes it's achieved through the pipe syscall but in windows it's a socket pair created through libevent which means instead of read/write we need to use recv/send which was already abstracted through flb_pipe_(r/w).
output_thread patch #2 : in windows the SOCKET data type is defined as an UINT_PTR which means in 64 bit operating systems it's an 8 byte number instead of 4. libevent abstracts this through the evutil_socket_t data type which in turn is abstracted using the flb_pipefd_t data type in fluent bit.
The problem comes to play when calling mk_event_channel_create whcih receives 2 int pointers to return both pipe endpoints. This means there are 2 possible bugs (one of which was happening and the other is not really a …

output_thread: fixed wrong pipe io function usage

---

src/fluent-bit.c

free() is not signal safe function. https://man7.org/linux/man-pages/man7/signal-safety.7.html
It means we can't call flb_stop/flb_destroy on signal handler.
This patch is to simplify the signal handler.
* Signal handler only changes `exit_signal` variable.
* If `exit_signal` is not 0 , it breaks sleeping loop and invokes current signal handler function from main.
* SIGSEGV and SIGCONT are handled same way.
----
**Testing**
- [] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found …

bin: Prevent free on signal handler

---

.github/workflows/pr-commit-message.yaml

Reverts fluent/fluent-bit#3465

Revert "workflow: add missing single quotation to commit message pattern"

---

plugins/in_node_exporter_metrics/ne.c
plugins/in_node_exporter_metrics/ne.h
plugins/in_node_exporter_metrics/ne_config.c
plugins/in_node_exporter_metrics/ne_cpu_linux.c
plugins/in_node_exporter_metrics/ne_cpufreq_linux.c
plugins/in_node_exporter_metrics/ne_diskstats_linux.c
plugins/in_node_exporter_metrics/ne_meminfo_linux.c
plugins/in_node_exporter_metrics/ne_utils.c
plugins/in_node_exporter_metrics/ne_utils.h

in_node_exporter_metrics: add new options 'path.procfs' and 'path.sysfs'

---

src/flb_network.c

…nd specific error string lookup
There were issues with specific error codes not being defaulted to EAI_SYSTEM without hinting at what caused them and since we use coroutines at this step I consider that using errno for it would not be the safest choice, instead, adding a conditional to the error string lookup line makes more sense.
Signed-off-by: Leonardo Almiñana <leonardo@calyptia.com>

network: remove the c-ares result code masquerading

---

.github/workflows/unit-tests.yaml

* Check that the entire unit test matrix passes correctly. This will be used to add a github branch rule check.

workflows: add extra job to validate matrix.

---

plugins/out_influxdb/influxdb.c
plugins/out_influxdb/influxdb.h

out_influxdb: migrate to configmap and append new options

---

CMakeLists.txt
src/CMakeLists.txt

build: packaging fixes (#3742)

---

src/multiline/flb_ml.c
src/multiline/flb_ml_rule.c
tests/internal/multiline.c

multiline: add breakline handling for raw texts

---

documentation/examples/multiline/regex-001/fluent-bit.conf
documentation/examples/multiline/regex-001/parsers_multiline.conf
documentation/examples/multiline/regex-001/test.log

docs: examples: multiline: new regex-001 example

---

documentation/examples/multiline/filter_multiline/fluent-bit.conf
documentation/examples/multiline/filter_multiline/parsers_multiline.conf
documentation/examples/multiline/filter_multiline/test.log

docs: examples: multiline: filter_multiline example

---

tests/internal/fuzzers/signv4_fuzzer.c

Fixes several memory leaks in signv4 fuzzer.
----
**Testing**
----

tests: internal: fuzzers: signv4: free allocated memory.

---

plugins/out_loki/loki.c

msgpack_pack_str_body will return with a new mp_sbuf->data
if mp_sbuf->data was resized
Signed-off-by: Richard Burakowski <richard.burakowski@gmail.com>
move mp_sbuf->data dereference to after msgpack_pack_str_body() call
Fixes #3796 
----
**Testing**
---- …

out_loki: delay mp_sbuf->data derefence (#3796)

---

lib/cmetrics/CMakeLists.txt
lib/cmetrics/include/cmetrics/cmt_counter.h
lib/cmetrics/include/cmetrics/cmt_gauge.h
lib/cmetrics/include/cmetrics/cmt_log.h
lib/cmetrics/include/cmetrics/cmt_untyped.h
lib/cmetrics/src/cmetrics.c
lib/cmetrics/src/cmt_counter.c
lib/cmetrics/src/cmt_encode_prometheus_remote_write.c
lib/cmetrics/src/cmt_gauge.c
lib/cmetrics/src/cmt_untyped.c
plugins/out_prometheus_remote_write/remote_write.c

out_prometheus_remote_write: support multiple context concatenation

---

plugins/out_loki/loki.c

This is a follow on from PR #3839
That issue possibly came about because the same msgpack_sbuffer is being passed twice in function calls:
both directly as mp_sbuf and indirectly as part of mp_pck,
leading to issues if the relationship isn't clear.
This change avoids passing mp_sbuf and instead just uses mp_pck.
----
**Testing**
build]$ valgrind ./bin/fluent-bit -c /wrk/etc/fluent-bit.conf 
==427174== Memcheck, a memory error detector
==427174== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==427174== Using Valgrind-3.17.0 and …

out_loki: avoid passing mp_sbuf twice

---

src/flb_network.c

network: added a time delta to the UDP timeout to keep it from
ticking after the upstream timeout handler.

network: fixed cleanup order in UDP timeout handler

---

plugins/out_splunk/splunk.c

If the user has configured an 'event_key' and the content is not found
in the incoming record, the plugin just skips the record.
This patch improves the behavior by adding a workaround to avoid skipping
the record, so if the 'event_key' is not found, it just falls back to
package the record as a normal event map.
----
**Testing**
----

out_splunk: if 'event_key' is missing, pack as a normal map

---

include/fluent-bit/flb_fstore.h
include/fluent-bit/flb_http_client.h
plugins/custom_calyptia/calyptia.c
plugins/out_calyptia/calyptia.c
plugins/out_calyptia/calyptia.h
src/flb_fstore.c
src/flb_http_client.c

custom_calyptia: add support for session store and agent patching

---

src/flb_http_client.c

http_client: remove ability to see HTTP request for non-dev env

---

lib/monkey/include/monkey/mk_core/mk_event.h
lib/monkey/include/monkey/mk_core/mk_event_epoll.h
lib/monkey/include/monkey/mk_core/mk_event_kqueue.h
lib/monkey/include/monkey/mk_core/mk_event_libevent.h
lib/monkey/include/monkey/mk_core/mk_event_select.h
lib/monkey/mk_core/mk_event.c
lib/monkey/mk_core/mk_event_epoll.c
lib/monkey/mk_core/mk_event_kqueue.c
lib/monkey/mk_core/mk_event_libevent.c
lib/monkey/mk_core/mk_event_select.c
lib/monkey/mk_server/CMakeLists.txt

lib: monkey: sync dev changes

---

src/http_server/api/v1/metrics.c

This is to fix below memory leak which I found at #4056 
I added destructor function `hs_metrics_key_destroy` to release allocated buffer.
```
==447858== 461 (16 direct, 445 indirect) bytes in 1 blocks are definitely lost in loss record 4 of 4
==447858==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==447858==    by 0x2B9D1E: flb_malloc (flb_mem.h:62)
==447858==    by 0x2B9FDA: cb_mq_metrics (metrics.c:108)
==447858==    by 0x6E4158: mk_fifo_worker_read (mk_fifo.c:431)
==447858==    by 0x6F3C07: mk_server_worker_loop (mk_server.c:569)
==447858==    by 0x6EA6D6: mk_sched_launch_worker_loop (mk_scheduler.c:418)
==447858==    by 0x4864608: start_thread (pthread_create.c:477)
==447858==    by 0x4B10292: clone (clone.S:95)
==447858== …
```

http_server: metrics: add destructor to prevent leak

---

src/http_server/api/v1/health.c

Fixes #3983.
This patch is to check if hs_health_key is NULL and allocate it before using.
This patch also adds the destructor of hs_health_key to prevent memory leak.
----
**Testing**
https://github.com/fluent/fluent-bit/issues/3983#issuecomment-912942057
There is no SIGSEGV.
```
d$  bin/fluent-bit -c ~/git/WORKTREE/v1.8.3/build/health_check.conf 
[2021/09/04 19:32:14] [ info] [engine] …
```

http_server: health: check if hs_health_key is NULL(#3983)

---

plugins/out_kinesis_firehose/firehose.c
plugins/out_kinesis_streams/kinesis.c

move info logs to debug 

---

plugins/out_kinesis_firehose/firehose.c
plugins/out_kinesis_streams/kinesis.c

out_kinesis_streams: info => debug for log send statement

---

include/fluent-bit/stream_processor/flb_sp.h
src/stream_processor/README.md
src/stream_processor/flb_sp.c
tests/internal/include/sp_cb_functions.h
tests/internal/include/sp_helpers.h
tests/internal/include/sp_invalid_queries.h
tests/internal/include/sp_select_keys.h
tests/internal/include/sp_select_subkeys.h
tests/internal/include/sp_snapshot.h
tests/internal/include/sp_window.h
tests/internal/stream_processor.c

Signed-off-by: Masoud Koleini <masoud.koleini@gmail.com>
This pull request re-structures unit test code for better readability.
**Testing**
----

sp: re-structure unit test code

---

lib/monkey/CMakeLists.txt
lib/monkey/include/monkey/mk_config.h
lib/monkey/include/monkey/mk_http_thread.h
lib/monkey/include/monkey/mk_thread_libco.h
lib/monkey/include/monkey/mk_thread_ucontext.h
lib/monkey/include/monkey/mk_tls.h
lib/monkey/mk_core/mk_utils.c
lib/monkey/mk_server/mk_fifo.c
lib/monkey/mk_server/mk_http_thread.c
lib/monkey/mk_server/mk_lib.c
lib/monkey/mk_server/mk_net.c
lib/monkey/mk_server/mk_scheduler.c
lib/monkey/mk_server/mk_vhost.c
lib/monkey/mk_server/monkey.c

lib: monkey: thread-local-storage fixes

---

plugins/filter_kubernetes/kube_meta.c
plugins/in_nginx_exporter_metrics/nginx.c
plugins/in_storage_backlog/sb.c
plugins/in_tail/tail_config.c
tests/runtime/out_elasticsearch.c

core: address compiler warnings 

---

conf/parser_custom.conf

parsers: add rabbitmq, neo4j and dns custom parsers

---

include/fluent-bit/flb_sha512.h
src/flb_sha512.c

OpenSSL provides an optimized implementation of SHA512. This patch
changes flb_sha512_*() functions to use them if available. Otherwise
they continue to use the current implementation.
----
**Testing**
```
valgrind bin/fluent-bit -c fin
==133849== Memcheck, a memory error detector
==133849== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==133849== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==133849== Command: bin/fluent-bit -c fin
==133849==
* Copyright (C) 2019-2021 The Fluent Bit …
```

sha512: use openssl implementation if available

---

plugins/filter_aws/aws.c

Current implementation try to retrieve metadata in the flush
callback, it works, but ideally we should do this in the initialization
stage and only 're-check' in the flush callback if is set or not.
This patch makes the plugin to retrieve metadata when the plugin gets
initialized.

filter_aws: retrieve metadata on initialization

---

plugins/out_calyptia/calyptia.c

out_calyptia: process and append AWS metadata

---

lib/monkey/mk_server/mk_clock.c
lib/monkey/mk_server/mk_fifo.c
lib/monkey/mk_server/mk_lib.c
lib/monkey/mk_server/mk_server.c

This PR updates monkey to the latest version (PR #357)

lib: monkey: sync dev changes 

---

src/multiline/flb_ml_parser_cri.c

multiline: cri: allow empty lines (#4284)

---

.github/workflows/README.md
.github/workflows/call-build-packages.yaml
packaging/update-repos.sh

Minor tweaks to resolve some niggles in the staging build. 
Tested locally using ubuntu18 container to confirm.
----
**Testing**
----

workflows: resolve failures in staging build

---

CMakeLists.txt

build: require cmake >= 3.0

---

lib/monkey/deps/flb_libco/CMakeLists.txt
lib/monkey/deps/flb_libco/aarch64.c
lib/monkey/mk_core/mk_rconf.c
lib/monkey/mk_server/mk_clock.c
lib/monkey/mk_server/mk_fifo.c
lib/monkey/mk_server/mk_lib.c
lib/monkey/mk_server/mk_server.c

lib: monkey: sync Apple M1 support and other fixes

---

lib/flb_libco/CMakeLists.txt
lib/flb_libco/aarch64.c

lib: flb_libco: add Apple M1 support

---

lib/monkey/mk_core/mk_rconf.c

original issue reported internally by gutaotao,

lib: monkey: sync fix for config reader

---

src/aws/flb_aws_credentials_sts.c

Fix a formatting issue in error message.
----
**Testing**
----

aws: fix error message

---

lib/monkey/include/monkey/mk_core/mk_event.h
lib/monkey/include/monkey/mk_core/mk_list.h
lib/monkey/mk_core/mk_event.c
lib/monkey/mk_core/mk_event_epoll.c
lib/monkey/mk_core/mk_event_kqueue.c
lib/monkey/mk_core/mk_event_libevent.c
lib/monkey/mk_core/mk_event_select.c

lib: monkey: sync inject enhancement and list fixes

---

lib/monkey/include/monkey/mk_core/mk_event.h
lib/monkey/include/monkey/mk_core/mk_list.h
lib/monkey/mk_core/mk_event.c
lib/monkey/mk_core/mk_event_epoll.c
lib/monkey/mk_core/mk_event_kqueue.c
lib/monkey/mk_core/mk_event_libevent.c
lib/monkey/mk_core/mk_event_select.c

1.8: backport of lib/monkey event injection and list fixes

---

plugins/out_cloudwatch_logs/cloudwatch_logs.c
plugins/out_cloudwatch_logs/cloudwatch_logs.h
plugins/out_kinesis_firehose/firehose.c
plugins/out_kinesis_firehose/firehose.h
plugins/out_kinesis_streams/kinesis.c
plugins/out_kinesis_streams/kinesis.h
plugins/out_s3/s3.c
plugins/out_s3/s3.h

aws: add external_id support for plugins

---

src/flb_upstream.c

There was a "typo" kind of error in `flb_upstream_conn_timeouts`. When backporting the feature I put the event injection call in the `av_queue` foreach loop instead of the `busy_queue` foreach loop and this PR corrects that.

upstream: moved event injection to the right place

---

include/fluent-bit/flb_file.h
src/CMakeLists.txt
src/flb_file.c
tests/internal/CMakeLists.txt
tests/internal/data/file/text_file.txt
tests/internal/file.c

Just a simple utility function for reading the whole file contents into an flb_sds_t instance. Adding in a new module which can be used for other file-related utilities in the future.

file: add new utility module

---

SECURITY.md

add announcements section
Signed-off-by: lecaros <lecaros@calyptia.com>

security: add announcements section

---

src/flb_sds.c
tests/runtime/out_elasticsearch.c

out_es: elasticsearch fixes and sds fix

---

.github/workflows/cron-scorecards-analysis.yaml
.github/workflows/cron-stale.yaml

Updates stale check action to latest version which includes improvements for ops per run.
Sets OSSF scorecard action to main to pick up changes to resolve null heads issue.
----
**Testing**
----

workflows: various updates

---

plugins/out_kinesis_firehose/firehose.c
plugins/out_kinesis_streams/kinesis.c
plugins/out_s3/s3.c

aws: add default workers

---

tests/internal/fuzzers/record_ac_fuzzer.c

tests: internal: fuzzer: fix leak in record_ac_fuzzer

---

src/multiline/flb_ml_parser.c

multiline: fix leak

---

plugins/in_random/random.c

Add configmap support for the in_random plugin. This is related to https://github.com/fluent/fluent-bit/issues/4863.
----
**Testing**
----

in_random: add support for configmap.

---

plugins/out_azure/azure.c
plugins/out_azure/azure_conf.c

out_azure: add config map support

---

lib/cmetrics/CMakeLists.txt

lib: cmetrics: upgrade DEV v0.3.0 (2e315e3)

---

.github/workflows/build-master-packages.yaml
.github/workflows/call-build-images.yaml
.github/workflows/call-build-packages.yaml
.github/workflows/staging-build.yaml

Resolves the checkout issue for latest 1.9.0-rc3 builds: https://github.com/fluent/fluent-bit/runs/5447670115?check_suite_focus=true
Part of the work required anyway to support the regular builds under #4875 
----
**Testing**
----

workflows: support ref for checkout

---

.github/workflows/README.md

workflows: add some info on release process

---

.github/workflows/call-build-packages.yaml
.github/workflows/cron-unstable-build.yaml
.github/workflows/staging-release.yaml
packaging/update-repos.sh

Resolves failing builds as the cron schedule was incorrect for checking against.
----
**Testing**
----

workflows: unstable build updates

---

packaging/update-repos.sh

packaging: fix path

---

.github/workflows/call-build-packages.yaml
.github/workflows/staging-build.yaml
packaging/server/README.md
packaging/server/publish-all.sh

Resolves failures due to differences between legacy and master builds.
Confirmed locally.
----
**Testing**
----

workflows: resolve staging build issue

---

.github/workflows/call-build-packages.yaml
.github/workflows/cron-scorecards-analysis.yaml
.github/workflows/staging-build.yaml
packaging/server/README.md
packaging/server/publish-all.sh

Fixes failing run due to incorrect filename: https://github.com/fluent/fluent-bit/actions/runs/2022362451
Can only run on master unfortunately so unable to test.
----

workflows: fix ossf filename

---

src/flb_input.c

input: remove dummy debug message

---

.github/workflows/call-build-windows.yaml
packaging/update-repos.sh

Resolve issues seen in 1.9.2 release run due to missing deb files in appropriate location and use of bash syntax on Windows runner.
----
**Testing**
----

workflows: resolve packaging release issues

---

.github/actions/sync-to-bucket/action.yaml
.github/workflows/call-build-linux-packages.yaml
.github/workflows/call-build-macos.yaml
.github/workflows/call-build-windows.yaml
.github/workflows/staging-build.yaml

Resolving issues with the S3 upload credentials and buckets for Windows/Mac builds.
Common action now to keep changes to single location in the future.
----
**Testing**
https://github.com/fluent/fluent-bit/actions/runs/2156978018
----

workflows: refactor S3 sync to common action and add checks

---

lib/cmetrics/CMakeLists.txt
lib/cmetrics/src/cmt_decode_prometheus.c

lib: cmetrics: upgrade to v0.3.1

---

plugins/in_prometheus_scrape/prom_scrape.c

in_prometheus_scrape: log call format string issue fixed

---

tests/runtime/filter_lua.c

This patch is to add test code for 'code'.
https://github.com/fluent/fluent-bit/pull/5302
----
**Testing**
```
$ bin/flb-rt-filter_lua 
Test hello_world...                             [2022/04/16 20:55:50] [ info] [fluent bit] …
```

tests: runtime: filter_lua: add test code for 'code'

---

plugins/filter_multiline/CMakeLists.txt
plugins/filter_multiline/ml.c
plugins/filter_multiline/ml.h
plugins/filter_multiline/ml_concat.c
plugins/filter_multiline/ml_concat.h
tests/runtime/filter_multiline.c

filter_multiline: Add Fluentd Log Driver Partial Message Support

---

.github/workflows/call-integration-test.yaml
.github/workflows/master-integration-test.yaml
.github/workflows/pr-integration-test.yaml
.github/workflows/staging-test.yaml

Recent PR #5368 broke the workflow call with secrets.

workflows: fix integration tests secrets vars

---

.github/workflows/master-integration-test.yaml
.github/workflows/pr-integration-test.yaml
.github/workflows/staging-test.yaml

workflows: rename parameter to terraform_api_token

---

.github/workflows/build-branch-containers.yaml
.github/workflows/call-build-images.yaml

Fixes #5407
----
**Testing**
----

workflows: add container build workflow

---

install.sh

workflows: correctly replace env vars from generated script.

---

src/flb_fstore.c

This PR addresses the `error writing tag metadata` bug in [5378](https://github.com/fluent/fluent-bit/issues/5378).
This is a simplistic approach that applies the same logic used all around in fluent bit which is "If the chunk is down, bring it up, use it and set it down again". It was implemented in this particular way to ensure that the issue is fixed with minimal chances of introducing bugs.
The real solution here would be implementing a smart chunk list at stream level that acts in FIFO mode (or an optimal approach based on "hotness") where chunks are brought up whenever needed and are automatically set down displaced by others.
The simplistic fix used everywhere is not only error prone because code is copied around and people are fallible (ie. could forget to set a chunk down when …

fstore: ensure the chunk is up while modifying it

---

.github/actions/release-server-sync/action.yaml
.github/workflows/call-build-images.yaml
.github/workflows/staging-build.yaml
.github/workflows/staging-release.yaml
packaging/server/publish-all.sh

Resolves #5365.
Resolves #5196.
Resolves #5254.
----
**Testing**
----

packaging: resolve various issues with Windows jobs and major release version

---

plugins/out_pgsql/pgsql.c

Fix typo specefied → specified
------------------------------

out_pgsql: Fix typo specefied -> specified

---

.github/workflows/pr-closed-docker.yaml

Resolves #5560 by using an action that supports removal of all containers for that sub-tree.
----

workflows: switch action to delete images

---

.github/workflows/pr-closed-docker.yaml

Fix version of action to be correct.
----

workflows: fix version

---

lib/cmetrics/.github/workflows/build.yaml
lib/cmetrics/.github/workflows/packages.yaml
lib/cmetrics/CMakeLists.txt
lib/cmetrics/cpack/macos/welcome.txt.cmakein
lib/cmetrics/src/cmetrics.c
lib/cmetrics/src/cmt_decode_msgpack.c
lib/cmetrics/src/cmt_decode_opentelemetry.c
lib/cmetrics/src/cmt_decode_prometheus.c
lib/cmetrics/src/cmt_encode_influx.c
lib/cmetrics/src/cmt_encode_msgpack.c
lib/cmetrics/src/cmt_encode_text.c
lib/cmetrics/src/cmt_variant.c
lib/cmetrics/tests/data/issue_fluent_bit_5541.txt
lib/cmetrics/tests/prometheus_parser.c

lib: cmetrics: upgrade to v0.3.4

---

.github/actions/release-server-sync/action.yaml
.github/workflows/call-build-linux-packages.yaml

Addresses https://github.com/fluent/fluent-bit/issues/5328 by providing tarballs and checksums - will require a release to push them up though.
Changes taken from #5341 .
----
**Testing**
----

workflows: add source packages to releases

---

include/fluent-bit/flb_input.h

Signed-off-by: lecaros <lecaros@calyptia.com>
fix some typos in code's documentation.
----

include: fluent-bit: flb_input: fix some typos in comments

---

.github/workflows/pr-perf-test.yaml

Resolves #5622 by running on a dedicated VM.
----
**Testing**
----

workflows: switch perf test to dedicated VMs

---

.github/workflows/pr-perf-test.yaml
examples/perf_test/docker-compose.yml
examples/perf_test/scripts/entrypoint.sh

Resolves #5627 niggles.
----
**Testing**
----

ci: perf test improvements

---

tests/runtime/in_syslog.c

This patch is fixing unavailable _FLB_HAVE_UNIX_SOCKET_ macro environments.
That macro lacking definition leads to failure for compiling test cases on macOS.
We have to remove a test case function which is `connect_tcp_unix` for compilation target.
Follows up https://github.com/fluent/fluent-bit/pull/5388.
Also, I suggested this fix is in https://github.com/fluent/fluent-bit/pull/5641#issuecomment-1166421149
None. No related issue.
----
**Testing** …

tests: runtime: in_syslog: Add missing FLB_HAVE_UNIX_SOCKET clause

---

.github/workflows/pr-perf-test.yaml

Addresses #5659 by (hopefully) adding a comment with plots of performance on it.
----
**Testing**
See https://github.com/patrick-stephens/comment-test/pull/5#issuecomment-1171341400
----

workflows: update to post comment on perf test PRs

---

plugins/in_opentelemetry/http_conn.c
plugins/in_opentelemetry/opentelemetry_config.c
plugins/in_opentelemetry/opentelemetry_prot.c

in_opentelemetry: endpoints change and new traces serialization

---

plugins/out_cloudwatch_logs/cloudwatch_api.c

Signed-off-by: Weijian Zhang <weijianz@amazon.com>
We are seeing an issue around the number of events capture by CloudWatch is not equal to the number of events which are logging by the fluent-bit. 
N/A 
----
**Testing**
----
Fluent Bit is …

out_cloudwatch_logs: skip counting empty events

---

.github/workflows/master-integration-test.yaml
.github/workflows/pr-integration-test.yaml

Resolves missing secret for remote call: https://github.com/fluent/fluent-bit/actions/runs/2760148491
----

workflows: add missing secret for int tests

---

.github/workflows/call-run-integration-test.yaml
.github/workflows/master-integration-test.yaml
.github/workflows/pr-integration-test.yaml
.github/workflows/staging-test.yaml

Resolves issue with calls to other repo checking out the wrong repo.
Fixes staging test as well.
----

workflows: update for in-repo call

---

plugins/in_tail/tail.c
plugins/in_tail/tail.h
plugins/in_tail/tail_config.h

tiger: add in_tail batch enhancement

---

plugins/in_tail/tail_file.c

in_tail: Add missed argument processed_bytes

---

plugins/filter_tensorflow/tensorflow.c

Signed-off-by: Masoud Koleini <masoud.koleini@gmail.com>
----
**Testing**
- [N/A] Backport …

filter_tensorflow: change flb_info to flb_plg_info inside function

---

include/fluent-bit/multiline/flb_ml.h
plugins/in_nginx_exporter_metrics/nginx.c
src/flb_crypto.c

core: fix two compiler warnings

---

tests/runtime/filter_lua.c
tests/runtime/filter_parser.c

Unit tests for `filter_parser` and `filter_lua` should use `flush 1.0` on service settings and `sleep(1)` idioms to wait for retrieving results.
But this idiom shouldn't work for relatively show environment such as macOS with kqueue.
To stabilize test results, we should wait with timeout operations.
This PR is not tied for any specific issues.
----
**Testing**
---- …

tests: filter_parser: filter_lua: Wait with timeout on retrieving results

---

plugins/in_syslog/syslog_conn.c

plugins: in_syslog: fixed a typo

---

CMakeLists.txt

build: fix a regression I caused previously in the uds detection snippet

---

tests/internal/aws_compress.c
tests/internal/aws_credentials.c
tests/internal/aws_credentials_http.c
tests/internal/aws_credentials_profile.c
tests/internal/aws_credentials_sts.c
tests/internal/aws_util.c

tests: internal: added initialization required to prevent crashes in macos (aws only)

---

README.md

Fixes #5879 
This patch is to add build requirements.
----
**Testing**
----

README: add requirements section

---

lib/monkey/include/monkey/mk_core/mk_utils.h
plugins/in_dummy_thread/in_dummy_thread.c
src/flb_config.c
src/flb_downstream.c
src/flb_upstream.c
tests/internal/config_format_fluentbit.c
tests/internal/flb_event_loop.c
tests/internal/flb_time.c
tests/internal/fstore.c
tests/internal/input_chunk.c
tests/internal/metrics.c
tests/internal/pack.c
tests/internal/record_accessor.c
tests/internal/signv4.c
tests/internal/stream_processor.c
tests/internal/utils.c
tests/runtime/config_map_opts.c
tests/runtime/flb_tests_runtime.h.in
tests/runtime/in_syslog.c
tests/runtime/out_file.c
tests/runtime/out_plot.c
tests/runtime_shell/in_http_tls_expect.sh
tests/runtime_shell/in_syslog_tcp_plaintext_expect.sh
tests/runtime_shell/in_syslog_tcp_tls_expect.sh
tests/runtime_shell/in_syslog_udp_plaintext_expect.sh

Reverts fluent/fluent-bit#5980

revert: "tests: macos fixes, mostly TLS initialization stuff" (#5980)

---

plugins/out_file/file.c

Without this fix, fluent-bit on macOS does not handle mkdir option in
out_file correctly:
```console
$ bin/fluent-bit -i dummy -o file -p path=output/log.txt -p mkdir=true -vv
Fluent Bit v2.0.0
[2022/09/05 23:13:42] [ info] Configuration:
[2022/09/05 23:13:42] [ info]  flush time     | 1.000000 seconds
[2022/09/05 23:13:42] [ info]  grace          | 5 seconds
[2022/09/05 23:13:42] [ info]  daemon         | 0
[2022/09/05 23:13:42] [ info] ___________
[2022/09/05 23:13:42] [ info]  inputs:
[2022/09/05 23:13:42] [ info]      dummy
[2022/09/05 23:13:42] [ info] ___________
[2022/09/05 23:13:42] [ info]  filters:
[2022/09/05 23:13:42] [ info] ___________ …
```

plugin: out_file: macos: Fix incorrect behavior for creating directories with mkdir option

---

.github/workflows/call-build-linux-packages.yaml
.github/workflows/staging-build.yaml

Addresses #6007 by allowing a release of partial build.
----
**Testing**
Sample test of 1.9.8 build: https://github.com/fluent/fluent-bit/actions/runs/2999040806
----

workflows: add override to allow partial staging build

---

cmake/headers.cmake
lib/chunkio/CMakeLists.txt
lib/chunkio/deps/crc32/crc32.c
lib/chunkio/include/chunkio/chunkio.h
lib/chunkio/include/chunkio/cio_file.h
lib/chunkio/include/chunkio/cio_file_native.h
lib/chunkio/include/chunkio/cio_file_st.h
lib/chunkio/src/CMakeLists.txt
lib/chunkio/src/cio_file.c
lib/chunkio/src/cio_file_unix.c
lib/chunkio/src/cio_file_win32.c
lib/chunkio/src/cio_memfs.c
lib/chunkio/src/cio_os.c
lib/chunkio/src/cio_utils.c
lib/chunkio/src/win32/dirent.c
lib/chunkio/tests/context.c
lib/chunkio/tests/fs.c
lib/chunkio/tests/memfs.c

1.9: upgrade Chunk I/O to v1.3.0

---

.github/workflows/update-dockerhub.yaml
dockerfiles/dockerhub-description.md

Resolves failure due to incorrect credentials: https://github.com/fluent/fluent-bit/actions/runs/3088929649/jobs/4995964489
Also minor markdown tweak to show list for contact info:
----
**Testing**
https://github.com/fluent/fluent-bit/actions/runs/3089141558/jobs/4996408600
----

workflows: fix dockerhub update workflow

---

src/config_format/flb_cf_fluentbit.c
src/flb_ra_key.c
tests/internal/config_format.c
tests/internal/config_format_fluentbit.c
tests/internal/data/config_format/classic/indent_level_error.conf
tests/internal/data/config_format/classic/issue_5880.conf

- https://github.com/fluent/fluent-bit/pull/5950
- https://github.com/fluent/fluent-bit/pull/5997
----

1.9: backport changes from GIT master

---

lib/cfl/.github/actionlint-matcher.json
lib/cfl/.github/workflows/build.yaml
lib/cfl/.github/workflows/lint.yaml
lib/cfl/.github/workflows/packages.yaml
lib/cfl/CMakeLists.txt
lib/cfl/include/cfl/cfl_sds.h
lib/cfl/src/cfl_array.c
lib/cfl/src/cfl_sds.c
lib/cfl/tests/CMakeLists.txt
lib/cfl/tests/sds.c

lib: cfl: upgrade to v0.1.7

---

lib/ctraces/CMakeLists.txt
lib/ctraces/include/ctraces/ctr_decode_msgpack.h
lib/ctraces/include/ctraces/ctr_mpack_utils.h
lib/ctraces/include/ctraces/ctr_mpack_utils_defs.h
lib/ctraces/include/ctraces/ctr_variant_utils.h
lib/ctraces/src/CMakeLists.txt
lib/ctraces/src/ctr_decode_msgpack.c
lib/ctraces/src/ctr_encode_msgpack.c
lib/ctraces/src/ctr_id.c
lib/ctraces/src/ctr_mpack_utils.c
lib/ctraces/tests/CMakeLists.txt
lib/ctraces/tests/decoding.c

lib: ctraces: upgrade to v0.2.3

---

lib/ctraces/CMakeLists.txt
lib/ctraces/src/ctr_decode_msgpack.c
lib/ctraces/tests/decoding.c

lib: ctraces: upgrade to v0.2.4

---

packaging/distros/debian/Dockerfile
packaging/distros/raspbian/Dockerfile
packaging/distros/ubuntu/Dockerfile

Backport of https://github.com/fluent/fluent-bit/pull/6183 to resolve #6175.
----
**Testing**
----

packaging: update raspbian container and pin cmake

---

plugins/out_tcp/tcp.c

Fixes #6208 
`compose_payload` of out_tcp allocates memory when `format` is not `msgpack`.
We doesn't free it when connection is not available and it causes issue.
v1.9.9 processes 
1. invoke compose_payload
2. check connection 
When no connection is available, we should release buffer when `format` is not `msgpack`.
This patch is to change flow.
1. check connection
2. invoke compose_payload
If `compose_payload` fails, we should release `u_conn`.
----
**Testing**
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) …

out_tcp: check connection first (#6208)

---

lib/cmetrics/CMakeLists.txt
lib/cmetrics/include/cmetrics/cmt_encode_splunk_hec.h
lib/cmetrics/src/CMakeLists.txt
lib/cmetrics/src/cmt_encode_splunk_hec.c
lib/cmetrics/tests/encoding.c

lib: cmetrics: upgrade to v0.5.3 (Splunk HEC)

---

src/flb_connection.c

connection: added cast to remove warning

---

packaging/test-release-packages.sh

- Yum update curl to avoid installing a new version.

workflows: update test release packages to update curl

---

plugins/out_opentelemetry/opentelemetry_conf.c

This code works in the same way as the original except it doesn't lose default values. Anything else is just the same.

opentelemetry: fixed uri sanitizer issue

---

lib/cmetrics/CMakeLists.txt
lib/cmetrics/include/cmetrics/cmt_decode_msgpack.h
lib/cmetrics/src/cmt_counter.c
lib/cmetrics/src/cmt_decode_msgpack.c
lib/cmetrics/src/cmt_encode_msgpack.c

lib: cmetrics: upgrade to v0.5.5

---

lib/monkey/.gitignore
lib/monkey/CMakeLists.txt
lib/monkey/include/monkey/mk_config.h
lib/monkey/include/monkey/mk_core.h
lib/monkey/include/monkey/mk_core/mk_list.h
lib/monkey/mk_core/CMakeLists.txt
lib/monkey/mk_core/mk_event_kqueue.c
lib/monkey/mk_core/mk_event_libevent.c
lib/monkey/mk_server/mk_lib.c
lib/monkey/mk_server/mk_server.c
lib/monkey/mk_server/monkey.c

lib: monkey: upgrade to 24e68bbf

---

lib/cmetrics/CMakeLists.txt
lib/cmetrics/include/cmetrics/cmt_decode_msgpack.h
lib/cmetrics/include/cmetrics/cmt_metric.h
lib/cmetrics/src/cmt_decode_msgpack.c
lib/cmetrics/src/cmt_decode_opentelemetry.c
lib/cmetrics/src/cmt_decode_prometheus.c
lib/cmetrics/src/cmt_summary.c
lib/cmetrics/tests/data/pr_168.txt
lib/cmetrics/tests/prometheus_parser.c

lib: cmetrics: upgrade to v0.5.6

---

lib/cmetrics/.github/workflows/build.yaml
lib/cmetrics/.github/workflows/packages.yaml
lib/cmetrics/CMakeLists.txt
lib/cmetrics/src/cmt_decode_prometheus.c
lib/cmetrics/tests/data/histogram_different_label_count.txt
lib/cmetrics/tests/prometheus_parser.c
lib/monkey/mk_server/mk_server.c

libs: upgrade cmetrics and monkey

---

src/flb_engine.c

engine: failed/expired retries is an error level event

---

plugins/filter_ecs/ecs.c
plugins/filter_ecs/ecs.h

filter_ecs: enhancements

---

cmake/windows-setup.cmake

windows: enable ECS filter

---

.github/workflows/staging-release.yaml

Resolves the failures seen here: https://github.com/fluent/fluent-bit/actions/runs/3441944702/jobs/5746887899
cc @stevehipwell
----
**Testing**
----

workflows: fix typo in windows container releases

---

src/multiline/flb_ml.c

This is a backport of #6371 to fluent-bit 1.9.
----
**Testing**
----

multiline: do not permanently set ml group time to the first log time (backported from 2.0).

---

src/aws/flb_aws_util.c

aws: different user agent on windows vs linux

---

plugins/out_es/es_bulk.c

Fixes #5680.
----
**Testing**
Note: All testing was on Windows Server 2016. See https://github.com/fluent/fluent-bit/issues/5680#issuecomment-1194723285 for logs leading up to the crash _before_ these changes.
----

out_es: fix es bulk buffer overrun

---

src/flb_io.c

There was a bug in net_io_write_async and net_io_read_async where they changed the connection registration in the event loop in order to get awakened to complete the desired operation but didn't restore the original registration status.
This problem was exposed when the downstream provider accidentally made input plugins work in async io mode. For most simple plugins where a chunk of data is received, a response is sent and the connection is closed this did not cause any issues but when using the forward input plugin with ACK delivery enabled this caused the input plugin to stop receiving messages from the client.

io: restore connection registration after async io operation

---

src/flb_parser.c

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52414
----
**Testing**
- [N/A ] …

parser: fix overflow

---

tests/internal/pack.c

This patch is to add test case for `FLB_PACK_JSON_DATE*`
----
**Testing**
```
$ valgrind --leak-check=full bin/flb-it-pack 
(snip)
Test json_date_iso8601...                       [ OK ]
==78744== Warning: invalid file descriptor -1 in syscall close()
==78744== 
==78744== HEAP SUMMARY:
==78744==     in use at exit: 256 bytes in 1 …
```

tests: internal: pack: add test case for FLB_PACK_JSON_DATE*

---

.github/workflows/call-build-images.yaml

Typo in signing workflow for release.
----
**Testing**
----

workflows: fix missing slash in signing

---

include/fluent-bit/flb_config.h
include/fluent-bit/flb_input_chunk.h
lib/chunkio/CMakeLists.txt
lib/chunkio/include/chunkio/chunkio.h
lib/chunkio/include/chunkio/cio_chunk.h
lib/chunkio/include/chunkio/cio_error.h
lib/chunkio/include/chunkio/cio_file.h
lib/chunkio/include/chunkio/cio_file_native.h
lib/chunkio/src/cio_chunk.c
lib/chunkio/src/cio_error.c
lib/chunkio/src/cio_file.c
lib/chunkio/src/cio_file_unix.c
lib/chunkio/src/cio_file_win32.c
lib/chunkio/src/cio_scan.c
plugins/in_storage_backlog/sb.c
src/flb_config.c
src/flb_input_chunk.c
src/flb_storage.c

lib: chunkio: upgrade to v1.4.0

---

plugins/in_tail/tail.c
plugins/in_tail/tail_config.h
plugins/in_tail/tail_fs_inotify.c

Porting this PR to master: https://github.com/fluent/fluent-bit/pull/6225.
----
**Testing**
----

tail: add a progress check interval to catch files that fall behind.

---

plugins/out_stackdriver/stackdriver.c

Reverts fluent/fluent-bit#6453

out_stackdriver: Revert "stackdriver: cache token expiration and use it when using cached tokens"

---

plugins/in_node_exporter_metrics/CMakeLists.txt
plugins/in_node_exporter_metrics/ne.c
plugins/in_node_exporter_metrics/ne.h
plugins/in_node_exporter_metrics/ne_filesystem.c
plugins/in_node_exporter_metrics/ne_filesystem.h
plugins/in_node_exporter_metrics/ne_filesystem_linux.c

in_node_exporter_metrics: initial commit of the filesystem collector

---

src/aws/flb_aws_util.c

aws_util: refreshing creds is an info level event

---

lib/monkey/mk_server/mk_fifo.c

lib: monkey: upgrade to 6f9be603

---

lib/ctraces/CMakeLists.txt
lib/ctraces/include/ctraces/ctr_id.h
lib/ctraces/src/ctr_decode_msgpack.c
lib/ctraces/src/ctr_encode_msgpack.c
lib/ctraces/src/ctr_id.c

lib: ctraces: upgrade to v0.3.0

---

plugins/out_opensearch/opensearch.c

In this patch, we add support for traces. A trace is converted directly to it representation in JSON format.
note that this PR cannot be merged until #6810 is fixed.
----

out_opensearch: add support for traces

---

CODEOWNERS

CODEOWNERS: made pettitwesley owner of all AWS code

---

conf/rate_limit.conf
scripts/rate_limit.lua

scripts: example lua script to do Rate limiting

---

plugins/in_tail/tail_fs_inotify.c

This is a backport of PR #6798

in_tail: fixed argument order that caused a segfault in issue 6797

---

plugins/out_stackdriver/stackdriver.c

This change makes it so we don't attempt any request to Cloud Logging if we know that an expired token is being used.
Signed-off-by: Ridwan Sharif <ridwanmsharif@google.com>

out_stackdriver: cache token expiration and use it when using cached tokens

---

plugins/out_opentelemetry/opentelemetry.c

msgpack_object_to_otlp_any_value missed a conditional to handle nil objects and result was not properly initialized.

out_opentelemetry: fixed bugs that caused issue 6899

---

plugins/out_loki/loki.c

Note : This is a direct backport of PR 6902 by @nokute78
safe_sds_cat can update flb_sds_t pointer.
Following function can't return updated pointer since arg is not a pointer.
func (flb_sds_t ptr){
safe_sds_cat(&ptr, "a", 1);
}
This patch is to use flb_sds_t pointer as an arg.

out_loki: use flb_sds_pointer to propagate updated pointer.

---

plugins/in_systemd/systemd_config.c

#6951 
This patch is to check return value of `sd_journal_add_match` ,`sd_journal_add_disjunction` and `sd_journal_add_conjunction`
----
**Testing**
```
[INPUT]
Name systemd
Systemd_Filter …
```

in_systemd: check return value of sd_journal_add_*(#6951)

---

packaging/update-repos.sh

Resolves https://github.com/fluent/fluent-bit/issues/6789#issuecomment-1455771386 due to missing variable.
----
**Testing**
----

packaging: add missing variable

---

plugins/in_prometheus_scrape/prom_scrape.c
plugins/in_prometheus_scrape/prom_scrape.h

Introduce `buffer_max_size` parameter to `prometheus_scrape` input plugin
Addresses: #7032
----
**Testing**
[fluent-bit.conf.txt](https://github.com/fluent/fluent-bit/files/11017973/fluent-bit.conf.txt)
[log-with-set-buffer_max_size.log](https://github.com/fluent/fluent-bit/files/11018113/log-with-set-buffer_max_size.log)
[log-without-set-buffer_max_size.log](https://github.com/fluent/fluent-bit/files/11018114/log-without-set-buffer_max_size.log)
---- …

in_prom_scrape: add buffer_size parameter

---

plugins/in_event_type/event_type.c

in_event_type: add support for interval_sec and interval_nsec options

---

lib/cmetrics/CMakeLists.txt
lib/cmetrics/src/cmt_cat.c
lib/cmetrics/tests/cat.c

lib: cmetrics: upgrade to v0.5.9

---

include/fluent-bit/flb_aws_util.h
plugins/out_cloudwatch_logs/cloudwatch_logs.c
src/aws/flb_aws_util.c

Fixes: https://github.com/aws/aws-for-fluent-bit/issues/503
----
**Testing**
----

aws: util: fix extra_user_agent type

---

lib/cmetrics/CMakeLists.txt
lib/cmetrics/src/cmt_decode_msgpack.c
lib/cmetrics/src/cmt_encode_msgpack.c

lib: cmetrics: upgrade to v0.6.0

---

.github/workflows/staging-release.yaml
packaging/test-release-packages.sh
packaging/update-apt-repo.sh

Resolves #7124 
- Incorrect file path to sync
- Invalid secret
- Incorrect Ubuntu version (numeric rather than codename)
Still an issue with the docs PR but will resolve separately.
----
**Testing**
https://github.com/fluent/fluent-bit/actions/runs/4619227098
----

workflows: fix automation for release

---

src/flb_input_chunk.c

cio_chunk_lock ensures that the chunk is mapped and then calls cio_chunk_sync which in turn calls cio_file_sync which trims the file to the required size, updates the checksum and syncs it.
The trimming process requires us to remap the file in some platforms such as macos and windows which means the address we previously got from cio_chunk_get_content is no longer valid.

input_chunk: changed order of operations when flushing a chunk

---

include/fluent-bit/flb_input_chunk.h
plugins/in_event_type/event_type.c
src/flb_input.c
src/flb_input_chunk.c

input: add function to release ring buffer content and other fixes

---

lib/monkey/include/monkey/mk_cache_tls.h
lib/monkey/include/monkey/mk_scheduler_tls.h
lib/monkey/include/monkey/mk_server_tls.h
lib/monkey/include/monkey/mk_tls.h
lib/monkey/include/monkey/mk_vhost_tls.h
lib/monkey/mk_core/mk_event_libevent.c

lib: monkey: upgrade to 798fde05

---

plugins/out_cloudwatch_logs/cloudwatch_logs.c

CloudWatch Logs new options to support CWL api mocking.
While Mock API can support TLS, the Mock does not have valid CA Certs, and so TLS verify will fail.
Give an option to:
1. Opt out of TLS entirely (may use this only in rare cases)
2. Opt out of TLS verification (will use this commonly)

out_cloudwatch_logs: support tls verify and port options

---

CODEOWNERS

CODEOWNERS: add PettitWesley as code owner for AWS filter tests

---

CMakeLists.txt
include/fluent-bit/flb_config.h
include/fluent-bit/flb_output.h
include/fluent-bit/flb_plugin.h
include/fluent-bit/flb_plugins.h.in
include/fluent-bit/flb_processor.h
include/fluent-bit/flb_processor_plugin.h
plugins/CMakeLists.txt
plugins/in_event_type/event_type.c
plugins/processor_labels/CMakeLists.txt
plugins/processor_labels/labels.c
src/flb_config.c
src/flb_input.c
src/flb_input_metric.c
src/flb_input_trace.c
src/flb_output.c
src/flb_plugin.c
src/flb_processor.c
src/fluent-bit.c
tests/internal/processor.c

This PR adds the native processor plugin type including all the machinery to manage its life cycle and a metrics label manipulation processor.

processor: added processor plugin support

---

DEVELOPER_GUIDE.md

developer guide: add -DFLB_VALGRIND=on to valgrind section

---

packaging/appveyor-download.sh

Resolves #7274.
----
**Testing**
Verified functions locally vs the original.
```shell
$ mkdir -p /tmp/staging
$ cd /tmp/staging
$ export TAG=v2.1.2
$ ~/github/fluent/fluent-bit/packaging/appveyor-download.sh v2.1.2
+ TAG=v2.1.2
+ URL=https://ci.appveyor.com/api
+ PROJECT_SLUG=fluent/fluent-bit-2e87g
+ OUTPUT_DIR=/tmp/staging
++ curl -sSfL --header 'Content-type: application/json' 'https://ci.appveyor.com/api/projects/fluent/fluent-bit-2e87g/history?recordsNumber=100'
++ jq -cr 'first(.builds[]|select(.isTag)|select(.tag == "v2.1.2")).version'
+ APPVEYOR_BUILD_VERSION=v1-winbuild-12299
++ curl -sSfL --header 'Content-type: application/json' https://ci.appveyor.com/api/projects/fluent/fluent-bit-2e87g/build/v1-winbuild-12 …
```

packaging: handle multiple AppVeyor builds for downloading

---

.github/workflows/staging-release.yaml

Simplify automation by using dedicated docs script from https://github.com/fluent/fluent-bit-docs/blob/master/update-release-version-docs.sh
----
**Testing**
Verified script runs correctly with appropriate inputs.
----

workflows: doc generation updates

---

plugins/out_opentelemetry/opentelemetry.c

the current implementation in `process_traces` for out_opentelemetry only processes the first trace from a chunk. This PR makes sure that we process all the traces from the chunk
----
**Testing**
```
[SERVICE]
flush 1
grace 1
log_level info
[INPUT]
listen 0.0.0.0
port 3000
[OUTPUT]
Name                     opentelemetry
Match                    *
Host                     collector
Port                     3030
Log_response_payload     false
compress gzip
tls                      off
tls.verify               off
Traces_uri               /v1/traces
add_label                app fluent-bit
add_label                color blue …
```

out_opentelemetry: flush multiple traces from one chunk

---

plugins/filter_lua/lua.c

This patch is to fix following warnings.
```
[ 36%] Building C object plugins/filter_lua/CMakeFiles/flb-plugin-filter_lua.dir/lua.c.o
/home/taka/git/fluent-bit/plugins/filter_lua/lua.c: In function ‘pack_result’:
/home/taka/git/fluent-bit/plugins/filter_lua/lua.c:384:26: warning: unused variable ‘log_event’ [-Wunused-variable]
384 |     struct flb_log_event log_event;
|                          ^~~~~~~~~
/home/taka/git/fluent-bit/plugins/filter_lua/lua.c:383:34: warning: unused variable ‘log_decoder’ [-Wunused-variable]
383 |     struct flb_log_event_decoder log_decoder;
|                                  ^~~~~~~~~~~
/home/taka/git/fluent-bit/plugins/filter_lua/lua.c:382:9: warning: unused variable ‘map_detected’ [-Wunused-variable]
382 |     int map_detected;
|         ^~~~~~~~~~~~ …
```

filter_lua: remove unused variables

---

.github/workflows/staging-release.yaml

Addresses #7432 - simply typo.
----
**Testing**
----

workflows: fix typo in increment version

---

lib/monkey/include/monkey/mk_api.h
lib/monkey/include/monkey/mk_clock.h
lib/monkey/include/monkey/mk_config.h
lib/monkey/include/monkey/mk_plugin.h
lib/monkey/include/monkey/mk_plugin_net.h
lib/monkey/include/monkey/mk_scheduler.h
lib/monkey/include/monkey/mk_static_plugins.h.in
lib/monkey/mk_core/mk_event_epoll.c
lib/monkey/mk_core/mk_event_kqueue.c
lib/monkey/mk_core/mk_event_libevent.c
lib/monkey/mk_core/mk_event_select.c
lib/monkey/mk_core/mk_string.c
lib/monkey/mk_server/mk_clock.c
lib/monkey/mk_server/mk_fifo.c
lib/monkey/mk_server/mk_header.c
lib/monkey/mk_server/mk_http.c
lib/monkey/mk_server/mk_net.c
lib/monkey/mk_server/mk_plugin.c
lib/monkey/mk_server/mk_scheduler.c
lib/monkey/mk_server/mk_server.c
lib/monkey/mk_server/monkey.c
lib/monkey/plugins/CMakeLists.txt
lib/monkey/plugins/dirlisting/dirlisting.c
lib/monkey/plugins/liana/liana.c
lib/monkey/plugins/logger/logger.c
lib/monkey/plugins/mandril/mandril.c

lib: monkey: upgrade to 13a4ccd3

---

.github/workflows/staging-release.yaml

Resolves missing secret due to change in #7474 
----
**Testing**
----

workflows: ensure we have access to bucket name

---

.github/workflows/staging-release.yaml

Release documentation generation failing due to some minor issues that are resolved.
----
**Testing**
Verified the script runs successfully with the correct output here: https://github.com/fluent/fluent-bit-docs/pull/1115
----

workflows: fix hash outputs

---

plugins/in_kubernetes_events/kubernetes_events.c

Use one of the following, in order as the time for an event:
* lastTimestamp
* firstTimestamp
* metadata.creationTimestamp
----
**Testing**
----

in_kubernetes_events: fix error when lastTimestamp is missing.

---

include/fluent-bit/flb_aws_credentials.h
include/fluent-bit/flb_aws_util.h
plugins/out_s3/s3_multipart.c
src/aws/flb_aws_credentials.c
src/aws/flb_aws_credentials_ec2.c
src/aws/flb_aws_credentials_http.c
src/aws/flb_aws_credentials_profile.c
src/aws/flb_aws_credentials_sts.c
src/aws/flb_aws_util.c
src/flb_signv4.c

aws: various core code fixes

---

lib/monkey/mk_core/mk_utils.c
lib/monkey/mk_server/monkey.c

lib: monkey: upgrade to v1.7.0

---

lib/monkey/CMakeLists.txt
lib/monkey/include/monkey/mk_config.h
lib/monkey/include/monkey/mk_mimetype.h
lib/monkey/include/monkey/mk_plugin.h
lib/monkey/include/monkey/mk_server.h
lib/monkey/include/monkey/monkey.h
lib/monkey/mk_bin/mk_signals.h
lib/monkey/mk_server/mk_server.c

lib: monkey: upgrade to v1.7.1 (fix warnings)

---

plugins/filter_log_to_metrics/log_to_metrics.c

filter_log_to_metrics: rename 'label' option to 'add_label'

---

.github/workflows/call-build-images.yaml
.github/workflows/call-build-linux-packages.yaml
.github/workflows/call-build-macos.yaml
.github/workflows/call-build-windows.yaml
.github/workflows/call-integration-image-build.yaml
.github/workflows/cron-scorecards-analysis.yaml
.github/workflows/cron-trivy.yaml
.github/workflows/pr-fuzz.yaml

Reverts fluent/fluent-bit#8286 to address #8298

Revert "workflows: bump actions/upload-artifact from 3 to 4"

---

plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c

in_elasticsearch: fix typo

---

plugins/in_http/http_prot.c

in_http: fix payload parsing and error response

---

.github/workflows/call-build-windows.yaml

Resolves https://github.com/fluent/fluent-bit/pull/8441#issuecomment-1919352111
----
**Testing**
----

workflows: windows: Use concrete option on Invoke-WebRequest

---

plugins/in_tail/tail.c
plugins/in_tail/tail_file.c
plugins/in_tail/tail_file_internal.h

This PR adds the gzip compressed file ingestion capability to in_tail.

in_tail: compressed file ingestion support

---

plugins/in_http/http_prot.c

in_http: fix url decoder by unifying normal interface with the one used in HTTP/1.x

---

src/http_server/api/v1/trace.c

http_server: api: v1: trace: fix backport for CVE-2024-4323

---

plugins/filter_log_to_metrics/log_to_metrics.c
plugins/in_http/http_prot.c
plugins/in_kafka/in_kafka.c
plugins/in_kubernetes_events/kubernetes_events.c
plugins/in_tail/tail_db.c
plugins/in_tail/tail_multiline.c
plugins/in_tail/tail_scan_glob.c
plugins/out_azure_kusto/azure_kusto_ingest.c
plugins/out_chronicle/chronicle.c
plugins/out_cloudwatch_logs/cloudwatch_api.c
plugins/out_cloudwatch_logs/cloudwatch_logs.c
plugins/out_file/file.c
plugins/out_http/http.c
plugins/out_loki/loki.c
plugins/out_stackdriver/stackdriver.c
plugins/out_websocket/websocket.c
plugins/processor_metrics_selector/selector.c
src/config_format/flb_cf_yaml.c
src/flb_engine.c
src/flb_input.c
src/flb_io.c
src/flb_lua.c
src/flb_plugin_proxy.c
src/tls/openssl.c
tests/internal/hashtable.c

This PR fixes some compiler warnings
----

core and plugins: fix compiler warnings

---

plugins/in_winevtlog/winevtlog.c

The forwarded events are attached the additional elements which are stored in Event/RenderingInfo. This information should be useful to reconstruct without EvtFormatMessage API.
----
**Testing**
----

in_winevtlog: Retrieve messages of forwarded events correctly

---

src/flb_input_chunk.c

input_chunk: do not exit if cannot release old chunks

---

plugins/in_forward/fw_conn.c

in_forward: Plug a resource leak (CID 508219)

---

plugins/out_opensearch/opensearch.c

out_opensearch: Plug a use-after-free issue (CID 508013)

---

plugins/in_event_type/event_type.c

in_event_type: Plug a resource leak on exception (CID 507968)

---

plugins/filter_kubernetes/kube_conf.h
plugins/filter_kubernetes/kube_meta.c
plugins/filter_multiline/ml.c
plugins/in_docker/cgroup_v2.c
plugins/in_forward/fw_conn.c
plugins/in_forward/fw_prot.c
plugins/in_prometheus_remote_write/prom_rw_prot.c
plugins/out_chronicle/chronicle.c
plugins/out_cloudwatch_logs/cloudwatch_api.c
plugins/out_loki/loki.c
plugins/out_opentelemetry/opentelemetry.c
plugins/out_opentelemetry/opentelemetry_conf.c
plugins/out_opentelemetry/opentelemetry_logs.c
plugins/out_s3/s3.c
plugins/processor_content_modifier/cm_logs.c
src/aws/flb_aws_compress.c
src/aws/flb_aws_util.c
src/flb_regex.c

core: fixes for reports provided by Coverity 20240826

---

lib/cmetrics/CMakeLists.txt
lib/cmetrics/include/cmetrics/cmt_math.h
lib/cmetrics/src/cmt_cat.c
lib/cmetrics/tests/cat.c
lib/cmetrics/tests/prometheus_parser.c

lib: cmetrics: upgrade to v0.9.6

---

lib/ctraces/CMakeLists.txt
lib/ctraces/src/ctr_encode_opentelemetry.c
lib/ctraces/tests/decoding.c

lib: ctraces: upgrade to v0.5.6

---

plugins/in_opentelemetry/opentelemetry_prot.c

tags are still v1_logs/v1_metrics/v1_traces even in gRPC cases
backport of #8963 
----

in_opentelemetry: add tag_from_uri support to http2 codepath

---

plugins/in_blob/blob.c
plugins/in_blob/blob.h
plugins/out_azure_blob/azure_blob.c
plugins/out_azure_blob/azure_blob.h
plugins/out_azure_blob/azure_blob_db.c
plugins/out_azure_blob/azure_blob_db.h
plugins/out_azure_blob/azure_blob_http.c

blob: assorted improvements (cleanup)

---

.github/workflows/call-build-linux-packages.yaml
.github/workflows/call-build-macos.yaml
.github/workflows/staging-release.yaml

Backport of #9751 to 3.1 branch.

workflows: ubuntu packaging and macos fixes [backport 3.1]

---

lib/monkey/.github/workflows/build-pr.yaml
lib/monkey/ARDUINO_YUN.md
lib/monkey/cmake/arduino-yun.cmake
lib/monkey/include/monkey/mk_core/mk_event_poll.h
lib/monkey/mk_core/mk_event_poll.c
lib/monkey/qa/put_test01.htt
lib/monkey/test/CMakeLists.txt
lib/monkey/test/event_timeout.c
lib/monkey/test/lib/acutest/acutest.h
lib/monkey/test/lib_server.c
lib/monkey/test/mk_tests.h

3.2: lib: monkey files

---

lib/monkey/.github/workflows/build-pr.yaml
lib/monkey/ARDUINO_YUN.md
lib/monkey/cmake/arduino-yun.cmake
lib/monkey/include/monkey/mk_core/mk_event_poll.h
lib/monkey/mk_core/mk_event_poll.c
lib/monkey/qa/put_test01.htt
lib/monkey/test/CMakeLists.txt
lib/monkey/test/event_timeout.c
lib/monkey/test/lib/acutest/acutest.h
lib/monkey/test/lib_server.c
lib/monkey/test/mk_tests.h

lib: monkey: add missing files

---

dockerfiles/Dockerfile
dockerfiles/Dockerfile.centos7
packaging/distros/amazonlinux/Dockerfile
packaging/distros/centos/Dockerfile
packaging/distros/debian/Dockerfile
packaging/distros/raspbian/Dockerfile
packaging/distros/ubuntu/Dockerfile

This is backport PR for https://github.com/fluent/fluent-bit/pull/9860.
----
**Testing**
----

package: distro: dockerfiles: Install libcurl development package for oauthoicd on rdkafka [Backport 3.2]

---

.github/workflows/call-build-images.yaml

workflows: increase size of container builders

---

include/fluent-bit/flb_conditionals.h
src/flb_conditionals.c
tests/internal/conditionals.c

Implement the GTE (Greater Than or Equal) and LTE (Less Than or Equal) operators in the conditional evaluation API to support numeric range operations.
This PR:
- Adds GTE and LTE to the supported rule operators
- Implements numeric comparison functionality with equality
- Adds unit tests for both operators
Changes to the API
Added GTE and LTE to the supported rule operators:
```
enum flb_rule_operator {
FLB_RULE_OP_EQ,
FLB_RULE_OP_NEQ,
FLB_RULE_OP_GT,
FLB_RULE_OP_LT,
FLB_RULE_OP_GTE,    /* New operator */
FLB_RULE_OP_LTE,    /* New operator */
FLB_RULE_OP_REGEX,
FLB_RULE_OP_NOT_REGEX,
FLB_RULE_OP_IN,
FLB_RULE_OP_NOT_IN
};
```
Added test cases covering:
- Basic GTE/LTE operations
- Numeric boundary conditions
- Zero and negative number handling
- Multiple rules combination
- Edge cases …

conditionals: add GTE and LTE operators 

---

plugins/in_opentelemetry/opentelemetry_prot.c
plugins/in_prometheus_remote_write/prom_rw_prot.c

Provides fixes for OpenTelemetry and Prometheus Remote Write inputs associated to:
- https://github.com/advisories/GHSA-x9j4-33qm-hgjp
- https://github.com/advisories/GHSA-4g89-mg9x-4chc
----

security update: CVE-2024-50608 and CVE-2024-50609

---

.github/workflows/staging-release.yaml

Resolves missing approval during release: https://github.com/fluent/fluent-bit/actions/runs/13674323433/job/38231503402

workflows: ensure we approve cosign

---

plugins/out_splunk/splunk.c

backport of #10119
This PR ensures that OpenTelemetry resource attributes are properly included when packaging OTLP metadata. Previously, these attributes were omitted from the final fields value.
----

out_splunk: when packing OTel metadata, include resource attributes (backport 3.2)

---

.github/workflows/staging-release.yaml

Resolves #10131 and also fixes a missed error with JSON schema uploads actually doing everything: https://github.com/fluent/fluent-bit/actions/runs/14067455504/job/39435340301

workflows: update release promotion to correctly sync

---

src/flb_env.c

By using the file:// prefix now is possible to set an environment variable value coming from the file system. This is very useful for security purposes where secrets or bearer tokens cannot be shared in a configuration file, instead through a file where access can be controlled.
Usage:
```yaml
env:
FLUSH_INTERVAL: 1
TOKEN: file://mysecret.txt
service:
flush: ${FLUSH_INTERVAL}
pipeline:
inputs:
- name: dummy dummy: '{"message": "Hello, World!", "secret": "${TOKEN}"}'
outputs:
- name: stdout match: '*'
```
content of the file:
$ cat mysecret.txt
```
abcdefg
```
Fluent Bit output:
```
$ bin/fluent-bit -c ../conf/env-secrets.yaml
Fluent Bit v4.0.0
* …
```

env: add support to set environment variable content from a file

---

run_code_analysis.sh

ci: configurable and recent (same as used by GitHub Actions) version of CMake in code analysis shell script to match minimal CMake version requirement after upgrade of libs in https://github.com/fluent/fluent-bit/pull/10195.
This pull request fixes [issue](https://github.com/fluent/fluent-bit/pull/10195/files#r2054490299) found after https://github.com/fluent/fluent-bit/pull/10195 was merged.
----
**Testing**
- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found - refer to [flb_run_code_analysis_10238.log](https://drive.google.com/file/d/1BlBz4xZTEieKfuc9Qs-ZhHyPVvIHzQPA/view?usp=sharing) for the output of …

ci: CMake upgrade in code analysis script

---

lib/ctraces/.github/workflows/build.yaml
lib/ctraces/.github/workflows/packages.yaml
lib/ctraces/CMakeLists.txt
lib/ctraces/src/ctr_decode_opentelemetry.c

lib: ctraces: upgrade to v0.6.5

---

plugins/in_node_exporter_metrics/ne_cpu_linux.c

This PR removes an unnecessary optimization that caused fluent-bit to crash in virtual machines with 64 or more vCPUs.
Note: This is a backport of PR #10347

in_node_exporter: removed unnecessary optimization that caused crash

---

plugins/in_forward/fw.c

in_forward: Check return values from mutex functions

---

plugins/in_forward/fw.c
plugins/in_forward/fw_conn.c
plugins/in_forward/fw_prot.c

in_forward: fix handling of connections and memory on exceptions

---

src/flb_hash_table.c
tests/internal/hashtable.c

hash_table: fix leak in case insensitive and add unit tests

---

src/flb_io.c

io: on network connect exceptions, invalidate file descriptor

---

src/multiline/flb_ml.c
src/multiline/flb_ml_parser.c

multiline: release unpacked contexts on exceptions

---

plugins/out_opentelemetry/opentelemetry.c

Fix handling of response HTTP status code according to the OTLP spec: https://opentelemetry.io/docs/specs/otlp/#retryable-response-codes
----

out_opentelemetry: fix handling of retry status (fix #10481)

---

examples/wasi_serde_json/README.md

Recently, wasm32-wasi target was renamed to wasm32-wasip1.
This is because it makes easy to understand the previous revision of wasi revisions.
ref: https://github.com/rust-lang/compiler-team/issues/607
----
**Testing**
----

examples: wasi_serde_json: Follow Rustc target renaming from wasm32-wasi to wasm32-wasmp1

---

.github/workflows/staging-release.yaml

workflows: fix windows check for container image

---

MAINTENANCE.md

New MAINTENANCE.md file with details of v4.x maintenance
----

maintenance: new MAINTENANCE.md file (must read)

---

src/flb_pack.c
tests/internal/pack.c

This is backporting PR of https://github.com/fluent/fluent-bit/pull/10607.
----
**Testing**
----

pack: Handle UINT64_MAX value correctly in json packing [Backport 4.0]

---

plugins/in_syslog/syslog_prot.c

The syslog input plugin previously processed and encoded records one by one, resulting in frequent writes to the ring buffer when running in threaded mode. This was particularly inefficient under high-load environments, where it could lead to ring buffer saturation and increased retry pressure.
This change introduces encoder batching by resetting the encoder before parsing each message and flushing the accumulated records after processing. The new behavior improves throughput and reduces contention on the ring buffer.
High level overview of the changes
| Metric                          | Before                       | After                        | Improvement                          |
|---------------------------------|------------------------------|------------------------------|------- …

in_syslog: do batching to reduce ring buffer pressure under load

---

plugins/filter_aws/aws.c
plugins/filter_aws/aws.h

Backporting https://github.com/fluent/fluent-bit/pull/10584.
----
**Testing**
----

filter_aws: send entity attributes for telemetry association [Backport 4.0]

---

plugins/out_kafka/kafka_config.c

Backporting from https://github.com/fluent/fluent-bit/pull/10663.
----
**Testing**
----

out_kafka: do not release config map properties [Backport to 4.0]

---

src/flb_engine.c

Backporting from https://github.com/fluent/fluent-bit/pull/10671.
----
**Testing**
----

engine: fix endless loop on reload [backport to 4.0]

---

plugins/in_kafka/in_kafka.c

in_kafka: improve offset commit timing to avoid data loss in edge cases (backport v4.0)

---

plugins/out_datadog/datadog_remap.c

backport of https://github.com/fluent/fluent-bit/pull/10537
----

out_datadog: task_arn now correctly mapped to full arn (backport v4.0)

---

dockerfiles/Dockerfile.windows

dockerfiles: windows: update to ltsc 2025 and fix layers

---

.github/workflows/staging-release.yaml

Backported from https://github.com/fluent/fluent-bit/pull/10705.
----
**Testing**
----

workflows: Retrieve the actual target image with tag [Backport to 4.0]

---

src/flb_engine.c

Backporting from https://github.com/fluent/fluent-bit/pull/10720.
----
**Testing**
----

engine: fix busy chunks on reload.  [Backpoprt to 4.0]

---

src/flb_http_client.c

backport of https://github.com/fluent/fluent-bit/pull/10810
- Add missing validation for flb_http_get_response_data() return value
- Handle all possible return values from check_connection():
- FLB_HTTP_ERROR: propagate parsing errors
- FLB_HTTP_NOT_FOUND: continue normally (valid per HTTP spec)
- FLB_HTTP_OK: process connection close logic
- Fix silent failures that could cause undefined behavior
- Maintain full backward compatibility with existing callers
----

http_client: fix incomplete error handling in flb_http_do() (backport v4.0)

---

plugins/out_opentelemetry/opentelemetry_conf.c

Backporting of https://github.com/fluent/fluent-bit/pull/10960.
----
**Testing**
----

out_opentelemetry: no longer reallocates the http2 setting string [Backport to 4.0]

---

plugins/out_file/file.c

Backporting of https://github.com/fluent/fluent-bit/pull/10969.
----
**Testing**
----

out_file: sanitize incoming Tag to prevent path traversal [Backport to 4.0]
