fluent/fluent-bit

- plugins/out_s3/s3.c
- plugins/out_s3/s3.h
- plugins/out_s3/s3_multipart.c
This patch is related to https://github.com/fluent/fluent-bit/pull/5009
In that patch(#5009), `storage_class` option requires S3 PutObject API mode (`use_put_object On`).
It means that `storage_class` option cannot be used in S3 multipart upload mode.
This patch allows `storage_class` option to be used in both multipart upload mode and PutObject mode.
In addition, `content_type` option, which could not be used in multipart upload mode, can now be used when multipart upload mode.
----
**Testing**
* …
> out_s3: add storage_class support in multipart upload mode

- .github/actions/generate-package-build-matrix/action.yaml
- .github/workflows/README.md
- .github/workflows/build-master-packages.yaml
- .github/workflows/call-build-images.yaml
- .github/workflows/call-build-linux-packages.yaml
- .github/workflows/call-build-macos.yaml
- .github/workflows/call-build-windows.yaml
- .github/workflows/cron-unstable-build.yaml
- .github/workflows/pr-windows-build.yaml
- .github/workflows/staging-build.yaml
Resolves #5241 by determining the type of build to do for 1.8 container images vs more recent.
Refactors Windows job into common one for unstable and staging to reuse.
Provides MacOS job dependent on #5247 - it will skip if not present for older branches/versions.
This also lays groundwork for multiple staging builds of different versions - previously we could only do master/1.9.
----
**Testing**
Tested with a build modified to call this branch (reusable workflows currently have to be hardcoded): https://github.com/fluent/fluent-bit/actions/runs/2101759748
This is a build of the 1.8 branch attempted in the original #5241 issue that failed previously.
Also tested a `master` build: …
> workflows: support 1.8 branch builds plus MacOS (and Windows for staging)

- plugins/out_stackdriver/stackdriver.c
> out_stackdriver: fix wrong check of connection

- dockerfiles/Dockerfile.windows
- dockerfiles/README.md
This is needed for Anthos pipeline to build the windows image.
More information here:
https://github.com/fluent/fluent-bit/discussions/5007#discussioncomment-2524868
----
**Testing**
- [ N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any …
> dockerfiles: Add a dockerfile for windows for 1.8

- plugins/in_exec/in_exec.c
In commit [in_exec: refactor to use config_map.](https://github.com/fluent/fluent-bit/commit/7196b273404131a2080db40ab8a9d30d0db45927) the in_exec plugin was refactored to use a config_map. The interval config settings were now loaded into the `flb_exec` context (`ctx->interval_sec`), but `in_exec_init` was still using the prior local variables instead of the new location of these settings.
Fixes #5221
> in_exec: fix using interval from config map

- plugins/in_storage_backlog/sb.c
Currently if a single chunk is corrupted, the whole fluent-bit process stops. Skip corrupted chunks instead.
Fixes #5265. Relevant to #4278
----
**Testing**
- [n/a ] Example configuration file for the change
- [n/a ] Debug log output from testing the change
- [ n/a] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found
- [ n/a] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build. …
> in_storage_backlog: skip corrupted chunks

- .github/workflows/call-build-macos.yaml
Currently, nightly building on macOS failed.
We need to install `bison` and `flex` dependencies on macOS in nightly build workflow.
No issue is related but this PR should fix macOS nightly building failure on our workflow.
----
**Testing** …
> workflows: Install building dependencies on macOS

- .github/workflows/cron-unstable-build.yaml
Resolves #5259 by making sure pre-releases are on a separate repo.
Needs https://github.com/calyptia/fluent-bit-infra/pull/105 to run.
----
**Testing**
----
> workflows: move unstable releases to separate repo

- .github/workflows/call-build-images.yaml
- .github/workflows/cron-unstable-build.yaml
Part of work for #4875, this now supports building 1.8 based container images (all of the architectures) via the same workflows.
Resolves #5254 by determining major tag to use for images as well.
----
**Testing**
Verified by testing on an unstable release: https://github.com/fluent/fluent-bit/actions/runs/2150327416
----
> workflows: handle 1.8 container builds and image tagging by major version

- .github/workflows/call-build-images.yaml
- .github/workflows/cron-unstable-build.yaml
Resolves failures due to two PRs conflicting in renaming things.
----
**Testing**
https://github.com/fluent/fluent-bit/actions/runs/2154209327
----
> workflows: resolve refactoring conflicts

- CMakeLists.txt
- cmake/macos-setup.cmake
Currently, macOS specific building rules are growing and growing.
We should put macOS specific building rules into `cmake/macos-setup.cmake` for simplifying cmake files.
----
**Testing**
---- …
> build: macos: Split macOS specific cmake rules into cmake/macos-setup.cmake

- plugins/out_bigquery/bigquery.c
- plugins/out_bigquery/bigquery.h
Ensure that the OAuth2 request body is URL-encoded, to match the [header value](https://github.com/fluent/fluent-bit/blob/master/include/fluent-bit/flb_oauth2.h#L29).
Also replace the old URL for retrieving OAuth2 tokens with the newer one. The new token URL is what's listed in the [well-known OAuth2 config](https://accounts.google.com/.well-known/openid-configuration).
Similar to #3198.
----
**Testing**
If this …
> out_bigquery: Ensure URL encoding for the OAuth2 request, and send to the more modern endpoint.

- include/fluent-bit/flb_luajit.h
- plugins/filter_lua/lua.c
- plugins/filter_lua/lua_config.c
- plugins/filter_lua/lua_config.h
- src/flb_luajit.c
The following PR adds a new option called `code` that allows loading the Lua code from a text from the configuration instead of an existing file.
note: 'code' and 'script' cannot be used at the same time.
config usage example:
```yaml
service:
flush:           1
daemon:          off
log_level:       info
pipeline:
inputs:
- random:
tag:           test
samples:       10
filters:
- lua:
match:         "*"
call:          append_tag
code:          |
function append_tag(tag, timestamp, record)
new_record = record
new_record["tag"] = tag
return 1, timestamp, new_record
end
outputs:
- stdout:
match:         "*"
```
----
> filter_lua: allow to load Lua code from the config

- packaging/testing/smoke/container/fluent-bit.conf
- packaging/testing/smoke/container/fluent-bit.yaml
Verifies changes in #5302 for #4634 
----
**Testing**
```
$ cd packaging/testing/smoke/container/
$ docker run --rm --pull=always -it -v $PWD/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro ghcr.io/fluent/fluent-bit/master:x86_64
$ docker run --rm --pull=always -it -v $PWD/fluent-bit.yaml:/fluent-bit/etc/fluent-bit.yaml:ro ghcr.io/fluent/fluent-bit -c /fluent-bit/etc/fluent-bit.yaml
```
https://github.com/fluent/fluent-bit-docs/pull/789
---- …
> packaging: update smoke tests to verify inline LUA

- .github/workflows/docs-generate.yaml
- README.md
Addition of basic diagram generation showing codebase structure.
* https://next.github.com/projects/repo-visualization/#integrate-into-your-own-projects
----
**Testing**
----
> ci: add codebase visualisation

- plugins/filter_nightfall/nightfall.c
A patch https://github.com/fluent/fluent-bit/pull/4671 modified filter callback api.
This patch is to modify filter callback for filter_nightfall.
Cc @PettitWesley 
----
**Testing**
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new …
> filter_nightfall: add input instance to filter callback

- tests/runtime/CMakeLists.txt
- tests/runtime/in_forward.c
This patch is to add test code for in_forward.
----
**Testing**
```
$ bin/flb-rt-in_forward 
Test forward...                                 [2022/04/16 20:41:00] [ info] [input] pausing forward.0
[ OK ]
Test forward_port... …
```
> tests: runtime: in_forward: add test for in_forward

- plugins/filter_grep/grep.c
See also: https://github.com/fluent/fluent-bit/issues/5103
This patch is to check if flb_strndup returns NULL.
----
**Testing**
```
[INPUT]
Name dummy
Dummy {"log":"\"protocol\":\"HTTP2\""}
[FILTER]
Name    grep
Match   *
Regex   log \"protocol\"\s*:\s*\"HTTP
[OUTPUT]
Name stdout …
```
> filter_grep: check if flb_strndup returns NULL

- plugins/filter_nest/nest.c
See also: https://github.com/fluent/fluent-bit/issues/5103
This patch is to check if flb_strndup returns NULL.
----
**Testing**
```
[INPUT]
Name mem
Tag  mem.local
[OUTPUT]
Name  stdout
Match *
[FILTER]
Name nest
Match *
Operation nest
Wildcard Mem.*
Nest_under Memstats …
```
> filter_nest: check if flb_strndup returns NULL

- include/fluent-bit/flb_csv.h
- src/CMakeLists.txt
- src/flb_csv.c
- src/flb_file.c
- tests/internal/CMakeLists.txt
- tests/internal/csv.c
This implements a CSV library that can be used as the basis of implementing CSV plugins/parsers on fluent-bit.
The library is designed with a simple re-entrant API where you feed bytes, and the parse function tells you if it needs more data to complete a full CSV record. 
It can optionally receive a callback that will be invoked whenever a CSV column is fully parsed (idea similar to a SAX parser). If no callback is passed, then the library can only be used for splitting CSV records (which may span across multiple lines).
A note about the tests: It may seem complex, but I've tested the same inputs multiple times, with each time having a different chunk size (from 1 to the full data). The reason for doing this is that we can't predict where CSV data will be split when reading from a file …
> csv: Implement CSV support library

- plugins/filter_nest/nest.c
Patch for PR #4936, which added config map support to filter_nest, but omitted to configure the key `Wildcard` as a multi-entry config.
----
**Testing**
https://docs.fluentbit.io/manual/pipeline/filters/nest#example-1-nest-and-lift-undo
```
[INPUT]
Name mem
Tag  mem.local
[OUTPUT]
Name  stdout
Match *
[FILTER]
Name nest …
```
> filter_nest: fix wildcard config to allow multiple entries

- plugins/filter_throttle/throttle.c
- tests/runtime/filter_throttle.c
This patch is to set default value if the config value is invalid.
https://github.com/fluent/fluent-bit/blob/v1.8.15/plugins/filter_throttle/throttle.c#L118-L122
https://github.com/fluent/fluent-bit/blob/v1.8.15/plugins/filter_throttle/throttle.c#L125-L130
If user set `window=0`, it will cause SIGSEGV on v1.9.0-v1.9.2.
----
**Testing** …
> filter_throttle: set default value if config value is invalid

- tests/runtime/CMakeLists.txt
- tests/runtime/filter_checklist.c
This PR is to add test code for filter_checklist.
----
**Testing**
```
$ bin/flb-rt-filter_checklist 
Test lookup_key...                              [ OK ]
Test lookup_keys...                             [ OK ]
Test records... …
```
> tests: runtime: filter_checklist: add test code

- plugins/out_stackdriver/stackdriver.c
- plugins/out_stackdriver/stackdriver.h
- plugins/out_stackdriver/stackdriver_conf.c
- tests/runtime/out_stackdriver.c
This change mirrors the [out_loki](https://docs.fluentbit.io/manual/pipeline/outputs/loki#using-the-label_keys-property) exporter functionality to set static `labels` during configuration. This as a list of comma separate `key=value` pairs, e.g. `label_a=value_a,label_b=value_b`. The `record_accesor` wasn't implemented since the functionality can be recreated using `label_keys`.
The expected behavior is that elements set with `labels` and `label_keys` are combined to set the LogEntry Labels in the LogExplorer. When duplicated keys appear, we would give preference to values set in `labels` over `label_keys`.
This PR is one approach to add the feature in #4912 .
This configuration implements the functionality by setting `labels` using `key=value` pairs and using a `modify` + `nest` to set a …
> out_stackdriver: add static labels defined in configuration

- plugins/out_stackdriver/stackdriver.c
- plugins/out_stackdriver/stackdriver.h
Ensure that the OAuth2 request body is URL-encoded, to match the [header value](https://github.com/fluent/fluent-bit/blob/master/include/fluent-bit/flb_oauth2.h#L29).
Also replace the old URL for retrieving OAuth2 tokens with the newer one. The new token URL is what's listed in the [well-known OAuth2 config](https://accounts.google.com/.well-known/openid-configuration).
Fixes #5284.
----
**Testing** …
> out_stackdriver: Ensure URL encoding for the OAuth2 request, and send to the more modern endpoint.

- .github/workflows/docs-generate.yaml
Resolve a loop of running every time it commits a change it made.
----
> workflows: prevent re-trigger of generation workflow on its own changes

- CODEOWNERS
Fixes #5347 as that referenced a username that no longer seems to exist.
Picked @nokute78 and @edsiper mostly because they have commits to it recently.
----
**Testing**
----
> codeowners: update in_docker owner

- src/flb_input.c
This patch is to close event channels of input instance.
(I found this when I created the patch https://github.com/fluent/fluent-bit/pull/5350) 
Note: The event channels of output instance are closed on destroy handler.
https://github.com/fluent/fluent-bit/blob/v1.9.2/src/flb_output.c#L277-L283
----
**Testing**
- [N/A] …
> input: close event channel on destroy

- plugins/in_tcp/tcp_config.c
- tests/runtime/CMakeLists.txt
- tests/runtime/in_tcp.c
- Add test code
- Fix to close fd on exit
----
**Testing**
```
$ bin/flb-rt-in_tcp 
Test tcp...                                     [ OK ]
Test format_none...                             [ OK ]
Test …
```
> tests: runtime: in_tcp: add test code

- tests/runtime/in_forward.c
We should use `flb_sockfd_t` and `flb_socket_close` for compatibility.
----
**Testing**
```
$ bin/flb-rt-in_forward 
Test forward...                                 [2022/04/24 07:33:59] [ info] [input] pausing forward.0
[ OK ]
Test …
```
> tests: runtime: in_forward: use socket wrapper

- src/flb_parser.c
Avoid calling strcmp with potential NULL. This fixes
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45648
----
**Testing**
- [ N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any …
> parser: fix null dereference

- src/flb_strptime.c
Fixes bug: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=31770
----
**Testing**
----
> strptime: typecast to avoid signed overflow

- src/flb_output.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45644
----
**Testing**
- [N/A] …
> output: fix potential NULL deref

- plugins/in_docker/docker.c
This patch is to add missing properties `include` and `exclude` to config map.
The issue was caused by https://github.com/fluent/fluent-bit/pull/4923 .
----
**Testing**
Run containers.
```
$ sudo docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED             STATUS …
```
> in_docker: add missing include/exclude property

- plugins/in_docker/docker.c
This patch is to add NULL check to prevent SIGSEGV which is reported at https://github.com/fluent/fluent-bit/issues/5149
----
**Testing**
1. Run a container.
2. `sudo fluent-bit -i docker -o stdout`
I tested renaming invalid cpu resource file name.
```diff
diff --git …
```
> in_docker: fix error handling if some resources not found

- plugins/filter_record_modifier/filter_modifier.c
This is to add error check for `flb_strndup`
See also https://github.com/fluent/fluent-bit/issues/5103
----
**Testing**
```
$ bin/flb-rt-filter_record_modifier 
Test json_long...                               [ OK ]
Test …
```
> filter_record_modifier: add error check for flb_strndup(#5103)

- plugins/in_opentelemetry/http_conn.h
This patch is to remove below warning.
```
[ 69%] Building C object plugins/in_opentelemetry/CMakeFiles/flb-plugin-in_opentelemetry.dir/opentelemetry.c.o
In file included from /home/taka/git/fluent-bit/plugins/in_opentelemetry/opentelemetry.c:25:
/home/taka/git/fluent-bit/plugins/in_opentelemetry/http_conn.h:51:57: warning: ‘struct flb_opentelemetry’ declared inside parameter list will not be visible outside of this definition or declaration
51 | struct http_conn *opentelemetry_conn_add(int fd, struct flb_opentelemetry *ctx);
|                                                         ^~~~~~~~~~~~~~~~~
/home/taka/git/fluent-bit/plugins/in_opentelemetry/http_conn.h:53:44: warning: ‘struct flb_opentelemetry’ declared inside parameter list will not be visible outside of this definition or …
```
> in_opentelemetry: add missing header

- .github/workflows/call-integration-test.yaml
- .github/workflows/master-integration-test.yaml
- .github/workflows/pr-integration-test.yaml
- .github/workflows/staging-test.yaml
Adds the required terraform apply/output steps to the integration test run, required
for bootstrapping resources managed by terraform on the integration testing suite.
Related to https://github.com/fluent/fluent-bit-ci/issues/39
> Add terraform to integration tests CI.

- .github/workflows/master-integration-test.yaml
- .github/workflows/pr-integration-test.yaml
- .github/workflows/staging-test.yaml
Fix typo secret variable passed to the workflow from _access_key to secret_key.
----
> workflows: fix integration tests secrets vars

- plugins/filter_multiline/ml.c
- plugins/filter_multiline/ml.h
- plugins/in_emitter/emitter.c
https://github.com/fluent/fluent-bit/issues/4918
----
**Testing**
----
> Prevent multiline filter from losing logs on shutdown

- plugins/out_azure/azure.c
because of typo ctx->time_key was not initialized , hence call of flb_sds_len(ctx->time_key) leads to segv
see gdb output here https://pastebin.com/EqwK1Q2i (specifically Line 103)
Signed-off-by: Martin Strigl <martin.strigl@catalysts.cc>
> out_azure: fix typo which generates segv

- .github/workflows/call-build-images.yaml
Fixes #5405 to provide 1.8 container image build
----
> workflows: resolve 1.8 container build issue

- .github/workflows/build-branch-containers.yaml
- .github/workflows/call-build-images.yaml
- .github/workflows/cron-unstable-build.yaml
Ensures we can build 1.8 containers from the new workflow and with unstable builds - also prevent the current release creation failure issue from triggering a workflow failure so other issues are more obvious now.
----
**Testing**
Tested via https://github.com/fluent/fluent-bit/actions/runs/2280664269 which builds 1.8 branch.
----
> workflows: resolve missing debug source

- plugins/in_systemd/systemd.c
Fixes #5426 
in_systemd ignores a property `db.sync` from v1.9.0.
----
**Testing**
```
[INPUT]
Name systemd
db.sync normal
[OUTPUT]
Name counter
Match *
```
```
Fluent Bit v1.9.4
* …
```
> in_systemd: fix 'db.sync' property (#5426)

- plugins/out_cloudwatch_logs/cloudwatch_api.c
- plugins/out_kinesis_firehose/firehose_api.c
- plugins/out_kinesis_streams/kinesis_api.c
A common complaint from users is how to determine whether Fluent Bit is efficiently batching records to the AWS APIs. This can be altered with the `Flush` setting. But users need a way to check the batch size. This adds debug logs that users can easily search for that print the batch size in # of events and # of bytes. 
AWS team will add this to our debugging guide once this commit is released. 
----
**Testing**
---- …
> aws: add debug logs to check batch sizes

- tests/runtime/filter_lua.c
- tests/runtime/filter_rewrite_tag.c
This patch is to suppress below warnings.
#5171 
filter_lua:
```
[ 87%] Building C object tests/runtime/CMakeFiles/flb-rt-filter_lua.dir/filter_lua.c.o
/home/taka/git/fluent-bit/tests/runtime/filter_lua.c: In function ‘flb_test_drop_all_records’:
/home/taka/git/fluent-bit/tests/runtime/filter_lua.c:608:5: warning: implicit declaration of function ‘flb_time_msleep’ [-Wimplicit-function-declaration]
608 |     flb_time_msleep(1500); /* waiting flush */
```
filter_rewrite_tag:
```
[ 97%] Building C object tests/runtime/CMakeFiles/flb-rt-filter_rewrite_tag.dir/filter_rewrite_tag.c.o
/home/taka/git/WORKTREE/test_in_syslog/tests/runtime/filter_rewrite_tag.c:42:12: warning: ‘cb_check_result’ defined but not used [-Wunused-function]
42 | static int cb_check_result(void *record, size_t size, void …
```
> tests: runtime: remove warnings

- plugins/in_systemd/systemd_db.c
This can potentially cause an issue where a new row is
inserted into in_systemd_cursor table and in_systemd_cursor
table can now have more than one row. Once multiple rows
exist in the table, this then causes a memory leak as
strdup will be called for each row to set qs.cursor in
cb_cursor_check, however qs.cursor will only be freed once.
----
**Testing** …
> in_systemd: Don't insert rows if flb_sqldb_query fails

- src/flb_pack.c
- tests/internal/pack.c
- tests/runtime/in_tcp.c
Fixes #5336 
Root cause: https://github.com/fluent/fluent-bit/issues/5336#issuecomment-1115513183
`jsmn_parse` updates `jsmn_parser` members even if a JSON is incomplete. (state->parser is updated)
In this case, a member `toknext` points next incomplete object token.
This patch is to use `toknext` as an index of last member of complete JSON.
This patch also changes a loop to descending.
----
**Testing** …
> pack: modify to determine how many JSON messages are OK(#5336)

- include/fluent-bit/flb_ra_key.h
- include/fluent-bit/flb_record_accessor.h
- src/flb_ra_key.c
- src/flb_record_accessor.c
- tests/internal/record_accessor.c
I added an API to append key/value of map using record accessor and the API is only used by test code.
It is useful for filter plugin.
I'll update `filter_modify` to support record accessor when the patch will be merged.
- Fix update APIs which is added by #3835 .  https://github.com/fluent/fluent-bit/commit/6bf9b74aad21b81229a4bafab8f9211c098a604b https://github.com/fluent/fluent-bit/commit/dfa7163f603e882f0795cd5afb4391d04a4af0d4
- Add new append API. https://github.com/fluent/fluent-bit/commit/2b2cbe1a64f55758641b77def9e943b92de60ba5
- Add test codes.
See also : https://github.com/fluent/fluent-bit/pull/3835
```c
int flb_ra_append_kv_pair(struct flb_record_accessor *ra, msgpack_object map,
void **out_map, size_t *out_size, msgpack_object *in_val);
``` …
> record_accessor: add append API, flb_ra_append_kv_pair

- include/fluent-bit/flb_http_client.h
- src/flb_http_client.c
- tests/internal/http_client.c
This PR is to
* Add `flb_http_get_header` to get the value of request header
* Add test cases for http request header 
----
**Testing**
```
$ bin/flb-it-http_client 
Test http_buffer_increase...                    [2022/03/12 …
```
> http_client: add 'flb_http_get_header' to get the value of request header

- .github/workflows/docs-generate.yaml
- CODEOWNERS
- install.sh
- packaging/test-release-packages.sh
- packaging/testing/smoke/packages/Dockerfile.amazonlinux2
- packaging/testing/smoke/packages/Dockerfile.centos7
- packaging/testing/smoke/packages/Dockerfile.centos8
- packaging/testing/smoke/packages/Dockerfile.debian10
- packaging/testing/smoke/packages/Dockerfile.debian11
- packaging/testing/smoke/packages/Dockerfile.ubuntu1804
- packaging/testing/smoke/packages/Dockerfile.ubuntu2004
- packaging/testing/smoke/packages/run-package-tests.sh
Part of work for #5098 and other testing to allow us to easily parameterise all the scripts we currently have to verify things easily.
----
**Testing**
Confirmed with local tests of `packaging/test-release-packages.sh`.
Run `packaging/testing/smoke/packages/local-test-all.sh` successfully as well.
----
> packaging: add options to parameterise server/key for testing

- plugins/out_stackdriver/stackdriver.c
- plugins/out_stackdriver/stackdriver_conf.c
Initialize the metadata_server value to NULL so that environment values are checked and fetched properly. If this default is set, environment variables are never checked and hence always falls holds default value. This is a regression introduced in v1.9
> out_stackdriver: Initialize the metadata_server value to NULL

- .github/workflows/staging-release.yaml
Resolves #5366.
----
**Testing**
----
> workflows: add post-release test job

- plugins/in_opentelemetry/opentelemetry.c
Opentelemetry metrics were not being properly routed because the input plugin lacked the `event_type` member in its `flb_input_plugin` structure.
> in_opentelemetry: Fixed the event type so OTel metrics 

- plugins/out_stackdriver/stackdriver.c
- plugins/out_stackdriver/stackdriver_conf.c
- tests/runtime/out_stackdriver.c
If no environmental variables are not set, out_stackdriver allocates `ctx->metadata_server` and sets default value.
However it is not freed since `ctx->env` is NULL.
----
**Testing**
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all …
> out_stackdriver: free metadata_server when 'METADATA_SERVER' is not set

- src/flb_time.c
- tests/internal/flb_time.c
- Add strict event time type checking
- Add some test cases to test type converting
Currently, time API only check if Ext type or not.
It caused an issue https://github.com/fluent/fluent-bit/issues/5215 indirectly.
This patch is to check the ext type and ext data size.
https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v0#eventtime-ext-format
https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1#eventtime-ext-format
According above links, the type of event time should be 0 and its size is 8.
----
**Testing**
If this is a change to packaging …
> time: add strict event time type checking

- install.sh
- packaging/test-release-packages.sh
Resolves #5484 for Yum-based repositories.
The issue is that on a single line we need to both substitute variables and not substitute special variables:
```
baseurl = $RELEASE_URL/amazonlinux/\$releasever/\$basearch/
```
This was complicated by the use of a HEREDOC script wrapping a HEREDOC `cat` call so in the end the easiest approach is to `sed` it afterwards:
```
baseurl = $RELEASE_URL/amazonlinux/VERSION_ARCH_SUBSTR
...
sed -i 's|VERSION_ARCH_SUBSTR|\$releasever/\$basearch/|g' /etc/yum.repos.d/fluent-bit.repo
```
----
**Testing**
The following all pass now whereas before only the Apt-based installs worked:
```
$ docker run --rm -it centos:7 sh -c "yum install -y …
```
> workflows: ensure we substitute variables

- plugins/filter_kubernetes/kube_conf.h
- plugins/filter_kubernetes/kube_meta.c
- plugins/filter_kubernetes/kubernetes.c
The option sets the re-read frequency of the token for the
"read serviceaccount file" method and for option Kube_Token_Command. Default is 600 seconds.
Before this change, the token was reloaded only for the Kube_Token_Command with fixed default value 600s.
Signed-off-by: Michael Voelker <novecento@gmx.de>
----
**Testing**
----
> filter_kubernetes: add option kube_token_ttl (#4352)

- .github/workflows/call-build-images.yaml
- .github/workflows/call-build-windows.yaml
- .github/workflows/cron-unstable-build.yaml
Resolves #5493 with various tweaks:
* Corrects JSON schema filename now it includes the version
* Disables 1.9 branch builds for now
* Use master branch for Windows packaging scripts as not present on 1.8
----
> workflows: unstable ci updates

- include/fluent-bit/flb_lua.h
- plugins/filter_lua/lua.c
- src/flb_lua.c
- tests/runtime/filter_lua.c
Fix the mpack implementation of lua, which didn't handle record
splitting.
Fix #5496
Signed-off-by: Thiago Padilha <thiago@calyptia.com>
> filter_lua: Fix record split in mpack implementation

- plugins/out_syslog/syslog.c
- tests/runtime/CMakeLists.txt
- tests/runtime/out_syslog.c
- Add formatter callback for out_syslog plugin to test
- Add test code for out_syslog
----
**Testing**
```
$ bin/flb-rt-out_syslog 
Test format_severity_key_rfc3164...             [ OK ]
Test …
```
> tests: runtime: out_syslog: add test code

- plugins/out_http/http.c
- plugins/out_http/http.h
- plugins/out_http/http_conf.c
Add two new options to out_http that allows greater flexibility in controlling the http request body and headers.
"body_key" specifies a key in the record that contains the actual http body. This key's value must be a msgpack string or binary.
"headers_key" specifies a key in the record that contains headers the should be added to the request. This key's value must be a msgpack map.
To help in testing these new options, I've pasted here a configuration + helper files
Fluent bit configuration (http_body_headers_key.conf):
```ini
[SERVICE]
flush      0.1
grace      2
log_level  info
[INPUT]
name tail
read_from_head true
path_key file_name
exit_on_eof true
path record*.txt
[FILTER]
Name    lua
Match   *
script  add_headers.lua
call    process_record
[OUTPUT]
name http
host 127.0.0.1
port …
```
> out_http: Implement "body_key" and "headers_key" options

- src/flb_utils.c
- tests/internal/utils.c
Fixes #5530.
User can set a password that contains '@'.
If we seek '@' from head to get proxy host, we will fail to split password.
e.g. `http://example_user:example_pass_w_@_char@proxy.com:8080`
The password should be  `example_pass_w_@_char`.
However fluent-bit get 'example_pass_w_' as a password.
This patch is to fix it seeking from tail.
----
**Testing**
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) …
> utils: seek atmark from tail (#5530)

- plugins/out_http/http.c
- tests/runtime/out_http.c
* Fill output body and size to test when a format is msgpack
* Add test case for msgpack format
----
**Testing**
```
$ bin/flb-rt-out_http 
Test format_msgpack...                          [ OK ]
Test format_json... …
```
> out_http: add test for msgpack format 

- plugins/out_tcp/tcp.c
- tests/runtime/CMakeLists.txt
- tests/runtime/out_tcp.c
* Modify out_tcp to add formatter and be more testable. 
* Add format test code for out_tcp
----
**Testing**
```
$ bin/flb-rt-out_tcp 
Test format_msgpack...                          [ OK ]
Test format_json... …
```
> out_tcp: modify to be more testable add format test code

- plugins/in_opentelemetry/opentelemetry.c
- plugins/in_opentelemetry/opentelemetry_prot.c
This PR adds support for exporting raw traces using the OpenTelemetry input plugin.
Traces are exported from the application to the endpoint `/traces` on a host running the OTel input plugin, which reads the data and serialises it into a msgpack array (without trying to parse it), and forwards it to the next plugin with event type `FLB_INPUT_LOGS`.
> in_opentelemetry: add support for raw traces

- debian/conffiles
> debian: add missing fluent-bit configs to debian conffiles

- conf/parsers_kafka.conf
Adding Regex filter for kafka applications (more to come).
First parser for confluent schema registry, with and without prefix to allow `nest` filter.
----
**Testing**
Full configuration
/fluent-bit/etc/fluent-bit.conf content
```
[INPUT]
Name tcp
Listen 127.0.0.1
Port 8877
Tag firelens-healthcheck
[INPUT]
Name forward
unix_path /var/run/fluent.sock
[INPUT]
Name forward
Listen 127.0.0.1
Port 24224
[FILTER]
Match *
Record ecs_cluster dev
Record ecs_task_arn …
```
> conf: adding parser for confluent schema registry

- CODEOWNERS
Resolves issues with missing codeowner and error in comment.
Currently #4798 can be merged by any maintainer rather than requiring codeowner approval.
There is also an errant `@` in the comments which also triggers an error.
----
**Testing**
----
> codeowners: fix issue with non-existent user and error

- .github/workflows/call-build-images.yaml
- dockerfiles/Dockerfile
- update_version.sh
Addresses #5344 - containers have the variable set.
Also fixed the version update script to ensure it works for containers - although doesn't matter too much as the Github Action overwrites the label it is used for currently!
----
**Testing**
Containers:
```
$ docker buildx build -t test --target=debug -f ./dockerfiles/Dockerfile .
$ docker run --rm -it test env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=52759e978f94
TERM=xterm
FLUENT_BIT_VERSION=1.9.4
DEBIAN_FRONTEND=noninteractive
HOME=/root
```
---- …
> dockerfiles: add FLUENT_BIT_VERSION environment variable to containers

- .github/workflows/call-build-images.yaml
- .github/workflows/call-test-images.yaml
- .github/workflows/staging-release.yaml
We now have tags available in the cosign-installer, which allows us to pin the latest release via `v1`.
> workflows: pin cosign-installer to v1

- .github/workflows/unit-tests.yaml
- CMakeLists.txt
- cmake/windows-setup.cmake
- dockerfiles/Dockerfile.centos7
- src/config_format/flb_cf_fluentbit.c
Addresses #5308 by adding a slight hint in the error message and also enabling YAML support by default.
Fuzzing will fail until we handle the dependency as a static one for https://github.com/fluent/fluent-bit/blob/master/tests/internal/fuzzers/CMakeLists.txt#L49. Therefore we disable YAML support explicitly for now to ensure fuzzing still passes.
Windows needs a solution for the lib-yaml dependency so is explicitly disabled: it is already disabled just implicitly so this makes it clear.
----
**Testing** …
> config: enable YAML support by default

- .github/workflows/staging-release.yaml
- packaging/test-release-packages.sh
Partial fix for smoke test failures of #5539.
----
**Testing**
----
> workflows: fix release test job

- plugins/filter_throttle/throttle.c
- plugins/filter_throttle/throttle.h
cb_throttle_exit called free on flb_filter_throttle_ctx which
was still in use by time_ticker. The reason time_ticker was using the
shared resource is that time_ticker was on a separate thread that was
never exitable nor was there any attempt at in from the
cb_throttle_exit.
There was a done bool flag that was not thread safe to use nor was it
set by cb_throttle_exit.
cb_throttle_exit also did not wait for time_ticker to finish before it
freed shared resources.
With this commit the thread becomes cancellable while sleeping and the
cb_throttle_exit correctly waits for it to be cancelled and joined. This
is even better than the done bool flag as we do not need to wait for the
sleep to finish before our cb_throttle_exit can exit.
The code for the cancellation was heavily inspired on …
> throttle: Fixed use after free

- packaging/server/publish-all.sh
Addresses #5539 by adjusting calculation of MAJOR_VERSION for Windows.
----
**Testing**
----
> workflows: fix publish script

- .github/workflows/call-build-windows.yaml
- .github/workflows/cron-unstable-build.yaml
- .github/workflows/staging-build.yaml
Before deprecation of AppVeyor CI builds, we have to implement CI target for Windows 32bit.
Currently, GitHub Actions workers do not provide 32bit version of OpenSSL libraries on Windows workers. 
Closes https://github.com/fluent/fluent-bit/issues/5599
----
**Testing**
----
> workflows: Install 32bit version of openssl libraries via vcpkg

- .github/workflows/README.md
- .github/workflows/pr-perf-test.yaml
- .github/workflows/skipped-unit-tests.yaml
- .github/workflows/unit-tests.yaml
- examples/perf_test/.env
- examples/perf_test/docker-compose.yml
- examples/perf_test/fluent-bit.conf
- examples/perf_test/scripts/entrypoint.sh
- examples/perf_test/scripts/multi-line-log-generator.sh
Added simple compose stack as a basis for PR performance tests: a PR can update this as necessary to run tests.
Once https://github.com/fluent/fluent-bit-ci/pull/48 is merged we can use it to invoke this workflow via a label.
Eventually will transition to dedicated runners plus longer and more complex staging tests.
----
**Testing**
---- …
> workflows: add PR performance test

- plugins/out_datadog/datadog.c
- plugins/out_datadog/datadog.h
- plugins/out_datadog/datadog_conf.c
- plugins/out_datadog/datadog_conf.h
This PR simply migrates the datadog plugin to utilize the new(er) v2 logs endpoint. The PR changes the target endpoint as well as adding a couple of headers for better API compliance.  
The change should be transparent to the fluent-bit users, with no changes required to any configuration elements.
sample config to test:
```
[INPUT]
Name   kmsg
Tag    kernel 
[INPUT]
Name        tail
Path        /var/log/syslog
[OUTPUT]
Name              datadog
Match             *
Host              http-intake.logs.datadoghq.com
TLS               on
compress          gzip
apikey            <API_KEY>
dd_service        logger
dd_source         fluent-bit
dd_message_key    log
dd_tags           env:dev,owner:foo
```
[test.log](https://github.com/fluent/fluent-bit/files/8141996/test.log)
summary output:
``` …
```
> datadog: migrate to v2 API logs endpoint

- CMakeLists.txt
In https://github.com/fluent/fluent-bit/issues/5630, we found that libyaml is already installed on macOS runners but including libyaml's headers and linking libyaml are not working.
I found that homebrew-ed libyaml is not using normal include and library directories.
We have to search libyaml include and its library directories with cmake.
Note that pkg-config module name of libyaml is not `libyaml` but `yaml-0.1`.
I also confirmed that macOS executables can handle yaml configuration:
```yaml
service:
flush:       1
log_level:   info
pipeline:
inputs:
- dummy
- forward:
listen: 0.0.0.0
outputs:
- stdout:
match: "*"
```
```console
% bin/fluent-bit -c fluent.yaml
Fluent Bit v1.9.6
* Fluent …
```
> build: libyaml: Search libyaml with pkg-config and handle homebrew-ed libyaml

- .github/workflows/pr-perf-test.yaml
Resolves failure due to renamed tests workflow: https://github.com/fluent/fluent-bit/actions/runs/2569218222
----
> workflows: fix renamed perf-test call

- plugins/filter_throttle/throttle.c
- plugins/filter_throttle/throttle.h
Thread sanitizer reports data race using below configuration.
It reports main thread and timer thread access `ctx->hash->total` without exclusion.
This patch is to add mutex.
```
cmake .. -DSANITIZE_THREAD=on && make
bin/fluent-bit -c a.conf
```
a.conf:
```
[INPUT]
Name dummy
Rate 10000
[FILTER]
Name throttle
Match *
interval 1s
Rate 100
[OUTPUT]
Name null
```
```
==================
WARNING: ThreadSanitizer: data race (pid=16321)
Read of size 4 at 0x7b140000280c by thread T1:
#0 throttle_data /home/taka/git/fluent-bit/plugins/filter_throttle/throttle.c:98 (fluent-bit+0x289198)
#1 cb_throttle_filter /home/taka/git/fluent-bit/plugins/filter_throttle/throttle.c:217 (fluent-bit+0x2898ec)
#2 flb_filter_do /home/taka/git/fluent-bit/src/flb_filter.c:124 (fluent-bit+0x97ff8)
#3 …
```
> filter_throttle: add mutex to prevent race issue

- src/flb_parser.c
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45973
----
**Testing**
- [N/A] …
> parser: free allocated types

- plugins/in_storage_backlog/sb.c
changes:
- 131949192  in_storage_backlog: skip corrupted chunks
> tiger-1.8.15 20220628

- plugins/filter_multiline/ml_concat.c
This patch is to suppress below warning.
I modified to use flb_time API since `gettimeofday` is not supported on Windows.
```
[ 44%] Building C object plugins/filter_multiline/CMakeFiles/flb-plugin-filter_multiline.dir/ml_concat.c.o
/home/taka/git/fluent-bit/plugins/filter_multiline/ml_concat.c: In function ‘ml_current_timestamp’:
/home/taka/git/fluent-bit/plugins/filter_multiline/ml_concat.c:330:5: warning: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]
330 |     gettimeofday(&te, NULL);
|     ^~~~~~~~~~~~
```
----
**Testing**
If this is a change to packaging …
> filter_multiline: use flb_time API to get timestamp in millisecond

- src/flb_fstore.c
- src/flb_storage.c
This patch is to suppress below warnings.
```
[ 73%] Building C object src/CMakeFiles/fluent-bit-shared.dir/flb_storage.c.o
/home/taka/git/fluent-bit/src/flb_storage.c: In function ‘flb_storage_create’:
/home/taka/git/fluent-bit/src/flb_storage.c:510:17: warning: assignment to ‘void (*)(void *, int,  const char *, int,  const char *)’ from incompatible pointer type ‘int (*)(struct cio_ctx *, int,  const char *, int,  char *)’ [-Wincompatible-pointer-types]
510 |     opts.log_cb = log_cb;
|                 ^
```
```
[ 75%] Building C object src/CMakeFiles/fluent-bit-shared.dir/flb_fstore.c.o
/home/taka/git/fluent-bit/src/flb_fstore.c: In function ‘flb_fstore_create’:
/home/taka/git/fluent-bit/src/flb_fstore.c:465:17: warning: assignment to ‘void (*)(void *, int,  const char *, int,  const …
```
> fstore: Suppress log cb warn

- .github/workflows/pr-perf-test.yaml
Resolves issues with incorrect checks before running the perf-test: https://github.com/fluent/fluent-bit/runs/7153550752?check_suite_focus=true
Previously it was running whenever a PR was labelled as the second stage was intended to run `always` to pick up any results even in failure modes, however this is no longer required and now it should be chained to the previous check - if that is skipped (i.e. not a valid label for this workflow) then so will this stage.
----
> workflows: fix incorrect label running

- dockerfiles/README.md
Minor docs changes to ensure we use the correct context for Windows builds.
----
**Testing**
----
> dockerfiles: update Windows build

- plugins/in_exec/in_exec.c
I think there was a typo in https://github.com/fluent/fluent-bit/pull/4932/ as the `oneshot` parameter was renamed to `bool`:
```
bin/fluent-bit -f 1 -i exec -p "command=exec 2>&1; ls /var/log" -p 'oneshot=true' -o stdout
Fluent Bit v1.9.1
* Git commit: 619277847c6343dea9e4215deacd36cf61caf0a3
[2022/03/19 08:55:47] [ info] [engine] started (pid=2451199)
[2022/03/19 08:55:47] [ info] [storage] version=1.1.6, initializing...
[2022/03/19 08:55:47] [ info] [storage] in-memory
[2022/03/19 08:55:47] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/03/19 08:55:47] [ info] [cmetrics] version=0.3.0
[2022/03/19 08:55:47] …
```
> exec: fix name of oneshot parameter

- plugins/out_stdout/stdout.c
flb_time_pop_from_msgpack may return an error which should be handled.
This handles it and fixes a potential use-after-free:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45916
----
**Testing**
- [N/A] Attached [local packaging …
> out_stdout: handle error case

- src/flb_record_accessor.c
Check rp->key is set before dereferencing. This fixes:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45642
Note that `rp->key` is not ensured to be non-null by design: https://github.com/fluent/fluent-bit/blob/1e49a77bd3098c970ce445bb99f8e07557a4f2ab/src/flb_record_accessor.c#L320-L328
----
**Testing**
If this is a change to packaging of containers or …
> record_accessor: fix possible null-deref

- tests/internal/fuzzers/multiline_fuzzer.c
Fixes wrong indices used for array indexing.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45911
----
**Testing**
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new …
> tests: internal: fuzzers: fix index error

- src/flb_input.c
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45984
----
**Testing**
- [N/A] …
> input: return error code from cb_collect

- plugins/filter_expect/expect.c
- plugins/filter_expect/expect.h
- tests/runtime/CMakeLists.txt
- tests/runtime/filter_expect.c
- Support `result_key` property and `action result_key`
- Add test code for filter_expect
A property `action result_key` will append a result that rule is matched or not.
It is useful to test to check if the result value is true or false.
----
**Testing**
``` …
```
> filter_expect: support 'result_key' property and add test code

- plugins/in_netif/in_netif.c
This patch is to suppress below warning.
```
$ valgrind --leak-check=full bin/flb-rt-in_netif 
==17484== Memcheck, a memory error detector
==17484== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==17484== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==17484== Command: bin/flb-rt-in_netif
==17484== 
Test normal case...                             [ OK ]
Test no interface...                            [2022/06/25 07:36:56] [error] [input:netif:netif.0] 'interface' is not set
[2022/06/25 07:36:56] [error] Failed initialize input netif.0
[2022/06/25 07:36:56] [error] [lib] backend failed
[ OK ]
Test invalid interface...                       [2022/06/25 07:36:57] [error] [lib] backend failed
[2022/06/25 07:36:57] [error] [input:netif:netif.0] 	
: init …
```
> in_netif: add missing return type

- src/multiline/flb_ml.c
- tests/runtime/filter_multiline.c
https://github.com/fluent/fluent-bit/issues/5524
Currently, multiline doesn't update a last recently used parser `lru_parser`.
It causes second+ stream can't be parsed correctly.
This patch is to fix it and add test cases. 
----
**Testing** …
> ml: clear last recently used parser to match next parser(#5524)

- tests/runtime/in_tail.c
This patch is to add some test cases for in_tail. 
----
**Testing**
```
$ bin/flb-rt-in_tail 
Test issue_3943...                              [2022/05/15 21:22:06] [ info] [input] pausing tail.0
[ OK ]
Test skip_long_lines... …
```
> tests: runtime: in_tail: add some test cases

- plugins/filter_modify/modify.c
This is to add error check for `flb_strndup`.
See also https://github.com/fluent/fluent-bit/issues/5103
----
**Testing**
```
$ bin/flb-rt-filter_modify 
Test op_set_append...                           [2022/03/20 08:32:11] [ info] …
```
> filter_modify: add error check for flb_strndup(#5103)

- plugins/out_forward/forward.c
- plugins/out_forward/forward.h
Fixes #2181
This patch is to add 'unix_path' to forward via unix socket.
|Key|Description|Default|
|--|--|--|
|Unix_Path|Specify the path to unix socket to send a Forward message. If set, `Upstream` is ignored.||
----
**Testing**
1. `fluent-bit -c server.conf`
2. `fluent-bit -c client.conf`
server.conf:
```
[INPUT]
Name forward …
```
> out_forward: support 'unix_path'

- plugins/filter_kubernetes/kube_conf.c
- plugins/filter_kubernetes/kube_conf.h
- plugins/filter_kubernetes/kubernetes.c
Allow the user to set kubelet_host when use_kubelet is true.
Defaults to '127.0.0.1'.
Fixes #5143
Signed-off-by: Thomas Danielsson <thomas.danielsson@sharespine.com>
----
**Testing**
```
[INPUT]
Name dummy
Dummy {"top": {".dotted": "value"}}
[FILTER]
Name          kubernetes
Match         *
Use_Kubelet   true
Kubelet_Host  ${KUBELET_HOST}
Kubelet_Port  10250
[OUTPUT]
Name stdout
Match *
```
```
[2022/04/12 10:12:30] [ info] [filter:kubernetes:kubernetes.0] https=1 host=10.132.15.210 port=10250
[2022/04/12 10:12:30] [ info] [filter:kubernetes:kubernetes.0] local POD info OK
[2022/04/12 10:12:30] [ info] [filter:kubernetes:kubernetes.0] testing …
```
> filter_kubernetes: Add ability to change kubelet_host

- include/fluent-bit/flb_record_accessor.h
- plugins/out_cloudwatch_logs/cloudwatch_api.c
- plugins/out_cloudwatch_logs/cloudwatch_api.h
- plugins/out_cloudwatch_logs/cloudwatch_logs.c
- plugins/out_cloudwatch_logs/cloudwatch_logs.h
- src/flb_record_accessor.c
- tests/internal/record_accessor.c
#3246 
Doc PR: https://github.com/fluent/fluent-bit-docs/pull/834
----
**Testing**
----
> out_cloudwatch_logs: support record_accessor

- plugins/out_s3/s3.h
As part of supporting S3 Multi-part upload feature, we need to increase current limit on maximum file size to 1GB . 
----
**Testing**
- [N/A] …
> s3: update S3 PutObjectSize to 1GB

- .github/workflows/staging-release.yaml
See https://github.com/actions/virtual-environments/issues/5679#issuecomment-1165385662 for full details and links out.
The new client on the runners needs the region explicitly specifying which was done for staging builds but not releases so these fail to sync: https://github.com/fluent/fluent-bit/runs/7249669328?check_suite_focus=true
----
**Testing**
Same as staging build now which works.
----
> workflows: resolve AWS sync issue due to client upgrade on runners

- plugins/filter_expect/expect.c
This patch is to replace `free` with `flb_free`.
----
**Testing**
```
$ valgrind --leak-check=full bin/flb-rt-filter_expect 
==4595== Memcheck, a memory error detector
==4595== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward …
```
> filter_expect: use flb_free instead of free

- plugins/out_stackdriver/stackdriver.c
- plugins/out_stackdriver/stackdriver_conf.c
Prevent compiler warnings:
```
...
Scanning dependencies of target flb-plugin-out_stackdriver
[ 67%] Building C object plugins/out_stackdriver/CMakeFiles/flb-plugin-out_stackdriver.dir/stackdriver_conf.c.o
[ 67%] Building C object plugins/out_stackdriver/CMakeFiles/flb-plugin-out_stackdriver.dir/stackdriver_operation.c.o
[ 67%] Building C object plugins/out_stackdriver/CMakeFiles/flb-plugin-out_stackdriver.dir/stackdriver.c.o
[ 68%] Building C object plugins/out_stackdriver/CMakeFiles/flb-plugin-out_stackdriver.dir/gce_metadata.c.o
/tmp/fluent-bit/plugins/out_stackdriver/stackdriver_conf.c: In function 'parse_configuration_labels':
/tmp/fluent-bit/plugins/out_stackdriver/stackdriver_conf.c:215:17: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
ret = …
```
> out_stackdriver: removed unused variables

- src/flb_input_thread.c
Try to fix timeout of CI of in_dummy_thread.
#5718
----
**Testing**
----
> input_thread: pause coll_fd when read pipe is closed

- src/flb_utils.c
Fixes #4762 
----
**Testing**
----
Fluent Bit …
> utils: use fclose when fstat failed(#4762)

- lib/monkey/mk_core/mk_event_kqueue.c
- src/flb_config.c
> config: fix flush timeout destroy handling (kqueue)

- src/flb_input_thread.c
ref: https://github.com/lemmy/BlockingQueue/issues/3
On macOS, don't wait on a condition that is not initialized yet.
We must initialize it at first.
None for the accurate related issue.
----
**Testing**
- [N/A] Attached [local packaging …
> input_thread: macos: Add a missing pthread_cond_init

- .github/workflows/unit-tests.yaml
Resolves all linting issues: https://github.com/fluent/fluent-bit/runs/7433516723?check_suite_focus=true
----
> workflows: resolve linting issue with unit tests

- .github/workflows/call-build-windows.yaml
On GitHub Actions, we need to refer the equivalent OpenSSL libraries than AppVeyor ones.
In AppVeyor, it seems that it installs slproweb's OpenSSL library installers to provide OpenSSL libraries.
We need to use them on GitHub Actions' workflow to solve OpenSSL linking issue on the artifacts.
---
There is no reported error for dll linkage.
Closes #5703
----
**Testing**
- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption …
> workflows: windows: Use chocolatey's OpenSSL installer for linking OpenSSL

- plugins/out_es/es.c
- plugins/out_es/es.h
- plugins/out_es/es_conf.c
Add option to the elasticsearch ouput to allow compressing with gzip the payload when sending data.
----
**Testing**
----
> out_es: add option to compress payload

- .github/workflows/master-integration-test.yaml
- .github/workflows/pr-integration-test.yaml
Resolves issue with different default branch name: https://github.com/fluent/fluent-bit/actions/runs/2760070220
----
> workflows: fix branch for fluent-bit-ci calls

- .github/workflows/master-integration-test.yaml
- .github/workflows/pr-integration-test.yaml
Resolves workflow name to be correct.
----
> workflows: fix workflow name for fluent-bit-ci calls

- include/fluent-bit/flb_aws_util.h
- src/aws/flb_aws_util.c
Set AWS Fluent Bit user agent. The user agent can either be specified by:
1. Cloudwatch extra_user_agent option OR
2. environment variable $FLB_AWS_USER_AGENT
----
**Testing**
*Valgrind result:*
- With `extra_user_agent` set:
```
==23461== 
==23461== HEAP SUMMARY:
==23461==     in use at exit: 102,912 bytes in 3,432 blocks
==23461==   total heap usage: 65,209 allocs, 61,777 frees, 13,830,990 bytes allocated
==23461== 
==23461== LEAK SUMMARY:
==23461==    definitely lost: 0 bytes in 0 blocks
==23461==    indirectly lost: 0 bytes in 0 …
```
> aws_util: set AWS Fluent Bit user agent based on environment

- src/aws/flb_aws_util.c
> aws_util: use conccurent safe strtok_r

- plugins/in_tail/tail.c
- plugins/in_tail/tail.h
- plugins/in_tail/tail_config.h
This PR adds a batch limit to the tail function that ingests pending data from files that have been promoted to event mode.
> in_tail: added event based file ingestion batch limit

- plugins/in_tail/tail_file.c
- plugins/in_tail/tail_file_internal.h
Currently "path_key" tail option will send rotated filename after rotation, which is not the desired behavior. This PR fixes it.
> in_tail: Fix path_key when the file is rotated

- include/fluent-bit/flb_api.h
- include/fluent-bit/flb_input.h
- include/fluent-bit/flb_output.h
- include/fluent-bit/flb_plugin_proxy.h
- src/flb_api.c
- src/flb_input.c
- src/flb_input_thread.c
- src/flb_output.c
- src/flb_plugin_proxy.c
- src/proxy/go/go.c
- src/proxy/go/go.h
This PR provides Golang input plugin mechanism on Fluent Bit core.
This work is based on multi-threaded input plugin mechanism that is implemented on https://github.com/fluent/fluent-bit/pull/4586.
The related issue is None.
----
**Testing**
```ini
[SERVICE]
Flush        5
Log_Level    trace
Plugins_File plugins.conf
[INPUT]
Name gdummy
Tag  gdummy.local
[OUTPUT]
Name  stdout
Match gdummy*
```
```ini
[PLUGINS]
Path /path/to/workdir/fluent-bit/build/in_gdummy.so
```
This patch works with fluent-bit-go and corresponds a shared object that is built with Golang input plugin …
> go: proxy: plugin: Implement multi-threaded Golang input plugin mechanism

- conf/parsers.conf
Add parser for parsing istio's envoy proxy access logs.
- access log format: https://istio.io/latest/docs/tasks/observability/logs/access-log/#default-access-log-format
----
> conf: parser: add istio-envoy-proxy parser

- conf/parsers.conf
Wrong rubular link was attached, updated it according to https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#default-format-string
----
> conf: parser: fix envoy access log rubular.com link

- plugins/in_node_exporter_metrics/ne_cpu_linux.c
Older kernel versions may be missing the `guest_nice` field so instead of failing we should just ignore/zero it.
This then allows reporting of CPU metrics otherwise we get a complete failure.
```
[input:node_exporter_metrics:node_exporter_metrics.0] could not process line: cpu0 2781 461 1709 1962724 2666 22 31 427 0
```
----
**Testing**
---- …
> in_node_exporter_metrics: handle missing fields in different kernel versions

- lib/monkey/mk_core/mk_event_kqueue.c
When using NOTE_SECONDS side of EV_SET routine on macOS,
we got a severe performance degradation on threaded input plugin
environment.
Instead, we shouldn't use NOTE_SECONDS event filtering flag and
specify as milliseconds on macOS.
Closes https://github.com/fluent/fluent-bit/issues/5760
----
**Testing**
---- …
> lib: monkey: core event kqueue: don't use NOTE_SECONDS on macOS (#5756 backport to 1.9)

- .gitignore
- DEVELOPER_GUIDE.md
- Dockerfile
- Vagrantfile
- dockerfiles/Dockerfile
- plugins/in_node_exporter_metrics/ne_cpu_linux.c
Part of supporting work for #5716 by adding a Vagrantfile people can use to compile and run Fluent Bit in a VM.
----
**Testing**
```shell
$ vagrant up
$ vagrant ssh
vagrant@ubuntu-jammy:/vagrant$ cd build/
vagrant@ubuntu-jammy:/vagrant/build$ cmake -DFLB_RELEASE=On -DFLB_TRACE=Off -DFLB_JEMALLOC=On -DFLB_TLS=On -DFLB_SHARED_LIB=Off -DFLB_EXAMPLES=Off -DFLB_HTTP_SERVER=On -DFLB_IN_EXEC=Off -DFLB_IN_SYSTEMD=On -DFLB_OUT_KAFKA=On -DFLB_OUT_PGSQL=On -DFLB_NIGHTLY_BUILD="$FLB_NIGHTLY_BUILD" -DFLB_LOG_NO_CONTROL_CHARS=On ..
vagrant@ubuntu-jammy:/vagrant/build$ make
...
[100%] Linking C executable ../bin/fluent-bit
[100%] Built target fluent-bit-bin
vagrant@ubuntu-jammy:/vagrant/build$ bin/fluent-bit -i cpu -o stdout -m '*' …
```
> vagrantfile: provide test and build VM definition

- CMakeLists.txt
- lib/chunkio/CMakeLists.txt
- lib/cmetrics/CMakeLists.txt
$< is a private detail from the Makefile generated by CMakefile and
are not under control or to be used at the CMakeLists level. In 3.20
that private generation changed pre-requisite targets[1] and now logs
contain the path compiler_depend.ts instead of the actual file.
Fixes #5492 
----
**Testing**
- [ N/A ] Example configuration file for the change
- [ N/A ] Debug log output from testing the change
- [ N/A ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found …
> build: CMakeLists.txt Do not use private makefile targets

- src/flb_engine.c
&config and &config->ch_event points same address since ch_event is a first member of struct.
We can pass &config instead of &config->ch_event.
However it is a risk of bug.
- If the first member of struct will be changed, the code will be broken. However we can compile it. #5843 
- We misunderstand the function needs a config, not a ch_event.
This patch is to pass `config->ch_event` explicitly.
----
**Testing** …
> engine: pass config->ch_event explicitly

- cmake/windows-setup.cmake
- plugins/out_kinesis_firehose/firehose.c
- plugins/out_kinesis_firehose/firehose.h
- plugins/out_kinesis_firehose/firehose_api.c
- tests/runtime/CMakeLists.txt
Currently, Windows release artifacts do not include the following-
- Kinesis Firehose output plugin
- Kinesis Streams output plugin
- AWS Filter
In this change, we are making the required changes to enable support for the same.
The changes for the same include-
- Changing the struct name for Kinesis Firehose plugin so that the build can succeed (`error C2011: 'event': 'struct' type redefinition`)
- Addition of `FLB_OUT_KINESIS_STREAMS` to the Windows cmake file
- Adding of  `FLB_FILTER_AWS` to the Windows cmake file
----
**Testing** …
> windows: enabled Kinesis Firehose, Kinesis Stream, and AWS Filter

- .github/workflows/call-build-macos.yaml
- .github/workflows/unit-tests.yaml
Follows up #5874.
For macOS build, we need to pass the place of openssl via `-DOPENSSL_ROOT_DIR=...`
----
**Testing**
----
> workflows: macos: Pass OPENSSL_ROOT_DIR as a cmake argument

- src/config_format/flb_cf_fluentbit.c
- tests/internal/config_format_fluentbit.c
- tests/internal/data/config_format/classic/issue_5880.conf
Fixes #5880 
This patch is to report undefined value error.
----
**Testing**
```
[INPUT]
Name dummy
Tag dummy
[FILTER]
Name modify
Match *
ADD foo bar
ADD
[OUTPUT]
Name stdout
Match *
Format
```
Fluent-bit reports below error.
```
[2022/08/13 11:04:49] [error] [config] error in …
```
> cf_fluentbit: report undefined value error(#5880)

- src/flb_record_accessor.c
- tests/runtime/filter_rewrite_tag.c
This patch is to prevent below SIGSEGV of filter_rewrite_tag.
```
$ ../bin/fluent-bit -c bug.conf 
Fluent Bit v2.0.0
[2022/08/12 14:03:37] [ info] [fluent bit] version=2.0.0, commit=fc325524d5, pid=43215
[2022/08/12 14:03:37] [ info] [storage] version=1.2.0, type=memory-only, sync=normal, checksum=disabled, max_chunks_up=128
[2022/08/12 14:03:37] [ info] [cmetrics] version=0.3.5
[2022/08/12 14:03:37] [ info] [sp] stream processor started
[2022/08/12 14:03:37] [ info] [output:stdout:stdout.0] worker #0 started
[2022/08/12 14:03:37] [engine] caught signal (SIGSEGV)
#0  0x5611f7c539eb      in  flb_ra_regex_match() at src/flb_record_accessor.c:622
#1 …
```
> record_accessor: add NULL check(#5846)

- tests/internal/aws_util.c
Current `flb-it-aws_util` may fail on some environment since it uses `mktime` and it depends on timezone.
<details>
<summary> TZ=Australia/Sydney </summary>
```
$ TZ=Australia/Sydney bin/flb-it-aws_util 
Test parse_api_error...                         [ OK ]
Test flb_aws_endpoint...                        [ OK ]
Test flb_get_s3_key_multi_tag_exists...         [ FAILED ]
aws_util.c:97: Check strcmp(s3_key_format, S3_OBJECT_KEY_TAG_PART) == 0... failed
Test flb_get_s3_key_full_tag...                 [ FAILED ]
aws_util.c:108: Check strcmp(s3_key_format, S3_OBJECT_KEY_FULL_TAG) == 0... failed
Test flb_get_s3_key_tag_special_characters...   [ FAILED ]
aws_util.c:120: Check strcmp(s3_key_format, S3_OBJECT_KEY_SPECIAL_CHARCATERS_TAG) == 0... failed
Test flb_get_s3_key_multi_tag_delimiter... …
```
> tests: internal: aws_util: remove timezone dependency

- plugins/in_tail/tail_file.c
- plugins/in_tail/tail_file_internal.h
Signed-off-by: Thiago Padilha <thiago@calyptia.com>
----
**Testing**
----
> in_tail: fix path_key when the file is rotated (#5829 backport to 1.9)

- plugins/in_http/http_prot.c
Fixes #5810 
This patch is to allow multiple json payloads per one http post.
input :
```
curl -d $'{"1":1}{"2":2}' -H "content-type: application/json" http://127.0.0.1:8888
```
output : 
```
[0] http.0: [1659219897.698633420, {"1"=>1}]
[1] http.0: [1659219897.698633420, {"2"=>2}]
```
Note: 
in_http already supports array to ingest multiple json.
```
curl -d $'[{"1":1}, {"2":2}]' -H "content-type: application/json" http://127.0.0.1:9880
```
----
**Testing**
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) …
> in_http: allow multiple json payloads(#5810)

- include/fluent-bit/flb_aws_util.h
This patch is to fix below warnings.
Currently a type of `extra_user_agent` is a `flb_sds_t *`.
I think it should be `flb_sds_t`.
-  `flb_sds_destroy` needs a `flb_sds_t`.
- `flb_sds_create` returns `flb_sds_t`.
```c
tmp = flb_sds_create(buf);
if (!tmp) {
flb_errno();
goto error;
}
aws_client->extra_user_agent = tmp;
```
Warnings:
```
[ 28%] Building C object src/aws/CMakeFiles/flb-aws.dir/flb_aws_util.c.o
/home/taka/git/fluent-bit/src/aws/flb_aws_util.c: In function ‘flb_aws_client_destroy’:
/home/taka/git/fluent-bit/src/aws/flb_aws_util.c:234:39: warning: passing argument 1 of ‘flb_sds_destroy’ from incompatible pointer type [-Wincompatible-pointer-types]
234 |             flb_sds_destroy(aws_client->extra_user_agent);
|                             ~~~~~~~~~~^~~~~~~~~~~~~~~~~~
| …
```
> aws_util: fix type of extra_user_agent

- src/flb_plugin_proxy.c
- src/proxy/go/go.c
In some cases, fluent-bit calls fprintf to log error.
I think it should use flb_error or something.
----
**Testing**
```
[SERVICE]
Plugins_File ./plugins.conf
[INPUT]
Name dummy
[OUTPUT]
Name stdout
Match *
[OUTPUT]
Name gstdout
Match *
```
plugins.conf:
``` 
[PLUGINS]
Path …
```
> proxy: use flb_error api

- plugins/in_kmsg/in_kmsg.c
- plugins/in_kmsg/in_kmsg.h
This patch is to add `prio_level`. It is useful to filter debug kernel logs.
If user sets prio_level=4, the logs that priority is greater than 4 are ignored.
Priority=5,6,7 are ignored.
Default value is 8. It means all logs are saved.
----
**Testing**
- [] Documentation required for this feature
```
[INPUT]
Name kmsg
Prio_Level 4 …
```
> in_kmsg: support prio_level property.

- plugins/filter_parser/filter_parser.c
A type of default value `def_value` should be flb_sds_t.
It means FLB_TRUE/FLB_FALSE is invalid as a default value.
However filter_parser use FLB_FALSE as a default value. I fixed it.
```c
struct flb_config_map {
/* Public fields used by plugins at registration */
int type;                      /* type */
flb_sds_t name;                /* property name */
flb_sds_t def_value;           /* default value */
int flags;                     /* option flags (e.g: multiple entries allowed) */
int set_property;              /* set context property ? (use offset ?) */
uintptr_t offset;              /* member offset */
flb_sds_t desc;                /* description */
struct flb_config_map_val value; /* lookup value */
struct mk_list _head;
};
```
---- …
> filter_parser: use string as a default value

- plugins/in_exec/in_exec.c
https://github.com/fluent/fluent-bit/issues/5715#issuecomment-1184409540
Valgrind reports using uninitialized `ctx->parser_name`.
I modified to fill NULL using `flb_calloc`.
----
**Testing**
```
[SERVICE]
Flush        1
Parsers_File parsers.conf 
[INPUT]
Name …
```
> in_exec: use flb_calloc to fill NULL (#5715)

- plugins/out_es/es.c
- plugins/out_opensearch/opensearch.c
Fixes #5314 5314
----
**Testing**
----
> out_es: fix trace_error truncating the response

- plugins/out_azure_kusto/azure_kusto_ingest.c
Removed a reference to a deprecated header. 
> plugins: out_azure_kusto: removed deprecated header

- .github/workflows/call-build-windows.yaml
This PR is backporting #5870.
Related to https://github.com/fluent/fluent-bit/issues/5885.
----
**Testing**
----
> workflows: windows: Use chocolatey's OpenSSL installer for linking OpenSSL (#5780 backport to 1.9)

- plugins/out_stackdriver/stackdriver.c
- plugins/out_stackdriver/stackdriver_conf.c
This change adds the `name` label to the metrics. When used with multiple
of the same exporter, the metrics from each of them become
indistinguishable from the others. This leads to problems when ingesting
metrics. For example the `prometheus` receiver in Open Telemetry will
assume they are one and the same metric and will replace existing data
points with later ones.
> out_stackdriver: add name label to the metrics emitted

- plugins/out_lib/out_lib.c
- tests/runtime/out_lib.c
This patch is to support metrics data type.
It is useful to test some metrics input plugins.
----
**Testing**
```
$ valgrind --leak-check=full bin/flb-rt-out_lib 
==94166== Memcheck, a memory error detector
==94166== Copyright (C) …
```
> out_lib: support metrics input

- src/tls/openssl.c
Refer to doc, `SSL_load_error_strings` has been deprecated since OpenSSL v1.1.0.
https://www.openssl.org/docs/man3.0/man3/SSL_load_error_strings.html
```
The ERR_load_crypto_strings(), SSL_load_error_strings(), and ERR_free_strings() functions were deprecated in OpenSSL 1.1.0 by OPENSSL_init_crypto() and OPENSSL_init_ssl() and should not be used.
```
I think it causes below valgrind leak report.
```
$ valgrind --leak-check=full --show-leak-kinds=all bin/fluent-bit -i dummy -o null
==38038== Memcheck, a memory error detector
==38038== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==38038== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==38038== Command: bin/fluent-bit -i dummy -o null
==38038== 
Fluent Bit v2.0.0
* Copyright (C) 2015-2022 The Fluent …
```
> openssl: remove deprecated SSL_load_error_strings

- src/flb_pack.c
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45978
In `in_lib_collect`:
```cpp
else if (ret == FLB_ERR_JSON_INVAL) {
flb_plg_warn(ctx->ins, "lib data invalid");
flb_pack_state_reset(&ctx->state);
flb_pack_state_init(&ctx->state);
return -1;
}
```
When `flb_pack_state_init` returns with an error because `s->tokens = flb_malloc(size);` fails, it leaves `s->buf_data` with already freed pointer value because `flb_pack_state_reset` only frees the `s->buf_data` but doesn't reset its value. Later it leads to double free when `flb_pack_state_reset(&ctx->state);` is called on the same `ctx->state`.
> pack: Fix Heap-double-free in flb_pack_state_reset

- cmake/homebrew.cmake
In recent mebedtls removal, OpenSSL installation became one of the requirements to build fluent-bit.
And specifying every time of `-DOPENSSL_ROOT_DIR=$(brew --prefix openssl)` is a bit of redundant for CI and self building by users. 
No issue is not tied for this PR but it might be another follow up for #5887 and #5874.
----
**Testing**
---- …
> build: macos: openssl: Search homebrewed OpenSSL installed directory

- plugins/filter_tensorflow/tensorflow.c
- plugins/filter_tensorflow/tensorflow.h
Several fixes and modifications in the TensorFlow plugin.
----
**Testing**
```
valgrind --leak-check=full ./build/bin/fluent-bit -c conf/filter_tensorflow.conf                                                                                                         
==33454== Memcheck, a memory error detector                                                                                                                                                                                  
==33454== Copyright (C) 2002-2017, and GNU GPL'd, by Julian …
```
> filter_tensorflow: fixes and removal of string-type input field

- src/flb_lib.c
This patch ensures to call `pthread_cancel` on flb_lib termination phases.
In macOS, without calling pthread_cancel, we always SEGV on `flb-rt-in_forward` test cases. We should fix those SEGV failures.
----
**Testing**
----
> lib: macos: Call pthread_cancel explicitly to ensure thread termination

- tests/runtime/filter_stdout.c
This is because macOS requests surely initialization for pthread stuffs.
In our code base, flb_init_env() should initialize thread local storage stuffs.
Otherwise, FLB_TLS_GET returns invalid values.
----
**Testing**
----
> test: runtime: filter_stdout: Ensure TLS(thread local storage) initialization on macOS.

- plugins/out_kafka/kafka.c
When fluent-bit shutdown for out_kafka plugin with rdkafka.linger.ms and
rdkafka.batch.size and then we show the warn message and lose the message.
So, this patch fixes the issue of not flushing due to the rdkafka linger.ms option.
The 'rd_kafka_flush' function is linger.ms time will be ignored for the
duration of the call, queued messages will be sent to the broker as soon as possible.
Fix: #5593 
Signed-off-by: jinyong.choi <inimax801@gmail.com>
----
**Testing**
- [`v`] Example configuration file for the change
- [`v`] Debug log output from testing the change
- [`N/A`] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) …
> out_kafka: add support to force flush when shutdown. (fluent#5593)

- src/flb_ra_key.c
- tests/internal/record_accessor.c
Fixes #5936 
`subkey_to_object` doesn't save a value if the last element is an array.
Therefore, we can't get like `$key['nest'][1]`
This patch is to save it.
----
**Testing**
```
[INPUT]
Name dummy
Dummy {"method": "GET","requestHeader": {"User-Agent": ["mydevice"]}}
[FILTER]
Name …
```
> ra_key: save value when the data type is array(#5936)

- src/multiline/flb_ml.c
- tests/internal/multiline.c
- tests/runtime/data/tail/parsers_multiline_json.conf
- tests/runtime/filter_multiline.c
- tests/runtime/in_tail.c
Logic for checking if it is too early to flush in the multiline timer callback was inverted.
You want to ignore flushing in the timer callback if the last flush plus the timeout is after now time and not before.
fixes #5504
----
**Testing**
- [N/A] Attached [local packaging …
> multiline: fix flush timeout logic (fixes #5504)

- .github/workflows/unit-tests.yaml
- Set timeout-minutes to 60 minutes instead of 30.
> workflows: update unit tests timeout.

- CMakeLists.txt
- src/flb_network.c
This PR fixes the cmake snippet that detects unix socket availability. 
Additionally it disables the unix socket peer pid lookup feature in macos.
> network: fix unix socket detection and usage in macos

- src/flb_network.c
In macOS, when detection of unix socket support is failed, the following error is occurred on FLB_HAVE_UNIX_SOCKET's else branch:
```log
/Users/cosmo/GitHub/fluent-bit/src/flb_network.c:1632:14: error: conflicting types for 'flb_net_server_unix'
flb_sockfd_t flb_net_server_unix(const char *listen_path)
^
/Users/cosmo/GitHub/fluent-bit/include/fluent-bit/flb_network.h:162:14: note: previous declaration is here
flb_sockfd_t flb_net_server_unix(const char *listen_path, int stream_mode,
^
```
----
**Testing**
If this is a change to packaging of containers or native binaries then please confirm it …
> flb_network: Fix argument glitch when detection of unix socket support is failed

- plugins/in_forward/fw.c
- plugins/in_forward/fw_config.c
- plugins/in_http/http.c
- plugins/in_http/http.h
- plugins/in_http/http_config.c
- plugins/in_opentelemetry/opentelemetry.c
- plugins/in_opentelemetry/opentelemetry.h
- plugins/in_opentelemetry/opentelemetry_config.c
- plugins/in_syslog/syslog.c
- plugins/in_syslog/syslog.h
- plugins/in_syslog/syslog_conn.c
- plugins/in_syslog/syslog_server.c
- plugins/in_tcp/tcp.c
- plugins/in_tcp/tcp.h
- plugins/in_tcp/tcp_config.c
- plugins/in_udp/udp.c
- plugins/in_udp/udp.h
- plugins/in_udp/udp_config.c
- plugins/in_unix_socket/unix_socket.c
- plugins/in_unix_socket/unix_socket.h
- plugins/in_unix_socket/unix_socket_config.c
This PR fixes a long standing macos shutdown issue that persisted after the downstream upgrade.
When an input plugin registers a socket collector it is automatically added to the event loop. If the 
plugin then closes the file descriptor on its destructor without disposing of the collector when 
`flb_input_instance_destroy`  iterates the collector list destroying them it tries to unregister the already
closed file descriptor which causes a corruption that we are still investigating to determine if it's a 
bug in the `mk_event` layer.
Regardless of that, properly disposing of the collector (`flb_input_collector_pause` would work as well) 
before closing the socket solves the issue.
> plugins: added collector destruction before listener disposal to fix macos issue

- .github/workflows/call-run-integration-test.yaml
Resolves issue with integration tests picking up wrong config for GKE: https://github.com/fluent/fluent-bit/runs/8129900217?check_suite_focus=true
- https://github.com/fluent/fluent-bit-ci/blob/9fe15373756283874e821e903910f5c90184b46c/terraform/kubernetes.tf#L70-L72
- https://github.com/fluent/fluent-bit-ci/blob/9fe15373756283874e821e903910f5c90184b46c/terraform/kubernetes.tf#L128-L131
Aligns with workflow in other repo: https://github.com/fluent/fluent-bit-ci/blob/main/.github/workflows/call-run-integration-test.yaml
----
**Testing** …
> workflows: fix integration test zone for GKE

- src/flb_scheduler.c
that affected macos where the event loop registration mechanism is not
the same.
Changes in monkey are necessary but this is enough to prevent crashes.
> scheduler: fixed an issue with the way in which timers were disabled

- src/flb_pack.c
This is a continuation of https://github.com/fluent/fluent-bit/pull/5883 in order to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45978 Now same file make fluent-bit to crash in a different place.
The fix is to reset the `tokens` pointer to NULL after it is freed and handle that the value may be NULL in a different place.
> pack: Fix oss-fuzz crash

- tests/internal/aws_util.c
In macOS, it uses BSD origin strftime.
This implementation throws away % character for % and subsequent invalid
format character case.
The below is the minimum repo:
```c
#include <time.h>
#define KEY_SIZE 1024
int main(int argc, char **argv) {
int ret = 0;
char *key;
char *format = "logs/2020/m/08/d/15/%q";
struct tm gmt = {0};
time_t tm = time(NULL);
if (!gmtime_r(&tm, &gmt)) {
printf("Failed to create timestamp.\n");
goto error;
}
key = calloc(1, KEY_SIZE * sizeof(char));
if (!key) {
goto error;
}
ret = strftime(key, KEY_SIZE, format, &gmt);
if(ret == 0){
printf("Object key length is longer than the 1024 character limit.\n");
}
printf("[result] %s\n", key);
return 0;
error:
return -1;
}
```
In Linux, this should return as:
```console
$ ./strftime …
```
> tests: internal: aws_util: Handle difference of strftime format handling

- src/flb_pack.c
> 1.9.8: pack backport fixes

- lib/monkey/include/monkey/mk_core/mk_utils.h
- plugins/in_dummy_thread/in_dummy_thread.c
- src/flb_config.c
- src/flb_downstream.c
- src/flb_upstream.c
- tests/internal/config_format_fluentbit.c
- tests/internal/flb_event_loop.c
- tests/internal/flb_time.c
- tests/internal/fstore.c
- tests/internal/input_chunk.c
- tests/internal/metrics.c
- tests/internal/pack.c
- tests/internal/record_accessor.c
- tests/internal/signv4.c
- tests/internal/stream_processor.c
- tests/internal/utils.c
- tests/runtime/config_map_opts.c
- tests/runtime/flb_tests_runtime.h.in
- tests/runtime/in_syslog.c
- tests/runtime/out_file.c
- tests/runtime/out_plot.c
- tests/runtime_shell/in_http_tls_expect.sh
- tests/runtime_shell/in_syslog_tcp_plaintext_expect.sh
- tests/runtime_shell/in_syslog_tcp_tls_expect.sh
- tests/runtime_shell/in_syslog_udp_plaintext_expect.sh
There's nothing special about this PR, in fact, it's pretty crude but it's necessary.
If someone wants to refactor this it'd be great but we need to run those initialization steps
to keep the logger macro that accesses the TLS from crashing in macos.
> tests: macos fixes, mostly TLS initialization stuff

- include/fluent-bit/flb_log.h
- src/flb_log.c
- tests/runtime/CMakeLists.txt
- tests/runtime/core_log.c
Requested at https://github.com/fluent/fluent-bit/pull/5761#issuecomment-1216978362.
This patch splits `flb_log_print` function.
1. Construct log and check the buffer size.
2. Send log to pipe.
This patch also adds a function to check if the log will be truncated or not using Step1 of `flb_log_print` and test codes.
The function doesn't flush log buffer, only checks.
It needs args like printf and returns the result.
Return value
0              : The log is not truncated or filtered by log level setting.
-1             : Some error occurs.
positive number: The log will be truncated. Return value means the excess size.
----
**Testing**
- [N/A] …
> log: add flb_*_is_truncated functions to check if log will be truncated

- src/flb_strptime.c
Return 0 if signed integer overflows occur
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47092
----
**Testing**
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new …
> strptime: fix signed overflow

- tests/runtime/out_http.c
- tests/runtime/out_syslog.c
- tests/runtime/out_tcp.c
This patch is to remove unused value of test code.
I removed out_lib callback values from out_tcp/out_http/out_syslog test code.
----
**Testing** …
> tests: runtime: out_tcp: remove unused out_lib_cb

- src/config_format/flb_cf_fluentbit.c
- tests/internal/config_format_fluentbit.c
- tests/internal/data/config_format/classic/indent_level_error.conf
Relates #5888 #5911 
If user passed `cf` as args, `flb_cf_fluentbit_create` didn't return error.
Therefore fluent-bit will not stop even if some configuration error.
This patch is to modify it and the function returns NULL when some error occurs.
Note: `flb_cf_yaml_create` returns error even if user passed `cf`.
Note: v1.8.15 stops when indentation level error occurs.
```
$ ~/git/WORKTREE/v1.8.15/build/bin/fluent-bit -c issues/5888/a.conf 
Fluent Bit v1.8.15
[2022/08/28 09:11:50] [  Error] File issues/5888/a.conf
[2022/08/28 09:11:50] [  Error] Error in line 3: Invalid indentation level
Error: Configuration file contains errors. Aborting
```
----
Enter …
> config_format: fluentbit: return NULL when some error occurs

- tests/runtime/CMakeLists.txt
- tests/runtime/in_fluentbit_metrics.c
This patch is to add a test code for in_fluentbit_metrics.
----
**Testing**
```
$ valgrind --leak-check=full bin/flb-rt-in_fluentbit_metrics 
==2763== Memcheck, a memory error detector
==2763== Copyright (C) 2002-2017, and GNU GPL'd, …
```
> tests: runtime: in_fluentbit_metrics: add test code

- src/flb_ra_key.c
flb_sds_create_len may fail and this needs to be handled.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46082
----
**Testing**
- [N/A ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets …
> ra_key: handle error case

- include/fluent-bit/flb_connection.h
- include/fluent-bit/flb_network.h
- src/flb_connection.c
- src/flb_network.c
This PR adds a remote host address setter to `flb_connection` which is used to provide some info on the remote host before the connection is established just in case it times out, the same setter should be used when trying to send data to hosts through UDP while using a downstream listerner (shoddy, yeah).
We might want to improve UDP support since there are some implicit concepts in the `io` layer that could be confusing and cause issues in the future.
> connection: address processing improvements

- CMakeLists.txt
- include/fluent-bit/flb_custom_plugin.h
- include/fluent-bit/flb_filter_plugin.h
- include/fluent-bit/flb_input_plugin.h
- include/fluent-bit/flb_log.h
- include/fluent-bit/flb_output_plugin.h
> core: rename macro __FILENAME__ as __FLB_FILENAME__

- cmake/headers.cmake
- lib/chunkio/CMakeLists.txt
- lib/chunkio/deps/crc32/crc32.c
- lib/chunkio/include/chunkio/chunkio.h
- lib/chunkio/include/chunkio/cio_file.h
- lib/chunkio/include/chunkio/cio_file_native.h
- lib/chunkio/include/chunkio/cio_file_st.h
- lib/chunkio/src/CMakeLists.txt
- lib/chunkio/src/cio_file.c
- lib/chunkio/src/cio_file_unix.c
- lib/chunkio/src/cio_file_win32.c
- lib/chunkio/src/cio_memfs.c
- lib/chunkio/src/cio_os.c
- lib/chunkio/src/cio_utils.c
- lib/chunkio/src/win32/dirent.c
- lib/chunkio/tests/context.c
- lib/chunkio/tests/fs.c
- lib/chunkio/tests/memfs.c
> lib: chunkio: upgrade to v1.3.0

- src/flb_pack.c
This PR fixes Stack-buffer-overflow in msgpack_sbuffer_write revealed by fuzzing:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45208
The root cause is that snprintf call in flb_pack_msgpack_to_json_format returns the number of characters that would have been written if the buffer had been sufficiently large.
It leads to reading out of the boundaries of the buffer later.
> pack: Fix read Stack-buffer-overflow READ in msgpack_sbuffer_write

- src/flb_parser.c
It's not necessary to free tmp here as tmp is freed at fconf_error
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51132
----
**Testing**
- [N/A ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all …
> parser: fix double-free

- src/flb_scheduler.c
We need to do this so that the timer can be properly disabled and 
disposed of later.
> scheduler: set the `timer_fd` field in `schedule_request_now`

- tests/runtime_shell/in_http_tls_expect.sh
- tests/runtime_shell/in_syslog_tcp_plaintext_expect.sh
- tests/runtime_shell/in_syslog_tcp_tls_expect.sh
- tests/runtime_shell/in_syslog_udp_plaintext_expect.sh
- tests/runtime_shell/in_syslog_uds_dgram_plaintext_expect.sh
This PR spreads the shell script ports so they don't collide when 
running ctest with more than one job.
> tests: runtime_shell: spread the ports so they don't collide

- src/flb_downstream.c
- src/flb_upstream.c
This PR fixes fixes the issue where fluent-bit tries to remove a file descriptor
from both read and write "lists" when a timeout occurs, this is not a problem 
normally but it does generate a spurious kernel trip.
> upstream: event injection macos fix

- DEVELOPER_GUIDE.md
- run_code_analysis.sh
Provide a simple mechanism to run unit tests locally with various tools.
----
**Testing**
----
> developers: add code analysis tooling

- packaging/distros/amazonlinux/Dockerfile
Initial packaging support to build (not release) for Amazon Linux 2022 so addresses #6020.
This only provides the option to build, it will require further updates to build this target for release - related to #6039 as well to get those changes to config in.
Note AL2022 is still not stable/released so I don't think we can create release packages for it until then.
We will also need to update the release server to provide the necessary repositories.
----
**Testing** …
> packaging: add initial build support for Amazon Linux 2022

- src/fluent-bit.c
Replace `0` with `EXIT_SUCCESS`.
----
**Testing**
----
> bin: use EXIT_SUCCESS macro consistently

- conf/parsers.conf
The default cri parser @ parsers.conf should probably contain
Time_Keep On, otherwise the time tag does not exist at output at all.
Fixes #3085
----
**Testing**
----
> Set Time_Keep On for cri parser (fix #3085)

- run_code_analysis.sh
Recent updates for unit tests mean netcat is required now so added to the helper container as an extra dependency.
Without this PR it just stalls running the following:
```shell
$ ./run_code_analysis.sh
...
61/109 Test  #61: in_syslog_tcp_tls_expect.sh ................   Passed    6.03 sec
Start  62: in_syslog_tcp_plaintext_expect.sh
```
----
**Testing**
Now completes successfully.
----
> scripts: add netcat to code analysis helper script

- plugins/out_es/es.h
- plugins/out_es/es_conf.c
Complete unfinished work in PR https://github.com/fluent/fluent-bit/issues/3920
Ticket: #4260 
…g cloud_id.
----
**Testing**
```
[2022/05/16 07:53:42] [ info] [cmetrics] version=0.3.1
[2022/05/16 07:53:42] [debug] [output:es:es.0] extracted cloud_host: 'xyz.westeurope.azure.elastic-cloud.com:9243'
[2022/05/16 07:53:42] [debug] [output:es:es.0] check whether extracted cloud_host 'xyz.westeurope.azure.elastic-cloud.com:9243' contains a port
[2022/05/16 07:53:42] [debug] [output:es:es.0] cloud_host without port: 'xyz.westeurope.azure.elastic-cloud.com'
[2022/05/16 07:53:42] [debug] …
```
>  out_es: resolve domain name not found issue in cloud_id as it contains a port.

- include/fluent-bit/flb_record_accessor.h
- include/fluent-bit/flb_sds_list.h
- plugins/out_loki/loki.c
- plugins/out_loki/loki.h
- src/CMakeLists.txt
- src/flb_record_accessor.c
- src/flb_sds_list.c
- tests/internal/CMakeLists.txt
- tests/internal/record_accessor.c
- tests/internal/sds_list.c
- tests/runtime/data/loki/labelmap.json
- tests/runtime/out_loki.c
Fixes #5996 
See also https://github.com/grafana/loki/issues/4648#issuecomment-1223622156
This patch is to port `LabelMapPath` of go-loki plugin.
https://grafana.com/docs/loki/latest/clients/fluentbit/#labelmappath
1. Adds `flb_sds_list` to handle a string list
2. Loads json file and converts msgpack
3. Converts msgpack into record accessor string using `flb_sds_list`
4. Save string using `flb_loki_kv_append`
----
**Testing**
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all …
> out_loki: support label_map_path

- tests/include/flb_tests_initialize_tls.h
macOS requests to initialize TLS correctly.
The previous patch, https://github.com/fluent/fluent-bit/pull/5980, needs to put `flb_config` calling and destroy code on the every needed places of unit test files.
This should be sick for us to clean up code after TLS refactoring.
With this approach, we can remove TLS initializing code completely from unit tests with removing `TEST_INIT` and `TEST_FINI` part from flb_tests_internal.h.in.
Before TLS refactoring, we need to initialize TLS with `flb_config_init` because fluent-bit's logging mechanism is heavily relying on TLS for thread specific settings for worker.
Thus, once we use flb_{trace, debug, info, warn, error} function on somewhere, it implicitly depends on fluent-bit's logging …
> tests: internal: macos: Ensure TLS initialization for config function on every startup

- tests/runtime/core_chunk_trace.c
We need to enable chunk trace feature on unit test.
This feature should be needed to enable explicitly by command line arguments like this:
```console
$ ./bin/fluent-bit -H -i dummy -F record_modifier -m '*' -p record="foo bar" -o stdout -m '*' -f 1 -Z
```
And HTTPie:
```console
$ http -v 127.0.0.1:2020/api/v1/trace/dummy.0 output=stdout prefix=trace. enable:=true params:='{"format":"json"}'
POST /api/v1/trace/dummy.0 HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 86
Content-Type: application/json
Host: 127.0.0.1:2020
User-Agent: HTTPie/3.2.1
{
"enable": true,
"output": "stdout",
"params": {
"format": "json"
},
"prefix": "trace."
}
HTTP/1.1 200 OK
Date: Wed, 14 Sep 2022 …
```
> tests: core_chunk_trace: Enable chunk trace correctly

- tests/internal/fuzzers/pack_json_state_fuzzer.c
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35730
The issue is not really interesting, but is just a consequence of processing large amounts of data which is to be expected.
----
**Testing**
- [N/A ] Attached [local packaging …
> tests: internal: fuzzer: limit input size

- .github/workflows/staging-release.yaml
- .github/workflows/update-dockerhub.yaml
- dockerfiles/dockerhub-description.md
Resolves #5793 by ensuring we update the description in Dockerhub automatically on release but also adding a manual update option.
----
**Testing**
----
> workflows: add automated Dockerhub description update

- plugins/out_syslog/syslog.c
- plugins/out_syslog/syslog_conf.c
- plugins/out_syslog/syslog_conf.h
- tests/runtime/out_syslog.c
In some cases, a record doesn't contain a value for syslog. This patch adds *_preset properties to set a default value.
----
**Testing**
```
[INPUT]
Name dummy
[OUTPUT]
Name syslog
syslog_message_key dummy
syslog_appname_preset fluent-bit
syslog_hostname_preset localhost
```
netcat got a default appname and hostname.
```
$ nc -l …
```
> out_syslog: support preset configuration

- include/fluent-bit/flb_input.h
- include/fluent-bit/flb_storage.h
- src/flb_input.c
- src/flb_input_chunk.c
- src/flb_storage.c
The memory-ring-buffer mechanism is an optional buffering strategy for input plugins that relies only in memory. When this is enabled, the chunks management behaves as a ring buffer of a fixed size were setting up `mem_buf_limit` is mandatory to specify that limit.
When the chunks are enqueued, and `mem_buf_limit` is reached, instead  of pausing the input plugin as normally would happen with the default memory strategy, this new mechanism removes the oldest Chunks from  the queue until to make sure there is enough space for the new incoming data.
The configuration of this new strategy is as follows:
```
[INPUT]
name          tail
path          /var/log/*
storage.type  memrb
mem_buf_limit 20M
```
NOTE: by default Fluent Bit tries to enqueue Chunks of size around  2M, this is an internal …
> core: new memory-ring-buffering mechanism (memrb)

- include/fluent-bit/flb_input.h
- include/fluent-bit/flb_storage.h
- src/flb_input.c
- src/flb_input_chunk.c
- src/flb_storage.c
The memory-ring-buffer mechanism is an optional buffering strategy for input plugins that relies only in memory. When this is enabled, the chunks management behaves as a ring buffer of a fixed size were setting up `mem_buf_limit` is mandatory to specify that limit.
When the chunks are enqueued, and `mem_buf_limit` is reached, instead  of pausing the input plugin as normally would happen with the default memory strategy, this new mechanism removes the oldest Chunks from  the queue until to make sure there is enough space for the new incoming data.
The configuration of this new strategy is as follows:
```
[INPUT]
name          tail
path          /var/log/*
storage.type  memrb
mem_buf_limit 20M
```
NOTE: by default Fluent Bit tries to enqueue Chunks of size around  2M, this is an internal …
> 1.9: core: new memory-ring-buffering mechanism (memrb)

- src/config_format/flb_cf_yaml.c
- tests/internal/data/config_format/yaml/test/dummy_pipeline.yaml
Make the plugin property name explicit, allowing the rest of the properties to be declared at the same level.
This change modifies the way properties are passed to plugins so that now there is just a single map for them instead of nesting them under a map with a single with the plugin name, ie:
```yaml
pipeline:
inputs:
- name: dummy
rate: 5
```
This is related to the discussion of YAML 2.0: https://github.com/fluent/fluent-bit/discussions/6029.
----
**Testing**
----
> config/yaml: make the name property explicit and unnest properties.

- packaging/testing/smoke/container/fluent-bit.yaml
Update smoke test to work with new YAML 2.0 yaml format.
This fix is for #6029, which has already been merged.
----
**Testing**
----
> smoke-tests: update smoke test for new YAML format.

- lib/monkey/include/monkey/mk_core/mk_event.h
- lib/monkey/include/monkey/mk_core/mk_list.h
- lib/monkey/include/monkey/mk_core/mk_utils.h
- lib/monkey/mk_core/mk_event.c
- lib/monkey/mk_core/mk_event_epoll.c
- lib/monkey/mk_core/mk_event_kqueue.c
- lib/monkey/mk_core/mk_event_libevent.c
- lib/monkey/mk_core/mk_event_select.c
- lib/monkey/mk_core/mk_rconf.c
- lib/monkey/mk_core/mk_string.c
- lib/monkey/mk_server/mk_lib.c
- lib/monkey/mk_server/mk_mimetype.c
- lib/monkey/mk_server/mk_stream.c
Sync with upstream commit [754088d69ffb507e8cd651701fda93511f07cf69]. This provides several fixes for tests as well as new functionality for the upcoming 2.0 release.
----
**Testing**
----
> lib/monkey: sync with upstream.

- src/flb_config.c
- tests/internal/aws_credentials.c
- tests/internal/flb_event_loop.c
- tests/internal/input_chunk.c
- tests/internal/network.c
- tests/runtime/config_map_opts.c
- tests/runtime/core_chunk_trace.c
- tests/runtime/filter_kubernetes.c
- tests/runtime/flb_tests_runtime.h.in
- tests/runtime/in_fluentbit_metrics.c
- tests/runtime/in_syslog.c
- tests/runtime/in_tail.c
- tests/runtime/out_file.c
- tests/runtime/out_lib.c
- tests/runtime/out_plot.c
Currently, unit tests on macOS are failing on every time. 
One of the reasons is that macOS's filesystem is relatively slow due to inotify is not supported. 
Another reason is macOS's timer is not accurate for other platforms such as Windows and Linux. This is because macOS's timer is not precise under microseconds. Always macOS's timestamp are zeroed the last 3 digits of nanosecond scale of time.
~~There is still a SEGV issue on `mk_event_loop_destroy(log->evl);` at `flb_log_destroy`. 
But, this is timing issue. Not every time occurred.~~ This issue is fixed by https://github.com/fluent/fluent-bit/pull/6135.
----
**Testing**
If this is a …
> macos: tests: Fix most of unit tests failures on macOS

- tests/runtime/filter_stdout.c
The filter_stdout test throws a SIGSEGV when invoking pthread_join inside flb_stop. Since we do not call flb_start before the thread ID is null. So I just removed the call to flb_stop.
----
**Testing**
----
> tests/filter_stdout: fix SIGSEGV by not calling flb_stop without flb_start

- examples/tracing/docker-compose.yml
Update the docker-compose example for tracing to use the new compile flag `FLB_CHUNK_TRACE` instead of the old `FLB_TRACE` to enable tracing.
----
**Testing**
----
> trace: update docker build for example with new compile flag.

- plugins/out_loki/loki.c
The Loki output plugin previously disabled processing mulitple tasks per flush because Loki historically did not support out-of-order writes. However this behavior had a deleterious effect on throughput.
Signed-off-by: Paul Wheeler <pwheeler@revacomm.com>
This change simply removes the `FLB_OUTPUT_NO_MULTIPLEX` from the Loki output plugin flags. I will open a separate issue for adding a backward compatibility configuration that preserves the existing behavior for user who may still be using older versions of Loki.
Fixes #5868
----
**Testing**
[fluent-bit.config](https://github.com/fluent/fluent-bit/files/9700933/fluent-bit.config.txt)
See [this repository](https://github.com/revacomm-pwheeler/fluent-bit-loki-grafa …
> out_loki: enable processing multiple tasks in loki output plugin.

- src/flb_help.c
Add in the options that input net plugins use to the help menu.
----
**Testing**
----
> help: show implicit options for input net plugins.

- src/flb_metrics.c
This patch is to add warn message when title was truncated.
https://linux.die.net/man/3/snprintf
```
The functions snprintf() and vsnprintf() do not write more than size bytes (including the terminating null byte ('\0')). If the output was truncated due to this limit then the return value is the number of characters (excluding the terminating null byte) which would have been written to the final string if enough space had been available. Thus, a return value of size or more means that the output was truncated.
```
----
**Testing**
- [N/A] …
> metrics: add warn message when 'title' was truncated

- dockerfiles/Dockerfile
The new Tap feature requires enabling at both compilation and runtime.
This would therefore require custom images for any user who wants to use a headline feature of 2.0 so this PR enables it by default for containers only - it still requires runtime activation via `--enable-chunk-trace` CLI parameter or setting `Enable_Chunk_Trace On` in the service section of the config file (along with the webserver and exposing that port).
----
**Testing**
---- …
> dockerfiles: enable Tap in official containers

- tests/internal/fuzzers/engine_fuzzer.c
Fix API of engine fuzzer to match latest changes.
Fixes a broken fuzzer
----
**Testing**
- [N/A …
> tests: internal: fuzzers: engine_fuzzer: fix build

- plugins/in_opentelemetry/opentelemetry_prot.c
This PR updates the opentelemetry metrics decoder interface to match the new interface in cmetrics.
> in_opentelemetry: updated decoder interface

- include/fluent-bit/config_format/flb_cf.h
- src/config_format/flb_cf_fluentbit.c
- src/config_format/flb_cf_yaml.c
- src/config_format/flb_config_format.c
- src/flb_parser.c
- src/flb_parser_decoder.c
- src/flb_plugin.c
- src/flb_upstream_ha.c
- src/fluent-bit.c
- src/stream_processor/flb_sp.c
- tests/internal/config_format.c
- tests/internal/config_format_fluentbit.c
- tests/internal/config_format_yaml.c
This adds support for lists in the YAML file configuration format. Here is an example:
```yaml
pipeline:
filters:
- name: record_modifier
match: *
record:
- powered_by calyptia
- generated_by fluent-bit
```
Disccussed in https://github.com/fluent/fluent-bit/discussions/6029.
----
**Testing**
----
> config/yaml: clist and slist support

- src/config_format/flb_config_format.c
- src/fluent-bit.c
Properties values were being truncated to the length of their key. They were also not being correctly reported when there were errors.
----
**Testing**
----
> config: fix property values being truncated.

- .github/workflows/call-build-linux-packages.yaml
- packaging/build.sh
Related to #6171 to ensure we correctly default to `fluent-bit` name for 1.9 branch builds.
----
**Testing**
----
> packaging: handle 1.9 package builds for fluent-bit defaults

- packaging/distros/raspbian/Dockerfile
Resolves #6175 by fixing issue in CI with `tini` and also pin `cmake` for a separate issue on raspbian/buster targets
----
**Testing**
Tested in CI: https://github.com/fluent/fluent-bit/actions/runs/3225270493/jobs/5277384734
- https://github.com/fluent/fluent-bit/pull/6184
----
> packaging: update raspbian container and pin cmake

- src/flb_parser.c
Only limited fields should be freed when an early error happens in `parser_conf_file`. Otherwise, we will either free too much such that a double free will happen when used in combination with `flb_parser_exit` and `flb_config_exit`, or, memory leaks will happen. This fixes so neither of these situations happen.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51223
----
**Testing**
- [N/A ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows …
> parser: refine exit path

- src/flb_strptime.c
The current boundary is wrong, this fixes it.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51024
----
**Testing**
- [N/A ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any …
> strptime: fix integer boundary

- src/flb_env.c
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51278
----
**Testing**
- [N/A ] …
> env: add size check before copying

- dockerfiles/Dockerfile.windows
Resolves #6181 by adding OpenSSL to the container build.
----
**Testing**
Tested in a container build here: https://github.com/fluent/fluent-bit/actions/runs/3225614044/jobs/5278419160
Openssl: https://github.com/fluent/fluent-bit/actions/runs/3225614044/jobs/5278419160#step:4:1018
----
> dockerfiles: add OpenSSL to Windows container

- packaging/build-config.json
- packaging/server/README.md
- packaging/server/publish-all.sh
- packaging/testing/smoke/packages/Dockerfile.amazonlinux2022
- packaging/update-repos.sh
Part of steps for #6020 to provide official Amazon Linux 2022 packages.
Also handles usage of `createrepo_c` on Ubuntu 22 for packaging usage - partly required for https://github.com/fluent/fluent-bit/issues/6174.
Final steps are docs and release process itself.
----
**Testing**
----
> packaging: update to provide AL 2022 as an official target

- plugins/in_tail/tail_file.c
On a 32 bit system, the inode number is 32 bits, not 64, so the format string expecting a 64bit parameter would end up with junk data and continue to think a new file was found, leaking file descriptors and eventually preventing fluent bit from running.
Cast the inode parameter when generating the file hash to 64 bits to avoid differences on 32 versus 64 bit systems.
Fixes #6198 
----
**Testing**
- [X ] Debug log output from testing the change
- [X ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found …
> in_tail: Fix 32 bit support in file hash logic

- plugins/in_event_type/event_type.c
- plugins/out_opentelemetry/opentelemetry.c
- plugins/out_opentelemetry/opentelemetry.h
out_opentelemetry:
- export traces (add config option for traces uri)
in_event_type:
- use correct buffer length for span id
- set correct event type
----
**Testing**
```
[INPUT]
Name event_type
type traces
[OUTPUT]
match *
host 0.0.0.0
port 4318
[OUTPUT]
name stdout
match *
```
https://pastebin.com/vDeE3xPN
https://pastebin.com/YFVmt1ZJ
---- …
> out_opentelemetry: export traces

- plugins/out_forward/forward.c
Fixes #6082 
This patch is to free memory when `time_as_integer` is true and no connection is available.
----
**Testing**
```
fluent-bit -i dummy -o forward -p time_as_integer=on
```
```
$ valgrind --leak-check=full bin/fluent-bit -i dummy -o forward -p time_as_integer=on
==43252== …
```
> out_forward: release buf when no connection available and time_as_integer is true(#6082)

- plugins/out_forward/forward.c
This is a porting for 1.9 branch.
Original PR is #6210
----
**Testing**
- [N/A] Backport …
> out_forward: 1.9 release buf when no connection available and time_as_integer is true(#6082)

- plugins/in_winevtlog/in_winevtlog.c
- plugins/in_winevtlog/winevtlog.c
- plugins/in_winevtlog/winevtlog.h
Additions to in_winevtlog plugin to allow scenarios where one or more channels are missing on Windows Event Log
ex: PowerShellCore/Operational needs the proper software installed to
appear under Application and Services Log
----
**Testing**
Added …
> plugins: in_winevtlog: adds ability to ignore channels missing in Windows Event Log

- include/fluent-bit/flb_pack.h
- include/fluent-bit/flb_time.h
- src/flb_pack.c
- src/flb_time.c
This PR addresses [the comment](https://github.com/fluent/fluent-bit/pull/4131#discussion_r964648743) on [the original pull request](https://github.com/fluent/fluent-bit/pull/4131) since there has been no progress for a long time.
>This PR adds epoch_ms format which represents UNIX epoch in milliseconds.
----
**Testing**
----
```
[OUTPUT]
Name  stdout
Match *
Format json
json_date_key timestamp
json_date_format epoch_millis
```
```
* Fluent Bit is a CNCF sub-project under …
```
> pack: add 'epoch_ms' format based on  jeongki-kim's commit

- src/flb_parser_logfmt.c
In #4359, @nokute78 notes that bare keys in logfmt lines get the wrong
value after parsing: they should get a `true` value, not `nil`.
----
**Testing**
---- …
> logfmt: bare keys get "true" as value, not "nil"

- src/config_format/flb_cf_fluentbit.c
- tests/internal/config_format_fluentbit.c
- tests/internal/data/config_format/classic/recursion.conf
This commit 
- Sets a limit number of config files. (1000)
- Checks recursion based on inode number.
Fluent-bit allocates an array to save inodes to compare new file's inode.
If the inode is matched, fluent-bit aborts.
----
**Testing**
- [N/A] …
> config_format: fluentbit: set config file number limit and check recursion(#5998)

- packaging/server/publish-all.sh
- packaging/update-repos.sh
Resolves #6223 which was triggering failures on staging builds due to word splitting (or lack of).
----
> packaging: handle parameters separate from command for word splitting

- src/flb_input.c
This PR adds a check to ensure the user is providing both a certificate and a private key file when using TLS in input plugins.
> input: added missing mandatory TLS parameter detection and reporting.

- plugins/out_loki/loki.c
Fixes #6207 
Refer to #6207, user wants to get tenant_id from record to use as a http header and remove it from record.
This patch is to call `get_tenant_id_from_record` before removing keys.
----
**Testing**
```
[INPUT]
Name dummy
Dummy {"namespace":"NAME", "container":"CONTAINER", …
```
> out_loki: get tenant_id before removing keys(#6207)

- src/fluent-bit.c
Minor bug fix to update the usage of the new config format API from the command line.
----
**Testing**
- [N/A] Backport to latest stable …
> fluent-bit: fix command line parsing with new config format API.

- .github/workflows/build-legacy-branch.yaml
After removal of 1.8 build support, this re-introduces a separate workflow to provide a container build for a 1.8 based branch.
----
**Testing**
----
> workflows: add 1.8 branch container build

- src/flb_parser_logfmt.c
A line like `foo=bar baz` should be parsed to `{"foo"=>"bar", "baz"=>nil}`, but `baz` was silently omitted by returning early from the parser.
----
**Testing**
----
> logfmt: don't omit last item if it does not have a value

- include/fluent-bit/flb_filter.h
- src/flb_filter.c
Instead of just having metrics for number of records added/dropped, we
now also have metrics for the total number of records and bytes
processed by each filter.
We want to have insight into this to check whether our filters match the correct things.
----
**Testing**
----
> filter: add total processing volume metrics

- include/fluent-bit/flb_metrics.h
- lib/cmetrics/CMakeLists.txt
- lib/cmetrics/include/cmetrics/cmt_encode_splunk_hec.h
- lib/cmetrics/src/CMakeLists.txt
- lib/cmetrics/src/cmt_encode_splunk_hec.c
- lib/cmetrics/tests/encoding.c
- plugins/out_splunk/splunk.c
With cmetrics support of Splunk HEC encoding, we can handle metrics type of events on out_splunk.
----
**Testing**
----
> out_splunk: Handle metrics type of events

- examples/filter_rust/README.md
- examples/filter_rust_clib/README.md
filter_wasm handles `WASM_Path` instead of `WASI_Path`.
----
> example: wasm: Fix typos

- plugins/filter_record_modifier/filter_modifier.c
- tests/runtime/filter_record_modifier.c
Fixes #6200 
This patch is to allow `Whitelist_keys` for compatibility.
----
**Testing**
```
[INPUT]
Name dummy
Dummy {"a":"aaa", "b":"bbb", "c":"ccc"}
[FILTER]
Match *
Whitelist_Key a
Whitelist_Key b
[OUTPUT]
Name stdout
Match *
```
```
$ valgrind …
```
> filter_record_modifier: fix ignoring whitelist_keys (#6200)

- plugins/in_tail/tail_file.c
When appending Path_Key or Offset_Key in multiline mode, append the keys to the correct buffer.
Fixes #6240
----
**Testing**
* Backport PR: https://github.com/fluent/fluent-bit/pull/6244
**main.conf**
```
[INPUT]
Name              tail
Key               message
Path              ./test.log
Path_Key          path …
```
> in_tail: Fix multiline + Path_Key emitting empty logs

- plugins/in_tail/tail_file.c
Backport of PR #6243 for issue #6240
When appending Path_Key or Offset_Key in multiline mode, append the keys to the correct buffer.
----
**Testing**
**main.conf**
```
[INPUT]
Name              tail
Key               message
Path              ./test.log
Path_Key          path …
```
> in_tail: Fix multiline + Path_Key emitting empty logs (1.9)

- plugins/in_opentelemetry/opentelemetry_prot.c
Adds support for ingesting OpenTelemetry logs into Fluent Bit (both JSON and protobuf encoded payloads)
Addresses #5779 
----
**Testing**
```
[INPUT]
host 0.0.0.0
port 4318
[OUTPUT]
name stdout
match *
```
https://github.com/fluent/fluent-bit-docs/pull/872
----
> in_opentelemetry: add proto files for logs

- tests/runtime/in_simple_systems.c
The new dummy tests for copies do not pass on the CI systems due to latency or some other timing related reason. I also witnessed this on my M1 mac book. This is a patch to increment the sleep time taken by these tests from 2 to 5 seconds in the hopes that allows enough time for it to run on the CI systems.
----
**Testing**
----
> dummy: up the sleep time in the tests so they pass.

- src/flb_chunk_trace.c
- src/flb_filter.c
- src/http_server/api/v1/trace.c
Several minor fixes I applied while testing the rewrite_tag filter with traces:
* check an alias is set for an input when searching for an input to activate a trace on.
* improve handling for empty records (which rewrite_tag emits...).
* fix arguments passed to trace filter.
----
**Testing**
----
> chunk_trace: minor fixes when tracing with rewrite_tag filters.

- dockerfiles/Dockerfile.windows
Currently, Dockerfile for windows in fluent-bit's master is not working correctly on Windows.
This PR should fix this issue.
With this fix, we can run fluent-bit 2.0 included Windows container on Windows:
```log
PS> docker build . -t fluent/fluent-bit:<<fluent-bit-built-tag>> -f .\dockerfiles\Dockerfile.windows
PS> docker run -it --rm fluent/fluent-bit:<<fluent-bit-built-tag>>
Fluent Bit v2.0.0
[2022/10/25 17:02:34] [ info] [fluent bit] version=2.0.0, commit=, pid=1308
[2022/10/25 17:02:34] [ info] [storage] ver=1.2.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2022/10/25 17:02:34] [ …
```
> dockerfiles: Fix to work correctly for Windows container

- src/flb_fstore.c
- src/flb_storage.c
This PR fixes two warning related to the logging callback prototype expected by chunk io.
> storage: fixed chunkio log callback prototypes

- plugins/out_forward/forward_format.c
Since fluent-bit 2.0.0, we start to add `fluent_signal` to represent event_type for logs, metrics, and traces.
However, out_forward still wants to be chunk key as the first key of the option.
Closes https://github.com/fluent/fluent-bit/issues/6290
----
**Testing**
client:
```ini
[SERVICE]
Flush                1
Daemon               Off
Log_Level            debug
Parsers_File         ../conf/parsers.conf
[INPUT]
Name                 tcp
Listen               0.0.0.0
Port                 5170
Format               none
Separator            \n
[OUTPUT]
Name                 forward
Match …
```
> out_forward: Put chunk key as the first key of the option map

- src/config_format/flb_cf_fluentbit.c
- tests/internal/config_format_fluentbit.c
- tests/internal/data/config_format/classic/issue6281.conf
- tests/internal/data/config_format/classic/issue6281_input.conf
- tests/internal/data/config_format/classic/issue6281_output.conf
https://github.com/fluent/fluent-bit/blob/v2.0.0/src/config_format/flb_cf_fluentbit.c#L439
In this case, fluent-bit tries to resolve the real path.
However `st` will not be updated using new real path.
Then `st.st_ino` will be 0 and fluent-bit will abort.
https://github.com/fluent/fluent-bit/blob/v2.0.0/src/config_format/flb_cf_fluentbit.c#L453
This issue was caused by https://github.com/fluent/fluent-bit/pull/6213
It will happen using following command.
```
fluent-bit -c <absolute path to configuration file>
```
This patch is to fix it calling stat for new real path to get real inode.
----
**Testing** …
> config_format: fluentbit: call stat again when resolve real path(#6281)

- plugins/in_winevtlog/winevtlog.c
With previous implementation, winevtlog plugin does not handle any channels when ignore_missing_channels parameter is not true.
----
**Testing**
----
> in_winevtlog: Fix ignoring non-existent channel handling

- tests/runtime/out_forward.c
From PR https://github.com/fluent/fluent-bit/pull/6298, the order of `fluent_signal` had been changed.
We should follow the option alignment. 
----
**Testing**
----
> tests: runtime: out_forward: Follow option order for fluent_signal

- tests/runtime/out_http.c
- tests/runtime/out_lib.c
- tests/runtime/out_tcp.c
DBL_EPSILON should compare with absolute value since (0.0 - 1.0) < DBL_EPSILON always true.
----
**Testing**
- [N/A] Backport to latest …
> tests: runtime: add missing fabs() to compare DBL_EPSILON

- tests/internal/fuzzers/CMakeLists.txt
- tests/internal/fuzzers/base64_fuzzer.c
> tests: internal: fuzzers: add base64 fuzzer

- .github/workflows/call-build-images.yaml
- .github/workflows/staging-build.yaml
- .github/workflows/staging-release.yaml
Addresses #6278 by pushing the current staging Windows OCI images to release registries and also builds for Windows Server 2022.
We re-enable the MacOS build as well for staging (it is stable now).
----
**Testing**
Test run of this branch: https://github.com/fluent/fluent-bit/actions/runs/3360667316
----
> workflows: windows OCI image release

- packaging/server/publish-all.sh
- packaging/test-release-packages.sh
Resolves failures during publishing on the server side.
Adds AL2022 to test suite for releases and resolves issue with curl vs curl-minimal mismatch to resolve #6280 .
----
**Testing**
Changes tested for 2.0.3 release process and also run the `test-release-packages.sh` script locally which failed for AL2022 prior to the updates in #6280 for the release server symlink.
----
> packaging: fix publish script

- plugins/out_opensearch/opensearch.c
- plugins/out_opensearch/opensearch.h
- plugins/out_opensearch/os_conf.c
- tests/runtime/out_opensearch.c
> out_opensearch: add support for record accessor on 'index' property

- include/fluent-bit/flb_input.h
- plugins/in_forward/fw.c
- plugins/in_http/http.c
- plugins/in_mqtt/mqtt.c
- plugins/in_opentelemetry/opentelemetry.c
- plugins/in_syslog/syslog.c
- plugins/in_tcp/tcp.c
- plugins/in_udp/udp.c
- plugins/in_unix_socket/unix_socket.c
- src/flb_help.c
- src/flb_input.c
This PR adds the `FLB_INPUT_NET_SERVER` flag meant to be used in input plugins that start listeners in order to differentiate them from those that actively fetch information from remote sources while enforcing TLS setting correctness.
Additionally, the `FLB_IO_OPT_TLS` flag was added to some plugins that should have it but didn't.
> networking: added a flag to diferentiate input plugins that listen for connections 

- include/fluent-bit/flb_parser.h
- include/fluent-bit/flb_strptime.h
- include/fluent-bit/flb_time.h
- src/flb_parser.c
- src/flb_parser_json.c
- src/flb_parser_logfmt.c
- src/flb_parser_ltsv.c
- src/flb_parser_regex.c
- src/flb_strptime.c
- tests/runtime/filter_parser.c
Fix time zone offsets being lost on Windows when parsing time stamps.
Fixes #2941.
----
**Testing**
----
> parser: fix time zone offsets being dropped on Windows

- CMakeLists.txt
wasm-micro-runtime(WAMR) does not support *BSD platforms. We should disable Wasm feature on them.
With this patch, cmake's configuration can be passed but still not buildable due to incompatible pointer type:
```
[ 45%] Building C object src/CMakeFiles/fluent-bit-static.dir/flb_engine_dispatch.c.o
/home/cosmo/GitHub/fluent-bit/src/flb_network.c:516:17: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
str = strerror_r(error, so_error_buf, sizeof(so_error_buf));
^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/cosmo/GitHub/fluent-bit/src/flb_network.c:1796:18: error: variable has incomplete type 'struct ucred'
struct ucred peer_credentials;
^ …
```
> build: wasm: Disable WASM for *BSD

- src/flb_env.c
- tests/internal/CMakeLists.txt
- tests/internal/env.c
Fixes #6313 
The issue exposed by strict checking patch https://github.com/fluent/fluent-bit/pull/6152 
However the root cause is small temporary buffer size.(=64 bytes)
If a size of environment value name  exceeds the buffer size, the variable is not translated.
----
**Testing** …
> env: increase temp buffer size(#6313)

- tests/internal/fuzzers/CMakeLists.txt
- tests/internal/fuzzers/ctrace_fuzzer.c
> tests: internal: fuzzers: add ctrace fuzzer

- plugins/out_forward/forward.c
- plugins/out_forward/forward.h
Just using to pack `msgpack_pack_bin` is not suitable for them. Instead, we should format as forward mode compatible array with:
```
[[time, [{map of msgpack payloads}]]]
```
to be able to handle with ordinary msgpack handler for format of forward mode.
----
**Testing**
```ini
[SERVICE]
log_level       info
[INPUT]
Name dummy
Tag  dummy.local
Dummy {"message":"ok"},{"message":"ng"}
[INPUT]
name            fluentbit_metrics
tag             internal_metrics
[OUTPUT]
name forward
host 127.0.0.1
port 24224
Match *
```
```ini
[SERVICE]
Flush        5
Daemon …
```
> out_forward: Make forwardable for msgpack payloads of ctraces and cmetrics

- plugins/out_opentelemetry/opentelemetry.c
- plugins/out_opentelemetry/opentelemetry.h
- plugins/out_opentelemetry/opentelemetry_conf.c
This removes the last memory error I was able to detect in @Syn3rman 's otlp-log-obj branch
----
**Testing**
----
> out_opentelemetry: a single line fix to remove the last invalid free from the otlp-log-obj branch.

- tests/internal/CMakeLists.txt
- tests/internal/parser_regex.c
This patch is to add internal test for regex parser.
----
**Testing**
```
$ valgrind --leak-check=full --show-leak-kinds=all bin/flb-it-parser_regex 
==37283== Memcheck, a memory error detector
==37283== Copyright (C) 2002-2017, and …
```
> tests: internal: parser_regex: add test for parser_regex

- include/fluent-bit/flb_network.h
- plugins/in_syslog/syslog.c
- plugins/in_syslog/syslog.h
- plugins/in_syslog/syslog_conf.c
- plugins/in_syslog/syslog_server.c
- src/flb_network.c
This PR adds an option to set receiving socket buffer size on syslog.
This avoids losing packets on an datagram listening socket in case of a burst of incoming packet when the default buffer size (/proc/sys/net/core/rmem_default) is too low.
----
**Testing**
----
> in_syslog: added option to set receiving socket buffer size

- src/flb_input.c
- src/flb_network.c
In FreeBSD, `struct ucred` is incomplete strust type like as macOS.
We should avoid to use it on FreeBSD.
Related to https://github.com/fluent/fluent-bit/issues/6289.
----
**Testing**
----
> network: freebsd: Don't use linux like struct ucred on freebsd

- src/fluent-bit.c
Fix a compiler warning which can cause some of our docker builds to fail.
----
**Testing**
----
> fluent-bit: fix return type for flb_cf_section_property_add.

- plugins/in_health/health.c
- plugins/in_nginx_exporter_metrics/nginx.c
- plugins/in_prometheus_scrape/prom_scrape.c
- src/flb_input.c
This PR fixes the TLS parameter verification and TLS session initialization for those input plugins that actively scrape remote endpoints. Additionally, this enables those plugins to connect to TLS endpoints which was not an option (regardless of the parameter verification issue).
> input: TLS parameter verification fix

- .github/workflows/staging-release.yaml
- packaging/testing/smoke/packages/Dockerfile.amazonlinux2
- packaging/testing/smoke/packages/Dockerfile.amazonlinux2022
- packaging/testing/smoke/packages/Dockerfile.centos7
- packaging/testing/smoke/packages/Dockerfile.centos8
- packaging/testing/smoke/packages/Dockerfile.centos9
- packaging/testing/smoke/packages/Dockerfile.debian10
- packaging/testing/smoke/packages/Dockerfile.debian11
- packaging/testing/smoke/packages/Dockerfile.ubuntu1804
- packaging/testing/smoke/packages/Dockerfile.ubuntu2004
- packaging/testing/smoke/packages/Dockerfile.ubuntu2204
- packaging/testing/smoke/packages/run-package-tests.sh
- packaging/testing/smoke/packages/test.sh
Resolves #6356 by providing a separate job to do the Windows container release so this can run on a Windows runner.
Resolves #6357 by using podman which handles systemd and cgroupsv2 much better.
----
**Testing**
----
> workflows: handle windows container release

- src/multiline/flb_ml.c
Use a local variable instead of setting the ml group time when flushing multiline groups with a zeroed log time. This avoids a problem where log times get stuck as the first log time when an actual time is not parsed from the logs.
----
**Testing**
----
> multiline: do not permanently set ml group time to the first log time.

- tests/internal/CMakeLists.txt
- tests/internal/parser_ltsv.c
This patch is to add internal test for ltsv parser.
----
**Testing**
```
d$ valgrind --leak-check=full bin/flb-it-parser_ltsv 
==26075== Memcheck, a memory error detector
==26075== Copyright (C) 2002-2017, and GNU GPL'd, by Julian …
```
> tests: internal: parser_ltsv: add test for parser_ltsv

- packaging/build-config.json
Related to #6300 but disable the ARM build due to the excessive time until we can resolve.
> packaging: disable ARM build for AL2022 due to time

- cpack/wix/WIX.template.in.cmakein
* In fluent-bit 2.0, some of cases leads installation failure due to strictly checking on returning values.
* Introduce environment variables to skip service launching for orchestration tools.
Managing with Ansible or Chef or else cases, automatic service launch is not preferable for such cases.
Because Windows does not permit file replacement during someone is using.
----
**Testing**
---- …
> wix: windows: Tweak wix installer for fluent-bit 2.0

- src/flb_chunk_trace.c
This happens enough that I decided to add a warning. Warn people to enable chunk tracing when it is disabled and they attempt to activate it.
----
**Testing**
----
> chunk-trace: add a warning to enable tracing when it is not enabled.

- plugins/in_tail/win32/stat.c
This patch fixes an issue where st_mtime for Windows platforms was set directly from `ftLastWriteTime` without converting it to a Unix epoch timestamp first. This caused checks against `st_mtime` to not behave as expected.
For instance, this caused the `Ignore_Older` configuration option for in_tail to not work properly as it still registered files that it shouldn't have. 
How to reproduce the issue on Windows without this fix: Using in_tail, if you add a new file that matches the `Path` pattern you will see while debugging the application that [this](https://github.com/fluent/fluent-bit/blob/master/plugins/in_tail/tail_file.h#L46) line does not *"return the file modification time in seconds since epoch"* as expected, but rather an 18-digit long LDAP timestamp.
Fixes #6294
----
Enter …
> in_tail: fix st_mtime timestamp format

- plugins/in_node_exporter_metrics/ne_vmstat_linux.c
Vmstat metrics seems to be of counter types: https://github.com/torvalds/linux/blob/master/mm/vmstat.c
The goal of this MR is to change vmstat metrics type int the in_node_exporter_metrics from untyped to counter.
**Testing**
- [ N/A ] Example configuration file for the change
- [ N/A ] Debug log output from testing the change
- [  ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found
- [ N/A ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build. …
> in_node_exporter_metrics: fix set vmstat metrics as counter metrics

- plugins/in_cpu/cpu.c
Inlining the format string produces this warning:
format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘char (*)[8]’
`v_cpuid` is already a `char[8]`, so it can be passed directly.
Signed-off-by: Tobias Nießen <tniessen@tnie.de>
> in_cpu: fix pointer to v_cpuid

- plugins/in_emitter/emitter.c
- src/flb_chunk_trace.c
Use a ring buffer to send the trace chunks from the thread executing the trace to the emitter on the trace pipeline. This is done because `flb_start()` actually invokes the new pipeline on a separate thread.`
----
**Testing**
---- …
> trace: use ring buffers from the main thread to the trace pipeline.

- src/flb_upstream_ha.c
The extra parameters of an upstream were stored as cfl_variant, but retrieved as strings (char *) in out_forward.
This would lead to errors when using "Compress gzip" in an upstream configuration file for out_forward, for example:
[error] [output:forward:forward.0] invalid compress mode: ☺
Yes, I swear we really did have a smiley instead of "compress" by pure (bad) luck.
----
**Testing** …
> upstream_ha: Fixed extra parameters storage

- plugins/out_opentelemetry/opentelemetry.c
- plugins/out_opentelemetry/opentelemetry.h
- plugins/out_opentelemetry/opentelemetry_conf.c
Add GZIP compression option to opentelemetry output plugin. 
**Testing**
https://github.com/fluent/fluent-bit-docs/pull/939
> out_opentelemetry: add gzip compression

- .github/workflows/staging-release.yaml
- packaging/test-release-packages.sh
Minor improvement to release process to verify the version we're expecting is installed.
----
**Testing**
Checking for latest works:
```shell
$ VERSION_TO_CHECK_FOR=2.0.5 ./test-release-packages.sh 
...
Installation completed. Happy Logging!
Fluent Bit v2.0.5
Git commit: 
+ check_version /tmp/tmp.WAOUgMtLHG
+ [[ -n 2.0.5 ]]
+ local LOG_FILE=/tmp/tmp.WAOUgMtLHG
+ grep -q 2.0.5 /tmp/tmp.WAOUgMtLHG
+ rm -f /tmp/tmp.WAOUgMtLHG
...
$ echo $?
0
```
Failure case works:
```shell
$ VERSION_TO_CHECK_FOR=2.0.4 ./test-release-packages.sh
...
Installation completed. Happy Logging!
Fluent Bit v2.0.5
Git commit: 
+ check_version /tmp/tmp.RwYk6CfwuJ
+ [[ -n 2.0.4 ]]
+ local …
```
> packaging: add version check in release package tests

- src/aws/flb_aws_util.c
> aws: different user agent on windows vs linux

- cmake/windows-setup.cmake
> windows: enable ECS filter

- plugins/in_tcp/tcp_conn.c
> in_tcp: user friendly warn message for skipping records

- plugins/out_datadog/datadog.c
- plugins/out_datadog/datadog_conf.c
- plugins/out_datadog/datadog_remap.c
- plugins/out_datadog/datadog_remap.h
> out_datadog: fix/add error handling for all flb_sds calls

- include/fluent-bit/flb_input.h
- src/flb_downstream.c
This PR fixes an error in the downstream provider where it didn't properly distinguish between downstreams running in sync and async mode which resulted in `flb_downstream_conn_get` misappropriating the last coroutine handle set in the TLS variable (which when running in single thread mode is usually a dead or dying flush coroutine).
> downstream: misappropiated coroutine fix

- packaging/distros/debian/Dockerfile
Resolves typo in #6382 although this is not exposed in the release packages as they override the variable anyway - it only affects builds from source for Debian.
----
**Testing**
----
> dockerfiles: fix typo

- plugins/out_forward/forward.c
- plugins/out_forward/forward.h
This patch makes UDS connections thread specific to prevent threads from interfering with each other.
Additionally it can handle UDS servers going down momentarily or not being available when fluent-bit starts.
On a side note, the UDS connection was being set to non blocking mode which works fine mostly except when the output plugin needs to receive the ACK from the server so I had to change that because the neither flb_io_fd_write nor flb_io_fd_read really support async file descriptors so the output plugin was just writing stuff and wishing for the best...
A proper refactor of this output plugin is much needed, maybe it could be used as a case study to upgrade flb_upstream to support other transports.
> out_forward: fix concurrency issue when operating in UDS mode

- src/tls/flb_tls.c
There was a bug in flb_tls_session_create, flb_tls_net_write_async and flb_tls_net_read_async where they changed the connection registration in the event loop in order to get awakened to complete the desired operation but didn't restore the original registration status.
> tls: restore connection registration after async io operation

- .github/workflows/call-build-linux-packages.yaml
- .github/workflows/remove-release.yaml
- .github/workflows/staging-release.yaml
Addresses #6174 by switching to Ubuntu 22.04 for packaging as this provides `createrepo_c`. Packaging scripts already updated to support it.
----
**Testing**
https://github.com/fluent/fluent-bit/actions/runs/3515729290
Looks good: https://github.com/fluent/fluent-bit/actions/runs/3515729290/jobs/5891540361
----
> workflows: update packaging to remove Ubuntu 18 runners

- .github/workflows/unit-tests.yaml
Addresses #6174 and the soon-to-be removal of Ubuntu 18 runners.
----
**Testing**
https://github.com/fluent/fluent-bit/actions/runs/3515883866/jobs/5891709736
----
> workflows: update unit test runner OS

- tests/internal/parser.c
This patch is to fix below warnings.
```
[ 97%] Building C object tests/internal/CMakeFiles/flb-it-parser.dir/parser.c.o
/home/taka/git/fluent-bit/tests/internal/parser.c: In function ‘test_parser_time_lookup’:
/home/taka/git/fluent-bit/tests/internal/parser.c:228:67: warning: passing argument 5 of ‘flb_parser_time_lookup’ from incompatible pointer type [-Wincompatible-pointer-types]
228 |         ret = flb_parser_time_lookup(t->time_string, len, now, p, &tm, &ns);
|                                                                   ^~~
|                                                                   |
|                                                                   struct tm *
In file included from /home/taka/git/fluent-bit/tests/internal/parser.c:5: …
```
> tests: internal: parser: fix warnings

- tests/internal/CMakeLists.txt
- tests/internal/parser_logfmt.c
This patch is to add test code for parser_logfmt.
----
**Testing**
```
d$ valgrind --leak-check=full --show-leak-kinds=all bin/flb-it-parser_logfmt 
==20474== Memcheck, a memory error detector
==20474== Copyright (C) 2002-2017, and …
```
> tests: internal: parser_logfmt: add test for parser_logfmt

- plugins/filter_record_modifier/filter_modifier.c
- plugins/filter_record_modifier/filter_modifier.h
- tests/runtime/filter_record_modifier.c
This patch is to append UUID to each record.
Requested at #5571 
|Name|Description|
|---|---|
|uuid_key| If set, the plugin generates uuid per record.|
----
**Testing**
```
[INPUT]
Name dummy
[FILTER]
Match *
uuid_key uuid
[OUTPUT]
Name stdout
```
```
$ valgrind --leak-check=full bin/fluent-bit -c uuid.conf …
```
> filter_record_modifier: support uuid_key

- tests/runtime/out_tcp.c
This patch is to remove below warnings.
```
[ 87%] Building C object tests/runtime/CMakeFiles/flb-rt-out_tcp.dir/out_tcp.c.o
/home/taka/git/fluent-bit/tests/runtime/out_tcp.c: In function ‘flb_test_tcp_exit_workers’:
/home/taka/git/fluent-bit/tests/runtime/out_tcp.c:903:9: warning: unused variable ‘bytes’ [-Wunused-variable]
903 |     int bytes;
|         ^~~~~
/home/taka/git/fluent-bit/tests/runtime/out_tcp.c: In function ‘flb_test_tcp_exit_no_workers’:
/home/taka/git/fluent-bit/tests/runtime/out_tcp.c:948:9: warning: unused variable ‘bytes’ [-Wunused-variable]
948 |     int bytes;
|         ^~~~~
[ 87%] Linking C executable ../../bin/flb-rt-out_tcp
```
----
**Testing**
Before we can approve your change; please submit …
> tests: runtime: out_tcp: remove unused variables

- plugins/out_tcp/tcp.c
- plugins/out_tcp/tcp.h
- plugins/out_tcp/tcp_conf.c
add new `raw_message_key` option, this option allows to send records raw content of a specific key, this mode is incompatible with format. Usage:
__client__
```
fluent-bit -i dummy -p "dummy={\"key\": \"abc\", \"real\": \"good\"}" -o tcp -p port=55441 -p "raw_message_key=\$real"
```
__server__
```
nc -l 55441
```
----
> out_tcp: new 'raw_message_key' option

- packaging/server/publish-all.sh
Addresses #6442 failure with JSON schema publishing. 
Command ran manually to confirm on release server.
----
**Testing**
----
> packaging: handle change in location of JSON schema for release

- packaging/server/aptly.conf
- packaging/server/create-aptly-repo.sh
Resolves #6442.
----
**Testing**
```shell
$ docker run --rm -it debian:bookworm /bin/sh -c 'apt-get update && apt-get install -y sudo gpg curl && curl https://raw.githubusercontent.com/fluent/fluent-bit/master/install.sh | sh'
...
Preparing to unpack .../fluent-bit_2.0.6_amd64.deb ...
Unpacking fluent-bit (2.0.6) ...
Setting up libyaml-0-2:amd64 (0.2.5-1) ...
Setting up libpq5:amd64 (15.1-1) ...
Setting up fluent-bit (2.0.6) ...
Processing triggers for libc-bin (2.36-4) ...
Installation completed. Happy Logging!
```
----
> packaging: add extra repo creation details

- include/fluent-bit/flb_output.h
- include/fluent-bit/flb_task.h
- plugins/out_cloudwatch_logs/cloudwatch_logs.c
- src/flb_engine.c
- src/flb_engine_dispatch.c
- src/flb_output.c
- src/flb_task.c
>Master branch PR https://github.com/fluent/fluent-bit/pull/6413
Please leave review comments on this 1.9x branch.
Implement a synchronous task scheduler plugin option allowing for the cloudwatch_logs plugin to opt into to allow for migrate to the Async Network stack.
Due to limitations of the CloudWatch API in processing PutLogEvents network requests synchronously, Fluent Bit sends data to CloudWatch using a less supported “synchronous” networking stack. This stack is prone to indefinite hangs and segfaults and only works well when used with a fine tuned configuration.
See: https://github.com/fluent/fluent-bit/issues/6140 and https://github.com/fluent/fluent-bit/issues/6329
While at first we tried to resolve the networking hang issues found in the synchronous network stack by adding …
> core: minimal synchronous scheduler

- plugins/out_s3/s3.c
- plugins/out_s3/s3.h
- plugins/out_s3/s3_store.c
----
**Testing**
https://github.com/fluent/fluent-bit-docs/pull/956/files
----
> out_s3: add store_dir_limit_size to limit S3 disk usage

- .github/workflows/staging-release.yaml
Resolves #6466 by ensuring we do not overwrite `latest` tags for 1.9 container releases.
----
**Testing**
----
> workflows: ensure 1.9 containers do not update latest tag

- init/systemd.in
This PR provides a more general way to give environment variables (e.g.`AWS_CONFIG_FILE`) for fluent-bit running on systemd without rewriting unit files.
environment variables are to be sourced from these files if exists.
* `/etc/default/<FLB_OUT_NAME>` (Debian based system)
* `/etc/sysconfig/<FLB_OUT_NAME>` (Others)
The file is rendered with CMake. The results of the my local build are:
```
[Unit]
Description=TD Agent Bit
Documentation=https://docs.fluentbit.io/manual/
Requires=network.target
After=network.target
[Service]
Type=simple
EnvironmentFile=-/etc/default/td-agent-bit
EnvironmentFile=-/etc/sysconfig/td-agent-bit
ExecStart=/opt/td-agent-bit/bin/td-agent-bit -c //etc/td-agent-bit/td-agent-bit.conf
Restart=always
[Install]
WantedBy=multi-user.target
```
---- …
> init: systemd: allow to set environment variables from file

- plugins/in_syslog/syslog.c
- plugins/in_syslog/syslog.h
- plugins/in_syslog/syslog_prot.c
implements #6476 by adding a new option called `raw_message_key`, based on #6477.  e.g:
```
[SERVICE]
parsers_file parsers.conf
[INPUT]
name            syslog
mode            udp
parser          syslog-rfc5424
raw_message_key raw
[OUTPUT]
name   stdout
match  *
format json_lines
```
testing a message:
```json
{
"date": 1669778120.283024,
"pri": "14",
"time": "2022-11-29T21:15:20.283024-06:00",
"host": "monox-2.lan",
"ident": "syslogtest",
"pid": "23551",
"msgid": "some_unique_msgid",
"extradata": "-",
"message": "This is an interesting message",
"raw": "<14>1 2022-11-29T21:15:20.283024-06:00 monox-2.lan syslogtest 23551 some_unique_msgid - This is an interesting message"
}
```
----
**Testing**
Before we can approve …
> in_syslog: new raw_message_key option

- src/tls/openssl.c
This patch is to print errno when openssl API returns `SSL_ERROR_SYSCALL`.
There are several issues that `SSL_ERROR_SYSCALL`(=5) returned. #6431 #5705
```
[2022/11/21 11:57:45] [error] [tls] error: error:00000005:lib(0):func(0):DH lib
```
```
$ grep SSL_ERROR_SYSCALL /usr/include/openssl/*
/usr/include/openssl/ssl.h:# define SSL_ERROR_SYSCALL               5/* look at error stack/return
```
https://www.openssl.org/docs/man3.1/man3/SSL_get_error.html
```
SSL_ERROR_SYSCALL
Some non-recoverable, fatal I/O error occurred. The OpenSSL error queue may contain more information on the error. 
For socket I/O on Unix systems, consult errno for details. 
If this error occurs then no further I/O operations should be performed on the connection and SSL_shutdown() must not be called.
This value can …
```
> openssl: add SSL_ERROR_SYSCALL case

- plugins/filter_wasm/filter_wasm.c
- src/wasm/flb_wasm.c
This patch is to fix some memory errors when fluent-bit fails to load wasm.
----
**Testing**
```
[INPUT]
Name dummy
[FILTER]
Name wasm
Match *
Wasm_Path a
Function_Name go_filter
[OUTPUT]
Name stdout
```
```
$ valgrind --leak-check=full bin/fluent-bit -c wasm.conf 
==14189== …
```
> wasm: Fix wasm load error

- include/fluent-bit/flb_input.h
- include/fluent-bit/flb_output.h
- include/fluent-bit/flb_plugins.h.in
- src/flb_output.c
- src/flb_plugin_proxy.c
- src/proxy/go/go.c
- src/proxy/go/go.h
Change proxy cb_exit to correctly pass right ctx to Go callback FLBPluginExitCtx and remove global plugin related memory freeing code from this method. Add new method cb_destroy that is correctly called when whole plugin is unregistered to free up whole plugin related memory. 
Fix https://github.com/fluent/fluent-bit-go/issues/49 in fluent-bit-go repository.
Wrong behavior with code from current master and latest stable branch:
> 2022/11/28 14:59:14 [multiinstance] Exit called for id: dummy_metrics
2022/11/28 14:59:14 [multiinstance] Unregister called
2022/11/28 14:59:14 [multiinstance] Unregister called
double free or corruption (out)
./multiold.sh: line 7: 1092320 Aborted                 ./bin/fluent-bit-orig -c test_multi/fluent-bit.conf
---- …
> proxy: fix memory bugs when use same golang output plugin multiple times

- .github/workflows/staging-release.yaml
Will create a valid Github release as soon as the release process is successful - this will link out to the announcement.
----
**Testing**
----
> workflows: automatically create release during the release process

- plugins/out_kafka/kafka.c
Fix segmentation fault in out_kafka.
Stacktrace:
```
Nov 23, 2022 @ 00:53:23.362 | [2022/11/22 15:53:23] [engine] caught signal (SIGSEGV)
-- | --
| Nov 23, 2022 @ 00:53:23.473 | #0  0xaaaad87abb10      in  produce_message() at plugins/out_kafka/kafka.c:189
| Nov 23, 2022 @ 00:53:23.473 | #1  0xaaaad87ac50b      in  cb_kafka_flush() at plugins/out_kafka/kafka.c:483
| Nov 23, 2022 @ 00:53:23.473 | #2  0xaaaad84a4a17      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:519
| Nov 23, 2022 @ 00:53:23.473 | #3  0xaaaad8ede3fb      in  co_switch() at lib/monkey/deps/flb_libco/aarch64.c:133
| Nov 23, 2022 @ 00:53:23.473 | #4  0xffffffffffffffff  in  ???() at ???:0
```
Fix #6451 
Thank you @Jinmo , for kindly helping me troubleshooting !
----
**Testing**
We tested this change by …
> out_kafka: fix segmentation fault issue while produce_message

- tests/runtime/in_tail.c
This patch is to remove unused variable.
```
Consolidate compiler generated dependencies of target flb-rt-in_tail
[ 81%] Building C object tests/runtime/CMakeFiles/flb-rt-in_tail.dir/in_tail.c.o
/home/taka/git/fluent-bit/tests/runtime/in_tail.c: In function ‘wait_with_timeout’:
/home/taka/git/fluent-bit/tests/runtime/in_tail.c:290:13: warning: unused variable ‘ret’ [-Wunused-variable]
290 |     int64_t ret = 0;
|             ^~~
[ 81%] Linking C executable ../../bin/flb-rt-in_tail
```
----
**Testing** …
> tests: runtime: in_tail: remove unused var

- CMakeLists.txt
- cmake/FindLibEdit.cmake
Since LLVM 15, libedit will be linked with cmake functionality. We have to find out where libedit is installed in the building boxes.
see: https://reviews.llvm.org/rG9426358ea1fa84bac7b85f550f9efce12349c9da
----
**Testing**
----
> build: wamrc: Make buildable with LLVM 15

- dockerfiles/Dockerfile
Signed-off-by: Christian Norbert Menges <christian.norbert.menges@sap.com>
Update systemd to v251.3, to fix CVE-2022-3821. The severity of this issue is rated as moderate and I'm not sure whether this code is actually used by fluent-bit, however, security scanners complain about the old, unfixed version.
The underlying bug was fixed in https://github.com/systemd/systemd/pull/23933 and ported to the Debian fork of systemd in commit https://salsa.debian.org/systemd-team/systemd/-/commit/3e11e1771a3c121d5036232ea7c1b0b51dd508d3 and tagged with https://salsa.debian.org/systemd-team/systemd/-/tags/upstream%2F251.3. This version is only available in the bullseye-backports package repo, which had to be added to `sources.list`.
----
Enter `[N/A]` in the box, if an item is not applicable to your …
> dockerfiles: update systemd to v251.3

- SECURITY.md
remove 1.8 and 1.9
Signed-off-by: José Lecaros <lecaros@calyptia.com>
remove 1.8 and 1.9
> security policy: update supported versions

- plugins/filter_throttle/throttle.c
When running with Valgrind with the throttle filter, you can see a warning:
```
==1== Thread 4:
==1== Conditional jump or move depends on uninitialised value(s)
==1==    at 0x34E701: time_ticker (throttle.c:84)
==1==    by 0x4854EA6: start_thread (pthread_create.c:477)
==1==    by 0x4FBDA2E: clone (clone.S:95)
==1==  Uninitialised value was created by a heap allocation
==1==    at 0x483877F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1==    by 0x34E58A: flb_malloc (flb_mem.h:79)
==1==    by 0x34EAC7: cb_throttle_init (throttle.c:163)
==1==    by 0x2394B5: flb_filter_init_all (flb_filter.c:480)
==1==    by 0x24C585: flb_engine_start (flb_engine.c:666)
==1==    by 0x22B9B4: flb_lib_worker (flb_lib.c:626)
==1==    by 0x4854EA6: start_thread …
```
> filter_throttle: Fix print_status being partially uninitialized

- src/flb_input_chunk.c
The struct input_chunk_raw definition does not need to be conditional on FLB_IN_STORAGE_BACKLOG
Relates to one of the build problems mention in #6464
----
**Testing** …
> build: input_chunk_raw does not depend on FLB_IN_STORAGE_BACKLOG

- plugins/custom_calyptia/calyptia.c
Concatenate values from the configuration as strings instead of fmt strings via flb_sds_printf. This avoids issues where values have format strings in them.
----
**Testing**
----
> calyptia: concatenate configuration as raw strings.

- plugins/out_opensearch/opensearch.c
- tests/runtime/out_opensearch.c
Add tests to make sure the combination of using an `index` with record accessor in combination with either  `id_key` or `generate_id` does not result in generating a packet with an index of '(null)'.
----
**Testing**
----
> opensearch: fix '(null)' index when using record accessor and id_key/generate_id.

- .github/workflows/call-build-images.yaml
- .github/workflows/staging-release.yaml
Keyless container signing is currently blocking and timing out waiting for user authentication. It also needs to use image digests.
The fluentd-aggregator-image workflow uses keyless signing and works fine so adopting the necessary changes here from @stevehipwell:
https://github.com/fluent/fluentd-aggregator-docker-image/blob/a7057e9c4626c3ffef6346df4dead2e8196bdcd1/.github/workflows/release.yaml#L11
----
**Testing**
---- …
> workflows: tweak keyless container signing

- plugins/custom_calyptia/calyptia.c
- tests/runtime/CMakeLists.txt
- tests/runtime/custom_calyptia_test.c
Fix addressing for the call to `flb_sds_cat_safe`.
----
**Testing**
----
> calyptia: fix segfault when concatenating custom configuration.

- include/fluent-bit/flb_parser.h
- src/flb_parser.c
- src/flb_parser_logfmt.c
- src/multiline/flb_ml_parser_cri.c
- src/multiline/flb_ml_parser_docker.c
- tests/internal/fuzzers/engine_fuzzer.c
- tests/internal/fuzzers/parse_json_fuzzer.c
- tests/internal/fuzzers/parse_logfmt_fuzzer.c
- tests/internal/fuzzers/parse_ltsv_fuzzer.c
- tests/internal/fuzzers/parser_fuzzer.c
- tests/runtime/filter_parser.c
To allow a gradual move towards logfmt and otel messages, we need to enable logfmt parsing in a way that does not try to parse non-logfmt messages. Unlike the json parser, which has an easy time rejecting non-json messages, the logfmt parser will hapily accept any log messages and parse them into something quite unusable.
By making it possible (but not required) that all items in a logfmt message have a value, we give the logfmt parser the capability to reject message and enable a gradual move towards logfmt messages.
We've been running with this (in a different form, as a parser that always rejects lines with value-les kesy) in production for over a year, and I can say it's been the only way to get people to adopt structured logging. In an environment where random libraries can throw …
> parser: logfmt: Allow the logfmt parser to reject messages that have keys without values

- include/fluent-bit/flb_stream.h
When an output plugin runs with in multi worker mode the upstream is set to thread safe mode which means flb_stream_acquire_lock and flb_stream_release_lock are used to manipulate the underlying mutex.
There was an error in flb_stream_acquire_lock where the wait_flag condition was inverted and because of that, a second thread could unknowingly access the resources while they shouldn't be able to.
An unrelated but somewhat similar in nature error could be present in flb_upstream_conn_get since the upstream lock is acquired inside the keepalive available queue loop so the locking code / strategy should be reviewed.
> stream: fixed an condition that caused concurrency issues

- tests/internal/parser_json.c
- tests/internal/parser_logfmt.c
- tests/internal/parser_ltsv.c
- tests/internal/parser_regex.c
- tests/runtime/custom_calyptia_test.c
- tests/runtime/filter_parser.c
Fix CI bugs introduced by the two latest merges.
----
**Testing**
----
> tests: fix unit tests for parsers and calyptia custom.

- src/config_format/flb_cf_fluentbit.c
Currently fluent-bit exit silently when it fails to load config file.
This patch is to log it.
```
[2022/12/17 14:33:23] [error] [/home/taka/git/fluent-bit/src/config_format/flb_cf_fluentbit.c:290 errno=2] No such file or directory
[2022/12/17 14:33:23] [error] file=/home/taka/git/fluent-bit/build/issues/6547/aaa
```
----
**Testing** …
> cf_fluentbit: print config file load error

- plugins/out_prometheus_exporter/prom_http.c
Fixes #6554 
This patch is to add following content-type to a response of out_prometheus_exporter.
```
Content-Type: text/plain; version=0.0.4
```
----
**Testing**
```
#
#
#
[SERVICE]
log_level       info
[INPUT]
name            fluentbit_metrics
tag             internal_metrics
[OUTPUT]
name            prometheus_exporter
match           internal_metrics
host …
```
> out_prometheus_exporter: add content-type(#6554)

- plugins/in_windows_exporter_metrics/we_cpu.c
We should compare via fabsf and FLB_EPLISON for two float values. Otherwise, we encountered missing metrics for the newer Windows platform.
This is because floating point values cannot compare directly in C.
----
**Testing**
----
> in_windows_exporter_metrics: cpu: Don't compare float values directly

- tests/internal/fuzzers/ctrace_fuzzer.c
Extend the fuzzing target for ctrace lib so it hits encoding logic as well.
----
**Testing**
- [N/A] …
> tests: internal: fuzzers: extend ctrace fuzzer

- plugins/out_s3/s3.c
> out_s3: always use sync IO mode

- plugins/in_tail/tail_file.c
When consuming data from a file, fstat() is being invoked twice upon reading the content and then adjusting the internal counters, this patch simply remove the first check and let the adjust_counters() function perform the fstat().
This patch also removes an unused function.
> in_tail: remove extra fstat() syscall and remove unused function

- include/fluent-bit/flb_aws_util.h
- plugins/out_cloudwatch_logs/cloudwatch_logs.c
- src/aws/flb_aws_util.c
Fixes https://github.com/aws/aws-for-fluent-bit/issues/503
----
**Testing**
----
> aws: fix extra_user_agent type

- plugins/out_kafka/kafka.c
- plugins/out_kafka/kafka_config.c
- plugins/out_kafka/kafka_config.h
https://github.com/fluent/fluent-bit/issues/6132
This patch is to support nanosecond timestamp format `iso8601_ns`.
I want a user feed back since I'm not familiar with kafka.
----
**Testing**
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including …
> out_kafka: support iso8601_ns format

- plugins/out_splunk/splunk.c
- src/flb_engine.c
changes:
- engine now log FLB_ERROR from output plugins
- out_splunk: print as a log the chunks that could not be processed (e.g: HTTP 400 error)
----
> tiger: 1.8.15: 20221220

- plugins/out_stackdriver/stackdriver.c
This change makes it so we don't attempt any request to Cloud Logging if we know that an expired token is being used.
> stackdriver: cache token expiration and use it when using cached tokens

- CMakeLists.txt
Fixes #6519 
This patch is to fix to use `FLB_DEFINITION` to define `FLB_HAVE_*`.
`FLB_HAVE_CHUNK_TRACE` should be defined in flb_info.h.
However it isn't defined since it is defined using `add_definitions`.
It causes struct size mismatch between fluent-bit and fluent-bit-plugin since the size will be changed `FLB_HAVE_CHUNK_TRACE` is defined or not.
----
**Testing**
If this is a change to packaging of containers or native binaries then please confirm it works …
> CMakeLists: use FLB_DEFINTION for FLB_HAVE_*(#6519)

- src/flb_config.c
Some fields are not checked for NULL before used in cleanup functions. These issues are found locally following some modifications of the fuzzing set up that forces malloc to error at certain times. The new fuzzer set up will be pushed once I have fixed the issues it finds following short local runs.
----
**Testing** …
> config: add safety checks in config_exit

- src/flb_config.c
flb_ml_init can fail and this ensures we check the error code.
----
**Testing**
- [N/A] …
> config: bail if multiline failed initialization

- src/flb_config.c
Fixes two leaks due to missing config cleanup.
----
**Testing**
- [N/A] Documentation required for …
> config: fix two leaks

- src/flb_parser.c
If it's not freed leaks may happen.
----
**Testing** …
> parser: free time_fmt_full during interim cleanup

- src/flb_parser.c
In the event flb_strdup fails we need to bail and cleanup.
----
**Testing** …
> parser: fix two leaks

- tests/internal/utils.c
This patch is to add test cases for `flb_utils_split`.
It is to check regressions of the function before merging https://github.com/fluent/fluent-bit/pull/6387
----
**Testing**
```
$ valgrind --show-leak-kinds=all --leak-check=full …
```
> tests: internal: utils: add test case for flb_utils_split

- plugins/out_s3/s3.c
> out_s3: in 2.0 series default to on/true for Preserve_Data_Ordering

- plugins/filter_ecs/ecs.c
- plugins/filter_ecs/ecs.h
- tests/runtime/filter_ecs.c
> filter_ecs: fix multiple bugs and make retries configurable

- include/fluent-bit/flb_log.h
- include/fluent-bit/flb_output.h
- include/fluent-bit/flb_output_plugin.h
- include/fluent-bit/flb_worker.h
- src/flb_log.c
- src/flb_output.c
- src/flb_worker.c
- tests/internal/CMakeLists.txt
- tests/internal/log.c
The following PR implements a new option called `log_suppress_interval` that allows the suppressing of log messages from output plugins that look similar within  an interval of time.
The current missing implementation is to allow dynamic config if the interval since internally is set to 10 seconds, but to enable it and test it, it must be set in the configuration, e.g:
```
[OUTPUT]
name http
match *
log_suppress_interval 10s
```
----
> log: implement log suppress feature

- src/config_format/flb_config_format.c
- src/flb_input_chunk.c
- tests/internal/log.c
- tests/runtime/core_chunk_trace.c
- tests/runtime/filter_kubernetes.c
This patch is to solve unused variable warnings.
- tests/internal/log.c
- src/flb_input_chunk.c
- src/config_format/flb_config_format.c
- tests/runtime/core_chunk_trace.c
- tests/runtime/filter_kubernetes.c
```
[ 94%] Building C object tests/internal/CMakeFiles/flb-it-log.dir/log.c.o
/home/taka/git/fluent-bit/tests/internal/log.c: In function ‘cache_one_slot’:
/home/taka/git/fluent-bit/tests/internal/log.c:90:33: warning: unused variable ‘entry’ [-Wunused-variable]
90 |     struct flb_log_cache_entry *entry;
|                                 ^~~~~
```
----
**Testing**
If this is a change to …
> tests: internal: log: remove unused variable

- packaging/server/create-aptly-repo.sh
- packaging/server/publish-all.sh
Resolves an issue with publishing for the new Aptly Bookworm repo.
----
**Testing**
Confirmed to work.
----
> packaging: fix server publishing for Debian Bookworm

- .github/workflows/staging-release.yaml
- install.sh
- packaging/appveyor-download.sh
- packaging/server/publish-manual.sh
- packaging/test-release-packages.sh
- packaging/update-source-packages.sh
Various updates to handle the new server approach with a bucket.
Added automated AppVeyor download as well.
----
**Testing**
----
> packaging: more changes for switchover

- src/config_format/flb_config_format.c
> config_format: fix memory leak

- src/aws/flb_aws_credentials.c
The memory is currently non-nullified since malloc is used. However, shortly after malloc is used `flb_aws_credentials_destroy` is called in the event an error occurs. `flb_aws_credentials_destroy` will treat some of the memory in the malloced memory as pointers and use the memory as arguments to `free` if the given memory is non-null. This causes issues since non-null memory returned by malloc is not guaranteed to be safe to free. To avoid this use `calloc` instead as `flb_aws_credentials_destroy` will not call `free` on NULL bytes.
----
**Testing**
- [N/A] Example configuration file for …
> aws: fix freeing arbitrary memory

- src/flb_input_chunk.c
When testing conditions to see if too many chunks are up compare max_chunks_up to total_chunks_up instead of total_chunks. This should improve handling of cases where we reach fluent-bits set buffer limits.
This fixes issue #6663.
----
**Testing**
----
> input: compare max_chunks_up to total_chunks_up not total_chunks.

- install.sh
If FLUENT_BIT_PACKAGES_URL is not provided, RELEASE_KEY will fail validation
`error: /fluentbit.key: import read failed(2).`
* Base default value for RELEASE_KEY off RELEASE_URL which has a default. FLUENT_BIT_PACKAGES_URL is optional
Fixes #6679 
----
**Testing**
> install: Base RELEASE_KEY default off RELEASE_URL which will have a default

- .github/workflows/pr-install-script.yaml
- install.sh
- packaging/test-release-packages.sh
Resolves various problems introduced on some platforms and also introduces a PR workflow to verify it.
- Incorrect usage of bash specific test syntax
- Multiple base urls fail if not available for Yum targets
```shell
$ ./packaging/test-release-packages.sh
...
================================
Fluent Bit Installation Script 
================================
This script requires superuser access to install packages.
You will be prompted for your password by sudo.
sh: 31: [[: not found
sh: 35: sudo: not found
...
===============================
Fluent Bit Installation Script 
================================
This script requires superuser access to install packages.
You will be prompted for your password by sudo.
[fluent-bit]
name = Fluent Bit
baseurl = …
```
> install: resolve various niggles

- install.sh
- packaging/test-release-packages.sh
Resolves #6692 by adding options to specify version to install as well as disabling install entirely (or adding some other prefix command).
----
**Testing**
Verified we can install version 2.0.6 (as indicated in the original issue):
```shell
$ export INSTALL=https://raw.githubusercontent.com/fluent/fluent-bit/1db6cc0de8ce8f79a0188b6769e5178c3e1d1297/install.sh
$ export VERSION_TO_CHECK_FOR=2.0.6
$ export FLUENT_BIT_RELEASE_VERSION=2.0.6
./packaging/test-release-packages.sh
...
Setting up fluent-bit (2.0.6) ...
Processing triggers for libc-bin (2.31-13+deb11u5) ...
Installation completed. Happy Logging!
Fluent Bit v2.0.6
...
```
Also verified it installs the latest (2.0.8) when not set.
---- …
> install: specify version to install script

- src/flb_signv4.c
`flb_kv_item_create_len` may fail and this should be handled.
----
**Testing** …
> signv4: handle error case

- include/fluent-bit/flb_mem.h
- tests/internal/fuzzers/base64_fuzzer.c
- tests/internal/fuzzers/config_fuzzer.c
- tests/internal/fuzzers/config_map_fuzzer.c
- tests/internal/fuzzers/config_random_fuzzer.c
- tests/internal/fuzzers/ctrace_fuzzer.c
- tests/internal/fuzzers/engine_fuzzer.c
- tests/internal/fuzzers/filter_stdout_fuzzer.c
- tests/internal/fuzzers/flb_json_fuzzer.c
- tests/internal/fuzzers/http_fuzzer.c
- tests/internal/fuzzers/msgpack_parse_fuzzer.c
- tests/internal/fuzzers/msgpack_to_gelf_fuzzer.c
- tests/internal/fuzzers/multiline_fuzzer.c
- tests/internal/fuzzers/pack_json_state_fuzzer.c
- tests/internal/fuzzers/parse_json_fuzzer.c
- tests/internal/fuzzers/parse_logfmt_fuzzer.c
- tests/internal/fuzzers/parse_ltsv_fuzzer.c
- tests/internal/fuzzers/parser_fuzzer.c
- tests/internal/fuzzers/record_ac_fuzzer.c
- tests/internal/fuzzers/signv4_fuzzer.c
- tests/internal/fuzzers/strp_fuzzer.c
- tests/internal/fuzzers/utils_fuzzer.c
This modifies the logic for making flb_malloc failable with more control in the fuzzer for how often it should fail. The signv4 fuzzer sets the necessary flb_malloc_mod param to a value dependent on the fuzz-data, which means the value can be arbitrary. The consequence is that eventually we should have all flb_mallocs reached by the signv4 fuzzer tested for erroneous malloc calls. From local runs, this has led to fixes e.g.:
- https://github.com/fluent/fluent-bit/pull/6654
- https://github.com/fluent/fluent-bit/pull/6652
- https://github.com/fluent/fluent-bit/pull/6653
- https://github.com/fluent/fluent-bit/pull/6655
Eventually, the same change will be applied to all the other fuzzers but am taking them one by one to avoid spamming the oss-fuzz log.
Signed-off-by: David Korczynski …
> tests: internal: fuzzers: make malloc failable

- src/flb_signv4.c
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55269
----
**Testing**
- [N/A] …
> signv4: clean up if failed split string

- .github/workflows/staging-release.yaml
- packaging/test-release-packages.sh
- packaging/update-repos.sh
Fixes #6732 to ensure the bucket repo data matches the legacy server for Debian Bullseye.
----
**Testing**
Spun up new server.
Sync'd bucket.
Checked the files (repeated for `Label`):
```shell
$ find bucket/ -name "Release" -exec cat {} \;|grep Origin
Origin: . bookworm
Origin: . bookworm
Origin: . bookworm
Origin: . stretch
Origin: . stretch
Origin: . stretch
Origin: . stretch
Origin: . stretch
Origin: . stretch
Origin: . stretch
Origin: . buster
Origin: . buster
Origin: . buster
Origin: . jessie
Origin: . jessie
Origin: . jessie
Origin: . jessie
Origin: . bullseye
Origin: . bullseye
Origin: . bullseye
```
Ran the update-repos.sh script in this PR with appropriate …
> packaging: resolve legacy Bullseye setup issue

- packaging/distros/debian/Dockerfile
- packaging/distros/ubuntu/Dockerfile
Signed-off-by: Nikita Kozlovsky <nikitka@gmail.com>
This pull request adds SASL mechanisms support. I added pkg-config as a dependency, because without it librdkafka's cmake unable to find libsasl2 and disables SASL support. 
Without pkg-config I got error `failed to create producer: No provider for SASL mechanism SCRAM-SHA-512: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN`. After I've added pkg-config and have recompiled package error is gone and I've successfully connected to kafka with SCRAM-SHA-512 SASL mechanism.
I think this pull requests fixes #632.
----
**Testing**
- [N/A] Example configuration …
> packaging: enable kafka SASL mechanisms support for Debian and Ubuntu

- packaging/distros/raspbian/Dockerfile
Signed-off-by: Nikita Kozlovsky <nikitka@gmail.com>
Add pkg-config as a dependency for the Raspbian builds, same as PR #6734. 
Addresses #632
----
**Testing**
----
> packaging: add pkg-config dependency for the Raspbian builds

- plugins/in_forward/fw_prot.c
The leak is huge: 8k per ACK sent.
Signed-off-by: Benoît GARNIER <bunch@orange.fr>
----
**Testing**
----
> in_forward: fixed memory leak when sending ACK

- packaging/distros/amazonlinux/Dockerfile
- packaging/distros/centos/Dockerfile
- packaging/distros/ubuntu/Dockerfile
I've found out that we don't have `cyrus-sasl-devel` dependency for CentOS targets, also I have added `libsasl`, `openssl` and `pkg-config` dependencies for Ubuntu 16.04. And I have added zlib-dev for CentOS and Amazon Linux targets for enabling GZIP support in librdkafka (Debian and Raspbian targets already had `zlib-1g-dev` dependency). 
I've checked that libfluent-bit.so in all x64 builds contains substring "CMAKE GNU GNU PKGCONFIG HDRHISTOGRAM ZLIB LIBDL PLUGINS SSL SASL_SCRAM SASL_OAUTHBEARER SASL_CYRUS C11THREADS CRC32C_HW SNAPPY SOCKEM". I think now we have the same set of enabled librdkafka features for every build target. I hope that arm64 targets fine too because they have the same package list as x64.
Addresses #632, #6086 
---- …
> packaging: librdkafka SASL_SCRAM and GZIP support on all targets

- src/tls/openssl.c
Quick one-line fix that I stumbled upon accidentally.
----
**Testing**
- …
> tls: add missing mutex unlock

- lib/monkey/mk_core/external/winpthreads.c
> lib: monkey: Upgrade to b096cd6063b5d058caac53bade70c851f8672038

- include/fluent-bit/flb_aws_util.h
- plugins/out_kinesis_firehose/firehose_api.c
- plugins/out_kinesis_streams/kinesis_api.c
- src/aws/flb_aws_util.c
----
**Testing**
```
[INPUT]
Name                         forward
Listen                       0.0.0.0
Port                         24224
[OUTPUT]
Name                         kinesis_streams
Match                        *
region                       us-east-1
stream                       test-clay-firehose
time_key                     @timestamp
time_key_format              %Y-%m-%dT%H:%M:%S.%3N.%L.%L
```
***Normal time_key_format***
```
[INPUT]
Name                         forward
Listen                       0.0.0.0
Port                         24224
[OUTPUT]
Name                         kinesis_streams
Match                        * …
```
> flb_aws_util: added function flb_aws_strftime_precision for time output

- plugins/out_s3/s3.c
- plugins/out_s3/s3_store.c
- plugins/out_s3/s3_store.h
Signed-off-by: Clay Cheng <claychen@amazon.com>
----
**Testing**
```
[OUTPUT]
Name s3
Match *
bucket clay-s3-timestamp
region us-east-1
total_file_size 1M
upload_timeout 1m
use_put_object On
```
***Upload timeout + put object used***
```
[INPUT]
Name                         forward
Listen                       0.0.0.0
Port                         24224
[OUTPUT]
Name s3
Match *
bucket s3-time-test
region us-east-1
total_file_size 50M
retry_limit 2
upload_timeout 10s
```
```
{
"generator": {
"name": "basic",
"config": {
"contentLength": 1000
}
},
"datajet": {
"name": "forward",
"config": {
"batchSize": 1,
"timeOffset": -100
}
},
"stage": { …
```
> out_s3: updated for getting upload time from timestamp.

- plugins/out_opentelemetry/opentelemetry.c
Remove an invalid free and fix a memory leak.
This fixes #6720.
----
**Testing**
----
> out_opentelemetry: fix memory leak and invalid free

- include/fluent-bit/flb_upstream_node.h
- src/flb_upstream_ha.c
- src/flb_upstream_node.c
Some temporaries were not freed, and some allocation strings were reallocated and freed once.
Signed-off-by: Benoît GARNIER <bunch@orange.fr>
----
**Testing**
----
> upstream: fixed memory leaks in configuration

- src/flb_input_chunk.c
This is a bug related to: https://github.com/fluent/fluent-bit/issues/6663
----
**Testing**
----
> input_chunk: use total_chunks_up in overlimit warn message

- tests/internal/network.c
With no IPv6 supported environment, the current implementation causes infinite loop to wait ev events for network testing. We should prevent such protocol glitching issue on test to prevent stucking test cases.
----
**Testing**
----
> network: test: internal: Prevent Infinite loop for no IPv6 environment

- src/flb_input_chunk.c
> input_chunk: info level instead of debug for chunk removal msg

- plugins/out_datadog/datadog.c
This patch is a port of the draft PR #6750
> out_datadog: fix buffer resize logic (#6750)

- tests/internal/log.c
This patch tries to fix following test error.
https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/45867890/job/u6f3mqnfwf2l45fd#L3761
```
31/38 Test #31: flb-it-log .......................***Failed   20.23 sec
Test cache_basic_timeout...                     
------------------------
[ FAILED ]
log.c:60: Check ret_1 == FLB_TRUE... failed
log.c:61: Check ret_2 == FLB_TRUE... failed
log.c:64: Check ret_1 == FLB_FALSE... failed
log.c:65: Check ret_2 == FLB_FALSE... failed
log.c:68: Check ret_1 == FLB_TRUE... failed
log.c:69: Check ret_2 == FLB_TRUE... failed
log.c:76: Check ret_1 == FLB_FALSE... failed
log.c:79: Check ret_2 == FLB_FALSE... failed
Test cache_one_slot...                          
[ OK ]
FAILED: 1 of 2 unit tests has failed.
```
The test checks at the 5th second to …
> tests: internal: log: make cache_basic_timeout more stable

- include/fluent-bit/flb_http_server.h
- include/fluent-bit/http_server/flb_hs.h
- src/flb_metrics_exporter.c
- src/http_server/CMakeLists.txt
- src/http_server/api/v2/CMakeLists.txt
- src/http_server/api/v2/metrics.c
- src/http_server/api/v2/metrics.h
- src/http_server/api/v2/register.c
- src/http_server/api/v2/register.h
- src/http_server/flb_hs.c
The following PR, introduces the new endpoint `/api/v2/` which exposes by default the internal metrics of Fluent Bit:
| endpoint | description | 
|--|--|
| `/api/v2/metrics` | expose internal metrics in text format |
| `/api/v2/metrics/prometheus` | expose internal metrics in Prometheus text format |
note: there is no changes to the `/api/v1` endpoint, this is just the beginning of a next version, both will be available. 
----
> http_server: add new /api/v2 endpoint with new metrics

- plugins/out_s3/s3.c
> out_s3: fix logic in log_key warn message

- CMakeLists.txt
Fluent-bit is mostly written in C,
so don't require CXX in the top-level project.
Signed-off-by: Thomas Devoogdt <thomas.devoogdt@barco.com>
Seen while debugging fluent-bit on https://github.com/buildroot/buildroot/commit/6a0f7c39bcb48fc13aa2ce3fc4996baf1be66483 with c-only toolchains.
https://patchwork.ozlabs.org/project/buildroot/patch/20230130121930.3472747-1-thomas@devoogdt.com/
Fluent-bit is mainly written in C,
so don't require CXX in the top-level project.
https://cmake.org/cmake/help/latest/command/project.html
- Optional. Can also be specified without LANGUAGES keyword per the first, short signature.
- By default C and CXX are enabled if no language options are given. 
No mention of "New in version", so I guess that older cmake versions can handle this.
---- …
> CMakeLists.txt: only require a C compiler

- plugins/in_tail/tail_fs_inotify.c
These messages are useful for debugging except with only the inode, it you have to do work to match this with specific files.
----
**Testing**
----
> in_tail: add file name context to inotify debug event mask

- plugins/out_s3/s3.c
- plugins/out_s3/s3_store.c
- plugins/out_s3/s3_store.h
Signed-off-by: Clay Cheng <claychen@amazon.com>
----
**Testing**
```
[INPUT]
Name                         forward
Listen                       0.0.0.0
Port                         24224
[OUTPUT]
Name s3
Match *
bucket s3-time-1
region us-east-1
use_put_object On
total_file_size 10M
retry_limit 2
upload_timeout 5s
```
```
{
"generator": {
"name": "basic",
"config": {
"contentLength": 100000,
"batchSize": 1
}
},
"datajet": {
"name": "forward",
"config": {
"logStream": "stderr",
"port": 24224
}
},
"stage": {
"batchRate": 5,
"maxBatches": 1000
}
}
```
***Upload timeout + put object used***
```
[INPUT]
Name                         forward
Listen …
```
> out_s3: update for getting upload time from timestamp.

- plugins/filter_ecs/ecs.c
- plugins/filter_ecs/ecs.h
- tests/runtime/filter_ecs.c
This is rebased on top of: https://github.com/fluent/fluent-bit/pull/6589
The ECS Filter was first released in AWS for Fluent Bit 2.29.0. The first version works, but has a non-ideal experience when metadata lookups for a log fails, and the code is very inefficient. 
When customers configure the ECS filter, they provide a list of metadata key value pairs they want added to logs. The filter looks up metadata from the ECS Agent introspection endpoint. 
However, the metadata fetch can fail, for one of two reasons:
1. ECS Agent introspection endpoint is unreachable. 
2. The filter is trying to attach metadata for a container that is not running as part of an ECS Task. The ECS Agent introspection endpoint only returns metadata for containers that are running as part of ECS Tasks. However, …
> filter_ecs: only attach metadata keys if their values are non-empty

- tests/internal/fuzzers/parse_json_fuzzer.c
> tests: internal: fuzzers: make parse_json fuzzer able to fail malloc

- tests/internal/fuzzers/parse_logfmt_fuzzer.c
> tests: internal: fuzzers: make parse_logfmt fuzzer able to fail malloc

- include/fluent-bit/flb_mem.h
> mem: add chance of failure for calloc

- include/fluent-bit/flb_record_accessor.h
- include/fluent-bit/record_accessor/flb_ra_parser.h
- src/flb_mp.c
- src/flb_record_accessor.c
- src/record_accessor/flb_ra_parser.c
- tests/internal/mp.c
Fixes #5546 
out_loki tries to remove key/value using flb_mp_accessor_keys_remove.
The API needs a key lists to indicate which key should be removed.
I tested the API and I found that the list should be sorted if it is passed nested key/value.
However the lists is not sorted at current master. It may not work if user passes nested key/value.
- Add test code
- Add API to get subkey number
- Insert record_accessor sorted by subkey number
----
**Testing**
- [N/A] Attached [local packaging …
> mp: sort flb_record_accessor by a number of subkeys(#5546)

- src/flb_config_map.c
flb_sds_create can return NULL and this need to be guarded, as otherwise NULL-dereferences can happen later in the execution. This was found by the fuzzer locally from https://github.com/fluent/fluent-bit/pull/6858
----
**Testing**
- [N/A] Run …
> config_map: fix possible NULL-deref

- src/flb_engine.c
Due to how flb_task_users_release determines if it can drop the involved chunk and how entries in the retries list are handled by flb_task_retry_create we need to explicitly remove the retry entries related to the failed task and plugin instance before calling flb_task_users_dec to ensure that chunks linked to tasks that had at least one retry but are deemed not retriable afterwards can be properly disposed of.
> engine: added retry cleanup when a task cannot be retried

- plugins/in_node_exporter_metrics/ne.c
- plugins/in_node_exporter_metrics/ne.h
Currently, node_exporter_metrics does not support switch on/off for each of metrics and support each of intervals of scrapiong metrics neither. 
----
**Testing**
```python
[SERVICE]
log_level       info
[INPUT]
name            node_exporter_metrics
tag             fluentbit.metrics.${HOSTNAME}
scrape_interval 5
collector.cpu.scrape_interval 5
collector.cpufreq.scrape_interval 15
collector.meminfo.scrape_interval 5
collector.diskstats.scrape_interval 30
collector.filesystem.scrape_interval 25
collector.uname.scrape_interval 50
collector.stat.scrape_interval 35
collector.time.scrape_interval 55
collector.loadavg.scrape_interval …
```
> node_exporter_metrics: Support individual on/off and intervals for metrics

- plugins/in_windows_exporter_metrics/we.c
- plugins/in_windows_exporter_metrics/we.h
Currently, windows_exporter_metrics does not support switch on/off for each of metrics and support each of intervals of scrapiong metrics neither.
----
**Testing**
```python
[INPUT]
Name windows_exporter_metrics
Tag             windows_metrics
scrape_interval 5
we.logical_disk.allow_disk_regex /(C|D)/
we.logical_disk.deny_disk_regex /^HarddiskVolume.*/
collector.cpu.scrape_interval 10
collector.cpu_info.scrape_interval 50
collector.os.scrape_interval 30
collector.net.scrape_interval 40
collector.logical_disk.scrape_interval 35
collector.cs.scrape_interval 60
collector.thermalzone.scrape_interval 55
collector.logon.scrape_interval 15 …
```
> windows_exporter_metrics: Support individual on/off and intervals for metrics

- tests/internal/fuzzers/msgpack_parse_fuzzer.c
To test all of the error-handling logic the fuzzer reaches.
----
**Testing**
- [N/A] Set `ok-package-test` label to test for all …
> tests: internal: fuzzers: make msgpack fuzzer able to fail malloc

- tests/internal/fuzzers/config_map_fuzzer.c
> tests: intenral: fuzzers: make config_map fuzz able to fail malloc

- plugins/in_elasticsearch/in_elasticsearch.c
- plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
- plugins/in_elasticsearch/in_elasticsearch_config.c
This patch is minor fixes.
- Use flb_sds APIs since `ctx->listen` and `ctx->tcp_port` are `flb_sds_t`
- Fix typo `IN TCP` -> `IN_ELASTICSEARCH`
- Add missing releasing functions
- Allocates `bulk_statuses` and `bulk_response`. I think they are allocated only in POST case.
----
**Testing**
- [N/A] Set `ok-package-test` label to test for all targets (requires maintainer …
> in_elasticseach: minor fixes

- include/fluent-bit/flb_signv4.h
- plugins/out_bigquery/bigquery.c
- plugins/out_es/es.c
- plugins/out_es/es.h
- plugins/out_es/es_conf.c
- plugins/out_http/http.c
- plugins/out_opensearch/opensearch.c
- plugins/out_opensearch/opensearch.h
- plugins/out_opensearch/os_conf.c
- src/aws/flb_aws_util.c
- src/flb_signv4.c
- tests/internal/fuzzers/signv4_fuzzer.c
- tests/internal/signv4.c
master pr: https://github.com/fluent/fluent-bit/pull/6612
Several minor changes:
- Add payload hash to authenticated request headers as:
```
x-amz-content-sha256
```
- Allow for configurable service name where "es" is used by default.
- Add Excluded_Headers parameter to aws sigv4 function.
- Exclude content_length from OpenSearch & ES headers
Tested by FireLens team on Amazon AWS Opensearch with the following plugin configurations
```
[SERVICE]
Flush 1
Grace 30
[INPUT]
Name cpu
Tag cpu
[OUTPUT]
Name  es
Match *
Index cpu
Host my.es.amazonaws.com
port 443
aws_auth on
aws_region us-west-2
tls on
```
```
[SERVICE]
Flush 1
Grace 30
[INPUT]
Name cpu
Tag cpu
[OUTPUT]
Name  opensearch
Match *
Index cpu
Host my.es.amazonaws.com
port 443
aws_auth on
aws_region us-west-2
tls on
```
No error …
> opensearch: aoss support - 1.9

- include/fluent-bit/flb_signv4.h
- plugins/out_bigquery/bigquery.c
- plugins/out_es/es.c
- plugins/out_es/es.h
- plugins/out_es/es_conf.c
- plugins/out_http/http.c
- plugins/out_opensearch/opensearch.c
- plugins/out_opensearch/opensearch.h
- plugins/out_opensearch/os_conf.c
- src/aws/flb_aws_util.c
- src/flb_signv4.c
- tests/internal/fuzzers/signv4_fuzzer.c
- tests/internal/signv4.c
Please see notes and add comments to : https://github.com/fluent/fluent-bit/pull/6448
----
**Testing**
----
> opensearch: Aoss master

- include/fluent-bit/flb_sds.h
Check are done only on GCC/Clang.
Signed-off-by: Benoît GARNIER <bunch@orange.fr>
----
**Testing**
----
> sds: check flb_sds_printf() format and arguments at compile time

- .github/actions/generate-package-build-matrix/action.yaml
- .github/workflows/call-build-linux-packages.yaml
- .github/workflows/call-build-macos.yaml
- .github/workflows/call-build-windows.yaml
- .github/workflows/cron-unstable-build.yaml
- .github/workflows/unit-tests.yaml
- packaging/build-config.json
Resolves typo in build matrix action causing issues like: https://github.com/fluent/fluent-bit/actions/runs/4229760590/jobs/7346422917
Removed nightly 1.9 build.
Resolves #6887  issues with new ARM target for Windows.
Ensure we run unit tests for 2.0 PRs and pushes.
Resolve macOS build issues as well.
Fix incorrect string replacement for uploaded package names.
----
**Testing**
- `master`: https://github.com/fluent/fluent-bit/actions/runs/4260976499
- Shows it builds all targets including Windows ARM
- `2.0`: https://github.com/fluent/fluent-bit/actions/runs/4261512866
- Shows it builds all targets excluding Windows ARM
- `1.9`: https://github.com/fluent/fluent-bit/actions/runs/4261864100
- Compilation failures but not …
> packaging: update workflows for new targets and branches

- include/fluent-bit/flb_input.h
- plugins/in_elasticsearch/in_elasticsearch.c
- plugins/in_elasticsearch/in_elasticsearch.h
- plugins/in_elasticsearch/in_elasticsearch_bulk_conn.c
- plugins/in_forward/fw.c
- plugins/in_forward/fw.h
- plugins/in_forward/fw_conn.c
- plugins/in_http/http.c
- plugins/in_http/http.h
- plugins/in_http/http_conn.c
- plugins/in_mqtt/mqtt.c
- plugins/in_mqtt/mqtt.h
- plugins/in_mqtt/mqtt_conn.c
- plugins/in_opentelemetry/http_conn.c
- plugins/in_opentelemetry/opentelemetry.c
- plugins/in_opentelemetry/opentelemetry.h
- plugins/in_syslog/syslog.c
- plugins/in_syslog/syslog.h
- plugins/in_syslog/syslog_conf.c
- plugins/in_syslog/syslog_conn.c
- plugins/in_tcp/tcp.c
- plugins/in_tcp/tcp.h
- plugins/in_tcp/tcp_conn.c
- plugins/in_udp/udp.c
- plugins/in_udp/udp.h
- plugins/in_unix_socket/unix_socket.c
- plugins/in_unix_socket/unix_socket.h
- plugins/in_unix_socket/unix_socket_conn.c
- src/flb_input.c
This pull request addresses the same issues that PR #6882 covered.
> downstream: PR 6882 rework

- include/fluent-bit/flb_input.h
- plugins/in_elasticsearch/in_elasticsearch.c
- plugins/in_elasticsearch/in_elasticsearch.h
- plugins/in_elasticsearch/in_elasticsearch_bulk_conn.c
- plugins/in_forward/fw.c
- plugins/in_forward/fw.h
- plugins/in_forward/fw_conn.c
- plugins/in_http/http.c
- plugins/in_http/http.h
- plugins/in_http/http_conn.c
- plugins/in_mqtt/mqtt.c
- plugins/in_mqtt/mqtt.h
- plugins/in_mqtt/mqtt_conn.c
- plugins/in_opentelemetry/http_conn.c
- plugins/in_opentelemetry/opentelemetry.c
- plugins/in_opentelemetry/opentelemetry.h
- plugins/in_syslog/syslog.c
- plugins/in_syslog/syslog.h
- plugins/in_syslog/syslog_conf.c
- plugins/in_syslog/syslog_conn.c
- plugins/in_tcp/tcp.c
- plugins/in_tcp/tcp.h
- plugins/in_tcp/tcp_conn.c
- plugins/in_udp/udp.c
- plugins/in_udp/udp.h
- plugins/in_unix_socket/unix_socket.c
- plugins/in_unix_socket/unix_socket.h
- plugins/in_unix_socket/unix_socket_conn.c
- src/flb_input.c
This is a backport of PR #6906.
> downstream: pr 6906 backport

- plugins/in_tail/tail_fs_inotify.c
As a side note, if the attributes in the mask are composable (as the code suggests) there could be combinations that exceed the filename + 64 assumption causing a buffer overflow.
> in_tail: fixed argument order that caused a segfault in issue 6797

- src/flb_slist.c
flb_sds_create_len can fail and return NULL. This adds a safeguard to ensure no NULL dereference happens if that's the case.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56223
----
**Testing**
- [N/A ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets …
> slist: fix possible NULL derefence

- src/flb_input.c
This patch is to remove following warning.
```
[ 69%] Building C object src/CMakeFiles/fluent-bit-shared.dir/flb_input.c.o
/home/taka/git/fluent-bit/src/flb_input.c: In function ‘flb_input_downstream_set’:
/home/taka/git/fluent-bit/src/flb_input.c:1915:9: warning: unused variable ‘flags’ [-Wunused-variable]
1915 |     int flags = 0;
|         ^~~~~
```
----
**Testing** …
> input: remove unused variable flags

- plugins/out_loki/loki.c
This patch may fix some SIGSEGVs of out_loki that relates flb_sds_t.
#6897 #6802 #6645
`safe_sds_cat` can update flb_sds_t pointer.
https://github.com/fluent/fluent-bit/blob/v2.0.9/plugins/out_loki/loki.c#L46
However following function can't return updated value since arg is not a pointer.
```c
func (flb_sds_t ptr){
safe_sds_cat(&ptr, "a", 1);
}
```
If the flb_sds_t pointer is updated, caller can touch previous pointer which is already released and it may cause SIGSEGV.
This patch is to use flb_sds_t pointer as an arg to propagate updated pointer.
----
**Testing**
If this is a change to …
> out_loki: use flb_sds pointer to propagate updated pointer and prevent SIGSEGV

- src/flb_chunk_trace.c
This patch is to fix following warning.
```
[ 75%] Building C object src/CMakeFiles/fluent-bit-shared.dir/flb_chunk_trace.c.o
/home/taka/git/fluent-bit/src/flb_chunk_trace.c:101:13: warning: ‘log_cb’ defined but not used [-Wunused-function]
101 | static void log_cb(void *ctx, int level, const char *file, int line,
|             ^~~~~~
```
----
**Testing** …
> chunk_trace: remove unused function log_cb

- src/aws/flb_aws_util.c
- tests/internal/fuzzers/CMakeLists.txt
- tests/internal/fuzzers/aws_util_fuzzer.c
Adds a fuzzer for aws_util and also fixes a possible double free on `buf` and `tmp`.
----
**Testing**
- [N/A] Set `ok-package-test` label to test for all targets (requires maintainer …
> tests: internal: fuzzers: add aws utils fuzzer

- include/fluent-bit/flb_sds.h
The checks, which were missing for the flb_sds_snprintf() variant, are now done with the new generic FLB_FORMAT_PRINTF() macro.
----
**Testing**
---- …
> sds: check format and arguments at compile time

- plugins/in_opentelemetry/opentelemetry_prot.c
- plugins/out_opentelemetry/opentelemetry.c
Most of these changes correct memory corruption issues in the opentelemetry output plugin, there is only one fix in the opentelemetry input plugin to correct a uninitialized variable usage that has not caused issues at the moment (but I know it will with the log event refactor because I have already fixed it in that branch as well).
> opentelemetry: memory corruption fixes

- plugins/out_loki/loki.c
- tests/runtime/out_loki.c
out_loki doesn't append floating point value using following configuration.
```
[INPUT]
Name dummy
Dummy {"value":1.3}
[OUTPUT]
Name loki
Match *
Line_Format key_value
```
```
$ nc -l 3100
POST /loki/api/v1/push HTTP/1.1
Host: 127.0.0.1:3100
Content-Length: 89
User-Agent: Fluent-Bit
Content-Type: application/json
{"streams":[{"stream":{"job":"fluent-bit"},"values":[["1676170056677523154","value="]]}]}^C
```
----
**Testing** …
> out_loki: add missing flb_sds_cat for float value

- plugins/out_s3/s3.c
This PR fixes the error introduced in PR #6475 adding the structure instance I think was missing in those calls.
Still, I think it'd be good if either @PettitWesley or @Claych vouched for it.
> out_s3: added missing structure instance in s3_retry_warn calls

- plugins/out_loki/loki.c
- plugins/out_loki/loki.h
I removed the dynamic_tenant_id field from the context structure in favor of passing an output argument in order to correct the concurrency issue.
> out_loki: fixed race condition / toctou reported in issue 6911

- plugins/filter_aws/aws.c
- plugins/filter_checklist/checklist.c
- plugins/filter_ecs/ecs.c
- plugins/filter_kubernetes/kube_meta.c
- plugins/filter_nightfall/nightfall_api.c
- plugins/in_elasticsearch/in_elasticsearch_bulk_conn.c
- plugins/in_exec/in_exec.c
- plugins/in_exec_wasi/in_exec_wasi.c
- plugins/in_http/http_conn.c
- plugins/in_opentelemetry/http_conn.c
- plugins/in_stdin/in_stdin.c
- plugins/out_azure_blob/azure_blob_http.c
- plugins/out_http/http.c
- plugins/out_kinesis_firehose/firehose_api.c
- plugins/out_loki/loki.c
- plugins/out_s3/s3.c
- plugins/out_splunk/splunk_conf.c
- plugins/out_stackdriver/stackdriver_resource_types.c
- src/config_format/flb_cf_yaml.c
- src/flb_input_chunk.c
- src/flb_pack_gelf.c
- src/flb_time.c
- src/flb_typecast.c
- src/http_server/api/v1/trace.c
- src/multiline/flb_ml_parser.c
- src/multiline/flb_ml_stream.c
Fixed format and arguments for:
- flb_log_print(), and associated macros like flb_error() and flb_plg_error()
- flb_sds_printf()
These formatting issues were revealed by #6921 and #6925.
----
**Testing**
----
> fluent-bit: fix printf-like format and arguments

- include/fluent-bit/flb_http_client.h
- plugins/out_loki/loki.c
- plugins/out_loki/loki.h
- src/flb_http_client.c
Add bearer token authentication support to the general http client. Then use the added bearer token support in the Loki output plugin. This allows fluent-bit to be used for opstrace and other non basic auth loki configurations.
----
**Testing**
----
----
```
[SERVICE]
[INPUT]
Name dummy
Tag dummy
[OUTPUT]
Name loki
Match *
labels job=fluentbit
host https://loki.example
port 443
bearer_token insertbigtokenhere
```
```
* Fluent …
```
> out_loki: Add support for bearer token auth

- plugins/out_stackdriver/stackdriver.c
this change updates the retried log metric when the output plugin sends a retry signal to the scheduler.
> out_stackdriver: add metric for retried logs

- plugins/in_tail/tail_fs_inotify.c
Basically, the current estimate could be too small if the file name is very long and all of the possible inotify events were triggered. 
----
**Testing**
----
> in_tail: fix buffer size estimate to support all inotify events 

- CODEOWNERS
Update to codeowners to cover cmake in the absence of @niedbalski 
----
> codeowners: add patrick-stephens to cmake approvers

- plugins/out_s3/s3.c
- plugins/out_s3/s3.h
- src/aws/flb_aws_util.c
Fixes #6933
----
**Testing**
----
> out_s3: fix tag corruption with preserve_data_ordering

- plugins/out_s3/s3.c
- plugins/out_s3/s3.h
- src/aws/flb_aws_util.c
This PR fixes a bug in the add_to_queue function used to enqueue chunk uploads, that function used to allocate an insufficiently large buffer which resulted in the tag string not being NULL terminated sometimes.
Additionally, flb_malloc calls have been replaced with flb_calloc to ensure that the memory is zeroed out.
> out_s3: backport of PR 6988

- src/flb_output.c
This PR fixes a bug in the base code that sets up an output plugins upstream which previously missed the keepalive flag.
> output: backport of PR 6992

- src/flb_output.c
Fixes #6977 
----
**Testing**
**Test Case: net.keepalive on**
configuration:
```
[SERVICE]
Flush         5
Log_Level     debug
Log_File      /usr/local/logs/fluent-bit.log
Daemon        off
HTTP_Server   On
HTTP_Listen   0.0.0.0
HTTP_Port     2020
[INPUT]
Name              cpu
Tag               demo
[OUTPUT]
Name          forward
Match_Regex   *
Host          <fluentd host>
Port          43000
Retry_Limit   2
net.keepalive on
```
Debug log output:
```
[1m[[0m2023/03/10 12:58:38[1m][0m [[92m info[0m] [fluent bit] version=2.1.0, commit=6ee3b8a05d, pid=1191
[1m[[0m2023/03/10 12:58:38[1m][0m [[93mdebug[0m] [engine] coroutine stack …
```
> output_upstream: set FLB_IO_TCP_KA flag when net.keepalive is true.

- plugins/out_opentelemetry/opentelemetry.c
- plugins/out_opentelemetry/opentelemetry_conf.c
This patch is to suppress some warnings.
opentelemetry.c: 
```
[ 46%] Building C object plugins/out_opentelemetry/CMakeFiles/flb-plugin-out_opentelemetry.dir/opentelemetry.c.o
In file included from /home/taka/git/fluent-bit/plugins/out_opentelemetry/opentelemetry.c:20:
/home/taka/git/fluent-bit/plugins/out_opentelemetry/opentelemetry.c: In function ‘process_logs’:
/home/taka/git/fluent-bit/plugins/out_opentelemetry/opentelemetry.c:823:27: warning: passing argument 1 of ‘flb_output_plugin_log_suppress_check’ from incompatible pointer type [-Wincompatible-pointer-types]
823 |             flb_plg_error(ins, "log event conversion failure");
|                           ^~~
|                           |
|                           struct flb_input_instance * …
```
> out_opentelemetry: fix some warnings

- plugins/in_winevtlog/pack.c
The missing break was causing an extra `?` string to be packed after packing a binary `StringInsert`; the extra string causes all kinds of problems downstream.
Fixes #7017.
----
**Testing**
- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) …
> in_winevtlog: fix missing break

- plugins/out_pgsql/pgsql.c
- plugins/out_pgsql/pgsql.h
- plugins/out_pgsql/pgsql_connections.c
libpq supports connection options on the postgresql plugin. Passing connection options to client are basic functionality but the plugin cannot pass connection options. I patched it.
#6836 
----
**Testing**
---- …
> out_pgsql: pass connection options to postgresql client

- CMakeLists.txt
- plugins/CMakeLists.txt
- plugins/in_event_type/event_type.c
- plugins/out_vivo_exporter/CMakeLists.txt
- plugins/out_vivo_exporter/vivo.c
- plugins/out_vivo_exporter/vivo.h
- plugins/out_vivo_exporter/vivo_http.c
- plugins/out_vivo_exporter/vivo_http.h
- plugins/out_vivo_exporter/vivo_stream.c
- plugins/out_vivo_exporter/vivo_stream.h
The following new output plugin provides an HTTP interface to expose logs, metrics and traces
by using a temporary buffer per stream.
By default, the HTTP Server runs in TCP port 2025 and exposes the following endpoints:
- /logs
- /metrics
- /traces
All the returned content is in readable JSON format. Each endpoint contains a 'stream' with a
fixed size capacity (20M default) and by configuration is possible to change the size. Details
of the options available:
- `empty_stream_on_read`: if enabled, when a HTTP Client consumes the stream content, the content
is removed from the queue (default: off)
- `stream_queue_size`: set the size in bytes for each stream like logs, metrics and traces (default: 20M)
By using curl we can easily retrieve the streams. Here is an example by ingesting a dummy …
> out_vivo_exporter: new output plugin to export Vivo records

- tests/internal/fuzzers/record_ac_fuzzer.c
----
**Testing**
- [N/A ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [N/A ] Set `ok-package-test` label to test for all targets (requires maintainer to do). …
> tests: internal: fuzzers: record_ac: make malloc failable

- src/stream_processor/flb_sp.c
This patch is to fix following stream processor leak.
It detected `name` and `exec` were lost.
`flb_cf_section_property_get_string` allocates and returns flb_sds_t and it is passed to `flb_sp_task_create`.
`flb_sp_task_create` also creates flb_sds_t from `name` and `exec`.
So we should release `name` and `exec` after passing.
```
==40140== 
==40140== HEAP SUMMARY:
==40140==     in use at exit: 172 bytes in 2 blocks
==40140==   total heap usage: 4,596 allocs, 4,594 frees, 576,266 bytes allocated
==40140== 
==40140== 23 bytes in 1 blocks are definitely lost in loss record 1 of 2
==40140==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==40140==    by 0x1B9657: flb_malloc (flb_mem.h:80)
==40140==    by 0x1B983A: sds_alloc (flb_sds.c:41)
==40140==    by …
```
> sp: release name and exec after using

- src/flb_parser.c
This patch is to suppress following warnings.
```
[ 74%] Building C object src/CMakeFiles/fluent-bit-shared.dir/flb_parser.c.o
In file included from /home/taka/git/fluent-bit/src/flb_parser.c:21:
/home/taka/git/fluent-bit/src/flb_parser.c: In function ‘flb_parser_time_lookup’:
/home/taka/git/fluent-bit/src/flb_parser.c:1151:23: warning: field precision specifier ‘.*’ expects argument of type ‘int’, but argument 5 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
1151 |             flb_error("[parser] cannot parse '%.*s'", tsize, time_str);
|                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~
|                                                       |
|                                                       size_t {aka long unsigned int} …
```
> parser: fix warning that pass size_t as a field precision specifier

- plugins/filter_grep/grep.c
- plugins/filter_grep/grep.h
- tests/runtime/filter_grep.c
Doc PR: https://github.com/fluent/fluent-bit-docs/pull/1031
EDIT: update default value.
This patch is to support 'logical_op' to handle multiple conditions like Fluentd's `and`/`or` directive.
https://docs.fluentd.org/filter/grep
User requests: #6708 #6245
|Key|Description|
|---|----|
|Logical_Op|Specify whether to use logical conjuciton or disjunction. `AND` and `OR` are allowed. Default is `legacy`.|
Note: Default is none for backward  backward compatibility.
Because filter_grep treats 'AND' when multi `Regex`s are set.
When multi `Exclude`s are set, filter_grep treats 'OR'.  Please see test case `flb_test_filter_grep_multi_regex` and `flb_test_filter_grep_multi_exclude`
----
**Testing**
Before we can approve your …
> filter_grep: support logical_op property

- packaging/update-source-packages.sh
Resolves #7048.
We refactored things for 2.0.9 to split up various jobs and unfortunately that slightly changed the path for the source to copy over.
----
**Testing**
----
> packaging: fix missing source packages

- plugins/out_vivo_exporter/vivo.c
- plugins/out_vivo_exporter/vivo.h
- plugins/out_vivo_exporter/vivo_http.c
> out_vivo_exporter: add new option 'http_cors_allow_origin' for CORS handling

- tests/internal/log.c
#6841 
- Increment interval on first time
- update ret_1/ret_2 not to reuse last ret_1/ret_2
----
**Testing**
```
$ valgrind …
```
> tests: internal: log: make cache_basic_tmeout more stable

- plugins/out_vivo_exporter/vivo_http.c
> out_vivo_exporter: expose access control headers

- tests/runtime/filter_log_to_metrics.c
This patch is to suppress following warning.
```
Consolidate compiler generated dependencies of target flb-rt-filter_log_to_metrics
[ 82%] Building C object tests/runtime/CMakeFiles/flb-rt-filter_log_to_metrics.dir/filter_log_to_metrics.c.o
In file included from /home/taka/git/fluent-bit/include/fluent-bit/flb_config.h:27,
from /home/taka/git/fluent-bit/include/fluent-bit/flb_utils.h:25,
from /home/taka/git/fluent-bit/include/fluent-bit.h:37,
from /home/taka/git/fluent-bit/tests/runtime/filter_log_to_metrics.c:21:
/home/taka/git/fluent-bit/tests/runtime/filter_log_to_metrics.c: In function ‘callback_test’:
/home/taka/git/fluent-bit/tests/runtime/filter_log_to_metrics.c:138:19: warning: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘void *’ [-Wformat=]
138 | …
```
> tests: runtime: filter_log_to_metrics: fix warning

- tests/runtime/filter_lua.c
- Remove warning
- Fix valgrind errors
----
**Testing**
```
$ valgrind --leak-check=full bin/flb-rt-filter_lua 
==80978== Memcheck, a …
```
> tests: runtime: filter_lua: remove warning

- tests/runtime/filter_nest.c
- Fix warning.
- Release unused data on callback.
```
[ 81%] Building C object tests/runtime/CMakeFiles/flb-rt-filter_nest.dir/filter_nest.c.o
In file included from /home/taka/git/fluent-bit/include/fluent-bit/flb_config.h:27,
from /home/taka/git/fluent-bit/include/fluent-bit/flb_utils.h:25,
from /home/taka/git/fluent-bit/include/fluent-bit.h:37,
from /home/taka/git/fluent-bit/tests/runtime/filter_nest.c:3:
/home/taka/git/fluent-bit/tests/runtime/filter_nest.c: In function ‘callback_count’:
/home/taka/git/fluent-bit/tests/runtime/filter_nest.c:53:19: warning: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘void *’ [-Wformat=]
53 |         flb_debug("[test_filter_nest] received message: %s", data);
| …
```
> tests: runtime: filter_nest: fix warning

- plugins/in_systemd/systemd_config.c
This is to fix following warning.
```
[ 65%] Building C object plugins/in_systemd/CMakeFiles/flb-plugin-in_systemd.dir/systemd_config.c.o
In file included from /home/taka/git/fluent-bit/plugins/in_systemd/systemd_config.c:21:
/home/taka/git/fluent-bit/plugins/in_systemd/systemd_config.c: In function ‘flb_systemd_config_create’:
/home/taka/git/fluent-bit/include/fluent-bit/flb_input_plugin.h:45:47: warning: format ‘%i’ expects argument of type ‘int’, but argument 7 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
45 |         flb_log_print(FLB_LOG_DEBUG, NULL, 0, "[input:%s:%s] " fmt,     \
|                                               ^~~~~~~~~~~~~~~~
/home/taka/git/fluent-bit/plugins/in_systemd/systemd_config.c:272:5: note: in expansion of macro ‘flb_plg_debug’
272 | …
```
> plugin: in_systemd: fix warning

- plugins/out_azure_kusto/azure_kusto_conf.c
https://github.com/fluent/fluent-bit/pull/6729 changed the signature of `flb_upstream_node_create` to use `flb_sds_t` instead of `char*`, this caused the azure_kusto output plugin, which was passing `char*` to create broken upstream nodes that would eventually fail the plugin, this fix merely creates sds strings and passes those along the upstream node creation.
----
**Testing**
- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new …
> pipeline: outputs: azure_kuto: fix upstream node creation

- tests/runtime/filter_wasm.c
- remove warning
- fix valgrind errors
----
**Testing**
```
$ valgrind --leak-check=full bin/flb-rt-filter_wasm 
==27680== Memcheck, a …
```
> tests: runtime: filter_wasm: make more stable

- src/flb_utils.c
Fixes #7009
Error message of `FLB_ERR_CFG_PLUGIN_FILE` is not defined and it causes #7009 
This patch is to define it.
----
**Testing**
```
[SERVICE]
Plugins_File /home/fluentbit/plugins.conf
[INPUT]
Name …
```
> utils: add plugins_file not found error case

- lib/flb_libco/CMakeLists.txt
- lib/flb_libco/libco.c
- lib/flb_libco/ppc64le.c
add support for IBM ppc64le
----
> lib: flb_libo: upgrade to 4bd9260

- plugins/in_tail/tail_file.c
Use `orig_name` consistently for `path_key`. This solves some weird edge cases where the rotated log path name gets used instead.
----
**Testing**
- [*] Debug log output from testing the change
- [*] Backport to latest stable release.
This is the pull request for the 2.0 backport: https://github.com/fluent/fluent-bit/pull/6997
---- …
> tail: always use file->orig_name for the `path_key` even when file is rotated

- plugins/in_tail/tail_file.c
This is the tiger-1.8.15 backport for https://github.com/fluent/fluent-bit/pull/6996.
----
**Testing**
----
> tail: always use file->orig_name for the path_key even when file is rotated.

- plugins/in_http/http.c
- plugins/in_http/http.h
- plugins/in_http/http_config.c
- plugins/in_http/http_prot.c
This PR adds a new option to in_http that allows the plugin to append a number of custom headers to the response when ingestion succeeds.
> in_http: added support for custom headers upon successful ingestion

- plugins/filter_modify/modify.c
- tests/runtime/filter_modify.c
This patch is to support boolean type as a VALUE of condition.
#7075 
----
**Testing**
This configuration is to add `TAG:Log` if the condition is matched.
```
[INPUT]
Name dummy
Dummy …
```
> filter_modify: support boolean as VALUE

- .github/actions/generate-package-build-matrix/action.yaml
- .github/workflows/build-legacy-branch.yaml
- .github/workflows/call-build-images.yaml
- .github/workflows/call-build-linux-packages.yaml
- .github/workflows/call-build-macos.yaml
- .github/workflows/call-build-windows.yaml
- .github/workflows/call-integration-image-build.yaml
- .github/workflows/cron-scorecards-analysis.yaml
- .github/workflows/cron-stale.yaml
- .github/workflows/cron-unstable-build.yaml
- .github/workflows/pr-compile-check.yaml
- .github/workflows/pr-image-tests.yaml
- .github/workflows/pr-windows-build.yaml
- .github/workflows/staging-release.yaml
- .github/workflows/unit-tests.yaml
- dockerfiles/Dockerfile
- packaging/build-config.json
- packaging/distros/amazonlinux/Dockerfile
- packaging/test-release-packages.sh
- packaging/update-apt-repo.sh
- packaging/update-repos.sh
- packaging/update-source-packages.sh
- packaging/update-yum-repo.sh
Merge from `master` and add AL2023 support: https://github.com/fluent/fluent-bit/pull/7080
----
**Testing**
----
> packaging: AL2023 backport support

- lib/cmetrics/CMakeLists.txt
- lib/cmetrics/src/cmt_atomic_msvc.c
> lib: cmetrics: upgrade to v0.6.1

- src/aws/flb_aws_credentials_sts.c
This caused a warning but there was no risk since the compiler was allocating 8 times the required space.
> aws: fixed the typo in the line that defined random_data

- plugins/in_node_exporter_metrics/CMakeLists.txt
- plugins/in_node_exporter_metrics/ne.c
- plugins/in_node_exporter_metrics/ne.h
- plugins/in_node_exporter_metrics/ne_textfile.c
- plugins/in_node_exporter_metrics/ne_textfile.h
- plugins/in_node_exporter_metrics/ne_textfile_linux.c
Prometheus' node_exporter provides textfile metrics that handles text format of Prometheus payloads.
Note that the current implementation should work for Counter, Gauge, and Untyped metrics due to summary and histograms concatenations are not supported in cmetrics. 
See also: https://github.com/fluent/cmetrics/issues/178
----
**Testing**
```python
[SERVICE]
log_level       debug
[INPUT]
name            node_exporter_metrics
tag             fluentbit.metrics.${HOSTNAME}
collector.textfile.path /path/to/prom_metrics/*/*.prom
metrics textfile
[OUTPUT]
name stdout
Match *
```
<details>
```log
Fluent Bit v2.1.0
* …
```
> node_exporter_metrics: textfile: Implement textfile metrics on node_exporter

- src/flb_input_chunk.c
cio_chunk_lock ensures that the chunk is mapped and then calls cio_chunk_sync which in turn calls cio_file_sync which trims the file to the required size, updates the checksum and syncs it.
The trimming process requires us to remap the file in some platforms such as macos and windows which means the address we previously got from cio_chunk_get_content is no longer valid.
> input_chunk: changed order of operations when flushing a chunk

- plugins/out_forward/forward.c
This patch is to fix following warning.
```
[ 53%] Building C object plugins/out_forward/CMakeFiles/flb-plugin-out_forward.dir/forward.c.o
In file included from /home/taka/git/fluent-bit/plugins/out_forward/forward.c:20:
/home/taka/git/fluent-bit/plugins/out_forward/forward.c: In function ‘forward_read_ack’:
/home/taka/git/fluent-bit/include/fluent-bit/flb_output_plugin.h:82:51: warning: field precision specifier ‘.*’ expects argument of type ‘int’, but argument 7 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
82 |             flb_log_print(FLB_LOG_DEBUG, NULL, 0, "[output:%s:%s] " fmt,    \
|                                                   ^~~~~~~~~~~~~~~~~
/home/taka/git/fluent-bit/plugins/out_forward/forward.c:728:5: note: in expansion of macro ‘flb_plg_debug’
728 | …
```
> out_forward: fix warning

- plugins/in_tail/tail_file.c
This is the 2.0 backport for https://github.com/fluent/fluent-bit/pull/6996.
----
**Testing**
----
> tail: always use file->orig_name for the `path_key` even when file is rotated.

- tests/runtime/filter_parser.c
- Fix warning
- Fix valgrind error
----
**Testing**
- [N/A] …
> tests: runtime: filter_parser: make more stable 

- plugins/in_docker/CMakeLists.txt
- plugins/in_docker/cgroup_v1.c
- plugins/in_docker/docker.c
- plugins/in_docker/docker.h
This patch is to prepare to support cgroup v2.
NOTE: in_docker doesn't support cgroup v2 with this patch. Just preparing and no functionality changes.
- Add `struct cgroup_api` to support cgroup function pointers
- Move cgroup v1 depended API to cgroup_v1.c
- Rename defines to clarify for cgroup v1
----
**Testing** …
> in_docker: prepare to support cgroup v2

- src/http_server/api/v1/trace.c
This patch is to remove following warning.
```
/home/taka/git/fluent-bit/src/http_server/api/v1/trace.c: In function ‘http_enable_trace’:
/home/taka/git/fluent-bit/src/http_server/api/v1/trace.c:227:9: warning: unused variable ‘toggled_on’ [-Wunused-variable]
227 |     int toggled_on = -1;
|         ^~~~~~~~~~
```
----
**Testing**
If this is a change to packaging of containers or native binaries then please …
> trace: remove unused variable

- plugins/out_syslog/syslog.c
- plugins/out_syslog/syslog_conf.c
- plugins/out_syslog/syslog_conf.h
- tests/runtime/out_syslog.c
Fixes #6787 
RFC 5424 limits a size of SD-ID and PARAM-NAME to 32 characters. 
https://www.rfc-editor.org/rfc/rfc5424#section-6
If 'sd_allow_longer_sd_id' is true,
Fluent-bit allows a SD-ID and PARAM-NAME that is longer than 32 characters.
|Name|Description|Default|
|--|--|--|
|allow_longer_sd_id|If true, Fluent-bit allows SD-ID that is longer than 32 characters. Such long SD-ID violates RFC 5424.|`false`|
----
**Testing**
- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) …
> out_syslog: add allow_longer_sd_id property

- src/flb_metrics_exporter.c
- tests/internal/flb_event_loop.c
- tests/internal/fuzzers/signv4_fuzzer.c
- tests/internal/http_client.c
- tests/internal/network.c
Note: This is a minimized version of this PR, following the decisions made in a sync up with Leonardo 2 weeks ago: https://github.com/fluent/fluent-bit/pull/7001
>   Fluent Bit seems to support multiple adds of the same events to the event loop.
>     
>   However there's an issue where if you add the same event multiple times, the internal linked list that tracks ready events could be corrupted.
>   
>   This is solved by checking if the event is in the event loop's ready list and if so, removing it. See this monkey pr on the fix: https://github.com/monkey/monkey/pull/389
>   
>   However the solution requires that events are initialized, so that we can track if the event has or has not been added to the ready list. Uninitialized memory can't be trusted.
Leonardo agrees that this change …
> events: minimal fix - zero events via calloc

- include/fluent-bit/config_format/flb_cf.h
- include/fluent-bit/flb_event.h
- include/fluent-bit/flb_filter.h
- include/fluent-bit/flb_input.h
- include/fluent-bit/flb_output.h
- include/fluent-bit/flb_processor.h
- src/CMakeLists.txt
- src/config_format/flb_cf_yaml.c
- src/config_format/flb_config_format.c
- src/flb_filter.c
- src/flb_input.c
- src/flb_input_log.c
- src/flb_output.c
- src/flb_processor.c
- src/fluent-bit.c
- tests/internal/CMakeLists.txt
- tests/internal/processor.c
- tests/lib/acutest/acutest.h
(note: fixed branch of #7121)
Fluent Bit is able to filter, drop or enrich data before the data hits the final destination, but has been always limited to logs data type and depended on tag/matching routing mechanism, in long configurations this becomes problematic.
In recent versions of Fluent Bit, the input plugins can run in a separate thread, so doing data processing in a separate thread helps to desaturate the main event loop. All of this is an optional feature with no breaking changes.
To take advantage of processors, the user must use Yaml configuration format, this functionality is not exposed in classic mode due to the restriction of nested levels of configuration. Here you can find an example of Yaml that implements processing rules for logs in a random input:
```yaml
service: …
```
> processor: new input and output processors

- include/fluent-bit/flb_input.h
- src/flb_input.c
#7061 
Note: Valgrind reports too many errors. We should check that this patch causes it.
I modified to use pthread_key to handle `flb_libco_in_params`.
Currently  `flb_libco_in_params` is a global variable, I suspect it causes race error.
----
**Testing** …
> input: use pthread_key to handle flb_libco_in_params

- plugins/filter_grep/grep.c
This patch is to fix following warning.
```
[ 41%] Building C object plugins/filter_grep/CMakeFiles/flb-plugin-filter_grep.dir/grep.c.o
/home/taka/git/fluent-bit/plugins/filter_grep/grep.c: In function ‘cb_grep_filter’:
/home/taka/git/fluent-bit/plugins/filter_grep/grep.c:298:12: warning: variable ‘record_begining’ set but not used [-Wunused-but-set-variable]
298 |     size_t record_begining = 0;
|            ^~~~~~~~~~~~~~~
```
```
[ 41%] Building C object plugins/filter_grep/CMakeFiles/flb-plugin-filter_grep.dir/grep.c.o
/home/taka/git/fluent-bit/plugins/filter_grep/grep.c: In function ‘cb_grep_filter’:
/home/taka/git/fluent-bit/plugins/filter_grep/grep.c:298:12: warning: variable ‘record_end’ set but not used [-Wunused-but-set-variable]
298 |     size_t record_end = 0;
| …
```
> filter_grep: remove unused val

- include/fluent-bit/flb_plugin_proxy.h
- include/fluent-bit/flb_plugins.h.in
- src/flb_engine.c
- src/flb_plugin_proxy.c
- src/proxy/go/go.c
- src/proxy/go/go.h
Previously the go plugin code attempted to free and unregister the plugin
in the same code as the call to cb_exit on the plugin instance. This
causes a segfault when there are multiple instances of the same go
plugin configured.
https://github.com/aws/aws-for-fluent-bit/issues/613
----
**Testing**
----
> go: fix segfault on shutdown by separating exit and unregister

- plugins/out_forward/forward_format.c
- tests/runtime/out_forward.c
After merging on #7133, out_forward test case is failing.
I plugged a memory leak and undefined timestamp on message mode.
----
**Testing**
```
% bin/flb-rt-out_forward -v
Test message_mode:
out_forward.c:222: Check ret == 0... ok
[2023/04/10 14:19:24] [ info] [fluent bit] version=2.1.0, commit=0d4006faad, pid=618266
[2023/04/10 14:19:24] [ info] [storage] ver=1.2.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/04/10 14:19:24] [ info] [output:forward:forward.0] worker #0 started
[2023/04/10 14:19:24] [ info] [output:forward:forward.0] worker #1 started
[2023/04/10 14:19:24] [ …
```
> out_forward: Plug undefined timestamp on message mode

- src/flb_sds.c
- tests/internal/sds.c
> sds: fix off by 1 bug in flb_sds_printf

- src/flb_upstream.c
Resolves #6821
Currently the keepalive dropped connection event is only removed in the async case. However, sync connections can also have keepalive. This PR ensures the event is always removed if it was added. 
----
**Testing**
----
> upstream: remove keepalive close event on cleanup

- .github/workflows/call-run-integration-test.yaml
Resolves some integration test failures: https://github.com/fluent/fluent-bit-ci/pull/99
Due to changes on GKE 1.26, it's required to install gke-gcloud-auth-plugin and also we changed GKE auth method from gcloud cli to google-github-actions/get-gke-credentials actions.
Same changes are all green on fluent-bit-ci repo -> https://github.com/fluent/fluent-bit-ci/actions/runs/4639117016/jobs/8209803655
----
**Testing**
https://github.com/fluent/fluent-bit/actions/runs/4315962903
----
> workflows: add GKE auth plugin

- tests/runtime/filter_modify.c
This patch is to fix following warning and valgrind error.
```
[ 85%] Building C object tests/runtime/CMakeFiles/flb-rt-filter_modify.dir/filter_modify.c.o
In file included from /home/taka/git/fluent-bit/include/fluent-bit/flb_config.h:27,
from /home/taka/git/fluent-bit/include/fluent-bit/flb_utils.h:25,
from /home/taka/git/fluent-bit/include/fluent-bit.h:37,
from /home/taka/git/fluent-bit/tests/runtime/filter_modify.c:3:
/home/taka/git/fluent-bit/tests/runtime/filter_modify.c: In function ‘callback_count’:
/home/taka/git/fluent-bit/tests/runtime/filter_modify.c:1340:19: warning: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘void *’ [-Wformat=]
1340 |         flb_debug("[test_filter_modify] received message: %s", data);
| …
```
> tests: runtime: filter_modify: fix warning

- src/flb_output.c
This is a fix to the sync core scheduler implemented for the Cloudwatch Logs output plugin.
Please see this issue for more information on the fix:
https://github.com/fluent/fluent-bit/issues/6849
----
**Testing**
----
> core: sync scheduler resolve multi task user issue

- include/fluent-bit/flb_filter.h
- include/fluent-bit/flb_filter_plugin.h
- include/fluent-bit/flb_input.h
- include/fluent-bit/flb_input_plugin.h
- include/fluent-bit/flb_log.h
- include/fluent-bit/flb_output_plugin.h
- src/flb_filter.c
- src/flb_input.c
This patch is to support `log_suppress_interval` for input/filter plugins.
See also #6435 
----
**Testing**
- [] Documentation required for this feature
```
[INPUT]
Name      node_exporter_metrics
Log_Suppress_Interval 60s
[OUTPUT]
Name …
```
> input: filter: support log_suppress_interval

- include/fluent-bit/flb_aws_credentials.h
- plugins/out_bigquery/bigquery.c
- plugins/out_cloudwatch_logs/cloudwatch_logs.c
- plugins/out_cloudwatch_logs/cloudwatch_logs.h
- plugins/out_es/es.c
- plugins/out_es/es.h
- plugins/out_es/es_conf.c
- plugins/out_kinesis_firehose/firehose.c
- plugins/out_kinesis_firehose/firehose.h
- plugins/out_kinesis_streams/kinesis.c
- plugins/out_kinesis_streams/kinesis.h
- plugins/out_opensearch/opensearch.c
- plugins/out_opensearch/opensearch.h
- plugins/out_opensearch/os_conf.c
- plugins/out_s3/s3.c
- plugins/out_s3/s3.h
- src/aws/flb_aws_credentials.c
- src/aws/flb_aws_credentials_profile.c
- tests/internal/aws_credentials.c
- tests/internal/aws_credentials_process.c
- tests/internal/aws_credentials_profile.c
- tests/internal/data/aws_credentials/shared_credentials_file.ini
This PR introduces a new feature that enables users to specify the profile attribute in their AWS output plugins such as S3, Cloudwatch, Firehose, ES, Kinesis, and OpenSearch. With this feature, customers can now configure multiple profiles, offering greater flexibility in setting up multiple destinations. By specifying the profile attribute, users can easily select the appropriate AWS credentials to access different accounts in different regions making cross-account access simpler.
**Testing**
```
[SERVICE]
flush 10
[INPUT]
Name dummy
Tag mylog
[OUTPUT]
Name s3
Match *
region us-east-1
bucket testfluentbitbucket
static_file_path On
profile custom_profile
upload_timeout 1m …
```
> aws: Profile support for AWS output plugins

- CMakeLists.txt
- cmake/windows-setup.cmake
- plugins/CMakeLists.txt
- plugins/in_calyptia_fleet/CMakeLists.txt
- plugins/in_calyptia_fleet/in_calyptia_fleet.c
- src/flb_lib.c
This pull request adds support for the forthcoming Calyptia cloud fleet management feature.
The configuration is downloaded from the calyptia API and then saved to a /tmp directory with the fleet_id in it. Each configuration is saved with a timestamp based on its last-modified date and then hard linked to new.ini. The old configuration is then hard linked to old.ini. The intent is to later use this to rollback in case of errors.
There are no known memory leaks at the moment. There is a single known bug where sometimes flb_reload will simply not work on initialization when running via valgrind. This must be some kind of race condition.
I still have the following improvements to make:
Here is a simple example configuration:
```ini
[INPUT]
Name          calyptia_fleet
Api_Key …
```
> in_calyptia_fleet: initial implementation of calyptia fleet management.

- plugins/filter_aws/aws.c
- tests/runtime/filter_aws.c
Fixes parsing EC2 tags when tag names are quite long.
Example configuration:
```
[SERVICE]
flush        1
log_level    debug
[INPUT]
name stdin
[FILTER]
Name aws
imds_version v1
Match *
tags_enabled true
[OUTPUT]
name  stdout
match *
```
Valgrind output with debug logs:
```
mwarzynski@e5c714a8ed5d:/fluent-bit-dev/build$ valgrind ./bin/fluent-bit -c fluent-bit.conf
==28096== Memcheck, a memory error detector
==28096== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==28096== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==28096== Command: ./bin/fluent-bit -c fluent-bit.conf
==28096==
Fluent Bit v2.1.0 …
```
> filter: aws fix ec2 long tags

- plugins/filter_wasm/filter_wasm.c
- src/wasm/flb_wasm.c
This PR adds two fixes, first, the WASM can return NULL and then it's still converted to a string via `flb_strdup`. Second it adds that it correctly skips the log entry on returning NULL, it also adds that in some languages the return value is still an empty string. I consider that a good tradeoff, as a fully empty result will likely not be useful at all for follow up filters/outputs.
----
**Testing**
```bash
filter_rust-test-1  | filter found: abcd
filter_rust-test-1  | skip log
filter_rust-test-1  | [2023/03/15 06:37:36] [error] [filter:wasm:wasm.0] invalid JSON format. ret: -1, buf: …
```
> filter_wasm: skip log on NULL or empty WASM return

- plugins/out_prometheus_remote_write/remote_write.c
- plugins/out_prometheus_remote_write/remote_write.h
- plugins/out_prometheus_remote_write/remote_write_conf.c
----
**Testing**
```
[SERVICE]
log_level       debug
[INPUT]
name            fluentbit_metrics
tag             internal_metrics
[OUTPUT]
Name            prometheus_remote_write
Match           internal_metrics
aws_region      us-east-1
aws_auth        On
Host            aps-workspaces.us-east-1.amazonaws.com
Uri             /workspaces/ws-c0da0bb9-734c-496c-b9aa-7d14d688be8f/api/v1/remote_write
Port            443
Tls             On
Tls.verify      On
```
```
Fluent Bit v2.1.0
* …
```
> out_prometheus_remote_write: add aws sigv4 authentication

- plugins/in_elasticsearch/in_elasticsearch.c
- plugins/in_elasticsearch/in_elasticsearch_bulk_conn.c
- plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
This patch is to release buffer on error case.
----
**Testing**
```
$ valgrind --leak-check=full bin/flb-rt-in_elasticsearch 
==5321== Memcheck, a memory …
```
> in_elasticsearch: release buffer on error case

- src/flb_filter.c
After merging input and filter suppression commits, flb_filter.c is not able to compile with macOS's CommandLine tool due to lack of including `<fluent-bit/flb_utils.h>` on flb_filter.c... 
```log
flb_filter.c:292:15: error: call to undeclared function 'flb_utils_time_to_seconds'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
ret = flb_utils_time_to_seconds(tmp);
^
1 error generated.
```
----
**Testing**
----
Fluent Bit is licensed under Apache 2.0, …
> filter: fix implicit util function on filter

- .github/workflows/unit-tests.yaml
macOS support is now much better and unit tests should not be expected to fail so enabling.
----
**Testing**
----
> workflows: enable macos unit test failures

- src/flb_engine.c
Currently, a few of using HTTP client related tests are failed.
This is because HTTP client needs event loop assignment to run its mechanism.
However, the current implementation cause pointer glitches when assigning the custom event loop.
Thanks for your suggestion @leonardo-albertovich !
----
**Testing**
----
> engine: Ensure TLS initialization for evl only once

- src/flb_engine.c
This is backporting PR that is corresponds to https://github.com/fluent/fluent-bit/pull/7188.
----
**Testing**
----
> engine: Ensure TLS initialization for evl only once [2.0 backport] 

- src/CMakeLists.txt
Resolves #7189 to ensure systemd services are included in appropriate packages.
Changes in #5818 seem to be triggering`pkg-config` issues in the container builds for some targets so adding the old default as well.
----
**Testing**
----
> packaging: handle systemd service detection

- CMakeLists.txt
- plugins/filter_lua/lua.c
This PR temporarily disables the mpack code path in filter_lua in favor of using the new log event encoder to prevent metadata loss.
> filter_lua: disable mpack to preserve metadata

- CMakeLists.txt
- plugins/CMakeLists.txt
- plugins/processor_attributes/CMakeLists.txt
- plugins/processor_attributes/attributes.c
- plugins/processor_attributes/variant_utils.h
- plugins/processor_labels/labels.c
This PR introduces the attribute processor which at the moment only supports traces.
The operations this processor supports are : update, insert, upsert, delete, convert, extract and hash
> processor_attributes: initial commit of the attribute processor

- include/fluent-bit/flb_config.h
- src/flb_config.c
- src/flb_reload.c
- src/fluent-bit.c
The previous hot reload PR does not handle for enabling hot reloading feature with configuration file. 
This PR should fix this specification mistake.
----
**Testing**
This service configuration option should be used as:
```conf
[SERVICE]
Enable_Hot_Reload On
```
```
==547697== 
==547697== HEAP SUMMARY:
==547697==     in use at exit: 0 bytes in 0 blocks
==547697==   total heap usage: 52,235 allocs, 52,235 frees, 15,953,425 bytes allocated
==547697== 
==547697== All heap blocks were freed -- no leaks are possible
==547697== 
==547697== For lists of detected and suppressed errors, rerun with: -s
==547697== ERROR SUMMARY: 0 errors from 0 contexts …
```
> bin: config: reload: Enable hot reloading via config file

- src/tls/openssl.c
Adds a missing return from commit 7ea4fd3cbf6678b824fb75ae9a6a286a8e8fda30
Fixes #6690 
----
**Testing**
----
> tls: openssl: add missing return in SSL_ERROR_SYSCALL case

- plugins/out_opensearch/opensearch.c
This patch is to address following warnings.
```
[ 49%] Building C object plugins/out_opensearch/CMakeFiles/flb-plugin-out_opensearch.dir/opensearch.c.o
/home/taka/git/fluent-bit/plugins/out_opensearch/opensearch.c: In function ‘opensearch_format’:
/home/taka/git/fluent-bit/plugins/out_opensearch/opensearch.c:288:11: warning: unused variable ‘p’ [-Wunused-variable]
288 |     char *p;
|           ^
/home/taka/git/fluent-bit/plugins/out_opensearch/opensearch.c:287:12: warning: unused variable ‘off’ [-Wunused-variable]
287 |     size_t off = 0;
|            ^~~
[ 49%] Building C object plugins/out_opensearch/CMakeFiles/flb-plugin-out_opensearch.dir/__/__/lib/lwrb/lwrb/src/lwrb/lwrb.c.o
[ 49%] Linking C static library ../../library/libflb-plugin-out_opensearch.a
```
---- …
> out_opensearch: remove unused variables

- plugins/in_calyptia_fleet/in_calyptia_fleet.c
Fix a few minor issues for Calyptia fleet management:
- Implement configuration rollback:
- Check the syntax of the configuration file before loading it.
- Use cur.ini upon load, rename old.ini back to cur.ini when new.ini
fails to validate.
- Make the `Last-Modified` header lookup case insensitive.
- Fix Fleet configuration section generated in the new configuration file:
- Use valid values for `TLS`.
- Add Missing `Config_Dir` setting.
----
**Testing**
----
Fluent Bit is licensed under Apache 2.0, …
> in_calyptia_fleet: fixes found when connecting to production.

- plugins/filter_aws/aws.c
- plugins/filter_aws/aws.h
- tests/runtime/filter_aws.c
Add Filter AWS option for EC2 tags to include/exclude specified tags. Options are `tags_include` and `tags_exclude`.
Here is the usage (`tags_enabled` is already present in master, but left for context):
```
$ fluent-bit -F aws --help
tags_enabled       Enable EC2 instance tags, injects all tags if tags_include and
tags_exclude are empty
> default: false, type: boolean
tags_include       Defines list of specific EC2 tag keys to inject into the logs; tag keys
must be separated by "," character; tags which are not present in this
list will be ignored; e.g.: "Name,tag1,tag2"
> default: , type: string
tags_exclude       Defines list of specific EC2 tag keys not to inject into the logs; tag
keys must be separated by "," character; if both tags_include and
tags_exclude are specified, …
```
> filter: aws ec2 tags include/exclude

- src/flb_plugin_proxy.c
- src/proxy/go/go.c
Currently, fluent-bit frees allocated memory on every time even if a clean up callback is registered.
However, freeing allocated memory in every time is not good behavior for resource handling on Golang shared object (input plugin) side.
Also, we should keep the behavior when cleanup callback is not registered.
----
**Testing**
---- …
> proxy: plugin_proxy: Clean up allocated resources correctly

- examples/filter_rust/README.md
- examples/filter_rust/src/lib.rs
- examples/filter_rust_clib/README.md
- examples/filter_rust_clib/src/lib.rs
`WASM` filter declaration should have `match` field. Examples should be in sync with the [docs](https://docs.fluentbit.io/manual/pipeline/filters/wasm#config_example).
Signed-off-by: Eugene Tolbakov [ev.tolbakov@gmail.com](mailto:ev.tolbakov@gmail.com)
**Testing**
- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new …
> example: wasm: Fix typos in Filter declaration

- examples/kafka_filter/Dockerfile
- examples/kafka_filter/Makefile
- examples/kafka_filter/kafka.conf
- examples/kafka_filter/kafka.lua
- plugins/in_kafka/in_kafka.c
- plugins/in_kafka/in_kafka.h
The flb_input_thread API was deprecated, so we are moving to a simpler implementation that uses `flb_input_set_collector_time` to periodically poll librdkafka for messages.
Also updated the example scripts, which were referencing kafka versions no longer available for download.
----
**Testing**
To see this working in action, go to `examples/kafka_filter` and execute `make && make start`. This will run the following containers in docker compose:
- kafka-broker is runing a kafka instance
- kafka-producer posts messages to the fb-source topic
- fluent-bit is running a lua filter that processes in the `fb-source` topic, and posting the results in the `fb-sink` topic
- kafka-consumer is reading messages posted on the `fb-sink` topic
After `make start`, you should see `kafka-consumer` messages …
> in_kafka: refactor to use flb_input_set_collector_time

- packaging/update-source-packages.sh
Creates target directory if not exist
Fixes #7222 
----
**Testing**
----
> ci: 2.1 Windows release not synced

- .github/workflows/staging-release.yaml
Resolves #7237 
----
**Testing**
----
> ci: ensure 2.1 series is pushed as latest container

- plugins/out_forward/forward.c
- plugins/out_forward/forward_format.c
- plugins/out_forward/forward_format.h
This PR fixes the wrong default behavior that caused issue #7240 when interacting with fluent-bit 1.9
> out_forward: added missing code to drop metadata by default

- include/fluent-bit/flb_input.h
- plugins/in_forward/fw.c
- plugins/in_forward/fw_prot.c
- src/flb_input.c
Forward input plugin always respected the Tag set by the client on every record, for usability reasons it also supports `tag_prefix` option to prefix events so  routing can be more customizable, but there are other cases where fully replace the tag is desired.
This patch makes the plugin to override the events Tag if it was manually set in the configuration.
> in_forward: allow to override events tag with 'tag' property

- plugins/in_opentelemetry/opentelemetry_prot.c
Fix following warning.
```
[ 56%] Built target flb-plugin-in_elasticsearch
Consolidate compiler generated dependencies of target flb-plugin-in_opentelemetry
[ 56%] Building C object plugins/in_opentelemetry/CMakeFiles/flb-plugin-in_opentelemetry.dir/opentelemetry_prot.c.o
In file included from /home/taka/git/fluent-bit/include/fluent-bit/flb_coro.h:34,
from /home/taka/git/fluent-bit/include/fluent-bit/flb_input.h:25,
from /home/taka/git/fluent-bit/include/fluent-bit/flb_input_plugin.h:24,
from /home/taka/git/fluent-bit/plugins/in_opentelemetry/opentelemetry_prot.c:20:
/home/taka/git/fluent-bit/plugins/in_opentelemetry/opentelemetry_prot.c: In function ‘process_payload_logs’:
/home/taka/git/fluent-bit/plugins/in_opentelemetry/opentelemetry_prot.c:1342:19: warning: field precision specifier …
```
> in_opentelemetry: fix warning

- src/flb_time.c
This is a backport of commit e77d32b42133294bca3f01cb5d4171a12dbb0989 by Benoît Garnier.
> time: fixed printf format string in flb_time_pop_from_mpack

- tests/runtime/out_exit.c
This is because not calling flb_stop on json_invalid case, event loop is still continuing during shutdown.
That causes invalid evl context and causes SEGV on teardown.
On invalid case, the following `flb_engine_exit` is not called and also cb_exit_flush is not called due to no ingested logs.
https://github.com/fluent/fluent-bit/blob/1fa0e94a09e4155f8a6d8a0efe36a5668cdc074e/plugins/out_exit/exit.c#L71-L74
----
**Testing**
---- …
> macos: test: out_exit: Plug invalid evl context case

- lib/cfl/src/cfl_sds.c
> lib: cfl: upgrade to v0.2.3

- src/stream_processor/CMakeLists.txt
stream_processor is written in c, so only enforce a c compiler
----
**Testing** …
> sp: CMakeLists.txt: don't require c++

- .github/workflows/staging-release.yaml
Ensures we pick the next patch version after release to auto-generate the PR with.
Also resolved an issue with using the wrong ref and repo for 2.0 releases.
----
**Testing**
----
> workflows: ensure we increment the version for the new PR

- .github/workflows/pr-package-tests.yaml
Remove the noise during package tests for PRs.
We get a "temporarily deployed" message for each environment usage so just removed for PRs
----
**Testing**
See CI runs below and no additional statements in this PR.
----
> workflows: reduce PR noise

- src/flb_mp.c
This PR fixes an issue in `flb_mp_validate_log_chunk` which I didn't update to use the log event abstraction layer before the release (because I missed it).
Originally I intended to update the code to use the log event decoder but there is something about possible the trailing bytes I'm not sure about so I patched it to comply with the new format in order to fix the issue while minimizing the possibility of introducing new bugs.
We should modernize it in the near future but I don't think this is the right time.
> mp: updated the format check to accept the new format released with 2.1

- plugins/filter_parser/filter_parser.c
This patch fixes parser filters where they have dropped timestamp and metadata if the configured parser does not process a log (when `out_buf` is `NULL`) since #7133.
----
**Testing**
---- …
> filter_parser: fix timestamp and metadata to be properly copied

- plugins/out_vivo_exporter/vivo.c
- plugins/out_vivo_exporter/vivo_http.c
Additionally a small memory leak that happened when a client queried the endpoint while no data was available was fixed.
> out_vivo_exporter: updated the code to use the log event decoder

- src/flb_output_thread.c
This PR fixes a small uninitialized memory access issue that causes valgrind to fail.
> output_thread: added event memory intialization

- lib/snappy-fef67ac/CMakeLists.txt
Don't require C++ for the snappy lib.
----
**Testing**
- [N/A]` Example configuration file for the change
- [N/A]` Debug log output from testing the change
- [N/A]` Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found
- [N/A]` Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [N/A]` Documentation required for this feature
----
Fluent Bit is licensed under Apache …
> lib: snappy: don't require c++

- dockerfiles/Dockerfile
Update libldap to v2.5-0, to fix https://nvd.nist.gov/vuln/detail/CVE-2015-3276. The severity of this issue is rated as high and security scanners complain about the old, unfixed version.
----
**Testing**
- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including …
> dockerfiles: update libldap to v2.5-0

- plugins/filter_lua/lua.c
https://github.com/fluent/fluent-bit/blob/v2.1.2/plugins/filter_lua/lua.c#L610
filter_lua passes ` record_end` as a buffer size.
However it is an offset, it means `record_end` increases per loop.
https://github.com/fluent/fluent-bit/blob/v2.1.2/plugins/filter_lua/lua.c#L493
It will cause SIGSEGV, when `record_end` becomes huge value.
----
**Testing**
- [N/A] Set `ok-package-test` label to test for all targets …
> filter_lua: fix buffer size calculation(#7304)

- plugins/filter_rewrite_tag/rewrite_tag.c
This patch is to emit record using decoder parameters.
See also https://github.com/fluent/fluent-bit/pull/7305#pullrequestreview-1410313237
----
**Testing**
```
[INPUT]
name dummy
[FILTER]
name rewrite_tag …
```
> filter_rewrite_tag: emit using decoder parameters

- src/flb_filter.c
This patch is to remove following warning.
```
[ 67%] Building C object src/CMakeFiles/fluent-bit-shared.dir/flb_filter.c.o
/home/taka/git/fluent-bit/src/flb_filter.c: In function ‘is_active’:
/home/taka/git/fluent-bit/src/flb_filter.c:52:21: warning: unused variable ‘m_head’ [-Wunused-variable]
52 |     struct mk_list *m_head;
|                     ^~~~~~
```
----
**Testing** …
> filter: remove unused variable

- plugins/in_opentelemetry/opentelemetry_prot.c
This patch is to follow RFC9110.
https://www.rfc-editor.org/rfc/rfc9110.html#name-content-length
```
A server MUST NOT send a Content-Length header field in any response with a status code of 1xx (Informational) or 204 (No Content).
A server MUST NOT send a Content-Length header field in any 2xx (Successful) response to a CONNECT request (Section 9.3.6).
```
----
**Testing**
- [N/A] Set `ok-package-test` label to …
> in_otel: do not send content-length at 204(#7231)

- plugins/out_prometheus_remote_write/remote_write.c
- plugins/out_prometheus_remote_write/remote_write.h
This PR adds a new setting named `compression` which accept a string value the user should set to the desired compression algorithm.
The default value is `snappy` to retain the current behavior but it can also be set to `gzip` or `none`.
> out_prometheus_remote_write: added configurable compression method

- plugins/out_prometheus_remote_write/remote_write.c
This PR fixes a missing header issue introduced by the previous prometheus remote write improvement PR.
> out_prometheus_remote_write: added missing header inclusion

- src/flb_parser_json.c
- tests/internal/parser_json.c
This PR will cause the `json` parser to retain the time field if parsing the time key fails.
Resolves #7322 
----
**Testing**
----
> parser_json: keep time key when parsing fails

- src/flb_parser_json.c
- tests/internal/parser_json.c
Backport of #7323 
#7322 
----
**Testing**
----
> Backport keep time key

- CMakeLists.txt
- plugins/in_node_exporter_metrics/CMakeLists.txt
- plugins/in_node_exporter_metrics/ne.c
- plugins/in_node_exporter_metrics/ne.h
- plugins/in_node_exporter_metrics/ne_systemd.c
- plugins/in_node_exporter_metrics/ne_systemd.h
This PR adds a systemd collector to the `node_exporter_metrics` input plugin.
> in_node_exporter_metrics: added a systemd metrics collector

- src/flb_record_accessor.c
- tests/internal/record_accessor.c
This patch is to allow a single character for `flb_ra_translate`.
Currently, `flb_ra_translate` doesn't allow a single character and it causes a issue like #7330.
----
**Testing**
```
[SERVICE]
Flush     1 …
```
> record_accessor: allow single char for flb_ra_translate(#7330)

- plugins/in_winevtlog/pack.c
In this particular function, we were accidentally passing in the actual `winevtlog_config` instead of the log_encoder field of the config. This caused Fluent Bit to crash with an access violation error, since it gets a completely unexpected shape of data.
Fixes #7270
----
**Testing**
- [N/A] Run [local packaging test](./packaging/local-build-all.sh) …
> in_winevtlog: properly pass the log encoder arg

- src/flb_record_accessor.c
- tests/internal/record_accessor.c
Addresses #7335 
----
**Testing**
----
> backport PR 7332

- plugins/in_kafka/in_kafka.c
- src/flb_log_event_encoder_primitives.c
Use log_encoder instead of mpack in in_kafka
#7301 
----
**Testing**
```
[INPUT]
Name kafka
topics quickstart-events
brokers 0.0.0.0:9092
[OUTPUT]
Name stdout
Match *
```
```
Fluent Bit v2.1.3
* https://fluentbit.io/
[2023/05/11 08:43:35] [ info] [fluent bit] version=2.1.3, commit=1e62c1b861, pid=45090
[2023/05/11 08:43:35] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/05/11 08:43:35] [ info] [cmetrics] version=0.6.1
[2023/05/11 08:43:35] [ info] [ctraces ] version=0.3.0
[2023/05/11 …
```
> in_kafka: use log encoder

- include/fluent-bit/flb_input.h
- plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
- src/flb_input.c
- tests/runtime/in_elasticsearch.c
This is backporting PR that is corresponds to https://github.com/fluent/fluent-bit/pull/7360
Closes https://github.com/fluent/fluent-bit/issues/7365
----
**Testing**
----
> in_elasticsearch: Refer the plugin provided tag [2.0 backport]

- plugins/filter_geoip2/geoip2.c
Fixes https://github.com/fluent/fluent-bit/issues/7351.
For other filters, there is a guard for decoder error when decoding done but FLB_EVENT_DECODER_ERROR_INSUFFICIENT_DATA.
In this code path, we should handle this error as success.
----
**Testing**
----
> filter_geoip2: Guard for insifficient data error for fully decoded case

- plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
- tests/runtime/in_elasticsearch.c
Currently, in_elasticsearch does not refer the `Tag` property in its configuration.
This PR's motivation is the current implementation always collided for tag routing for multiple in_elasticsearch instantiated fluent-bit.
This should be able to avoided with adding the capability of handling plugin tag property. 
----
**Testing**
```
[INPUT]
name elasticsearch
listen 0.0.0.0
port 9880
buffer_max_size 4M
tag raw.es
[OUTPUT]
name stdout
match *
```
```
Fluent Bit v2.1.3
[2023/05/11 17:54:27] [ info] …
```
> in_elasticsearch: Refer the plugin provided tag

- .github/PULL_REQUEST_TEMPLATE.md
New contributors could be unaware of the `FLB_VALGRIND` CMake option, leading to false positives in attached Valgrind outputs.
----
**Testing**
- [N/A] Set `ok-package-test` label to …
> PR template: add valgrind instructions

- plugins/filter_modify/modify.c
- src/flb_regex.c
- tests/runtime/filter_modify.c
Fixes #7368 
- Add `rule_free` to release `struct modify_rule`
- Check if valid pointer before releasing
- Use `flb_calloc` to initialize members of struct
- Add test code for #7368 
----
**Testing**
```
[SERVICE]
Flush      1 …
```
> filter_modify: fix clean up function for cond/rule(#7368)

- plugins/in_opentelemetry/opentelemetry_prot.c
in_opentelemetry: enforce log record structure as [ timestamp, { body } ], and start msgpack_array in otel_pack_array
#7191 
----
**Testing**
```
[SERVICE]
flush 1
grace 1
log_level info
[INPUT]
listen 127.0.0.1
port 8101
[OUTPUT]
name stdout
match *
```
```
receivers:
filelog:
include: [./sample.json]
start_at: beginning
operators:
- type: json_parser
parse_from: body
parse_to: body
exporters:
logging:
loglevel: debug
otlphttp:
endpoint: "http://127.0.0.1:8101"
compression: none
service:
telemetry:
metrics:
level: none
pipelines:
logs:
receivers: [filelog]
processors: []
exporters: [otlphttp]
```
``` …
```
> in_opentelemetry: fix record structure

- .github/workflows/pr-image-tests.yaml
- dockerfiles/Dockerfile
Resolves #7383  by reverting #7309 as there are a few conflicts and it triggers an issue at runtime as the library is missing.
Primarily the issue is that even some of the bullseye-backports components we use still have this dependency, e.g. installing `curl/bullseye-backports` triggers it: https://packages.debian.org/bullseye-backports/libcurl4
Realistically I think it needs more work to remove or update this dependency - this is primarily a fix to the image to ensure it works. cc @Garfield96 
Also added a sanity test to the PR image tests workflow.
----
**Testing**
CI verifies it with the new test case.
---- …
> dockerfiles: revert update ldap dependencies from 7309

- plugins/out_stackdriver/stackdriver.c
- plugins/out_stackdriver/stackdriver.h
- tests/runtime/data/stackdriver/stackdriver_test_span_id.h
- tests/runtime/out_stackdriver.c
This adds support for processing the logging.googleapis.com/spanId special field from the jsonPayload
----
**Testing**
This is backporting: https://github.com/fluent/fluent-bit/pull/7345
----
Fluent …
> out_stackdriver: process spanId special field

- plugins/in_elasticsearch/in_elasticsearch.c
- plugins/in_elasticsearch/in_elasticsearch_bulk_conn.c
- plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
This is backporting PR that is corresponds to https://github.com/fluent/fluent-bit/pull/6939.
----
**Testing**
----
> in_elasticsearch: release buffer on error case [2.0 backport]

- plugins/in_windows_exporter_metrics/we_wmi.c
This could be occurred on Windows VM environment.
In on premise case, this situation does not occur.
However, fluent-bit is running on Windows VM, L2/L2 cache is not provided from WMI information:
```powershell
PS>  Get-WmiObject Win32_Processor | Format-List *
<snip>
CpuStatus                               : 0
CreationClassName                       : Win32_Processor
CurrentClockSpeed                       : 3200
CurrentVoltage                          :
DataWidth                               : 64
Description                             : ARMv8 (64-bit) Family 8 Model 0 Revision   0
DeviceID                                : CPU1
ErrorCleared                            :
ErrorDescription                        :
ExtClock                                :
Family …
```
> in_windows_exporter_metrics: Fill the empty string when l2/l3 cache is not defined case

- lib/ctraces/CMakeLists.txt
- lib/ctraces/include/ctraces/ctr_mpack_utils_defs.h
upgrade ctraces to v0.3.1
----
**Testing**
----
> lib: ctraces: upgrade to v0.3.1

- plugins/out_opentelemetry/opentelemetry.c
out_opentelemetry: Added missing goto in case FluentBit is unable to parse the trace payload correctly
ctraces: bump to v0.3.1
----
**Testing**
```
[SERVICE]
flush 1
grace 1
log_level info
[INPUT]
listen 0.0.0.0
port 3000
[OUTPUT]
Name                     opentelemetry
Match                    *
Host                     collector
Port                     3030
Log_response_payload     false
compress gzip
tls                      off
tls.verify               off
Traces_uri               /v1/traces
add_label                app fluent-bit
add_label                color blue
#storage.total_limit_size  90M
```
```
Fluent Bit …
```
> out_opentelemetry: fix error handling for failed msgpack decoding

- plugins/in_node_exporter_metrics/ne.c
- plugins/in_node_exporter_metrics/ne.h
- plugins/in_node_exporter_metrics/ne_filesystem_linux.c
Closes https://github.com/fluent/fluent-bit/issues/7404
----
**Testing**
```
==1817411== 
==1817411== HEAP SUMMARY:
==1817411==     in use at exit: 0 bytes in 0 blocks
==1817411==   total heap usage: 182,849 allocs, 182,849 frees, 10,069,450,097 bytes allocated
==1817411== 
==1817411== All heap blocks were freed -- no leaks are possible
==1817411== 
==1817411== For lists of detected and suppressed errors, rerun with: -s
==1817411== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
``` …
> in_node_exporter_metrics: Make ignoring mount points and filesystem types of regular expressions to be configurable

- src/flb_input.c
- src/flb_output.c
- src/flb_processor.c
In https://github.com/fluent/fluent-bit/issues/7071, users reported SEGV when including rewrite_tag plugin within processor stack.
This can be occurred with initialization order for filter plugins on the stack.
All of plugins must be initialized through `flb_engine_start` to initialize event loop and storage and other required instances correctly.
This PR fixes the invalid initialization of processor stack which includes rewrite_tag plugin.
----
**Testing**
```python
pipeline:
inputs:
- name: dummy
tag: test-tag.raw
dummy: '{"tool": "fluent", "sub": {"s1": {"s2": "bit"}}}'
processors:
logs:
- name: modify
match: test-tag.*
add: hostname monox …
```
> processor: input: output: organize initialization sequence for processor

- plugins/out_opensearch/opensearch.c
- plugins/out_opensearch/opensearch.h
- plugins/out_opensearch/os_conf.c
This change adds support for compressing the payload sent to an OpenSearch server using gzip.
Compression is off by default, similar to other outputs that support compression.
----
**Testing**
https://github.com/fluent/fluent-bit-docs/pull/1104
---- …
> out_opensearch: Add gzip compression

- include/fluent-bit/flb_compression.h
- include/fluent-bit/flb_gzip.h
- src/CMakeLists.txt
- src/flb_compression.c
- src/flb_gzip.c
This PR adds an initial version of the compression abstraction layer.
At this moment it only supports gzip decompression but more algorithms, a simple interface and its compression counterpart will be added soon.
> core: compression abstraction layer addition

- src/flb_engine.c
This PR replaces handle_output_event (from the event loops
perspective) with handle_output_events which processes up to
FLB_ENGINE_OUTPUT_EVENT_BATCH_SIZE events per event loop cycle
(currently 16).
Additionally, the event processing stage in the event loop was
decoupled in order to prioritize internal signals over scheduler events
including but not limited to collection timers and other events such
as sockets or file descriptor events.
This is particularly important if we want to ensure that we decrement
the finished flush task reference counters before servicing the
static file collection timers or inotify events which usually try to
ingest data and could fail when trying to drop a chunk that in fact
had already finished trying to flush.
> tiger: output event handling improvements

- include/fluent-bit/flb_config.h
- include/fluent-bit/flb_storage.h
- src/flb_config.c
- src/flb_input_chunk.c
- src/flb_storage.c
This PR adds a configurable semi hard limit for the chunk files.
This will break chunks when they reach the limit but it will not break up a single ingestion that should span multiple chunks which means flb_input_chunk_append_raw should not be called with multi megabyte buffers.
>  tiger: chunk size limit addition

- include/fluent-bit/flb_engine_dispatch.h
- include/fluent-bit/flb_output.h
- src/flb_engine.c
- src/flb_engine_dispatch.c
This PR introduces a chunk withholding feature intended to ensure that
the oldest chunks can be disposed in case of extreme congestion.
> tiger: chunk rollover workaround

- plugins/out_opentelemetry/opentelemetry.c
fix memory leak when cmt_encode_opentelemetry_create fails:
```
[2023/05/18 10:55:04] [error] [output:opentelemetry:opentelemetry.0] Error encoding context as opentelemetry
^C[2023/05/18 10:55:15] [engine] caught signal (SIGINT)
[2023/05/18 10:55:15] [ warn] [engine] service will shutdown in max 10 seconds
[2023/05/18 10:55:15] [ info] [input] pausing storage_backlog.1
[2023/05/18 10:55:16] [ info] [engine] service has stopped (0 pending tasks)
[2023/05/18 10:55:16] [ info] [input] pausing storage_backlog.1
==17803==
==17803== HEAP SUMMARY:
==17803==     in use at exit: 92,948 bytes in 965 blocks
==17803==   total heap usage: 7,336 allocs, 6,371 frees, 3,424,151 bytes allocated
==17803==
==17803== 92,948 (56 direct, 92,892 indirect) bytes in 1 blocks are definitely lost in loss record 42 …
```
> out_opentelemetry: fix memory leak

- plugins/out_opentelemetry/opentelemetry.c
----
**Testing**
```
[SERVICE]
flush 1
grace 1
log_level info
storage.path chunks
[INPUT]
listen 0.0.0.0
port 3000
storage.type filesystem
#[OUTPUT]
[OUTPUT]
Name                     opentelemetry
Match                    *
Host                     collector
Port                     3030
Log_response_payload     false
compress gzip
tls                      off
tls.verify               off
Traces_uri               /v1/traces
#Logs_uri                 /v1/logs
#Metrics_uri              /v1/metrics
add_label                app fluent-bit
add_label                color blue
#storage.total_limit_size  90M
```
```
[2023/05/18 …
```
> out_opentelemetry: flush multiple traces from one chunk

- include/fluent-bit/flb_str.h
- src/tls/flb_tls.c
* tls uses dot trimmed tcp_host/proxied_host for vhost
* new rtrim() function
Fixes #7403
**Testing**
```
[SERVICE]
Daemon Off
Flush  1s
[INPUT]
Name   dummy
Tag    dummy.log
Samples 2
[OUTPUT]
Name                tcp
Host                logstash.redacted.com.
Port                5059
Format              json_lines
json_date_key       @timestamp
json_date_format    iso8601
Match               *
tls                 On
tls.verify          On
tls.ca_file         /tmp/ca.crt
tls.crt_file        /tmp/tls.crt
tls.key_file        /tmp/tls.key
tls.debug           4
[OUTPUT]
Name   stdout
Match  *
```
```
Fluent Bit v2.1.3
* Fluent Bit is a CNCF sub-project …
```
> TLS: using dot trimmed tcp_host/proxied_host for vhost

- plugins/in_node_exporter_metrics/ne_utils.c
This is because ne_utils_path_scan already concatenates the supplied mount point as a prefix for path.
We don't need to re-concatenate for path there.
Without this patch, sysfs path should be concatenated twice due to ne_utils_path_scan already set up sysfs included paths after executing glob.
Closes https://github.com/fluent/fluent-bit/issues/7342
----
**Testing**
```python
[INPUT]
Name node_exporter_metrics
metrics cpu 
scrape_interval 5
tag node_exporter
[OUTPUT]
Name stdout
Match node_exporter
```
```
Fluent Bit v2.1.3
* …
```
> in_node_exporter_metrics: Prevent to duplicate sysfs path for collecting metrics

- plugins/in_tail/tail.c
- plugins/in_tail/tail_file.c
This PR fixes a minor error in in_tail where it could access uninitialized 
memory in the pending data collector callback.
Additionally it corrects the teardown order so the log event encoders 
are disposed of after the multiline context (which uses one of them).
> in_tail: teardown and memory initialization fixes

- plugins/in_tail/tail.c
This PR fixes a minor error in in_tail where it could access uninitialized
memory in the pending data collector callback.
Note: this is a backport of #7441
> in_tail: added cleanup / initialization in the pending collector

- src/flb_processor.c
This PR fixes the misinterpretation of the result of the multiline filter callback when it returns FLB_FILTER_MODIFIED without setting the output variables.
Even the multiline filter should be fixed to not make the assumption that those variables are pre-primed this is the most pragmatic way of ensuring this bug doesn't get triggered by other filters.
> processor: added cleanup / initialization in the processor loop

- include/fluent-bit/flb_processor.h
- src/flb_processor.c
This PR adds a lock to each processor unit in order to prevent 
concurrency issues in multi worker output plugin deployments.
> processor: added limited concurrency support

- src/multiline/flb_ml.c
- tests/internal/multiline.c
This PR fixes a bug in the multiline core where it scheduled flush timer 
in the main pipeline thread rather than the scheduler pertaining to the 
thread it was being initialized on which affects both the tail input plugin 
when running in threaded mode and the multiline filter when used in 
a processor stack (where the input plugin is running in threaded mode).
Note: This is a backport of PR #7445
> multiline: make the multiline core use the appropriate scheduler

- plugins/in_emitter/emitter.c
This patch uses the scheduler instance from the thread local storage to determine if the filter creating the emitter instance is running in an input plugins thread to transparently switch over to the ring buffer based mechanism.
This is not a definitive solution, it's a workaround.
> in_emitter: added automatic threading detection workaround

- include/fluent-bit/flb_error.h
- include/fluent-bit/flb_reload.h
- src/flb_utils.c
- src/fluent-bit.c
During reloading, it needs to prevent to run hot-reloading due to some of cases cause invalid fluent-bit contexts.
This means that too frequent reloading causes invalid contexts and invalid event loops.
To fix this issue, we need to protect to call flb_reload during hot-reloading is in progress.
Related to https://github.com/fluent/fluent-bit/issues/7427.
----
**Testing**
```python
[SERVICE]
Flush        1
[INPUT]
Name dummy
Tag dummy.locals
[FILTER]
Match *
Record hostname ${HOSTNAME}
[OUTPUT]
Name  stdout
Match *
```
In another …
> reload: bin: Prevent too short interval of reloading

- src/flb_compression.c
This change addresses a corner case that arises when the last operation leaves the read buffer pointer at the end of the input buffer.
> compression: added buffer adjust step to get available size

- include/fluent-bit/flb_filter.h
- include/fluent-bit/flb_input_log.h
- include/fluent-bit/flb_input_metric.h
- include/fluent-bit/flb_input_trace.h
- include/fluent-bit/flb_output.h
- include/fluent-bit/flb_processor.h
- plugins/filter_rewrite_tag/rewrite_tag.c
- src/flb_input_log.c
- src/flb_input_metric.c
- src/flb_input_trace.c
- src/flb_processor.c
- tests/internal/processor.c
This PR adds the concept of processor stages which are just an index that's used to skip the stages that the record has already gone through when re-ingesting them (ie. filter_rewrite_tag) which allows us to resume the process and invoke any remaining processors as expected.
> processor: inline re-ingestion implementation

- .github/workflows/staging-build.yaml
- .github/workflows/staging-release.yaml
Addresses #7473 by verifying we both have an AppVeyor build and it is the right version.
It will fail as it cannot find the 2.1.4 binaries for example.
----
**Testing**
----
> workflows: add sanity check on release

- plugins/in_windows_exporter_metrics/we_logical_disk.c
This is a backport of https://github.com/fluent/fluent-bit/pull/7495.
----
**Testing**
----
> in_windows_exporter_metrics: Fix wrong metrics type of free megabytes [backport 2.0]

- plugins/in_kubernetes_events/kubernetes_events.c
- plugins/in_kubernetes_events/kubernetes_events.h
- plugins/in_kubernetes_events/kubernetes_events_conf.c
- plugins/in_kubernetes_events/kubernetes_events_sql.h
This adds the missing functionality for #7494.
This includes:
- Support for limit and continue.
- Saving state via the database.
- Configuration of the polling interval.
- Blocking of concurrent requests by a single instance.
There is also a fix for out-of-order events when using the plugin without a database to save the current state.
----
**Testing**
---- …
> in_kubernetes_events: merge in pending fixes and enhancements.

- .github/actionlint.yml
- .github/workflows/call-build-linux-packages.yaml
- .github/workflows/pr-package-tests.yaml
- packaging/build-config.json
Resolves #6978 and resolves #6300 by re-enabling ARM64 builds of Amazon Linux 2023 but also running all ARM builds on the actuated.dev runners. 
Guarded to only trigger for this repo rather than any forks.
This requires some additional infrastructure set up which needs capturing to ensure it is fully reproducible.
----
**Testing**
See package builds in the checks for demonstration of build time improvements.
AL2023 ARM64 actually completes now and in a fraction of the time: https://github.com/fluent/fluent-bit/actions/runs/5204502425/jobs/9388809859?pr=7527
----
> packaging: support ARM64 AL2023 builds via Actuated runners

- .github/workflows/README.md
Minor docs tweaks to add links to Equinix sponsoring the ARM builders.
----
> workflows: minor updates

- plugins/out_stackdriver/stackdriver.c
- plugins/out_stackdriver/stackdriver.h
- tests/runtime/data/stackdriver/stackdriver_test_trace_sampled.h
- tests/runtime/out_stackdriver.c
This adds support for processing the logging.googleapis.com/traceSampled
special field from the jsonPayload
Addresses: https://github.com/GoogleCloudPlatform/ops-agent/issues/459
----
**Testing** …
> out_stackdriver: process traceSampled special field

- plugins/in_emitter/emitter.c
- src/flb_compression.c
- src/flb_input_chunk.c
This patch is to remove 3 warnings.
```
fluent-bit/plugins/in_emitter/emitter.c:117:9: warning: unused variable ‘ret’ [-Wunused-variable]
117 |     int ret;
|         ^~~
```
```
fluent-bit/src/flb_input_chunk.c: In function ‘input_chunk_append_raw’:
fluent-bit/src/flb_input_chunk.c:1811:19: warning: format ‘%d’ expects argument of type ‘int’, but argument 5 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
1811 |         flb_debug("[input chunk] update output instances with new chunk size diff=%d, records=%zu, input=%s",
|                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1812 |                   real_diff, n_records, flb_input_name(in));
|                   ~~~~~~~~~
|                   |
|                   size_t {aka …
```
> in_emitter: remove unused variable

- .github/workflows/call-build-linux-packages.yaml
Fixes missing dependencies for AWS CLI: https://github.com/fluent/fluent-bit/actions/runs/5210374391/jobs/9401376498
----
**Testing**
Tested using this branch: https://github.com/fluent/fluent-bit/actions/runs/5211769160
----
> workflows: ensure we install AWS dependencies

- src/multiline/flb_ml.c
- tests/internal/multiline.c
we are flushing the stream buffer in case it is
different in two consecutive runs, which leads to
incorrect parsing of multiline logs where we have
messages from different streams (stderr & stdout for ex) interleaved
we also update the test case to match the expected output due to the change in flushing logic
Fixes #4387 
----
**Testing**
```
[INPUT]
Name tail
Path ../cri.log
Multiline.Parser cri
Read_from_head True
[OUTPUT]
name stdout
match *
```
```
2021-11-18T14:47:34.730908438+00:00 stdout P start B
2021-11-18T14:47:34.730908438+00:00 stdout F end B
2021-11-18T14:47:34.730939216+00:00 stdout P C 1
2021-11-18T14:47:34.735454549+00:00 …
```
> multiline: remove incorrect flush 

- plugins/in_node_exporter_metrics/ne_textfile_linux.c
----
**Testing**
```python
[SERVICE]
log_level       debug
[INPUT]
name            node_exporter_metrics
tag             fluentbit.metrics.${HOSTNAME}
collector.textfile.path /path/to/prom_payloads/prom_metrics/*/*.prom
metrics textfile
[OUTPUT]
name stdout
Match *
```
```
==511818== 
==511818== HEAP SUMMARY:
==511818==     in use at exit: 95,170 bytes in 702 blocks
==511818==   total heap usage: 16,152 allocs, 15,450 frees, 50,327,111 bytes allocated
==511818== 
==511818== LEAK SUMMARY:
==511818==    definitely lost: 0 bytes in 0 blocks
==511818==    indirectly lost: 0 bytes in 0 blocks
==511818== …
```
> in_node_exporter_metrics: textfile: Plug unhandled NULL case

- include/fluent-bit/flb_log_event_decoder.h
- include/fluent-bit/flb_log_event_encoder.h
- src/flb_log_event_decoder.c
- src/flb_log_event_encoder.c
This patch is to add strerror functions for log_event_encoder/decoder to output human readable error.
----
**Testing**
- [N/A] Set `ok-package-test` label to test for all targets …
> log_event_encoder: add strerror function for encoder

- src/multiline/flb_ml.c
- tests/internal/multiline.c
we are flushing the stream buffer in case it is
different in two consecutive runs, which leads to
incorrect parsing of multiline logs where we have
messages from different streams (stderr & stdout for ex) interleaved
#4387 
----
**Testing**
```
[INPUT]
Name tail
Path ../cri.log
Multiline.Parser cri
Read_from_head True
[OUTPUT]
name stdout
match *
```
cri.log:
```
2021-11-18T14:47:34.730908438+00:00 stdout P start B
2021-11-18T14:47:34.730908438+00:00 stdout F end B
2021-11-18T14:47:34.730939216+00:00 stdout P C 1
2021-11-18T14:47:34.735454549+00:00 stderr F some log message D in stderr part one
2021-11-18T14:47:34.735482854+00:00 stdout F …
```
> multiline: remove incorrect flush

- plugins/in_windows_exporter_metrics/we_logical_disk.c
free_megabytes metrics should increase/decrease its values. Using gauge type should be correct here instead of using counter type.
Closes https://github.com/fluent/fluent-bit/issues/7493
----
**Testing**
----
> in_windows_exporter_metrics: Fix wrong metrics type of free megabytes

- CMakeLists.txt
- cmake/platform_feature_checks.cmake
- plugins/in_exec/in_exec.c
- plugins/in_exec/in_exec.h
- plugins/in_exec/in_exec_win32_compat.h
Enable use of `fluent-bit` as a log-processing command wrapper by enhancing the `exec` plugin with options to exit on child process exit and propagate exit code.
Adds new options to `in_exec` plugin:
Exit_After_Oneshot [bool]
Propagate_Exit_Code [bool]
`Exit_After_Oneshot` implies` Oneshot` and causes `fluent-bit` to terminate when the command run by the `exec` plugin terminates.
`Propagate_Exit_Code` causes `fluent-bit` to exit with the same exit code as the on-shot child process it invoked, following the shell convention for handling of signal exits.
```
$ ./bin/fluent-bit -q -o stdout -i exec -p propagate_exit_code=true -p exit_after_oneshot=true -p command='echo some command output; exit 2' 
[0] exec.0: [[1681771813.322498607, {}], {"exec"=>"some command output"}]
$ echo $?
2
``` …
> plugins: exec: exit fluent-bit after oneshot and propagate exit code

- plugins/in_node_exporter_metrics/ne.h
- plugins/in_node_exporter_metrics/ne_systemd.c
On https://github.com/fluent/fluent-bit/issues/7506, a user reported glitching a place of floating point.
However, I investigated this issue and I found that some of the metrics of systemd tend not to be updated for a long time.
For example, if a systemd unit has an active state, other statues are not updated.
Additionally, for a long time, if it will not be changed the state of a systemd unit, the other activating, active, deactivating, and failed statues are not updated. The current mechanism tends to cause non-updated metrics.
So, we should touch systemd metrics on every interval for updating them.
----
**Testing**
```python
[SERVICE]
Flush …
```
> in_node_exporter_metrics: update systemd metrics regardless their states

- lib/cmetrics/CMakeLists.txt
- lib/cmetrics/src/cmt_encode_opentelemetry.c
> lib: cmetrics: upgrade to v0.6.2

- plugins/out_cloudwatch_logs/cloudwatch_logs.c
- plugins/out_cloudwatch_logs/cloudwatch_logs.h
> out_cloudwatch_logs: fix logic in free-ing log streams on shutdown

- src/aws/flb_aws_credentials_sts.c
> aws: sts_credentials: make STS response parsing less brittle by checking for the full XML end node

- plugins/out_s3/s3.c
> out_s3: fix wrong decrementing of INDEX when UploadPart fails

- .github/workflows/pr-image-tests.yaml
- dockerfiles/Dockerfile.windows
Fixes #7574 setting Chocolatey version to 1.4.0 since the version doesn't require .NET 4.8, also ensures the host version matches the container version.
----
**Testing**
----
> ci: set a version for Chocolatey

- .github/workflows/pr-image-tests.yaml
- dockerfiles/Dockerfile.windows
* ci: set a version for Chocolatey
fixes #7574 setting Chocolatey version to 1.4.0 since the version doesn't require .NET 4.8
* ci: added windows tests to pr image tests
* ci: changed build method
* ci: changed runner to windows 2019
* ci: add matrix for windows 2019 and 2022
* change job title
---------
----
**Testing**
----
> ci: set a version for Chocolatey (#7588) - 2.0 backport

- include/fluent-bit/flb_network.h
- src/flb_upstream.c
By default, Fluent Bit tries to deliver data as faster as possible and create TCP connections on-demand and in keepalive mode for performance reasons. In high-scalable environments, the user might want to control how many connections are done in parallel by setting a limit.
This patch implements a new configuration property called `net.max_worker_connections` that can be used in the output plugins sections, so Fluent Bit plugin, per worker, won't open more than `net.max_worker_connections` if it has been set. If the limit is reach, the output plugins will issue a retry.
Configuration example:
```
[OUTPUT]
name                splunk
match               *
splunk_token        abc
net.max_connections 10
```
Note that this feature works at upstream/plugin level, and the limit is applied for …
> upstream: new property to limit the amount of active TCP connections

- src/flb_downstream.c
This PR fixes a longstanding issue in the downstream component where it would not remove connections from the event loop if the stream didn't have the ASYNC flag which caused the event loop to constant activate resulting in service disruption.
> downstream: fixed the event loop registration detection mechanism

- .github/workflows/cron-scorecards-analysis.yaml
Resolves failing runs due to changes in OpenSSF scorecard action.
----
**Testing**
----
> workflows: fix up OpenSSF Scorecard workflow

- src/flb_log_event_decoder.c
This patch is to replace `free(3)`.
----
**Testing** …
> log_event_decoder: use flb_free

- include/fluent-bit/flb_log_event_decoder.h
This patch is to rename wrong function name.
It should be `flb_log_event_decoder_get_error_description`.
https://github.com/fluent/fluent-bit/blob/v2.1.6/src/flb_log_event_decoder.c#L304
It was reviewed and I thought it was fixed..
https://github.com/fluent/fluent-bit/pull/7539#discussion_r1225263275
----
**Testing**
If this is a change to packaging of containers or native binaries then please confirm it works …
> log_event_decoder: fix wrong api name

- plugins/out_gelf/gelf.c
This patch is to fix following valgrind error.
- Remove unused msgpack_unpacked
- Add missing `flb_log_event_decoder_destroy`
```
==17050== 
==17050== HEAP SUMMARY:
==17050==     in use at exit: 41,280 bytes in 10 blocks
==17050==   total heap usage: 1,693 allocs, 1,683 frees, 2,151,921 bytes allocated
==17050== 
==17050== 41,280 (280 direct, 41,000 indirect) bytes in 5 blocks are definitely lost in loss record 2 of 2
==17050==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==17050==    by 0xBB320C: msgpack_zone_new (zone.c:199)
==17050==    by 0xBB0CFC: template_callback_map (unpack.c:252)
==17050==    by 0xBB1567: template_execute (unpack_template.h:233)
==17050==    by 0xBB2C34: msgpack_unpack_next (unpack.c:677)
==17050==    by 0x2DC420: …
```
> out_gelf: fix releasing function handling

- plugins/out_syslog/syslog.c
This patch is to fix error verification after flb_log_event_decoder_next.
See also #7636 
No error verification except for test code.
----
**Testing**
```
$ …
```
> out_syslog: check error after flb_log_event_decoder_next

- src/config_format/flb_cf_yaml.c
- tests/internal/config_format_yaml.c
- tests/internal/data/config_format/yaml/issue_7559.yaml
Fixes #7559 
This patch is to fix yaml config file parser to handle 'customs' section.
----
**Testing**
```
customs:
- name: calyptia
pipeline:
inputs:
- name: fluentbit_metrics
scrape_interval: 30 …
```
> config_format: yaml: fix 'customs' section handling(#7559)

- plugins/in_kubernetes_events/kubernetes_events.h
Increase the default interval for `in_kubernetes_events` to 500 ms.
----
**Testing**
----
> in_kubernetes_events: increase interval to 500 milliseconds.

- plugins/in_kubernetes_events/kubernetes_events.c
- plugins/in_kubernetes_events/kubernetes_events.h
- plugins/in_kubernetes_events/kubernetes_events_conf.h
Add the `kube_namespace` parameter to specify a single namespace to listen to events for. This is crucial when listening to events with a service account that does not have cluster-wide permissions for events.
To create a token
```bash
kubectl create serviceaccount $SVC_ACCOUNT_NAME
kubectl create role $ROLE_EVENTS --verb=get,list --resource=events
kubectl create rolebinding $ROLE_EVENTS_BINDING \
--serviceaccount=system:serviceaccount:$NAMESPACE:$SVC_ACCOUNT_NAME \
--role=$ROLE_EVENTS
kubectl create token $SVC_ACCOUNT_NAME > token.txt
```
----
**Testing**
If this is a change to packaging of containers or native binaries then please confirm it …
> in_kubernetes_events: allow listening to a single namespace.

- plugins/in_kubernetes_events/kubernetes_events.c
When using `kubectl proxy` it is possible to not use a token and skip authentication. This patch allows setting `kube_token_file` as an empty string to avoid having to load the token file.
----
**Testing**
----
> in_kubernetes_events: allow setting kube_token_file as empty for use with kubectl proxy.

- plugins/in_kubernetes_events/kubernetes_events_conf.c
This patch is to fix leak when initialization failed.
```
$ valgrind --leak-check=full bin/fluent-bit -i kubernetes_events -p kube_url=ftp://hoge -o stdout
(snip)
==13078== 254 (48 direct, 206 indirect) bytes in 1 blocks are definitely lost in loss record 21 of 27
==13078==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==13078==    by 0x2A40D6: flb_calloc (flb_mem.h:95)
==13078==    by 0x2A8643: flb_ra_create (flb_record_accessor.c:307)
==13078==    by 0x3CAFF4: k8s_events_conf_create (kubernetes_events_conf.c:176)
==13078==    by 0x3C676F: k8s_events_init (kubernetes_events.c:728)
==13078==    by 0x1D4F74: input_thread (flb_input_thread.c:331)
==13078==    by 0x23025E: step_callback (flb_worker.c:43)
==13078==    by 0x4FD7B42: start_thread …
```
> in_kubernetes_events: call destructor when init failed

- plugins/custom_calyptia/calyptia.c
- plugins/in_calyptia_fleet/in_calyptia_fleet.c
Configure calyptia fleet via the custom calyptia plugin so we can set default values for 'host' and 'port' (set to the production calyptia cloud).
This should fix to #7523. It will require using the custom calyptia plugin instead of the input plugin, ie:
```bash
$ # old command line
$ docker run \
--rm -ti xxxx/fluent-bit \
-i calyptia_fleet \
-p API_KEY=$CALYPTIA_CLOUD_TOKEN \
-p fleet_id=bad53a0e-57a5-4ac4-8b40-0ae20bde49bc \
-p host=cloud-api.calyptia.com \
-p port=443 \
-p tls=on
$ # new command line
docker run \
--rm -ti xxxx/fluent-bit \
-C calyptia \
-p API_KEY=$CALYPTIA_CLOUD_TOKEN \
-p fleet_id=bad53a0e-57a5-4ac4-8b40-0ae20bde49bc
```
----
**Testing**
Before we can approve your change; please submit the …
> custom_calyptia: set defaults for calyptia fleet.

- include/CMakeLists.txt
When using/installing Golang fluent-bit bindings, we need to install config_format related headers if someone wanted to use config_format related feature on that bindings.
Those headers are tightly coupled for the internal headers.
This lack of installation of cf headers causes inconvenient failures.
----
**Testing**
----
> build: Install config_format headers

- plugins/filter_rewrite_tag/rewrite_tag.c
`flb_slist_entry_get` can return NULL which is not checked for at the moment. This fixes it.
----
**Testing**
- [N/A]] Example configuration file for the change
- [N/A]] Debug log output from testing the change
- [N/A]] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found
- [N/A]] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [N/A]] Set `ok-package-test` label to test for all targets (requires …
> filter_rewrite_tag: fix potential NULL dereference

- include/fluent-bit/flb_utils.h
- src/flb_custom.c
- src/flb_filter.c
- src/flb_input.c
- src/flb_output.c
- src/flb_utils.c
Currently, shared properties which is commonly used parameters by plugins are simply handled in input/filter/output/custom's set property functions. They don't free for duplicated string type of properties.
Without hot-reloading, they will be free-ed on termination.
With hot-reloading, they won't be free-ed during reloading.
This should cause memory leaks on every kicking on hot-reloadings.
Fixes  https://github.com/fluent/fluent-bit/issues/7457
----
**Testing**
```python
[SERVICE]
Flush        1
[INPUT]
Name dummy
Tag dummy.locals
Tag dummy.twice
Alias …
```
> utils: plugin: freeing properly for duplicated string shared properties

- plugins/in_elasticsearch/in_elasticsearch.c
- plugins/in_elasticsearch/in_elasticsearch.h
- plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
- plugins/in_elasticsearch/in_elasticsearch_bulk_prot.h
- tests/runtime/in_elasticsearch.c
Currently, in_elasticsearch just returns elasticasearch server version as `8.0.0`.
Some of elasticsearch/opensearch clients wants to newer version of its server.
This PR provides configurable option for elasticsearch server version.
----
**Testing**
```console
$ bin/fluent-bit -i elasticsearch -p port=9880 -pversion=8.1.2 -o stdout
```
Another terminal
```
$ curl localhost:9880/
{"version":{"number":"8.1.2","build_flavor":"Fluent Bit OSS"},"tagline":"Fluent Bit's Bulk API compatible endpoint"}
```
```
==189199== 
==189199== HEAP SUMMARY:
==189199==     in use at exit: 95,170 bytes in 702 blocks
==189199==   total heap usage: 2,842 allocs, …
```
> in_elasticsearch: provide version parameter for configurable server version

- plugins/in_windows_exporter_metrics/CMakeLists.txt
- plugins/in_windows_exporter_metrics/we.c
- plugins/in_windows_exporter_metrics/we.h
- plugins/in_windows_exporter_metrics/we_config.c
- plugins/in_windows_exporter_metrics/we_wmi.c
- plugins/in_windows_exporter_metrics/we_wmi.h
- plugins/in_windows_exporter_metrics/we_wmi_cpu_info.c
- plugins/in_windows_exporter_metrics/we_wmi_logon.c
- plugins/in_windows_exporter_metrics/we_wmi_service.c
- plugins/in_windows_exporter_metrics/we_wmi_service.h
- plugins/in_windows_exporter_metrics/we_wmi_system.c
- plugins/in_windows_exporter_metrics/we_wmi_thermalzone.c
Fixes https://github.com/fluent/fluent-bit/issues/6669
windows exporter should support service collector.
Our service collector should be WMI based collector for now.
Also, it has where clause support.
Not specifying where clause, service collector just retrieves entire service information on the local box.
----
**Testing**
```python
[SERVICE]
flush_interval 10s
[INPUT]
Name windows_exporter_metrics
scrape_interval 10s
metrics service
we.service.include {"Name":"docker","Name":"%Svc%", "Name":"%Service"}
we.service.where NOT Name LIKE 'UdkUserSvc%' AND NOT Name LIKE 'webthreatdefusersvc%' AND Name!='XboxNetApiSvc'
[OUTPUT]
Name stdout
```
``` …
```
> in_windows_exporter_metrics: Add service metrics support

- plugins/in_node_exporter_metrics/ne_cpu_linux.c
`node_cpu_core_throttles_total` and `node_cpu_package_throttles_total` metrics are not existing in the Virtual Machine (VM) environment,
In VM environment, they are just missing.
So, when they are absent, we should handle to output this issue with debug messages and not to handle as error.
The official node_exporter uses the same approach:
https://github.com/prometheus/node_exporter/blob/master/collector/cpu_linux.go#L267-L287
Fixes https://github.com/fluent/fluent-bit/issues/7589.
----
**Testing**
```console
$ bin/fluent-bit -i node_exporter_metrics -pmetrics=cpu -o stdout
```
```
==564825== 
==564825== HEAP SUMMARY:
==564825==     in use at …
```
> in_node_exporter_metrics: handle not as error when missing cpu_throttle_metrics

- lib/cmetrics/CMakeLists.txt
- lib/cmetrics/src/cmt_decode_opentelemetry.c
> lib: cmetrics: upgrade to v0.6.3

- plugins/filter_kubernetes/kube_meta.c
> in_kubernetes_filter: fix leak on exception

- .github/workflows/pr-fuzz.yaml
This will make it easier to interpret the output of CIFuzz by making it possible to view the result in the Github security page.
----
**Testing**
- [N/A] Set `ok-package-test` label to …
> workflows: enable sarif output for CIFuzz

- plugins/in_exec_wasi/in_exec_wasi.c
`tmpfile()` can return NULL and this is not checked for at the moment. If indeed it returns NULL then the call on line 70 `fileno(stdoutp)` will cause a NULL dereference.
----
**Testing**
- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) …
> in_exec_wasi: fix possible NULL deref

- src/aws/flb_aws_imds.c
Backports fix in #7683 to 2.0.
----
**Testing** …
> backport: aws: imds: set length when initializing token to dummy value

- src/flb_upstream.c
In the previous version a new option called net.max_worker_connections was introduced to provide control around the maximum number of allowed TCP connections per worker inside an output plugin, the logic was wrong.
In the upstream logic, connections are linked to one of these lists:
- av_queue  : connections ready to be used (available)
- busy_queue: connections that are busy (someone is using them)
- drop_queue: connections in the cleanup phase (to be drop)
Fluent Bit don't create connections ahead of time, just on demand. When a connection is created is placed into the busy_queue, when is not longer needed one of these things happen:
- if keepalive is enabled (default), the connection is moved to the 'av_queue'.
- if keepalive is disabled, the connection is moved to 'drop_queue' then is …
> upstream: fix logic to restrict number of connections

- plugins/out_stackdriver/stackdriver.c
- plugins/out_stackdriver/stackdriver.h
- plugins/out_stackdriver/stackdriver_conf.c
> out_stackdriver: support gzip compression

- CODEOWNERS
This PR adds the Google contributors to CODEOWNERS for the `out_stackdriver` plugin.
----
**Testing**
- [N/A] Set `ok-package-test` label to test for all targets (requires maintainer …
> CODEOWNERS: Add codeowners for out_stackdriver

- CODEOWNERS
Take over Code ownership of the Calyptia and Calyptia Fleet.
----
**Testing** …
> codeowners: add pwhelan for calyptia and calyptia fleet.

- CODEOWNERS
In the previous PR I forgot to add Google owners to the `out_stackdriver` tests as well. I also accidentally put the row in the AWS section before so I've fixed that here.
----
**Testing**
----
> CODEOWNERS: Google owners for out_stackdriver test

- src/flb_downstream.c
This patch is to fix following warning.
```
[ 70%] Building C object src/CMakeFiles/fluent-bit-shared.dir/flb_downstream.c.o
/home/taka/git/fluent-bit/src/flb_downstream.c: In function ‘prepare_destroy_conn’:
/home/taka/git/fluent-bit/src/flb_downstream.c:184:24: warning: variable ‘stream’ set but not used [-Wunused-but-set-variable]
184 |     struct flb_stream *stream;
|
```
----
**Testing**
If this is a change …
> downstream: remove not used variable

- .github/workflows/call-build-windows.yaml
This is because Chocolatey only supports x64 installation after OpenSSL 3.1.1 package.
ref: https://community.chocolatey.org/packages/openssl/3.1.1#files
The CI result is:
https://github.com/fluent/fluent-bit/actions/runs/5596570106/jobs/10233770791
----
**Testing**
----
> build: Install OpenSSL with chocolatey only for x64

- plugins/in_tail/tail_file.c
I was getting the following errors when threaded was enabled for input tail plugin while using multiline.parser.
```
[2023/07/18 22:44:53] [error] [/usr/src/fluent-bit/src/flb_input_chunk.c:1875 errno=11] Resource temporarily unavailable
[2023/07/18 22:44:53] [error] [/usr/src/fluent-bit/src/flb_input_chunk.c:1875 errno=11] Resource temporarily unavailable
[2023/07/18 22:44:53] [error] [/usr/src/fluent-bit/src/flb_input_chunk.c:1875 errno=11] Resource temporarily unavailable
[2023/07/18 22:44:53] [error] [/usr/src/fluent-bit/src/flb_input_chunk.c:1875 errno=11] Resource temporarily unavailable
[2023/07/18 22:44:53] [error] [/usr/src/fluent-bit/src/flb_input_chunk.c:1875 errno=11] Resource temporarily unavailable
[2023/07/18 22:44:53] [error] [/usr/src/fluent-bit/src/flb_input_chunk.c:1875 …
```
> in_tail: Don't append records if sl_log_event_encoder buffer is 0

- plugins/in_calyptia_fleet/in_calyptia_fleet.c
Due to the change in #7524 the `calyptia_fleet` input plugin is now private. The reload configuration was still using that plugin. Fix it to use the custom calyptia plugin instead.
----
**Testing**
----
> calyptia_fleet: fix non existent plugin name.

- plugins/in_splunk/splunk_prot.c
This patch is to fix following warnings.
```
[ 59%] Building C object plugins/in_splunk/CMakeFiles/flb-plugin-in_splunk.dir/splunk_prot.c.o
/home/taka/git/fluent-bit/plugins/in_splunk/splunk_prot.c: In function ‘process_json_payload_pack’:
/home/taka/git/fluent-bit/plugins/in_splunk/splunk_prot.c:317:9: warning: unused variable ‘ret’ [-Wunused-variable]
317 |     int ret;
|         ^~~
/home/taka/git/fluent-bit/plugins/in_splunk/splunk_prot.c: In function ‘process_hec_raw_payload’:
/home/taka/git/fluent-bit/plugins/in_splunk/splunk_prot.c:549:9: warning: variable ‘type’ set but not used [-Wunused-but-set-variable]
549 |     int type = -1;
|         ^~~~
In file included from /home/taka/git/fluent-bit/plugins/in_splunk/splunk_prot.c:20: …
```
> in_splunk: fix warnings

- plugins/in_tail/tail.c
Fix the description of `ignore_older`. It works at the file level, based on the modification date.
----
> in_tail: fix ignore_older description.

- examples/kafka_filter/Dockerfile
- examples/kafka_filter/kafka.conf
- plugins/in_kafka/in_kafka.c
- plugins/in_kafka/in_kafka.h
This fixes json parsing for in_kafka, also add `data_format` configuration option, for explicit parsing control.
Fixes #7481
> in_kafka: Fix in kafka json parsing

- plugins/in_http/http_prot.c
Add support for `Content-Type:application/x-www-form-urlencoded` to the `in_http` plugin.
This PR addresses #5385.
----
**Testing**
----
> in_http: add support for form/url_encoded payloads.

- plugins/in_collectd/in_collectd.c
- plugins/in_statsd/statsd.c
Add the FLB_INPUT_NET_SERVER to the `in_collectd` and `out_statsd` plugins, which do use UDP instead of TCP, so the schema includes the network properties for them. 
The `FLB_IO_TLS` flag should not and is not set which should avoid most special cased code. If not we need another way to express they use network properties so the correct schema and help options can be output for them.
----
**Testing**
---- …
> in_collectd/out_statsd: set the FLB_INPUT_NET_SERVER flag to fix their schema.

- include/fluent-bit/flb_callback.h
- include/fluent-bit/flb_luajit.h
- include/fluent-bit/flb_thread_pool.h
- include/fluent-bit/flb_utils.h
- plugins/filter_kubernetes/kubernetes.c
- plugins/filter_modify/modify.c
- plugins/filter_multiline/ml.c
- plugins/filter_nightfall/nightfall.c
- plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
- plugins/in_event_type/event_type.c
- plugins/in_forward/fw_prot.c
- plugins/in_head/in_head.c
- plugins/in_mqtt/mqtt_prot.c
- plugins/in_splunk/splunk_prot.c
- plugins/out_azure_logs_ingestion/azure_logs_ingestion.c
- plugins/out_prometheus_remote_write/remote_write.c
- plugins/out_splunk/splunk.c
- src/flb_help.c
- src/flb_input.c
- src/flb_network.c
- src/flb_reload.c
- src/flb_snappy.c
- src/flb_storage.c
- src/flb_strptime.c
- src/flb_time.c
- src/stream_processor/flb_sp.c
> core: fix some compiler warnings

- src/fluent-bit.c
Quick update for the trace command line options help.
----
**Testing**
----
> chunk_traces: update the help for '--enable-chunk-trace'.

- include/fluent-bit/flb_connection.h
- src/flb_connection.c
- src/flb_upstream.c
This PR addresses an issue caused by `flb_upstream_conn_timeouts` when a connection times out in a cycle where  `FLB_ENGINE_LOOP_MAX_ITER` is exceeded. 
What this means is the priority event loop will defer processing of the event for the next overall iteration which happens after `flb_upstream_conn_pending_destroy_list` is invoked by the thread which results in a coroutine being left suspended indefinitely.
The main issue was that `flb_upstream_conn_timeouts` immediately performed most of the connection disposal and marked the connection to be reaped at the end of the cycle.
In order to prevent this while retaining some of the required functionality we now only perform the connection shutdown and inject an event in order to force the engine to resume the coroutine as soon as possible.
> upstream: premature connection destruction fix

- plugins/custom_calyptia/calyptia.c
- plugins/in_calyptia_fleet/in_calyptia_fleet.c
This PR adds the parameter `fleet_name` which allows registering an instance of fluent-bit with a fleet using it's name instead by ID.
----
**Testing**
----
> custom_calyptia: allow registering fleets by name instead of id.

- plugins/in_syslog/syslog.c
- plugins/in_syslog/syslog.h
- plugins/in_syslog/syslog_conn.c
- plugins/in_syslog/syslog_prot.c
- plugins/in_syslog/syslog_prot.h
- tests/runtime/in_syslog.c
Closes https://github.com/fluent/fluent-bit/issues/7581
Currently, in_syslog plugin does not offer adding source address feature.
This PR provides this feature.
----
**Testing**
```python
[SERVICE]
Parsers_File  /path/to/parsers.conf # For example, /etc/fluent-bit/parsers.conf
[INPUT]
Name syslog
Port 5140
Listen   0.0.0.0
Parser syslog-rfc5424
Mode     tcp
Source_Address_Key source_host
[OUTPUT]
Name stdout
```
```log
Fluent Bit v2.1.7
[2023/07/05 19:01:35] [ info] Configuration:
[2023/07/05 19:01:35] [ …
```
> in_syslog: Provide appending source address parameter

- src/fluent-bit.c
This patch is to fix following valgrind error.
```
==20919== 
==20919== HEAP SUMMARY:
==20919==     in use at exit: 7 bytes in 1 blocks
==20919==   total heap usage: 1,572 allocs, 1,571 frees, 968,794 bytes allocated
==20919== 
==20919== 7 bytes in 1 blocks are still reachable in loss record 1 of 1
==20919==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==20919==    by 0x18E880: flb_malloc (flb_mem.h:80)
==20919==    by 0x18EB6A: flb_strndup (flb_str.h:34)
==20919==    by 0x18EBD1: flb_strdup (flb_str.h:46)
==20919==    by 0x1912B7: flb_main (fluent-bit.c:949)
==20919==    by 0x192012: main (fluent-bit.c:1375)
==20919== 
==20919== LEAK SUMMARY:
==20919==    definitely lost: 0 bytes in 0 blocks
==20919==    indirectly lost: 0 bytes in 0 blocks …
```
> fluent-bit: remove cleanup code from flb_signal_exit

- .github/workflows/build-legacy-branch.yaml
- .github/workflows/call-build-images.yaml
- .github/workflows/call-integration-image-build.yaml
- .github/workflows/pr-compile-check.yaml
- .github/workflows/pr-image-tests.yaml
Resolves #7748 by ensuring the registry will provide images in a legacy and non-OCI format, i.e. Docker v1 & v2.
----
**Testing**
----
---
- https://app.asana.com/0/0/1205158744450533
> workflows: disable provenance for legacy format images

- .github/workflows/staging-release.yaml
Addresses #7748 by having a fallback to future proof any further unknown updates to CI actions.
We push arch-specific tags (the images will already be there so this should just add an extra tag for those specific digests rather than have to push anything) as a fallback via basic:
- `docker pull --platform=linux/[amd64|arm64|arm/v7] fluent/fluent-bit:<version>`
- `docker tag fluent/fluent-bit:<version> [docker.io|ghcr.io]/fluent/fluent-bit:<version>-[amd64|arm64|arm-v7]`
- `docker push [docker.io|ghcr.io]/fluent/fluent-bit:<version>-[amd64|arm64|arm-v7]`
It means for a 2.1.9 release we get the current multi-arch manifest plus the specific arch tags:
- `fluent/fluent-bit:2.1.9`
- `fluent/fluent-bit:2.1.9-amd64`
- `fluent/fluent-bit:2.1.9-arm64`
- `fluent/fluent-bit:2.1.9-amd-v7`
----
Enter …
> workflows: add extra push of arch-specfic images

- .github/workflows/call-build-windows.yaml
Recently, I migrated to use vcpkg to install OpenSSL in Windows 32bit.
Also, I migrate to use vcpkg for same operations in Windows 64bit.
GitHub Actions result is: https://github.com/fluent/fluent-bit/actions/runs/5688172289
----
**Testing**
----
> workflows: windows: Use vcpkg to install dependencies

- .github/workflows/call-build-windows.yaml
Currently, nasm.us is occasionally down.
To improve our CI stability, we have to implement caching mechanism for source packages to stabilize vcpkg installations.
CI result is here: https://github.com/fluent/fluent-bit/actions/runs/5710860698
----
**Testing**
----
> workflows: windows: Implement cache mechanism for source packages of vcpkg

- .github/workflows/call-build-windows.yaml
The previous PR #7773 might not handle restoring caches for vcpkgs correctly.
Adding `restore-keys` should handle to restore the caches of vcpkg.
It behaves for the searching prefix for specifying which is the most appropriate cache.
CI result is here:
* Restoring: https://github.com/fluent/fluent-bit/actions/runs/5734470706/job/15540703740#step:7:62
* Saving: https://github.com/fluent/fluent-bit/actions/runs/5734470706/job/15540703740#step:10:54 (already existed
another cache which already had been created with the same key)
----
**Testing** …
> workflow: windows: Make more rigid handling for caches

- plugins/out_stackdriver/stackdriver.c
This fixes the access token caching in the out_stackdriver plugin.
Signed-off-by: Ridwan Sharif <ridwanmsharif@google.com>
----
**Testing**
```
==20035== Memcheck, a memory error detector
==20035== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==20035== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==20035== Command: bin/fluent-bit -v --config /run/google-cloud-ops-agent-fluent-bit/fluent_bit_main.conf --parser /run/google-cloud-ops-agent-fluent-bit/fluent_bit_parser.conf --log_file /var/log/google-cloud-ops-agent/subagents/logging-module.log --storage_path …
```
> out_stackdriver: fix access token caching

- CODEOWNERS
adds celalettin1286 to codeowners
----
**Testing**
----
> ci: add codeowner celalettin1286

- plugins/in_prometheus_scrape/prom_scrape.c
- plugins/in_prometheus_scrape/prom_scrape.h
This PR adds both regular HTTP and Bearer authorization to the prometheus scrape input plugin.
> in_prometheus_scrape: added authorization support

- src/config_format/flb_config_format.c
The return value of `strchr` is not checked for failure. If it's failure then `tmp` will be `0` in the `(tmp-p)` calculation, causing `xlen` to be `p`. `xlen` is later  used for copying memory by way of `memcpy` in string creation using `flb_sds_create_len`. This fixes it.
----
**Testing**
- [N/A] Run …
> config_format: fix possible heap overflow

- tests/internal/fuzzers/utils_fuzzer.c
Extnd the `utils_fuzzer` with an additional string split operation.
----
**Testing** …
> tests: fuzzers: utils_fuzzer: extend

- tests/internal/fuzzers/cmetrics_decode_fuzz.c
Extend cmetrics_fuzzer so it reaches prometheus decoding logic as well.
----
**Testing** …
> tests: internal: fuzzers: cmetrics_fuzzer: extend

- tests/internal/fuzzers/CMakeLists.txt
- tests/internal/fuzzers/input_fuzzer.c
Add fuzzer dedicated to input chunk fuzzing. Although much of the logic is covered already, it would be nice to have something more dedicated.
----
**Testing**
- [N/A] Set …
> tests: internal: fuzzers: add input fuzzer

- src/flb_utils.c
When retrieving the machine_id for agents, and in some other rare cases, the following error can be spuriously reported:
This pushes out the error log so it is not reported when not necessary.
----
**Testing**
----
---
- https://app.asana.com/0/0/1205215063623017
> flb_utils: remove false positive error 'file not found'.

- src/aws/flb_aws_util.c
This issue is reported by addrress sanitizer on macOS.
On Linux, this isue won't be happened.
```
Test flb_get_s3_key_invalid_key_length...       [2023/07/31 17:50:07] [ warn] [s3_key] Object key length is longer than the 1024 character limit.
=================================================================
==67093==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x000109409580 at pc 0x000106924088 bp 0x00016b48e020 sp 0x00016b48d7e0
READ of size 1025 at 0x000109409580 thread T0
#0 0x106924084 in wrap_strlen+0x164 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x18084) (BuildId: f0a7ac5c49bc3abc851181b6f92b308a32000000200000000100000000000b00)
#1 0x1049899b0 in flb_get_s3_key flb_aws_util.c:923
#2 0x10497fa18 in test_flb_get_s3_key_invalid_key_length aws_util.c:278
#3 0x10497cbe8 in …
```
> aws: macos: prevent buffer overflow on address sanitier

- plugins/out_kinesis_firehose/firehose_api.c
- plugins/out_kinesis_streams/kinesis_api.c
Fixes #7790 
Thoughput -> Throughput
----
**Testing** …
> out_kinesis: fix typo

- include/fluent-bit/flb_input_thread.h
- src/flb_input.c
- src/flb_input_chunk.c
- src/flb_input_thread.c
Fixes #7071
I was getting the following error.
```
[2023/08/09 06:48:50] [ warn] [input] tail.0 paused (mem buf overlimit)
[2023/08/09 06:48:50] [ info] [input] tail.0 resume (mem buf overlimit)
[2023/08/09 06:48:50] [ warn] [input] tail.0 paused (mem buf overlimit)
[2023/08/09 06:48:50] [error] [input] cannot resume collector tail.0:2, already running
```
Log processing would start going to standstill once the "cannot resume collector" line was logged.
After looking at the code, I found a race condition around pause/resume.
flb_input_pause sends a signal to input thread event loop
https://github.com/fluent/fluent-bit/blob/v2.1.8/src/flb_input.c#L1673
flb_input_resume is done by the main thread instead of sending signal to input thread event loop …
> input: send resume signal to the input thread event loop if plugin is threaded

- src/flb_config.c
Add a one-liner so if for some reason a property is not properly checked or applied an error is raised nonetheless.
With this configuration:
```yaml
---
pipeline:
inputs:
- name: dummy
dummy:
message: '{"message: "my custom dummy"}'
outputs:
- name: stdout
match: "*"
format: json_lines
```
Without this change the fact that `dummy` is set as a key/value map is silently ignored, even though it is set as a string in the dummy plugin `config_map`. This change does not check the types but at least it does raise an error when the type is ignored, ie:
```shell
./bin/fluent-bit -c bad-dummy.yml
Fluent Bit v2.1.8
[2023/08/02 15:44:22] [error] [config] could not …
```
> config: throw an error if a configuration property is not applied.

- plugins/in_windows_exporter_metrics/CMakeLists.txt
- plugins/in_windows_exporter_metrics/we.c
- plugins/in_windows_exporter_metrics/we.h
- plugins/in_windows_exporter_metrics/we_wmi_memory.c
- plugins/in_windows_exporter_metrics/we_wmi_memory.h
- plugins/in_windows_exporter_metrics/we_wmi_paging_file.c
- plugins/in_windows_exporter_metrics/we_wmi_paging_file.h
Currently, there is no memory and paging file metrics to debug memory related issues as describe in:
https://github.com/fluent/fluent-bit/issues/5337#issue-1211255889.
To achieve this, I added two metrics which is memory and paging_file metrics.
They can use to debug memory related issues.
Closes: https://github.com/fluent/fluent-bit/issues/5337
----
**Testing**
These metrics can used as:
```powershell
PS> bin/fluent-bit -i windows_exporter_metrics -pmetrics=memory -pscrape_interval=2 -o stdout -vv
PS> bin/fluent-bit -i windows_exporter_metrics -pmetrics=paging_file -pscrape_interval=2 -o stdout
```
```console
PS> bin/fluent-bit -i …
```
> in_windows_exporter_metrics: Implement WMI based memory and paging_file metrics

- include/fluent-bit/flb_coro.h
- plugins/in_event_test/event_test.c
In macOS, the size of pthread stack min of Intel Mac (x64) and Apple Silicon (M1/M2) is smaller than the Linux one.
This means that the concrete values are:
PTHREAD_STACK_MIN = 8192
(3 * PTHREAD_STACK_MIN) / 2 = 12288 which means fluent-bit's minimum stack size
PTHREAD_STACK_MIN = 16384
(3 * PTHREAD_STACK_MIN) / 2 = 24576 which means fluent-bit's minimum stack size
They shouldn't be enough for libresolv API which needs to use heap memories: `res_ninit(statep)`.
When increasing the coroutine size to:
24576 bytes (24KiB) on Intel Mac and 36864 bytes (36KiB) on Apple Silicon respectively, the heap memory corruptions are not occurred.
Related to https://github.com/fluent/fluent-bit/issues/7670.
I tested for the minimum code:
```c
#include <limits.h>
#ifdef …
```
> macos: core: macOS coroutine unstability fixes

- include/fluent-bit/flb_processor.h
- src/config_format/flb_cf_yaml.c
- src/config_format/flb_config_format.c
- src/flb_processor.c
- tests/internal/config_format_yaml.c
- tests/internal/data/config_format/yaml/fluent-bit.yaml
- tests/internal/data/config_format/yaml/parsers/parsers-conf.yaml
- tests/internal/data/config_format/yaml/parsers/parsers.conf
- tests/internal/data/config_format/yaml/pipelines/slist/even.yaml
- tests/internal/data/config_format/yaml/pipelines/slist/odd.yaml
- tests/internal/processor.c
This PR includes a refactoring of the YAML parser to use a stack based parser instead of using a single state that is continuously modified. 
This simplifies the code as well as allowing the reuse of code where appropriate, ie: properties for customs, inputs, filters, outputs, processors.
I also introduced debug output for the parser which requires a modification to fluent-bit to allow setting verbose mode when parsing command line arguments. A PR to do so is forthcoming.
----
**Testing**
----
Fluent …
> yaml/v2: use stack based parser.

- CMakeLists.txt
- tests/internal/fuzzers/CMakeLists.txt
- tests/internal/fuzzers/config_yaml_fuzzer.c
> tests: internal: fuzzers: add config yaml fuzzer

- tests/internal/fuzzers/CMakeLists.txt
- tests/internal/fuzzers/flb_mp_fuzzer.c
> tests: internal: fuzzers: add mp fuzzer

- plugins/filter_multiline/ml.c
- plugins/filter_rewrite_tag/rewrite_tag.c
Minor bugfix/cleanup
Noticing that [the input instance is destroyed here on fail](https://github.com/fluent/fluent-bit/blob/5686334b56ee9d92f0654b0a621113943b175b94/plugins/filter_rewrite_tag/rewrite_tag.c#L81) but not [here, later in the code](https://github.com/fluent/fluent-bit/blob/5686334b56ee9d92f0654b0a621113943b175b94/plugins/filter_rewrite_tag/rewrite_tag.c#L100), I spoke with @leonardo-albertovich.
There is a [global teardown for input instances](https://github.com/fluent/fluent-bit/blob/5686334b56ee9d92f0654b0a621113943b175b94/src/flb_engine.c#L1086), but regardless this cleanup should happen on exit as a best practice and in case that behavior changes. Also, "filters included in the processor stack unlink themselves from the global list" so would may not be cleaned up in the …
> emitter_create: exit and destroy instance on fail

- plugins/out_kinesis_streams/kinesis_api.c
`tmp_size` is assigned twice where each of the assignments are not used.
----
**Testing** …
> out_kinesis_streams: remove dead stores

- plugins/in_winevtlog/in_winevtlog.c
- plugins/in_winevtlog/winevtlog.c
- plugins/in_winevtlog/winevtlog.h
I implemented XML query capability for filtering Windows EventLog.
This is because filter_grep and type converter should be difficult to use when the types of records are unknown.
Instead, we also are able to provide a capability of XML query language to filter events.
EvtSubscribe API which is defined in winevt.h can handle that XML query.
ref: https://learn.microsoft.com/en-us/windows/win32/api/winevt/nf-winevt-evtsubscribe
The advantage of the parameter is using in_winevtlog plugin only and not consuming for unneeded events on that plugin.
This feature is also a parity of fluent-plugin-windows-eventlog plugin's event_query parameter: https://github.com/fluent/fluent-plugin-windows-eventlog#configuration
This is related to https://github.com/fluent/fluent-bit/issues/7271.
----
Enter …
> in_winevtlog: Support XML query parameter for filtering events

- plugins/custom_calyptia/calyptia.c
- plugins/in_calyptia_fleet/in_calyptia_fleet.c
Submit metrics to calyptia cloud when not in fleet mode.
----
**Testing**
----
---
- https://app.asana.com/0/0/1205285584289449
> calyptia: submit metrics when not in fleet mode.

- include/fluent-bit/flb_lua.h
- src/flb_lua.c
- tests/internal/lua.c
I need a debug function to add new feature for flb_lua to fix issue 7708.
- add `flb_lua_dump_stack`
- modify `flb_lua_arraylength` to be able to pass index of stack
- add `flb_lua_absindex` 
`flb_lua_dump_stack` is to dump lua stack for debug.
It needs to modify `flb_lua_arraylength` since the function expects an array should be on the top of the stack.
`flb_lua_dump_stack` needs to dump an array in the middle of the stack.
This patch also supports `flb_lua_absindex`.
In some cases, we use negative index to point from a top of the stack. e.g. `lua_next(l, -2)` of `flb_lua_arraylength`.
It can cause an error when the top of stack is added/deleted.
`flb_lua_absindex` is to prevent it since it returns a positive index from the bottom of the stack.
---- …
> lua: add dump lua stack function and extract flb_lua_arraylength

- plugins/in_exec_wasi/in_exec_wasi.c
> in_exec_wasi: fix possible file descriptor leak

- src/config_format/flb_cf_yaml.c
During development to debug the parser many messages were left as error messages. This is due to the fact that the log level is not actually configured in `flb_main` until after parsing configuration files. I will open a PR with a possible fix for that later. For now the messages will be demoted to debugging for now.
----
**Testing**
----
> yaml/v2: suppress debug messages.

- include/fluent-bit/config_format/flb_cf.h
- src/config_format/flb_cf_fluentbit.c
- src/config_format/flb_cf_yaml.c
- src/config_format/flb_config_format.c
- tests/internal/config_format_fluentbit.c
- tests/internal/config_format_yaml.c
The current Yaml reader is agnostic from the keys format, it only cares to convert them to lower
case so the backend layer can configure the properties properly. The following is an non-idiomatic
example:
```yaml
env:
flushInterval: 1
service:
flush: ${flushInterval}
pipeline:
inputs:
- name: random
Interval_Sec: 1
filters:
- name: record_modifier
match: "*"
record: powered_by calyptia
uuid_key: abc
outputs:
- name: stdout
match: "*"
```
The following patch make the Yaml parser to be idiomatic by supporting a compatible layer with
camelCase style for key names, e.g:
```yaml
env:
flushInterval: 1
service:
flush: ${flushInterval}
pipeline:
inputs:
- name: random
intervalSec: 1
filters:
- name: record_modifier
match: "*"
record: powered_by calyptia
uuidKey: abc
outputs:
- name: stdout
match: …
```
> config_format: yaml: add support for idiomatic Yaml camelCase (fix #7593)

- plugins/out_splunk/splunk.c
This PR fixes a memory leak in the splunk output plugin that triggers when the key provided in the `event_key` option does not match a map key in the log event body.
> out_splunk: release flb_ra_translate result buffer on failure
