fluent/fluent-bit

src/config_format/flb_cf_yaml.c
The NULL check has to happen before the call to `strcmp` as otherwise a NULL dereference exists in `strcmp`.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=61733
----
**Testing**
- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new …
=> config_format: yaml: fix null dereference

plugins/in_node_exporter_metrics/ne.c
Fixed for registering callback settings for systemd metrics.
----
**Testing**
fluent-bit starts with: `valgrind bin/fluent-bit -i node_exporter_metrics -p metrics=systemd -o stdout`
```
==85698== 
==85698== HEAP SUMMARY:
==85698==     in use at exit: 0 bytes in 0 blocks
==85698==   total heap usage: 128,161 allocs, 128,161 frees, 6,672,526,968 bytes allocated
==85698== 
==85698== All heap blocks were freed -- no leaks are possible
==85698== 
==85698== For lists of detected and suppressed errors, rerun with: -s
==85698== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
``` …
=> in_node_exporter_metrics: Fix registering callback for systemd metrics

plugins/in_windows_exporter_metrics/CMakeLists.txt, plugins/in_windows_exporter_metrics/we.c, plugins/in_windows_exporter_metrics/we.h, plugins/in_windows_exporter_metrics/we_config.c, plugins/in_windows_exporter_metrics/we_wmi_process.c, plugins/in_windows_exporter_metrics/we_wmi_process.h
To monitor per process work loads, we need to implement process metrics on in_windows_exporter_metrics plugin.
Closes https://github.com/fluent/fluent-bit/issues/7855
----
**Testing**
```ini
[SERVICE]
flush_interval 10s
[INPUT]
Name windows_exporter_metrics
scrape_interval 2s
metrics process
we.process.allow_process_regex /firefox|svchost/
[OUTPUT]
Name stdout
```
https://github.com/fluent/fluent-bit-docs/pull/1182
----
Fluent Bit is licensed under Apache 2.0, by submitting this pull …
=> in_windows_exporter_metrics: Implement WMI based process metrics

plugins/in_tail/tail.c, plugins/in_tail/tail_file.c, plugins/in_tail/tail_fs_inotify.c
This PR addresses two individual issues : 
1. When `ignore_older` is set and a file that was deemed viable is being ingested (while no one is appending data to it) fluent-bit will drop the file as soon as the modification time exceeds the limit imposed by `ignore_older`.
2. When a file is being ingested in event mode yet it's not being written to, the ingestion rate is severely limited by the progress timer frequency.
It's important to keep in mind that point number one has been a long standing default behavior which means changing it could cause disruptions so please, request the change if we need to add a new option to opt-out of the old behavior.
---
- https://app.asana.com/0/0/1205273257137240
=> in_tail: ingestion interruption fix

plugins/in_lib/in_lib.c
This patch is to fix error verification after flb_log_event_decoder_next.
See also https://github.com/fluent/fluent-bit/issues/7636
----
**Testing**
- [N/A] Set `ok-package-test` label …
=> in_lib: fix error handling after flb_log_event_decoder_next

src/flb_io.c, src/flb_upstream.c, src/tls/openssl.c
This PR adds error code propagation for some non-recoverable errors which previously caused broken keepalive connections to be returned to the idle connection queue.
=> io: keepalive error detection improvement

plugins/in_nginx_exporter_metrics/nginx.c
This patch is to add missing releasing function.
----
**Testing**
- [N/A] …
=> in_nginx_exporter_metrics: add missing release function

plugins/custom_calyptia/calyptia.c, plugins/in_calyptia_fleet/in_calyptia_fleet.c, plugins/out_calyptia/calyptia.c
Refactor the logic behind the machine_id in the calyptia plugins so it is generated by `custom_calyptia` so that it is consistent across all of them and can be used by `in_calyptia_fleet` for the purposes of registering a single machine in several fleets without any conflicts in the directory that fluent-bit uses to store the configuration locally.
----
**Testing**
---- …
=> custom_calyptia: generate the machine_id in custom_calyptia so machines can register to multiple fleets.

src/flb_utils.c
Suppress a false error log when flb_utils_read_file reads empty files. This affects custom_calyptia when it attempts to read /etc/machine-id inside docker containers when it is present but empty.
----
**Testing**
----
=> utils: suppress errno when file is empty but readable.

plugins/custom_calyptia/calyptia.c
This PR passes the `fleet_id` parameter to the calyptia output plugin when joining a fleet so it can be correctly registered as an agent.
----
**Testing**
----
=> fleet: correctly register fleet agent.

src/flb_input_chunk.c
Fixes only second scenario described in #7846
If a threaded input plugin is paused due to memory buf limits, dont read chunks/records from the ring buffer.
This will prevent this debug message from being logged.
```
[2023/08/21 20:35:35] [ info] [task]   task_id=36 still running on route(s): kafka/kafka.0
[2023/08/21 19:55:57] [debug] [input chunk] tail.0 is paused, cannot append records
[2023/08/21 19:55:57] [debug] [input chunk] tail.0 is paused, cannot append records
[2023/08/21 19:55:57] [debug] [input chunk] tail.0 is paused, cannot append records
[2023/08/21 19:55:57] [debug] [input chunk] tail.0 is paused, cannot append records
[2023/08/21 19:55:57] [debug] [input chunk] tail.0 is paused, cannot append records
[2023/08/21 19:55:57] [debug] [input chunk] tail.0 is paused, cannot …
```
=> input: apply back pressure if input threaded plugin is paused

tests/internal/stream_processor.c
Fix the usage of datafile so it will not overflow when testing from a long repository path. This patch uses snprintf as well as defining the size of the string with PATH_MAX.
----
**Testing**
- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) …
=>  tests: internal: stream_processor: fix when test path is too long.

tests/internal/CMakeLists.txt, tests/internal/log_event_decoder.c
This patch is to add test code for flb_log_event_decoder.
----
**Testing**
```
$ valgrind --leak-check=full bin/flb-it-log_event_decoder 
==50620== …
```
=> tests: internal: log_event_decoder: add test for log_event_decoder

plugins/out_forward/forward.c, plugins/out_forward/forward.h, plugins/out_forward/forward_format.c
Forward protocol supports metadata through the 'options' feature. This information is appended to the whole payload and normally is handled only by the Forward plugin implementation.
This plugin extends Fluent Bit Forward configuration where now is possible to set arbitrary options key/value pairs (strings) for very advanced use cases. Usage:
```
[OUTPUT]
name        forward
match       *
add_option  key1 val1
add_option  key2 val2
```
=> out_forward: add new 'add_option' configuration property

include/fluent-bit/flb_config.h, lib/chunkio/include/chunkio/chunkio.h, lib/chunkio/include/chunkio/cio_file_st.h, lib/chunkio/src/chunkio.c, lib/chunkio/src/cio_file.c, src/flb_config.c, src/flb_input_chunk.c, src/flb_storage.c
This PR adds a new option named `storage.trim_files` which can be used to control the file trimming behavior in chunkio.
This is necessary in order to address an issue where excessive file fragmentation was caused by over zealously trimming chunk files in certain XFS deployments.
The default behavior for `storage.trim_files` is `off` which is a deviation from the previous default behavior which is something we might want to be mindful of.
=> storage: file trimming improvement

include/fluent-bit/flb_kernel.h, src/flb_config.c, src/flb_kernel.c
This patch is to add releasing function for flb_kernel.
----
**Testing**
```
$ valgrind --leak-check=full bin/fluent-bit -i cpu -o stdout
==71676== …
```
=> kernel: add release function

plugins/out_loki/loki.c, plugins/out_loki/loki.h
Add compress option for gzip compression in out_loki
Fixes #7917
----
**Testing**
```
docker run --rm --net=host grafana/loki
```
I'm not sure what I should write here. Any example?
<details>
<summary>with gzip</summary>
```
% valgrind  bin/fluent-bit -i dummy -p rate=60 -o loki -p match='*' -p labels="job=gzip" -p compress=gzip
==61990== Memcheck, a memory error detector
==61990== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==61990== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==61990== Command: …
```
=> out_loki: add compress option for gzip

lib/monkey/CMakeLists.txt, lib/monkey/mk_core/external/winpthreads.c
Monkey v1.7.2 includes a fix to `pthread_setspecific` which fixes a crash in win32 in the co-routines API. This is a blocker for #7929.
----
**Testing**
----
=> lib: monkey: upgrade to v1.7.2

src/flb_processor.c
This patch is to replace tab for readability.
https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#coding-style
```
You have to pay attention to the code indentation, tabs are 4 spaces, spaces on conditionals, etc. If your code submission is not aligned, it will be rejected.
```
----
**Testing** …
=> processor: replace tab with white space

src/flb_uri.c, tests/internal/CMakeLists.txt, tests/internal/uri.c
- Add test code for flb_uri
- Prevent passing negative pos
----
**Testing**
```
d$ valgrind --leak-check=full bin/flb-it-uri 
==28059== …
```
=> tests: internal: uri: add test code

include/fluent-bit/flb_config.h, src/flb_config.c, src/flb_metrics.c, src/flb_reload.c, src/http_server/api/v2/reload.c
For HTTP REST API users, there is lack of capability to confirm that the status of hot-reloading.
It would be nice to have the endpoint which can handle the request for returning the count of the hot-reloading times.
Also, we need to provide the metrics for the status of hot-reloading counts.
In this PR, I added two capabilities.
One is providing an endpoint which can handle GET method to return the count of hot-reloading.
This can be called with:
```console
$ curl -XGET <hostname>:2020/api/v2/reload 
```
The other is provide a v2 metrics which includes the count of hot-reloading.
This can be called by:
```console
$ curl -XGET <hostname>:2020/api/v2/metrics
```
Then, the metrics can be displayed as follows:
```log
<snip>
2023-09-06T07:25:45.332832481Z …
```
=> core: metrics: Provide capabilities for returning the count of hot reloaded in REST API and its metrics

cmake/windows-setup.cmake, plugins/in_calyptia_fleet/in_calyptia_fleet.c, src/fluent-bit.c
This PR implemenets hot reload in windows for the `in_calyptia_fleet` plugin. It includes the necessary changes for the plugin itself as well as rudimentary support for hot-reload under win32.
The calyptia fleet plugin reloads configuration taken from calyptia, which requires hot-reload in windows. This requires two major changes:
- fixing TLS under windows: monkey/monkey#408.
- Simulating the SIGHUP signal.
The first concern was fixed in monkey and is still awaiting merging upstream to fluent-bit.
I used GenerateConsoleCtrlEvent to simulate the behavior of the SIGHUP signal in windows and implemented a simple mechanism to signal the main thread from the GenerateConsoleCtrlEvent handler. This is so the main thread can execute flb_reload.
The implementation I went with uses a simple `int` …
=> in_calyptia_fleet: windows support.

plugins/out_http/http.c
When using body_key and headers_key in output:http, post_all_requests() is called in cb_http_flush(). The exit condition of the while(ret = flb_log_event_decoder_next()) loop is stored in 'ret' and returned as is. This leads to an error being recognized in cb_http_flush(), resulting in a "failed to post requests body" error, and input tasks accumulating in a pending state, causing continuous memory consumption growth. This has been fixed.
----
**Testing**
If this is a change to …
=> out_http: Fix bug where post_all_requests() always returns a value less than 0

src/flb_engine.c
This patch is a workaround to output initialization error logs.
Example:
```
$ bin/fluent-bit -i dummy -p aaa=bbb -o stdout
Fluent Bit v2.1.9
[2023/09/16 09:43:38] [error] [lib] backend failed
[2023/09/16 09:43:38] [ info] [fluent bit] version=2.1.9, commit=3c2c5004b1, pid=24686
$
```
----
**Testing** …
=> engine: add sleep to output logs on init

src/flb_scheduler.c
This is fixing a use-after-free if multiple schedulers are used in a single run.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60089
----
**Testing**
- [N/A] Set …
=> scheduler: use calloc instead of malloc

src/flb_plugin_proxy.c
This is because the recent version of fluent-bit wants to process the ring buffers when nothing ingested but called in the callback. We need to check whether the logs are ingested or not on that line.
The main motivations is:
https://github.com/calyptia/plugin/pull/43#pullrequestreview-1626033613
----
**Testing**
----
=> plugin_proxy: Handle no ingestion case

src/flb_input_chunk.c
This is because log_level for this line should be handled.
----
**Testing**
----
=> input_chunk: Use flb_plg_debug instead of normal printf

include/fluent-bit/flb_lua.h, plugins/filter_lua/lua.c, plugins/filter_lua/lua_config.h, src/flb_lua.c, tests/runtime/filter_lua.c
#7708  https://github.com/fluent/fluent-bit/pull/7799#issuecomment-1702469588
In Lua, nil value is a special value to delete key/value pair from associative array.
https://www.lua.org/pil/2.5.html
```
you can assign nil to a table field to delete it.
```
It means the key/value will be removed from record if its value is null.
e.g. If record is `{"aaa":null, "bbb":"cccc"}` ,`"aaa":null` will be removed in Lua.
This patch is to support `enable_flb_null`.
If set, fluent-bit pass a lightuserdata `flb_null` as a nil value to prevent removing key/value.
Default value is false to keep backward compatibility. 
|Value |Description|Default|
|--|--|--|
|`enable_flb_null`|If enabled, null will be converted to flb_null in Lua. It is useful to prevent removing key/value since nil is a special value to …
=> filter_lua: support enable_flb_null

src/flb_input_chunk.c, src/flb_upstream.c, tests/internal/config_format_fluentbit.c
This patch is to address following warinngs.
tests/internal/config_format_fluentbit.c:
```
[ 95%] Building C object tests/internal/CMakeFiles/flb-it-config_format_fluentbit.dir/config_format_fluentbit.c.o
/home/taka/git/fluent-bit/tests/internal/config_format_fluentbit.c: In function ‘test_nolimit_line’:
/home/taka/git/fluent-bit/tests/internal/config_format_fluentbit.c:265:21: warning: unused variable ‘head’ [-Wunused-variable]
265 |     struct mk_list *head;
|                     ^~~~
```
flb_upstream.c:
```
[ 70%] Building C object src/CMakeFiles/fluent-bit-shared.dir/flb_upstream.c.o
/home/taka/git/fluent-bit/src/flb_upstream.c: In function ‘shutdown_connection’:
/home/taka/git/fluent-bit/src/flb_upstream.c:445:26: warning: variable ‘u’ set but not used [-Wunused-but-set-variable]
445 …
```
=> upstream: Remove unused variables

include/fluent-bit/flb_lua.h, src/flb_lua.c, tests/runtime/filter_lua.c
Fixes #7708 
Fluent-bit converts empty array into empty map.
Lua table represents array and map and we can't determine when a table is empty.
Lua supports metatable and this patch is to append metatable to save data type.
https://www.lua.org/manual/5.1/manual.html#2.8
1. Fluent-bit converts msgpack into Lua data type and appends metatable if the type is array or map.
2. Fluent-bit processes Lua script.
3. Fluent-bit converts Lua data type into msgpack using metatable if it is saved.
Note:
metatable is for Lua table and userdata since other types share a single metatable for the type.
```
Tables and full userdata have individual metatables (although multiple tables and userdata can share their metatables). Values of all other types share one single metatable per type; that is, there is one …
```
=> lua: support metatable to save table type

plugins/filter_log_to_metrics/log_to_metrics.c, plugins/filter_log_to_metrics/log_to_metrics.h, tests/runtime/filter_log_to_metrics.c
Add setting `label` to filter "Log to Metrics". It allows a user to define a custom label name and a key from which the value of the label is read.
Addresses #7737.
----
**Testing**
https://github.com/fluent/fluent-bit-docs/pull/1167
----
Fluent Bit is …
=> filter_log_to_metrics: Add setting "label"

plugins/out_logdna/logdna.c
`len` is assigned but never used. No need for the operations related to this.
----
**Testing** …
=> out_logdna: remove unused store

plugins/out_azure_logs_ingestion/azure_logs_ingestion.c
The code checks if `ctx` is NULL, and if it is' NULL proceeds to dereference `ctx` by way of `ctx->ins`. As such, there will always be a NULL dereference if the condition `if (!ctx)` is true. This fixes it by removing the dereference.
----
**Testing** …
=> out_azure_logs_ingestion: fix NULL dereference

tests/internal/fuzzers/CMakeLists.txt, tests/internal/fuzzers/fstore_fuzzer.c
=> tests: internal: fuzzers: add fstore fuzzer

src/flb_log_event_encoder.c
This patch is to fix typo. 
"Serializatoin" -> "Serialization"
----
**Testing** …
=> log_evnet_encoder: fix typo

plugins/in_systemd/systemd.c
This patch is to fix following warning what I found while investigating #7234 
```
==66582== Thread 2 flb-pipeline:
==66582== Conditional jump or move depends on uninitialised value(s)
==66582==    at 0x22E588: flb_router_match (flb_router.c:111)
==66582==    by 0x2456C0: flb_routes_mask_set_by_tag (flb_routes_mask.c:51)
==66582==    by 0x1CC70E: flb_input_chunk_create (flb_input_chunk.c:1018)
==66582==    by 0x1CD03F: input_chunk_get (flb_input_chunk.c:1268)
==66582==    by 0x1CDB18: input_chunk_append_raw (flb_input_chunk.c:1639)
==66582==    by 0x1CE688: flb_input_chunk_append_raw (flb_input_chunk.c:1989)
==66582==    by 0x2C4B41: input_log_append (flb_input_log.c:65)
==66582==    by 0x2C4BDC: flb_input_log_append (flb_input_log.c:84)
==66582==    by 0x343212: in_systemd_collect …
```
=> in_systemd: init last_tag to fix valgrind warning

include/fluent-bit/flb_config.h, include/fluent-bit/stream_processor/flb_sp.h, src/flb_config.c, src/stream_processor/flb_sp.c, tests/internal/stream_processor.c
This patch is to fix #2498 #5629
TODO: add test code.
This patch is to support following configuration.
|Key|Description|Default|
|--|--|--|
|sp.convert_from_str_to_num|If enabled, Stream processor converts from number string to number type.|true|
----
**Testing**
- [N/A] Backport to latest …
=> sp: prevent converting from string to num if config is set

plugins/out_es/es_conf.c
Some cloud id format is `<deployment_region>$<elasticsearch_hostname>:<port>$<kibana_hostname>`.
e.g. https://github.com/elastic/beats/blob/v8.4.1/libbeat/cloudid/cloudid_test.go#L60
Current out_es fails to parse it.
```
[2022/09/17 09:11:25] [debug] [output:es:es.0] extracted cloud_host: 'ac31ebb90241773157043c34fd26fd46:9243.us-central1.gcp.cloud.es.io'
[2022/09/17 09:11:25] [debug] [output:es:es.0] extracted cloud_port_char: '9243.us-central1.gcp.cloud.es.io'
[2022/09/17 09:11:25] [debug] [output:es:es.0] converted cloud_port_char to port int: '9243'
[2022/09/17 09:11:25] [debug] [output:es:es.0] checked whether extracted port was null and set it to default https port or not. Outcome: '9243' and cloud_host: 'ac31ebb90241773157043c34fd26fd46'.
[2022/09/17 09:11:25] [debug] …
```
=> out_es: check if host contains port number

tests/internal/input_chunk.c
This is because different storage.paths should be used per test. Sometimes this cause failure for retrieving the file contents to prepare the data for test cases:
```log
Test input_chunk_exceed_limit...                [ FAILED ]
input_chunk.c:91: Check getting output file content: ~/GitHub/fluent-bit/tests/internal/data/input_chunk/out/a_thousand_plus_one_bytes.out... failed
[2023/07/28 00:03:09] [error] [~/GitHub/fluent-bit/tests/internal/input_chunk.c:56 errno=0] Success
```
After splitting the storage.path per test case, this error won't happen.
----
**Testing**
If this is a change to packaging of containers or native binaries then please …
=> tests: internal: input_chunk: Use the different storage.path per tests

tests/internal/fuzzers/fstore_fuzzer.c
=> tests: fuzzers: fix fstore div-by-zero

plugins/filter_log_to_metrics/log_to_metrics.c, tests/runtime/filter_log_to_metrics.c
The 'label' property for the `log to metrics` filter was renamed to 'add_label' for consistency with the rest of the plugins. This PR updates the code to use the new property and updates the test to work with the new property name.
----
**Testing**
----
=> filter_log_to_metrics: fix log to metrics label test.

tests/internal/stream_processor.c
This PR addresses the following leak reported by ASAN : 
```
Direct leak of 65536 byte(s) in 8 object(s) allocated from:
#0 0x7fb487452d40 in realloc (/lib/x86_64-linux-gnu/libasan.so.4+0xdfd40)
#1 0x56098a10d88a in msgpack_sbuffer_write /home/runner/work/fluent-bit/fluent-bit/lib/msgpack-c/include/msgpack/sbuffer.h:81
#2 0x56098a10d3ef in msgpack_pack_array /home/runner/work/fluent-bit/fluent-bit/lib/msgpack-c/include/msgpack/pack_template.h:724
#3 0x56098a10fd70 in package_results /home/runner/work/fluent-bit/fluent-bit/src/stream_processor/flb_sp.c:1139
#4 0x56098a101e80 in flb_sp_do_test /home/runner/work/fluent-bit/fluent-bit/tests/internal/stream_processor.c:125
#5 0x56098a1040d4 in test_window /home/runner/work/fluent-bit/fluent-bit/tests/internal/stream_processor.c:506
#6 …
```
=> tests: internal: stream_processor: fixed memory leak

plugins/filter_log_to_metrics/log_to_metrics.c, tests/internal/fuzzers/fstore_fuzzer.c, tests/internal/stream_processor.c, tests/runtime/filter_log_to_metrics.c
This PR adds missing fluent-bit and library initialization calls to test cases that require them.
=> tests: internal: sp: added environment initialization calls

tests/internal/fuzzers/fstore_fuzzer.c
We need to check for NULL here since we can cause mallocs to fail.
----
**Testing** …
=> tests: fuzzers: fix possible NULL deref

include/fluent-bit/flb_log_event_encoder.h, plugins/filter_log_to_metrics/log_to_metrics.c, tests/internal/fuzzers/fstore_fuzzer.c, tests/internal/stream_processor.c, tests/runtime/filter_log_to_metrics.c
This PR addresses an issue with msvc where it incorrectly saves integer data to the stack when passing data sizes to flb_log_event_encoder_append_body_values_unsafe.
=> log_event_encoder: switched data size type to overcome msvc issue

src/fluent-bit.c
After supporting fleet management on Windows,
Ctrl-C events won't be caught up.
This commit re-enables for the behavior.
Windows' ctrl event handlers stolen signals which are overlapped ones. So, we need to handle Ctrl-C events on the newly added event handler for Windows.
In Windows, SIGINT and SIGBREAK are valid ctrl events on their terminal. This is why we only need to handle CTRL_C_EVENT and CTRL_BREAK_EVENT events on console handler.
Closes #7985 
----
**Testing**
```console
PS> bin/fluent-bit -i random -o stdout -v
```
```log
Fluent Bit v2.1.10
* Fluent Bit is a CNCF sub-project under the …
```
=> bin: windows: Restore Ctrl-C behavior on windows

src/fluent-bit.c
this is a backport of https://github.com/fluent/fluent-bit/pull/7986
----
**Testing**
----
=> bin: windows: restore ctrl c behavior on windows [backport 2.1]

plugins/out_syslog/syslog.c
=> out_syslog: when using a message key, avoid prefixing raw messages

src/flb_utils.c
Add support for windows machines to the flb_utils function `flb_utils_get_machine_id` using the MachineGuid registry key in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography`.
This is required for better fleet support since the default behavior in `flb_utils_get_machine_id` is to return a new UUID. This will lead to a new fleet configuration directory being created each time a fleet is invoked on a windows machine.
----
**Testing**
---- …
=> flb_utils: add code to get the machine-id on windows machines.

src/http_server/api/v2/reload.c
Building on top of calyptia-fleet works on Windows, we can also offer for enabling hot-reloading on Windows. :)
However, Windows does not have SIGHUP signal. So, I enabled only for HTTP API for reloading.
Note that  GenerateConsoleCtrlEvent returns nonzero when succeeded.
ref: https://learn.microsoft.com/en-us/windows/console/generateconsolectrlevent
----
**Testing**
```console
PS> bin/fluent-bit -i random -o stdout -H -P 2020 -Y -v
```
```console
PS>  curl -XPOST -d '{}' http://localhost:2020/api/v2/reload
{"reload":"done","status":1}
```
```log
Fluent Bit v2.1.10
* Fluent Bit is a CNCF …
```
=> http_server: v2: reload: windows: Enable hot reloading

tests/internal/CMakeLists.txt, tests/internal/log_event_encoder.c
This patch is to add test code for log_event_encoder after merging https://github.com/fluent/fluent-bit/pull/7971
Note: #7736
----
**Testing**
```
$ …
```
=> tests: internal: log_event_encoder: add test code

plugins/out_loki/loki.c, plugins/out_loki/loki.h
This patch implementes a new configuration property called 'uri' that allows defining a custom HTTP URI.
The default one is always set to '/loki/api/v1/push'; this option allows to override that value.
----
=> out_loki: add new option 'uri' to customize HTTP URI endpoint

include/fluent-bit/flb_version.h.in
This patch is to fix following text :)
```
```
----
**Testing**
- [N/A] Set `ok-package-test` label to test for all …
=> version: happy new year 2023

include/fluent-bit/flb_config.h, include/fluent-bit/flb_output.h, include/fluent-bit/flb_plugin_proxy.h, src/flb_config.c, src/flb_output.c, src/flb_plugin_proxy.c, src/flb_reload.c
To support hot-reloading with Golang plugins which built on top of calyptia/plugin library, we need to expose more callbacks into Golang interface.
* Exposure of pre_run callbacks need to ensure only once execution before running with input callback or flush callback
* Exposure of pre_register callback needs to ensure initialization for waitgroup values before executing register callbacks
* Expose pause/resume callbacks to synchronize the statuses of input plugins against the lifecycle of fluent-bit itself
----
**Testing** …
=> plugin_proxy: core: expose more callbacks for golang plugins

plugins/CMakeLists.txt, plugins/in_node_exporter_metrics/CMakeLists.txt, plugins/in_node_exporter_metrics/ne.c, plugins/in_node_exporter_metrics/ne.h, plugins/in_node_exporter_metrics/ne_cpu.c, plugins/in_node_exporter_metrics/ne_cpu.h, plugins/in_node_exporter_metrics/ne_cpu_darwin.c, plugins/in_node_exporter_metrics/ne_diskstats.c, plugins/in_node_exporter_metrics/ne_diskstats.h, plugins/in_node_exporter_metrics/ne_diskstats_darwin.c, plugins/in_node_exporter_metrics/ne_filefd_linux.h, plugins/in_node_exporter_metrics/ne_filesystem.c, plugins/in_node_exporter_metrics/ne_filesystem.h, plugins/in_node_exporter_metrics/ne_loadavg.c, plugins/in_node_exporter_metrics/ne_loadavg.h, plugins/in_node_exporter_metrics/ne_loadavg_darwin.c, plugins/in_node_exporter_metrics/ne_meminfo.c, plugins/in_node_exporter_metrics/ne_meminfo.h, plugins/in_node_exporter_metrics/ne_meminfo_darwin.c, plugins/in_node_exporter_metrics/ne_netdev.c, plugins/in_node_exporter_metrics/ne_netdev.h, plugins/in_node_exporter_metrics/ne_netdev_darwin.c, plugins/in_node_exporter_metrics/ne_textfile.h, plugins/in_node_exporter_metrics/ne_uname.c, plugins/in_node_exporter_metrics/ne_uname.h, plugins/in_node_exporter_metrics/ne_uname_darwin.c
At the initial support for macOS, I implemented cpu,loadavg,meminfo,diskstats,uname, and netdev metrics.
Note that diskstats metrics depend on IOKit and Foundation frameworks which could introduces binary incompatibilities for macOS 12.0 (Monterey) or older.
In macOS, meminfo and vmstat metrics should be overlapped their information. So, I decided to provide meminfo metrics and not to provide vmstat metrics.
No referred issues for this PR. This is started for a researching task to support macOS metrics.
----
**Testing**
```console
$ bin/fluent-bit -i node_exporter_metrics -o stdout
```
```
$ bin/fluent-bit -i node_exporter_metrics -o stdout -v …
```
=> in_node_exporter_metrics: Initial support for macOS metrics

plugins/in_node_exporter_metrics/CMakeLists.txt, plugins/in_node_exporter_metrics/ne.c, plugins/in_node_exporter_metrics/ne.h, plugins/in_node_exporter_metrics/ne_processes.c, plugins/in_node_exporter_metrics/ne_processes.h, plugins/in_node_exporter_metrics/ne_processes_linux.c
To monitor for statuses of processes and threads, we need to implement processes metrics on in_node_exporter_metrics plugin.
Fixes https://github.com/fluent/fluent-bit/issues/7866
----
**Testing**
```console
$ bin/fluent-bit -i node_exporter_metrics -p metrics=processes -o stdout
```
```log
Fluent Bit v2.1.9
[2023/08/31 11:02:00] [ info] Configuration:
[2023/08/31 11:02:00] [ info]  flush time     | 1.000000 seconds
[2023/08/31 11:02:00] [ info]  grace          | 5 seconds
[2023/08/31 11:02:00] [ info] …
```
=> in_node_exporter_metrics: implement processes metrics

plugins/in_node_exporter_metrics/ne_processes.h
To build on macOS, we have to provide skeleton functions which are not targeted OSes.
Follows up https://github.com/fluent/fluent-bit/pull/7880. This should be affected by merging https://github.com/fluent/fluent-bit/pull/7947.
----
**Testing**
----
=> node_exporter_metrics: Fix macOS build

plugins/out_chronicle/chronicle.c
* Remove redundant initializations in
https://github.com/fluent/fluent-bit/blob/92e0435f4ab45ee2ecd19732935f9ff02b808979/plugins/out_chronicle/chronicle.c#L553-L555
The variables are already initialized with these values, and there's no code that could change them until this point.
* Remove unnecessary if
https://github.com/fluent/fluent-bit/blob/92e0435f4ab45ee2ecd19732935f9ff02b808979/plugins/out_chronicle/chronicle.c#L610-L612
At this point, `found` will always be `FLB_FALSE` (hence, the expression will always be true).
It's only changed in one line, and that block ends with a break https://github.com/fluent/fluent-bit/blob/92e0435f4ab45ee2ecd19732935f9ff02b808979/plugins/out_chronicle/chronicle.c#L605 hence never reaching the removed if statement
* Following the reasoning above, the …
=> out_chronicle: remove redundant code

plugins/in_node_exporter_metrics/ne.c
This patch is to fix referencing wrong intervals.
Following configuration doesn't output metrics.
We expect that fluent-bit output cpu metrics.
```
[INPUT]
Name node_exporter_metrics
Metrics cpu
collector.cpufreq.scrape_interval 1
[OUTPUT]
Name stdout
Match *
```
----
**Testing**
```
[INPUT] …
```
=> in_node_exporter_metrics: fix referencing wrong interval between cpu and cpufreq

src/stream_processor/flb_sp.c, src/stream_processor/parser/flb_sp_parser.c, tests/internal/include/sp_cb_functions.h
Key names are missing from the output record for the keys inside GROUP BY statement.
Fixes #7459 
----
**Testing**
- [] Debug log output from testing the change
```
==98401== Memcheck, a memory error detector
==98401== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==98401== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==98401== Command: ./bin/fluent-bit -c ../conf/bug
==98401== 
[2023/10/12 03:39:28] [ …
```
=> sp: fix missing key names when query contains GROUP BY

plugins/in_forward/fw_prot.c
`cmt_encode_msgpack_create` can return positive error code like `CMT_DECODE_MSGPACK_INVALID_ARGUMENT_ERROR`.
We should check if the return value is `CMT_DECODE_MSGPACK_SUCCESS` or not.
#8000 can be caused if the API returns positive error and cmt is invalid pointer.
----
**Testing**
- [N/A] Run [local …
=> in_forward: fix checking return value of cmt_decode_msgpack_create(#8000)

src/config_format/flb_cf_yaml.c, tests/internal/config_format_yaml.c, tests/internal/data/config_format/yaml/processors.yaml
Fix the logic behind handling errors when allocating a cfl_array in the yaml parser for input processors.
----
**Testing**
----
=> config_format: yaml: fix error logic for input processors and cfl_array.

plugins/out_cloudwatch_logs/cloudwatch_api.c, plugins/out_cloudwatch_logs/cloudwatch_logs.c, plugins/out_cloudwatch_logs/cloudwatch_logs.h, src/aws/flb_aws_util.c
Allow multiple workers on `cloudwatch_logs` by removing sequence tokens :tada::tada::tada:
This PR removes the sequence tokens from CloudWatch Log API requests entirely (as per the recent CWL API update).
Also removes error handling for `InvalidSequence` and `DataAlreadyAccepted` exceptions which no longer occur.
CWL API Docs:
> The sequence token is now ignored in PutLogEvents actions. PutLogEvents actions are always accepted and never return InvalidSequenceTokenException or DataAlreadyAcceptedException even if the sequence token is not valid. You can use parallel PutLogEvents actions on the same log stream. 
https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html
> Reopened from: https://github.com/fluent/fluent-bit/pull/6741
Note: This is a cleaned up …
=> cloudwatch_logs: remove sequence tokens from API calls

include/fluent-bit/flb_input.h, src/flb_input.c
To observe whether input plugins are paused or not, we should provide ~~any_overlimit~~ingestion_paused metrics which represents the input is paused or not.
----
**Testing**
```console
$ bin/fluent-bit -i dummy -o stdout -Y -H -P 2021
```
```
[2023/10/16 15:18:06] [ info] Configuration:
[2023/10/16 15:18:06] [ info]  flush time     | 1.000000 seconds
[2023/10/16 15:18:06] [ info]  grace          | 5 seconds
[2023/10/16 15:18:06] [ info]  daemon         | 0
[2023/10/16 15:18:06] [ info] …
```
=> input: Add ingestion_paused metrics to confirm whether an input plugin is paused or not

src/fluent-bit.c
This patch is to modify signal handler for hot reloading.
Multiple SIGHUP can cause SIGSEGV like following log.
This patch is to prevent it. 
```
[2023/10/14 10:26:43] [ info] [fluent bit] version=2.2.0, commit=8401076f11, pid=33322
[2023/10/14 10:26:43] [ info] [storage] ver=1.2.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/10/14 10:26:43] [ info] [cmetrics] version=0.6.3
[2023/10/14 10:26:43] [ info] [ctraces ] version=0.3.1
[2023/10/14 10:26:43] [ info] [input:cpu:cpu.0] initializing
[2023/10/14 10:26:43] [ info] [input:cpu:cpu.0] storage_strategy='memory' (memory only)
[2023/10/14 …
```
=> fluent-bit: modify hot reload handler

plugins/in_forward/fw_prot.c, src/stream_processor/flb_sp.c, src/stream_processor/parser/flb_sp_parser.c, tests/internal/include/sp_cb_functions.h
- in_forward: fix checking return value of cmt_decode_msgpack_create(#8000) (#8015)
- sp: fix missing key names when query contains GROUP BY (#8028)
=> backport: fixes from git master to v2.1

.github/actionlint.yml, .github/workflows/call-build-linux-packages.yaml
Backport of #8069 for 2.1 branch.
----
**Testing**
----
=> workflows: update Actuated sizes [backport to 2.1]

.github/actionlint.yml, .github/workflows/call-build-linux-packages.yaml
CNCF is sponsoring Actuated runners now so moving to using those instead of the Calyptia-provided ones. Requires tweaking the size of the VMs slightly.
----
**Testing**
----
=> workflows: update Actuated sizes and use CNCF runners

plugins/custom_calyptia/calyptia.c
The `machine_id` is configured and extracted automatically using the `flb_utils_get_machine_id` function when it is not set explicitly via `config_map`. When this occurs the value is not freed. This PR fixes that.
----
**Testing**
----
=> custom_calyptia: free machine_id when it is automatically set.

plugins/in_docker/CMakeLists.txt, plugins/in_docker/cgroup_v2.c, plugins/in_docker/docker.c, plugins/in_docker/docker.h
Currently, in_docker does not provide cgroups v2.
In this PR, I added a capability to handle cgroups v2 metrics for Docker.
This is related for https://github.com/fluent/fluent-bit/issues/5949.
----
**Testing**
```console
$  sudo bin/fluent-bit -i docker -o stdout 
```
In other terminals:
```console
$ docker run -it --rm ubuntu:jammy bash
```
```console
$ docker run -it --memory 300MB --rm debian:bullseye bash
```
fluent-bit log:
```log
[2023/10/26 15:18:53] [ info] Configuration: …
```
=> in_docker: Implement a capability for cgroups V2

plugins/out_stackdriver/stackdriver_conf.c
This fixes the use case of specifying the `service_account_email` and `service_account_secret` options explicitly.
Fixes #6969 
----
**Testing**
```
[OUTPUT]
Name        stackdriver
Match       …
service_account_email …
service_account_secret …
```
#8094 
----
=> out_stackdriver: Don't overwrite ctx->client_email and ctx->private_key.

include/fluent-bit/flb_chunk_trace.h, include/fluent-bit/flb_event.h, include/fluent-bit/flb_output.h, src/flb_chunk_trace.c, src/flb_event.c, src/flb_task.c
Create a separate thread to run the pipeline for chunk traces.
With this pull request traces now use a threaded input so traces can be logged using a ring buffer. This bypasses the need to call in_emitter_add_record from the in_emitter plugin as well.
This should fix the occasional crash ocurring during the flb-rt-core_chunk_trace test as well as making traces more stable.
As an extra bonus, the use of a threaded input with ring buffers now allows for logging the output return value from outputs.
----
**Testing** …
=> chunk_trace: use a threaded pipeline.

plugins/custom_calyptia/calyptia.c
Setting the `fleet_id` for the output plugin was done in two places as well as hidden behind an else condition that would never execute. This change should more reliably set `fleet_id` for the calyptia output plugin.
----
**Testing**
----
=> custom_calyptia: correctly set fleet_id for out_calyptia when fleet_name is set.

plugins/in_calyptia_fleet/in_calyptia_fleet.c
The  `in_calyptia_fleet` plugin has a configuration property `event_fd` which it makes no use of. This code drops it.
----
**Testing**
----
=> in_calyptia_fleet: remove unused event_fd configuration property.

plugins/in_calyptia_fleet/in_calyptia_fleet.c
Check if we are using the old configuration when checking the currently used configuration file.
----
**Testing**
----
=> in_calyptia_fleet: add old configuration file to checks.

src/flb_reload.c
This patch is to port #8042 
----
**Testing**
- [N/A] Documentation required …
=> reload: add missing flb_cf_destroy [backport 2.1]

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/README.md, .github/workflows/cron-unstable-build.yaml, .github/workflows/staging-release.yaml, .github/workflows/unit-tests.yaml
Preparation for 2.2 releases by updating the various workflows required.
Also resolves issue with unit tests not running on 2.1 PRs.
----
**Testing**
----
---
- https://app.asana.com/0/0/1205727736664990
=> workflows: update to handle 2.2 releases

plugins/in_calyptia_fleet/in_calyptia_fleet.c
This patch is to release resources on collect callback.
`data` and/or `header` can not be released on error case.
----
**Testing**
- [N/A] Set `ok-package-test` label to test for all …
=> in_calyptia_fleet: add missing release function on collect

plugins/in_calyptia_fleet/in_calyptia_fleet.c
This patch is to add releasing function on init.
----
**Testing**
----
=> in_calyptia_fleet: add missing release function

plugins/in_calyptia_fleet/in_calyptia_fleet.c
I have identified and fixed several memory leaks in fleet that happen during the reloading of the current configuration (when it exists from a previous run) or any new configurations loaded from the calyptia API.
- Initialization of plugin instances when testing the new configuration in `test_config_is_valid`.
- Memory leaked due to premature return (FLB_OUTPUT_RETURN) in the collect callback.
- File paths (flb_sds_t) leaked during error handling.
The function `test_config_is_valid` was attempting to be far too intelligent by instantiating the configured plugins. Attempting to free the memory instantiated by the initialization is problematic since `flb_output_exit` also frees the TLS variables it uses to store co-routine parameters, making it not thread-safe.
---- …
=> in_calyptia_fleet: fix memory leaks during hot-reload of current and new configurations.

include/fluent-bit/flb_filter.h, src/flb_filter.c, src/flb_input_chunk.c
This PR replaces the order of the filtering and writing operations in order to perform any filtering necessary in memory which in turn allows fluent-bit to minimize the overhead that comes with overwriting chunk sections (ie. IO and having to recalculate the file checksum each time).
---
- https://app.asana.com/0/0/1205838432919112
=> core: in memory filtering implementation

plugins/in_splunk/splunk_prot.c
`tag_from_record` is allocated at `tag_key`.
https://github.com/fluent/fluent-bit/blob/v2.1.10/plugins/in_splunk/splunk_prot.c#L202
It will be only released upon success at `process_flb_log_append`
https://github.com/fluent/fluent-bit/blob/v2.1.10/plugins/in_splunk/splunk_prot.c#L296
This patch is to ensure releasing `tag_from_record`.
----
**Testing** …
=> in_splunk: ensure releasing tag_from_record

include/fluent-bit/flb_filter.h, include/fluent-bit/flb_reload.h, plugins/filter_lua/lua.c, plugins/filter_wasm/filter_wasm.c, src/flb_filter.c, src/flb_reload.c, src/fluent-bit.c
On hot-reloading, we intended to keep fluent-bit process as much as possible when an error is included in the loaded configuration file. 
However, the current behavior is not ideal for containing invalid values for provided valid parameters in the configuration file during hot-reloading. This PR is mainly for filter_lua case which is loaded invalid lua script as described in #8067.
In this situation, we should validate malformed values especially for Lua script.
In filter_lua, fluent-bit isn't able to process events when loading an invalid Lua script. This should be halted for hot-reloading process.
Related to #8067 
----
**Testing**
If this …
=> reload: bin: filter: handle invalid values of configuration correctly on hot reloading

src/config_format/flb_cf_yaml.c
Fixes #8130
The log level here should be debug instead of error.
----
=> config_format: flb_cf_yaml: change log level in processing.

src/aws/flb_aws_util.c
Tested by adding a fake error:
```
[2023/11/02 20:43:59] [ warn] [output:cloudwatch_logs:cloudwatch_logs.1] PutLogEvents: Raw response: {"nextSequenceToken":"49645959017322090641208425572396895883538558252795036370"}
```
It works.
----
**Testing**
----
=> out_cloudwatch_logs: enhance api error response readability

plugins/filter_lua/lua.c
When building with `FLB_FILTER_LUA_USE_MPACK`, compilation fails because this `flb_lua_arraylength` call didn't have an index argument. This PR passes the index argument to the function that I believe to be correct, which is `-1` (assuming based on its usage in the following loop to get individual elements).
Didn't make an issue but I can if necessary
----
**Testing** …
=> filter_lua: add index to arraylength call

plugins/in_fluentbit_metrics/metrics.c
This patch is to add releasing function on initialization error.
----
**Testing** …
=> in_fluentbit_metrics: add missing release function on init

plugins/in_dummy/in_dummy.c, plugins/in_dummy/in_dummy.h, tests/runtime/in_simple_systems.c
This PR adds new `interval_sec` and `interval_nsec` settings to the `in_dummy` input plugin. This settings enable to set an arbitrary time interval in which to generate dummy logs. When `interval_sec/nsec` is set correctly, the `rate` configuration is ignored.
Documentation update in https://github.com/fluent/fluent-bit-docs/pull/1239.
```
[INPUT]
Name          dummy
Dummy         {"message": "custom dummy"}
Interval_sec  1
Interval_nsec 500000000
Rate          0
[OUTPUT]
Name   stdout
Match  *
```
With this config a log message is generated every 1.5 seconds).
```
./fluent-bit -c fluent-bit.conf
[2023/10/27 18:06:56] [ info] [fluent …
```
=> in_dummy: Add interval settings.

src/flb_input_chunk.c
This PR fixes a bug in the conditional meant to ignore dropped records  where it would previously append the records anyway.
=> input_chunk: fixed a corner case when records are dropped

plugins/in_forward/fw_prot.c, plugins/out_forward/forward_format.c
In the current forward plugins' implementations, they don't handle to forward gzip compressed chunks.
To achieve this, we have to handle this issue as follows:
* Add compress=gzip option for non logs type of chunks in out_forward
* Handle event_type correctly on gzip compressed case in in_forward 
Closes #8000 
----
**Testing**
For scraping metrics:
```ini
[SERVICE]
flush        1
log_level    debug
parsers_file /path/to/parsers.conf
http_server  Off
[INPUT]
name prometheus_scrape
tag metrics.foobar
host 0.0.0.0
port 9090
scrape_interval 15s
[OUTPUT]
Name forward
Match metrics.*
Host 127.0.0.1
Port 24225
Compress gzip
```
For …
=> forward: Handle to forward for compressed non log types of chunks

src/flb_http_client.c, src/flb_output.c, tests/internal/http_client.c
Fixes #6783 
----
**Testing**
----
=> out_http: Fix keepalive

src/flb_utils.c
Add code to get the machineID (serial number) on macOS machines.
This value is used after hashing it to identify agents in a fleet that does not have a machineID already assigned manually with the `MachineID` configuration property.
----
**Testing**
----
=> flb_utils: add code for getting the machineID on macOS.

.github/workflows/call-build-images.yaml, .github/workflows/call-test-images.yaml, CMakeLists.txt, README.md, cmake/s390x.cmake, dockerfiles/Dockerfile, dockerfiles/README.md
- Adding support for linux-s390x in CI
- Added s390x specific cmake target to disable WASM and LuaJIT
----
**Testing**
- [N/A] Backport to latest stable …
=> dockerfiles: Add support for s390x

plugins/in_node_exporter_metrics/CMakeLists.txt, plugins/in_node_exporter_metrics/ne.c, plugins/in_node_exporter_metrics/ne.h, plugins/in_node_exporter_metrics/ne_nvme.c, plugins/in_node_exporter_metrics/ne_nvme.h, plugins/in_node_exporter_metrics/ne_nvme_linux.c
In the official Prometheus exporter, NVMe metrics is provided as a default collecting collector.
Then, we should provide it in fluent-bit. This is because non numerical metrics of NVMe is not collected other types of metrics on node_exporter_metrics.
Closes #7888 
----
**Testing**
```console
$ bin/fluent-bit -i node_exporter_metrics -p metrics=nvme -o stdout -v
```
```log
[2023/10/17 11:15:47] [ info] Configuration:
[2023/10/17 11:15:47] [ info]  flush time     | 1.000000 seconds
[2023/10/17 …
```
=> in_node_exporter_metrics: Implement NVMe metrics

tests/runtime/core_chunk_trace.c
This one liner should fix the sporadic CI failures in the `flb-rt-core_chunk_trace' test. The crash occurs when the flb_lib based input uses the records structure after the test has exited and freed them. I added a sleep to avoid this scenario.
At the very least it ran around 725 times in succession without any further errors:
```
while ./bin/flb-rt-core_chunk_trace > error.log 2>&1 ; do echo -n "." ; done
.....................................................................................
.....................................................................................
.....................................................................................
..................................................................................... …
```
=> chunk_trace: add wait in test to avoid use after free in lib callback.

plugins/in_calyptia_fleet/in_calyptia_fleet.c
I refactored the `__mkdir` helper function to use PATH_SEPARATOR instead of the hardcoded '/' (Unix slash). This will allow it to work on win32.
This function is used to create the directory and sub directories where fleet configuration files are stored and then loaded.
----
**Testing**
----
---
- To see the specific tasks where the Asana app for …
=> in_calyptia_fleet: get __mkdir to work on non-Unix operating systems.

plugins/in_thermal/in_thermal.c
This patch is to support to read a temperature from hwmon subsystem. See also https://github.com/fluent/fluent-bit/issues/7955
https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface
in_thermal tries to read a temperature from `/sys/class/thermal` first.
If in_thermal can't read it, in_thermal tries to read `/sys/class/hwmon`.
----
**Testing**
- [N/A] Set …
=> in_thermal: support hwmon

CMakeLists.txt, plugins/CMakeLists.txt, plugins/in_process_exporter_metrics/CMakeLists.txt, plugins/in_process_exporter_metrics/pe.c, plugins/in_process_exporter_metrics/pe.h, plugins/in_process_exporter_metrics/pe_config.c, plugins/in_process_exporter_metrics/pe_config.h, plugins/in_process_exporter_metrics/pe_process.c, plugins/in_process_exporter_metrics/pe_process.h, plugins/in_process_exporter_metrics/pe_utils.c, plugins/in_process_exporter_metrics/pe_utils.h
In the official node_exporter, process level of metrics exporter is not provided. the 3rd party exporter is provided. However, the 3rd party exporter is still not process level but for process group level of exporter.
We try to provide genuine process level of exporter in Linux.
Closes  https://github.com/fluent/fluent-bit/issues/7870
----
**Testing**
```console
$ bin/fluent-bit -i process_exporter_metrics -o stdout
$ bin/fluent-bit -i process_exporter_metrics -p 'process_exclude_pattern=/chrome|kworker|firefox|gsd|Co/' -o stdout
$ bin/fluent-bit -i process_exporter_metrics -p 'process_include_pattern=/fluent-bit/' -o stdout
```
e.g.)
```
$ …
```
=> in_process_exporter_metrics: implement process exporter metrics

plugins/out_loki/loki.c, plugins/out_loki/loki.h
Following pattern from prometheus_remote_write, this adds the option to add arbitrary http headers.
Tested against a Loki endpoint and logging reverse proxy.
**Testing**
https://github.com/fluent/fluent-bit-docs/pull/1207
---- …
=> out_loki: add ability to add arbitrary http headers and adjust the URI path

.github/workflows/call-test-images.yaml
With s390x LUA plugin is disabled but smoke tests contain LUA filter so it leads to failure. PR removes the s390x from smoke tests matrix
----
**Testing**
----
=> fix: remove linux/s390x smoke tests

.github/workflows/call-build-images.yaml, .github/workflows/call-test-images.yaml, CMakeLists.txt, README.md, cmake/s390x.cmake, dockerfiles/Dockerfile, dockerfiles/README.md
- Adding support for linux-s390x in CI
- Added s390x specific cmake target to disable WASM and LuaJIT
Backporting s390x enablement via https://github.com/fluent/fluent-bit/pull/8095
----
**Testing**
- [N/A] Set `ok-package-test` label to test for all targets (requires maintainer to …
=> dockerfiles: Add support for s390x to 2.1

plugins/in_winevtlog/pack.c
This function needs the `winevtlog_config*` not the log encoder. This was causing a crash on any event log with `<Binary \>` in it.
#7832
=> in_winevtlog: pass correct value

plugins/out_stackdriver/stackdriver.c, plugins/out_stackdriver/stackdriver.h, plugins/out_stackdriver/stackdriver_conf.c
Adding `partialSuccess: true` as part of the request to Google Cloud Logging API.
----
**Testing**
```
[INPUT]
Name                          tail
Path                          <path-to-log-file>
Tag                           foo
Read_from_head                true
Buffer_Max_Size               100MB
Buffer_Chunk_Size             512k
[OUTPUT]
Match                         *
Name                          stackdriver
Retry_Limit                   3
http_request_key              logging.googleapis.com/httpRequest
net.connect_timeout_log_error False
resource                      gce_instance
stackdriver_agent …
```
=> out_stackdriver: Add partialSuccess: true to all logs sent to Google Cloud Logging API

src/flb_filter.c, src/flb_input_chunk.c, src/flb_task.c, tests/internal/input_chunk.c
In commit ac4ec1f, the input chunk writing was moved down from the previous spot to be below where input metrics are updated. This PR moves the metric update below the input chunk write so that the `ret == CIO_OK` check is actually right, and so that the metrics are only updated after the write has occurred.
I also moved adding to `total_records` outside of the metric ifdef. This appears to have been here for some time, but there are numerous output plugins that rely on `event_chunk->total_events`, which is set from this total_records value. This will mean it always gets updated, even if metrics are disabled.
----
**Testing**
If this is a …
=> input_chunk: update records in the right place

plugins/in_calyptia_fleet/in_calyptia_fleet.c
Add support for extra fleet files. These go along with the main configuration and can be referred to using relative paths. The intention is to use them for:
- Parsers
- Includes
- Lua Scripts
But they are not restricted to just those uses. They can also be used as general files for plugins.
----
**Testing**
----
=> in_calyptia_fleet: support multiple files for configurations.

tests/internal/log.c
Use an actual clock that gets reset instead of an interval to avoid timing problems where sleep might not be exact due to scheduling or possibly noisy neighbours.
This should cut down on the many false negatives we have had during continuous integration with the flb-it-log test, especially on macos machines.
----
**Testing**
----
=> test: fix internal log test to use a clock instead of an interval.

.github/workflows/staging-release.yaml
Resolves #6937 doc generation, requires https://github.com/fluent/fluent-bit-docs/pull/1270
----
**Testing**
----
=> workflows: update docs generation process for releases

tests/runtime/in_simple_systems.c
Add a busy wait loop for in_dummy checks that wait around 5 seconds or for the first record before tests check record count. This should make tests less flaky when running on hosted multi-tenant environments.
I ran the test several times while running sysbench, similar to my previous log test fix.
----
**Testing**
----
=> tests: in_dummy: try and wait for the first record before doing checks.

plugins/in_node_exporter_metrics/ne_nvme_linux.c
In NVMe not mounted node, the not found error is generated by ne_utils_path_scan.
However, not every node and Linux boxes have NVMe as their storage.
So, we have to suppress the error message and suppress logs for it.
Specifically, it will occurred on the visualized/containerized environments such as EC2 instances or ChromeOS's Linux containers.
----
**Testing**
```log
$ LANG=C ls /sys/class/nvme
ls: cannot access '/sys/class/nvme': No such file or directory
$ bin/fluent-bit -i node_exporter_metrics -p metrics=nvme -o stdout -v
Fluent Bit v2.2.1
* Fluent Bit is a CNCF sub-project under the …
```
=> in_node_exporter_metrics: Suppress error log when NVMe is not mounted

CODEOWNERS
This PR adds the Google codeowners to the test data files used by the test file we already own.
=> CODEOWNERS: add google codeowners to test data

README.md
As discussed with Patrick via slack - add a note/link-back to actuated which is used for Arm-based CI and releases -  https://docs.actuated.dev/faq/#is-there-a-sponsored-subscription-for-open-source-projects
----
**Testing**
----
=> Update README.md with actuated reference

src/flb_input_chunk.c
`flb_filter_do` may modify the input chunk's total records, meaning that if there is a filter in the pipeline the total records could be double-counted which breaks anything that relies on an event chunk's `total_records`.
----
**Testing**
----
=> input_chunk: handle filter_do edge case

plugins/in_opentelemetry/opentelemetry_prot.c
This patch is to fix following valgrind error.
The resource should be freed by `opentelemetry__proto__collector__logs__v1__export_logs_service_request__free_unpacked`.
```
==149281== 
==149281== HEAP SUMMARY:
==149281==     in use at exit: 688 bytes in 21 blocks
==149281==   total heap usage: 1,611 allocs, 1,590 frees, 1,258,568 bytes allocated
==149281== 
==149281== 688 (40 direct, 648 indirect) bytes in 1 blocks are definitely lost in loss record 9 of 9
==149281==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==149281==    by 0x9893BC: system_alloc (protobuf-c.c:154)
==149281==    by 0x98940C: do_alloc (protobuf-c.c:167)
==149281==    by 0x98E30C: protobuf_c_message_unpack (protobuf-c.c:3063)
==149281==    by 0x9926B3: …
```
=> in_opentelemetry: fix memory leak

plugins/in_calyptia_fleet/in_calyptia_fleet.c
The following warning appears when using clang 15.0.0:
```bash
/Users/pwhelan/Code/fluent-bit/plugins/in_calyptia_fleet/in_calyptia_fleet.c:1002:9: warning: variable 'fname' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
if (ret < 0) {
^~~~~~~
/Users/pwhelan/Code/fluent-bit/plugins/in_calyptia_fleet/in_calyptia_fleet.c:1053:21: note: uninitialized use occurs here
flb_sds_destroy(fname);
^~~~~
/Users/pwhelan/Code/fluent-bit/plugins/in_calyptia_fleet/in_calyptia_fleet.c:1002:5: note: remove the 'if' if its condition is always false
if (ret < 0) {
^~~~~~~~~~~~~~
/Users/pwhelan/Code/fluent-bit/plugins/in_calyptia_fleet/in_calyptia_fleet.c:987:20: note: initialize the variable 'fname' to silence this warning
flb_sds_t fname;
```
This PR fixes the code to both …
=> in_calyptia_fleet: rewrite error handling code for get_calyptia_file to fix warnings.

plugins/in_calyptia_fleet/in_calyptia_fleet.c
Fix the majority of the memory leaks in the calyptia fleet code. 
Here is a run of fluent-bit with the patch under valgrind:
```bash
valgrind --leak-check=full ./bin/fluent-bit -c fleet.conf
==85735== Memcheck, a memory error detector
==85735== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==85735== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==85735== Command: ./bin/fluent-bit -c fleet.conf
==85735==
Fluent Bit v2.2.1
[2023/12/11 21:33:06] [ info] [fluent bit] version=2.2.1, commit=469652f625, pid=85735
[2023/12/11 21:33:06] [ info] [custom:calyptia:calyptia.0] custom initialized!
[2023/12/11 21:33:06] [ info] …
```
=> in_calyptia_fleet: fix memory leaks.

src/flb_input_chunk.c
When an output plugin is configured to use `storage.total_limit_size` while the input plugin uses memory storage mode, it would previously
continue calculating and eventually pass an empty pointer to the
storage context in the function that releases space. This PR adds a
validationg in the overlimit route check that will cause the check to
be skipped, ensuring that the rest of the space freeing routines are
never executed.
----
**Testing**
Any input plugin with memory storage type, any output plugin with `storage.total_limit_size` set. I tested it with this:
```
[SERVICE]
Flush            10
Daemon           off
Log_Level        debug …
```
=> flb_input_chunk: skip overlimit check in mem mode

.github/workflows/call-build-images.yaml, .github/workflows/call-build-linux-packages.yaml, .github/workflows/call-build-macos.yaml, .github/workflows/call-build-windows.yaml, .github/workflows/call-integration-image-build.yaml, .github/workflows/cron-scorecards-analysis.yaml, .github/workflows/cron-trivy.yaml, .github/workflows/pr-fuzz.yaml
Resolves #8298 by ensuring we use uploads immutably.
Note v4 is a matching upgrade for upload and download artifact.
----
**Testing**
----
=> workflows: handle v4 upload-artifact usage

.github/workflows/call-build-windows.yaml
Resolves failure in CI: https://github.com/fluent/fluent-bit/actions/runs/7260326110/job/19779963759
Previous to PR #8304 we were using v3 version of the action which allowed us to add all Windows binaries into the same package. Now we have separate packages so have to merge them together to properly sync to S3.
Taken from <https://github.com/actions/download-artifact/tree/v4/?tab=readme-ov-file#download-multiple-filtered-artifacts-to-the-same-directory>.
----
**Testing**
----
Fluent Bit is licensed …
=> workflows: merge multiple Windows uploads together

plugins/in_kafka/in_kafka.c, plugins/in_kafka/in_kafka.h
We need to register pause/resume callback for correct handling of back pressure in in_kafka.
Back pressure implementation of Fluent Bit is relying on pause/resume callback which is registered in the each of plugins.
~~Also, the current implementation of in_kafka does not consider the threshold to halt polling after reaching the limit of chunks.~~
~~It causes always over limit status of chunks. This shouldn't happen if the parameters are correctly set up.~~
I implemented restrictive polling in in_kafka. This shouldn't cause spikes of memory consumption.
----
**Testing**
```ini
[INPUT]
Name        kafka
Brokers     127.0.0.1:9092
Topics …
```
=> in_kafka: Make back pressure workable and add a mechanism of polling threshold

src/flb_plugin_proxy.c, src/proxy/go/go.c
As described in #8253, we should handle an error on initialization from Golang output plugin.
Currently, this should be discarded and not handled correctly. We should handle it properly.
----
**Testing**
```ini
[SERVICE]
Flush        5
Plugins_File plugins.conf
storage.metrics On
[INPUT]
Name gdummy
Tag  dummy.local.ins1
Dummy {"compact": true, "schema": 1, "message": "ok"}
[OUTPUT]
Name  gstdout
Match *
```
```ini
[PLUGINS]
Path /path/to/fluent-bit/build/in_gdummy.so
Path /path/to/fluent-bit/build/out_gstdout.so
```
If an error occurred on Golang plugin …
=> go: plugin_proxy: Handle FLBPluginInit(cb_init) error correctly and plug a SEGV case

.github/workflows/call-build-windows.yaml, .github/workflows/pr-windows-build.yaml, CMakeLists.txt, DEVELOPER_GUIDE.md, appveyor.yml, cmake/windows-setup.cmake, dockerfiles/Dockerfile.windows
Docs and minor CMake build tweaks for Windows builds
* Abort cmake early if flex, bison or openssl missing on windows builds, since the build is not tested without them and is currently known to fail if they are missing. See https://github.com/fluent/fluent-bit/pull/7207 for context.
* Enable `workflow_dispatch` for `.github/workflows/pr-windows-build.yaml` so users of forked repos can run it manually on their branches via their github repo Actions tab. The workflow must have `workflow_dispatch` in the default (master) branch for this to work, so it's sensible to have this pre-defined.
* add Windows build section in DEVELOPER_GUIDE.md
* x-ref comments in the various windows CI files to point to each other and the docs
----
Enter `[N/A]` in the box, if an item is not applicable to your …
=> windows: build docs and tweaks

cmake/windows-setup.cmake
Work done as part of #7207 made the in_exec plugin build-able on Windows, but did not enable it as part of the build.
Enable its compliation on Windows per request of @patrick-stephens .
Please also merge related Windows PR https://github.com/fluent/fluent-bit/pull/7463
----
**Testing**
**`master` is totally valgrind-unclean so please remove this from the PR template^^** …
=> plugins: in_exec: enable on win32

plugins/in_process_exporter_metrics/pe_process.c
This function is to release string in error cases.
----
**Testing**
- [N/A] …
=> in_process_exporter_metrics: release str in error cases

tests/internal/flb_event_loop.c
The event loop has multiple time epsilons defined, one for each operating system, which defines the longest time delta that is acceptable for a wait or timeout when running timers in the event loop. This delta can easily be exceeded when either running on over-provisioned machines, running other tasks on the same hardware, etc...
This pull request increases this epsilon from 20ms to 50ms for linux. I arrived at this number by running the tests in 1024 parallel instances using GNU parallel while running sysbench on the same AMD Ryzen 9 5900X 12-Core Processor.
The script I used to run the parallel instances of the test:
```bash
#!/bin/bash
NUM=1024
parallel --joblog job.log -j 1024 ./test.sh {1} ::: {1..1024}
if cat job.log | awk -F ' ' '{print $7}' | grep -v "0\|Exitval"; then
exit 1
fi …
```
=> tests: event_loop: increase eplison on linux.

include/fluent-bit/flb_output.h, src/flb_engine.c, src/flb_output.c
Currently, the capacity of chunks are not explicitly collected in metrics of fluent bit. This should be collected and described for non fluent-bit expert. Note that the capacity of chunks as percent should be collected per plugins. This is because Fluent Bit can set up different capacity of total limit of chunks per plugin.
----
**Testing**
```ini
[SERVICE]
HTTP_Server On
HTTP_Port 2021
Hot_Reload On
[INPUT]
Name dummy
rate 1000
[OUTPUT]
Name http
storage.total_limit_size 1MB
```
<details>
```log
* …
```
=> engine: output: Add metrics for displaying the available capacity of chunks as percent

plugins/in_node_exporter_metrics/CMakeLists.txt, plugins/in_node_exporter_metrics/ne.c, plugins/in_node_exporter_metrics/ne.h, plugins/in_node_exporter_metrics/ne_thermalzone.c, plugins/in_node_exporter_metrics/ne_thermalzone.h, plugins/in_node_exporter_metrics/ne_thermalzone_linux.c, plugins/in_node_exporter_metrics/ne_thermalzone_linux.h, plugins/in_node_exporter_metrics/ne_utils.c, plugins/in_node_exporter_metrics/ne_utils.h
This patch adds support for reading temperature values from `/sys/calss/thermal_zone`. The labels are replicated from the same behaviour as the prometheus node_exporter.
This plugin provides thermal reporting on linux/arm64, especially for raspberry pi 4 and other similar SBCs.
These sensors are already implemented in the prometheus node_exporter_metrics: https://github.com/prometheus/node_exporter/blob/ed1b8e3d88851806627e4f8262ee26232ca56c2c/collector/thermal_zone_linux.go#L31.
----
**Testing** …
=> in_node_exporter_metrics: add support for thermal_zone.

plugins/out_stdout/stdout.c
This patch fixes print_traces_text() function to print all ctrace contexts
the patch has been tested with opentelemetry-cpp-1.12.0/example_otlp_http http://localhost:4318/v1/traces DEBUG=yes bin, fluent-bit 2.2.0 and ctrace fix (https://github.com/fluent/ctraces/pull/46)
----
**Testing**
```
[INPUT]
listen 127.0.0.1
port 4318
successful_response_code 200
[OUTPUT]
name stdout
match *
```
```
Before fix
root@40eda9de5e56:/source/fluent-bit-2.2.0/build/bin# ./fluent-bit -c ./flb.conf
* …
```
=> out_stdout: Fix incomplete printing of traces

plugins/in_calyptia_fleet/in_calyptia_fleet.c
Upon first run of the calyptia fleet plugin there will be no fleet directory but the plugin will attempt to create it's base configuration header. Fix that by creating the fleet directory first.
----
**Testing**
----
=> in_calyptia_fleet: create configuration directory before the fleet header.

plugins/in_calyptia_fleet/in_calyptia_fleet.c
Fix a double free in the rare case that the calyptia API responds with an empty body.
----
**Testing**
----
=> in_calyptia_fleet: fix double free when calyptia API returns with an empty response payload.

src/config_format/flb_cf_yaml.c, tests/internal/config_format_yaml.c, tests/internal/data/config_format/yaml/fluent-bit-windows.yaml, tests/internal/data/config_format/yaml/service-windows.yaml
In Windows, flb-it-config_format_yaml unit test has been failed. However, the failed YAML config test is not enabled on AppVeyor. So, we didn't recognize this failure.
I'm not sure this should be the correct fix but this failure was introduced by stack based YAML parser.
This stack based parser for YAML config format is working correctly on non-Windows platforms.
Some of the functionalities of concatenating directories is not working correctly yet on Windows.
----
**Testing**
----
Fluent Bit is …
=> config_format: yaml: windows: Handle directory separator for include directive on yaml config correctly on windows

plugins/in_opentelemetry/opentelemetry.c, plugins/in_opentelemetry/opentelemetry.h, plugins/in_opentelemetry/opentelemetry_prot.c, tests/runtime/in_opentelemetry.c
This patch is to support property `tag_from_uri`.
Currently, in_otel composes tag from uri.
e.g.  v1_metrics, v1_traces or v1_logs.
It may confuse user. https://github.com/fluent/fluent-bit/issues/7939
If user set `tag_from_uri=false`, tag will be the value of property `tag`.
Default is `true` to prevent breaking current behavior.
|Key|Description|Default|
|---|---|---|
|tag_from_uri|If true, tag will be created from uri. e.g. v1_metrics from /v1/metrics .| true |
----
**Testing** …
=> in_opentelemetry: support tag_from_uri

plugins/in_kubernetes_events/kubernetes_events.c, plugins/in_kubernetes_events/kubernetes_events.h, plugins/in_kubernetes_events/kubernetes_events_conf.c, plugins/in_kubernetes_events/kubernetes_events_conf.h
input kubernetes_events currently uses a record accessor that is hard coded to `$metadata['creationTimestamp']`. This patch allows it to be configurable so that you can use other timestamp fields as the record timestamp such as `lastTimestamp` which will have the most recent event's timestamp and not the time the of the first matching kubernetes event (which could be hours/days prior) which is what the `$metadata['creationTimestamp']` is set to.
----
**Testing**
- [ X] Example configuration file for the change
```
[INPUT]
Name kubernetes_events
Tag k8s_events
timestamp_key lastTimestamp
```
If this is a change to packaging of containers or …
=> in_kubernetes_events: make timestamp from incoming record configurable

plugins/in_storage_backlog/sb.c
If a backlog chunk has corruptions and the Tag cannot be read, just completely remove it since it cannot be routed.
----
=> in_storage_backlog: if a chunk tag cannot be read, delete it

src/flb_storage.c
Fixes #8259
cio_load creates storage stream if directory exists before creating input chunks.
It prevents to create memory stream by input plugins. 
This patch is to recreate stream if the stream type is different.
----
**Testing**
```
[SERVICE] …
```
=> storage: recreate cio_stream if storage type is different(#8259)

plugins/out_stackdriver/stackdriver.c, plugins/out_stackdriver/stackdriver.h, tests/runtime/data/stackdriver/stackdriver_test_log_name.h, tests/runtime/out_stackdriver.c
A new configuration option for the out_stackdriver plugin `project_id_key` allows you to specify a key within the jsonPayload that will be used to set the GCP Project ID to export to. This allows a stackdriver out plugin that has logWriter permissions in multiple projects to write to different gcp projects based on a jsonPayload (record) key. This also introduces a default `logging.googleapis.com/projectId` key that will be used if present in the record. The key that is used from the record is removed similar to how `severity_key` and `label_key` work.
Addresses #8195
**Testing**
```
[FILTER]
Name modify
Match k8s_*project1*
Add logging_project_id prj-fluent-bit-test1
[FILTER]
Name modify
Match k8s_*project2*
Add …
```
=> out_stackdriver: add project_id_key override to allow specifying gcp project id from the record

lib/monkey/mk_server/mk_http_thread.c
This upgrade fix the thread libco params leaks that exists on exit.
----
=> lib: monkey: upgrade to v1.7.3

plugins/in_calyptia_fleet/in_calyptia_fleet.c
Release upstream connection used to connect to calyptia API when polling for configuration changes in the collect call back.
----
**Testing**
----
=> in_calyptia_fleet: release upstream conn in collect.

plugins/in_dummy/in_dummy.c, plugins/in_dummy/in_dummy.h, tests/runtime/in_simple_systems.c
This PR adds new `flush_on_startup` setting to the in_dummy input plugin. When `interval_sec/nsec` is set for a long time, its helpful to be able to verify the first event is generated at startup to avoid waiting.
Documentation update in https://github.com/fluent/fluent-bit-docs/pull/1264.
```
[INPUT]
Dummy            {"message": "Dummy", "severity": "INFO"}
Interval_NSec    0
Interval_Sec     10
Name             dummy
Start_time_sec   0
Flush_on_startup True
[OUTPUT]
Name            stdout
Match           *
```
With this config a log message is generated at startup and then every 10 seconds.
```
./fluent-bit -c fluent-bit.conf
Fluent Bit v2.2.1 …
```
=> in_dummy: Add flush_on_startup config.

plugins/in_node_exporter_metrics/ne.c
Fixes #8368 
The issue #8368 is caused by flushing metrics before updating it.
This patch is to update metrics at startup to prevent flushing empty metrics.
----
**Testing** …
=> in_node_exporter_metrics: collect metrics at startup(#8368)

tests/runtime/filter_nest.c
This patch is add test case `add_prefix` of filter_nest
----
**Testing**
```
$ valgrind --leak-check=full …
```
=> tests: runtime: filter_nest: add test case for add_prefix

conf/parsers.conf
This PR simply adds a reasonable default `logfmt` parser configuration, to allow filters to specify only `parser: logfmt` without needing a full-blown `parsers.conf`.
=> config: add default logfmt parser

plugins/in_kubernetes_events/kubernetes_events.c, plugins/in_kubernetes_events/kubernetes_events.h, plugins/in_kubernetes_events/kubernetes_events_conf.c, plugins/in_kubernetes_events/kubernetes_events_conf.h
----
This consolidates timestamp lookup logic in the kubernetes_events input and removes record accessor timestamp key logic entirely as it's not needed.
Currently during events processing logic we are fetching the timestamp from the record twice in 2 different ways.
We first use `item_get_timestamp()` that cleanly fetches the timestamp from any of the following record values in order of precedence: lastTimestamp, firstTimestamp, metadata.creationTimestamp, this is then used to look up if the current event is older than the set retention time and if so the event is discarded (via `check_event_is_filtered`). We then immediately fetch the timestamp again to set it in the event, but only look at a single field from the resource accessor (`K8S_EVENTS_RA_TIMESTAMP`). 
This diff removes the …
=> in_kubernetes_events: consolidate record timestamp logic

CMakeLists.txt
FLB_IN_EVENT_TEST is specified twice. I guess the latter prevails.
----
**Testing**
- [N/A] …
=> build: Remove duplicated line FLB_IN_EVENT_TEST

plugins/out_azure_blob/azure_blob.c, plugins/out_azure_blob/azure_blob.h, plugins/out_azure_blob/azure_blob_appendblob.c, plugins/out_azure_blob/azure_blob_blockblob.c, plugins/out_azure_blob/azure_blob_conf.c, plugins/out_azure_blob/azure_blob_http.c, plugins/out_azure_blob/azure_blob_uri.c
Sometimes user cannot use shared key authentication. So, this patch support authenticate Azure Blob Storage with shared access signatures. 
Here is the document about shared access signatures: https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview
This patch add two configuration parameters for out_azure_blob plugin: auth_type and sas_token.
- auth_type, default value is "key", it can be "key" or "sas".
- sas_token, default value is NULL, it is the SAS token, it is required when auth_type is "sas".
Fixes #8230 
------
**Testing**
```
[INPUT]
name tail
path /workspaces/fluent-bit/build/test.log
tag test.txt
[OUTPUT]
name …
```
=> out_azure_blob: add support for Azure Blob SAS authentication

include/fluent-bit/flb_config.h, include/fluent-bit/flb_network.h, src/flb_config.c, src/flb_network.c, src/flb_upstream.c
Fixes #8214 
----
**Testing**
```
[SERVICE]
flush     1
[INPUT]
name      dummy
Tag       dummy.tag
[OUTPUT]
name                   loki
match                  *
host                   listener
port                   8080
tls                    Off
net.dns.prefer_ipv6    true
```
```
version: '3.7'
services:
listener:
image: mendhak/http-https-echo
ports:
- "8080:8080"
environment:
- LOG_WITHOUT_NEWLINE=true
- ECHO_BACK_TO_CLIENT=false
networks:
app_net:
ipv6_address: 2001:db8:1::40
fluent-bit:
build:
context: .
dockerfile: dockerfiles/Dockerfile
image: fluent/fluent-bit
volumes:
- …
```
=> network: prefer ipv6 DNS results option

CMakeLists.txt
Enabling `FLB_RELEASE` should enable compiler optimizations. However, if `FLB_DEBUG` (enabled by default) was enabled at the same time, no optimization settings were applied. Now, `FLB_RELEASE` will always enable optimizations and includes debug information (`CMAKE_BUILD_TYPE` is `RelWithDebInfo`).
This issue affects all published Docker images and most likely severely degrades performance.
----
**Testing**
If …
=> build: Fix release builds with enabled FLB_DEBUG

plugins/out_forward/forward.c
I observed that memory consumption was constantly growing while the data sink of the forward plugin was unavailable. Using valgrind, it could be confirmed that there is a leak in the forward output plugin:
```
==8== 385,024 bytes in 47 blocks are definitely lost in loss record 126 of 126
==8==    at 0x4E055B4: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8==    by 0x4E0A81C: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8==    by 0x739B7B: msgpack_sbuffer_write (sbuffer.h:81)
==8==    by 0x5D5262: msgpack_pack_map (pack_template.h:753)
==8==    by 0x5D8F8A: flb_mp_map_header_init (flb_mp.c:321)
==8==    by 0x73A026: append_options (forward_format.c:103)
==8==    by 0x73AE2F: flb_forward_format_forward_mode (forward_format.c:442)
==8==    by …
```
=> out_forward: fix memory leak during connection loss

plugins/in_calyptia_fleet/in_calyptia_fleet.c
This PR is a cleanup of fixes provided originally by PR #8371
----
=> in_calyptia_fleet: general fixes from #8371

plugins/out_stackdriver/stackdriver.c, plugins/out_stackdriver/stackdriver.h, plugins/out_stackdriver/stackdriver_resource_types.c, tests/runtime/data/stackdriver/stackdriver_test_k8s_resource.h, tests/runtime/out_stackdriver.c
Add k8s_cluster resource type to out_stackdriver plugin. 
This can be used in combination with the in_kubernetes_events to write k8s_cluster type events to stackdriver (such as any non-Pod based kubernetes events)
----
**Testing**
```
[INPUT]
Name kubernetes_events
Tag k8s_events
[FILTER]
Name rewrite_tag
Match k8s_events
Rule $involvedObject['Kind'] Pod k8s_events.$metadata['namespace'].k8s_pod false
Rule $metadata['namespace'] .* k8s_events.$metadata['namespace'].k8s_cluster false
[OUTPUT]
Name stackdriver
Match k8s_events*k8s_cluster
resource k8s_cluster
k8s_cluster_name my-cluster-name
k8s_cluster_location us-central1
```
If this is a …
=> out_stackdriver: add k8s_cluster resource type

.github/workflows/cron-unstable-build.yaml, .github/workflows/staging-release.yaml
`master` now covers upcoming 3.0 release series with a separate 2.2 branch for stable releases.
Updated unstable build and container releases to cope.
----
**Testing**
----
=> workflows: update for new 2.2 branch/3.x master

src/flb_input_chunk.c
This PR adds proper accounting of chunks that are rolled over in order to release space for new chunks.
=> input_chunk: added proper accounting of chunks that are rolled over

.github/workflows/call-build-windows.yaml
Resolve https://github.com/fluent/fluent-bit/pull/8441#issuecomment-1919352111
----
**Testing**
----
=> workflows: windows: use concrete option on windows workflow [Backport 2.2]

dockerfiles/Dockerfile.windows
Also, we need to refer its headers correctly.
----
**Testing**
----
=> dockerfile: windows: Link OpenSSL libraries correctly

plugins/out_stackdriver/stackdriver.c
The k8s_pod process_local_resource_id does not process the local_resource_id if using a custom_k8s_regex.
The return that is being checked if it is 0, should actually match what is happening in k8s_container and k8s_node sections: https://github.com/fluent/fluent-bit/blob/master/plugins/out_stackdriver/stackdriver.c#L1947 because the return should be > 0 when there is an actual match.
----
**Testing**
---- …
=> out_stackdriver: fix bug in k8s_pod process_local_resource_id

plugins/out_stackdriver/stackdriver.c
When there is an api error (ie a permission denied, or other error) when submitting to the google logging api, we get a print out of the payload text, but that is not specific enough to debug the issue. Adding the chunk tag (which usually comes from an input plugin like tail) may assist in finding the root cause of the issue. 
Ideally I'd like the output success / failure metrics to include the logName as a tag, but this is much more involved as this would require looping through every entry in the logging request to get the entry number and logName and that would have to be compared to the response. Maybe this is less work that i initially assessed but it would possibly be a good idea and something that we can put into a feature request in the future.
----
Enter `[N/A]` in the box, if an …
=> out_stackdriver: print tag with api error message

include/fluent-bit/flb_mp.h, plugins/out_opentelemetry/opentelemetry.c, plugins/out_opentelemetry/opentelemetry.h, plugins/out_opentelemetry/opentelemetry_conf.c, src/flb_mp.c
The following patch fix and enhance the OpenTelemetry output connector when handling log records.
In Fluent Bit world, we deal with ton of unstructured log records which comes from variety of sources, or just simply raw text files. When converting those lines to structured messages, there was no option to define what will be the log body and log attributes and everything is packaged inside log body by default.
This patch enhances the previous behavior by allowing the following:
- log body: optionally define multiple record accessor patterns that tries to match a key or sub-key from the record structure. For the first matched key, it's value is used as part of the body content. If no matches exists, the whole record is set inside the body.
- log attributes: if the log record contains …
=>  out_opentelemetry: enhancements for log body and attributes handling (fix #8359)     

include/fluent-bit/flb_metrics.h, plugins/out_cloudwatch_logs/cloudwatch_api.c, plugins/out_cloudwatch_logs/cloudwatch_api.h, plugins/out_cloudwatch_logs/cloudwatch_logs.c, tests/runtime/out_cloudwatch.c
~~This PR depends on [EMF encoder support on cmetrics](https://github.com/fluent/cmetrics/pull/192). So, the current PR status is _canary_.~~
This PR supports metrics type of plugins handling on out_cloudwatch_logs plugin.
On ingested the metrics type of events, cmetrics will encode JSON/EMF format to prepare ingesting to the Cloudwatch Logs' metrics.
----
**Testing**
```python
[SERVICE]
Flush        10
Hot_Reload   On
Grace 5
[INPUT]
Name fluentbit_metrics
[FILTER]
Name stdout
Match *
[OUTPUT]
Name cloudwatch_logs
Match *
log_stream_name …
```
=> out_cloudwatch_logs: Support EMF format for metrics type of events

plugins/in_head/in_head.c
"split_line" of in_head doesn't work at least v2.1.2.
in_head outputs blank value.
This patch is  to fix this issue.
----
**Testing**
```
pipeline:
inputs:
- name: head
tag: head.cpu
file: /proc/cpuinfo …
```
=> in_head: fix buffer length for split_line

include/fluent-bit/flb_gzip.h, plugins/in_http/http_prot.c, src/flb_gzip.c
This change adds support for gzipped content to in_http. I discovered this by accident when attempting to send gzipped JSON from another fluent-bit, and found that fluent-bit responded with an invalid JSON error. With this PR, fluent-bit will now appropriately handle gzipped content on the HTTP input.
----
**Testing**
----
=> Adds support for Content-Encoding: gzip to in_http

plugins/out_http/http.c, plugins/out_http/http.h, plugins/out_http/http_conf.c, tests/runtime/out_http.c
Default `out_http` to JSON format so it works with in_http. Setting the output format to msgpack is still possible by setting it manually.
----
**Testing**
----
=> out_http: default the output format to JSON.

src/flb_network.c, src/flb_utils.c, tests/internal/utils.c
After updated the latest command line tools, I got int conversion errors.
These should be generated using POSIX version of strerror_r and needless flb_free calling.
The latter one is able to be confirmed with:
```
% leaks -atExit -- bin/flb-it-utils test_flb_utils_get_machine_id
flb-it-utils(34841) MallocStackLogging: could not tag MSL-related memory as no_footprint, so those pages will be inc
luded in process footprint - (null)
flb-it-utils(34841) MallocStackLogging: recording malloc and VM allocation stacks using lite mode
Test test_flb_utils_get_machine_id...           [ OK ]
SUCCESS: All unit tests have passed.
Process 34841 is not debuggable. Due to security restrictions, leaks can only show or save contents of readonly memo
ry of restricted processes.
Process:         flb-it-utils …
```
=> network: utils: Fix int conversion errors

plugins/processor_content_modifier/cm.c
Quick fix for compile error on certain machines to match cb_processor_logs to the pointer type declared for processors.
----
**Testing**
----
=> processor_content_modifier: fix cb_processor_logs callback arguments type

plugins/in_tail/tail.c
Fixes #8487 
This patch is to flush multiline data before exit on EOF.
----
**Testing**
test.conf:
```
[SERVICE]
Flush             1
Daemon            Off
Parsers_File      parsers.conf
[INPUT]
Name …
```
=> in_tail: flush multiline before exit on EOF

src/flb_network.c, src/flb_utils.c, tests/internal/utils.c
This is backport PR for https://github.com/fluent/fluent-bit/pull/8555.
----
**Testing**
----
=> network: utils: Fix int conversion errors [Backport to 2.2]

plugins/in_forward/fw.c, plugins/in_forward/fw.h, plugins/in_forward/fw_config.c, plugins/in_forward/fw_conn.c, plugins/in_forward/fw_conn.h, plugins/in_forward/fw_prot.c, plugins/in_forward/fw_prot.h
In forward protocol, there is a definition for handshake.
When using out_forward on Fluentd with `<security>` directive(s), out_forward on Fluentd hangs due to Fluent Bit didn't implement handshake protocol on its in_forward.
This PR aims to implement handshake protocol. ~~but I didn't implement user authentication part yet.~~ User authentication is also implemented in this PR.
----
**Testing**
```ini
[SERVICE]
Flush        5
HTTP_Monitor Off
[INPUT]
Name forward
Listen 0.0.0.0
Port 24224
shared_key  FluentBit
security.users fluentd changeme
tls         On
tls.verify  Off
tls.crt_file …
```
=> in_forward: Implement handshake protocol

include/fluent-bit/flb_network.h, plugins/in_collectd/in_collectd.c, plugins/in_event_test/event_test.c, plugins/in_statsd/statsd.c, src/flb_downstream.c, src/flb_network.c, tests/internal/network.c
This PR adds the port sharing feature which allows more than one input plugin to share a listener in order to balance the load.
=> network: add port sharing feature

CMakeLists.txt, include/fluent-bit/flb_lib.h, include/fluent-bit/flb_metrics.h, include/fluent-bit/flb_processor.h, plugins/CMakeLists.txt, plugins/processor_labels/labels.c, plugins/processor_metrics_selector/CMakeLists.txt, plugins/processor_metrics_selector/selector.c, plugins/processor_metrics_selector/selector.h, src/flb_input_metric.c, src/flb_lib.c, src/flb_processor.c, tests/runtime/CMakeLists.txt, tests/runtime/processor_metrics_selector.c
For processing metrics, we need to move using processors because there is less motivations in the current implementation to use processors based pipeline.
If we provide filtering feature on this mechanism, users want to use processors from the classic configuration.
Also, ordinary filters are intended to use non-processor world due to msgpack based ingestion on ingesting filters. This is really hard to distinguish which types of events: logs, metrics, and traces.
Instead, the interface of processor provides easily to be able to distinguish three types of events.
----
**Testing**
```yaml
service:
flush: 5
daemon: off
log_level:  debug
pipeline: …
```
=> processor: Implement native processor metrics_selector

plugins/in_winevtlog/winevtlog.c
Fluent Bit is also using pull subscription model for collecting Windows EventLog. Through a registered signal, we're able to obtain the internal state of EvtSubscribe API.
Like as https://github.com/fluent-plugins-nursery/winevt_c/pull/44 fix, Fluent Bit can be made to detect the failure of the subscription.
We need to check it for more strict approach to handle subscription for EventLog.
When failed status is returned from a registered signal, we should recreate the subscription if possible.
This signal approach is inspired from the article: https://learn.microsoft.com/en-us/windows/win32/wes/subscribing-to-events#pull-subscriptions
This article describes that when using the pull type of subscription, EvtSubscribe can tell whether Windows EventLogs are collected or not via a registered …
=> in_winevtlog: Display error on invalid subscription state

src/flb_reload.c, src/http_server/api/v2/reload.c
When the reloading signal (SIGHUP) is received, the reloading process is sometimes in progress.
For HTTP API, we need to distinguish and switch the response when reloading / ready to reload.
```
*   Trying 127.0.0.1:2021...
* Connected to localhost (127.0.0.1) port 2021 (#0)
> POST /api/v2/reload HTTP/1.1
> Host: localhost:2021
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Length: 2
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: Monkey/1.7.2
< Date: Tue, 06 Feb 2024 05:59:19 GMT
< Transfer-Encoding: chunked
< Content-Type: application/json
< 
* Connection #0 to host localhost left intact
{"reload":"done","status":0}
```
```
*   Trying 127.0.0.1:2021...
* Connected to localhost (127.0.0.1) port 2021 (#0)
> POST …
```
=> api: v2: reload: Prevent duplicated request via api v2 reload

src/flb_reload.c, src/http_server/api/v2/reload.c
This is backport PR for https://github.com/fluent/fluent-bit/pull/8461.
----
**Testing**
----
=>  api: v2: reload: Prevent duplicated request via api v2 reload [Backport 2.2]

include/fluent-bit/flb_msgpack_append_message.h, plugins/in_tcp/tcp.c, plugins/in_tcp/tcp.h, plugins/in_tcp/tcp_conn.c, plugins/in_tcp/tcp_conn.h, src/CMakeLists.txt, src/flb_msgpack_append_message.c, tests/internal/CMakeLists.txt, tests/internal/data/msgpack_append_message/map1.json, tests/internal/msgpack_append_message.c, tests/runtime/in_tcp.c
Currently, in_tcp plugin does not offer adding source address feature.
This PR provides this feature.
----
**Testing**
```python
[INPUT]
Name        tcp
Listen      0.0.0.0
Port        5170
Chunk_Size  32
Buffer_Size 64
Format      json
Source_Address_Key source_host
[OUTPUT]
Name        stdout
Match       *
```
```log
Fluent Bit v2.1.7
[2023/07/10 14:30:42] [ info] Configuration:
[2023/07/10 14:30:42] [ info]  flush time     | 1.000000 seconds
[2023/07/10 14:30:42] [ info]  grace          | 5 seconds …
```
=> in_tcp: Add a capability to inject source IP

include/fluent-bit/flb_gzip.h, plugins/in_http/http_prot.c, src/flb_gzip.c
This is a backport PR for https://github.com/fluent/fluent-bit/pull/7667.
----
**Testing**
----
=> in_http: Adds support for Content-Encoding: gzip [Backport to 2.2]

plugins/custom_calyptia/calyptia.c
This patch is to fix #8530 and release ctx when initialization failed.
#8530 points following code is vulnerable.
Because `setup_cloud_output` can release ctx and it means `ctx->o` can be freed memory.
```c
ctx->o = setup_cloud_output(config, ctx);
if (ctx->o == NULL) {
return -1;
}
```
----
**Testing** …
=> custom_calyptia: fix using after freed memory(#8530)

src/flb_pack.c
When converting from msgpack to raw JSON or sds-json, the reallocation strategy is very convervative to keep the memory usage very low, but in most of scenarios this lead to more fragmentation and high CPU usage.
This patch changes the memory reallocation with an exponential strategy for better performance.
Kudos to @LukasJerabek and @lecaros for helping to troubleshoot and indentify the root cause of this issue.
Here are some comparison before and after the changes:
**before**
note: the test could not finish, takes too long
**after**
note: it finished pretty quickly
----
=> pack: increase buffer reallocation for higher performance (fix #8492)

plugins/out_opentelemetry/opentelemetry.c, plugins/out_opentelemetry/opentelemetry.h, plugins/out_opentelemetry/opentelemetry_conf.c
This patch is to support several metadata key properties to get a OTLP values from metadata.
See also https://github.com/fluent/fluent-bit/pull/8294 and https://github.com/fluent/fluent-bit/issues/8205
|key|Description|Default|
|---|--|---|
|logs_observed_timestamp_metadata_key| Specify an ObservedTimestamp key to look up in the metadata. |ObservedKey|
|logs_timestamp_metadata_key|Specify an Timestamp key to look up in the metadata. |Timestamp|
|logs_severity_key_metadata_key|Specify an SeverityText key to look up in the metadata.|SeverityText|
|logs_severity_number_metadata_key| Specify an SeverityNumber key to look up in the metadata.|SeverityNumber|
|logs_trace_flags_metadata_key|Specify an Flags key to look up in the metadata.|Flags|
|logs_span_id_metadata_key|Specify an SpanId key to …
=> out_opentelemetry: support metadata key properties

plugins/processor_content_modifier/cm_logs.c, tests/runtime/CMakeLists.txt, tests/runtime/processor_content_modifier.c
- Add test code for "logs" using processor_content_modifier
- Fix not freed memory issue for processor_content_modifier
Note: Test code for `metrics` and `traces` are not implemented.
Memory issue is 
```
==66962== HEAP SUMMARY:
==66962==     in use at exit: 105 bytes in 2 blocks
==66962==   total heap usage: 12,619 allocs, 12,617 frees, 4,267,696 bytes allocated
==66962== 
==66962== 105 (24 direct, 81 indirect) bytes in 1 blocks are definitely lost in loss record 2 of 2
==66962==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==66962==    by 0x96CE2F: cfl_variant_create (cfl_variant.c:242)
==66962==    by 0x96CB1A: cfl_variant_create_from_string_s (cfl_variant.c:94)
==66962==    by 0x53D9A7: cfl_variant_convert (cm_logs.c:182) …
```
=> tests: runtime: processor_content_modifier: add test code

plugins/in_elasticsearch/in_elasticsearch_bulk_prot.h
This patch is to fix following warnings.
```
[ 57%] Building C object plugins/in_elasticsearch/CMakeFiles/flb-plugin-in_elasticsearch.dir/in_elasticsearch.c.o
In file included from /home/taka/git/fluent-bit/plugins/in_elasticsearch/in_elasticsearch.c:28:
/home/taka/git/fluent-bit/plugins/in_elasticsearch/in_elasticsearch_bulk_prot.h:31:46: warning: ‘struct in_elasticsearch_bulk_conn’ declared inside parameter list will not be visible outside of this definition or declaration
31 |                                       struct in_elasticsearch_bulk_conn *conn,
|                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/taka/git/fluent-bit/plugins/in_elasticsearch/in_elasticsearch_bulk_prot.h:36:52: warning: ‘struct in_elasticsearch_bulk_conn’ declared inside parameter …
```
=> in_elasticsearch: include file to fix warnings

plugins/filter_nest/nest.c
https://github.com/fluent/fluent-bit/issues/8137
An arg of `FLB_LOG_EVENT_STRING_LENGTH_VALUE` is a `flb_log_event_encoder_size_t`. 
`flb_log_event_encoder_size_t` is `size_t*` on Windows. 
It can cause pointer arithmetic and the output can be larger value. 
e.g. `FLB_LOG_EVENT_STRING_LENGTH_VALUE(10+3)` can be 10 + sizeof(size_t*) * 3 = 34.
We use 'new_size' to prevent pointer arithmetic.
----
**Testing**
If this is a change to packaging of containers or …
=> filter_nest: define a new var to prevent pointer arithmetic

plugins/processor_sql/parser/CMakeLists.txt
flb_mem.h wants to depend on jemalloc when FLB_JEMALLOC is turned on.
jemalloc building order itself is mostly controlled by `target_link_libraries(fluent-bit-static libjemalloc)`. However, processor-sql-parser library does not have such dependency indication of jemalloc.
This should be lack of information for building order after the bundled jemalloc is built.
This PR fixes the order glitch.
----
**Testing**
---- …
=> processor_sql: Ensure jemalloc compiling before starting to build sql parser

plugins/processor_sql/parser/sql-parser.y
Because `%option warn noyywrap nodefault` option is already specified in sql-parse.l and it seems that no need to define yywrap in sql-parser.y.
Resolves #8606.
----
**Testing**
----
=> processor_sql: Remove a needless yywrap definition

src/http_server/flb_http_server_http2.c
This PR adds the code required to send WINDOW_UPDATE  frames when receiving large payloads.
=> http_server: removed deprecated code and added window update handling

packaging/build.sh
Theoretically, podman cli could be used for creating packages. The default command for container cli should be docker.
To use _podman_ instead of _docker_, define `FLB_DOCKER_CLI=podman`. Then podman is working with build and run commands.
----
**Testing**
----
=> packaging: build: Make to be able to replace docker cli via environment variable

lib/nghttp2/CMakeLists.txt
Even if dusabling the auto-detection for OpenSSL in nghttp2, 
I got the following result:
```python
[INPUT]
Name        http
Port        8080
tls         On
tls.verify  Off
tls.crt_file self_signed.crt
tls.key_file self_signed.key
[OUTPUT]
Name stdout
Match *
```
```
% bin/fluent-bit -c in_http.conf
Fluent Bit v3.0.0
\_   _____/|  |  __ __   ____   _____/  |_  \______   \__|/  |_  ___  _\_____  \ 
|    __)  |  | |  |  \_/ __ \ /    \   __\  |    |  _/  \   __\ \  \/ / _(__  < 
|     \   |  |_|  |  /\  ___/|   |  \  |    |    |   \  ||  |    \   / /       \
\___  / …
```
=> lib: nghttp2: Disable auto-detection for OpenSSL

src/http_server/flb_http_server_http1.c
As pointed out by Phil in PR #8643 this PR changes the http1 side of the http server component to reset the parser and request contexts after each cycle to prevent them from erroneously referenced already released memory.
=> http_server: added parser reset code to prevent use after free 

include/fluent-bit/flb_task.h, src/flb_engine_dispatch.c, src/flb_task.c
When a task is not created and the filesystem storage is used, then set the chunk down
Fixes #8395 #7329 #5485 #5217
----
**Testing**
- [N/A] …
=> engine_dispatch: remove chunks from memory if the task fails to be created

plugins/in_forward/fw_prot.c
On out_forward in Fluentd payloads, sometimes gzip compressed payloads are concatenated because Fluentd has a capability to compress its buffers with gzip compression.
With this circumstance, Fluentd sometimes concatenates its payloads on forward protocol.
This causes that Fluent Bit gives up to uncompress for the concatenated ones.
In this PR, I implemented for decoding way to distinguish whether the ingested forwarded payloads is concatenated or not.
This is not mandatory specification and not well-documented behavior on Ruby's zlib gem. 
But, in fact, Fluentd is heavily relying on this behavior for saving the CPU usage to avoid unnecessary compressions/decompressions. 
This is why I found that the reason Fluentd is actually relying on the concatenated gzipped payloads: …
=> in_forward: Handle multiply concatenated gzip payloads

src/wamrc/CMakeLists.txt
This is because macOS's homebrew sometimes introduces the cutting edge version of Formulae.
So, we need to make a room for user specified LLVM_DIR here.
----
**Testing**
----
=> wamrc: build: macos: Prioritize for defined LLVM_DIR environment variable

plugins/out_websocket/websocket.c, plugins/out_websocket/websocket.h
This adds the ability to add additional headers to the websocket handshake, identical to how we specify headers in out_http. This allows users of the websocket output to handshake with an authenticated endpoint for example.
Fixes #8367
----
**Testing**
```
[INPUT]
Name   dummy
[OUTPUT]
Name websocket
Match *
Host foo.bar.com
URI /my/path
Port 443
Format json_lines
Header Authorization bearer my_token
TLS on
```
```
Fluent Bit v3.0.0
\_   _____/|  |  __ __   ____   _____/  |_  \______   \__|/  |_ …
```
=> out_websocket: Add ability to provide additional headers

src/flb_input_chunk.c
Some debug messages in the input_chunk interface are just very noisy that adds little value for majority of users, since they are mostly developer focus I am switching them to trace mode
----
=> input_chunk: handle some chunk size debug messages as traces

plugins/out_loki/loki.c
This PR will lower the severity of the message: 
`empty record accessor key translation for pattern`
from warning to debug level. This prevents from spamming the Fluent Bit log, in case logs sometimes do not have all defined labels filled.
Fixes: #6231
**Testing**
- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new …
=> out_loki: Change loglevel for non-existing but defined label in record

plugins/in_tail/tail.c, plugins/in_tail/tail_config.h, plugins/in_tail/tail_db.c, plugins/in_tail/tail_db.h, plugins/in_tail/tail_sql.h, tests/runtime/in_tail.c
Preventing incorrect inode usage from db.
The first commit involves deleting items that are not being monitored by Fluent-Bit when it starts.
The second commit involves considering already running Fluent-Bit instances, preventing incorrect inode usage during execution.
This commit is more about enhancement option than fixing a bug. That's why 'true' and 'false' may be needed depending on the user's use case.
Fixes #8025
----
**Testing**
- fluent-bit-test.conf
```
[SERVICE]
flush        1
log_level    info
parsers_file parsers.conf
plugins_file plugins.conf
storage.path /tmp/storage
storage.sync normal …
```
=> in_tail: Preventing incorrect inode usage from db. #8025

src/flb_task.c
=> task: on retry, only put chunk down if there are no users (fix #8691)

plugins/out_oracle_log_analytics/oci_logan.c
Fresh the variable `tmp_sds` (which is still holding info for header `host`) before handle the new header `x-content-sha256`.
Fixes #8684
----
**Testing**
```
[SERVICE]
flush 1
[INPUT]
Name   dummy
[Output]
Name oracle_log_analytics
Match *
Namespace ${namespace}
config_file_location /mnt/oci-config
oci_la_log_group_id ${group_id}
oci_la_log_source_name source-name
tls On
tls.verify Off
```
```
[2024/04/08 14:11:48] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] placed request
[2024/04/08 14:11:48] [debug] [output:oracle_log_analytics:oracle_log_analytics.0] request header POST …
```
=> fix Oracle Log Analytics output plugin 400 Bad Request issue

src/fluent-bit.c
This is a small change to fix a compilation error when using `FLB_HAVE_STATIC_CONF`.
----
**Testing**
- [N/A] Set `ok-package-test` label to test for all targets (requires maintainer …
=> config: fix compilation with FLB_HAVE_STATIC_CONF.

tests/internal/log.c
The `flb-it-log` is failing sporadically. I believe this is because initially time is counted from 1 second before the message is first cached for both messages being test, TEST_RECORD_1 and TEST_RECORD_2.
```
[ FAILED ]
log.c:18: Check (start + timeout) >= now... failed
clock error, unsuppresed log: now=1712179281, timeout=1712179280, diff=1
log.c:110: Check ret == 0... failed
log.c:18: Check (start + timeout) >= now... failed
clock error, unsuppresed log: now=1712179281, timeout=1712179280, diff=1
log.c:114: Check ret == 0... failed
Test cache_one_slot...                          
[ OK ]
FAILED: 1 of 2 unit tests has failed.
```
Only a single failure is registered even though the loop occurs twice. This lines up with the idea that it is an off-by-one caused by starting the clocks one …
=> test: internal: log: fix failures caused by timing issue.

plugins/filter_kubernetes/kube_conf.h, plugins/filter_kubernetes/kube_meta.c, plugins/filter_kubernetes/kubernetes.c
fix regression in 3.0 from #8279
fixes #8642
Adds a new namespace_metadata_only config option that is off by default. When this option is enabled it allows you to fetch only namespace metadata without also having to fetch pod metadata.
----
**Testing**
https://github.com/fluent/fluent-bit-docs/pull/1352
----
=> in_kubernetes_filter: add namespace_metadata_only option to fix regression from #8279

tests/internal/fuzzers/cmetrics_decode_fuzz.c
Add missing include to fix clang-18 error:
```
2 warnings and 1 error generated.
/src/fluent-bit/tests/internal/fuzzers/cmetrics_decode_fuzz.c:53:18: error: call to undeclared function 'cmt_decode_msgpack_create'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
53 |         result = cmt_decode_msgpack_create(&cmt, (char *) data, size, &off);
|                  ^
```
----
**Testing**
I've only tested this via oss-fuzz, after bumping the oss-fuzz clang version to clang-18.
I've used this command in the oss-fuzz project to test:
```
oss-fuzz# python3 infra/helper.py build_fuzzers --sanitizer address    --engine libfuzzer fluent-bit
```
Docs, Backport, or other testing should not be needed, I think.
----
Fluent Bit is licensed under Apache …
=> Update cmetrics_decode_fuzz.c: Add missing include

plugins/in_winevtlog/in_winevtlog.c
Previously, I had chosen to restrict with the threshold to prevent unlimited subscribing per a cycle.
This should cause flood of memory comsumptions but it depends on the amound of the channels of Windows EventLog.
Nowadays, this plugin is getting widely used.
Also, in the fluent community slack, there is a request to make to be able to configure for this threshold per a cycle.
To prevent slowing down for the subscribe the channels, it won't de able to set up below 512KiB with the newly introduced parameter.
----
**Testing**
```powershell
PS> bin/fluent-bit -i winevtlog -p channels=application -p threshold_size=1MB -p USE_ANSI=On -p …
```
=> in_winevtlog: Make configurable for the size of collecting threshold per a cycle

plugins/in_http/http_conn.c
Reassign pointers in mk_http_request when the request buffer is reallocated. If this is not done a crash occurs when in_http attempts to check header values or the uri.
----
**Testing**
----
=> in_http: reassign mk_http_request values on realloc.

plugins/filter_multiline/ml.c, plugins/filter_multiline/ml.h, plugins/filter_rewrite_tag/rewrite_tag.c, plugins/filter_rewrite_tag/rewrite_tag.h, plugins/in_emitter/emitter.c, src/flb_input.c, tests/runtime/filter_multiline.c
This PR covers two issues:
1) This PR corrects the behavior of a reached mem_buf_limit. The plugin used to accept further records even after being paused which leads to https://github.com/fluent/fluent-bit/issues/8198
2) The current `in_emitter` implementation results in ***only one record per chunk*** being created, which is suboptimal. This PR fixes the collector handling: 
Please refer to line:
https://github.com/fluent/fluent-bit/blob/9652b0dc6fd9e59ef87c3bdc59c89da9abed995b/plugins/in_emitter/emitter.c#L165
To validate this observation, please use:
- fluent-bit.conf https://gist.github.com/drbugfinder-work/e5b28ed2c2247c741695eca7c3add110
- multiline_parsers.conf https://gist.github.com/drbugfinder-work/a9979a730fef75242d5cb4058dc93757
- in_emitter_debug_output.diff …
=> in_emitter: Fix single record chunks and respect mem_buf_limit pause

plugins/in_splunk/splunk.h, plugins/in_splunk/splunk_config.c, plugins/in_splunk/splunk_prot.c, plugins/out_splunk/splunk.c, plugins/out_splunk/splunk.h, plugins/out_splunk/splunk_conf.c
Currently, in_splunk does not have a capability to store and propagate the ingested Splunk token.
This could be needed to handle for simplifying logs pipeline for ingesting payloads of Splunk HEC format.
----
**Testing**
On terminal:
```console
$ bin/fluent-bit -i splunk -p port=8088 -o splunk -p port=8081 -psplunk_token=db496524-e7e6-4ae9-b3f0-2287d8e65cd4 -p "event_key=\$event" -f 1 -v
```
And another terminal:
```console
$ bin/fluent-bit -i splunk -p port=8081 -o stdout 
```
```log
Fluent Bit v3.0.3 …
```
=> in_splunk: out_splunk: Propagate ingested splunk_token authentication header

plugins/out_chronicle/chronicle.c
The actual size of payloads on out_chronicle is determined by the results of `chronicle_format`. Due to the metadata and timestamps, the first attempt to create a payload can exceed the limit of chronicle, which is 1MiB (= 1 * 1024 * 1024). This will set a smaller threshold and retry sending the data.
----
=> out_chronicle: handle 1MB or larger chunks

plugins/out_http/http.c, plugins/out_http/http.h
json_lines currently results in Content-Type `application/json`, but it should be `application/x-ndjson`.
Fluentd uses `application/x-ndjson`
https://github.com/fluent/fluentd/blob/284bf4064a9831f5262330a94e3505e09ef6a068/lib/fluent/plugin/out_http.rb#L192
This spec here suggests the same: https://github.com/ndjson/ndjson-spec?tab=readme-ov-file#33-mediatype-and-file-extensions
----
**Testing**
If this is a …
=> out_http: Use x-ndjson content type for json_lines

plugins/in_elasticsearch/in_elasticsearch.c, plugins/in_http/http.c, plugins/in_opentelemetry/opentelemetry.c, plugins/in_splunk/splunk.c, src/flb_http_common.c, src/http_server/flb_http_server_http1.c
This patch moves the initialisation of a HTTP/1.1 stream from the session initialisation to the session ingestion step.
Previously, using keep-alive on HTTP/1.1 would panic on the second request, as it would attempt to use components like the header map that are destroyed after each stream, but only initialised at the start of the session, when the HTTP protocol autodetection was run.
With this fix, HTTP/1.1 keep-alive is now enabled for the HTTP, OpenTelemetry, Elasticsearch and Splunk inputs
Fixes #8758
----
**Testing**
If this is a change to packaging of containers or native binaries then …
=> http_server: Fix keep-alive for HTTP/1.1 requests

.github/workflows/call-build-macos.yaml
GitHub now published hosted runners which are based on M1 macOS: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
To use them and continue to use Intel mac runners, we need to specify them with build matrix and set up with `macos-12` and `macos-14`. Now, macos-latest is pointed in macos-14. So, we need to specify macos-12 or macos-13 explicitly to create Intel Mac artefacts.
----
**Testing** …
=> workflows: macos: Use matrix for building Apple Silicon artefacts

plugins/filter_aws/aws.c, plugins/filter_aws/aws.h, tests/runtime/filter_aws.c
PR adds handling errors received while fetching metadata groups in the Filter AWS functionality. It also allows to define the retries interval if such scenario occurs.
```
retry_interval_s   Defines minimum duration between retries for fetching metadata groups
> default: 300, type: integer
```
Our current behaviour is to not inject any AWS metadata if fetching just one piece of information fails. It might be not the best approach as most likely we would like to inject as much as we can. In other words, it would be better to have some additional AWS labels, if we can fetch them, rather than nothing.
For example, on current `master`, if Instance Metadata server misbehaves and our implementation fails to fetch EC2 tags, then output logs won't contain any AWS Metadata labels. Even the basic …
=> filter: aws metadata group retries

plugins/out_kafka/kafka.c
This commit increases the max length of kafka dynamic topics.
As the limit previously set (64) seemed arbitrary, and kafka allows for a maximum of 249 characters per topic, I think fluentbit should reflect that limit.
Fixes #4337 
----
**Testing**
----
=> out_kafka: increase max kafka dynamic topic length to 249 characters

plugins/processor_labels/labels.c
Insert implies that adding new key-value pairs of labels. However, we did put the existence check for the keys of labels. This shouldn't be effective for such operation
----
**Testing**
```yaml
service:
flush: 2
daemon: off
log_level:  debug
pipeline:
inputs:
- name: fluentbit_metrics
tag: fluentbit.metrics
scrape_interval: 2
processors:
metrics:
- name: labels
insert: agent fluentbit
outputs:
- name: stdout
match: '*'
```
```log
Fluent Bit v3.0.4
___________.__                        __    __________.__  __ …
```
=> processor_labels: Remove a needless existence check for insert operation

src/flb_kernel.c
Config: fix incorrect assignment of kernel version between major and minor
----
**Testing**
----
=> Config: fix incorrect assignment of kernel version between major and minor

plugins/out_splunk/splunk.c, plugins/out_splunk/splunk_conf.c
In Splunk output plugin fix record accessor key for hec_token. Record accessor key should start with `$` else `flb_ra_translate` function simply returns the key as value. `flb_ra_translate` returns an empty string if key is not found which would pass `if (hec_token)` check, so we need to use `flb_ra_translate_check` function to return NULL if key is not found.
At this function https://github.com/fluent/fluent-bit/blob/3529bbb13236d8127df60be027543ec9212268b1/plugins/out_splunk/splunk.c#L350-L369  I am not sure if we really want to check for `if (ctx->event_sourcetype_key)` existence before searching for `hec_token` key. Either we should check for `metadata_auth_key` in which case if statement is redundant as `metadata_auth_key` is always defined. …
=> fix: splunk output plugin correct record accessor key for hec_token

plugins/out_datadog/datadog.c
These options are useful when there is no attribute in the incoming log that indicates the field to use for the `source` or `service` attributes, but otherwise the backend will automatically look for both in the incoming log attributes.
Ref: #8687
**Testing**
----
=> out_datadog: Update the descriptions of special field options

plugins/in_kubernetes_events/kubernetes_events.c
The time code was refactored earlier but some code was not updated correctly to use the same type. This PR attempts to fix it.
----
**Testing**
----
=> in_kubernetes_events: update time check to use struct flb_time.

tests/runtime/in_podman_metrics.c
At some point the counters API was refactored to use `cfl_list` instead of `mk_list`. Update the `check_metric` function to match.
----
**Testing**
----
=> tests: in_podman_metrics: refactor iteration of counters to use cfl_list.

src/flb_config.c
In the current code, `config->log_file` may be referenced in the `log_push` function after it is freed. This fix frees `log_file` after calling `flb_log_destroy` function so that it waits for `log_worker_collector` function to exit.
Fixes #8429 
----
**Testing**
[valgrind.log](https://github.com/fluent/fluent-bit/files/14294441/valgrind.log) …
=> engine: free after log worker thread has been stopped

plugins/out_splunk/splunk.c, plugins/out_splunk/splunk.h, plugins/out_splunk/splunk_conf.c
The following patch perform 2 changes in the code that helps to fix the problems found with Splunk hec token handling:
1. In the recent PR #8793, when using the record accessor API flb_ra_translate_check() to validate if the hec_token field exists, leads to noisy log messages since that function warns the issue if the field is not found. Most of users are not using hec_token set by Splunk input plugin, so their logging gets noisy.
This patch replaces that call with flb_ra_translate() which fixes the problem.
2. If hec_token was set in the record metadata, it was being store in the main context of the plugin, however the flush callbacks that formats and deliver the data runs in separate/parallel threads that could lead to a race condition if more than onen thread tries to manipulate the …
=> out_splunk: reduce noise and fix hec_token handling (fix #8859)

plugins/in_winevtlog/winevtlog.h
The `total_size_threshold` field was originally an unsigned int. The field in the config map uses `FLB_CONFIG_MAP_SIZE`, which reads the value as a `size_t` and then writes it to the offset of the field in the struct. On a 64-bit machine, this is 8 bytes. This means the 8 byte value would be written at this offset, as a result overriding the value of the next struct field. This would cause `string_inserts` with default values to end up being `false` when it should be `true`.
This PR changes `total_size_threshold` to a `size_t`. This seems consistent with other usages of `FLB_CONFIG_MAP_SIZE` that I was able to find.
#8854
----
**Testing**
- …
=> winevtlog: change total_size_threshold to size_t

include/fluent-bit/flb_output.h, tests/runtime/processor_metrics_selector.c
This patch passes an cmt_out_context pointer so that output processors can modify metrics.
Without this change, it is not possible to modify metrics in an output processor. Example config which reproduces:
```yaml
service:
flush: 1
pipeline:
inputs:
- name: event_type
tag: event
type: metrics
outputs:
- name: stdout
match: event
processors:
metrics:
- name: metrics_selector
metric_name: /kubernetes/
action: include
```  
Without the patch, we observe unmodified metrics:
```
2024-05-21T17:51:30.526411118Z kubernetes_network_load_counter = 3
2024-05-21T17:51:30.526411118Z kubernetes_network_load_counter{hostname="localhost",app="cmetrics"} = 1
2024-05-21T17:51:30.526411118Z kubernetes_network_load_counter{hostname="localhost",app="test"} = 12.15 …
```
=> output: Fix handling of metrics in output processor

packaging/build-config.json, packaging/distros/ubuntu/Dockerfile, packaging/update-repos.sh
=> packaging: add build support for ubuntu 24.04 noble numbat

plugins/out_stackdriver/stackdriver.c, plugins/out_stackdriver/stackdriver.h, tests/runtime/data/stackdriver/stackdriver_test_payload.h, tests/runtime/out_stackdriver.c
Write payload to textPayload field of LogEntry if the text_payload_key is string format and the only field after stripping special fields.
----
**Testing**
```
[OUTPUT]
Name                      stackdriver
Match                     etcd
Resource                  gke_container
severity_key              severity
text_payload_key          message
test_log_entry_format     true
k8s_cluster_name          test-cluster
k8s_cluster_location      us-central1-c
export_to_project_id      customer-project
```
Change is unit tested.
```
cmake -DFLB_DEV=On -DFLB_TESTS_RUNTIME=On -DFLB_TESTS_INTERNAL=On -DFLB_VALGRIND=On ../ && make -j 8
valgrind …
```
=> out_stackdriver: Support writing to textPayload field of Cloud Logging LogEntry.

src/fluent-bit.c
The tls variable for out_flush_params is not initialized as the flb_start function is not called during the dry run. Call flb_init directly and then shutdown the engine.
```
configuration test is successful
================================================================= ==63633==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x0001f71b3ac0 in thread T0
#0 0x103c9f260 in wrap_free+0x98 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x53260)
#1 0x100179d9c in flb_free flb_mem.h:127
#2 0x10017f4a0 in flb_output_exit flb_output.c:481
#3 0x1001cb038 in flb_engine_shutdown flb_engine.c:1119
#4 0x10010d45c in flb_destroy flb_lib.c:240
#5 0x100008c40 in flb_main fluent-bit.c:1348
#6 0x10000c644 in main fluent-bit.c:1456
#7 0x18f11e0dc  (<unknown module>)
frame #6: …
```
=> core: Fix crash when running dry

plugins/in_prometheus_scrape/prom_scrape.c
This PR will add a `User-Agent: Fluent-Bit` to the `in_prometheus_scrape` HTTP requests.
Fixes #8880
----
**Testing**
[valgrind.txt](https://github.com/fluent/fluent-bit/files/15456328/valgrind.txt)
---- …
=> in_prometheus_scrape: add User-Agent HTTP header (#8880)

tests/internal/log.c
Use milliseconds for calculating the timeout during log cache tests in an attempt to reduce the amount of false negatives (... and therefore the flakiness).
----
**Testing**
----
=> tests: internal: log: use milliseconds to do time comparisons for cache timeout.

tests/runtime/in_podman_metrics.c
re-apply #8844 to master.
----
**Testing**
----
=> tests/runtime/in_podman_metrics: refactor iteration of counters to use cfl_list from #8844.

plugins/out_cloudwatch_logs/cloudwatch_api.c, plugins/out_cloudwatch_logs/cloudwatch_logs.c, plugins/out_cloudwatch_logs/cloudwatch_logs.h
=> out_cloudwatch_logs: support log_group_class option

plugins/in_http/http_prot.c, tests/runtime/in_http.c
This request attempts to respond with error codes to requests that run into them for whatever reason, this includes:
- invalid formatting.
- write errors when persisting to disk.
- others scenarios that do not occur to me at the moment...
Any other error scenarios should also have tests added for them as both of the first ones have them.
Currently the `in_http` plugin makes no attempt to signal to the client if an error occurs while trying to ingest their records. This PR attempts to address that.
At the moment there is no attempt to actually report the error back to the client, or even to hint at its nature. A 400 error response is sent under any and all circumstances. This is in part to avoid leaking information the client as much as it is the lack of faculties to do so in fluent-bit. …
=> in_http: respond accordingly to requests that produce errors.

plugins/out_calyptia/calyptia.c
Moving the debug payload from info to debug level.
The output of this can result in half-way lines, which confuses the user.
<details><summary>Example 1</summary>
```text
[2024/05/07 21:11:41] [ warn] [output:calyptia:calyptia.2] http_status=422:
{"error":"zero metric values"}
[2024/05/07 21:11:41] [error] [output:calyptia:calyptia.2] could not deliver metrics
[2024/05/07 21:11:41] [ info] [output:calyptia:calyptia.2] debug payload:
2024-05-07T21:11:40.221389762Z fluentbit_uptime{pipeline_id="xxx",hostname="yyy"} = 5
...
2024-05-07T21:11:35.674983168Z fluentbit_output_retries_failed_total{pipeline_id="xxx",name="stdout.1"} = 0
2024-05-07T21:11:35.674983168Z fluentbit_output_dropped_records_total{pipeline_id="xxx",name="stdout.1"} = 0
2024-05-07T21:11:35.674983168Z …
```
=> out_calyptia: move debug payload to debug level.

tests/runtime/out_http.c
This PR simplifies the `in_http` test for `out_http`, designed to make sure the defaults work well together, to use a single fluent-bit context. This should hopefully make it work better on machines with higher occupancy.
This PR also improves the chances of success by using a try loop to detect when the output is finally flushed.
----
**Testing**
----
=> tests: rutime: out_http: simplify and make the in_http test more robust.

plugins/in_splunk/splunk_prot.c
When enabling HTTP2 and using raw HEC endpoint, I got a garbage character for Splunk HEC token.
This shouldn't be occurred and handled properly.
----
**Testing**
```console
$ bin/fluent-bit -i splunk -p port=8081 -o stdout -v
```
```console
$ bin/fluent-bit -i splunk -p port=8088 -o splunk -p port=8081 -psplunk_token=db496524-e7e6-4ae9-b3f0-2287d8e65cd4 -p "event_key=\$event" -f 1 -v
```
And sending a HEC event via curl:
```console
$ curl -k -XPOST "http://localhost:8088/services/collector/raw" \
-H "Authorization: Splunk db496524-e7e6-4ae9-b3f0-2287d8e65cd4" \
-d '{"event": "Hello, world!"}'
```
```log
Fluent Bit v3.0.7 …
```
=> in_splunk: Store HEC token on enabled HTTP2 and raw endpoints

plugins/in_splunk/splunk.c, plugins/in_splunk/splunk.h, plugins/in_splunk/splunk_config.c, plugins/in_splunk/splunk_prot.c, tests/runtime/in_splunk.c
In this enhancement, I implemented capabilities for storing metadata into records and handle multiple HEC tokens in configuration.
----
**Testing**
```ini
[INPUT]
Name splunk
Tag splunk.test.ingest
HTTP2 off
store_token_in_metadata off
Splunk_Token 7bba8847-4aee-4e62-ba7b-08c6139e42b9,4e63c0c9-c3b5-4a0a-bf4d-bfd5bc0d0070
[OUTPUT]
Name stdout
Match *
```
```ini
[INPUT]
Name splunk
Tag splunk.test.ingest
HTTP2 off
store_token_in_metadata on
Splunk_Token 7bba8847-4aee-4e62-ba7b-08c6139e42b9,4e63c0c9-c3b5-4a0a-bf4d-bfd5bc0d0070
[OUTPUT]
Name stdout
Match *
```
```log
Fluent Bit v3.0.7
* Fluent Bit …
```
=> in_splunk: Add switch for storing in metadata or records and handle multiple tokens on in splunk

plugins/in_kubernetes_events/kubernetes_events.c
Fixes a build error when building in_kubernetes_events caused by code that was not properly refactored. This is basically a reaplication of #8845 to master.
----
**Testing**
----
=> in_kubernetes_events: refactor time check to use struct flb_time.

plugins/in_kubernetes_events/kubernetes_events.c, src/tls/openssl.c
Fix two instances where the build fails with GCC 14.1 by adding explicit type casting.
Fixes #8858
----
**Testing**
- [N/A] Set `ok-package-test` label to test for all targets …
=> Fix GCC 14.1 build issues

plugins/in_systemd/systemd_config.c
On recent versions of systemd, `read_from_tail()` doesn't work as expected unless followed with a call to `sd_journal_previous()`.
This can be tested with: `fluent-bit -i systemd -p read_from_tail=On -o stdout`
The command works on:
- Ubuntu 22.10 with systemd 251 (251.4-1ubuntu7.3)
- Yocto mickledore with systemd 253 (253.1)
But it doesn't work on:
- Ubuntu 24.04 with systemd 255 (255.4-1ubuntu8.1)
- Yocto nanbield with systemd 254 (254.4)
The following short program can also be used to test this (uncomment the line that calls sd_journal_previous() to see the difference):
```C
#include <systemd/sd-journal.h>
int main(void) {
sd_journal *j;
int ret;
sd_journal_open(&j, SD_JOURNAL_LOCAL_ONLY);
sd_journal_seek_tail(j);
//sd_journal_previous(j);
for …
```
=> in_systemd: Move one record back after skipping to the end

src/http_server/api/v1/trace.c
Fix two bugs with name matching for inputs when enabling chunk traces via the http_server API:
- false positive with short names.
- matching for plugin aliases.
This fixes https://github.com/fluent/fluent-bit/issues/8885.
----
**Testing**
----
=> http_server: api: v1: traces: fix finding inputs by alias.

plugins/in_winevtlog/in_winevtlog.c
This pull request addresses a **conditioning error** in the **in_winevtlog.c** file. 
Currently, even if the **highest allowed value (1843200)** is set for the **read_limit_per_cycle** parameter in the configuration file, an unnecessary warning **(read limit per cycle cannot exceed)** message is still shown **without exceeding the maximum threshold size.**
**MAXIMUM_THRESHOLD_SIZE =1843200**.
issue (#8783)
- Warning log
`[2024/04/23 19:33:02] [ warn] [input:winevtlog:winevtlog.0] read limit per cycle cannot exceed 1.8M. Set up to 1.8M`
This fix ensures that when the maximum value is set, the warning message is skipped, making the behavior more consistent and clear.
----
**Testing**
Before we can approve your change; …
=> in_winevtlog: Fix threshold condition to avoid unnecessary warning

dockerfiles/Dockerfile
Update to Debian `bookworm` as the base for the container images.
Increments to `libssl3`, `libldap-2.5` and `libffi8` as part of this. Also added `libcap2` to prevent runtime linkage problems.
----
**Testing**
CI covers build and run sanity check.
----
=> dockerfile: update to bookworm base image

plugins/processor_metrics_selector/selector.c, plugins/processor_metrics_selector/selector.h, tests/runtime/processor_metrics_selector.c
In this PR, I implemented a context of delete_label_value operation.
----
**Testing**
```yaml
service:
flush: 2
daemon: off
log_level:  debug
pipeline:
inputs:
- name: fluentbit_metrics
tag: fluentbit.metrics
scrape_interval: 2
processors:
metrics:
- name: metrics_selector
context: delete_label_value
label: name stdout.0
outputs:
- name: stdout
match: '*'
```
```log
Fluent Bit v3.0.4
\_   _____/|  |  __ __   ____   _____/  |_ …
```
=> processor_metrics_selector: Implement delete by label value operation

dockerfiles/Dockerfile.windows
=> dockerfiles: windows: Update to use vcpkg instead of chocolatey

plugins/out_opentelemetry/opentelemetry_logs.c
=> out_opentelemetry: fix handling of multiple scopes

src/tls/openssl.c
Closes #8072
As mentioned in the TLS hostname issue ticket, this issue will be reproduced easily.
After applied this patch, Fluent Bit will deny to connect inappropriate server name against for the certificates' data.
----
**Testing**
As mentioned in https://github.com/fluent/fluent-bit/issues/8072
After applied this patch, Fluent Bit does safely disconnect from the not matched vhost.
```log
Fluent Bit v3.1.0
\_   _____/|  |  __ …
```
=> tls: Verify vhost when tls.verify is enabled

.github/workflows/staging-release.yaml
No longer depend on AppVeyor builds completing for a release and no longer provide them officially.
Github built binaries are the recommended version for a while and the docs reflect this.
AppVeyor binaries are inconsistent with missing YAML support, etc.
----
**Testing**
----
=> workflows: remove AppVeyor from release workflow

lib/monkey/examples/list.c, lib/monkey/examples/quiz.c, lib/monkey/include/monkey/mk_api.h, lib/monkey/include/monkey/monkey.h, lib/monkey/monkey.spec, lib/monkey/qa/checklog
=> lib: monkey: upgrade to v1.7.5

plugins/in_opentelemetry/opentelemetry_prot.c
Pass on tag with length so that tag_from_uri get applied on OpenTelemetry input plugin
Fixes #8734 
----
**Testing**
```
service:
flush: 1
log_file: /tmp/fluent-bit.log
daemon: false
pipeline:
inputs:
- name: opentelemetry
listen: 127.0.0.1
port: 9999
raw_traces: false
successful_response_code: 200
tag_from_uri: true
http2: false
outputs:
- name: stdout
match: "v1_traces"
```
```
[2024/05/27 14:58:22] [ info] [fluent bit] version=3.0.7, commit=dffcd42ada, pid=1820178
[2024/05/27 14:58:22] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2024/05/27 14:58:22] [ info] [storage] ver=1.5.2, type=memory, sync=normal, …
```
=> in_opentelemetry: attempt to fix tag_from_uri

src/flb_help.c
Before this commit, fluent-bit -J produces the incorrect schema for listen address for ip.
host should be used for specifing to hostname.
And, listen parameter should be used for setting up for listen address.
This is because the following lines in flb_input.c:
```c
else if (prop_key_check("listen", k, len) == 0) {
flb_utils_set_plugin_string_property("listen", &ins->host.listen, tmp);
}
else if (prop_key_check("host", k, len) == 0) {
flb_utils_set_plugin_string_property("host", &ins->host.name, tmp);
}
```
Set up for listen address and hostname respectively. And the host member is typed as struct flb_net_host whose definition is:
```c
struct flb_input_instance {
/* snip */
/*
* Input network info:
*
* An input plugin can be specified just using it shortname or using the
* complete …
```
=> help: input: Handle listen to be a parameter for setting up listen address

plugins/in_opentelemetry/opentelemetry_prot.c
It's replying with `400 Forbidden`; it should be `400 Bad Request`
----
=> in_opentelemetry: opentelemetry_prot: Fix string in http response code 400

plugins/in_prometheus_remote_write/prom_rw_prot.c
It's replying with `400 Forbidden`; it should be `400 Bad Request`
----
=> in_prometheus_remote_write: prom_rw_prot: Fix string in http response code 400

plugins/in_winevtlog/pack.c
Only extracting the SID when is used for normal data cases. For string inserts, we needn't replace with the actual data because replacing with actual user account's domain and its name causes breaking the relationship of corresponding string interpolated message and the element of string inserts.
----
**Testing**
----
=> in_winevtlog: Retrieve actual user account's domain and name

plugins/in_splunk/splunk_prot.c
It's replying with `400 Forbidden`; it should be `400 Bad Request`
----
=> in_splunk: splunk_prot: Fix string in http response code 400.

plugins/in_winevtlog/winevtlog.c
When subscribing Forwarded events channels such as ForwardedEvents channel, PublisherMetadata could be absent.
This is the side note for this phenomenon:
> [in] PublisherMetadata
> A handle to the provider's metadata that the [EvtOpenPublisherMetadata](https://learn.microsoft.com/en-us/windows/desktop/api/winevt/nf-winevt-evtopenpublishermetadata) function returns. The handle acts as a formatting context for the event or message identifier.
> You can set this parameter to NULL if the Windows Event Collector service forwarded the event. Forwarded events include a RenderingInfo section that contains the rendered message strings.
ref: https://learn.microsoft.com/en-us/windows/win32/api/winevt/nf-winevt-evtformatmessage
So, FormatEventMessage function should handle NULL in case of …
=> in_winevtlog: Permit absence of publisher metadata

plugins/in_docker/cgroup_v2.c
This PR fixes a memory leak that would occur after a conversion error.  This leak is not very likely to occur in production but nevertheless should be fixed. The issue was found using the gcc static analyzer (compiler option `-fanalyzer`).
----
**Testing** …
=> in_docker: fix memory leak caused by conversion error

include/fluent-bit/flb_input.h, include/fluent-bit/flb_output.h, include/fluent-bit/tls/flb_tls.h, plugins/filter_kubernetes/kube_conf.h, plugins/filter_kubernetes/kube_meta.c, plugins/filter_kubernetes/kubernetes.c, src/flb_input.c, src/flb_output.c, src/tls/flb_tls.c, src/tls/openssl.c
This is backporting PR for https://github.com/fluent/fluent-bit/pull/8966.
----
**Testing**
----
=> tls: input: output: Provide restoring way for tls.verify hebavior [Backport 3.0]

cmake/plugins_options.cmake, plugins/CMakeLists.txt, plugins/out_opentelemetry/opentelemetry_logs.c, plugins/processor_opentelemetry_envelope/CMakeLists.txt, plugins/processor_opentelemetry_envelope/otel_envelope.c, src/flb_mp.c, src/flb_pack.c
When collecting data from all plugins except in_opentelemetry, the records comes with  basic timestamp, metadata and content; there are cases where this information collected needs to send to be send an OpenTelemetry endpoint (vendor or another OTel compatible endpoint) and packaging with proper OTel Log Resources and Scopes simplify the data transformation.
This processor creates the internal group with OTel basic structure. Note that this creates the envelope, for further processing can be used in conjunction with content modifier processor.
usage example:
```yaml
pipeline:
inputs:
- name: dummy
samples: 1
processors:
logs:
- name: opentelemetry_envelope
context: otel_resource_attributes
action: upsert
key: "aaa"
value: "bbb"
outputs:
- name : stdout
match: '*' …
```
=> processor_opentelemetry_envelope: new processor to package non OTel Logs content as OTel

plugins/in_winevtlog/pack.c
This is backporting PR which is corresponding to https://github.com/fluent/fluent-bit/pull/8992.
----
**Testing**
----
=> in_winevtlog: Retrieve actual user account's domain and name [Backport to 3.0]

plugins/in_opentelemetry/opentelemetry_prot.c
=> in_opentelemetry: handle missing or invalid content-type headers in metrics and traces handlers

plugins/out_loki/loki.c, plugins/out_loki/loki.h, tests/runtime/out_loki.c
This patch adds a third value to `drop_single_key` - `raw`, which allows sending unquoted strings to Loki when using JSON as the `line_format`.
While yes, for the output to be valid JSON, quotes would be expected, Loki does not support reading a plain quoted string with its JSON parser, complaining that it cannot find a `}` character. Instead, you need to use a combination of regexp and line_format expressions to unquote the log before running any other parsers over it.
By adding a third value of `raw`, this ensures backwards compatibility for anyone that is already relying on the existing behaviour.
An example query before this change for plaintext logs, to remove the quotes:
```
{"job"="fluent-bit"} | regexp `^"?(?S<log>.*?)"?$` | line_format "{{.log}}"
```
This is necessary to add …
=> out_loki: allow sending unquoted strings

include/fluent-bit/flb_parser.h, plugins/in_kubernetes_events/kubernetes_events.c, src/flb_parser.c, src/flb_parser_json.c, src/flb_parser_logfmt.c, src/flb_parser_ltsv.c, src/flb_parser_regex.c, src/multiline/flb_ml_parser_cri.c, src/multiline/flb_ml_parser_docker.c, tests/internal/fuzzers/engine_fuzzer.c, tests/internal/fuzzers/parse_json_fuzzer.c, tests/internal/fuzzers/parse_logfmt_fuzzer.c, tests/internal/fuzzers/parse_ltsv_fuzzer.c, tests/internal/fuzzers/parser_fuzzer.c, tests/internal/parser.c, tests/internal/parser_json.c, tests/internal/parser_logfmt.c, tests/internal/parser_ltsv.c, tests/internal/parser_regex.c, tests/runtime/filter_parser.c
This is the same PR #8164 with the only difference that commits has been split per interface. All commits honor the original author.
----
=> parser: add new option time_system_timezone (copy of #8164)

plugins/processor_content_modifier/cm_logs.c
=> processor_content_modifier: logs: do not fail if keys are not found

plugins/out_datadog/datadog.c, plugins/out_datadog/datadog.h
This PR adds support for setting a static hostname in the Datadog output plugin. This field is analogous to the existing `dd_service` and `dd_source` configuration options that can be used to set a static value.
If unset, the default behavior is backwards compatible. This behavior is to not set an explicity `hostname` field, but if the record has a field that is detected as the hostname in Datadog (such as `host` or `syslog.hostname`), it will be picked up.
Closes: #8971
----
**Testing**
----
Fluent …
=> out_datadog: Add support for setting a static hostname

plugins/in_opentelemetry/opentelemetry_prot.c
Updates to the OpenTelemetry input plugin's HTTP/2 server code to handle/report error cases better.
These were changes I made as part of other work trying to fix #8734 - but I have split them out into a separate PR as I can imagine they may need to be reviewed separately. 
----
**Testing requirements**
```
service:
pipeline:
inputs:
- name: opentelemetry
tag_from_uri: true
http2: true
outputs:
- name: 'stdout'
match: '*'
```
----
=> Improved OpenTelemetry OTLP error handling

include/fluent-bit/flb_input.h, include/fluent-bit/flb_output.h, include/fluent-bit/tls/flb_tls.h, plugins/filter_kubernetes/kube_conf.h, plugins/filter_kubernetes/kube_meta.c, plugins/filter_kubernetes/kubernetes.c, src/flb_input.c, src/flb_output.c, src/tls/flb_tls.c, src/tls/openssl.c
Closes https://github.com/fluent/fluent-bit/issues/8959.
The previous enforced hostname verification with tls.verify breaks some of the certificates
for kubelet. We should restore functionality and make opt-in feature for hostname verification in TLS.
----
**Testing**
Same as in https://github.com/fluent/fluent-bit/issues/8072. But it needs to add `tls.verify_hostname on` for hostname verification.
https://github.com/fluent/fluent-bit-docs/pull/1393
---- …
=> tls: input: output: Provide restoring way for tls.verify hebavior

src/flb_utils.c, tests/internal/utils.c
This PR addresses an issue, which is that the **flb_utils_size_to_bytes** function is only processing non-floating numbers even after providing a floating-number in configuration.
It would address one aspect of the performance issues (Ref: https://github.com/fluent/fluent-bit/issues/8673)
----
- Consider a case where the **input plugin** is **winevtlog** and the **output plugin** is **stdout**.
1. If **read_limit_per_cycle** is set to **1.8 M**,
- Configuration file for the above scenario 
```
[SERVICE]
flush        1
log_level    debug
parsers_file parsers.conf
plugins_file plugins.con
http_server  Off
http_listen  0.0.0.0
http_port    2020
[INPUT]
Name         winevtlog
Channels     Setup,Windows PowerShell
Interval_Sec 60
read_existing_events true …
```
=> utils: floating-point number support in size-to-bytes conversion

conf/parsers.conf
Adds a parser for Linux kernel netfilter firewall log messages. Applying this parser on the /var/log/kern.log will extract firewall logs
**Testing**
```
pipeline:
inputs:
- name: tail
tag: firewall
path: /var/log/kern.log
parser: kmsg-netfilter-log
outputs:
- name: stdout
```
=> Added parser for Linux kernel netfilter firewall log

.github/workflows/staging-release.yaml
=> workflows: update for 3.1 release

include/fluent-bit/flb_metrics.h, src/flb_metrics.c
However, still aded limitations over 1024 characters to prevent a waste of memory consumptions for title names.
Closes https://github.com/fluent/fluent-bit/issues/8938
----
**Testing**
```console
$ fluent-bit -i fluentbit_metrics -o stdout -v
```
```log
Fluent Bit v3.1.0
\_   _____/|  |  __ __   ____   _____/  |_  \______   \__|/  |_  ___  _\_____  \ 
|    __)  |  | |  |  \_/ __ \ /    \   __\  |    |  _/  \   __\ \  \/ / _(__ …
```
=> metrics: Allocate metrics' titles dynamically

plugins/in_winevtlog/pack.c, plugins/in_winevtlog/winevtlog.c
In the previous implementation, I didn't fully considered for buffer allocation error and not mapped error.
This PR intended to handle them correctly.
----
**Testing**
----
=> in_winetvlog: Handle buffer allocation error and not mapped error

plugins/out_splunk/splunk.c, plugins/out_splunk/splunk.h
Fixes #8927. This does **not** remove the ability to send raw events, i.e. using `Splunk_Send_Raw On`, but rather sends them to correct endpoint.
----
**Testing**
- [N/A] Set …
=> out_splunk: remove raw endpoint

src/flb_http_common.c
When a client uses HTTP/1.1 protocol version, we are only setting the content-length at special cases, however if the caller like in_splunk, in_http or other sets a response body, the header is not set, so the client "have to assume" the response of the request is either none or just hangs and wait for some bytes.
This patch forces to format a content-length header when the request comes from a HTTP/1.1 session
This fixes the  issue #9010.
----
=> http_server: always set the content-length on HTTP/1.x (fix #9010)

include/fluent-bit/flb_downstream.h, src/flb_downstream.c, src/http_server/flb_http_server.c
This PR is still work in progress. As of now keepalive issues are fixed, however we are waiting for some unit tests to validate proper behaviors on:
- in_http
- in_splunk
- in_elasticsearch
- ...
----
=> http_server and downstream: fix keepalive issues

src/tls/openssl.c
=> tls: openssl: fix handling of noisy non TLS errors

lib/nghttp2/lib/includes/nghttp2/nghttp2.h, lib/nghttp2/lib/nghttp2_helper.c, lib/nghttp2/lib/nghttp2_session.c, lib/nghttp2/lib/nghttp2_session.h
Before v3.1 release, we wanted to upgrade to Nghttp2 version 1.62, however, we found some build issues on Windows and the [issue has been reported](https://github.com/nghttp2/nghttp2/issues/2219). In the meanwhile upstream fixes the build process, this PR backports a security fix that was available in recent versions:
00201ecd [PATCH] Limit CONTINUATION frames following an incoming HEADER frame
https://github.com/nghttp2/nghttp2/security/advisories/GHSA-x6x3-gv8h-m57q
----
=> lib: nghttp2: backport upstream security fix

plugins/out_gelf/gelf.c, plugins/out_gelf/gelf.h, tests/internal/gelf.c
To align the behavior of Fluentd side of gelf plugin, we need to implement a capability to inject tag information to gelf records if available.
Closes https://github.com/fluent/fluent-bit/issues/8921
----
**Testing**
```console
$ bin/fluent-bit -i dummy -pdummy='{"message":"dummy","send":"from fluent-bit"}' -o gelf -p port=12202 -pgelf_short_message_key=message -v
```
```
$ bin/fluent-bit -i dummy -pdummy='{"message":"dummy","send":"from fluent-bit"}' -o gelf -p port=12202 -pgelf_short_message_key=message -pgelf_tag_key=tag -v
```
```log
Fluent Bit v3.1.0
* Fluent Bit is a CNCF sub-project under …
```
=> out_gelf: test: Implement injecting tag capability

plugins/out_loki/loki.c, plugins/out_loki/loki.h
This PR adds support for [structured metadata](https://grafana.com/docs/loki/latest/get-started/labels/structured-metadata/) in the loki output.  As of Loki 3.0, structured metadata has been made GA.  
Implementation wise, labels and structured metadata are very similar: both are key/value pairs, and both support record accessors, consequently this PR does some light refactoring to avoid nontrivial code duplication between labels and structured metadata.
This PR only implements the analog of the `labels` config parameter, which is called `structured_metadata`.  Analogs for `label_keys` and `label_map_path` were not implemented to keep the change both simple and immediately useful, though they could be added later. 
Fixes #8080.
Because the code paths are slightly different when labels …
=> out_loki: add support for structured metadata

src/http_server/flb_http_server.c
HTTP/2 always requests to enable keepalive.
Also, handling for protocol version of HTTP/2 is inverted. So, I also fixed this conditional clause.
----
**Testing**
----
=> http_server: Don't override keepalive for HTTP/2

include/fluent-bit/flb_config_map.h, include/fluent-bit/flb_processor.h, src/config_format/flb_cf_yaml.c, src/flb_config_map.c, src/flb_processor.c
This was initially based on
https://github.com/fluent/fluent-bit/pull/8656 and https://github.com/fluent/fluent-bit/pull/8661 but ended up making few different choices:
- Instead of adding FLB_CONFIG_MAP_KVLIST and FLB_CONFIG_MAP_ARRAY as config map types, it adds a single FLB_CONFIG_MAP_VARIANT which accepts an array or map. The passed array/map can have nested values and accept any JSON/YAML types, which are converted to cfl types. The processor will simply receive a `cfl_variant` pointer and is responsible for releasing the memory later.
- The existing `flb_config_map_set` function is reused by passing the `cfl_variant` pointer (from the yaml parsing phase) as the value of a `flb_kv`. Then pointer is eventually moved into the processor context.
I have added an example processor which …
=> config_format: yaml: Support passing arbitrary objects to processors

plugins/in_syslog/syslog_conf.c
When running syslog example:
`bin/fluent-bit -i syslog -o stdout -f 1`
if no parser is set we get a double-free:
```
[2024/06/18 15:36:32] [ info] [fluent bit] version=3.1.0, commit=2bef95819e, pid=144050
[2024/06/18 15:36:32] [ info] [storage] ver=1.5.2, type=memory, sync=normal, checksum=off, m  ax_chunks_up=128
[2024/06/18 15:36:32] [ info] [cmetrics] version=0.9.1
[2024/06/18 15:36:32] [ info] [ctraces ] version=0.5.1
free(): double free detected in tcache 2
[2024/06/18 15:36:32] [ info] [input:syslog:syslog.0] initializing
zsh: IOT instruction  bin/fluent-bit -i syslog -o stdout -f 1
```
Remove the redundent flb_log_event_encoder_destroy, since that is already done in syslog_conf_destroy.
----
**Testing**
Before …
=> in_syslog: Fix double free when no parser is set

plugins/out_http/http.c
Fix a problem that http output plugin retries all requests that respond with an 4xx status code excepting 429 status code
Fixes #8860
----
**Testing**
- [N/A] …
=> out_http: don't retry non retryable 4xx status codes

plugins/out_loki/loki.c, plugins/out_loki/loki.h
Adds http_buffer_max_size option, default is 512K now. Purges the upstream connection in case of HTTP 5xx errors.
----
**Testing** …
=> out_loki: Add http_buffer_max_size option and handle HTTP 5xx errors

lib/luajit-cmake/LuaJIT.cmake
Thanks @xl-sec!!!
Closes https://github.com/fluent/fluent-bit/issues/9062.
----
**Testing**
----
=> luajit-cmake: Add git repository existence check

packaging/centos7-repo.sh, packaging/test-release-packages.sh
=> packaing: test: centos7: Fix packaging test

CMakeLists.txt
If git is configured to show the signature in `git log` then the extraction of the commit hash breaks. So instead call `git log` with the `-c log.showSignature=false` config options.
Fixes #9064
----
**Testing** …
=> cmake: Correctly fetch FLB_GIT_HASH from signed commit

plugins/out_opentelemetry/opentelemetry_logs.c
When the log records comes as raw, meaning non-otel schema, the user can specify through the configuration how to extract different fields from the main message body such as:
- traceId
- spanId
- traceFlags
- severityText
- severityNumber
This PR fix the manual parsing that got broken after the refactor.
This fixes issue #9071
----
=> out_opentelemetry: restore manual parsing for log record fields (fix #9071)

plugins/filter_log_to_metrics/log_to_metrics.c, plugins/filter_log_to_metrics/log_to_metrics.h, tests/runtime/filter_log_to_metrics.c
This PR will add functionality to set emitter alias and mem buf limit. The default mem buf limit is 10MB.
Needs https://github.com/fluent/fluent-bit/pull/8473 to be applied before taking effect.
(**EDIT** PR is merged)
----
**Testing**
- [N/A] Set `ok-package-test` label to test for all targets (requires maintainer to …
=> filter_log_to_metric: Add emitter alias and mem buf limit

src/flb_input.c
This PR fixes a dependency issue for the `storage.pause_on_chunks_overlimit` parameter.
In case the order in the config file was
```
storage.pause_on_chunks_overlimit On
storage.type Filesystem
```
then the `storage.pause_on_chunks_overlimit` was ignored.
This PR changes this behavior, so that the `storage.pause_on_chunks_overlimit` parameter will be parsed and set. It will be reset in case the `storage.type` is set to a different type than FS later.
----
**Testing**
- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was …
=> flb_input: Config parsing order fixed for storage.pause_on_chunks_overlimit

plugins/in_forward/fw.c, plugins/in_forward/fw.h
This PR adds pause functionality for forward input plugin.
----
**Testing**
----
Fluent Bit is licensed …
=> in_forward: Add plugin pause/resume mechanism

plugins/out_datadog/datadog.c, plugins/out_datadog/datadog.h
Fixes #8982.
This patch fixes the code to honor the documented behavior: If the 'dd_message_key' config option is not supplied, the 'log' key in the record will now be remapped to the datadog equivalent.
----
**Testing**
- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all …
=> out_datadog: fix default message key remapping

include/fluent-bit/flb_metrics.h, src/flb_metrics.c, src/flb_metrics_exporter.c
=> metrics: fix handling of old metric names (fix #9086)

lib/ctraces/CMakeLists.txt, lib/ctraces/include/ctraces/ctr_variant_utils.h
=> lib: ctraces: upgrade to v0.5.2

plugins/in_splunk/splunk.h, plugins/in_splunk/splunk_config.c, plugins/in_splunk/splunk_prot.c
We should process struct checking for credentials.
Adding length comparisons would be better to proceed the credential authentication.
Plus, spaces around commas will be trimmed. So, the attached configurations are valid even if including spaces around the comma.
----
**Testing**
```ini
[INPUT]
Name splunk
Tag splunk.test.ingest
Port 8090
Splunk_Token 7bba8847-4aee-4e62-ba7b-08c6139e42b9 , 4e63c0c9-c3b5-4a0a-bf4d-bfd5bc0d0070
store_token_in_metadata Off
Buffer_Max_Size 10M
http2 Off
tls On
tls.verify Off
tls.crt_file ./cert/ca_cert.pem
tls.key_file ./cert/ca_key.pem
tls.key_passwd fluentd
[OUTPUT]
Name stdout
Match *
```
Or,
```
[INPUT]
Name …
```
=> in_splunk: Process strict check for credentials

plugins/in_splunk/splunk_prot.c
Don't respond twice for Content-Type is not set.
Also, Splunk's official documentation does not mention to set `Content-Type: application/json` or `Content-Type: text/plain`.
So, we need to pass-through the request which don't use `Content-Type` header. 
----
**Testing**
----
=> in_splunk: Fix handlings for content type when http2 is off

plugins/out_stdout/stdout.c
Like as ctraces events, there is possibilities to have multiple concatenated cmetrics buffers case.
For instance, calling flb_input_metrics_append more than one per a cycle, msgpack payload of cmetrics have multiply concatenated contexts of cmetrics.
----
**Testing**
----
=> out_stdout: Consume entire metrics type of buffers

plugins/filter_log_to_metrics/log_to_metrics.c, plugins/filter_log_to_metrics/log_to_metrics.h, tests/runtime/filter_log_to_metrics.c
This PR allows to change namespace and subsystem for log_to_metrics. 
----
**Testing**
```
[SERVICE]
Flush     1
Daemon    off
Log_Level info
[INPUT]
Name               dummy
Dummy              {"message":"dummy", "kubernetes":{"namespace_name": "default", "docker_id": "abc123", "pod_name": "pod1", "container_name": "mycontainer", "pod_id": "def456", "labels":{"app": "app1"}}, "duration": 20, "color": "red", "shape": "circle"}
Tag                dummy.log
Interval_sec               10
[FILTER]
name               log_to_metrics
match              dummy.log*
tag                test_metric
metric_mode        counter
metric_name        count_all_dummy_messages
metric_description This metric counts dummy messages …
```
=> log_to_metrics: allow custom namespace and subsystem

plugins/out_s3/s3.c
Almost fixing for https://github.com/fluent/fluent-bit/issues/9093.
From the issue, the following valgrind log:
```
==8530== 110,926,948 bytes in 21 blocks are definitely lost in loss record 46 of 47
==8530==    at 0x4C39185: malloc (vg_replace_malloc.c:442)
==8530==    by 0xF0898D: cio_file_content_copy (in /opt/fluent-bit/code/fluent-bit/bin/fluent-bit)
==8530==    by 0xF05568: cio_chunk_get_content_copy (in /opt/fluent-bit/code/fluent-bit/bin/fluent-bit)
==8530==    by 0xB82CE3: flb_fstore_file_content_copy (in /opt/fluent-bit/code/fluent-bit/bin/fluent-bit)
==8530==    by 0xA7F976: s3_store_file_read (in /opt/fluent-bit/code/fluent-bit/bin/fluent-bit)
==8530==    by 0xA76D08: construct_request_buffer (in /opt/fluent-bit/code/fluent-bit/bin/fluent-bit)
==8530==    by 0xA7688B: …
```
=> out_s3: Plug memory leaks on gzipped buffers during the swapping contents

dockerfiles/Dockerfile.centos7, packaging/distros/centos/Dockerfile
epel-release is already included in Extra repo on CentOS 7.
----
**Testing**
----
=> workflows: Fix CentOS7 build failure for EPEL

plugins/filter_log_to_metrics/log_to_metrics.c, plugins/filter_log_to_metrics/log_to_metrics.h
[updated]
By default, the filter don't drop the logs from the pipeline, there are cases where only metrics are desired to reduce log volume.
This patch introduces a new option called `discard_logs` (default: false) which when enabled will discard the logs once they are processed.
usage:
```yaml
service:
pipeline:
inputs:
- name: dummy
tag: dummy.log
dummy: '{"message":"dummy", "kubernetes":{"namespace_name": "default", "docker_id":
"abc123", "pod_name": "pod1", "container_name": "mycontainer", "pod_id": "def456"},
"duration": 20, "color": "red", "shape": "circle"}'
processors:
logs:
- name: log_to_metrics
tag: test_metric
metric_name: count_all_dummy_messages
metric_mode: counter
metric_description: This metric counts dummy messages
discard_logs: true
outputs:
- name: …
```
=> filter_log_to_metrics: add new option 'discard_logs'

plugins/in_node_exporter_metrics/ne_systemd_linux.c
In the original node_exporter, it only uses 0 or 1 which means that this status is active or not.
To represent this specification on Fluent Bit, we need to fill as 0 at first. Then, we need filling with 1 for the active statuses.
----
**Testing**
```
$bin/fluent-bit -i node_exporter_metrics -o stdout -v
```
```
==3791369== 
==3791369== HEAP SUMMARY:
==3791369==     in use at exit: 0 bytes in 0 blocks
==3791369==   total heap usage: 228,729 allocs, 228,729 frees, 13,302,851,339 bytes allocated
==3791369== 
==3791369== All heap blocks were freed -- no leaks are possible
==3791369== 
==3791369== For lists of detected and suppressed errors, rerun …
```
=> node_exporter_metrics: Align the collecting metrics of unit statuses

include/fluent-bit/flb_gzip.h, plugins/in_forward/fw_prot.c, src/flb_gzip.c, tests/internal/gzip.c
Using for concatenated gzip conformation with magic bytes, compression method and OS flags.
* 0x1f & 0x8b
* 8 (deflate)
* skip 7 bytes
* OS flags <--- Added in this PR
Follows up for https://github.com/fluent/fluent-bit/pull/8665.
----
**Testing**
----
=> in_forward: Use full width of gzip header for checking whether concatenated or not

.github/workflows/cron-unstable-build.yaml
Updating nightly builds to just be `master` and `3.0`.
The others fail.
----
**Testing**
----
=> workflows: update unstable nightly builds for 3.0

plugins/in_mqtt/mqtt.c, plugins/in_mqtt/mqtt.h, plugins/in_mqtt/mqtt_conn.c, plugins/in_mqtt/mqtt_conn.h, plugins/in_mqtt/mqtt_prot.c
This PR adds an optional setting to the MQTT input plugin named `buffer_size` which sets the maximum message size.
According to the MQTT standard the protocol can handle messages of up to 256 megabytes, however, to keep the default memory footprint low, the default value has been raised to 2048 bytes (from 1024 bytes).
Additionally, this PR fixes a leak in the protocol handler which triggered when a message did not contain a valid JSON payload.
=> in_mqtt: added buffer size setting and fixed a leak

src/aws/flb_aws_util.c
This PR fixes leading zeros in time_key strings.
The kinesis_datastream/kinesis_firehose ouput plugin can add timestamps by specifying the time_key/time_key_format parameters.
Format qualifiers include `%3N` for milliseconds and `%9N` / `%L` for nanoseconds.
In the current implementation, the number of digits in the timestamp is insufficient when milliseconds are smaller than 100 ms (e.g., `0xx` / `00x` ) or nanoseconds are smaller than 100 ms (e.g., `0xxxxxxxxxxx` / `00xxxxxxxxx` ).
Therefore, the number of digits has been corrected to be correct.
This fix was opened by @PettitWesley in https://github.com/fluent/fluent-bit/pull/8116, but there have been no changes for about 6 months, and I was troubled that this problem was not resolved.
Therefore, I created a new Pull request.
- Fixes …
=> aws_util: fix leading zeros in time_key strings

plugins/out_opensearch/opensearch.c
This PR fixes a bug in the opensearch output plugin where it incorrectly ignores the encoded payload buffer for traces.
=> out_opensearch: fixed wrong payload buffer usage for traces

.github/workflows/pr-compile-check.yaml, CMakeLists.txt, cmake/headers.cmake, cmake/luajit.cmake, src/CMakeLists.txt
e.g. buildroot has logic to build luajit,
so if pkg_check_modules can find a suitable version, then use that one
----
**Testing**
- [N/A] Documentation required for …
=> build: use the system provided LuaJIT if found

plugins/out_prometheus_exporter/prom.c
Like as ctraces, there is a possibility to handle concatenated metrics type of events payloads during processing #9119.
This is because in_statsd of metrics ingestion mode requests to handle cmetrics payloads which is ingested events more one times per a cycle.
Currently, we need to handle manually for multiply concatenated cmetrics payloads to handle multiple ingestion for metrics type of events.
----
**Testing**
```
$ bin/fluent-bit -i fluentbit_metrics -o prometheus_exporter -v
```
```log
______ _ …
```
=> out_prometheus_exporter: Handle multiply concatenated metrics type of events

plugins/in_emitter/emitter.c, plugins/in_forward/fw_conn.c, plugins/in_forward/fw_prot.c, plugins/in_tail/tail_file.c, plugins/out_kafka/kafka.c, plugins/out_stackdriver/stackdriver.c
=> core: fixes for issues reported by Coverity

include/fluent-bit/wasm/flb_wasm.h, plugins/filter_wasm/filter_wasm.c, plugins/filter_wasm/filter_wasm.h, plugins/in_exec_wasi/in_exec_wasi.c, plugins/in_exec_wasi/in_exec_wasi.h, src/wasm/flb_wasm.c
Currently, heap and stack sizes for Wasm is fixed and not configurable.
This PR indented to make them configurable.
----
**Testing**
```ini
Flush        1
Hot_Reload   On
Grace 5
[INPUT]
Name dummy
Tag dummy.locals
Dummy {"message":"dummy","wasm_float1":1.0,"wasm_float2":100.0,"wasm_int1":1,"wasm_int2":100}
[FILTER]
Name wasm
WASM_Path rust_clib_filter.aot
Function_Name rust_clib_filter
accessible_paths .
[OUTPUT]
Name  stdout
Match *
```
```ini
[SERVICE]
Flush        1
HTTP_Port …
```
=> wasm: in_exec_wasi: filter_wasm: Make configurable for wasm heap and stack sizes

CMakeLists.txt, include/fluent-bit/flb_compat.h, include/fluent-bit/flb_endian.h, src/flb_log_event_decoder.c
This PR adds a new feature flag named `FLB_ENFORCE_ALIGNMENT` which can be used to ensure that when decoding the timestamp field from a record fluent-bit ensures that the memory access operation is aligned which is not the case normally due to how the msgpack wire protocol packs `ext` types.
While it's clear that exchanging one read operation for seven reads and a few more writes is undesirable to say the least, this  is the only way I found to ensure that the output machine code was not tampered with in any of the compiler and architecture combinations.
There are two alternative implementations for this function using either two individual `DWORD` reads : 
```
uint32_t __attribute__((optimize("-O0"))) FLB_ALIGNED_DWORD_READ(char *source) {
uintptr_t      alignment_offset;
unsigned char …
```
=> core: memory alignment feature addition

src/flb_pack.c
In `flb_msgpack_raw_to_json_sds`, when the buffer is reallocated it calls `flb_sds_increase`. This increases the length by adding the `len` argument to the length and reallocating the sds object. After doing this, the `out_size` is multiplied by `realloc_size`. This does not match reality, as what happened in the reallocation was additive not multiplicative. This commit corrects the inconsistency.
Fixes #9192.
Fixes #8993.
----
**Testing**
----
Fluent Bit is licensed under Apache 2.0, by submitting …
=> pack: do not multiply out_size by realloc_size

plugins/out_stackdriver/stackdriver.c, plugins/out_stackdriver/stackdriver.h, plugins/out_stackdriver/stackdriver_conf.c
Add metric to measure the round trip latency for write entries HTTP request to Cloud Logging.
This is an observability improvement.
----
**Testing**
New metric is exposed to v2 metrics endpoint.
```
curl -s http://127.0.0.1:2020/api/v2/metrics/prometheus
fluentbit_stackdriver_write_entries_latency_bucket{le="1.0",name="stackdriver-cp-v3-container"} 2326
fluentbit_stackdriver_write_entries_latency_bucket{le="2.0",name="stackdriver-cp-v3-container"} 2329
fluentbit_stackdriver_write_entries_latency_bucket{le="4.0",name="stackdriver-cp-v3-container"} 2329
fluentbit_stackdriver_write_entries_latency_bucket{le="8.0",name="stackdriver-cp-v3-container"} 2329
fluentbit_stackdriver_write_entries_latency_bucket{le="16.0",name="sta …
```
=> stackdriver: Add latency metric for write log entries HTTP request.

include/fluent-bit/flb_upstream_node.h, plugins/out_azure_kusto/azure_kusto_conf.c, src/flb_upstream_ha.c, src/flb_upstream_node.c
Reported in https://github.com/fluent/fluent-bit/issues/9152#issuecomment-2277689385.
----
**Testing**
Certificates are used from here: https://github.com/fluent/fluent-bit/issues/8072#issue-1954001284
Client side:
```ini
[SERVICE]
flush 1
[INPUT]
name  dummy
dummy {"message": "custom dummy message"}
[OUTPUT]
name   forward
match  *
Upstream      upstream-ha.conf
```
upstream-ha.conf
```ini
[UPSTREAM]
name        forward-balancing
[NODE]
name          node-1
host          other.fluent-backoffice.de
port          24224
tls           on
tls.verify    on
tls.verify_hostname on
tls.ca_file   /path/to/necessary-certs/fluent-root.crt …
```
=> upstream_ha: upstream_node: process verify hostname on HA settings

plugins/in_kubernetes_events/kubernetes_events.h
=> in_kubernetes_events: Use time_t for time(NULL) returned value (CID 507947)

plugins/in_exec_wasi/in_exec_wasi.c
=> in_exec_wasi: Fix resource leak on exception (CID 508347)

include/fluent-bit/flb_parser.h, tests/runtime/filter_parser.c
Previously, `Time_System_Timezone` would not work for timezone specifications like `America/Toronto` or `EST5EDT` because I neglected to set `tm_isdst` to `-1`, which prompts `mktime` to detect daylight savings time on its own.
This PR addresses this issue, and fixes the test data which was previously incorrect due to the existence of this bug.
#9197
----
**Testing**
---- …
=> Make `Time_System_Timezone` properly detect daylight savings

plugins/in_http/http_prot.c, tests/runtime/in_http.c
**Summary**
- Updated `http_prot` to handle json content type header with charset. 
- Include guard for content types that maybe be a flavor of `application/json` but of an unknown/unsupported content type. 
- Includes `in_http` runtime tests.
Current issue: https://github.com/fluent/fluent-bit/issues/9018
Other issue related to this PR fix https://github.com/fluent/fluent-bit/issues/5062
----
**Testing**
If …
=> in_http: Content-Type rejected for application/json when encoding value is present.

include/fluent-bit/flb_metrics.h, plugins/in_statsd/statsd.c, tests/runtime/in_statsd.c
----
**Testing**
```console
$ bin/fluent-bit -i statsd -p metrics=On -o stdout -v
```
```log
Fluent Bit v3.1.6
______ _                  _    ______ _ _           _____  __  
|  ___| |                | |   | ___ (_) |         |____ |/  | 
| |_  | |_   _  ___ _ __ | |_  | |_/ /_| |_  __   __   / /`| | 
|  _| | | | | |/ _ \ '_ \| __| | ___ \ | __| \ \ / /   \ \ | | 
| |   | | |_| |  __/ | | | |_  | |_/ / | |_   \ V /.___/ /_| |_
\_|   |_|\__,_|\___|_| |_|\__| \____/|_|\__|   \_/ \____(_)___/
[2024/08/14 …
```
=> in_statsd: Implement metrics type of ingestion way

plugins/out_cloudwatch_logs/cloudwatch_logs.c
Fixes #8949
Since release 3.0.7 `auto_create_group` couldn't be set to Off anymore. That was a breaking change.
I didn't see any reason why `log_group_class_type` and `log_group_class` should be set, as they're not used when `[auto_]create_group` is off.
Please review @PettitWesley @edsiper
----
**Testing** …
=> out_cloudwatch_logs: fix disabled auto_create_group

tests/runtime/in_http.c
This PR changes the failure triggering mechanism because it was noticed that in some systems the directory ACL change was "ignored" causing a false positive.
=> tests: in_http: replaced the failure trigger mechanism

plugins/in_elasticsearch/in_elasticsearch.h, plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c, plugins/in_elasticsearch/in_elasticsearch_config.c
=> in_elasticsearch: Store log_encoder pointer (CID 508245)

plugins/out_chronicle/chronicle.c
=> out_chronicle: Plug a resource leak on exception (CID 508008)

src/flb_config_map.c, tests/internal/config_map.c
Addresses #8828
It fixes two types configuration failure issues that only appear on big endian systems,
- Plugin configurations with predefined int values are always zero, .e.g `rotate_wait` in `tail` plugin.
- Boolean variables in plugin configuration cannot be turned on in configuration files, .e.g `read_from_head` in `tail` plugin and `lowercase` in `systemd` plugin.
----
**Testing**
```
[INPUT]
Name             tail
Path             /var/log/dpkg.log
Read_from_Head   True
[OUTPUT]
Name   stdout
Match  *
```
```
fluent-bit/bin# ./fluent-bit -c fluent.conf 
Fluent Bit v3.0.4
* Fluent Bit is a …
```
=> core: fix configuration type cast issue on big endian systems

plugins/in_emitter/emitter.c
=> in_emitter: Plug a possible resource leak on exception (CID 508193)

plugins/filter_log_to_metrics/log_to_metrics.c, plugins/filter_log_to_metrics/log_to_metrics.h
This PR addresses an issue where the incorrect data type was used for the `mode` option which caused the config map handler to overwrite the adjacent fields (`discard_logs` at least) in 64 bit systems.
=> filter_logs_to_metrics: fixed memory corruption issue

plugins/in_winevtlog/pack.c
`S-1-15-3-` prefixed SIDs are not mapped for friendly names.
We should skip to query to retrieve associated names.
----
**Testing**
----
=> in_winevtlog: Skip to translate SID for capability SIDs

CMakeLists.txt, include/fluent-bit/flb_endian.h
This PR addresses an issue with the byte order detection macro in `flb_endian.h` switching the buggy implementation with the proven cmake based detection mechanism used by msgpack-c.
=> core: endianness detection fix

plugins/in_process_exporter_metrics/pe_process.c
=> in_process_exporter_metrics: Initialize with NULL for flb_sds_t pointer variables (CID 507975)

src/flb_output.c
=> output: Remove a needless calling of flb_output_instance_destroy() (CID 507809)

plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
It's replying with `400 Forbidden`; it should be `400 Bad Request`
----
=> in_elasticsearch: Fix string in http response code 400

plugins/out_logdna/logdna.c, plugins/out_logdna/logdna.h
Previously, the LogDNA URI was hardcoded to use the `/logs/ingest` endpoint. This change introduces flexibility by allowing users to specify their own endpoint through the `logdna_endpoint` configuration. This can be particularly useful for users with different LogDNA setups or those using Super Tenancy.
----
**Testing** …
=> out_logdna: refactored LogDNA URI formation to support configurable endpoints

plugins/in_splunk/splunk_prot.c, tests/runtime/in_splunk.c
In Splunk HEC protocol, we need to handle 1.0 suffixed endpoints for event and raw type of payloads of Splunk HEC.
----
**Testing**
----
=> in_splunk: test: Handle 1.0 suffixed endpoints

src/flb_utils.c
kIOMainPortDefault is available on macOS 12+: https://developer.apple.com/documentation/iokit/kiomainportdefault
Add a fallback definition to fix compilation on earlier systems.
Verified to work on macOS 10.6.
----
**Testing**
----
=> flb_utils.c: fix for macOS < 12

plugins/out_es/es.c, plugins/out_es/es.h
The current out_elasticsearch implementation is just giving up to process responses when encountering the error information. In this patch, continue to process until the end of the elements of msgpack converted JSON response.
If there is a succeeded information in the converted response, Fluent Bit will assume the requested payloads to be succeeded to send ES clusters.
Another solution to fix https://github.com/fluent/fluent-bit/issues/6341.
----
**Testing**
```ini
[SERVICE]
Flush        1
Flush        5
[INPUT]
Name forward
Port 24225
[OUTPUT]
Name es …
```
=> out_elasticsearch: Process error information properly

plugins/in_winevtlog/pack.c, plugins/out_s3/s3.c
In Windows, mkdir does not have second argument.
Plus, pack_wstr in pack.c in in_winevtlog does not have third argument.
Today or yesterday, it seems that the windows-latest worker is upgraded. So, these previously warnings are treated as compilation errors.
----
**Testing**
----
=> in_winevtlog: out_s3: Fix windows build failures

plugins/in_podman_metrics/podman_metrics_data.c
=> in_podman_metrics: Plug a resource leak on exception (CID 507805)

plugins/out_calyptia/calyptia.c, plugins/out_opentelemetry/opentelemetry_logs.c
=> coverity: fixes for 20240829

src/flb_record_accessor.c
=> record_accessor: Plug a resource leak on exception (CID 508119)

plugins/out_opentelemetry/opentelemetry_utils.c
=> out_opentelemetry: Prevent null dereference on memcpy (CID 507910)

plugins/out_calyptia/calyptia.c, plugins/out_opentelemetry/opentelemetry_logs.c
=> coverity: fixes as of 20240830 (CID 507960)

.github/workflows/unit-tests.yaml
This workflow could be used for aarch64 Linux testing purpose such as #8851.
Also, `uraimo/run-on-arch-action@v2` workflow component can handle s390x and ppc64le architectures by QEMU emulations.
So, we can add these targets in the future.
----
**Testing**
----
=> workflows: linux: Compile and execute internal test on non-amd64 platforms Linux

plugins/out_influxdb/influxdb.c, plugins/out_influxdb/influxdb.h, tests/runtime/CMakeLists.txt, tests/runtime/out_influxdb.c
This is because in their line protocol, it needs to add "i" suffix for handling a value as an integer:
| Datatype | Element(s)   | Description |
|:--------:|:------------:|:------------|
| Integer | Field values | Signed 64-bit integers (-9223372036854775808 to 9223372036854775807). Specify an integer with a trailing i on the number. Example: 1i |
So, we need to add "i" suffix for signed/unsigned integer values if needed.
ref: https://docs.influxdata.com/influxdb/v1/write_protocols/line_protocol_reference/
Closes https://github.com/fluent/fluent-bit/issues/9120.
----
**Testing**
```yaml
service:
flush: 1
pipeline:
inputs:
- …
```
=> out_influxdb: Handle signed/unsigned integer as influx's integer of that representation

plugins/out_http/http.c
Request timed out status should be retried.
Related to https://github.com/fluent/fluent-bit/issues/9371.
----
**Testing**
----
=> out_http: Request timed out(408) to be treated as retry

plugins/out_splunk/splunk.c
408 and 429 also should be treated as retry.
Backport of https://github.com/fluent/fluent-bit/pull/9375.
----
**Testing**
----
=> out_splunk: Extend retrying HTTP status code [Backport 3.1]

plugins/out_http/http.c
Backport of https://github.com/fluent/fluent-bit/pull/9377.
----
**Testing**
----
=> out_http: Request timed out(408) to be treated as retry [Backport 3.1]

plugins/out_influxdb/influxdb.c, plugins/out_influxdb/influxdb.h, tests/runtime/CMakeLists.txt, tests/runtime/out_influxdb.c
Backporting PR: https://github.com/fluent/fluent-bit/pull/9301.
----
**Testing**
----
=> out_influxdb: Handle signed/unsigned integer as influx's integer of that representation [Backport 3.1]

src/flb_io.c, src/tls/flb_tls.c
Code that does not specifically support coroutines can result in a segmentation fault when coroutines are used during I/O and network calls. Under most circumstances this should not occur but if an input plugin shares the same thread as any output plugin that can inadvertently enable coroutines for all input plugins as well as causing custom events to use coroutines as well.
~~This PR mitigates this by juggling out the thread local storage used by coroutines during collect callbacks for non-coroutine inputs as well as custom events which do not have a way to express their compatibility with coroutines.~~
This PR has been refactored so that both the `flb_io_net_connect` and `flb_tls_session_create` functions respect the `FLB_IO_ASYNC` flag instead of assuming it when coroutines have been …
=> input: disable coroutines for custom events and input callbacks that do not support coroutines.

src/flb_io.c, src/tls/flb_tls.c
This backports https://github.com/fluent/fluent-bit/pull/9338 to the 3.1 series.
----
**Testing**
----
=> backport: PR #9338 to 3.1

plugins/filter_log_to_metrics/log_to_metrics.c, plugins/filter_log_to_metrics/log_to_metrics.h
This PR will change the log_to_metrics filter to use a timer based metric inject and not directly inject metrics on every incoming log record anymore. This will lower the overall load and memory consumption especially in high-volume and high-cardinality situations.
cc @leonardo-albertovich @edsiper 
Fixes https://github.com/fluent/fluent-bit/issues/9189
----
**Testing**
- [N/A] Set `ok-package-test` label to test for all targets …
=> filter_log_to_metrics: Add timer callback for emitting metrics

src/flb_io.c, src/tls/flb_tls.c
This backports #9338 to the 3.0 series.
----
**Testing**
- [Y] Backport to latest stable release.
----
=> input: backport #9338 to 3.0.

plugins/out_splunk/splunk.c
408 and 429 also should be treated as retry.
Related to https://github.com/fluent/fluent-bit/issues/9371.
----
**Testing**
----
=> out_splunk: Extend retrying HTTP status code

lib/cmetrics/CMakeLists.txt, lib/cmetrics/include/cmetrics/cmt_math.h, lib/cmetrics/src/cmt_cat.c, lib/cmetrics/tests/cat.c, lib/cmetrics/tests/prometheus_parser.c
=> 3.1: lib: upgrade cmetrics to v0.9.6

dockerfiles/Dockerfile.centos7, packaging/distros/centos/Dockerfile, plugins/in_winevtlog/pack.c, plugins/out_s3/s3.c
Resolves #9414 by including fixes from `master` for:
- #9157 
- #9212
- #9293
**Testing**
----
=> backport: resolve build failures for CentOS 7 and Windows on 3.0

.github/workflows/cron-scorecards-analysis.yaml, dockerfiles/Dockerfile, dockerfiles/Dockerfile.windows
Resolve failures in scorecard analysis and linting annotations in PRs around new docker checks: https://github.com/fluent/fluent-bit/actions/runs/10968711777/job/30460429783
Aligned scorecard workflow with recommended one: https://github.com/ossf/scorecard/blob/main/.github/workflows/scorecard-analysis.yml
=> workflows: Update scorecard workflow and remove Dockerfile warnings

src/config_format/flb_cf_yaml.c, tests/internal/config_format_yaml.c, tests/internal/data/config_format/yaml/broken_plugin_variant.yaml
These memory leaks are detected by OSSFuzz.
`(struct parser_state *)state->variant_kvlist_key` and `(struct parser_state *)state->variant` should be destroyed before tweardowning parser state value is cleaned up.
----
**Testing**
----
=> config_format: cf_yaml: Plug memory leaks on exception for processing variants on plugin elements

plugins/out_calyptia/calyptia.c
Adds fields to agents for operating system and architecture.
It supports the following operating systems:
- Linux
- Windows
- MacOS
- FreeBSD
- NetBSD
- OpenBSD
It supports the following architectures:
- X86
- X86_64
- ARM
- ARM64
All of these are assigned using C macro definitions and not by using system calls.
----
**Testing**
----
---
- To see the …
=> out_calyptia: register OS and architecture for agents.

src/flb_upstream.c
prepare_destroy_conn calls mk_list_del on the event in the priority bucket queue, so for safety, we inject it after this covers us against the case where the event was triggered and waiting, but we also reached the timeout.
Addresses this issue on 1.9: https://github.com/fluent/fluent-bit/issues/6822
**See the issue for a design doc on why this is needed**
----
**Testing**
---- …
=> upstream_conn: fix ordering of mk_event_inject and prepare_conn_destroy

plugins/in_calyptia_fleet/in_calyptia_fleet.c
Fleet is unable to work due to a breaking change to the Calyptia API. This update brings the code inline with that update.
----
**Testing**
----
Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under …
=> in_calyptia_fleet: fix 'unable to find fleet by name'.

src/multiline/flb_ml.c
This PR resets the size of the metadata buffer on a flush event, which fixes continuous growth of this buffer over time.
Fixes #9262, Fixes #8925, Fixes #9337, Fixes #8567
----
**Testing**
```
root@fb-dev:~/test/fluent-bit/build# valgrind --leak-check=full ./bin/fluent-bit -c /root/test/fluent-bit.conf 
==645974== Memcheck, a memory error detector
==645974== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==645974== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==645974== Command: ./bin/fluent-bit -c …
```
=> filter_multiline: Reset group metadata buf on flush - Fixes 9262,8925,9337,8567

lib/ctraces/CMakeLists.txt, lib/ctraces/src/ctr_encode_opentelemetry.c, lib/ctraces/tests/decoding.c, plugins/in_calyptia_fleet/in_calyptia_fleet.c, plugins/out_calyptia/calyptia.c, src/config_format/flb_cf_yaml.c, src/multiline/flb_ml.c, tests/internal/config_format_yaml.c, tests/internal/data/config_format/yaml/broken_plugin_variant.yaml
- 5afc24144 filter_multiline: Reset group metadata buffer on flush
- dc08a18ff in_calyptia_fleet: fix 'unable to find fleet by name'.
- fd7bdd62f lib: ctraces: upgrade to v0.5.6
- e430fe6b8 out_calyptia: add missing parameter for msgpack_str for windows os field.
- 6b70766f0 out_calyptia: register OS and architecture for agents.
- dc2ac8dc2 config_format: cf_yaml: Cleanup variants only if occurred an exception
- a4371405c config_format: cf_yaml: tests: Add a test case for broken plugin variant
- 0702144d3 config_format: cf_yaml: Plug memory leaks on exception for variants on plugin elements
----
=> 3.1: backport fixes 2024-09-26

src/flb_reload.c
This is another approach to fix the issue handled in #9428 by removing unnecessary calls to `flb_stop` in `flb_reload` when `flb_start` fails.
The crash is caused by calling `pthread_join`, which is called by `flb_stop`. The `flb_reload` function calls `flb_stop` whenever `flb_start` fails but it already cleans up the thread if necessary, making the call to `flb_stop` after `flb_start` fails semantically incorrect.
```
$ valgrind ./bin/fluent-bit -c fleet.conf -Y
==52681== Memcheck, a memory error detector
==52681== Copyright (C) 2002-2024, and GNU GPL'd, by Julian Seward et al.
==52681== Using Valgrind-3.23.0 and LibVEX; rerun with -h for copyright info
==52681== Command: ./bin/fluent-bit -c fleet.conf -Y
==52681==
* …
```
=> reload: do not call flb_stop when flb_start fails to avoid crash on RHEL/CentOS.

src/flb_reload.c
This is a backport to 3.1 of #9432.
----
**Testing**
----
=> reload: do not call flb_stop when flb_start fails and fix crash on RHEL

src/flb_upstream.c, src/flb_utils.c
Added specific messages for errors inside the function `flb_utils_proxy_url_split()`.
Removed the call to `flb_errno()` since errors are displayed by `flb_utils_proxy_url_split`.
Fixes #9327 
----
**Testing**
Config for repro from #9327.
```text
______ _                  _    ______ _ _           _____  __  
|  ___| |                | |   | ___ (_) |         |____ |/  | 
| |_  | |_   _  ___ _ __ | |_  | |_/ /_| |_  __   __   / /`| | 
|  _| | | | | |/ _ \ '_ \| __| | ___ \ | __| \ \ / /   \ \ | | 
| |   | | |_| |  __/ | | | |_  | |_/ / | |_   \ V /.___/ /_| |_ …
```
=> upstream: Improve error message for misconfigured HTTP_PROXY variable

src/flb_upstream.c, src/flb_utils.c
This is backport of #9328
----
=> upstream: Improve error message for misconfigured HTTP_PROXY variable - Backport to 3.1

.github/workflows/staging-release.yaml
CI updates now we have a `3.1` branch - also added placeholders for 4.0 releases from `master` but this will need updates to the workflow to remove 3.1 as the `latest` release.
Related to https://github.com/fluent/fluent-bit/pull/9440
=> workflows: update for 3.1 branch

plugins/in_opentelemetry/opentelemetry_prot.c
For some reason the new HTTP/2 server codepaths in the OpenTelemetry input plugin don't have any support for the `tag_from_uri` plugin option.
This PR adds the same `v1_metrics` / `v1_logs` / `v1_traces` tags that the `tag_from_uri` behaviour in the previous `flb_downstream`-based non-HTTP/2 codepath.
Strictly speaking, this is arguably not fully correct, as the "URI"s in the gRPC cases are more complex:
* `opentelemetry.proto.collector.metrics.v1.MetricsService/Export`
* `opentelemetry.proto.collector.traces.v1.TracesService/Export`
* `opentelemetry.proto.collector.logs.v1.LogsService/Export`
However it's probably a good enough first step given that anyone trying to filter by telemetry signal type would already be using these `v1_metrics` / `v1_logs` / `v1_traces` tags, and it seems …
=>  in_opentelemetry: add tag_from_uri support to http2 codepath 

plugins/in_http/http_prot.c
This patch fixes the problem where a JSON object cannot be ingested by using in_http, e.g:
```bash
curl -d '{"key1":"value1","key2":"value2"}' -XPOST -H "content-type: application/json" http://localhost:8888/app.log
```
----
=> in_http: fix parsing of root JSON object

lib/monkey/CMakeLists.txt, lib/monkey/api/test.c, lib/monkey/include/monkey/mk_http_parser.h, lib/monkey/mk_core/mk_event_select.c, lib/monkey/mk_server/mk_http.c, lib/monkey/mk_server/mk_http_parser.c, lib/monkey/plugins/logger/logger.c, plugins/in_elasticsearch/in_elasticsearch_bulk_conn.c, plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c, plugins/in_http/http_conn.c, plugins/in_http/http_prot.c, plugins/in_opentelemetry/http_conn.c, plugins/in_opentelemetry/opentelemetry_prot.c, plugins/in_splunk/splunk_conn.c, plugins/in_splunk/splunk_prot.c, src/http_server/flb_http_server_http1.c
This PR upgrades Monkey Library through https://github.com/monkey/monkey/pull/417 to add support for HTTP/1.1 chunked transfer encoding. It adds support to the internal http_server http/1.1 API and it also modify the following plugins to extend it support:
----
=> lib: monkey: upgrade to v1.8.1 (add support for HTTP/1.1 chunked transfer encoding)

src/http_server/flb_http_server_http1.c
When Monkey parser returns `MK_HTTP_PARSER_PENDING` always reset the parser state:
```
The primary reason is that the caller may need to expand the buffer size when payloads
exceed the current buffer's capacity. In such cases, parser pointers could end up
referencing incorrect memory locations.
To prevent this, we reset the parser state, which introduces a minimal performance overhead 
in exchange for ensuring safety.
```
----
=> http_server: http1: always reset the parser context on pending status

tests/internal/input_chunk.c
There is a use-after-free bug in the internal test `input_chunks`, specifically in the sub-test `input_chunk_dropping_chunks`. This is caused by a premature and explicit freeing of all the chunks and explicit stopping of all the tasks by the test. This is done implicitly by either `flb_stop` or `flb_destroy`.
This PR simply eliminates this code to fix this potential use-after-free or double-free. This should make this test less flakey on macOS, as well as other operating systems.
----
**Testing** …
=> tests/internal: fix use-after-free for input_chunks test input_chunk_dropping_chunks.

.github/workflows/unit-tests.yaml, CMakeLists.txt, include/fluent-bit/flb_simd.h, src/flb_engine.c, src/flb_utils.c
For cases where JSON encoding is needed, if SIMD is available, this brings 30%-50% performance improvement.
__PostgreSQL SIMD__ 
The  _header file_ with SIMD functionality has been taken from the PostgreSQL project, stripped down, and adapted for our specific needs. 
__Notes on other improvements__
- the routine that is used to escape characters, now uses a lookup table which heavily improves performance when Fluent Bit is built on release mode (optimizations on). This brings performance improvements for all systems/architectures.
- SIMD operations are available for architectures that implement SSE2 (Intel/AMD) and Neon (Arm) based instructions. Note that AVX2 is not implemented so there is still more room for improvement. 
---- …
=> simd: add new SIMD support for JSON escaping

include/fluent-bit/config_format/flb_cf.h, include/fluent-bit/flb_parser.h, include/fluent-bit/flb_plugin.h, src/config_format/flb_cf_yaml.c, src/config_format/flb_config_format.c, src/flb_config.c, src/flb_parser.c, src/flb_plugin.c, src/flb_upstream_ha.c, src/stream_processor/flb_sp.c, tests/internal/config_format_yaml.c, tests/internal/data/config_format/yaml/extra_parser.yaml, tests/internal/data/config_format/yaml/parsers_and_multiline_parsers.yaml, tests/internal/data/config_format/yaml/plugins.yaml, tests/internal/data/config_format/yaml/stream_processor.yaml, tests/internal/data/config_format/yaml/upstream.yaml
The following PR/branch implements the final pieces for full Yaml support. Components that are being added to Yaml
__Parsers__
Parsers are now supported in the main config file or through an included Yaml file, definition:
```yaml
parsers:
- name: json
format: json
- name: docker2
format: json
time_key: time
time_format: "%Y-%m-%dT%H:%M:%S.%L"
time_keep: true
```
Note that this functionality is compatible with the old service `parsers_file` directive.
__Multiline Parsers__
Multiline parsers combine logs that are split across multiple events into one, keeping the full message together, like with stack traces or detailed logs.
The current implementation in Yaml differs a bit in syntax from classic format, however there are no breaking changes. Here is an example of one multiline parser …
=> config: complete Yaml support

plugins/processor_content_modifier/CMakeLists.txt, plugins/processor_content_modifier/cm.c, plugins/processor_content_modifier/cm.h, plugins/processor_content_modifier/cm_config.c, plugins/processor_content_modifier/cm_metrics.c, plugins/processor_content_modifier/cm_opentelemetry.c, plugins/processor_content_modifier/cm_opentelemetry.h, plugins/processor_content_modifier/cm_traces.c, plugins/processor_content_modifier/cm_utils.c, plugins/processor_content_modifier/cm_utils.h, src/flb_processor.c, tests/runtime/processor_content_modifier.c
The following PR extends Content Modifier processor allowing to operate on metrics generated originally by OpenTelemetry. The following contexts are available for metrics:
- `otel_resource_attributes`
- `otel_scope_name`
- `otel_scope_version`
usage example:
```yaml
service:
pipeline:
inputs:
- name: opentelemetry
processors:
metrics:
context: otel_scope_name
action: upsert
value: "fluent-bit-scope"
context: otel_scope_attributes
action: upsert
key: scope_attr_processor
value: "attributes fluent-bit"
context: otel_scope_name
action: upsert
value: "new-scope-name"
context: otel_resource_attributes
action: insert
key: "added_by"
value: "fluent-bit" …
```
=> processor_content_modifier: add support for Metrics processing

src/tls/openssl.c
Users with expired CA never got to understand the root cause by reading the log message, although this information is available on the x509 error details. (https://x509errors.org/) 
```
[2024/09/16 10:00:38] [error] [tls] error: unexpected EOF with reason: certificate verify failed
```
This patch adds the X509_verify_cert_error_string to the log message when SSL verification result != X509_V_OK.
With this patch applied, the following information is returned
```
[2024/10/28 22:35:46] [error] [tls] certificate verification failed, reason: unable to get local issuer certificate (X509 code: 20)
```
**Testing**
Configuration I have used.
```ini
[SERVICE]
[CUSTOM]
name calyptia
api_key xxx
fleet_name test-jorge
calyptia_tls.verify on
calyptia_host …
```
=> tls: include X509 error string when verify result is not x509_V_OK.

src/tls/openssl.c
Gives better detailed information on the cause of the failure when loading system certificates on windows.
This patch also adds a condition to allow identifying colliding certificates (X509_R_CERT_ALREADY_IN_HASH_TABLE)
or errors while enumerating the system certificates (GetLastError() != CRYPT_E_NOT_FOUND)
This patch goes next to #9527 and #9528 
**Testing**
This patch goes next to #9527 and #9528 
----
=> tls: improve debug information on the cause of the failure when loading system certificates on windows 

DEVELOPER_GUIDE.md
This pull request adds new documentation to the DEVELOPER_GUIDE for building and running fluent on Windows Server 2022. 
* Added Windows 2022 setup instructions. step-by-step for setting up the environment to build Fluent Bit on Windows Server 2022, including Visual Studio installation, Flex and Bison setup, and dependency management using vcpkg.
* Also, I corrected references from Chocolatey to vcpkg for dependency installation, aligning the local build guide with the tools used in CI.
=> docs: DEVELOPER_GUIDE: add instructions for windows 2022.

src/flb_input_chunk.c
move input metrics collections before applying filters.
Fixes #8729
----
**Testing** …
=> input_chunk: fix input plugin metrics not counting records re-emitted by filters downstream

src/CMakeLists.txt, src/tls/openssl.c
This patch should be stacked after
- #9527 
- #9533 
I realised that none of the expected locations for the PEM files was available on my machine. I had some PEM files created by the brew installer but none of them were being detected by fluent-bit.
If the plugin didn't have explicilty set to tls.verify off, I would get a certify verify failed, no matter on which
location I place my CA ring or my pem files.
```
[2024/10/25 15:46:49] [debug] [calyptia:calyptia.0] created event channels: read=27 write=28
[2024/10/25 15:46:49] [debug] [output:calyptia:calyptia.0] machine_id=73a2e3fa6b6844dd36fcd9970d39537980905f85972aa7f9c210080c55dcf3e2
[2024/10/25 15:46:49] [error] [tls] error: unexpected EOF with reason: certificate verify failed
[2024/10/25 15:46:49] [debug] [upstream] …
```
=> tls: macos load system certificates using security framework.

plugins/out_azure_blob/azure_blob.c
Consider auto_create_container when ensuring container exist
1. Today we are not considering this setting
2. Changing the behaviour that setting auto_create_container to false should return FLB_TRUE. If auto_create_container is false return FLB_FALSE, fluent-bit will never flush data to storage account, it will retry and eventually fail.
Fixes #9459 
----
**Testing**
No need for debug log output, attaching info log output
With `auto_create_container` on:
```
* Fluent Bit is a CNCF …
```
=> out_blob: consider auto_create_container

plugins/filter_multiline/ml.c
This PR adds the support to re-emit the processed multiline records back into the processor pipeline.
It is basically a copy of the rewrite_tag code:
https://github.com/fluent/fluent-bit/blob/aadaf1c071c41198c08f5214708d4ee8ecd07f47/plugins/filter_rewrite_tag/rewrite_tag.c#L319-L348
----
**Testing**
- [N/A] …
=> filter_multiline: Add functionality to use as processor

include/fluent-bit/flb_output.h
For full context, refer to #9553.
A chunk with no records is a valid scenario for logs (e.g., when all are dropped) and should either be added to the flush list or released immediately. However, the chunk should not attempt to flush.
This patch allows for the record size to be zero for `FLB_EVENT_TYPE_LOGS`.
I created a basic processor that calls `flb_mp_chunk_cobj_record_destroy` on each record, resulting in a chunk with no records (size = 0). When this happens, coroutine tasks do not run, and `fluentbit_storage_mem_chunks` continues to grow, causing a memory leak (refer to the issue report).
```c
#include <fluent-bit/flb_processor_plugin.h>
static int cb_init(struct flb_processor_instance *ins,
void *source_plugin_instance,
int source_plugin_type,
struct flb_config *config)
{
return …
```
=> output: allow records size 0 on flb event type logs processor

plugins/in_calyptia_fleet/in_calyptia_fleet.c
Given that this search is to get a fleet id, it should only return either 0 or 1 match. For this, this must be case-sensitive and do not return partial matches.
This is based on https://github.com/chronosphereio/calyptia-backend/blob/2704bda975697f64fd962a3d0d2d3bc6dae247ac/components/cloud/spec/open-api.yml#L9706-L9709
and https://github.com/chronosphereio/calyptia-backend/blob/2704bda975697f64fd962a3d0d2d3bc6dae247ac/components/cloud/internal/postgres/search.go#L15-L19
----
Tests with the CLI:
Starting point is, I have a fleet named `TEST-case` 
```text
➜  ~ calyptia create fleet --name test-case
Error: fleet name taken
➜  ~ calyptia get fleet test-case
Error: could not find fleet "test-case"
➜  ~ calyptia get fleet TEST-case
NAME      TAGS AGE
TEST-case      1 hour
```
Fluent Bit is …
=> in_calyptia_fleet: fleet id search by name must use exact name.

plugins/custom_calyptia/calyptia.c, plugins/in_calyptia_fleet/in_calyptia_fleet.c
Increase max http buffer size and make it configurable. The setting had to be replicated to both `custom_calyptia` and `in_calyptia_fleet`.
----
**Testing**
----
=> in_calyptia_fleet: make the http client buffer size configurable.

plugins/in_calyptia_fleet/in_calyptia_fleet.c
Fix a bug where calyptia fleet agents will not correctly register after the first  time it is run.
The calyptia fleet plugin stores the initial configuration that is used to invoke fluent-bit inside a file called `header.conf` (it only stores the configuration for the custom calyptia plugin) and makes use of it in further executions. The plugin also resolves the `fleet_name` into a `fleet_id`. This `fleet_id` though is not known on further executions and due to how it is resolved it would never be resolved in time to register the agent on subsequent executions.
THis fix simply adds the `fleet_id` to this `header.conf` so it can be used in subsequent executions beyond the first so it can register fluent-bit with the calyptia frontend.
---- …
=> in_calyptia_fleet: fix registering agent after first invocation.

include/fluent-bit/flb_filter.h, include/fluent-bit/flb_metrics.h, src/flb_filter.c
To observe more precisely for filter plugins, we need to add dropped bytes metrics into ordinary metrics for filter plugins.
The dropped size should be a monotonic value. So, I choose counter type of cmetrics to handle it.
----
**Testing**
```ini
[SERVICE]
HTTP_Server On
HTTP_Port 2020
[INPUT]
Name dummy
Dummy {"endpoint":"localhost", "value":"something"}
Tag dummy
[FILTER]
Name grep
Match *
Exclude value something
[OUTPUT]
Name stdout
```
```
% bin/fluent-bit -c grep.conf -v
______ _ …
```
=> filter: Add dropped_bytes_total / drop_bytes metrics

include/fluent-bit/flb_network.h, src/flb_io.c, src/flb_network.c, src/flb_upstream.c
This PR is a rebased and slightly amended version of PR #3096.
Credit for this feature should be attributed to Abilio Marques.
=> network: tcp keepalive addition

plugins/out_datadog/datadog.c, plugins/out_datadog/datadog.h
Added ability to set custom HTTP headers for Datadog output
----
**Testing**
```
[INPUT]
name              tail
path              /var/lib/docker/containers/**/*.log
path_key          path
multiline.parser  docker, cri
Parser            docker
Docker_Mode       On
[SERVICE]
Flush        1
Parsers_File parsers.conf
[Output]
name                  datadog
match                 *
host                  victorialogs
port                  9428
tls                   off
compress              gzip
apikey                test
dd_service            test
dd_source             data
dd_message_key        log
dd_tags               env:dev
header …
```
=> out_datadog: custom added ability ot set custom HTTP headers

plugins/out_kinesis_streams/kinesis.c, plugins/out_kinesis_streams/kinesis.h, tests/runtime/out_kinesis.c
This PR enhances the Kinesis output plugin by adding support for custom port configuration. The changes include:
1. Added a new configuration option 'port' to allow users to specify a custom port for Kinesis connections.
2. Modified the plugin initialization to use the custom port when specified, defaulting to the standard port (443) when not provided.
3. Updated the connection logic to utilize the custom port when establishing connections to Kinesis.
4. Added error handling to validate the port number, ensuring it's within a valid range (1-65535).
5. Updated documentation to reflect the new 'port' configuration option.
6. Added new unit tests to verify the functionality of the custom port feature:
- Test for default port behavior
- Test for successful custom port configuration
- Test for …
=> out_kinesis_streams: add custom port support for Kinesis output plugin

src/flb_metrics_exporter.c, src/flb_processor.c
Fixes #7391
----
**Testing**
----
=> metrics_exporter: add support for filter metrics inside processors

src/flb_network.c
This is a typo I spotted in reviewing #5613 - the current code  appears to set opt.tries to 2 (from the default 3) but because the corresponding optflag is not set it will be ignored.
See the c-ares code that is being called:
https://github.com/c-ares/c-ares/blob/e4a4346596c62621704371270220b567b0ddd83d/src/lib/ares_options.c#L310-L316
I'm afraid this is a bit thrown over the wall and untested - I'm just doing it to highlight what's clearly a bug in the code.
An alternative approach would be to delete the line setting opt.tries, because that would leave the behaviour unchanged;
right now I'd _want_ the change I'm proposing tested, because that tries setting has never worked before.
----
**Testing**
Before we can …
=> fix: ARES_OPT_TRIES must be set to update opt.tries

src/flb_network.c
The build fails in OSX because TCP_KEEPIDLE doesn't exist in the netinet lib, instead TCP_KEEPALIVE should be used.
Not sure if the ifdef should be here or not. I'd appreciate the feedback.
----
=> network: use TCP_KEEPALIVE instead of TCP_KEEPIDLE in OSX

plugins/in_opentelemetry/opentelemetry.c, plugins/in_opentelemetry/opentelemetry.h, plugins/in_opentelemetry/opentelemetry_prot.c
This PR will not build until the accompanying PR that introduces cprofiles in the system is merged and this one is rebased
=> opentelemetry: initial addition of the experimental otlp profile signal

.github/workflows/cron-unstable-build.yaml, .github/workflows/staging-release.yaml, dockerfiles/Dockerfile, fluent-bit-3.2.0.bb, snap/snapcraft.yaml
CI updates to support 3.2 releases.
Do not merge until ready to release 3.2.0.
Note this assumes a `3.1` branch for docs as well.
----
**Testing**
----
=> ci: support 3.2 releases as latest version

plugins/in_ebpf/CMakeLists.txt
Without the generated directory creation before compiling eBPF objects, I get failed to compile eBPF objects for in_ebpf plugin.
After adding that creation of directory, I succeeded to compile in_ebpf plugin in Ubuntu 24.04 with 6.11 (noble-proposed) Kernel and its associated linux-tools. 
----
**Testing**
----
=> in_ebpf: Prepare build directory for building eBPF objects

plugins/in_splunk/splunk_prot.c
Changes validation of received Splunk token to be case-insensitive, as the Splunk HEC does.
fixes #9517 
----
=> in_splunk: splunk token validation must be case-insensitive

plugins/in_splunk/splunk_prot.c
Backport to 3.1 of #9518 
----
=> in_splunk: splunk token validation must be case-insensitive. Backport of #9518

SECURITY.md
Moving 3.0 out of support.
----
=> security: supported versions now are 3.1.x and 3.2.x

run_code_analysis.sh
ci: extended script running tests to match requirements of test_flb_utils_get_machine_id test for flb_utils_get_machine_id function from flb_utils.c
----
**Testing**
```bash
TEST_PRESET=valgrind ./run_code_analysis.sh
```
can be found at [flb_run_code_analysis_9630.log](https://drive.google.com/file/d/1UE8E6cjG_u0POvMCY9YWXwyDMnSzMlB-/view?usp=sharing) which has (at the end of log):
```text
100% tests passed, 0 tests failed out of 139
```
- …
=> ci: extended CI script to pass test for flb_utils_get_machine_id

plugins/in_node_exporter_metrics/ne_utils.c
On exception happened, we just omitted to print the path of aborted path without mount point.
This is sometimes troublesome to distinguish where should cause the permission issue or just absent path.
In this case, we need to display the real_path which contains the full path of handling of glob.
----
**Testing**
```
$ bin/fluent-bit -i node_exporter_metrics -p metrics=cpu -p path.sysfs=/host/sysfs -o stdout -v
```
```
[2024/11/19 19:03:18] [error] [input:node_exporter_metrics:node_exporter_metrics.0] read error, check permissions: /host/sysfs/devices/system/cpu/cpu[0-9]*
```
More details:
```
Fluent Bit v3.2.1
* Copyright (C) 2015-2024 The …
```
=> node_exporter_metrics: Use real_path for complaining on glob error

plugins/in_opentelemetry/opentelemetry_prot.c
For some reason whoever first wrote the `in_opentelemetry` plugin's HTTP/2 codepaths wrote it in a way that no/null tags were what always got passed into the Fluentbit routing engine. This PR fixes up what should be the last remaining cases not passing the tag through - the metrics and trace cases of the HTTP/2 codepath specifically. Should fully fix #8734 (i.e. fix it for the (default!) HTTP/2 mode and not force users to use the HTTP/1 codepath to get this behaviour).
**Testing**
```yaml
service:
pipeline:
inputs:
- name: opentelemetry
tag_from_uri: true
http2: true
outputs:
- name: 'stdout'
match: 'v1_metrics'
- name: 'stdout'
match: 'v1_traces'
```
- [N/A] Documentation required for this feature - No
- This fix probably should be …
=> in_opentelemetry: Propogate tag in http2 metrics and trace handlers

plugins/filter_lua/lua.c
This PR implements a new global Lua Table that register the Fluent Bit Environment variables.
Fixes #9585
example:
```yaml
env:
A: aaa
B: bbb
C: ccc
service:
flush:           1
log_level:       info
pipeline:
inputs:
- name:    random
tag:     test
samples: 10
filters:
- name:  lua
match: "*"
call:  append_tag
code:  |
function append_tag(tag, timestamp, record)
new_record = record
new_record["my_env"] = FLB_ENV
return 1, timestamp, new_record
end
outputs:
- name:  stdout
match: "*"
```
output:
```
test: [[1731990257.781970977, {}], {"my_env"=>{"A"=>"aaa", "C"=>"ccc", "HOSTNAME"=>"monox-2.lan", "B"=>"bbb"}, "rand_value"=>4805047635809401856}]
```
e.g: `FLB_ENV['A']` access the string value `aaa`.
---- …
=> filter_lua: expose env variables in FLB_ENV Lua table

plugins/custom_calyptia/calyptia.c, plugins/custom_calyptia/calyptia.h, plugins/in_calyptia_fleet/in_calyptia_fleet.c, tests/runtime/CMakeLists.txt, tests/runtime/custom_calyptia_input_test.c
This change makes the custom calyptia plugin honour the configured collector
interval (both in secs and nanosecs) that is cascaded to the instantiated input fleet plugin.
Also, I took the chance to add unit test to validate the cascade of properties to the underlying
fleet plugin.
**Testing**
```ini
[SERVICE]
log_level trace
[CUSTOM]
Name calyptia
API_Key xxxx.xxxx
fleet_id e01085df-49d1-451d-b89f-226cd381369c
Calyptia_Host cloud-api.calyptia.com
fleet.interval_sec 120
```
----
=> custom_calyptia: honour collector interval in secs and nano secs.

plugins/out_stackdriver/stackdriver.c
This change fixes a bug in out_stackdriver that expired cached tokens are returned.
No issue number.
----
**Testing**
----
=> out_stackdriver bug fix: return cached token when current_timestamp is less than cached_expiration

include/fluent-bit/flb_http_client.h, include/fluent-bit/flb_lib.h, include/fluent-bit/flb_output.h, plugins/out_es/es.c, src/flb_http_client.c, src/flb_lib.c, src/flb_output.c, tests/runtime/data/es/json_es.h, tests/runtime/out_elasticsearch.c
We wanted to run unit testing for HTTP responses due to confirm this introduced mechanism should be validated on CI:
https://github.com/fluent/fluent-bit/pull/9236
Closes https://github.com/fluent/fluent-bit/issues/9260.
----
**Testing**
----
=> http_client: out_es: lib: implement http client response testing mechanism

src/flb_network.c
Addresses the issue of IPV6 addresses not being able to be stored properly, causing the connection to never by accepted and an endless loop occurring. 
Fixes #9053 
**Testing**
Tested on Windows 11.
Config input/output sections used:
[INPUT]
Name tcp
Chunk_Size 32
Format json
Listen [::1]
Port 5170
tag cs.systemmonitoring
[OUTPUT]
Name stdout
Format json_lines
json_date_format iso8601
json_date_key utc_timestamp
Match cs.systemmonitoring
Client app would open a TCP socket connection, send a json payload, then close the connection. Prior to this fix only IPV4 would work, using IPV6 would cause an endless loop. This fix will allow both IPV4 and IPV6 to work.
---- …
=> network: fix IPV6 handling for accepting connections

plugins/custom_calyptia/calyptia.c, plugins/custom_calyptia/calyptia.h, plugins/out_calyptia/calyptia.c, plugins/out_calyptia/calyptia.h, tests/runtime/CMakeLists.txt, tests/runtime/custom_calyptia_registration_retry_test.c
if register_retry_on_flush is set (default true, my proposal)0, agent registration is retried on each flush callback.
if set to false then registration will cause to abort the plugin initialisation.
**Testing**
Use with this configuration
```ini
[SERVICE]
[CUSTOM]
name                calyptia
api_key xxx
log_level           debug
calyptia_host       localhost
calyptia_port       5000
calyptia_tls        off
calyptia_tls.verify off
register_retry_on_flush false
```
 If set to true (my proposed default)
```
[2024/11/27 22:09:00] [ warn] [output:calyptia:calyptia.0] agent registration failed
[2024/11/27 22:09:00] [debug] [out flush] cb_destroy coro_id=0
[2024/11/27 22:09:00] [debug] [retry] new retry created for task_id=0 attempts=1
[2024/11/27 22:09:00] [ warn] [engine] …
```
=> out_calyptia: retry agent registration on flush callback

.github/workflows/unit-tests.yaml, CMakeLists.txt
Build with `-fsigned-char` on `aarch64` to resolve issue: https://github.com/fluent/fluent-bit/issues/8521
=> cmake: fix UNICODE-escaped characters on aarch64

src/wasm/flb_wasm.c
=> wasm: Plug a resource leak on exception (CID 508177)

plugins/in_winevtlog/winevtlog.c
Fix the `flags` argument of one of the calls to `EvtRender`. It's currently using a value of the [EVT_RENDER_CONTEXT_FLAGS ](https://learn.microsoft.com/en-us/windows/win32/api/winevt/ne-winevt-evt_render_context_flags) enum, which contains flags for creating the render context. This commit replaces it with the correct flag of the enum [EVT_RENDER_FLAGS](https://learn.microsoft.com/en-us/windows/win32/api/winevt/ne-winevt-evt_render_flags), which is also used on the prior call to determine the buffer size.
Since both enum values are 0, this minor mistake is unlikely to have caused any issues.
----
**Testing**
- …
=> in_winevtlog: Use correct flag for EvtRender

plugins/out_opentelemetry/opentelemetry.c, plugins/out_opentelemetry/opentelemetry.h
Fix a typo in out opentelemetry plugin
----
**Testing** …
=> Fix a typo in out opentelemetry plugin

include/fluent-bit/flb_cfl_ra_key.h, include/fluent-bit/flb_cfl_record_accessor.h, src/CMakeLists.txt, src/flb_cfl_ra_key.c, src/flb_cfl_record_accessor.c, tests/internal/CMakeLists.txt, tests/internal/cfl_record_accessor.c
Currently, we didn't implement CFL based record accessor. Which is also called as cobj.
This leads that we're not able to access nested cobjets in processor plugins.
To resolve this, I implemented cobj based record accessor and that infrastructure, cobj_ra_key.
In cobj based record accessor, the same mechanism of parser for record accessor syntax is able to use.
So, I didn't implement cobj specific parser of that syntax.
The main difference of the accessor is creating cobj based record accessor related sturct and use it there.
Other part is mostly copy and paste and then adjust for the operation of cobj.
----
**Testing**
The written down test …
=> cfl_record_accessor: cfl_ra_key: Implement generic CFL based record accessor

src/http_server/flb_hs.c
Fixes https://github.com/fluent/fluent-bit/issues/9423.
----
**Testing**
```ini
[SERVICE]
Flush        1
HTTP_Listen  fe80::c97:XXXX:XXXX:XXX%en0 # Put valid IPv6 address
HTTP_Port    2021
Enable_Hot_Reload On
Health_Check On
[INPUT]
Name dummy
Tag dummy.locals
[OUTPUT]
Name  stdout
Match *
```
```
______ _                  _    ______ _ _           _____  _____ 
|  ___| |                | |   | ___ (_) |         |____ |/ __  \
| |_  | |_ …
```
=> http_server: hs: Handle IPv4 and IPv6 addresses

src/flb_utils.c, tests/internal/utils.c
=> utils: Detect machine_id corruption and fill out a dummy value

.github/workflows/unit-tests.yaml, CMakeLists.txt, cmake/riscv64.cmake
Same as other platforms, we have to use signed char even if RISC-V 64bit(riscv64).
For testing on RISCV64, we can also use uraimo/run-on-arch-action action to set up with riscv64 emulator with qemu.
In my visionfive RISC-V 64bit board, I succeeded to pass signedness sensitive tests which are flb-it-pack and flb-it-utils.
This is also causing problems on AArch64 Linux.
And there is also occurring on RISCV64 Linux.
----
**Testing**
----
Fluent Bit is licensed under Apache 2.0, by submitting this pull …
=> build: Use signed char in RISC-V 64bit

README.md
=> docs: update deployment details

plugins/in_forward/fw.c, plugins/in_forward/fw.h
When in_forward is paused, the remaining connections are discarded and disposed.
The status check should be aligned and protected with mutex lock.
This causes SEGV when resuming from the pause status of in_forward.
This is because in_fw_collect checks the state of ctx->is_paused. And is_paused is FLB_TRUE, in_forward plugins just gives up to accept tcp connections.
I also added to prevent thread switching during the checking status of pausing/resuming.
Closes https://github.com/fluent/fluent-bit/issues/9443.
Closes https://github.com/fluent/fluent-bit/issues/9288.
----
**Testing**
```
[INPUT]
Name                forward
Listen …
```
=> in_forward: Recreate connection when resumed

src/flb_cfl_record_accessor.c
=> cfl_record_accessor: Plug resource leaks (CID 516097)

src/flb_plugin.c
For classic mode and yaml mode of plugins_file parser should differ because classic mode of plugins_file has key-value pair which includes Path and the real path by contrast yaml mode of plugins_file just contains array under plugins section. 
This should be caused by the difference between ini file and Yaml file syntax.
So, we need to detect the format of files when loading configurations for external plugins.
Closes https://github.com/fluent/fluent-bit/issues/9729.
----
**Testing**
For yaml:
```yaml
service:
plugins_file: plugins.yaml
pipeline:
inputs:
- name: random
- name: gdummy
outputs:
- name: stdout
match: '*'
``` …
=> plugin: Detect config format and use a proper loader

.github/workflows/call-build-linux-packages.yaml, .github/workflows/call-build-macos.yaml, .github/workflows/staging-release.yaml
Resolves issues with building on latest ubuntu 24 runners provided by Github.
Pinning to Ubuntu 22 for now to align with previous image working correctly until Github images stabilise.
macOS 12 is no longer available - just errors if you try to use it now so removed: https://github.com/actions/runner-images/issues/10721
This means no Intel builds available for macOS now, only Apple Silicon.
Resolves #9739.
----
**Testing**
----
=> workflows: resolve ubuntu 24 packaging problems

src/flb_plugin_proxy.c
Removes the code which prevented flush callback on Golang side during hot-reloading
Fixes #9733 
----
**Testing** …
=> plugin_proxy: Allow to execute flush callback on Golang side during hot-reloading

include/fluent-bit/flb_conditionals.h, src/CMakeLists.txt, src/flb_conditionals.c, tests/internal/CMakeLists.txt, tests/internal/conditionals.c
Implement the base API for conditionals evaluation using record accessor, this API
will be initially used by a specific log processor, but eventually this same interface can be used
as a generic conditional evaluation for processor.
This PR:
- Implements the supported conditional operators (AND/OR)
- Implements the supported rule operators (Listed below)
- Types
- Library public interface
- Unit testing covering all conditional and rule operators
The following are the operator types supported for conditions
```C
enum condition_operator { 
    COND_OP_AND,
    COND_OP_OR 
};
```
The following are the operator types supported for each rule
```C
enum flb_rule_operator {
FLB_RULE_OP_EQ,
FLB_RULE_OP_NEQ,
FLB_RULE_OP_GT,
FLB_RULE_OP_LT,
FLB_RULE_OP_REGEX,
FLB_RULE_OP_IN,
FLB_RULE_OP_NOT_IN
}; …
```
=> internal: add conditionals evaluation API

plugins/in_systemd/systemd.c
Fix a memory leak in the systemd input plugin.
If option "lowercase" was on, the temporary buffer to convert a key to the lower-case string was not freed.
Fixes #9769
----
**Testing**
---- …
=> in_systemd: fix memory leak

packaging/local-build-all.sh
Build config format has changes in this commit: https://github.com/fluent/fluent-bit/commit/e4c982757dbb67330eb0f50dc6eba6bbb153cefd#diff-c08c571600c3c85d24ce5e2af55959c64188e70844c69e941a2ea91ecd7691e1
this commit adjusts `local-build-all.sh` script to the new config format.
**Before:**
**After:**
A side note: Seems like a docker image is missing from public docker hub (or private docker registry not specified) `flb-amazonlinux/2.arm64v8`:
```
ERROR: failed to solve: arm64v8/amazonlinux:2: failed to resolve source metadata for docker.io/arm64v8/amazonlinux:2: no match for platform in manifest: not found
+ echo 'Error building main docker image flb-amazonlinux/2.arm64v8'
Error building main docker image flb-amazonlinux/2.arm64v8
+ exit 1
```
----
**Testing**
Before we can approve your …
=> Regression fix: Selects docker image target fpr local-build-all.sh

packaging/README.md, packaging/build-config.json, packaging/distros/raspbian/Dockerfile
I added raspbian/bookworm package on our packing system.
Related to https://github.com/fluent/fluent-bit/issues/9730.
----
**Testing**
----
=> packaging: raspbian:  support raspbian bookworm package creation

plugins/out_stackdriver/stackdriver.c, plugins/out_stackdriver/stackdriver.h, plugins/out_stackdriver/stackdriver_conf.c
Add the `Cloud_Logging_Base_Url` configuration option to the `out_stackdriver` plugin. This feature is to support alternate `universe_domain`s in the output plugin. A majority of users will never need to change this.
----
**Testing**
```
[INPUT]
Name dummy
[OUTPUT]
Name stackdriver
Match *
Cloud_Logging_Base_Url https://www.logging-other.com
```
Please refer to the Valgrind output below. In that output, I used a universe domain that doesn't exist; I don't have an effective way to test an alternate universe domain at the moment. I also tested with `https://logging.googleapis.com` manually set through the config to still test the config building …
=> stackdriver: add cloud_logging_base_url

CODEOWNERS
Due to some changes in the team at Google, we have decided to adjust the codeowners for the `out_stackdriver` plugin. Since @qingling128 and @igorpeshansky have transitioned to new teams not involved with the plugin, we have decided to remove them from CODEOWNERS so they don't need to deal with the context switching it would require. In their place we are adding @jefferbrecht and @JeffLuoo, who have both been working with Fluent Bit as long or longer than I have and have lots of necessary context to be able to review `out_stackdriver` PRs. We are hoping to add more in the future.
=> CODEOWNERS: change out_stackdriver code owners

plugins/in_systemd/systemd.c
Fix for #9788 buffer over-reads in the systemd input plugin.
In systemd_enumerate_data_store: when copying the item value the input string may not be 0-terminated, so relying on strlen may lead to reads beyond the end of the buffer. Use the known string length instead of strlen.
----
**Testing** …
=> in_systemd: fix buffer over-read

.github/workflows/skipped-unit-tests.yaml, .github/workflows/unit-tests.yaml, tests/runtime_shell/custom_calyptia.sh
Resolve issue with macOS framework failing on cleanup.
Fixed an issue with `*.sh` changes not running unit tests.
----
**Testing**
----
=> tests: runtime_shell: custom_calyptia prevent fail on macOS at cleanup

.github/workflows/call-build-macos.yaml
=> workflows: macos: Build Intel Mac packages by macos-14-large runner

plugins/in_ebpf/CMakeLists.txt, src/CMakeLists.txt
When enabling in_ebpf plugin, we encountered that the skeletons are not existing before proper timing to scan the header dependencies. This leads missing headers for in_ebpf and causes compilation errors especially we use parallel building for 2 or more numbers on `-j` option in make.
This PR fixes such dependency glitches.
----
**Testing**
----
=> in_ebpf: core: Prepare eBPF skeletons before starting to compile in_ebpf plugin properly

src/flb_pack.c
Make JSON parser work with uppercase E when numbers are in scientific notation format. Also support scientific notation with positive exponent, not only negative.
Fixes #7113, improves on #2746.
----
**Testing** …
=> pack: fix missing scientific notation in JSON parser [Backport 3.2]

src/flb_pack.c
Make JSON parser work with uppercase E when numbers are in scientific notation format. Also support scientific notation with positive exponent, not only negative.
Fixes #7113, improves on #2746.
Backported to 3.2: #9853.
----
**Testing** …
=> pack: fix missing scientific notation in JSON parser

dockerfiles/Dockerfile, dockerfiles/Dockerfile.centos7, packaging/distros/amazonlinux/Dockerfile, packaging/distros/centos/Dockerfile, packaging/distros/debian/Dockerfile, packaging/distros/raspbian/Dockerfile, packaging/distros/ubuntu/Dockerfile
This is because libkafka's SASL OAUTHBEARER mechanism depends on libcurl and OpenSSL.
We already installed a development package of OpenSSL in each of building containers but we didn't install a development package of libcurl.
This leads for degraded usability for rdkafka library and it makes not to be able to use SASL OAUTHBEARER mechanism on kafka plugins like below with #9859 patch:
```
[2025/01/22 11:55:30] [error] [flb_kafka] cannot configure 'sasl.oauthbearer.method' property with error: 'Configuration property "sasl.oauthbearer.method" not supported in this build: OAuth/OIDC depends on libcurl and OpenSSL which were not available at build time'
[2025/01/22 11:55:30] [error] [flb_kafka] cannot configure 'sasl.oauthbearer.client.id' property with error: 'Configuration property …
```
=> package: distro: dockerfiles: Install libcurl development package for oauthoicd on rdkafka

.github/workflows/cron-unstable-build.yaml
Update to build 3.2 branch daily/nightly and remove unsupported regular builds.
We build master twice daily now to pick up changes more often.
=> workflows: update daily builds for 3.2

.github/workflows/call-build-images.yaml
Hitting errors building for release all the platforms so increasing the size of the runner to help.
=> workflows: increase size of container builders

.github/workflows/staging-build.yaml
Resolving config failures for release by disabling unsupported image platforms.
=> workflows: remove s390x and armv7 platforms for container builds

packaging/update-apt-repo.sh
Resolves #9878 by ensuring we skip repos with no files in, i.e. not built in this case for 3.2.
----
**Testing**
----
=> packaging: skip empty repos

.github/workflows/call-build-images.yaml
Resolves #9881 typo in debug image creation which made them use production digests instead.
----
**Testing**
----
=> workflows: fix debug image manifest

plugins/in_opentelemetry/opentelemetry_prot.c
=> in_opentelemetry: fix finalization of group for gRPC payload (backport for v3.2)

plugins/in_opentelemetry/opentelemetry_prot.c
This PR fixes the finalization of a Log record group when the data comes from a gRPC/protobuf payload.
----
=> in_opentelemetry: fix finalization of group for gRPC payload

tests/runtime/in_kubernetes_events.c
use multiple tries and wait for output in `in_kubernetes_events` tests, similar to the `in_simple_systems` and `out_http` tests.
----
**Testing**
----
=> tests: in_kubernetes_events: try/wait for output to make tests less flakey, re #9570.

plugins/in_calyptia_fleet/in_calyptia_fleet.c
When working with large numbers of unattended servers, it is very useful to know for sure when they have pulled what version of fleet config. Currently the only way that the pull of a new version can be known is by second-hand inference of the "changing to config dir" log messages, which aren't a reliable source for this anyway as they are always logged on Fluentbit startup.
**Testing**
Documentation not required for this feature
----
=> in_calyptia_fleet: log info about config pulled from API

.github/workflows/call-build-images.yaml, .github/workflows/call-test-images.yaml
There are failures building for s390x, possibly down to emulation issues, and it is extending build times significantly so removing this target for now.
Unit tests and other support is left in, this is purely for release purposes.
=> workflows: disable s390x container builds for release

include/fluent-bit/flb_log.h, src/flb_log.c
This PR addresses the deadlock reported in issue #9667 by adding a new management signal type used to interrupt the log worker poll operation when a new log client pipe is created.
=> log: added a new management signal to overcome a dedadlock

.github/workflows/call-build-images.yaml, .github/workflows/call-build-linux-packages.yaml
Remove usage of QEMU as no longer required and seems to be causing failures to set up.
----
**Testing**
----
=> workflows: remove qemu usage

lib/ctraces/.github/workflows/build.yaml, lib/ctraces/.github/workflows/lint.yaml, lib/ctraces/.github/workflows/packages.yaml, lib/ctraces/CMakeLists.txt, lib/ctraces/include/ctraces/ctr_link.h, lib/ctraces/include/ctraces/ctr_span.h, lib/ctraces/src/ctr_decode_msgpack.c, lib/ctraces/src/ctr_decode_opentelemetry.c, lib/ctraces/src/ctr_encode_msgpack.c, lib/ctraces/src/ctr_encode_text.c, lib/ctraces/src/ctr_link.c, lib/ctraces/src/ctr_span.c, plugins/in_opentelemetry/CMakeLists.txt, plugins/in_opentelemetry/opentelemetry_prot.c, plugins/in_opentelemetry/opentelemetry_traces.c, plugins/in_opentelemetry/opentelemetry_traces.h, plugins/in_opentelemetry/opentelemetry_utils.c, plugins/in_opentelemetry/opentelemetry_utils.h
This PR add support to receive Traces in JSON-Otel schema and also upgrades CTraces to v0.6.0
----
=> in_opentelemetry: add support for OpenTelemetry JSON traces

plugins/out_opentelemetry/opentelemetry.c, plugins/out_opentelemetry/opentelemetry.h, plugins/out_opentelemetry/opentelemetry_conf.c
Previously, enabling gRPC required setting both `grpc: on` and `http2: on`. For plaintext communication, users had to set `http2: force`, which was confusing.
This change simplifies the config:
- `grpc: on` now automatically enables HTTP/2.
- Plaintext gRPC works without needing `http2: force`.
This PR improves usability by reducing unnecessary config steps.
----
=> out_opentelemetry: auto configure HTTP/2 protocol when gRPC is enabled

include/fluent-bit/flb_log.h, src/flb_log.c
This PR addresses the deadlock reported in issue #9667 by adding a new management signal type used to interrupt the log worker poll operation when a new log client pipe is created.
=> log: added a new management signal to overcome a deadlock

plugins/in_kubernetes_events/kubernetes_events.c
Use correct precision of timestamps during in_kubernetes_events sqldb cleanup.
Fixes #9787 
----
**Testing**
----
=> in_kubernetes_events: fix sqldb cleanup

plugins/out_stackdriver/stackdriver.c, plugins/out_stackdriver/stackdriver.h, plugins/out_stackdriver/stackdriver_conf.c
Backport of #9779 to 3.2 release branch. See original PR for description.
=> stackdriver: add cloud_logging_base_url (#9779)

src/flb_input_chunk.c
it's more useful to see the plugin alias than the name
----
=> input_chunk: log plugin alias instead of plugin name if exists.

include/fluent-bit/flb_conditionals.h, src/flb_conditionals.c, tests/internal/conditionals.c
Fix for #9959 
Implement the NOT_REGEX operator in the conditional evaluation API to support pattern exclusion operations. 
This PR:
- Adds NOT_REGEX to the supported rule operators
- Implements pattern negation functionality
- Add unit tests for NOT_REGEX operator
- Maintains backward compatibility
Added NOT_REGEX to the supported rule operators:
```c
enum flb_rule_operator {
FLB_RULE_OP_EQ,
FLB_RULE_OP_NEQ,
FLB_RULE_OP_GT,
FLB_RULE_OP_LT,
FLB_RULE_OP_REGEX,
FLB_RULE_OP_NOT_REGEX,  /* New operator */
FLB_RULE_OP_IN,
FLB_RULE_OP_NOT_IN
};
```
Added test cases covering:
- Basic NOT_REGEX operations
- Unicode/non-ASCII handling
- Pattern boundary conditions
- Special characters handling
- Empty strings and patterns
- Long string edge cases
- Multiple rules combination
- Border cases
All …
=> internal: add NOT_REGEX operator to conditional processing

plugins/in_splunk/splunk_conn.c
When buffer reallocation occurs in HTTP/1.1 connections, parsed header references become invalid since they point to locations in the old buffer. This causes memory corruption and crashes when later accessing those headers.
Add splunk_conn_realloc_and_reparse() function that:
- Performs buffer reallocation
- Resets parser state
This ensures no dangling pointers exist after reallocation, preventing crashes at the cost of reparsing. A proper fix using offsets instead of pointers will be implemented in mk_http_parser in a future change.
Fixes #9964 
See #9964 
```
[ikslabdein@toolbox repro]$ ./main -payload=payload.json -rps=1 -token=AAAA-AAAA-AAAA-AAAA -endpoint=http://localhost:9393/services/collecto
r/event
Response was 200
Response was 200
```
```
record token before: 	{
SPLUNK_HEC_TOKEN …
```
=> in_splunk: fix memory corruption by resetting parser after reallocation

plugins/in_kubernetes_events/kubernetes_events.c
*Note* this is a backport of #9894 
Use correct precision of timestamps during in_kubernetes_events sqldb cleanup.
Fixes #9787 
----
**Testing**
----
=> in_kubernetes_events: fix sqldb cleanup (backport to v3.2)

tests/runtime/in_kubernetes_events.c
Backport the test fix in #9877 to the 3.2 series.
----
**Testing**
----
=> tests: in_kubernetes_events: backport flake test fix from #9877.

plugins/in_elasticsearch/in_elasticsearch_bulk_conn.c, plugins/in_http/http_conn.c, plugins/in_opentelemetry/http_conn.c, plugins/in_prometheus_remote_write/prom_rw_conn.c, plugins/in_prometheus_remote_write/prom_rw_prot.c, plugins/in_splunk/splunk_conn.c
=> http input layer: fix parser state after memory reallocation

plugins/in_elasticsearch/in_elasticsearch_bulk_conn.c, plugins/in_http/http_conn.c, plugins/in_opentelemetry/http_conn.c, plugins/in_prometheus_remote_write/prom_rw_conn.c, plugins/in_prometheus_remote_write/prom_rw_prot.c, plugins/in_splunk/splunk_conn.c
=> http input layer: parser realloc fixes (#9970)

plugins/in_http/http_prot.c
Add compression support for GZip, Snappy and ZSTD in HTTP/1.x connections
----
=> in_http: add compression handling support for gzip, snappy and zstd

CMakeLists.txt
Check for clang compiler during building ebpf.
Currently the doc doesn't mention clang dependency explicitly : https://docs.fluentbit.io/manual/pipeline/inputs/ebpf
Doc fix : https://github.com/fluent/fluent-bit-docs/pull/1570
=> bug-fix : Check for clang build dependency when building ebpf

plugins/in_http/http_prot.c
=> in_http: add compression handling support for gzip, snappy and zstd (backport v3.2)

src/flb_input_chunk.c
=> input_chunk: log plugin alias instead of plugin name if exists. - backport to 3.2

CODEOWNERS
This commit adds Cam (@sparrc), Anuj (@singholt), and Swapneil (@swapneils) as code-owners for the AWS-related code files.
----
=> CODEOWNERS: add AWS code-owners for AWS-related files

include/fluent-bit/flb_http_client.h, plugins/out_http/http.c, plugins/out_http/http.h, plugins/out_http/http_conf.c, src/flb_http_client.c
=> out_http: add support for zstd and snappy compression (backport for v3.2)

plugins/in_opentelemetry/opentelemetry_prot.c, plugins/in_prometheus_remote_write/prom_rw_prot.c
Backport of https://github.com/fluent/fluent-bit/pull/9993
Provides fixes for OpenTelemetry and Prometheus Remote Write inputs associated to:
https://github.com/advisories/GHSA-x9j4-33qm-hgjp
https://github.com/advisories/GHSA-4g89-mg9x-4chc
----
=> security update: CVE-2024-50608 and CVE-2024-50609 (v3.1)

.github/workflows/call-build-linux-packages.yaml
Resolves #9941 failures with Raspbian builds missing QEMU due to https://github.com/fluent/fluent-bit/pull/9931
See https://github.com/docker/setup-qemu-action/issues/198 and https://github.com/tonistiigi/binfmt/issues/240 which both suggest we have to pin QEMU version now for all runners from ubuntu 22+ (all of them basically).
----
**Testing**
----
=> workflows: pin QEMU version for Raspbian only

packaging/update-apt-repo.sh
When using unattended-upgrades at least the origin meta data in the release file shoulb be unique across all registered package repos in addition it's also good to set the label to something that clearly identifies the software source.
With this commit the published Release file will look like this:
Origin: packages.fluentbit.io
Label: fluent-bit
Suite: bookworm
Codename: bookworm
Add correct meta data to release file
n/a
----
**Testing**
- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or …
=> bug-fix: Set correct and unique repo meta data

plugins/in_opentelemetry/opentelemetry_logs.c
Groups encoding where not closing the msgpack map header, additionaly once the group header was finished instead of closing it we were appending the group finalization record (-2).
----
=> in_opentelemetry: fix groups encoding by closing headers properly

tests/internal/conditionals.c
In non-Western Windows environment, especially cp932 (Shift-JIS) environment of Windows, cl.exe complains continuous lines but this should be caused character encoding glitches.
This should be fixed by BOM at the top of the source files. This issue should be happened if the files contain non-ASCII characters such as AccsantGrave or other symbols or multibytes characters could cause this type of issue.
```
[ 98%] Building C object tests/internal/CMakeFiles/flb-it-conditionals.dir/conditionals.c.obj
conditionals.c
C:\Users\cosmo\Documents\GitHub\fluent-bit\tests\internal\conditionals.c(905): warning C4819: ファイルは、現在のコード  ページ (932) で表示できない文字を含んでいます。データの損失を防ぐために、ファイルを Unicode 形式で保存してください。
C:\Users\cosmo\Documents\GitHub\fluent-bit\tests\internal\conditionals.c(1384): error C2001: 定数が 2 …
```
=> internal: test: conditional: Add Byte-Order-Mark(BOM) for non western Windows environments

plugins/out_http/http.c
=> out_http: fix logic to handle status of compressed payloads (fix #10016)

plugins/out_http/http.c
=> out_http: fix logic to handle status of compressed payloads (fix #10016 - 3.2)

src/flb_cfl_ra_key.c, src/flb_ra_key.c, tests/internal/cfl_record_accessor.c, tests/internal/record_accessor.c
This PR fixes an issue where the Record Accessor API couldn't handle direct array access patterns like `$array[0]`.
The fix changes the condition that checks if a lookup succeeded by replacing `!found` with `matched == 0`, which properly tracks array element access.
Added test cases to verify array access works:
- Direct array access (`$array[0]`)
- Nested array access (`$matrix[1][2]`) 
- Mixed array and map access (`$records[1]['name']`)
- Handling of edge cases (out-of-bounds indices, nonexistent keys, type mismatches)
Fixes #9958
```
pipeline:
inputs:
- name: dummy
dummy: '{"array": ["a", "b", "c"]}'
outputs:
- name: stdout
match: "*"
processors:
logs:
- name: calyptia
actions:
- type: put
opts:
key: "worked"
value: "true"
condition:
operator: AND
rules:
- field: "$array[1]"
operator: …
```
=> ra: add support for direct array access notation 

.github/workflows/staging-release.yaml
Resolves errors seen in latest 3.2.8 release: https://github.com/fluent/fluent-bit/actions/runs/13650214544/job/38158253394
- Windows binaries not sync'd to expected location
- Old version of Cosign fails with TUF errors: https://blog.sigstore.dev/tuf-root-update/
- Version update PR using `master` instead of `3.2`: https://github.com/fluent/fluent-bit/pull/10038
=> workflows: update release with minor fixes

packaging/update-apt-repo.sh
Reverts fluent/fluent-bit#9949 as it is causing problems for existing users: #10042
=> packaging: revert apt repo origin/label info.

include/fluent-bit/flb_log_event.h, include/fluent-bit/flb_log_event_decoder.h, plugins/out_splunk/splunk.c, plugins/out_stdout/stdout.c, src/flb_log_event_decoder.c, tests/runtime/in_opentelemetry.c
This PR adds OTLP metadata support to the splunk output plugin and it improves the way in which group metadata is exposed to client code to prevent unintended meta records from being pushed to endpoints that do not expect them.
Technical notes : 
In this PR the log event decoder component has been modified to prevent unsuspecting plugins from receiving meta records that hold group attributes. In order to achieve this the default value of `read_groups` has been changed to `FLB_FALSE` and its meaning reinterpreted to mean that the client code wants raw access to group metadata records rather than having the decoder transparently providing access to the information while not delivering them directly through `flb_log_event_decoder_next`.
What this means is that while the client code iterates …
=> out_splunk: added otlp metadata support

src/flb_input_thread.c
Resolves segmentation faults on exit for --dry-run calls.
=> input_thread: added missing sanity check (backport)

docker_compose/loki-grafana-structured_metadata_map/README.md, docker_compose/loki-grafana-structured_metadata_map/config/fluent-bit_loki_out-structured_metadata_map.yaml, docker_compose/loki-grafana-structured_metadata_map/config/grafana/provisioning/datasources/datasource.yml, docker_compose/loki-grafana-structured_metadata_map/config/loki-config.yaml, docker_compose/loki-grafana-structured_metadata_map/docker-compose.yml, plugins/out_loki/loki.c, plugins/out_loki/loki.h, tests/runtime/out_loki.c
Resolves #9463 
* Adds stuctured_metadata_map_keys config to dynamically populate stuctured_metadata from a map
The below is the results for running this with `/docker_compose/loki-grafana-structured_metadata_map/`, which has input
```json
{
"message": "simple log generated",
"logger": "my.logger",
"level": "INFO",
"hostname": "localhost",
"my_map_of_attributes_1": {
"key_1": "hello, world!",
"key_2": "goodbye, world!"
},
"my_map_of_maps_1": {
"root_key": {
"sub_key_1": "hello, world!",
"sub_key_2": "goodbye, world!"
}
}
}
``` 
I used the following to query Loki: `curl http://localhost:3100/loki/api/v1/query_range --data-urlencode 'query={service_name="test"}' --data-urlencode 'limit=1'  --data-urlencode 'step=5' | jq '.data.result'`
This is the output with the option enabled. As you can …
=> out_loki: add stuctured_metadata_map_keys

docker_compose/loki-grafana-structured_metadata_map/README.md, docker_compose/loki-grafana-structured_metadata_map/config/fluent-bit_loki_out-structured_metadata_map.yaml, docker_compose/loki-grafana-structured_metadata_map/config/grafana/provisioning/datasources/datasource.yml, docker_compose/loki-grafana-structured_metadata_map/config/loki-config.yaml, docker_compose/loki-grafana-structured_metadata_map/docker-compose.yml, plugins/out_loki/loki.c, plugins/out_loki/loki.h, tests/runtime/out_loki.c
Resolves https://github.com/fluent/fluent-bit/issues/9463
* Adds stuctured_metadata_map_keys config to dynamically populate stuctured_metadata from a map
This is a PR to backport #9530 
----
**Testing**
https://github.com/fluent/fluent-bit-docs/pull/1527
----
=> out_loki: add stuctured_metadata_map_keys (3.2.x Backport)

plugins/in_opentelemetry/opentelemetry_logs.c
=> in_opentelemetry: logs: add missing checks for resource and scope

plugins/in_opentelemetry/opentelemetry_logs.c
=> in_opentelemetry: logs: add missing checks for resource and scope (backport 3.2)

plugins/out_opentelemetry/opentelemetry_logs.c
backport of https://github.com/fluent/fluent-bit/pull/10080
----
=> out_opentelemetry: restored old group meta record processing mechanism (backport)

tests/runtime/filter_grep.c, tests/runtime/filter_modify.c, tests/runtime/filter_record_modifier.c, tests/runtime/in_syslog.c, tests/runtime/out_kinesis.c
When calling `pthread_join(2)` on an invalid or even NULL `tid` the address sanitizer on macOS will raise an issue and crash fluent-bit. This has the effect on causing failures in CI.
----
**Testing**
----
=> tests: fix tests that call pthread_join on stopped contexts and crash on macos.

.github/workflows/staging-release.yaml
Fixes #10085, checksum calculation is all assuming the `/windows` directory only. Instead we were overwriting the installers with the `/windows/<version/` files which have a slightly different checksum.
Later `staging-release-windows-checksums` job needs them as well:
```shell
aws s3 sync "s3://${{ secrets.AWS_S3_BUCKET_RELEASE }}/windows" ./ --exclude "*" --include "*.sha256"
```
The change was introduced as part of #10040 to resolve failures seen with missing files in that checksum job. The files should not be missing though: staging build should create them and we should sync them here fine.
----
**Testing**
If this is a change to packaging …
=> workflows: remove invalid sync directory

plugins/out_opentelemetry/opentelemetry.c
We have received many reports that Fluent Bit cannot send data to the OpenTelemetry Collector over a plain text communication, this is happening because we enabled http2 by default so when the Otel Collector receives the request (PRI * HTTP/2.0...) it drops the connection.
This PR switches http2 default to off so users don't run into this problem.
----
=> out_opentelemetry: switch config property 'http2' default to 'off'

plugins/out_opentelemetry/opentelemetry.c
(backport of #10089 to 3.2 branch)
We have received many reports that Fluent Bit cannot send data to the OpenTelemetry Collector over a plain text communication, this is happening because we enabled http2 by default so when the Otel Collector receives the request (PRI * HTTP/2.0...) it drops the connection.
This PR switches http2 default to off so users don't run into this problem.
----
=> out_opentelemetry: switch config property 'http2' default to 'off' (backport 3.2)

include/fluent-bit/flb_log_event.h, include/fluent-bit/flb_log_event_decoder.h, plugins/out_splunk/splunk.c, plugins/out_stdout/stdout.c, src/flb_log_event_decoder.c, tests/runtime/in_opentelemetry.c
backport of https://github.com/fluent/fluent-bit/pull/10035/
----
=> out_splunk: added otlp metadata support (backport 3.2)

lib/ctraces/.github/workflows/build.yaml, lib/ctraces/.github/workflows/packages.yaml, lib/ctraces/CMakeLists.txt, lib/ctraces/CODEOWNERS, lib/ctraces/include/ctraces/ctr_span.h, plugins/in_opentelemetry/opentelemetry_traces.c
- fix handling of status code in JSON traces
- upgrade to CTraces v0.6.1 (fix typo)
----
=> in_opentelemetry: fix handling of status code in JSON traces

lib/ctraces/.github/workflows/build.yaml, lib/ctraces/.github/workflows/packages.yaml, lib/ctraces/CMakeLists.txt, lib/ctraces/CODEOWNERS, lib/ctraces/include/ctraces/ctr_span.h, plugins/in_opentelemetry/opentelemetry_traces.c
backport of https://github.com/fluent/fluent-bit/pull/10091
- fix handling of status code in JSON traces
- upgrade to CTraces v0.6.1 (fix typo)
----
=> in_opentelemetry: fix handling of status code in JSON traces (backport 3.2)

.github/workflows/call-build-images.yaml, .github/workflows/pr-package-tests.yaml
When running package tests for a PR, if that PR comes from a fork then it is unable to get a GITHUB_TOKEN with permissions to push the image: https://github.com/fluent/fluent-bit/pull/6792#issuecomment-2739821295
We are therefore tweaking the PR workflow to only build the image rather than push it so we verify that it builds fine but we do not get spurious failures for contributions via forks.
----
=> workflows: support optional image pushing

src/flb_record_accessor.c
Fix return value for `flb_ra_get_kv_pair` when `get_ra_parser` fails.
When a record accesor is created but has no hints, usually because it is invalid or truncated, it will be generated without any hints. When that happens the call `get_ra_parser` fails. The function `flb_ra_get_kv_pair` calls `get_ra_parser` as well as `flb_ra_key_value_get`. If `get_ra_parser` fails it returns FLB_FALSE but the function returns the value of `flb_ra_key_value_get` directly which returns 0 on success and -1 on failure.
All of this weird, unexpected behaviour casues a failure in the `structured_metadata_map_invalid_ra_key` test in the `flb-rt-out_loki` test binary.
To remedy the situation I updated the documentation for `flb_ra_get_kv_pair` as well as updated the return value when failing `get_ra_parser` …
=> record_accesor: fix return value for flb_ra_get_kv_pair when get_ra_parser fails.

.github/workflows/call-build-images.yaml
Resolves issue seen with #10106 due to the `outputs` line actually controlling image push.
----
**Testing**
----
=> workflows: fix optional image pushing

src/flb_record_accessor.c
Backport of `record_accesor: fix return value for flb_ra_get_kv_pair when get_ra_parser fails` #10105 
#10105 
----
**Testing**
----
=> record_accesor: fix return value for flb_ra_get_kv_pair when get_ra_parser fails (Backport) 

src/flb_input_chunk.c
There seems to be a logical flaw in looking for new chunks when checking `storage.total_limit_size`.
This PR hopes to solve this logical error.
----
**Testing**
----
=> input_chunk: check return values when calculating found chunks for new space.

include/fluent-bit/flb_aws_credentials.h, include/fluent-bit/flb_aws_util.h, include/fluent-bit/flb_utils.h, src/aws/flb_aws_credentials.c, src/aws/flb_aws_credentials_http.c, src/aws/flb_aws_util.c, src/flb_utils.c, tests/internal/aws_credentials_http.c, tests/internal/data/aws_credentials/container_authorization_token.txt, tests/internal/utils.c
Fluent Bit will not publish telemetry to CloudWatch when only EKS pod identity credential is present. This is because it does not use EKS pod identity as part of its credential provider chain. 
We are making a change to Fluent Bit's AWS HTTPS credential functions to use the token provided in environment variable `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE` which is injected by EKS Pod Identity webhook to query endpoint specified in `AWS_CONTAINER_CREDENTIALS_FULL_URI` environment variable to retrieve STS credentials.
This PR is a replica of https://github.com/fluent/fluent-bit/pull/9206 but merging the changes from @PettitWesley and @edsiper and also making the post-merge changes compatible with master branch.
Address https://github.com/fluent/fluent-bit/issues/8550
---- …
=> aws: add support for EKS Pod Identity

src/flb_processor.c
Fixes #10101
In a recent change, the read_groups flag was set to false to avoid issues with plugins who don't understand groups. This patch fixes the case for processors (logs) making reading groups the default.
----
=> processor: fix missing read_groups flags for log event decoder

src/flb_processor.c
=> processor: fix missing read_groups flags for log event decoder (backport for 3.2)

plugins/out_splunk/splunk.c
This PR ensures that OpenTelemetry resource attributes are properly included when packaging OTLP metadata. Previously, these attributes were omitted from the final `fields` value.
----
=> out_splunk: when packing OTel metadata, include resource attributes

include/fluent-bit/flb_custom.h, src/flb_custom.c, src/flb_reload.c
Add support for downstream and upstream `net.*` properties for custom calyptia plugins.
Add support for either downstream or upstream net properties, ie: net.dns.mode, etc... for custom plugins. This support is activated by setting the custom plugin flag FLB_CUSTOM_NET_CLIENT or FLB_CUSTOM_NET_SERVER. At the moment custom plugins can only accept either downstream or upstream properties, not both.
----
**Testing**
---- …
=> custom: add support for net properties to custom plugins.

include/fluent-bit/flb_input.h, src/flb_help.c, src/flb_input.c
Add support for upstream configuration for client input plugins.
Client side input plugins like in_health and in_kubernetes_events use the upstream API but the property check for input plugins only applies downstream configuration checks. This pull request checks the plugin flags to see which one applies, either the downstream or upstream configuration map.
I have not added a check to make sure that not both flags, FLB_INPUT and FLB_INPUT_SERVER, are set on a plugin. In this case the downstream configuration map would be used. There should probably be a check, earlier than `flb_input_net_property_check`, that actually checks that both flags are not set.
----
**Testing**
Before we can approve your change; please submit …
=> input: add support for upstream configuration for input client plugins.

plugins/out_exit/exit.c
This PR adds two new parameters to the `out_exit` plugin:
- record_count: exit after a set number of records.
- time_count: exit after a set number of seconds have elapsed (within a flush).
Here is a run for each different mode:
fush_count:
```
$ valgrind ./bin/fluent-bit -i dummy -o exit -p flush_count=5 -f 1
==225327== Memcheck, a memory error detector
==225327== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==225327== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==225327== Command: ./bin/fluent-bit -i dummy -o exit -p flush_count=5 -f 1
==225327==
Fluent Bit v3.0.0
___________.__                        __ …
```
=> out_exit: add time_count (seconds) and record_count parameters for out_exit.

include/fluent-bit/flb_input.h, include/fluent-bit/flb_output.h, include/fluent-bit/tls/flb_tls.h, src/flb_input.c, src/flb_output.c, src/tls/flb_tls.c, src/tls/openssl.c
This PR introduces three new TLS configuration options for both input and output plugins:
- `tls.min_version`: specifies the minimum allowed TLS version (e.g., TLSv1.1, TLSv1.2).
- `tls.max_version`: specifies the maximum allowed TLS version (e.g., TLSv1.2, TLSv1.3).
- `tls.ciphers`: allows users to define a specific set of TLS ciphers (up to TLSv1.2).
The options are added to the input/output configuration map and respected during TLS context initialization. This enhances TLS flexibility and allows better control over security compliance and compatibility with external systems.
----
=> tls: add support for setting min/max TLS version and cipher list

.github/workflows/call-build-images.yaml, dockerfiles/Dockerfile.windows
Resolves #10110 by optimising the Windows container build to remove unnecessary build targets and ensure we build in release mode.
Previously we were building the shared library and examples, along with debug symbols. None of which are required or done by the Linux builds.
----
**Testing**
----
=> windows: disable unused build targets and optimise container

plugins/in_kafka/in_kafka.c, plugins/in_kafka/in_kafka.h
Set the Kafka poll timeout based on execution mode:
(Note: The fix is based on what's suggested in #9625)
1. Running in the main event loop (non-threaded):
- Use a minimal timeout (1ms) to avoid blocking other inputs.
3. Running in a dedicated thread:
-  Optimize for throughput by allowing Kafka's internal batching.
-  Align with 'librdkafka.fetch.wait.max.ms' (default: 500ms) to maximize batch efficiency.
-  Set timeout slightly higher than 'librdkafka.fetch.wait.max.ms' (e.g., 1.5x - 2x) to ensure it does not interfere with Kafka’s fetch behavior, while still keeping the consumer responsive.
Fixes #8030.
----
**Testing**
Tested locally with the config `poll_timeout_ms` option.
```
[INPUT]
Name        kafka
Tag …
```
=> in_kafka: optimize poll timeout handling for threaded and main event loop modes

include/fluent-bit/flb_config.h, include/fluent-bit/flb_task.h, src/flb_config.c, src/flb_engine.c, src/flb_task.c, tests/internal/CMakeLists.txt, tests/internal/task_map.c
This PR modifies the `task_map` member of the global context structure (`struct flb_config`) to make its size dynamic, adds a new field named `task_map_size` to track its size and ancillary functions `flb_config_task_map_resize` and `flb_config_task_map_grow` to manage its size.
With these changes we overcome the 2048 concurrent task limit previously imposed by the static array size.
=> task_map: added task map scaling

include/fluent-bit/flb_mp_chunk.h, include/fluent-bit/flb_processor.h, src/flb_cfl_record_accessor.c, src/flb_conditionals.c, src/flb_config_map.c, src/flb_mp.c, src/flb_processor.c, tests/internal/CMakeLists.txt, tests/internal/config_map.c, tests/internal/processor_conditional.c, tests/runtime_shell/CMakeLists.txt, tests/runtime_shell/processor_conditional.sh
Fix #10127
This PR adds conditional processing support for logs in processors. This feature allows processors to conditionally process logs based on field values.
1. Simple
```yaml
service:
pipeline:
inputs:
- name: dummy
dummy: '{"request": {"method": "GET", "path": "/api/v1/resource", "headers": {"Authorization": "Bearer valid-token"}, "access": "granted"}}'
tag: error.msg
processors:
logs:
action: insert
key: modified_if_post
value: true
condition:
op: and
rules:
- field: "$request['method']"
op: eq
value: "POST"
action: insert
key: modified_if_get
value: true
condition:
op: and
rules:
- field: "$request['method']"
op: eq
value: "GET"
outputs:
- name: stdout
match: '*'
```
When this configuration runs, the processor only …
=> processor: add conditional processing support for logs

plugins/processor_labels/labels.c, tests/runtime/CMakeLists.txt, tests/runtime/processor_labels.c
Label processors allow to manipulate the labels from metrics, this PR extends the actions `insert`, `update` and `upsert` to support a record accessor pattern that helps to use the `$TAG` variable that can be populated dinamically, e.g:
```yaml
service:
flush: 1
pipeline:
inputs:
- name: event_type
type: metrics
tag: my_test
processors:
metrics:
- name: labels
upsert: tag $TAG
outputs:
- name: stdout
match: '*'
```
Fluent Bit output:
```
______ _                  _    ______ _ _             ___  _____ 
|  ___| |                | |   | ___ (_) |           /   ||  _  |
| |_  | |_   _  ___ _ __ | |_  | |_/ /_| |_  __   __/ /| || |/' |
|  _| | | | | |/ _ \ '_ \| __| | ___ \ | __| \ \ / / /_| ||  /| |
| |   | | |_| |  __/ | | | |_  | |_/ / | |_   \ V /\___  |\ |_/ /
\_|   |_|\__,_|\___|_| …
```
=> processor_labels: add support for record accessor in values

src/flb_unescape.c, tests/internal/pack.c
Currently, we ignore surrogate pairs for \u escape on Unicode representation.
To handle this, we need to process with surrogate pairs manner.
Noe that this representation is also encoded `\uXXXX` representation on creating JSON.
On creating msgpack, this unescaping operation is effective. 
Closes https://github.com/fluent/fluent-bit/issues/9712.
----
**Testing**
```
$ bin/fluent-bit -i stdin -o stdout
```
and send `{"text": "\ud83e\udd17"}` in the same terminal.
```
Fluent Bit v4.0.0
______ _ …
```
=> unescape: Decode \u escaped characters for surrogate pairs correctly

CMakeLists.txt, init/az2-sethostname.in, init/az2-systemd.in, src/CMakeLists.txt
In AmazonLinux2, it is built on top of coreos technology. So, this race condition bug is also existing there.
In this PR, I added a workaround which is proposed in https://github.com/fluent/fluent-bit/issues/9506#issue-2598519202.
This workaround is only effective for AmazonLinux2.
Closes https://github.com/fluent/fluent-bit/issues/9506
----
**Testing**
```ini
[SERVICE]
flush        1
log_level    info
http_server  Off
http_listen  0.0.0.0
http_port    2020
[INPUT]
name dummy
tag  dummy.local
interval_sec 10
[FILTER]
Name  record_modifier
Match *
Record hostname ${HOSTNAME}
Record filter_type …
```
=> systemd: build: Add sethostname workaround for AmazonLinux2 

src/flb_kafka.c
The errors which are happened in rd_kafka_conf_set() is suppressed for now.
This leads to make more difficult to debug why the specified rdkafka parameters are failed.
This PR makes to display those error messages.
----
**Testing**
----
=> kafka: Display error messages on error for rd_kafka_conf_set()

plugins/out_datadog/datadog_conf.c
Providing a static hostname via the dd_hostname configuration options is currently bugged, with an off-by-one error in the message packing loop causing dropped attributes and/or malformed output json. This PR corrects the issue, incrementing the msgpack map size by one when a dd_hostname property is detected.
----
**Testing**
https://github.com/fluent/fluent-bit/pull/10138
----
Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under …
=> out_datadog: Fix formatting issue when setting a static hostname

include/fluent-bit/flb_version.h.in
=> version: update copyright to 2025

plugins/processor_content_modifier/cm_utils.c
As described in #10145, some data types conversion were wrong or just missing. This patch makes the proper fixes and extend to handle unsigned types.
e.g:
```yaml
pipeline:
inputs:
- name: dummy
dummy: |
{
"string_to_int": "-1",
"string_to_uint": "1",
"string_to_double": "0.2",
"string_to_boolean": "true",
"string_to_string": "hello",
"int_to_string": 1,
"double_to_double": 0.2,
"int_to_boolean": 1,
"int_to_int": -1,
"uint_to_uint": 1,
"int_to_double": 1,
"boolean_to_string": true,
"boolean_to_boolean": true,
"boolean_to_int": true,
"boolean_to_double": true
}
processors:
logs:
action: convert
key: string_to_int
converted_type: int
action: convert
key: string_to_uint
converted_type: int
action: convert
key: …
```
=> processor_content_modifier: fix and enhance data type conversion

src/flb_log_event_decoder.c
This PR tweaks the log event decoder logic to ensure that regardless of if the client code chose to receive meta records or not regular records always contain the appropriate group metadata fields to improve the code update process.
=> log_event_decoder: improved group metadata fields are availability

src/flb_plugin_proxy.c
This PR fixes a memory leak in the plugin proxy, the regular plugin destruction process counts on the name (and description) being constants, however, the plugin proxy makes copies of them when creating both plugin spec instances.
ToDo: I don't really understand why does the plugin proxy create two instances of the `flb_output_plugin` / `flb_input_plugin` structure so I need to check with the code owner to get a better understanding of the reasoning behind it.
=> plugin_proxy: fixed memory leak

plugins/in_storage_backlog/sb.c
This PR fixes an issue with the storage backlog input plugin where the flexible routing mask was not initialized causing a NULL dereference.
=> in_storage_backlog: added missing routing mask initialization

src/config_format/flb_cf_yaml.c
Fix double frees when an error occurs when parsing yaml configuration files, especially with missing include files.
Remove calls to state_destroy on error when it will be cleaned up at the end of the function that parses the yaml configuration.
This fix is meant to address [CVE-2025-29477](https://nvd.nist.gov/vuln/detail/CVE-2025-29477). This is mostly to just encourage code cleanliness.
----
**Testing**
----
Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that …
=> config: yaml: fix double-free from freeing state before cleanup on exit.

src/flb_input_chunk.c
This patch fixes an issue where routes_mask was not initialized, leading to potential errors, by adding the necessary initialization code.
Closes #10223
----
**Testing**
```
==119424== 
==119424== HEAP SUMMARY:
==119424==     in use at exit: 0 bytes in 0 blocks
==119424==   total heap usage: 16,898,665 allocs, 16,898,665 frees, 17,168,835,647 bytes allocated
==119424== 
==119424== All heap blocks were freed -- no leaks are possible
==119424== 
==119424== For lists of detected and suppressed errors, rerun with: -s
==119424== ERROR SUMMARY: 0 …
```
=> input_chunk: routes_mask is not initialized (#10223)

plugins/in_podman_metrics/podman_metrics.c
pipeline: inputs: podman_metrics: fixed use after free which was discovered by failed CI build (after migration from GCC 7 to GCC 9 in https://github.com/fluent/fluent-bit/pull/10230 which was merged as part of https://github.com/fluent/fluent-bit/pull/10178) with optimization for size turned on (`cmake -DFLB_SMALL=On ...`).
Refer to https://github.com/fluent/fluent-bit/actions/runs/14581214135/job/40898148724?pr=7608 for the issue which this pull request fixes.
----
**Testing**
```bash
TEST_PRESET=valgrind SKIP_TESTS='flb-rt-out_td flb-it-network' ./run_code_analysis.sh
``` …
=> pipeline: inputs: podman_metrics: use after free fix

plugins/out_azure_blob/azure_blob.c
This PR fixes a double free in send_blob.
=> out_azure_blob: fixed double free

plugins/in_tail/tail.c, plugins/in_tail/tail_config.c, plugins/in_tail/tail_config.h, plugins/in_tail/tail_file.c, plugins/in_tail/tail_file.h, plugins/in_tail/tail_scan.c, plugins/in_tail/tail_scan.h, plugins/in_tail/tail_scan_glob.c, plugins/in_tail/tail_scan_win32.c
A new opt-out configuration option named `read_newly_discovered_files_from_head` was added to allow users to select the desired behavior. 
Additionally, when a file is ignored due to `ignore_older` its size is stored to ensure that if the file is modified we are able to ingest the data that triggered the timestamp update.
=> in_tail: make read_from_head after the initial discovery optional

plugins/in_tail/tail_file.c
This PR inverts the disposal of the multiline encoder and multiline contexts when removing a file in the tail input plugin in order to prevent a use after free.
=> in_tail: fix disposal order to prevent use after free

plugins/in_opentelemetry/opentelemetry_logs.c, plugins/out_opentelemetry/opentelemetry.h, plugins/out_opentelemetry/opentelemetry_conf.c, plugins/out_opentelemetry/opentelemetry_logs.c
Add support for `scope_logs.schema_url` for opentelemetry.
Encode scope_logs.schema_url inside `scope` for `in_opentelemetry` and then set it again in `out_opentelemetry` using a record accessor for that searches for `scope.schema_url` inside the logs group attributes.
This should fix issue #10143.
----
**Testing**
----
=> opentelemetry: fix support for schema_url in opentelemetry plugins.

plugins/out_oracle_log_analytics/oci_logan.c
This pull request includes a small but important change to the `cb_oci_logan_flush` function in the `oci_logan.c` file. The change improves error handling by logging an error message when the flush operation fails instead of destroying the configuration context.
* [`plugins/out_oracle_log_analytics/oci_logan.c`](diffhunk://#diff-81a068290e9bdd10163cce2b30b61dff7aee9f6ca351196d473d03cbd6d8ead5L1202-R1202): Modified the `cb_oci_logan_flush` function to log an error message with the failure code instead of destroying the configuration context when the flush operation fails.
=> out_oracle_log_analytics: fix use-after-free on flush failure

src/flb_mp.c, tests/internal/mp.c
Fixes #9091
The PR aims to make `flb_mp_accessor_keys_remove` work for sibling subkeys.
The existing versions of the function can only remove one (the first) subkey of a given key. This method is used by several output plugins including `loki` which my team uses. We noticed that not all keys are removed from log records when there are multiple subkeys specified.
A good example is provided in the added unit test, but here is another example of existing behaviour the PR is fixing.
Payload:
```json
{
"kubernetes": {
"pod_id": "id",
"pod_name": "name",
"host": "localhost"
},
"msg": "foo"
}
```
Accessor keys to remove:
```
"$kubernetes['pod_name']"
"$kubernetes['pod_id']"
```
Will result in only `pod_name` being removed. I.e.:
```json
{
"kubernetes": {
"pod_id": "id",
"host": "localhost"
}, …
```
=> mp: fix `flb_mp_accessor_keys_remove` for sibling keys removal

src/config_format/flb_config_format.c
Fixes: https://issues.oss-fuzz.com/issues/42530021
----
**Testing**
---- …
=> config_format: fix SEGV from missing return check

conf/parsers.conf
Fix the regex for the `istio-envoy-proxy` parser. Currently it includes a superfluous `"` character in the `authority` field and `upstream_transport_failure_reason` includes both `"` characters.
----
**Testing** …
=> conf: parsers: fix istio-envoy-proxy parser regex

packaging/test-release-packages.sh
=> packaging: remove older Ubuntu targets from smoke test

tests/internal/fuzzers/CMakeLists.txt, tests/internal/fuzzers/cmetrics_decode_prometheus.c
This split is because prometheus has calls to abort https://github.com/fluent/fluent-bit/blob/e8d608b7d7a7c12eae2dfce019f3c263257ed131/lib/cmetrics/src/cmt_decode_prometheus.y#L44 which forces prometheus decoding to cause exits. Consequently, coverage reports are missing for some of the cmetrics decoding files and the aborts also mean fuzzing of the other decoders will be limited.
Coverage report:
https://storage.googleapis.com/oss-fuzz-coverage/fluent-bit/reports/20250422/linux/src/fluent-bit/lib/cmetrics/src/report.html
This the above problems by splitting the decoding harness into two different fuzzers.
----
**Testing**
- [N/A] Example …
=> tests: internal: fuzzers: split cmetrics decoding

SECURITY.md
Update the security policy now 4.0 is out to show only it and 3.2 are supported.
----
=> security: update policy for 4.0 release series

plugins/out_azure_kusto/azure_kusto_conf.c
The pointer t is just a reference to an element within the tokens array, which is dynamically allocated using flb_calloc. When we free tokens at the end of the function, all memory associated with tokens (including the memory t points to) is automatically released. freeing t again results in double free scenario
fixes https://github.com/fluent/fluent-bit/issues/10257
----
**Testing**
---- …
=> out_azure_kusto: fixed double free

CMakeLists.txt
Commit 3b04755e99fa500e98dcd1318f9b12f6863d31e4
"build: lib: Bundle simdutf amalgamation v5.5.0",
added support for simdutf, and enforces CXX support if FLB_UNICODE_ENCODER is selected. Which is the default case, fix that now.
As requested by https://github.com/fluent/fluent-bit/pull/9277#discussion_r2068161694.
=> build: only compile simdutf if there is CXX support

src/flb_engine.c
When fluent-bit is shutting down it tries to immediately reschedule any pending retries, however, due to how scheduling works a flush task can be scheduled to run and (by signaling the appropriate pipe) then flb_engine_reschedule_retries can try to invalidate it and re-schedule it which in turn causes a problem when handle_output_event is invoked to handle the result of the flush that was supposed to be aborted because when a chunk has only one route it's always set down.
This is not the optimal approach but it's the safest one within the limits of the system.
=> engine: added conditional to avoid re-scheduling conflict

src/flb_pack.c
Fixes #10258
Before this patch, the JSON log record encoder only supported the log record body as an output content, missing support for log record metadata and group metadata and group attributes (if defined).
This patch makes the JSON encoder add support for the missing data, packaging into the record a new parent key called '__internal__' that holds the following inside it:
- group_attributes: group header attributes
- log_metadata: log record metadata
Note that for cases where the origin of the data was OTLP and as part of the groups we add 'group metadata' (in the origin), this is not being used since it only contains internal references that are not used for this JSON export: we do not aim to reassemble this JSON into a Fluent Bit record.
Consider the following original OTLP JSON …
=> pack: add support for metadata and group info in JSON log

plugins/in_opentelemetry/opentelemetry_logs.c, plugins/out_opentelemetry/opentelemetry.h, plugins/out_opentelemetry/opentelemetry_conf.c, plugins/out_opentelemetry/opentelemetry_logs.c
Add support for `scope_logs.schema_url` for opentelemetry. This is a backport of #10201 to the 3.2 series.
Encode scope_logs.schema_url inside `scope` for `in_opentelemetry` and then set it again in `out_opentelemetry` using a record accessor that searches for `scope.schema_url` inside the logs group attributes.
This should fix issue #10143 for the 3.2 series.
----
**Testing**
---- …
=> opentelemetry: fix support for schema_url in opentelemetry plugins (backport of #10201).

include/fluent-bit/flb_simd.h
This is because RVV instructions are truely hardware dependent. So, we need to obtain the actual width with the specific instriction of RVV extentions.
We use 1 segment of 8 or 32 elements of RVV or other SIMD instructions.
So, in RVV, we need to obtain the actual size of VLEN on the RISC-V CPU.
This could be enabled with the following instructions:
* __riscv_vsetvl_e8m1
* __riscv_vsetvl_e32m1
Note that the current implementation is also good but it is only effective for VLEN = 128 environments.
----
**Testing** …
=> simd: Use __riscv_vsetvl_eXXm1 function to get the actual width of RVV instructions

plugins/in_opentelemetry/opentelemetry_logs.c, plugins/out_opentelemetry/opentelemetry_conf.c
the  `schemaURL` is now properly set in the group body when received in Opentelemetry input, for JSON and gRPC, here is an example of the packed content inside the group body:
> pretty printed in JSON for readability
```json    
{
"resource": {
"attributes": {
"service.name": "my.service"
},
"schema_url": "https://example.com/schema2"
},
"scope": {
"schema_url": "https://example.com/schema1",
"name": "my.library",
"version": "1.0.0",
"attributes": {
"my.scope.attribute": "some scope attribute"
}
}
}
```
in addition, the OpenTelemetry output plugin has been fixed in the record accessor pattern to lookup for this value inside the scope map.
---- …
=> opentelemetry: fix handling of schemaUrl in resource and scope

init/az2-sethostname.in
PR #9845 added a service dependency `sethostname.service` for Amazon Linux 2, which uses Amazon's Instance Metadata Service (IMDS) to query and set the hostname. This works for instances using the legacy IMDSv1, however it fails when admins have enforced the usage of IMDSv2. This patch is a modification of @cpandya-we's comment/work on #10186. Closes #10186
Note: I used modified versions of the code samples @cosmo0920 submitted in #9845.  Specifically, note the differences in the packer file, where IMDSv2 support was enabled.
**Testing**
```
[SERVICE]
flush        1
log_level    info
http_server  Off
http_listen  0.0.0.0
http_port    2020
[INPUT]
name dummy
tag  dummy.local
interval_sec 10
[FILTER]
Name  record_modifier
Match *
Record hostname …
```
=> systemd: build: fix service startup failure when using IMDSv2

src/flb_input.c
Add options that were missing to `input_global_properties`.
add the following missing properties to `input_global_properties`:
- storage.type
- storage.pause_on_chunks_overlimit
- threaded
----
**Testing**
----
=> input: add missing options to input_global_properties.

include/fluent-bit/flb_config.h, src/flb_config.c, src/flb_engine.c, src/fluent-bit.c
With default limit of I/O on Windows is somewhat small for large amount of log volume environment.
I provide an option to set up this limit up to 2048.
----
**Testing**
https://github.com/fluent/fluent-bit-docs/pull/1528
----
=> bin: config: Provide windows.maxstdio option for increasing I/O limit on Windows

plugins/out_splunk/splunk.c
Fixes https://github.com/fluent/fluent-bit/issues/10208.
When we had implemented metadata retrieving feature, retrieved HEC token was prioritized for the specified HEC token on out_splunk.
This could be wrong assumptions. So, we need to organize the priorities.
----
**Testing**
Posted on https://github.com/fluent/fluent-bit/issues/10208#issue-2989871674
The final destination can receive logs:
```
Fluent Bit v4.0.2
______ _                  _    ______ _ _             ___  _____ 
|  ___| |                | | …
```
=> out_splunk: Change attaching priority for HEC token

packaging/build-config.json, packaging/distros/almalinux/Dockerfile, packaging/distros/raspbian/Dockerfile, packaging/distros/rockylinux/Dockerfile, packaging/test-release-packages.sh, packaging/update-repos.sh
Resolves #10333 by providing Alma Linux & Rocky Linux builds directly rather than relying on CentOS stream dependencies which are now deviating significantly.
----
**Testing**
----
=> packaging: add AlmaLinux and RockyLinux builds

plugins/in_node_exporter_metrics/ne_cpu_linux.c
This PR removes an unnecessary optimization that caused fluent-bit to crash in virtual machines with 64 or more vCPUs.
=> in_node_exporter: removed unnecessary optimization that caused crash

src/flb_http_client_http2.c
When the request body is quite big, it's split but only the first part is send multiple time instead of sending all parts.
----
**Testing**
----
=> http_client: fix muti part http2 request not working

src/flb_http_client_http2.c
This PR fixes an issue that occurred when a request body exceeded the provided buffer size where the last chunk of the body overwrote the first one.
Note: This is a backport of PR #9818
=> http_client_http2: fixed request body overwrite issue

src/wasm/CMakeLists.txt
As of Rustc 1.81, it starts to use reference type on Wasm creations. So, we need to enable it on our bundled runtime.
Closes https://github.com/fluent/fluent-bit/issues/10196.
Rustc
```
% rustc --version
rustc 1.87.0 (17067e9ac 2025-05-09)
```
AOT object is also able to load
```
$ bin/flb-wamrc --target=x86_64 --cpu=skylake -o filter_rust_rustc187.aot filter_rust_rustc187.wasm
Create AoT compiler with:
target:        x86_64
target cpu:    skylake
target triple: x86_64-pc-linux-gnu
cpu features:  
opt level:     3
size level:    3
output format: AoT file
Compile success, file filter_rust_rustc187.aot was generated.
```
----
**Testing**
``` …
```
=> wasm: Enable reference types feature on wasm

src/flb_config.c
This fixes a segfault in `flb_config_init` that occurs when the call to `flb_config_task_map_resize` fails and then calls `flb_config_exit`, which subsequently dereferences invalid `config->multiline_parsers`.
This was picked up by the fuzzer in CI and can be reproduced on master with this input:
```shell
echo "DgAAAAAHBy8rLi8vLv8QLi8rLy97AT8P/////////xYHB3sBAQAgPy79JjIxNDc0ODM2NDljATg3AAA=" | base64 -d > /tmp/repro_bin
bin/flb-it-fuzz-signv4_fuzzer_OSSFUZZ /tmp/repro_bin
```
----
**Testing** …
=> engine: fix segfault in flb_config_init error case

plugins/in_opentelemetry/opentelemetry.c, plugins/in_opentelemetry/opentelemetry.h, plugins/in_opentelemetry/opentelemetry_logs.c, tests/runtime/in_opentelemetry.c
Currently, the logs body is added to the record in multiple ways
* If it's a MAP, then the key-value pairs are added to the record at the top-level.
* For other types, it's added under the key "message" for OTLP Proto and "log" for OTLP JSON.
Support a way to always nest the logs body under a specific key for consistency, and to avoid possible clashes with other top-level keys in the record (e.g., `__internal__`).
----
**Testing**
If this is a change to packaging of containers or native binaries then please …
=> in_opentelemetry: Configurable logs_body_key

plugins/in_winevtlog/in_winevtlog.c, plugins/in_winevtlog/pack.c, plugins/in_winevtlog/winevtlog.c, plugins/in_winevtlog/winevtlog.h
This PR is a parity feature for fluent-plugin-windows-eventlog's in_windows_eventlog2.
This PR makes to be able to handle remote access on in_winevtlog plugin.
----
**Testing**
https://github.com/fluent/fluent-bit-docs/pull/1683
----
=> in_winevtlog: Support remote access of winevtlog

plugins/out_opensearch/opensearch.c, tests/runtime/out_opensearch.c
If `index` field is blank in the configuration, and `Logstash_Format` and `Generate_ID` are both `off`, a SIGSEGV can occur when trying to generate the index for a set of messages.
Port from https://github.com/fluent/fluent-bit/pull/10353 to the opensearch output plugin
----
**Testing**
- [] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found
- [n/a] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) …
=> out_opensearch: Prevent a SIGSEGV when ctx->index is NULL

plugins/filter_parser/filter_parser.c, plugins/filter_parser/filter_parser.h, tests/runtime/filter_parser.c
This PR authored by OpenAI Codex Agent introduces the ability to use the record accessor syntax within the filter parser. The record accessor syntax allows users to select nested fields via a specific format
https://github.com/fluent/fluent-bit/pull/10364
https://github.com/fluent/fluent-bit/issues/10330
----
**Testing**
Example configuration file
```
service:
flush: 1
pipeline:
inputs:
- name: dummy
dummy: '{"message": "hi", "nested": {"key1":"bye"}}'
filters:
- name: parser
match: "*"
parser: try
key_name: $nested['key1']
outputs:
- name: stdout
match: "*"
parsers:
- name: json
format: json
- name: try
format: regex
regex: ^(?<extracted>.*)$
```
```
SUCCESS: All unit tests have passed.
==93006== …
```
=> filter_parser: add record accessor support in parser filter

.github/workflows/call-build-windows.yaml, .github/workflows/call-windows-unit-tests.yaml, CMakeLists.txt, src/CMakeLists.txt
* Change the importlib name for `fluent-bit.exe`, and modify how debug data output is configured for `fluent-bit.dll` so that build outputs are not overwritten by other build outputs.
* Remove code preventing Ninja/MSVC builds.
* Update MSVC linker flags altered by [`/DEBUG`](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/opt-optimizations.md#arguments) to match Microsoft's [recommendations](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/optimization-best-practices.md#which-level-of-optimization-to-use).
* Update/fix vcpkg caching
All in all this reduces MSVC CI build times with ~20-25% if there is a cache hit for the vcpkg packages and the size of `fluent-bit.exe` is reduced with about 20 %.
---- …
=> build: ci: tune MSVC flags, modify ci caching

CMakeLists.txt, include/fluent-bit/flb_time.h, src/flb_strptime.c, tests/internal/CMakeLists.txt, tests/internal/strptime.c
I implemented a capability to process TimeZone strings.
Plus, `FLB_HAVE_ZONE` is currently nothing effective. This is a vestigial macro that was used or copied from the original BSD's strptime.c code.
Instead, we're able to use a detector which tries to compile the tm_zone member existence in `struct tm` to enable the conditional macro for tm_zone.
Also, I added basic scenarios to run assertions for time zone strings and other functionalities on flb_strptime. 
The corresponding issue is: https://github.com/fluent/fluent-bit/issues/10331
This is because internally, we use `flb_strptime` as a time format parser on flb_parser.c.
So, this change is effective for fluent-bit's parser.
---
The current supported time zone labels of 3-4 letter abbreviated strings:
| Abbreviation | UTC Offset …
=> strptime: Support some of abbriviated timezone strings for GNU extensions

src/flb_input_thread.c, src/proxy/go/go.c
When a Go plugin fails in initialization, with this change, it crashes fluentbit instead of only printing an error log. Also, `proxy_go_input_init` no longer frees memory that is also cleaned up on flb exit (e.g., a return from `flb_input_thread.c:flb_input_thread_instance_init:610` sees a double free, even before this change).
----
**Testing**
----
=> go: plugin_proxy: error on plugin initialization errors

include/fluent-bit/flb_log.h, src/flb_log.c, src/flb_metrics_exporter.c, tests/runtime/CMakeLists.txt, tests/runtime/core_internal_logger.c
This is a cleanup merge for: https://github.com/fluent/fluent-bit/pull/10326
----
=> log: expose internal logging call counts as internal metrics 

plugins/out_azure_blob/CMakeLists.txt, plugins/out_azure_blob/azure_blob.c, plugins/out_azure_blob/azure_blob.h, plugins/out_azure_blob/azure_blob_blockblob.c, plugins/out_azure_blob/azure_blob_blockblob.h, plugins/out_azure_blob/azure_blob_conf.c, plugins/out_azure_blob/azure_blob_store.c, plugins/out_azure_blob/azure_blob_store.h
This pull request introduces significant enhancements to the Azure Blob plugin, focusing on adding buffering capabilities and improving URI handling.
* Added new configuration options and fields to support buffering, such as `buffering_enabled`, `buffer_dir`, `store_dir_limit_size`, and `current_buffer_size` in the `flb_azure_blob` struct. These changes enable the plugin to buffer data before uploading to Azure Blob Storage.
* Introduced validation to ensure buffering is not used with the `appendblob` blob type, as it is incompatible. An error is logged if this configuration is detected.
* Updated the `azb_block_blob_uri` and `azb_block_blob_uri_commit` functions to include a new `random_str` parameter for generating more unique URIs for block blobs. This ensures better handling of …
=> out_azure_blob: added buffering to azure blob

include/fluent-bit/flb_api.h, include/fluent-bit/flb_custom.h, include/fluent-bit/flb_plugin_proxy.h, include/fluent-bit/flb_plugins.h.in, src/flb_api.c, src/flb_custom.c, src/flb_plugin_proxy.c, src/proxy/go/go.c, src/proxy/go/go.h
For some motivations to support custom plugin mechanism in Fluent Bit, we need to implement custom plugins which are built on top of Golang infrastructures.
This PR makes to be able to provide and support Golang custom plugins.
This PR is based on https://github.com/fluent/fluent-bit/pull/9470 but adding modifications with working on calyptia-plugin module which is maintained here:
https://github.com/chronosphereio/calyptia-plugin/pull/101
Plus, we need to implement custom plugin mechanism calyptia-plugin modue.
So, I also implemented custom Golang mechanism in https://github.com/chronosphereio/calyptia-plugin/pull/101.
Note that we might have to maintain ABI for plugin API like logging and obtaining cmetrics instances.
I just adding APIs for custom plugins afterwards of input or output …
=> api: proxy: custom: Implement APIs for custom Go plugins

plugins/out_es/es.c, tests/runtime/out_elasticsearch.c
If `index` field is blank in the configuration, and `Logstash_Format` and `Generate_ID` are both `off`, a SIGSEGV can occur when trying to generate the index for a set of messages.
Fixes #10339 
----
**Testing**
- v4.0.1: #10356
- v4.0.2: #10357 …
=> out_es: Prevent a SIGSEGV when ctx->index is NULL

src/flb_input.c, src/flb_input_thread.c, tests/internal/stream_processor.c
This is a rebased PR of https://github.com/fluent/fluent-bit/pull/10350 on top of master branch (trying to workaround some CI issues)
----
=> input: fixed threaded input processor initialization 

src/flb_utils.c, tests/internal/utils.c
When SIMD is enabled and we do JSON escaping with flb_utils_write_str, we will vectorize the search for special characters that need escaping. The current implementation lacks the highbit check, some issues happens with special Chinese characters.
This PR adds a unit test and proper fix.
----
=> utils: if flb_utils_write_str uses SIMD, add missing highbit_set check() detection

plugins/out_azure_kusto/azure_kusto.c
As outlined in the issue below, when the out_azure_kusto plugin was used alongside the in_opentelemetry plugin, it previously generated multiple logs for each incoming OTEL log. For instance: 
[62] v1_logs: [[-1.000000000, {"schema"=>"otlp", "resource_id"=>0, "scope_id"=>11}], {"resource"=>{"attributes"=>{"telemetry.sdk.name"=>"opentelemetry", "telemetry.sdk.language"=>"dotnet", "telemetry.sdk.version"=>"1.8.1", "service.name"=>"unknown_service:dotnet"}}, "schema_url"=>"", "scope"=>{"name"=>"Microsoft.Extensions.HttpClient.Logging.Internal.HttpLoggingHandler"}}]
[63] v1_logs: [[1741372257.966227535, {"otlp"=>{"observed_timestamp"=>1741372257825108400, "timestamp"=>1741372257825108400, "severity_number"=>17, "severity_text"=>"Error", "attributes"=>{"resolved_host"=>"<some url>.com", …
=> out_azure_kusto: support for otel log schema

plugins/in_tcp/tcp_conn.c
Fixed malfunction when using a seperator longer than 1 charactor in tcp INPUT none format log.
Consumed length does not include the length of the separator.
I use `$endlog$\r\n` as a separator. As shown below, however part of the separator is included in the split logs, or some content from the previous log is replayed in the next one.
```json
{"log":"Hello, fluent-bit! 1"}
{"log":"Hello, fluent-bit! 2"}
{"log":"Hello, fluent-bit! 3"}
{"log":"lo, fluent-bit! 3"}
{"log":"endlog$\r\nHello, fluent-bit! 4"}
{"log":"endlog$\r\nHello, fluent-bit! 5"}
{"log":"endlog$\r\nHello, fluent-bit! 6"}
{"log":"endlog$\r\nHello, fluent-bit! 7"}
{"log":"Hello, fluent-bit! 8"}
{"log":"t-bit! 8"}
{"log":"endlog$\r\nHello, fluent-bit! 9"}
{"log":"endlog$\r\nHello, fluent-bit! 10"}
{"log":"endlog$\r\nHello, …
```
=> in_tcp: fix parsed bytes to include separator length

plugins/in_http/http_config.c, plugins/in_http/http_prot.c
=> in_http: validate memory allocation and fix object type on tag key

plugins/out_azure_kusto/azure_kusto.c
This patch fix an invalid access after the file context has been deallocated.
----
=> out_azure_kusto: fix segfault when log level is debug or trace

include/fluent-bit/flb_config.h, src/flb_config.c, src/flb_storage.c, tests/internal/CMakeLists.txt, tests/internal/storage_inherit.c
Adds storage inheritance logic allowing input instances to inherit global storage configuration.
Example configuration with global storage inheritance:
```ini
[SERVICE]
storage.type filesystem
storage.inherit on
storage.path /tmp/fluent-bit-test
flush 1
daemon off
[INPUT]
name dummy
tag test.inherit
[INPUT] 
name dummy
tag test.override
storage.type memory
[OUTPUT]
name stdout
match *
```
Expected behavior:
- First input uses filesystem storage (inherited from service)
- Second input uses memory storage (explicit override)
- Input instances without explicit storage.type inherit from global config when storage.inherit=on
Example configuration without global storage:
```ini
[SERVICE]
storage.path /tmp/fluent-bit-test
flush 1
daemon off
[INPUT]
name dummy
tag test.default
[INPUT] 
name dummy …
```
=> config: implement storage inheritance option

src/flb_log_event_decoder.c
=> log_event_decoder: validate memory allocation

plugins/filter_modify/modify.c
=> filter_modify: fix leaks on exceptions

include/fluent-bit/flb_processor.h, plugins/filter_lua/lua.c, src/flb_processor.c, tests/runtime/filter_lua.c
Current Lua filter did not process the groups definitions, so when it process data that contains these metadata such as payloads coming from OpenTelemetry the groups definitions were dropped. 
This PR implements groups support allowing to work normally, this is a configuration example:
```yaml
pipeline:
inputs:
- name: dummy
dummy: "{\"message\": \"Hello, Fluent Bit!\"}"
metadata: "{\"record_meta\": \"ok\"}"
processors:
logs:
- name: opentelemetry_envelope
context: otel_resource_attributes
action: insert
key: my_res_attr
value: my_value
context: otel_scope_attributes
action: insert
key: my_scope_attr
value: my_value
- name: lua
time_as_table: true
call: noop
code: |
function noop(tag, timestamp, record)
record["new_field"] = "This is a new …
```
=> filter_lua: add groups metadata and body support

lib/lwrb/lwrb/CMakeLists.txt
This PR fix the build rules for lwrb library to avoid repeated compilation across plugins: every plugin was compiling lwrb over and over.
----
=> lib: lwrb: build it as a static lib instead of an interface

plugins/processor_content_modifier/cm_utils.c, plugins/processor_content_modifier/cm_utils.h
=> processor_content_modifier: fix leak on JSON conversion and data type

plugins/out_opentelemetry/opentelemetry_conf.c, plugins/out_opentelemetry/opentelemetry_logs.c
=> out_opentelemetry: fix leaks on exceptions

include/fluent-bit/http_server/flb_http_server.h, plugins/in_elasticsearch/in_elasticsearch.c, plugins/in_http/http.c, plugins/in_http/http_conn.c, plugins/in_http/http_prot.c, plugins/in_opentelemetry/opentelemetry.c, plugins/in_prometheus_remote_write/prom_rw.c, plugins/in_splunk/splunk.c, src/http_server/flb_http_server.c
The HTTP Server interface, which supports HTTP/2 with fallback to HTTP/1, now includes an API to configure the maximum buffer size per client during data ingestion. If a client exceeds this limit, a 413 Payload Too Large error is returned.
This PR updates the following input plugins to use the new API:
- in_elasticsearch
- in_http
- in_opentelemetry
- in_prometheus_remote_write
- in_splunk
----
=> http_server: add new API to configure the maximum buffer size

plugins/in_splunk/splunk_prot.c
if the length of token v/s auth header are different, it must skip the token instead of immediately return unauthorized
fixes #10483
----
<details><summary>Details</summary>
```text 
$FBIT_HOME/fluent-bit -c files/fluent-bit.yml
Fluent Bit v4.0.4
______ _                  _    ______ _ _             ___  _____ 
|  ___| |                | |   | ___ (_) |           /   ||  _  |
| |_  | |_   _  ___ _ __ | |_  | |_/ /_| |_  __   __/ /| || |/' |
|  _| | | | | |/ _ \ '_ \| __| | ___ \ | __| \ \ / / /_| ||  /| |
| |   | | |_| |  __/ | | | |_  | |_/ / | |_   \ V /\___  |\ |_/ /
\_|   |_|\__,_|\___|_| |_|\__| \____/|_|\__|   \_/     |_(_)___/ 
[2025/06/17 …
```
=> in_splunk: continue with the next token if length of auth header vs token doesn't match

src/config_format/flb_cf_yaml.c
Before this patch if a Yaml file contained a format error, it only show:
```
[2025/06/19 16:13:59] [error] [config] invalid YAML format in file mybadfile.yaml
[2025/06/19 16:13:59] [error] configuration file contains errors, aborting.
```
now it prints useful information about the problem:
```
[2025/06/19 16:34:14] [error] [config] invalid YAML in file mybadfile.yaml at line 4, column 1: could not find expected ':'
[2025/06/19 16:34:14] [error] [config] hint: check line 3 (above) for missing ':' or incorrect indentation
[2025/06/19 16:34:14] [error] configuration file contains errors, aborting.
```
----
=> config_format: yaml: add detailed error message on bad format

plugins/in_calyptia_fleet/in_calyptia_fleet.c, plugins/in_calyptia_fleet/in_calyptia_fleet.h
Report the currently loaded configuration version with each request from the fleet plugin, especially when querying for the latest configuration.
----
**Testing**
----
=> in_calyptia_fleet: report the configuration version.

src/flb_gzip.c
In the previous implementation, the last element of boundary is not allocated.
So, the last boundary that is reached for the maximum inflating gzip cases is not allocated but released.
This is not well behaved.
Fixes https://github.com/fluent/fluent-bit/issues/10509
----
**Testing**
----
=> gzip: Process boundary conditions strictly

src/flb_upstream.c
Currently, we're prioritizing the creation of new connections if there's no limit on them or if we are within the limits.
This commit prioritizes the reuse of connections and only creates one if there are no available ones and we're within the limits (if any).
This should address #10342 
This also fixes a regression introduced in #10423  where we were not reusing connections in the av_queue.
----
**Testing**
```yml
pipeline:
inputs:
- name: dummy
tag: dummy
- name: forward
port: 8888
tag: fwd
outputs:
- name: stdout
match: 'fwd'
- name: forward
match: dummy
host: localhost
port: 8888
service:
```
<details><summary>Debug …
=> upstream: prioritize the reuse of connections instead of establishing new ones

plugins/in_calyptia_fleet/in_calyptia_fleet.c, plugins/out_calyptia/calyptia.c
Fix memory leaks in `in_calyptia_fleet` and `out_calyptia` that could occur during initialization.
----
**Testing**
----
=> in_calyptia_fleet: fix init error mem leaks.

plugins/in_kmsg/in_kmsg.c
On 32-bit systems, kmsg stops producing logs after some time. This is because of ERANGE error. The ERANGE error occurs when processing timestamp, because although val is of type uint64_t, strtol cannot process the value because of long being only 4 bytes, which is not sufficient to hold the timestamp values. It would be better to use strtoull instead, to make sure we have 8 bytes to store the value on all systems.
Fixes #10373.
=> in_kmsg: use strtoull to fix timestamp parsing on 32-bit systems

include/fluent-bit/flb_ra_key.h, include/fluent-bit/flb_record_accessor.h, src/flb_ra_key.c, src/flb_record_accessor.c, tests/internal/record_accessor.c
> __note__ this is part of the solution for https://github.com/fluent/fluent-bit/issues/10460, basically we pack `trace_id` and `span_id` as binaries however record accessor don't support it
This PR extends record_accessor internals to support access to values which are binary, as well providing extra functionality to get a reference instead of a copy for strings/binaries, more details below:
__Binary value support__
The ra_types enumeration now includes FLB_RA_BINARY to represent MessagePack binary fields, and each flb_ra_value tracks whether its data was copied or referenced via the new ra_storage_type enum and storage field.
__Unified value access__
flb_ra_value_buffer() provides a single API to obtain the underlying buffer and length for either copied or referenced string/binary …
=> record_accessor: add support for binary values and references

src/aws/flb_aws_credentials.c, src/flb_http_client.c, src/flb_network.c, src/flb_upstream.c
fixes: https://github.com/fluent/fluent-bit/issues/10458
In addition, other fixes are part of this PR for async DNS resolution (remove stale fd from the event loop), extra validation of socket status for a synchronous network connection and the busy_flag management in the upstream interface.
----
=> network: general fixes for failure states

cmake/plugins_options.cmake, plugins/filter_lua/CMakeLists.txt, plugins/filter_lua/lua.c, plugins/filter_lua/lua_config.h, tests/runtime/filter_lua.c
Prior to this change, the Lua filter in Fluent Bit supported processing of individual log records with a function signature that allowed modifying the timestamp and the record only:
```lua
function append_tag(tag, timestamp, record)
...
return 1, timestamp, record
end
```
This PR introduces an optional extended prototype that allows access to group metadata and record metadata, making the function more powerful and better suited for structured formats like OpenTelemetry Logs.
The new supported Lua function prototype is:
```lua
function cb_metadata(tag, timestamp, group, metadata, record)
...
return 1, timestamp, metadata, record
end
```
- `tag`: the input tag of the log record.
- `timestamp`: the timestamp of the log record.
- `group`: a read-only table that contains group-level metadata …
=> filter_lua: add support to access groups and metadata

plugins/out_opentelemetry/opentelemetry_logs.c
Fixes #10485
note: still work in process, unit tests are coming.
----
=> out_opentelemetry: fix logic for grouping when using resource_id/scope_id

plugins/out_cloudwatch_logs/cloudwatch_api.c
See https://autobuild.buildroot.org/results/ade/ade1783e6a8a9025a4fc12a8370d479662b84ec4/build-end.log.
```
In file included from /workdir/instance-0/output-1/build/fluent-bit-4.0.2/lib/cfl/lib/xxhash/xxh3.h:55,
from /workdir/instance-0/output-1/build/fluent-bit-4.0.2/lib/cfl/include/cfl/cfl_hash.h:26,
from /workdir/instance-0/output-1/build/fluent-bit-4.0.2/lib/cfl/include/cfl/cfl.h:33,
from /workdir/instance-0/output-1/build/fluent-bit-4.0.2/include/fluent-bit/flb_config_map.h:27,
from /workdir/instance-0/output-1/build/fluent-bit-4.0.2/include/fluent-bit/flb_output.h:36,
from /workdir/instance-0/output-1/build/fluent-bit-4.0.2/plugins/out_cloudwatch_logs/cloudwatch_api.c:22:
/workdir/instance-0/output-1/build/fluent-bit-4.0.2/lib/cfl/lib/xxhash/xxhash.h:3962:5: warning: #warning "XXH3 …
```
=> out_cloudwatch_logs: fix strcasestr _GNU_SOURCE

plugins/in_kafka/in_kafka.c, plugins/in_kafka/in_kafka.h
> Note: this is a rebased of PR https://github.com/fluent/fluent-bit/pull/10412 on top of master branch and cleaned up history of commits.
Fixes https://github.com/fluent/fluent-bit/issues/9813
This change introduces a new configuration option 'enable_auto_commit' to control Kafka message commit behavior. When disabled (default), messages are committed only after successful processing, providing better control over message processing guarantees.
The option defaults to false to:
- Prevent potential message loss in case of failures
- Give users explicit control over commit behavior
- Ensure messages are only committed after successful processing
Users can enable auto-commit by setting enable_auto_commit true in their configuration if they prefer automatic batch commits.
----
Fluent Bit is …
=> in_kafka: add enable_auto_commit option for Kafka consumer

plugins/out_loki/loki.c, plugins/out_loki/loki.h, tests/runtime/out_loki.c
Fixes #10560
Added per-thread removal contexts in Loki’s configuration to prevent race conditions when multiple workers use the `Remove_Keys` option. The change introduces a thread-local storage for these contexts and created helper functions to manage them safely
----
=> out_loki: prevent race conditions when multiple workers use remove_keys

plugins/out_file/file.c
It's been a while this issue could be a long standing issue and avoding to use SHCreateDirectoryExA is a removing nonexisting API for Windows Nano Server.
This API is not listed in the supported API list here: https://learn.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt588480(v=vs.85)
Related to https://github.com/fluent/fluent-bit/issues/10255
----
**Testing**
```ini
[INPUT]
Name dummy
Tag win.dummy
[OUTPUT]
Name file
Match *
Path output_dir/in_dummy/deepened
Mkdir True
```
```console
Fluent Bit v4.0.5
* …
```
=> out_file: Replace SHCreateDirectoryExA to work for recursive directories correctly

src/flb_network.c
Enable EDNS0 for all DNS queries to match c-ares defaults and support responses larger than 512 bytes.
Partially addresses #10588
=> network: enable EDNS for DNS queries

include/fluent-bit/flb_output.h, include/fluent-bit/tls/flb_tls.h, src/flb_output.c, src/tls/flb_tls.c, src/tls/openssl.c
To support loading certificates with a user-specified name from Windows CertStore, we need to provide a capability to handle input and output parameters for specifying name of certstore and loading certstore with a user-defined name.
Fixes https://github.com/fluent/fluent-bit/issues/9215.
This is also a possible obstacles migrations from Fluentd to Fluent Bit.
So, we should eliminate this kind of blockers for migrations.
Plus, this is a parity for Fluentd's feature:
(Fluentd does, https://docs.fluentd.org/output/forward#how-to-connect-to-a-tls-ssl-enabled-server-with-windows-certstore-certificate).
----
**Testing**
```
[SERVICE]
Flush        5 …
```
=> tls: openssl: output: configurable certstore name

include/fluent-bit/flb_input.h, src/flb_input.c
Input plugins running in threaded mode use a per-instance ring buffer to enqueue records into the pipeline, which are then consumed by the engine. By default, each ring buffer is sized for 1024 entries.
In high-throughput scenarios, the default capacity may not be sufficient. This patch introduces two new configuration options to allow fine-tuning of the ring buffer behavior per input plugin:
- thread.ring_buffer.capacity: Sets the maximum number of entries the ring buffer can hold (default: 1024).
- thread.ring_buffer.window: Sets the flush window as a percentage of capacity, used to trigger a flush
request when the threshold is reached (default: 5).
----
Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms …
=> input: make input threads ring_buffer capacity and window flush configurable

include/fluent-bit/flb_output.h, include/fluent-bit/tls/flb_tls.h, src/flb_output.c, src/tls/flb_tls.c, src/tls/openssl.c
This is backporting PR for https://github.com/fluent/fluent-bit/pull/10590.
----
**Testing**
----
=> tls: openssl: output: configurable certstore name [Backport 4.0]

plugins/in_windows_exporter_metrics/CMakeLists.txt, plugins/in_windows_exporter_metrics/we.c, plugins/in_windows_exporter_metrics/we.h, plugins/in_windows_exporter_metrics/we_cache.c, plugins/in_windows_exporter_metrics/we_cache.h, plugins/in_windows_exporter_metrics/we_cpu.c, plugins/in_windows_exporter_metrics/we_logical_disk.c, plugins/in_windows_exporter_metrics/we_metric.c, plugins/in_windows_exporter_metrics/we_metric.h, plugins/in_windows_exporter_metrics/we_net.c, plugins/in_windows_exporter_metrics/we_perflib.c, plugins/in_windows_exporter_metrics/we_wmi_memory.c, plugins/in_windows_exporter_metrics/we_wmi_paging_file.c, plugins/in_windows_exporter_metrics/we_wmi_tcp.c, plugins/in_windows_exporter_metrics/we_wmi_tcp.h
This is backporting PR for https://github.com/fluent/fluent-bit/pull/10601.
----
**Testing**
----
=> in_windows_exporter_metrics: Extend metrics [Backport 4.0]

include/fluent-bit/flb_input.h, src/flb_input.c, src/flb_input_chunk.c
This patch adds new metrics to track the behavior of the input ring buffer, enabling better observability and troubleshooting in high-load or threaded environments.
The following counters are now registered per input instance:
| Metric Name                                          | Description                                 |
|------------------------------------------------------|---------------------------------------------|
| `fluentbit_input_ring_buffer_writes_total`           | Number of successful ring buffer writes     |
| `fluentbit_input_ring_buffer_retries_total`          | Number of retry attempts due to saturation  |
| `fluentbit_input_ring_buffer_retry_failures_total`   | Number of failed retries (after limit hit)  |
---
In high-throughput scenarios — especially when input …
=> input: add new ring buffer metrics

plugins/in_syslog/syslog_prot.c
> Backport of #10634 
The syslog input plugin previously processed and encoded records one by one, resulting in frequent writes to the ring buffer when running in threaded mode. This was particularly inefficient under high-load environments, where it could lead to ring buffer saturation and increased retry pressure.
This change introduces encoder batching by resetting the encoder before parsing each message and flushing the accumulated records after processing. The new behavior improves throughput and reduces contention on the ring buffer.
High level overview of the changes
| Metric                          | Before                       | After                        | Improvement                          |
|---------------------------------|------------------------------|---------------- …
=> in_syslog: do batching to reduce ring buffer pressure under load [v4.0]

include/fluent-bit/flb_network.h, src/flb_network.c, src/flb_output.c, src/flb_upstream.c
> Backport of #10613
This patch introduces a new configuration option: `net.proxy_env_ignore` (default: false).
By default, the upstream connection layer uses proxy settings from the environment (HTTP_PROXY, HTTPS_PROXY). However, in some scenarios, particularly when running multiple plugins with differing proxy needs, this default can cause unintended routing.
The new option `net.proxy_env_ignore` allows a plugin to explicitly disable the use of environment-based proxy configuration. When set to true, Fluent Bit will skip any proxy settings defined via environment variables, relying solely on plugin-level proxy settings (if provided).
e.g:
setting up an invalid proxy port (8081), however functional proxy runs in port 8080
```bash
export HTTP_PROXY=http://localhost:8081
```
```bash …
```
=> output: add new net.proxy_env_ignore option [v4.0]

plugins/out_chronicle/chronicle.c, plugins/out_chronicle/chronicle_conf.c, tests/runtime/CMakeLists.txt, tests/runtime/out_chronicle.c
The previous detection mechanism is too tight to handle missing log_key. Instead, we loosen the mechanism that permits to traverse entrie the record. And failing for just missing of anhy of the keys in a record map.
----
**Testing**
From leaks command on macOS, there is no reported memory leaks:
```console
Process:         fluent-bit [68263]
Path:            /Users/USER/*/fluent-bit
Load Address:    0x102b74000
Identifier:      fluent-bit
Version:         0
Code Type:       ARM64
Platform:        macOS
Parent Process:  leaks [68262]
Target Type:     live task
Date/Time:       2025-07-24 18:39:38.592 +0900
Launch Time:     2025-07-24 …
```
=> out_chronicle: Fix log_key detection mechanism

plugins/out_chronicle/chronicle.c, plugins/out_chronicle/chronicle_conf.c, tests/runtime/CMakeLists.txt, tests/runtime/out_chronicle.c
This is backporting PR of https://github.com/fluent/fluent-bit/pull/10642.
----
**Testing**
----
=> out_chronicle: Fix log_key detection mechanism [Backport 4.0]

plugins/in_windows_exporter_metrics/CMakeLists.txt, plugins/in_windows_exporter_metrics/we.h, plugins/in_windows_exporter_metrics/we_wmi_tcp.c
Fixes https://github.com/fluent/fluent-bit/issues/10659.
----
**Testing**
````
PS> bin/fluent-bit -i windows_exporter_metrics -p metrics=tcp -o stdout -v
````
```
Fluent Bit v4.1.0
______ _                  _    ______ _ _             ___  _____
|  ___| |                | |   | ___ (_) |           /   ||  _  |
| |_  | |_   _  ___ _ __ | |_  | |_/ /_| |_  __   __/ /| || |/' |
|  _| | | | | |/ _ \ '_ \| __| | ___ \ | __| \ \ / / /_| ||  /| |
| |   | | |_| |  __/ | | | |_  | |_/ / | |_   \ V /\___  |\ |_/ /
\_| …
```
=> in_windows_exporter_metrics: Follow windows_exporter prom names correctly and support connection_state metrics

plugins/in_winevtlog/pack.c
* SystemTimeToTzSpecificLocalTimeEx
* GetDynamicTimeZoneInformation
are able to handle Daylight Saving Time(DST).
FileTimeToLocalFileTime and SystemTimeToTzSpecificLocalTimeEx
automatically convert between ST and DST.
These functions are working well for DST conversions.
Then, we got:
```
[663] winevtlog.0: [[1753251022.125331400, {}], {"ProviderName"=>"Microsoft-Windows-RestartManager", "ProviderGuid"=>"{0888E5EF-9B98-4695-979D-E92CE4247224}", "Qualifiers"=>"", "EventID"=>10001, "Version"=>0, "Level"=>4, "Task"=>0, "Opcode"=>0, "Keywords"=>"0x8000000000000000", "TimeCreated"=>"2025-05-10 05:13:42 -0700", "EventRecordID"=>3959, "ActivityID"=>"", "RelatedActivityID"=>"", "ProcessID"=>34096, "ThreadID"=>61344, "Channel"=>"Application", "Computer"=>"hiro-area51-14", "UserID"=>"NT …
```
=> in_winevtlog: Handle Daylight saving time by using newer functions

include/fluent-bit/flb_input_chunk.h, include/fluent-bit/flb_output.h, src/flb_engine.c, src/flb_input_chunk.c, src/flb_output.c
This PR introduces a new Fluent Bit internal histogram metric:
- `fluentbit_output_latency_seconds`
This metric captures the end-to-end latency (in seconds) from the time a chunk is created by an input plugin until it is successfully delivered by an output plugin. It provides observability into chunk-level pipeline performance and helps identify slowdowns or bottlenecks in the output path.
__Metric Details__
- Metric name: `fluentbit_output_latency_seconds`
- Type: histogram
- Unit: seconds
- Labels:
- input: name of the input plugin instance (e.g., random.0)
- output: name of the output plugin instance (e.g., stdout.0)
__Example Output__
```
fluentbit_output_latency_seconds_bucket{le="0.5",input="random.0",output="stdout.0"} 0
fluentbit_output_latency_seconds_bucket{le="1.0",input="random …
```
=> output: add Histogram Metric for end-to-end chunk latency

include/fluent-bit/flb_input_chunk.h, include/fluent-bit/flb_output.h, src/flb_engine.c, src/flb_input_chunk.c, src/flb_output.c
Backporting from https://github.com/fluent/fluent-bit/pull/10644.
----
**Testing**
----
=> output: add Histogram Metric for end-to-end chunk latency [Backport to 4.0]

src/flb_log.c
Adds nanoseconds precision to the logs Fluent Bit writes.
It's possible in some cases that the underlying implementation of the time functions won't provide nanoseconds precision. In those cases, the precision will be to microseconds, which is still better than to the second. (see [here](https://github.com/fluent/fluent-bit/pull/9985#issuecomment-2859018751))
Addresses #9983
----
=> log: increase precision in log's timestamp to nanoseconds

cmake/msgpack.cmake, plugins/in_opentelemetry/opentelemetry_logs.c, src/flb_pack.c, src/opentelemetry/flb_opentelemetry_utils.c, tests/internal/data/opentelemetry/test_cases.json, tests/internal/pack.c
This PR fixes #10672 and #10673 
Couple of fixes were needed for cases with messages with long nested array/maps, as well some fixes for packaging for not set values while processing AnyValues.
Added some test cases and fixed the JSON packer that shown some issues packaging messages with many nested levels (recursion)
----
=> opentelemetry: general fixes for log handling

plugins/in_windows_exporter_metrics/we_os.c
Backporting from https://github.com/fluent/fluent-bit/pull/10676.
----
**Testing**
----
=> in_windows_exporter_metrics: Handle DST more precisely with dynamic timezone verison of functions [Backport to 4.0]

cmake/msgpack.cmake, plugins/in_opentelemetry/opentelemetry_logs.c, src/flb_pack.c, src/opentelemetry/flb_opentelemetry_utils.c, tests/internal/data/opentelemetry/test_cases.json, tests/internal/pack.c
Backporting from https://github.com/fluent/fluent-bit/pull/10693.
----
**Testing**
----
=> opentelemetry: general fixes for log handling [Backport to 4.0]

plugins/in_node_exporter_metrics/CMakeLists.txt, plugins/in_node_exporter_metrics/ne.c, plugins/in_node_exporter_metrics/ne.h, plugins/in_node_exporter_metrics/ne_hwmon.c, plugins/in_node_exporter_metrics/ne_hwmon.h, plugins/in_node_exporter_metrics/ne_hwmon_linux.c, plugins/in_node_exporter_metrics/ne_hwmon_linux.h
This PR adds hardware monitoring (hwmon) support to the in_node_exporter_metrics input plugin, enabling collection of hardware sensor data from Linux systems.
__New metrics__
- Temperature metrics: node_hwmon_temp_celsius, node_hwmon_temp_max_celsius, node_hwmon_temp_crit_celsius
- Voltage metrics: node_hwmon_in_volts
- Fan speed metrics: node_hwmon_fan_rpm
- Power metrics: node_hwmon_power_watts
__Features__
- Reads sensor data from /sys/class/hwmon/hwmon* interfaces
- Configurable regex filtering for chips and sensors (include/exclude patterns)
- Configurable scrape interval via collector.hwmon.scrape_interval
- Automatic sensor labeling from hwmon label files
- Added to default enabled metrics for Linux platforms
__Configuration Options__
- collector.hwmon.chip-include - regex to …
=> in_node_exporter_metrics: add Linux hwmon collector

include/fluent-bit/flb_macros.h, include/fluent-bit/flb_metrics.h, include/fluent-bit/flb_output.h, src/flb_input_metric.c, src/flb_metrics.c
Backport of https://github.com/fluent/fluent-bit/pull/10700/
----
=> input_metrics: discard cmetrics with no series (backport v4.0)

plugins/in_node_exporter_metrics/CMakeLists.txt, plugins/in_node_exporter_metrics/ne.c, plugins/in_node_exporter_metrics/ne.h, plugins/in_node_exporter_metrics/ne_sockstat.c, plugins/in_node_exporter_metrics/ne_sockstat.h, plugins/in_node_exporter_metrics/ne_sockstat_linux.c
Backport of https://github.com/fluent/fluent-bit/pull/10718
----
=> in_node_exporter_metrics: add Linux sockstat collector (backport v4.0)

plugins/in_node_exporter_metrics/CMakeLists.txt, plugins/in_node_exporter_metrics/ne.c, plugins/in_node_exporter_metrics/ne.h, plugins/in_node_exporter_metrics/ne_hwmon.c, plugins/in_node_exporter_metrics/ne_hwmon.h, plugins/in_node_exporter_metrics/ne_hwmon_linux.c, plugins/in_node_exporter_metrics/ne_hwmon_linux.h
Backport of https://github.com/fluent/fluent-bit/pull/10719
----
=> in_node_exporter_metrics: add Linux hwmon collector (backport v4.0)

conf/fluent-bit-metrics.conf, docker_compose/node-exporter-dashboard/docker-compose.yml, plugins/in_node_exporter_metrics/ne.c, plugins/in_node_exporter_metrics/ne.h, plugins/in_node_exporter_metrics/ne_config.c, plugins/in_node_exporter_metrics/ne_stat_linux.c, plugins/in_node_exporter_metrics/ne_utils.c, plugins/in_node_exporter_metrics/ne_utils.h
Backport of https://github.com/fluent/fluent-bit/pull/10723
----
=> in_node_exporter_metrics: add new option 'path.rootfs' (backport v4.0)

plugins/out_azure_kusto/azure_kusto.c, plugins/out_azure_kusto/azure_kusto.h, plugins/out_azure_kusto/azure_kusto_conf.c, plugins/out_azure_kusto/azure_msiauth.c, plugins/out_azure_kusto/azure_msiauth.h, tests/runtime/out_azure_kusto.c
Backport of https://github.com/fluent/fluent-bit/pull/10283
----
=> out_azure_kusto: Added workload identity support (backport v4.0)

plugins/out_cloudwatch_logs/cloudwatch_api.c, plugins/out_cloudwatch_logs/cloudwatch_api.h, plugins/out_cloudwatch_logs/cloudwatch_logs.c, plugins/out_cloudwatch_logs/cloudwatch_logs.h
Backport of https://github.com/fluent/fluent-bit/pull/10585
----
=> out_cloudwatch: add entity support and remove unnecessary log content (backport v4.0)

plugins/out_es/es.c, plugins/out_es/es.h, tests/runtime/out_elasticsearch.c
=> out_es: add apikey to available auth types

lib/chunkio/src/CMakeLists.txt, lib/chunkio/src/cio_os.c, lib/chunkio/src/win32/dirent.c
=> lib: chunkio: update to 98988d25

plugins/in_calyptia_fleet/in_calyptia_fleet.c
=> in_calyptia_fleet: fleet config fetch ignores older-timestamped files

CMakeLists.txt
Backporting from https://github.com/fluent/fluent-bit/pull/10786.
----
**Testing**
----
=> cmake: explicitly disable FLB_UNICODE_ENCODER when FLB_USE_SIMDUTF is disabled. [Backport to 4.0]

src/flb_pipe.c
Backporting from https://github.com/fluent/fluent-bit/pull/10789.
----
**Testing**
----
=> pipe: Specify linger option for flb_pipes which is build on top of socketpairs on Windows [Backport to 4.0]

plugins/in_opentelemetry/opentelemetry_logs.c, src/opentelemetry/flb_opentelemetry_logs.c, tests/internal/data/opentelemetry/README.md, tests/internal/data/opentelemetry/test_cases.json
Backport of https://github.com/fluent/fluent-bit/pull/10813 , fixes https://github.com/fluent/fluent-bit/issues/10793
----
=> opentelemetry: remove enforcement of timestamp fields for logs (backport v4.0)

include/fluent-bit/flb_http_client.h, plugins/out_http/http.c, plugins/out_http/http.h, src/flb_http_client.c
Backport of https://github.com/fluent/fluent-bit/pull/10801
----
=> http_client: add response and read idle timeouts (backport v4.0)

plugins/in_opentelemetry/opentelemetry_traces.c, src/opentelemetry/flb_opentelemetry_utils.c, tests/internal/data/opentelemetry/test_cases.json, tests/internal/opentelemetry.c
Backport of #10815, fixes https://github.com/fluent/fluent-bit/issues/10796
----
=> opentelemetry: fix handling of numeric attributes (backport v4.0)

plugins/in_winevtlog/pack.c
This PR is backporting of https://github.com/fluent/fluent-bit/pull/10849.
----
**Testing**
----
=> in_winevtlog: Plug possible SEGV occurrence paths [Backport to 4.0]

src/flb_utils.c, tests/internal/utils.c
Backport of https://github.com/fluent/fluent-bit/pull/10889
----
=> utils: relax proxy URL parsing

src/flb_upstream.c
Backporting from https://github.com/fluent/fluent-bit/pull/10886.
----
**Testing**
----
=> upstream: Move clearing TLS session from prepare phase to destroy phase [Backport to 4.0]

include/fluent-bit/flb_plugin_proxy.h, src/flb_input.c, src/flb_plugin_proxy.c, src/proxy/go/go.c, src/proxy/go/go.h
These changes resolve the following issue: [#8464](https://github.com/fluent/fluent-bit/issues/8464)
----
**Testing**
```yaml
service:
pipeline:
inputs:
- name: go-input-plugin-with-context
config-key: config-value-1
tag: one
- name: go-input-plugin-with-context
config-key: config-value-1
tag: one
outputs:
- name: stdout
match: '*'
```
```go
package main
/*
*/
import "C"
import (
"fmt"
"log"
"time"
"unsafe"
"fluent-bit-input-plugin/input"
)
//export FLBPluginRegister
func FLBPluginRegister(def unsafe.Pointer) int {
return input.FLBPluginRegister(def, "go-input-plugin-with-context", "Go Input Plugin With …
```
=> proxy: go: add context for input methods

src/flb_input_chunk.c
Addresses https://github.com/fluent/fluent-bit/issues/10384
```
> bin/fluent-bit -i tail -p path=./logslurp -p mem_buf_limit=1m -o file -m '*' -H
Fluent Bit v4.0.4
______ _                  _    ______ _ _             ___  _____ 
|  ___| |                | |   | ___ (_) |           /   ||  _  |
| |_  | |_   _  ___ _ __ | |_  | |_/ /_| |_  __   __/ /| || |/' |
|  _| | | | | |/ _ \ '_ \| __| | ___ \ | __| \ \ / / /_| ||  /| |
| |   | | |_| |  __/ | | | |_  | |_/ / | |_   \ V /\___  |\ |_/ /
\_|   |_|\__,_|\___|_| |_|\__| \____/|_|\__|   \_/     |_(_)___/ 
[2025/07/11 08:47:05] [ info] [fluent bit] version=4.0.4, commit=a4e3d2b20d, pid=71384
[2025/07/11 …
```
=> input: update mem buf limit logging to include size info

src/opentelemetry/flb_opentelemetry_logs.c, tests/internal/data/opentelemetry/test_cases.json
Backporting of https://github.com/fluent/fluent-bit/pull/10956.
----
**Testing**
----
=> opentelemetry: allow empty strings for TraceID and SpanID (logs) [Backport to 4.0]

plugins/in_emitter/emitter.c, tests/runtime/in_forward.c
backporting of https://github.com/fluent/fluent-bit/pull/10950.
----
**Testing**
----
=> in_emitter: in_forward: Ensure ring buffer on threaded mode in emitter [Backport to 4.0]

plugins/in_docker/cgroup_v1.c, plugins/in_docker/cgroup_v2.c, plugins/in_docker/docker.c, plugins/in_docker/docker.h
Backporting of https://github.com/fluent/fluent-bit/pull/10972.
----
**Testing**
----
=> in_docker: add helper for container name parsing [Backport to 4.0]

include/fluent-bit/flb_config.h, plugins/in_calyptia_fleet/in_calyptia_fleet.c, plugins/in_calyptia_fleet/in_calyptia_fleet.h, plugins/in_dummy/in_dummy.c, plugins/in_dummy/in_dummy.h, src/flb_config.c, src/flb_reload.c, tests/internal/reload.c
Backporting of https://github.com/fluent/fluent-bit/pull/10869, https://github.com/fluent/fluent-bit/pull/10826, and https://github.com/fluent/fluent-bit/pull/10874.
----
**Testing**
----
=> reload: add a timeout mechanism and its based commits backporting [Backport to 4.0]

plugins/in_forward/fw.c, plugins/in_forward/fw.h, plugins/in_forward/fw_config.c, plugins/in_forward/fw_conn.c, tests/runtime/in_forward.c
Backporting of https://github.com/fluent/fluent-bit/pull/10973.
----
**Testing**
----
=> in_forward: Fix user authentication to align Fluentd's behavior [Backport to 4.0]

src/flb_router.c, tests/internal/router.c
Backporting of https://github.com/fluent/fluent-bit/pull/10976.
----
**Testing**
----
=> router: use memchr() and tag length for matching tags [Backport to 4.0]

src/flb_reload.c
Backporting of https://github.com/fluent/fluent-bit/pull/10968.
----
**Testing**
----
=> reload: refactor watchdog to be preemptable on windows. [Backport to 4.0]

plugins/in_elasticsearch/in_elasticsearch.h, plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c, plugins/in_elasticsearch/in_elasticsearch_config.c, plugins/in_http/http.h, plugins/in_http/http_config.c, plugins/in_http/http_prot.c, plugins/in_splunk/splunk.c, plugins/in_splunk/splunk.h, plugins/in_splunk/splunk_config.c, plugins/in_splunk/splunk_prot.c
Backporting of https://github.com/fluent/fluent-bit/pull/10967.
Still WIP. Needed to backport in_http related stuffs.
----
**Testing**
----
=> in_http: in_splunk: in_elasticsearch: fix tag_key lookup [Backport to 4.0]
